### ISSUE TITLE
Avoid sorting routes by default

### ISSUE THREAD

**Issue by Kouty** [nuxt-modules/i18n#1001]
### Is your feature request related to a problem? Please describe.
I need to localize my routes and keep the routes order.
More specifically I use 2 regex expressions, and I need one regex path to be evaluated before the other.
``` 
'_country/products/filters/index': {
    it: '/:country/prodotti/:category(.*)?/filtri',
    en: '/:country/products/:category(.*)?/filters',
  },
  '_country/products/index': {
    it: '/:country/prodotti/:category(.*)?',
    en: '/:country/products/:category(.*)?',
  },
```
(parsePages: false)

May be we can avoid ordering routes, or at least not by default.

### Describe the solution you'd like
https://github.com/nuxt-community/i18n-module/blob/master/src/helpers/routes.js#L153
```
try {
    const { sortRoutes } = require('@nuxt/utils')
    localizedRoutes = sortRoutes(localizedRoutes)
  } catch (error) {
    // Ignore
  }
```
Add something like
`if(pageOptions.sortRoutes) {....`

In this way I can define the routes order in `extendRoutes(...)` method of nuxt.config.js file.

### Describe alternatives you've considered
Without the possibility to avoid routes sorting, I need to write a custom plugin to reorder routes after your sorting.

**Comment by rchl** [comment]
Here are some relevant comments about that: https://github.com/nuxt-community/i18n-module/pull/904

As I said, I'd prefer that the sorting function from Nuxt covers those cases properly but I'm willing to accept PR that adds an option for toggling sorting.

**Comment by Kouty** [comment]
Probably I am misunderstanding something.
My question is: "Why is nuxt-i18n module sorting routes?"

In my opinion sorting routes is a project configuration, and nuxt-i18n should not be opinionated about sorting. It should keep the order of the routes array provided by the developers configuration. Is there any reason for the code lines below?
```
try {
    const { sortRoutes } = require('@nuxt/utils')
    localizedRoutes = sortRoutes(localizedRoutes)
  } catch (error) {
    // Ignore
  }
```

I am proposing an option to tell nuxt-i18n if to sort or not, because removing the sorting now may be considered as a breaking change.

UPDATE:
Just read:
"But I'd argue that when using this module sorting is almost mandatory since without it you need to order locale in a certain way for all to be accessible. It's not obvious and difficult to explain.

Would fixing the issue with sortRoutes not fix your problem? If it would then I'd prefer that."

I do not completely understand what the bug is in sortRoutes, since it sorts the routes (and so it cannot keep routes order as defined in extendRoutes(...)).

Anyway, if you think that "an option for toggling sorting" is acceptable, I can create the PR.
Alternative "Will adding a custom sort function to nuxt-i18n configuration make sense?"
