### ISSUE TITLE
Dynamic pages generates wrong url with sub path

### ISSUE THREAD

**Issue by do-web** [nuxt-modules/i18n#1002]
### Version
nuxt-i18n: lastest
nuxt: latest

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [] spa

### Steps to reproduce
Create a link with localePath({name: 'slug', params:{slug: 'path-1/path-2'}})

### What is Expected?

Generated url should be 

http://localhost:3000/path-1/path-2

### What is actually happening?

If i create a link to a dynmaic page with a sub directory the generated url is wrong:

page.slug = 'path-1/path-2';

localePath({name: 'slug', params:{slug: page.slug}})

Generated url is 

http://localhost:3000/path-1%2Fpath-2

**Comment by rchl** [comment]
This behavior is specific to VueRouter and not this module.

See https://codesandbox.io/s/nuxt-dynamic-route-lsqvm?file=/pages/_slug.vue which reproduces without using this module.
