### ISSUE TITLE
is there support for runtimeConfig?

### ISSUE THREAD

**Issue by TBigwell** [nuxt-modules/i18n#1007]
Hi, i have a question about the module, is it possible to use runtimeConfig to load in language locales and translations. I would like to achieve something similar like gtm-module has, that was added during its last version update (https://github.com/nuxt-community/gtm-module/blob/master/CHANGELOG.md  module: add support for runtimeConfig (#53) (2bc1735))

Testing right now shows that whatever is given at build time is also still present at deploy, it does not use the environmental variables given at deploy. 

Thank you for your time :)

**Comment by rchl** [comment]
The main functionality depends on generating the routes in a certain way and this can only be done at build time. So unless there is some major refactoring to switch away from that approach (which I'm not even sure would be possible), this module can't use runtime config for its configuration.
