### ISSUE TITLE
dynamic addRoutes in plugin beforeEach hook

### ISSUE THREAD

**Issue by onward-web** [nuxt-modules/i18n#1011]
I have problem with “dynamic addRoutes in plugin afterEach hook”
This is very interesting, since it allows you to implement almost any url, for example, from the root "/" can be
/category_slug
/post_slug
/other_slug

My part of config 
module.exports = {
 ssr: true,
 mode: 'universal',
	...(!isDev && {
	modern: 'client'
 }),
	  .. 
 plugins: [
	'~/plugins/route'],
}

plugins/route.js

function interopDefault(promise) {
  return promise.then(m => m.default || m);
}

export default ({ app, router, routeres}) => {
  app.router.beforeEach((to, from, next) => {
  
  app.$axios.get('/seo/find_by_slug', {
	  params: {
		slug: to.path,
		locale: app.i18n.locale
	  }
	})
  .then(function (response) {
	// response.data.view  maybe category, post
	let dynamicView =  () => interopDefault(import('@/pages/'+response.data.view+'.vue'));
    app.router.addRoutes([
    {
       path: to.path,
       component: dynamicView
	}
    ]);
    app.context.next(to.path);
  })
  .catch(function (error) {
    console.log(error);
  });	
  })
}

When I disable ssr (ssr: false), it is work fine, but when I set “ssr: true” return 404 error "This page could not be found"

### Versions

- nuxt:  2.14.7 
- nuxt-i18n: "6.15.4"

**Comment by rchl** [comment]
Sorry but I don't have time to investigate your issue that doesn't seem to be directly related to nuxt-i18n.

Try to make it work without first nuxt-i18n. If it does, create a simple reproduction project that specifies clearly the problem you are having.
