### ISSUE TITLE
MessageFunctions missing from messages

### ISSUE THREAD

**Issue by amrindersaini** [nuxt-modules/i18n#1013]
### Version
nuxt-i18n: 6.16.0
nuxt: 2.14.12

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [x] spa

### Reproduction Link

https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-mi0wk?file=/nuxt.config.js:1013-1074

### Steps to reproduce
Add a MessageFunction to messages and try to use it on a page. It's unavailable.

Did some digging and found out that functions were not being copied to options.js after nuxt build.

### What is Expected?
vue-i18n supports Named Formatting, in which we can use a function which returns a string. 
Here's the link to the docs - https://kazupon.github.io/vue-i18n/guide/messages.html#named-formatting

Expected behaviour is that the function is available and can be called for use.
### What is actually happening?
The MessageFunction is missing
 WARN  [vue-i18n] Value of key 'greeting' is not a string or function !

**Comment by rchl** [comment]
See the infobox on https://i18n.nuxtjs.org/options-reference#vuei18n . If you are using functions for vueI18n options, you need to use an external configuration file.

**Comment by amrindersaini** [comment]
Worked like a charm. Thanks for the quick response :)
