### ISSUE TITLE
Browser language redirection after rendering

### ISSUE THREAD

**Issue by daishizenSensei** [nuxt-modules/i18n#1017]
Hello everyone,

We run an e-commerce Nuxt project with internationalization (language & currencies), and we have an issue with browser redirection. The site is www.warenghem.com

When page are loading in root, there is :
1. loading www.warenghem.com
2. rendering of the page
3. redirection to language path
4. rendering of the translated page

We're pretty sure that we have the right configuration in nuxt.config (see below). With prefix strategy.
How can we remove the step 2, and make redirection earlier in the loading process?

Thanks a lot!

In nuxt.config we have  : 
`  i18n: {
    strategy: 'prefix',
    baseUrl: 'https://www.warenghem.com',
    seo: false,
    lazy: true,
    vueI18nLoader: true,
    langDir: 'locales/',
    defaultLocale: 'fr-FR',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      cookieSecure: false,
      cookieDomain: null,
      alwaysRedirect: true,
      onlyOnRoot: true,
      cookieCrossOrigin: false,
    },
    vueI18n: {
      messages: {
        fr: require('./locales/fr-fr.json'),
        en: require('./locales/en-us.json'),
      },
    },
    locales: [
      {
        code: 'fr-FR',
        iso: 'fr-FR',
        name: 'Français',
        langFile:require('./locales/fr-fr.json')
      },
      {
        code: 'en-GB',
        iso: 'en-GB',
        name: 'English',
        langFile:require('./locales/en-us.json')
      },
      {
        code: 'en-US',
        iso: 'en-US',
        name: 'English',
        langFile:require('./locales/en-us.json')
      },
      {
        code: 'fr-CA',
        iso: 'fr-CA',
        name: 'Français',
        langFile:require('./locales/fr-fr.json')
      },
      {
        code: 'en-CA',
        iso: 'en-CA',
        name: 'English',
        langFile:require('./locales/en-us.json')
      },
      {
        code: 'fr-CH',
        iso: 'fr-CH',
        name: 'English',
        langFile:require('./locales/fr-fr.json')
      },
      {
        code: 'en',
        iso: 'en',
        name: 'English',
        langFile:require('./locales/en-us.json')
      },
    ],
  },`

**Comment by rchl** [comment]
Your pages are statically generated or running on a node server? If the former then this is https://github.com/nuxt-community/i18n-module/issues/895.

**Comment by daishizenSensei** [comment]
Statically generated, thanks. By the way, in documentation on "local list" section, it's write that we can "any custom property set on the object will be exposed at runtime. This can be used, for example, to define the language name for the purpose of using it in a language selector on the page."

But how we can fetch language name with i18n, nothing appear in their documentation. We tried {{$i18n.locale.name}} to fetch current local name, but it doesn't work.

I also tried {{$i18n.localeProperties.name}}

**Comment by rchl** [comment]
> I also tried {{$i18n.localeProperties.name}}

This will work once the `localeProperties` change is released. It was just integrated today but not released yet.

**Comment by daishizenSensei** [comment]
That's work now :). Do you know if it's possible to add image (like a flag) in nuxt.config? It's seems not working.

**Comment by rchl** [comment]
Maybe have a directory like `~/assets/lang_flags/` and store flag images using a `[code].png` convention.

Then you should be able to refer to those from the template using:
 ```
<img :src="require(`~/assets/lang_flags/${$i18n.localeProperties.code}.png`)">
```

**Comment by daishizenSensei** [comment]
Yes I forgot to use static folder. Thank you.
Can't wait to have a solution for this non UX redirection behavior...

**Comment by rchl** [comment]
Duplicate of #895
