### ISSUE TITLE
Revert to detecting browser's language after manually setting a locale?

### ISSUE THREAD

**Issue by ThibaultNocchi** [nuxt-modules/i18n#1018]
Hello everyone,

In my application I'd like to have my locale switch have options like this: "English", "French", "Spanish"... and "Auto" which would revert the application to the default i18n state, where it detects the user's browser's locale.

I've tried using `seLocale()` or `setLocale('')` but without luck.

Is it even possible without deleting the cookie and refreshing? Thanks!

**Comment by rchl** [comment]
I think `$i18n.setLocaleCookie('')` should work.

**Comment by ThibaultNocchi** [comment]
It works partially. If I set the cookie to `''`, the current locale isn't changed. It is only changed after routing to another page.

Example:
```javascript
window.$nuxt.$i18n.locale // 'de'
window.$nuxt.$i18n.setLocaleCookie('')
window.$nuxt.$i18n.locale // 'de'
// I click on a link to get to a new page
window.$nuxt.$i18n.locale // 'fr'
```

As I understood, locales are updated when browsing with nuxt-i18n, and it seems to be the case here. Is there maybe a way to force refresh? Thanks!

**Comment by rchl** [comment]
Maybe try `$router.go()` to "reload" the page. Alternatively you could do a hard-reload with `location.reload()`.

**Comment by ThibaultNocchi** [comment]
Thanks, but it's not really ideal. Maybe I can try to look around see if I can add a PR for this?

**Comment by rchl** [comment]
`getBrowserLocale()` API released in https://github.com/nuxt-community/i18n-module/releases/tag/v6.18.0

**Comment by ThibaultNocchi** [comment]
Thanks for the heads up! Have a nice day
