### ISSUE TITLE
Date and time localization ignores locale on nuxt generate

### ISSUE THREAD

**Issue by jollycic** [nuxt-modules/i18n#1028]
### Version
nuxt-i18n: 6.18.0
nuxt: 2.14.6

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt-i18n configuration
```
  i18n: {
    lazy: false,
    locales: ['en','es','fr','it'],
    strategy: 'prefix',
    defaultLocale: 'it',
    vueI18n: {
      fallbackLocale: 'it',
      messages: {
        en: { hello: 'Hello' },
        es: { hello: 'Hola' },
        fr: { hello: 'Salut' },
        it: { hello: 'Ciao' }
      },
      dateTimeFormats: {
        en: { long: { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' } },
        es: { long: { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' } },
        fr: { long: { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' } },
        it: { long: { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' } }
      }
    }
  }
```

### Reproduction Link
https://github.com/jollycic/test-nuxt-i18n-date-localization

### Steps to reproduce
1. Clone the repo and ``npm install`;
2. Run ``nuxt generate`` and wait for the task to complete;
3. Check ``~/dist/en/index.html``, ``~/dist/es/index.html``, ``~/dist/fr/index.html``, and ``~/dist/it/index.html``

### What is Expected?
Both the message and the date should be localized accordingly on each page.

### What is actually happening?
Only the message appears to be localized with the correct locale, while the date is always localized in English, no matter what locale has been set as default or fallback.

This behavior is inconsistent with the client side, where both the message and the date are localized correctly. This can be noticed when running in dev mode`. Does this hint to a possible concurrency issue?

I don’t know if this is a known or expected behavior, or if I have done anything wrong with the module configuration, in which case I apologize.

**Comment by rchl** [comment]
`vue-i18n` implements `$d` using the `Intl.DateTimeFormat` Javascript API and that API only supports the EN locale in Node 12 and is not supported at all in lower Node versions. So you'd need to use at least Node 13 (ideally 14) to have proper support for that API on the server-side.

**Comment by jollycic** [comment]
Thank you very much, I wasn’t aware of this.
