### ISSUE TITLE
How to use localeRoute in vuex

### ISSUE THREAD

**Issue by udje** [nuxt-modules/i18n#1031]
How to use localeRoute in vuex store?

`this.$router.push(this.localeRoute({ name: "home" }))`

**Comment by rchl** [comment]
`nuxt-i18n` only injects those extra functions on the `app` object so `this.app.localePath` should work.

(Standard `inject` mechanism would inject automatically in all contexts, which would make it available, but it would add a `$` prefix to the function name. The alternative is to of course to do it manually. So I'd say that it should still be fixed/added, one way or another.)
