### ISSUE TITLE
"lazy" option is not working, even following what the doc requests

### ISSUE THREAD

**Issue by rafaoliverce** [nuxt-modules/i18n#1032]
### Version
nuxt-i18n: 6.15.4
nuxt: 2.14.9

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal

### Nuxt-i18n configuration
```
i18n: {
    locales: [
      { name: 'English', code: 'en', iso: 'en-US', file: 'en-US.js' }
    ],
    langDir: 'lang/',
    defaultLocale: 'en',
    lazy: true,
    vuex: false,
    strategy: 'no_prefix',
    detectBrowserLanguage: false,
    seo: false
  }
```

### What is actually happening?
I thought the "lazy" feature was working, but after inspecting the source-code on the production website, I'm seeing translation texts from other routes on every route. So the "lazy" feature is not working.

**Comment by rchl** [comment]
> I thought the "lazy" feature was working, but after inspecting the source-code on the production website, I'm seeing translation texts from other routes on every route.

This is not how `lazy` works.

> Loading locale messages lazily means that only messages for currently used locale (and potentially of the default locale, if different from current locale) will be loaded on page loading.

https://i18n.nuxtjs.org/options-reference#lazy
