### ISSUE TITLE
[DOCS] Explicitly state that to use external files `lazyLoad` MUST be set to `true`

### ISSUE THREAD

**Issue by sushi2all** [nuxt-modules/i18n#1033]
### Is your feature request related to a problem? Please describe.
I was getting a headache trying to figure out why the site wouldn't load the messages, until I tried to set `lazyLoad` to `true` and it worked (and broke again when setting it to `false`).

### Describe the solution you'd like
Don't know if this behavior is intended. I don't expect it to change, but the documentation should state it more clearly if it is supposed to work this way. 

Currently the [docs](https://i18n.nuxtjs.org/lazy-load-translations/) mention external files only in case of lazy loading. I expected that the files would still be imported even without lazy loading, because nowhere it says that lazy loading is the ONLY way to use external files.

I personally don't have any issue with lazy loading the messages, but on the other hand I wonder if there's any case for wanting to load all translations right away. I don't see why it should not work, but it's not a request.

I would expect instead that the documentation addressed the topic of using external files directly, maybe with a specific paragraph somewhere regardless of lazy loading.

### Describe alternatives you've considered
NA

### Additional context
Willing to submit PR but I'm new to the project and didn't want to mess up the structure of the docs without asking for feedback and suggestions first.

**Comment by rchl** [comment]
Updated various places in documentation to hopefully make this more clear.
