### ISSUE TITLE
Can i have you call to function in translation? 

### ISSUE THREAD

**Issue by lwswnnscrm** [nuxt-modules/i18n#1035]
Hi, in my case i need use call function in my translation, example i have text ```You can by this product from localPrice(15)```, and then in template i need use this ```$t('product.by_price', { localPrice: (params) => return 15* localRate })```. I have not found anything similar in the documentation. Maybe have is some solution to this problem? The main thing i need params in translation and use this param in function i18n.t$. Can you help me?

**Comment by rchl** [comment]
This should be possible to implement with Message Function: https://kazupon.github.io/vue-i18n/guide/messages.html#message-function

**Comment by lwswnnscrm** [comment]
This is a little different, i need have opportunity to give props from template and from message. Exapmle: 
```
en: { 
  getLocal: ctx => ctx.price * ctx.rate,
  price: 'you can buy this item from @:price.getLocal({ price: 10}),
}
```
and then in template 
```$t('price', { rate: 1.3 })```
and in result have ``` you can buy this item from 13```. In message function i can drop props from massage and from template to 1 function. Maybe have other solution?

**Comment by rchl** [comment]
Maybe I'm not getting something but you have examples like this one in the linked documentation:

```vue
<p>{{ $t('greeting', { name: 'DIO' }) }}</p>
```

and then you can refer to that `name` variable from the string with:

```js
greeting: (ctx) => `hello, ${ctx.named('name')}!`
```

**Comment by lwswnnscrm** [comment]
Its a little different, but work in my case. Thank you for help.
