### ISSUE TITLE
Nuxt Static generation translated pages do not use payload

### ISSUE THREAD

**Issue by sven-ra** [nuxt-modules/i18n#1037]
### Version
nuxt-i18n: 6.18.0
nuxt-edge: 2.15.0-26854632.498f8553

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] static

### Nuxt-i18n configuration
```
{
 target: 'static'
}
```
```
i18n: {
        detectBrowserLanguage: true,
        locales: [
          { code: 'et', iso: 'est', name: 'ET', full_name: 'Eesti keeles' },
          {
            code: 'evk',
            iso: 'est',
            name: 'EVK',
            full_name: 'Eesti viipekeel'
          },
          { code: 'ru', iso: 'rus', name: 'RU', full_name: 'По Pусски' },
          { code: 'en', iso: 'eng', name: 'EN', full_name: 'In English' }
        ],
        defaultLocale: 'et',
        vueI18n: {
          fallbackLocale: 'et',
          messages: {
            en: require('./static/translations/strings-en.json'),
            et: require('./static/translations/strings-et.json'),
            evk: require('./static/translations/strings-et.json'),
            ru: require('./static/translations/strings-ru.json')
          }
        },
        parsePages: false,
        pages: {
          '_exhibition/index': {
            et: '/:exhibition',
            evk: '/:exhibition',
            en: '/:exhibition',
            ru: '/:exhibition'
          },
          '_exhibition/_parent/index': {
            et: '/:exhibition/:parent',
            evk: '/:exhibition/:parent',
            en: '/:exhibition/:parent',
            ru: '/:exhibition/:parent'
          },
          '_exhibition/_parent/_child': {
            et: '/:exhibition/:parent/:child',
            evk: '/:exhibition/:parent/:child',
            en: '/:exhibition/:parent/:child',
            ru: '/:exhibition/:parent/:child'
          }
        }
      }
```

### Steps to reproduce
run `nuxt generate && nuxt start` to generate and launch full static generated site.

### What is Expected?
All the generated pages to get their data from the payload.

### What is actually happening?
The site boots up but only the default language pages are fully static. Translated pages all fetch data from the API. nuxtServerInit does not fire at all thus breaking the site (I have crucial API requests there). When I browse the generated files I can see correct payload and store files for all the languages. The just aren't used by the app.

**Comment by rchl** [comment]
Can you also include the relevant part of the component that fetches the payload?
Or ideally a repro repo.

**Comment by sven-ra** [comment]
> Can you also include the relevant part of the component that fetches the payload?
> Or ideally a repro repo.


I have a function to handle all the API requests
```
export default async function fetchApi({ path, params }) {
  const baseUrl = process.env.BASE_URL
  const queryParams = params ? new URLSearchParams(params) : ''

  const data = await fetch(`${baseUrl}${path}?${queryParams}`).then((res) => {
    if (!res.ok) {
      return null
    }
    return res.json()
  })

  return data
}
```

And I use asyncData to fetch the data. Pretty straight forward and it works fine for the default language.
```
async asyncData({ app }) {
    const data = await fetchApi({
      path: 'pages/front-page',
      params: {
        lang: app.i18n.locale === 'evk' ? 'et' : app.i18n.locale,
        acf: true
      }
    })

    return {
      data
    }
}
```

**Comment by sven-ra** [comment]
Okay I just found out that with a trailing slash, it works as expected.
The problem is: switchLocalePath points to another language without a trailing slash.

**Comment by rchl** [comment]
You might have to create a reproducible repo.
Typically the payload should also be mapped to a path without the trailing slash so it should work. There seems to be something special about your project that makes this not work.

**Comment by sven-ra** [comment]
I tried this out in other projects and the problem persists.
I made a small [sandbox](https://codesandbox.io/s/friendly-brook-o7n78) where you can see this happening.

In the browser you can try to go straight to /ru and it will give an error, since the `nuxtServerInit` is not executed.
But if you go to /ru/ it works as expected, since it is fetching the data from the payload.

**Comment by rchl** [comment]
Trying to `yarn generate` this project fails with an error.

One obvious issue is that the `fetchApi` doesn't generate proper URLs (it tries to fetch from `http://localhost:3000site-data?lang=en` which is missing a slash after the domain).

**Comment by sven-ra** [comment]
> Trying to `yarn generate` this project fails with an error.
> 
> One obvious issue is that the `fetchApi` doesn't generate proper URLs (it tries to fetch from `http://localhost:3000site-data?lang=en` which is missing a slash after the domain).

The sandbox worked in incognito for me tho. You should be able to see the bug. But if you want to fork this I will have to send you the API url and whitelist your domain.

**Comment by rchl** [comment]
Ideally, the repro would just include a simple server middleware that would be used by the fetch.

**Comment by sven-ra** [comment]
here is a [sandbox](https://codesandbox.io/s/friendly-brook-o7n78) that uses a simple server middleware.
If you run "yarn generate && yarn start" you can see that it uses the payloads while using the navigation but if you go directly to /ru without the trailing slash for example it will run into an error. If you run this locally or on node server the fetch will never be made.

**Comment by rchl** [comment]
Thanks for providing a complete example. :)

I've figured out that it's because when going directly to `/en` the Nuxt static server doesn't serve the generated `en/index.html` file but instead serves the placeholder file `200.html`.

When using a different static server like `http-server` it does a client-side redirect from `/en` to `/en/` and it works (although the slash is added so in theory that could cause some issues and inconsistencies).

I'm starting to realize that for static-serving, the [`router.trailingSlash: true`](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#trailingslash) option might be a requirement to cover cases light that. ~~That said, this is still failing with `router.trailingSlash: true`. The https://github.com/nuxt/nuxt.js/pull/8489 was supposed to help with that (not released at the time of writing) but it seems like the current nuxt-edge breaks it even more instead...~~ (EDIT: See my next comment).

So the situation is a bit messy right now but hopefully, it will be resolved soon. The trailingSlash: true will still be required though.

**Comment by rchl** [comment]
Actually, I've rechecked with the current `nuxt-edge` (v2.15.0-26856070.08350560) and `router.trailingSlash: true` and it seems to be working.

See https://codesandbox.io/s/prod-sun-ou6i7 (of course export it and run `yarn generate && yarn start`).

**Comment by supachailllpay** [comment]
I agree that using `router.trailingSlash: true` solve the problem on nuxt server and can prevent the same problem to other static server. But it should not be required or enforced to use because after all `/en` and `/en/` are different things, IMO.

Instead I think this should be fix by nuxt. See https://github.com/nuxt/nuxt.js/issues/8684#issue-792668369.

**Comment by rchl** [comment]
I've tried again with updated dependencies (updated https://codesandbox.io/s/prod-sun-ou6i7) and it appears to work now with built-in Nuxt static server even without `trailingSlash: true`.
