### ISSUE TITLE
Typescript types not working correctly

### ISSUE THREAD

**Issue by Machine-Maker** [nuxt-modules/i18n#1038]
So i've added `nuxt-i18n` to my tsconfig.json
```json
"types": [
      "@nuxt/types",
      "@types/node",
      "@nuxtjs/axios",
      "cookie-universal-nuxt",
      "@nuxtjs/vuetify",
      "nuxt-i18n"
    ],
```

EDIT: so I got it to work, but only by manually doing it (see below). I just threw that at the top of `nuxt.config.ts` and it worked, but I still think I'm missing something.
```javascript

declare module 'vue/types/vue' {
    interface Vue {
        readonly $i18n: VueI18n & IVueI18n;
        $t: typeof VueI18n.prototype.t;
        $tc: typeof VueI18n.prototype.tc;
        $te: typeof VueI18n.prototype.te;
        $d: typeof VueI18n.prototype.d;
        $n: typeof VueI18n.prototype.n;
    }
}
```
but typescript still isn't showing $t or $i18n in components.

**Comment by rchl** [comment]
Those that you've added yourself are already provided through `vue-i18n` (https://github.com/kazupon/vue-i18n/blob/6c0c3b06fa7e4ad2cf70f7032a89c25eb709fd77/types/index.d.ts#L259-L268) so shouldn't be necessary.

You'd probably need to provide a project that reproduces if you want me to analyze it.

**Comment by Machine-Maker** [comment]
You can see the exact project [here](https://github.com/PaperMC/Hangar/tree/nuxt-frontend). Just clone it and look in the `/frontend` folder. Just comment out [these](https://github.com/PaperMC/Hangar/blob/nuxt-frontend/frontend/nuxt.config.ts#L9) lines.

**Comment by Machine-Maker** [comment]
nah, I figured it out. somehow I had installed it in the project root rather than the frontend/ folder.
