### ISSUE TITLE
Render an app with externally loaded translations

### ISSUE THREAD

**Issue by Rozkalns** [nuxt-modules/i18n#1042]
```js
// ~/plugins/i18n.js
export default function ({ app }) {
  app.i18n.loadedLanguages = []

  app.router.beforeEach((to, from, next) => {
    loadLanguageAsync(app.i18n.locale).then(() => next())
    next() // still debugging this
  })

  async function loadLanguageAsync (lang) {
    // If the language was already loaded
    if (app.i18n.loadedLanguages.includes(lang)) {
      return Promise.resolve()
    }

    const { data } = await app.$axios.get('translate', { params: { lang } })
    app.i18n.loadedLanguages.push(lang)
    app.i18n.setLocaleMessage(lang, data.data)
    return Promise.resolve()
  }
}
```

```js
// ~/nuxt.config.js
export default {
  plugins: [
    { src: '~/plugins/i18n.js' }
  ],
  modules: [
    '@nuxtjs/axios',
    'nuxt-i18n'
  ],
  i18n: {
    locales: [
      { code: 'en', iso: 'en-US', name: 'English' },
      { code: 'lv', iso: 'lv-LV', name: 'Latviešu' }
    ],
    defaultLocale: 'en',
    strategy: 'prefix',
    seo: false,
    vueI18n: {
      fallbackLocale: 'en',
      messages: {}
    }
  },
}
```

My main goal would be to render the page with the correct translations.
I might add sligh delay while the initial language file loads or whatever, but currently this does not work well.
The thing that I would like to see is that I dont have to manage translations on frontend side, nor on backend. At the moment I keep my translations in database behind backend.

I know that couple of years ago I had this thing working, but that was on Vue, and I haven't written too much frontends till back then.

I really would like to hear some suggestions or hints how to achieve these things.

Thanks!

**Comment by rchl** [comment]
You should look into using `lazy` option with `file` property pointing to a javascript file. You shouldn't need a separate plugin file then as all the logic could be contained within the function that this javascript file would export.

At least that should be sufficient if you are not loading locales per-page but only per-locale. It seems like you are loading per-locale, based on your plugin's code.

**Comment by Rozkalns** [comment]
@rchl actually I figured so far, but only issue is that I am not able to understand why $axios is not available in context therefore I get the error that 'get is not a function on undefined' or smth.
At the moment I am not at the computer so I can't copy the thing I managed to make, but can you explain how to get axios there?
Tried importing axios, but it didn't have all options that already set into nuxt config.

**Comment by rchl** [comment]
You must register the axios module after this module to make axios available.

**Comment by Rozkalns** [comment]
@rchl aaaaah, thats the issue... :D 
I will definetly try that

**Comment by Rozkalns** [comment]
```js
// nuxt.config.js
export default {
  modules: [
    'nuxt-i18n',
    '@nuxtjs/axios'
  ],
  i18n: {
    lazy: true,
    langDir: 'lang/',
    locales: [
      { code: 'en', iso: 'en-US', name: 'English', file: 'en.js' },
      { code: 'lv', iso: 'lv-LV', name: 'Latviešu', file: 'lv.js' }
    ],
    defaultLocale: 'en',
    strategy: 'prefix',
    seo: false
  }
}```

```js
// ~/lang/en.js
// ~/lang/lv.js
export default async ({ app }, locale) => {
  const { data } = await app.$axios.get('translate', { params: { locale } })
  return data.data
}
```

it works like a charm!

Thanks @rchl for helping out!
