### ISSUE TITLE
$axios undefined on context (lazy loading)

### ISSUE THREAD

**Issue by manvankaliber** [nuxt-modules/i18n#1045]
I use both the nuxt i18n module and the nuxt axios module. My localization dictionaries are provided by our external API (lazy loaded). I've also configured the nuxt axios module with a baseURL, default parameters and headers.

```
    const { data } = await context.$axios.$get( `http://api.com/language/${locale}.json` )
    return data
```

doing this does not work as $axios is only added to the context later. Axios will return as `undefined` Manually importing axios is not ideal as I will lose all my default configurations.

How can I use the nuxt axios module in the context without setting a timeout or using relatively ugly hacks?

**Comment by rchl** [comment]
The `@nuxtjs/axios` module must be registered **after** the `nuxt-i18n` module for this to work.

**Comment by manvankaliber** [comment]
This does seem to fix it. Weird. I expected that if I loaded `@nuxtjs/axios` module **before** the `nuxt-18n` module it would do the trick. Thank you for the help!

for people in the future; following the instructions above by @rchl, $axios will be available on `context.app`

**Comment by rchl** [comment]
This has to do with the order the plugins added from modules are registered in Nuxt.

I've just added a note about that at the bottom of https://i18n.nuxtjs.org/lazy-load-translations/ since you are not the first person to ask that question.
