### ISSUE TITLE
On language switch always error RangeError: Maximum call stack size exceeded no idea why ?

### ISSUE THREAD

**Issue by ghost** [nuxt-modules/i18n#1053]
Error message: `client.js?06a0:96 RangeError: Maximum call stack size exceeded
    at Observer.toString (<anonymous>)
    at klona (index.js?3aed:11)
    at set (index.js?3aed:2)
    at klona (index.js?3aed:48)
    at set (index.js?3aed:2)
    at klona (index.js?3aed:48)
    at set (index.js?3aed:2)
    at klona (index.js?3aed:48)
    at set (index.js?3aed:2)
    at klona (index.js?3aed:48)`

src code:

 ```
onChange(locale) {
        var language = locale.code.toLocaleLowerCase();
        this.$i18n.setLocale(language);
        this.$router.replace(this.switchLocalePath(language));
      },

```

**Comment by rchl** [comment]
Why are you trying to `setLocale` from locale change event?

**Comment by ghost** [comment]
> Why are you trying to `setLocale` from locale change event?

Hi rchl because i have a vue select element in the navbar which listens onChange events months this was working absolutely ok, but since the last update it breaks with the error callstack size, though the cookie is set ok so the language switch works on the cookie but some how not routing correct, i have no idea ...

**Comment by ghost** [comment]
removed onChange for nuxt-link now it works

**Comment by rchl** [comment]
Also a note that `this.$router.replace(this.switchLocalePath(language));` call seems redundant because `setLocale` should change the route itself, if it's necessary.

**Comment by nelsonlarocca** [comment]
hi !
I'm just using this.$i18n.setLocale(language);
and it works 100% fine only IF "nuxt-i18n": "^6.17.0",
any other version after that drops the error. Maybe not the first time but randomly after repeating some times the lang switching

![image](https://user-images.githubusercontent.com/30134532/108841887-4e558c80-758d-11eb-88f2-0a6b3d1c106d.png)

any help ?

**Comment by rchl** [comment]
Can't help without access to the broken repo.
