### ISSUE TITLE
Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by javimosch** [nuxt-modules/i18n#1058]
### Version
nuxt-i18n: ^6.20.0
nuxt: ^2.0.0

### Nuxt configuration
 - [X] server / ssr
 - [] spa

### Nuxt-i18n configuration

```
modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    // Doc: https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv',
    'nuxt-i18n',
  ],
  i18n: {
    locales: ['en', 'fr', 'es'],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          welcome: 'Welcome'
        },
        fr: {
          welcome: 'Bienvenue'
        },
        es: {
          welcome: 'Bienvenido'
        }
      }
    }
  },
```

### Steps to reproduce
Follows the basic usage guide using a custom express nuxt example:

### What is Expected?
Full page refresh loads the page fine

### What is actually happening?

Cannot read property 'install' of undefined
![Screenshot_20210209_214230](https://user-images.githubusercontent.com/12900508/107425981-f6943b80-6b1f-11eb-8a19-51d81deb241a.png)

**Comment by rchl** [comment]
Can you create a repo that reproduces? You could use https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-sty4f as a base.

The crashing line in the screenshot is a `Vue.use(VueI18n)` call where `VueI18n` is imported with `import VueI18n from 'vue-i18n'` so that's pretty basic stuff that should work unless there is something funky going on in your project.

**Comment by javimosch** [comment]
Before trying nuxt-18n, I tested vue-i18n-next which ask to install vue-i18n@next (last version).
Uninstalling vue-18n and installing with npm i --save vue-i18n (8.22.4) solves the problem.
https://github.com/kazupon/vue-i18n/tags

I noticed that vue-18n changed the maintainer and versions after 8.22.4 requires Vue 3. I suppose that was the issue.

Thanks.
