### ISSUE TITLE
strategy prefix static generation root redirect does not honor router base

### ISSUE THREAD

**Issue by zinsserzh** [nuxt-modules/i18n#1060]
### Version
nuxt-i18n: 6.20.0
nuxt: 2.14.12

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt-i18n configuration
```
  router: {
    base: '/nuxt/'
  },

  modules: [
    'nuxt-i18n'
  ],

  i18n: {
    locales: [
      { code: 'en', iso: 'en-US' },
      { code: 'fr', iso: 'fr-FR' },
    ],
    strategy: 'prefix',
    defaultLocale: 'en',
  },
```

### Steps to reproduce

```bash
npm init nuxt-app nuxt
cd nuxt
npm i nuxt-i18n
# Edit nuxt.config.js to include above config
npm run generate
mv dist nuxt
npx http-server
# Navigate to http://127.0.0.1:8080/nuxt/
```

### What is Expected?
Redirect to http://127.0.0.1:8080/nuxt/en

### What is actually happening?
Redirect to http://127.0.0.1:8080/en

### Comment
The redirect works fine with ssr mode `npm run build && npm run start` and dev mode `npm run dev`

**Comment by Mikaleb** [comment]
Bump, got the same problem
