### ISSUE TITLE
Nuxt@2.15.0 error - Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/i18n#1063]
### Version
nuxt-i18n: 6.20.0
nuxt: 2.15.0

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal

### Nuxt-i18n configuration
```
i18n: {
        locales: [...],
        defaultLocale: "en",
        vueI18nLoader: true
    }
```

### What is Expected?
Not sure where the issue lies and what could have changed since the previous version of Nuxt, but the description of the issue should be self explanatory about what is failing and where.

### What is actually happening?
Error when running npm run dev for Nuxt:
![image](https://user-images.githubusercontent.com/48835293/107943744-69247180-6f8d-11eb-81cf-d164d4907f88.png)

Result of console.log(config.module.rules) above failing line;
![image](https://user-images.githubusercontent.com/48835293/107943672-5316b100-6f8d-11eb-933b-f4c378802f23.png)

hooks.js logic which is looking for vue-loader when on the screenshot above there is an absolute path not equal to but **including** vue-loader:
![image](https://user-images.githubusercontent.com/48835293/107943884-9cff9700-6f8d-11eb-913f-35d7f7b8927a.png)

**Comment by rchl** [comment]
Fix released in https://github.com/nuxt-community/i18n-module/releases/tag/v6.20.1.
Thanks for reporting.
