### ISSUE TITLE
switchLocalePath and dynamic routes parameters

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt-modules/i18n#1066]
Hi,
I know there is a section dedicated to that in the docs but it doesn't seem to fit my needs.

First of all, here are the necessary files to understand my problem.

```js
// nuxt.config.js
export default {
//...
i18n: {
    strategy: "prefix",
    locales: [
      {
        code: "en",
        file: "en-US.js",
        name: "English"
      },
      {
        code: "es",
        file: "es-ES.js",
        name: "Español"
      },
      {
        code: "fr",
        file: "fr-FR.js",
        name: "Français"
      }
    ],
    lazy: true,
    langDir: "lang/",
    defaultLocale: "en"
  },
//...
}
```
```js
// lang/en-US.js
export default {
  header: {
    title: "Special characters"
  },
  content: {
    left: {
      title: "Sets",
      sets: [
        {
          name: "french",
          display: "French",
          slug: "french"
        },
        {
          name: "english",
          display: "English",
          slug: "english"
        }
      ]
    }
  }
};
```
The content is temporary and will be populated in the future with content from a strapi api.

So here's my problem: when I want to change the locale, the dynamic setting is not translated.
For example, I'm on _/en/french_ and I want the french version, so when I click on the change button, I would like to get _/fr/francais_. Instead, I get _/fr/french_.
To correct this, I tried to do a custom function:
```vue
// components/Header.vue
<script>
export default {
getSwitchPath(locale) {
      let slug = "";
      if (this.$route.params.set) {
        let i = this.$t("content.left.sets").findIndex(
          s => s.slug == this.$route.params.set
        );
        let localeSlug = this.$t(`content.left.sets[${i}].slug`, locale);
        slug = "/" + localeSlug;
      }
      return "/" + locale.code + slug;
    }
}
</script>
```
But since I use the lazy option, I can't get all the translations.

**Comment by rchl** [comment]
That would require https://github.com/nuxt-community/i18n-module/issues/740 to be implemented.
Then you would have to manually make sure that the locale is loaded before getting a translation.

But there is actually this feature also https://i18n.nuxtjs.org/lang-switcher#dynamic-route-parameters which seems like what would solve your use case.

**Comment by florian-lefebvre** [comment]
Is #740 planned to be implemented?

**Comment by rchl** [comment]
It's there to be implemented so yes. I don't know when I get time to do it though. Contributions are welcome.

But https://i18n.nuxtjs.org/lang-switcher#dynamic-route-parameters really seems like a better solution for your problem since it makes `switchLocalePath` and other APIs work correctly in this case.

**Comment by florian-lefebvre** [comment]
In the meantime, I disabled the lazy option and imported my files manually.
```js
import en from "./lang/en-US";
import es from "./lang/es-ES";
import fr from "./lang/fr-FR";

export default {
  i18n: {
    strategy: "prefix",
    locales: [
      {
        code: "en",
        // file: "en-US.js",
        name: "English"
      },
      {
        code: "es",
        // file: "es-ES.js",
        name: "Español"
      },
      {
        code: "fr",
        // file: "fr-FR.js",
        name: "Français"
      }
    ],
    // lazy: true,
    // langDir: "lang/",
    defaultLocale: "en",
    vueI18n: {
      fallbackLocale: "en",
      messages: { en, es, fr }
    }
  },
};

```
