### ISSUE TITLE
Infinite reload for nuxt static  "nuxt-i18n": "^6.20.2",

### ISSUE THREAD

**Issue by larstton** [nuxt-modules/i18n#1074]
When changed the `target` to `static `and `ssr` to `true`,  started a infinite reload of any page of the website. If I remove   `defaultLocale: en `the pages stops to reload but translations are not working. Is this a problem with il8n or with my routes?
    
       my config:
    
   ```
      i18n: {
    parsePages: false,
    locales: [
      {
        code: 'en',
        iso: 'en-GB',
        name: 'english',
        file: 'en.js',
      },
      {
        code: 'ro',
        iso: 'ro-RO',
        name: 'romanian',
        file: 'ro.js',
      },
    ],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'ro',
      messages: {
        ro: require('./lang/ro').default,
        en: require('./lang/en').default,
      },
    },
    lazy: true,
    langDir: 'lang/',
  },
```

My router:
```

    routes: [
      {
        path: '/',
        component: Index
      },
      {
        path: '/information/terms-and-service',
        component: Terms
      },
      {
        path: '/information/privacy-policy',
        component: Privacy
      },
      {
        path: '/information/refund-policy',
        component: Refund
      },
      {
        path: '/collections/:slug',
        component: CollectionItems,
      },
      {
        path: '/en/collections/:slug',
        component: CollectionItems,
      },
    ]
```

**Comment by larstton** [comment]
Looks like the infinite refresh is now only on the page:

 ```
   {
        path: '/collections',
        component: Collections,
      },
```

I have an identic page /tags and tags are working fine. 

Looks like the module is changing the language continuously itself.

**Comment by rchl** [comment]
This can depend on where you deploy or how you start the static server so it's hard to help without knowing exactly what you are doing.

But my guess would be that it has something to do with trailing slashes.

You could try setting `router { trailingSlash: true }` in nuxt.config.js.

**Comment by larstton** [comment]
Both cases I was getting the same error. I was generating the project with `nuxt generate` and then ` nuxt start ` and for dev purpose I was generating using `npm run dev `. After spending 2-3 hours trying to fix the problem I understood that the issue was happening only on `/collections/:slug ` page. 

After adding `router { trailingSlash: true }` the problem was fixed. 

Thank you. 


**EDIT** 

This solution caused a major bug that we were not able to identify right away. All clients from google adwords were getting infinite reload error because they were accessing the website via the link:

`siteurl?gclid=SAIDJOAI1231I23XAIJ123123 `

and the script was trying to add a trailing slash after google clid which was causing infinite reload.

**Comment by larstton** [comment]
Do you have any ideas how this bug with trailing slashes could be fixed? Tried fixing it with the most configurations from the module documentation, nothing helps.

**Comment by rchl** [comment]
If you create a reproducible case then I can look and try to fix it. The case of slash being added after query, I mean.

**Comment by larstton** [comment]
Tried many attempts to create a sandbox but is not working there for some reason even on local everything is up and running after `npm install`

If you have time pull the project from here:

`https://github.com/snaix93/FlowerqueenFront`

Thank you  in advance.

**Comment by rchl** [comment]
Can you reproduce after updating your dependencies (nuxt, nuxt-i18n, etc.)? Basically, try after `npm up`.

**Comment by larstton** [comment]
This is true black magic! :D Everything works smoothly. 

Have you pushed an update to the package or `npm up` done the magic? 

The funniest thing for me is the fact that I have tried updating different packages but I have done it separately being scared that after `npm up `  everything will crash. 

Thank you for help! :)

**Comment by rchl** [comment]
There were various changes in nuxt-i18n that could affect that or it could be some trailing slashes work done in Nuxt. I'm not gonna spend time investigating that but happy it works. :)

**Comment by skourta** [comment]
Hello,
I have the same issue with "@nuxtjs/i18n": "^7.0.2".

**Comment by divine** [comment]
> Hello,
> I have the same issue with "@nuxtjs/i18n": "^7.0.2".

Hello,

and you've got a reproduction repo as well?

Thanks!

**Comment by skourta** [comment]
Nope not yet. I faced the problem while workin on my company's website. I could apply the workaround with the `router { trailingSlash: true }`.
I will try to make a reproducible repo on my free time.
