### ISSUE TITLE
Migration path for $nuxtI18nSeo()

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#1085]
As `$nuxtI18nSeo()` is deprecated now, what's the equivalent `$nuxtI18nHead()` expression?

I suspect it's `$nuxtI18nHead({ addSeoAttributes: true })`, correct? If so, that could be added to the documentation, I didn't find this information there.

**Comment by rchl** [comment]
Documentation was updated to mention only the non-deprecated method: https://i18n.nuxtjs.org/seo#improving-performance

**Comment by dargmuesli** [comment]
Yep, but I'm wondering what the migration path may be.

**Comment by rchl** [comment]
Your guess is correct.

**Comment by dargmuesli** [comment]
Thanks!
