### ISSUE TITLE
How to configure i18n for static assets files?

### ISSUE THREAD

**Issue by zarpio** [nuxt-modules/i18n#1086]
Please note, I have some js files included as follows, from the root "static" directory.

```
head: {
    script: [
      {
        src: "libs/modernizr.min.js"
      },
      {
        src: "jquery.min.js"
      },
      {
        src: "custom.js"
      }
    ]
  },
```
configured i18n as follows
```
  i18n: {
    locales: [{
        code: 'en',
        name: 'English',
        file: 'en-US.js'
      },
      {
        code: 'ar',
        name: 'Arabic',
        file: 'ar-AR.js'
      }
    ],
    defaultLocale: 'en',
    lazy: true,
    langDir: 'lang/',
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en'
    }
  },
```
Using en there is no issue with loading my js file, but when I switch from en to ar, browser console gives me the following error for all included files from the static directory.

`GET http://localhost:3000/ar/js/jquery.min.js net::ERR_ABORTED 404 (Not Found) `

![nuxt-error](https://user-images.githubusercontent.com/112050/109960487-a701f380-7d0a-11eb-9e8b-e7537e50b52f.png)

**Comment by rchl** [comment]
Use absolute paths to source files. For example `/libs/modernizr.min.js` (note the leading slash).

Or the most robust solution would be to prepend the path with https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#base
