### ISSUE TITLE
open redirect vulnerability

### ISSUE THREAD

**Issue by myanotheraccount** [nuxt-modules/i18n#1092]
### Version
nuxt-i18n: 6.12.2
nuxt: 2.14.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal
 - [] spa

### Nuxt-i18n configuration

i18n: {
    strategy: 'prefix_except_default',
    ...
}

### Reproduction Link
https://sty4f.sse.codesandbox.io

### Steps to reproduce
https://sty4f.sse.codesandbox.io//google.com/

### What is Expected?
redirect to error page

### What is actually happening?
redirect to google.com

**Comment by rchl** [comment]
Thanks for reporting. Preparing a fix in #1093.
