### ISSUE TITLE
Support multiple domains in local options

### ISSUE THREAD

**Issue by jinevo** [nuxt-modules/i18n#1100]
### Problem 
Currently the only way to support multiple domains for one code is to declare each domain separately. 
At the first sight, it could be managed by env variables but it is useful when we want to progressively migrate a website to nuxt.

```
{
  locales: [
    {
      code: 'fr',
      domain: 'domain.fr',
      file: 'fr.js'
    },
    {
      code: 'fr',
      domain: 'fr.nuxtprod-domain.com',
      file: 'fr.js'
    },
    {
      code: 'fr',
      domain: 'fr.nuxtuat-domain.com',
      file: 'fr.js'
    },
    {
      code: 'en',
      domain: 'domain.com',
      file: 'en.js'
    },
    {
      code: 'en',
      domain: 'en.nuxtprod-domain.com',
      file: 'en.js'
    },
    {
      code: 'en',
      domain: 'en.nuxtuat-domain.com',
      file: 'en.js'
    },
   // and so on
  ],
  differentDomains: true
}
```

Besides, this implementation generates duplicated routes definition warnings in the console / terminal from vue-router
`WARN  [vue-router] Duplicate named routes definition: { name: "index___en", path: "" }`

### Solution
The solution would be to support an array of domains in the domain value

```
{
  locales: [
    {
      code: 'fr',
      domain: ['domain.fr', 'fr.nuxtprod-domain.com', 'fr.nuxtuat-domain.com'],
      file: 'fr.js'
    },
    {
      code: 'en',
      domain: ['domain.com', 'en.nuxtprod-domain.com', 'en.nuxtuat-domain.com'],
      file: 'en.js'
    },
   // and so on
  ],
  differentDomains: true
}
```

**Comment by larbijirari** [comment]
hello, 
i'm facing the same situation, any news about this feature ?

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
