### ISSUE TITLE
Error when project path contains ".js"

### ISSUE THREAD

**Issue by hrastnik** [nuxt-modules/i18n#1109]
### Version
nuxt-i18n: 6.21.0
nuxt: all versions

### Steps to reproduce
When the project directory path contains ".js" the bundler crashes with the following error:

`Dependency not found "~i18n-klona"`

The problem is in this line:
https://github.com/nuxt-community/i18n-module/blob/c6580240190e754496c3a6a25a52a46dc1c86c59/src/index.js#L88

The `.replace(".js", ".mjs")` should replace only the ".js" extension, but instead it replaces the first ".js" it encounters.

**Comment by rchl** [comment]
Thanks. Fixed in https://github.com/nuxt-community/i18n-module/releases/tag/v6.21.1

**Comment by ghost** [comment]
Wow, that was fast! Thank you for the quick fix.
