### ISSUE TITLE
Custom path in nuxt config file not working?

### ISSUE THREAD

**Issue by Stf-F** [nuxt-modules/i18n#1111]
Hi,

I am currently struggling to get the custom paths working when implemented in the nuxt config file.
They do, however, work from the components.

Currently my config is:

```javascript
i18n: {
    locales: [
      {
        code: 'en',
        iso: 'en-US',
        file: 'en-us.js',
        name: 'English (US)',
      },
      { code: 'fr', iso: 'fr-FR', file: 'fr.js', name: 'Français' },
      {
        code: 'gb',
        iso: 'en-GB',
        file: 'en-gb.js',
        name: 'English (UK)',
        isCatchallLocale: true,
      }, 
    ],
    lazy: true,
    seo: false,
    langDir: 'lang/',
    defaultLocale: 'gb',
    strategy: 'prefix_and_default', // https://i18n.nuxtjs.org/routing#prefix
    vueI18n: {
      fallbackLocale: 'gb',
    },
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'lang',
      onlyOnRoot: true, 
      alwaysRedirect: false, 
    },
    parsePages: false,
    pages: {
      about: {
        gb: '/about',
        fr: '/a-propos',
      },
      login: {
        gb: '/login',
        fr: '/se-connecter',
      },
      register: {
        gb: '/register',
        fr: '/s-inscrire',
      },
    },
  }, 
```

This does not generate the custom paths. 

The same config with the `parsePages` flag set to `true` with the following in my `register` page component does the job:

```javascript
  nuxtI18n: {
    paths: {
      fr: '/s-inscire', 
    },
  },
```
My folders structure:

![image](https://user-images.githubusercontent.com/52630104/111158527-07592680-8590-11eb-9953-73e271ae714d.png)

Edit: Adding deps from package.json for reference:

 ```json
"dependencies": {
    "@nuxt/content": "^1.11.1",
    "@nuxtjs/axios": "^5.12.5",
    "@nuxtjs/firebase": "^7.5.0",
    "@nuxtjs/gtm": "^2.4.0",
    "@nuxtjs/pwa": "^3.3.5",
    "aws-amplify": "3.3.21",
    "core-js": "^3.8.3",
    "date-fns": "^2.19.0",
    "firebase": "^8.3.0",
    "nuxt": "^2.15.3",
    "nuxt-buefy": "^0.4.4",
    "nuxt-i18n": "^6.21.1",
    "nuxt-social-meta": "0.0.5",
    "vue-social-sharing": "^3.0.5"
  },
  "devDependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.13.8",
    "@nuxtjs/eslint-config": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/prismic": "^1.2.6",
    "@vue/test-utils": "^1.1.2",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.5.0",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "vue-jest": "^3.0.4"
  }
```

Any pointer as to what I would be missing?

Thanks

**Comment by rchl** [comment]
Those would work if your routes would be files and not directories (`about.vue` rather than `about/index.vue`). ~~For your routes you need to change the keys to match the route names. You can find out the route names with browser extension Vue.js devtools or by looking into the generated `.nuxt/router.js` file.~~

**Comment by rchl** [comment]
That answer was wrong but the right answer is in the documentation:

![Screenshot_2021-03-15_at_15 45 20](https://user-images.githubusercontent.com/153197/111172411-177c0080-85a6-11eb-8f30-2c92eef82a21.png)

https://i18n.nuxtjs.org/routing#modules-configuration

So `about/index` instead of `about`, for example.

**Comment by Stf-F** [comment]
Hi @rchl , thanks. Looking at a previous comment from you this part of the documentation is critical:
![image](https://user-images.githubusercontent.com/52630104/111172963-2d85c300-859e-11eb-8628-fc9533eb942d.png)

The correct syntax is therefore the following:
![image](https://user-images.githubusercontent.com/52630104/111173054-41c9c000-859e-11eb-86a8-e314c6147ec1.png)

Adding the `/index` to the keys does the job and allows the paths to be converted from the config file.

Thanks for your prompt feedback.
