### ISSUE TITLE
Add i18n in context

### ISSUE THREAD

**Issue by ArthurDanjou** [nuxt-modules/i18n#1112]
### Is your feature request related to a problem? Please describe.

I recently discovered a new feature of View 3: The Composition API. So I learned about the existence of the Nuxt Composition API module. So I want to adapt my current site with this functionality, however the i18n module is not yet compatible.

### Describe the solution you'd like

I wanted to access the i18n module inside the context method.

### Describe alternatives you've considered

Actually, I have added the type inside the 'index.d.ts' file to access the i18n module directly from the context but I dont know if it is the best way

### Additional context

https://codesandbox.io/s/github/ArthurDanjou/artsite/tree/dev for testing and seeing what i have test

**Comment by rchl** [comment]
Should work with `@nuxtjs/composition-api`. See a working example here https://github.com/nuxt-community/i18n-module/blob/master/test/fixture/composition-api/pages/index.vue

**Comment by ArthurDanjou** [comment]
Bonjour, merci pour la reponse. Cependant, j'ai vu avec @pi0  qui m'a demande d'ouvrir un ticket pour l'ajouter directement dans le context

**Comment by rchl** [comment]
Can do that but that's not specific to composition API so updated the title.

BTW. Currently `nuxt-i18n` injects those to `context.app`:
 - i18n
 - localePath
 - localeRoute
 - switchLocalePath
 - getRouteBaseName

So I'm not entirely sure if I should expose all of those in `context` or just `i18n`. For consistency, the former would make more sense.
