### ISSUE TITLE
Routing only working for the default language

### ISSUE THREAD

**Issue by a4vg** [nuxt-modules/i18n#1116]
### Version
nuxt-i18n: 6.21.1
nuxt: 2.15.3

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [ ] spa

### Reproduction Link

https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-smvfh

### Steps to reproduce
1. Create a 404.vue page.
2. Extend routes in nuxt.config.js with the 404 page. As [show in Nuxt docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes).
```js
router: {
    extendRoutes(routes, resolve) {
      routes.push({
        name: "not-found",
        path: "*",
        component: resolve(__dirname, "pages/404.vue")
      });
    }
  }
```
3. Go to any page (except home) in the default language. <-- All ok
4. Go to any page (except home) in a language other than default. <-- 404 error

### What is Expected?
Get the page with the correct language, not the 404 page.

### What is actually happening?
The 404 shows up. Moving the route `"/fr*"` to the end in nuxt/router.js fixes it, but it's obviously not a long term solution.

Am I missing something? These seems like a use case too common and I haven't found anything about it.

**Comment by rchl** [comment]
Is there a reason you are adding this catch-all route that way instead of creating a `pages/_.vue` file?

Or if you want to do it that way, try with `/*` path which is what `_.vue` creates.

**Comment by a4vg** [comment]
Thanks! Changing it to `/*` didn't work, but using `_.vue` did.

Sorry, I'm new to Nuxt. I was trying it with the `extendRoutes` way because it appeared like that [in the docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes) and there's not much information about it. No special reason.

**Comment by rchl** [comment]
As for the original issue, I think the `sortRoutes` function from Nuxt doesn't work correctly in that case. The less specific `/fr*` route should be sorted after more specific `/fr/about`, for example.

Although having a route like `/fr*` would also catch stuff that starts with `fr` like for example `/from` so it's probably not a good idea to use that form anyway.

**Comment by vanling** [comment]
Im not sure if this is the same issue i am experiencing, but might be related. 

I am using `pages/_.vue` and do not have an pages/index.vue. 
Every time i use the router.push function to go to homepage via logo/menu etc it works fine.
A fresh refresh on homepage always returns a 404 and does not reach the _.vue code.

_I'm working around this issue by duplicating _.vue to index.vue for now.  👎_ 


**edit: This comment seemed to help me :)** https://github.com/nuxt-community/i18n-module/issues/1067#issuecomment-781476731

**Comment by rchl** [comment]
It seems to be an upstream (Nuxt) issue that affects very specific custom case so I'll just close it here.
