### ISSUE TITLE
Cannot find module 'lodash.merge'. at v6.22.0

### ISSUE THREAD

**Issue by tari404** [nuxt-modules/i18n#1122]
### Version
nuxt-i18n: 6.22.0
nuxt: 2.15.3

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal

### Bug

`lodash.merge` is installed as `devDependencies` in [package.json](https://github.com/nuxt-community/i18n-module/blob/v6.22.0/package.json#L131), but actually imported at [https://github.com/nuxt-community/i18n-module/blob/v6.22.0/src/index.js#L3](https://github.com/nuxt-community/i18n-module/blob/v6.22.0/src/index.js#L3). It will make an error when building, like:

```
   │   ✖ Nuxt Fatal Error                                                                │
   │                                                                                     │
   │   Error: Cannot find module 'lodash.merge'                                          │
   │   Require stack:                                                                    │
   │   - /xxx/node_modules/nuxt-i18n/src/index.js                                        │

```

unless I run `$ npm i lodash.merge` manually.

It looks like `lodash.merge` should be move to `dependencies` in package.json?

**Comment by mi-upto** [comment]
Hi! me too. I opend pr #1121

**Comment by rchl** [comment]
Sorry about that. Released the fix in https://github.com/nuxt-community/i18n-module/releases/tag/v6.22.1
