### ISSUE TITLE
Use message function in lazy mode results in unknown translation key

### ISSUE THREAD

**Issue by jon-ht** [nuxt-modules/i18n#1124]
### Version
nuxt-i18n: 6.15.4
nuxt: 2.14.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal
 - [] spa

### Reproduction Link

- Reproduction link with message function not exported https://codesandbox.io/s/nuxt-nuxt-i18n-message-function-not-found-syuec?file=/plugins/vue-i18n.js
- Reproduction with message function correctly handled https://codesandbox.io/s/nuxt-nuxt-i18n-message-function-found-duted?file=/plugins/vue-i18n.js

### Steps to reproduce

Define a translation key as message function with `lazy` mode active

### What is Expected?

Translation key should be exported / handled and its message should be shown instead of the key

### What is actually happening?

In the first reproduction link, the translation is handled from server side but in client side it's the key that is displayed. You can see a "flash" with the message 

https://user-images.githubusercontent.com/17051512/112760501-79515700-8ff7-11eb-884e-a1c03334c8b0.mp4

In the second link, everything works well if all translations are imported from `vue-i18n` plugin

---

After some digging, it seems like this line is in cause https://github.com/nuxt-community/i18n-module/blob/eaa72a8a4406c92b187888cebe026cee57e51950/src/templates/plugin.main.js#L45

The reason is that [`getLocaleMessage(locale)`](https://github.com/kazupon/vue-i18n/blob/728ad511e1658cbf474a13ebeacf49b6bee4d8f8/src/index.js#L754-L756) uses [`looseClone`](https://github.com/kazupon/vue-i18n/blob/3970a7a6277f5d462a5fcd6bb9301a3265dd61ee/src/util.js#L101-L103) method, which removes functions from original object.

If I replace the previous call in `plugin.main.js` by 
```js
langs[locale] = app.i18n._getMessages()[locale] || {}
```

I have my message function working as expected (this need to be applied to fallback locale too)

**Comment by rchl** [comment]
While not cloning should be safe in this case (and also more efficient) because those messages are assigned to Nuxt state object and cloned (stringified) by Nuxt later anyway, you are suggesting to use an internal method which is typically not a good idea.

**Comment by rchl** [comment]
Well, almost no chance of it ever breaking (unless maybe in a major release of `vue-i18n` but then it will be caught by tests). I'll change that.

**Comment by rchl** [comment]
I can't confirm that this suggested solution helps though.

With input like:
```
export default {
  home: 'Homepage',
  about: 'About us',
  posts: 'Posts',
  untranslated: 'in english',
  fn () { return 'Demo string' }
}
```
the resulting message function gets stringified to `fn: {}` on the client-side.

**Comment by rchl** [comment]
Nuxt uses `@nuxt/devalue` to serialize Nuxt state so functions end up as `{}` and a warning is triggered.

So I think that in this case, the only solution that would work is not storing messages in Nuxt state which would make the client-side import them themselves. The reason the Nuxt state is used like that is to avoid extra requests on the client-side.

**Comment by jon-ht** [comment]
Thanks for the response !

That was also my though for stringified Nuxt state. But what surprises me is the "flashing" translation, it's caused because Nuxt state is also initialized in client side ?

In the meantime I moved my translations to non-lazy mode but I was looking for a better way of handling large files.

> So I think that in this case, the only solution that would work is not storing messages in Nuxt state which would make the client-side import them themselves. The reason the Nuxt state is used like that is to avoid extra requests on the client-side.

Do you think that's something doable ? Or maybe only in case of combination of lazy mode + message function ?

**Comment by rchl** [comment]
Created #1125 fix that will make this case work with the downside of having to make an extra network request on the client-side to fetch the messages. This will only happen if we fail to serialize the messages.

**Comment by jon-ht** [comment]
Thanks for the fix ! I can confirm it's resolved on master branch
