### ISSUE TITLE
Feature Request: Way to redirect to existing locale when a locale does not exist to a favorable one

### ISSUE THREAD

**Issue by kgrosvenor** [nuxt-modules/i18n#1131]
### Is your feature request related to a problem? Please describe.

i am currently supporting the locale **hi-IN** in a website that i am building, however only **hi** exists in the list of chrome language settings, i would like to be able to use a descision map to redirect to the locale hi-IN from hi

### Describe the solution you'd like

Allow possiblity to detect hi, or specific descision maps in the url and redirect to a desired locale, i like the api of fallbackLocale from vue i18n, however this is a separate request, please let me know if this already exist as well!

### Describe alternatives you've considered

I am pondering the options now, please leave comments if there is any work arounds to this, it would be nice to have a similar api to fallbackLocales, but something like redirectableFallbackLocales?

### Additional context

```javascript
{
   redirectFallbackLocale: {
     'hi': ['hi-IN'],
  },
  messages: {
    'en-GB': require('./locales/en-GB'),
    'fr-CA': require('./locales/fr-CA'),
    'en-CA': require('./locales/en-CA'),
    'en-IE': require('./locales/en-IE'),
    'en-IN': require('./locales/en-IN'),
    'de-DE': require('./locales/de-DE')
  }
}
```

**Comment by rchl** [comment]
Are you talking about making the existing `detectBrowserLocale` support that functionality? In that case, does it not do that already? Can you provide reproduction steps for me to better understand that request (you can create one by forking https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-sty4f)?

**Comment by rchl** [comment]
Closing due to no response.
