### ISSUE TITLE
Merging i18n SEO metadata with my own - two potential issues

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/i18n#1133]
### Version
nuxt-i18n: 6.20.3
nuxt: 2.15.3

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [] spa

### What is actually happening?
Two possible issues shown below. One suggests to replace a deprecated function with `nuxtI18nHead()` which doesn't seem to exist. Another error complains about missing iterator in `i18nHead.meta`.

![image](https://user-images.githubusercontent.com/48835293/113483794-8661c080-94a5-11eb-8db0-3ef319f55ded.png)
![image](https://user-images.githubusercontent.com/48835293/113483908-f83a0a00-94a5-11eb-847c-b6860e60c154.png)
![image](https://user-images.githubusercontent.com/48835293/113483870-d3de2d80-94a5-11eb-81ed-a024861c4f6d.png)

**Comment by rchl** [comment]
Fixed the issue with wrong API being deprecated in https://github.com/nuxt-community/i18n-module/commit/9736bf1a68aeb7bb275f3b092c0911b69627ea04 (not released at the time of writing this).

As for the issue with "must have a ... method that returns an iterator", I think that's because it can be undefined according to the types. Try something like `...(i18nHead.meta || [])`.

**Comment by rchl** [comment]
Or alternatively, maybe do:

```js
return {
  ...i18nHead,
  title: ...
}
```

(unless you on purpose want to exclude something from `i18nHead`, of course)

**Comment by DamianGlowala** [comment]
https://github.com/nuxt-community/i18n-module/commit/9736bf1a68aeb7bb275f3b092c0911b69627ea04 fix has been released and suggestion to add `...(i18nHead.meta || [])` was spot on. Thanks a lot, closing the issue.

Perhaps it would be a good idea to modify the following snippet in the documentation @rchl? This is where I took the initial code from which doesn't contain an empty array.
[https://i18n.nuxtjs.org/seo/#merging-i18n-seo-metadata-with-your-own](https://i18n.nuxtjs.org/seo/#merging-i18n-seo-metadata-with-your-own)

**Comment by rchl** [comment]
> Perhaps it would be a good idea to modify the following snippet in the documentation

I've actually just changed the types to be more specific so you should not have this problem anymore, even without the `|| []`.

02cc072b4bd7c6fe2ca4a745c7a28238f0a48f45
