### ISSUE TITLE
Canonical hreflang per language if multiple region defined in nuxt.config.js

### ISSUE THREAD

**Issue by daishizenSensei** [nuxt-modules/i18n#1136]
Hi everyone, 

**PROBLEM**

I face an issue that i would like to share with you. I build a multilinguale website wich has multiple region per language. These locales : 

`    locales: [
      {
        code: 'fr-fr',
        iso: 'fr-FR',
      },
      {
        code: 'en-gb',
        iso: 'en-GB',
      },
      {
        code: 'fr-ch',
        iso: 'fr-CH',
      },
      {
        code: 'en-us',
        iso: 'en-US',
      },`
     
But we can't congifure a canonical link per language. Wich is the recommended by Google for SEO.

**SOLUTION**

For a better SEO, it would be great to have the possibility to add a canonical link to each language like this

`    locales: [
      {
        code: 'fr-fr',
        iso: 'fr-FR',
        canonical: true
      },
      {
        code: 'en-gb',
        iso: 'en-GB',
        canonical: true
      },
      {
        code: 'fr-ch',
        iso: 'fr-CH',
      },
      {
        code: 'en-us',
        iso: 'en-US',
      },`

Or maybe there is another way to do it ?

Have a good day,
Kevin

**Comment by rchl** [comment]
Can you link to the Google recommendations?

**Comment by daishizenSensei** [comment]
Sorry, it's tiredness... It is exactly what "isCatchallLocale: true" do right ? It prevent duplicate content ?
https://developers.google.com/search/docs/advanced/crawling/localized-versions

**Comment by rchl** [comment]
I believe that should cover it, yes.

**Comment by daishizenSensei** [comment]
Okay, thank you :). By the way, do you think that issue #895 will be solved, or it is not a priority for the team ? 
Because we have to know if we choose a prefix or prefix_except_default strategy for SEO

**Comment by rchl** [comment]
As I said in that PR, I don't see a clean way to fix that so either someone has to come up with some good suggestion or a PR or else it won't be fixed.
