### ISSUE TITLE
Release brokes build on IE 11 

### ISSUE THREAD

**Issue by fcorallini** [nuxt-modules/i18n#1137]
### What is actually happening?

nuxt-i18n adds the is-https dependency, which code is not transpiled properly,
similar error dissussed here #329 

The build works fine on IE11 with version v5.12.7

### Version
"nuxt": "^2.15.2",
"nuxt-i18n": "^6.22.3",

### Nuxt configuration

```
import webpack from 'webpack'

export default {
  /*
   ** Nuxt.js modules
   */
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    '@nuxtjs/font-awesome',
    'bootstrap-vue/nuxt',
    'cookie-universal-nuxt',
    'nuxt-modernizr',
    'nuxt-i18n',
  ],
  /*
   ** Customize the build directory
   */
  generate: {
    dir: 'dist/beta',
  },
  i18n: {
    locales: [
      {
        code: 'en',
        file: 'en.json',
        header: 'en-US',
      },
      {
        code: 'it',
        file: 'it.json',
        header: 'it-IT',
      },
    ],
    defaultLocale: 'it',
    strategy: 'prefix',
    langDir: 'lang/',
    lazy: true,
    vueI18n: {
      silentTranslationWarn: true,
      silentFallbackWarn: false,
      detectBrowserLanguage: false,
    },
  },
  /*
   ** Build configuration
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {},
    plugins: [
      new webpack.ProvidePlugin({
        // global modules
      }),
    ],
  },
  //  etc ...
}

```

**Comment by rchl** [comment]
@pi0 @danielroe Should `is-https` be compiled to a lower target?
I've tried with ES3/ES2015 targets and that still had default argument though...

**Comment by rchl** [comment]
For the moment I'll just inline that function as it's pretty small.

**Comment by danielroe** [comment]
@rchl esbuild/siroc can't currently build for IE11 (follow https://github.com/unjs/siroc/issues/197) so IE11 supporters should probably add `is-https` to `build.transpile`.

**Comment by rchl** [comment]
Thanks. I could add to `transpile` list from the module but for now, will just go with inlining since it's not likely to need updates.

Fixed in https://github.com/nuxt-community/i18n-module/releases/tag/v6.23.0
