### ISSUE TITLE
Can't access `localeProperties.iso` in beforeLanguageSwitch

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/i18n#1141]
### Is your feature request related to a problem? Please describe.

I'm trying to set moment local to a specific iso. 
French use Monday as the first day of the week, but in Québec (French Canada), we use Sunday.
So I'm trying to update the moment locale in my app, but beforeLanguageSwitch only return string.
```
$moment.locale(app.i18n.localeProperties.iso);
app.i18n.beforeLanguageSwitch = async (oldLocale, newLocale) => {
    $moment.locale(newLocale);
};
```

### Describe the solution you'd like

Nuxt-i18n should only return string if the locale are defined as string.
If the locale is defined as an object, nuxt-i18n should return an object in the callback.

### Describe alternatives you've considered

Instead of returning an object, maybe the callback could have 4 arguments:
```
$moment.locale(app.i18n.localeProperties.iso);
app.i18n.beforeLanguageSwitch = async (oldLocaleString, newLocaleString, oldLocaleObj, newLocaleObj) => {
    $moment.locale(newLocaleObj);
};
```

### Additional context

I already kinda have a solution.
I can use Array.find on the app.i18n.locales Array, but this add unnecessary complexity.
```
$moment.locale(app.i18n.localeProperties.iso);
app.i18n.beforeLanguageSwitch = async (oldLocale, newLocale) => {
    const newLocaleIso = app.i18n.locales.find(l => l.code === newLocale).iso
    $moment.locale();
};
```

**Comment by rchl** [comment]
This is **onBefore** event so I think it makes sense that all target-locale properties are not resolved yet.

Would it work for you to use **onLanguageSwitched** hook instead?

**Comment by mrleblanc101** [comment]
@rchl I don't agree. These propriety are not computed. These are static propriety of the lang, so they should be available even in `beforeLanguageSwitch`. Every example I've seen use `beforeLanguageSwitch` to change locale, not `onLanguageSwitched`.

**Comment by rchl** [comment]
Changing the value of existing arguments is not an option since that would be a breaking change.

Adding new arguments would be fine but I don't think that it's really worth it since there is already an easy way to achieve what you want. Either by looking up locale object or switching to `onLanguageSwitched`.

**Comment by mrleblanc101** [comment]
Seems like `6.27.0` did change the api but did not take this into account for the new `onBeforeLanguageSwitch` 😕
Related to #1164

**Comment by rchl** [comment]
I did not remember about this issue, unfortunately. Those still could be added as a trailing arguments though.
