### ISSUE TITLE
config `detectBrowserLanguage.fallbackLocale` ignored

### ISSUE THREAD

**Issue by tebaly** [nuxt-modules/i18n#1145]
### Version
nuxt-i18n: 6.24.0
nuxt: 2.14.10

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal
 - [] spa

### Nuxt-i18n configuration 
```
i18n: {
    vueI18nLoader: true,
    defaultLocale: 'ru', 
    strategy: 'prefix_and_default',
    detectBrowserLanguage: {
        fallbackLocale: 'ru',
        onlyOnNoPrefix: true
    },
    ...
}
``` 

### What is Expected?
There should be a 302 redirect to the main page

### What is actually happening?
Redirects 302 to the `en` locale (prefix` /en/ `). Ignores `fallbackLocale: 'ru'`, and `defaultLocale: 'ru'`,

**Comment by rchl** [comment]
You haven't specified your browser settings (or the value of the `Accept Language` header) so I can't tell if that is a bug or expected behavior.

If the detected browser locale is "en" then redirecting to `/en` sounds correct.

**Comment by tebaly** [comment]
I use for testing - https://technicalseo.com/tools/locale-adaptive/
If locale not detected - redirect to `en` not to `ru`

**Comment by rchl** [comment]
Provide a reproduction repo or codesanbox please.

**Comment by rchl** [comment]
Closing due to no response.
