### ISSUE TITLE
Use $i18n in Vuex store using Typescript

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt-modules/i18n#1146]
I'm migrating my Nuxt app to Typescript.
In `store/api.js`, I have the following:
```js
export const actions = {
// ...
getTranslation({}, { set }) {
    return set.translations.find(
      t => t.code == this.$i18n.localeProperties.code
    );
  },
}
```
But now, in `api.ts`, I can't do:
```ts
import { Module, VuexModule, Mutation, Action } from "vuex-module-decorators";
import { Translation, LocaleSet } from "@/utils/interfaces";

@Module({
  name: "api",
  stateFactory: true,
  namespaced: true
})
export default class Api extends VuexModule {
  //...
  @Action
  getTranslation(set: any): Translation {
    return set.translations.find(
      (t: Translation) => t.code == this.$i18n.localeProperties.code // this.context.$i18n also doesn't work
    );
  }
}
```
In the [docs](https://typescript.nuxtjs.org/cookbook/store), there is a guide to access the modules.
The issue is that I didn't manage to import any type from the module like:
```ts
// utils/store.js
import { SomeI18nType } from "nuxt-i18n";
let $i18n: SomeI18nType;

export function initializeI18n(i18nInstance: SomeI18nType): void {
  $i18n = i18nInstance;
}

export { $i18n };
```

How can I do ?

**Comment by rchl** [comment]
Gonna expose `NuxtI18nInstance` in https://github.com/nuxt-community/i18n-module/pull/1147 so you'll be able able to type the `$i18n` variable properly.

(In theory, you could have done that already by pulling the type from `Context['i18n']`, for example, but it makes sense to expose it anyway.)

**Comment by florian-lefebvre** [comment]
Thanks !

**Comment by florian-lefebvre** [comment]
When will it be available ?

**Comment by rchl** [comment]
Released https://github.com/nuxt-community/i18n-module/releases/tag/v6.25.0

**Comment by atlansien** [comment]
I can't find `NuxtI18nInstance` in v8.
