### ISSUE TITLE
Not working with @nuxtjs/router

### ISSUE THREAD

**Issue by DonSalvador** [nuxt-modules/i18n#1155]
### Version
nuxt-i18n: 6.25.0
nuxt: 2.15.3

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [ ] spa

### Reproduction Link
https://codesandbox.io/s/angry-sanne-uqrru
https://github.com/DonSalvador/langVue

### What is Expected?
-  i18n-module should generate the language routes automatically
- switchLocalePath should working when press the languages buttons
- localePath() should return the path with the prefix

### What is actually happening?
- the language routes are not being created automatically and I have to create them manually. If I go to /es without creating the routes for Spanish language, it will go to the user page /:username, instead of home.
- when I switchLocalePath nothings happen, so I have created a path manually
- localePath is returning the path without any prefix

**Comment by rchl** [comment]
Adding `@nuxtjs/router` removes all routes by default. See its documentation https://github.com/nuxt-community/router-module#usage and especially the `keepDefaultRouter` option.

You will have the same behavior without `nuxt-i18n`.
