### ISSUE TITLE
Issue with cyrillic translation duplicated URL

### ISSUE THREAD

**Issue by virtuallabdev** [nuxt-modules/i18n#1156]
Hi, managing russian and bulgarian traslation in a full static generated site lead to a duplicated url.
for example:

### Nuxt configuration
ssr: true
target: static

### Example Link
URL 1
http://localhost:3000/%D1%85%D0%B0%D0%BB%D0%BA%D0%B8%D0%B4%D0%B8%D0%BA%D0%B8-%D0%B2%D0%B8%D0%BB%D0%BB%D1%8B

URL 2
http://localhost:3000/%D1%85%D0%B0%D0%BB%D0%BA%D0%B8%D0%B4%D0%B8%D0%BA%D0%B8-%D0%B2%D0%B8%D0%BB%D0%BB%D1%8B/

### What is Expected?
i18n-module should generate the language routes for non latin characters without duplicate the URL and without fallback to spa pages

### What is actually happening?
URL 1 fallback to the spa page, instead URL 2 is the correct static page generated. I need that the nuxt generate produce only the static page without the "/" at the end to avoid content duplication and spa fallback

**This happens only if in my page I use cyrillic translated URL**. 
If I change the russian and bulgarial URL with latin characters everything works fine.

I just write all the details at this link:
[https://stackoverflow.com/questions/67161933/nuxt-full-static-generated-page-issue-with-cyrillic-uri](url)

Maybe it's only a matter of wrong configuration in nuxt.js but I'm not able to fix this.
Thank in advance for the support.

**Comment by rchl** [comment]
Please create a minimal reproduction if you want me to have a look. You can do it on codesandbox for example (using this template https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-sty4f?file=/nuxt.config.js).

Can just say generically that with static generation you get a folder structure like `халкидики-виллы/index.html` so the URL without `/` doesn't really exist and the server has to redirect to an URL with the slash.

There is this Nuxt option https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-generate#subfolders that you can try changing to false but it might cause you some other issues.

**Comment by virtuallabdev** [comment]
Hi,
thanks for your fast feedback,
I recreate a small example project, you can clone it from:
[https://github.com/virtuallabdev/nuxt_i18n](url)

- generate the static site
- go to the villas page 
- if you click on lang switcher button you can see in the browser console the log of the spa fallback
- If you switch back to english no log are show in console because you land in the static page
- If you add a "/" at the end of bulgarian or russian villas page you landin the static page (no log in the console)
- If you change the i18n in the villas page using the commented part you can see that after you have generated the full static site everything works as expected

**Comment by rchl** [comment]
Here is a simple repo that reproduces with pure Nuxt so please report this in Nuxt repo instead: https://github.com/rchl/nuxt-link-cyrillic-static

**Comment by virtuallabdev** [comment]
Thanks for your support
