### ISSUE TITLE
SEO: Domains in the webpage source code starts with http but expects to start with https

### ISSUE THREAD

**Issue by 0721Betty** [nuxt-modules/i18n#1167]
### Version
nuxt-i18n: ^6.18.0
nuxt: ^2.14.12

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [✔️] universal
 - [] spa

### Nuxt-i18n configuration

```
 {
        lazy: true,
        seo: true,
        langDir: 'lang/',
        defaultLocale: 'en',
        detectBrowserLanguage: false,
        locales: [
          {
            code: 'en',
            name: '',
            iso: 'en-US',
            file: 'en-US.ts',
            domain: 'xxx.xxx.io',
          },
          {
            code: 'cn',
            name: '中文',
            iso: 'zh-CN',
            file: 'zh-CN.ts',
            domain: 'xxx.xxx.cn',
          },
        ],
        differentDomains: true,
 },
```

### Steps to reproduce
Use `nuxt generate` to generate `dist` package...
Right-click to view the source code of the webpage

### What is Expected?
```
<link data-n-head="ssr" data-hid="i18n-alt-en" rel="alternate" href="https://xxx.xxx.io/" hreflang="en">
```

### What is actually happening?
```
<link data-n-head="ssr" data-hid="i18n-alt-en" rel="alternate" href="http://xxx.xxx.io/" hreflang="en">
```

**Comment by 0721Betty** [comment]
If you add `https` in the domain, the result is `<link data-n-head="ssr" data-hid="i18n-alt-en" rel="alternate" href="http://https://xxx.xxx.io/" hreflang="en">`

**Comment by rchl** [comment]
This logic whether to use HTTPS or HTTP is here: https://github.com/nuxt-community/i18n-module/blob/7d1e74fd2a8186fe00a3ff852a0a5b72a216a915/src/templates/utils-common.js#L143-L163

On the server-side it decides based on data from the request object and on the client it uses the currently used protocol.

**Comment by 0721Betty** [comment]
emmmm, Maybe I didn't express it clearly.
`webpage source code` means `index.html` in the `dist` directory generated after running `nuxt generate`.
what is the currently used protocol when run `nuxt generate` ?

**Comment by rchl** [comment]
I see. Then it's not handled correctly in case of `nuxt generate`.
Maybe there needs to be an explicit setting for it.

**Comment by divine** [comment]
Hello,

I'm using static target and everything works fine.

Probably the reason is `differentDomains`. @0721Betty what meta you've for `xxx.xxx.cn` ?

Thanks!

**Comment by rchl** [comment]
Yes, I meant that it doesn't work correctly for `differentDomains`.

**Comment by divine** [comment]
I think one way to fix this is to rewrite:
https://github.com/nuxt-community/i18n-module/blob/dcf43de88640dacb7823a84eba9f055cd03ddabf/src/templates/utils-common.js#L124-L129

```javascript
let domain;
if (process.server) { 
   protocol = (req && isHTTPS(req)) ? 'https:' : 'http:'
   domain = parseURL(lang.domain).host
} else { 
   protocol = hasProtocol(lang.domain, true) ? parseURL(lang.domain).protocol : window.location.protocol.split(':')[0]
   domain = parseURL(lang.domain).host
} 
return `${protocol}//${domain}`
```

What do you think @rchl ?

Thanks!

**Comment by rchl** [comment]
For nuxt generate i think the process.server condition is relevant (also)?

**Comment by divine** [comment]
> For nuxt generate i think the process.server condition is relevant?

`parseURL(lang.domain).protocol` returns `'https:'` that's the reason why I've modified the protocol part in `process.server`.

Domain part is added because if `lang.domain = "https://example.com"` then

```javascript
return `${protocol}//${lang.domain}`
```

would return

```javascript
`https://https://google.com`
```
in target server as well.

Kinda before domain in locale didn't accept protocols...

I hope that makes sense now.

Thanks!

**Comment by divine** [comment]
> For nuxt generate i think the process.server condition is relevant (also)?

Well, after thinking a little bit, this might even better for both server and static (since it's different domains?):

```javascript
protocol = hasProtocol(lang.domain, true) ? parseURL(lang.domain).protocol : ''
domain = parseHost(lang.domain).hostname

return `${protocol}//${domain}`
```

**Comment by 0721Betty** [comment]
> Hello,
> 
> I'm using static target and everything works fine.
> 
> Probably the reason is `differentDomains`. @0721Betty what meta you've for `xxx.xxx.cn` ?
> 
> Thanks!

Sorry to reply you so late! For cn: `<link data-n-head="ssr" data-hid="i18n-alt-zh" rel="alternate" href="http://xxx.xxx.cn/" hreflang="zh">`

**Comment by divine** [comment]
> > For nuxt generate i think the process.server condition is relevant (also)?
> 
> Well, after thinking a little bit, this might even better for both server and static (since it's different domains?):
> 
> ```js
> protocol = hasProtocol(lang.domain, true) ? parseURL(lang.domain).protocol : ''
> domain = parseHost(lang.domain).hostname
> 
> return `${protocol}//${domain}`
> ```

Should I send a PR, does that fix looks fine @rchl?

Thanks!

**Comment by rchl** [comment]
Feel free to make a PR and we can discuss it there.

As of now I can't quite see where are those `hasProtocol` and `parseURL` from and where are you checking the `x-forwarded-proto` header and `req.socket`.

**Comment by divine** [comment]
> Feel free to make a PR and we can discuss it there.
> 
> As of now I can't quite see where are those `hasProtocol` and `parseURL` from and where are you checking the `x-forwarded-proto` header and `req.socket`.

It's from https://github.com/unjs/ufo which is already being used.

Glad to hear, will send a PR.

Thanks!
