### ISSUE TITLE
How to correctly use vuex when migrating from vue-i18n to nuxt-i18n? 

### ISSUE THREAD

**Issue by andorfermichael** [nuxt-modules/i18n#1168]
In my opinion, the documentation regarding vuex would require more details. I actually don't understand how this module uses vuex. A few questions occur while reading the documentation and while trying to integrate the module into my existing project:

- What is stored in the vuex store by default? (How does the store look like?)
- What is stored in the vuex store when activating the sync options? (How does the store look like now?)
- How can I extend the store (adding functions for data handling)?
- Is the store somehow merged with another store?

Why am I asking that? I am asking because I previously used vue-i18n and managed the store myself, but I wanted to benefit from nuxt-i18n, but now I am stuck at the adaptation of my project to correctly use nuxt-i18n with the vuex option.

My config looks as follows:

    i18n: {
        lazy: true,
        langDir: '~/locales/',
        strategy: 'prefix_and_default',
        defaultLocale: 'en',
        detectBrowserLanguage: false,
        differentDomains: true,
        locales,
        vuex: {
            moduleName: 'nuxt-i18n',
            syncLocale: true,
            syncMessages: false,
            syncRouteParams: false
        }
    }

My store which was introduced before using nuxt-i18n looks like this:

```
import { locales } from '~/services/i18n'

export const state = () => ({
    locales,
    locale: {}
})

export const mutations = {
    setLocale(state, locale) {
        if (state.locales.includes(locale)) {
            state.locale = locale
        }
    }
}

export const getters = {
    locales: (state) => {
        return state.locales
    },
    locale: (state, getters) => {
        return state.locale.iso ? state.locale : getters.getLocaleFromCode(this.$i18n.defaultLocale)
    },
    language: (state) => {
        return state.locale && state.locale.iso ? state.locale.iso.split('-')[0] : this.$i18n.defaultLocale
    },
    getLocaleFromCode: (state) => (code) => {
        code = code.split('-')[0]
        return state.locales.find((locale) => locale.iso === code)
    },
    getLocalesFromLanguage: (state) => (language) => {
        return state.locales.filter((locale) => locale.iso.split('-')[0] === language)
    }
}
```

The messages/translations are already loaded correctly, but it seems to me that I am using two stores (i18n and nuxt-i18n) beside each other at the moment which somehow magical intersect with each other!?

Furthermore, I have the following plugin and I am wondering how adapt the commit to the new store correctly:

```
import { getLocaleForTld, getLocalesFromLanguageString } from '@/services/i18n'

/**
 * This function basically checks whether the domain matches the current locale or not.
 * If not (or if no locale is set) it sets the locale accordingly
 * This middleware should only be executed on server side
 *
 * @param store a vuex store instance to commit the locale to
 * @param req the request sent to the server
 */
export default function ({ i18n, store, req }) {
    let locale = store.state.i18n.locale
    const url = process.server ? new URL(req.url, `${req.protocol}://${req.headers.host}`) : window.location
    const tld = url.host.replace(/.*symptoma\./, '')

    if (!locale.iso) {
        // no locale set
        locale = getLocaleForTld(tld)
        if (!locale) {
            // set default locale
            locale = getLocalesFromLanguageString(i18n.defaultLocale).filter((l) => l.defaultLanguage)[0]
        }

        store.commit('i18n/setLocale', locale)
    } else {
        // locale is set, check if it matches the tld
        const tldLocale = getLocaleForTld(tld)
        if (!locale.iso === tldLocale.iso) {
            store.commit('i18n/setLocale', tldLocale)
        }
    }
}
```

Maybe someone can enlighten me, how to migrate my store from vue-i18n to nuxt-i18n correctly, whatever the solution is.

**Comment by rchl** [comment]
While the lacking documentation might be a valid issue, I wonder why you need to put all this data in the store if it's available on the `$i18n` object already.

**Comment by andorfermichael** [comment]
Okay, so you recommend not to store this data, don't you? But, what's the purpose of activating vuex for nuxt-i18n then? What does the sync do? I would appreciate it if you could explain that to me.

**Comment by rchl** [comment]
I'm not sure what's the use case of `syncLocale` and `syncMessages`. Those were already implemented when I've started working on this module.

Maybe there are some use cases where you have access to store but not Nuxt context or Vue instance but I can't imagine any.

**Comment by divine** [comment]
> I'm not sure what's the use case of `syncLocale` and `syncMessages`. Those were already implemented when I've started working on this module.
> 
> Maybe there are some use cases where you have access to store but not Nuxt context or Vue instance but I can't imagine any.

Hello,

Maybe this can be deprecated and later removed completely in the next major release?

Thanks!

**Comment by andorfermichael** [comment]
I could finally solve my problem by using the i18n instance where ever possible, shifting the helper functions to other files, removing my store, and letting nuxt-i18n take over the whole locales handling in the background.

However, I am still convinced that other people will be confused about nuxt-i18n and vuex like I was. I would really appreciate an update/extension of the docs regarding this and the removal of deprecated/unclear functionalities.

**Comment by rchl** [comment]
> Maybe this can be deprecated and later removed completely in the next major release?

I don't have any data on its usage so removing completely would be quite risky.

**Comment by rchl** [comment]
Maybe should look into removing that functionality for the next major version.
We can take that risk since it will be a major version and if someone complains we can restore it.

**Comment by rchl** [comment]
`syncLocale` and `syncMessages` were removed on the `next` branch which will be released in the next major release.
