### ISSUE TITLE
Question about generating duplicate hreflangs

### ISSUE THREAD

**Issue by wojciech-szymanski** [nuxt-modules/i18n#1170]
https://github.com/nuxt-community/i18n-module/blob/2d83bc81551b21324288bbac566a7cb910348ed2/src/templates/head-meta.js#L86

When nuxt config iso is in a `de-DE` format, this condition will always add an object to `localeMap`, as when we loop through first locale of a given language, it will not be present yet.

Then in next command after if, we add a duplicate with `localeIso`, thus generating hreflang twice:
 - de
 - de-DE

Is that intended behaviour as I am getting SEO review complains in our app that we only should have one hreflang link per locale.

**Comment by rchl** [comment]
It's a "catchall" locale that is added. Read also https://i18n.nuxtjs.org/seo#automatic-hreflang-generation

**Comment by divine** [comment]
> Is that intended behaviour as I am getting SEO review complains in our app that we only should have one hreflang link per locale.

Hello,

Remove software that complains about it or name and shame it. It's two different locales.

However, it might be possible that you're using the same code for two different locales.

    
```javascript
locales: [
  {
    code: "de",
    iso: "de",
    name: "German"
  },
  {
    code: "de",
    iso: "de-DE",
    name: "German de-de"
  }
],
```

which will generate something likes this:

```html
<link data-n-head="ssr" data-hid="i18n-alt-de" rel="alternate" href="/de" hreflang="de">
<link data-n-head="ssr" data-hid="i18n-alt-de-DE" rel="alternate" href="/de" hreflang="de-DE">
```
Basically, change your locales configuration to different codes:
```javascript
locales: [
  {
    code: "de",
    iso: "de",
    name: "German"
  },
  {
    code: "de-de",
    iso: "de-DE",
    name: "German de-de"
  }
],
```
then everything will be generated correctly:

```html
<link data-n-head="ssr" data-hid="i18n-alt-de" rel="alternate" href="/de" hreflang="de">
<link data-n-head="ssr" data-hid="i18n-alt-de-DE" rel="alternate" href="/de-de" hreflang="de-DE">
```

Thanks!

**Comment by wojciech-szymanski** [comment]
@divine thanks for your reply. Yes, we did some more research and it seems Google does not complain about duplicate hreflangs. I understand that reasoning behind this is about having a default lang only hreflang for all language cases and lang-region exceptions for those that match given country specifically.
