### ISSUE TITLE
In-Component Path Specification not working if strategy: 'prefix_except_default'

### ISSUE THREAD

**Issue by floriankapaun** [nuxt-modules/i18n#1171]
When using `strategy: 'prefix_except_default'`, `parsePages: true` and defining in-component paths, the defaultLocales paths aren't translated.

My page `about.vue` has the following specification:

```
export default {
  nuxtI18n: {
    paths: {
      en: '/about-us',
    }
  }
}
```

I should be able to access `/about-us` now, but instead I'm only able to access `/about`.

### Version
nuxt-i18n: 6.27.0
nuxt: 2.15.3

### Nuxt configuration
 - [X] universal
 - [] spa

### Nuxt-i18n configuration
```
defaultLocale: 'en',
langDir: 'lang/',
lazy: true,
locales: [
    {
        code: 'en',
        file: 'en.js',
        iso: 'en-US',
    },
],
parsePages: true,
strategy: 'prefix_except_default',
```

**Comment by rchl** [comment]
The `prefix_except_default` strategy is the default strategy and this functionality should be tested and working. Can you provide a reproduction?
