### ISSUE TITLE
At which point of the nuxt lifecycle is i18n ready?

### ISSUE THREAD

**Issue by andorfermichael** [nuxt-modules/i18n#1173]
I want to use `this.$i18n` in a computed property in one of my components, e.g.

```
topLevelDomain() {
    return getTldForLocale(this.$i18n.localeProperties)
}
```

However, it seems that $i18n is not initialized (correctly) at this point of time, because 
`console.log(this.$i18n.locale)` logs `{ code: ""}`

This only happens in production mode (nuxt build, nuxt start), and not in dev mode (nuxt).

Is there anything to consider in production mode?

**Comment by rchl** [comment]
It's already initialized when your component's or page's code runs. So there must be something else in your project that causes this issue.

**Comment by andorfermichael** [comment]
ok, thanks. I had to set 

```
vuex: {
  syncLocale: true
}
```

**Comment by rchl** [comment]
The use of vuex should not be necessary to get this working...

**Comment by andorfermichael** [comment]
For me it definitely was necessary

**Comment by rchl** [comment]
That would indicate some bigger issue at play, I'd think.
