### ISSUE TITLE
process.env variables not applied on i18n config in nuxt.config.js

### ISSUE THREAD

**Issue by andorfermichael** [nuxt-modules/i18n#1174]
### Version
nuxt-i18n: 6.26.0
nuxt: 2.15.4

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt-i18n configuration
```
    i18n: {
        lazy: true,
        langDir: '~/locales/',
        defaultLocale: process.env.DEFAULT_LOCALE,
        detectBrowserLanguage: false,
        differentDomains: true,
        locales: locales(process.env.SUB_DOMAIN),
        vueI18n: {
            fallbackLocale: process.env.DEFAULT_LOCALE
        },
        vuex: {
            syncLocale: true
        }
    }
```

### Reproduction Link

cannot provide repro link because already the template is not working for me (language switch not working etc.)

### What is Expected?
process.env.XXX is working for nuxt-i18n config, so that e.g. DEFAULT_LOCALE and SUB_DOMAIN are applied, causing fallback/default and locales domain prop working correctly

### What is actually happening?
process.env.XXX is not working for nuxt-i18n config, neither DEFAULT_LOCALE nor SUB_DOMAIN are applied, thus in components message keys are shown instead of message values, and current locale domain is wrong.

It works in dev mode but not in production mode.

**Comment by rchl** [comment]
Please provide repro steps, ideally a project that reproduces.

Also, are you generating a static site with `nuxt generate` for production? You know that the env variables will only be evaluated at build time in that case?
