### ISSUE TITLE
Fallback locale behavior for customPath

### ISSUE THREAD

**Issue by existe-deja** [nuxt-modules/i18n#1176]
### Is your feature request related to a problem? Please describe.
The doc says, if a custom path is missing, it get the `defaultLocale` one if set.
Thing is, you can expect custom path to behave like i18n translations, and so, to inherit from `fallbackLocale` rules.
It's ok because this kind of data is sensible so being explicit is not a bad thing. But things grows fast specially with lot of locales and routes.

I can give you a tangible situation:
I have to localize urls of a large website (>40 pages) into 13 locale/dialect without url prefixes (SEO considerations). We decided to run 1 instance per locale (kind of what is already in production with other stack) so we can take advantage of `prefix_except_default` strategy and `differentDomains`  option. So each instance will have a specific `defaultLocale`.
If I don't write every single routes, I will have bad fallback custom path, and my SEO won't like it :smile: 

### Describe the solution you'd like
Fallback custom path could inherit from `fallbackLocale` rules.

### Describe alternatives you've considered
Writing every routes for every languages.

### Additional context
could relates to https://github.com/nuxt-community/i18n-module/issues/984
testing https://codesandbox.io/s/nuxt-i18n-fallback-route-custom-path-8rw6t?file=/nuxt.config.js

**Comment by rchl** [comment]
I'm not convinced that using the "fallbackLocale" rules for custom paths is the right way to go about it. I would think that just applying the fallbackLocale rules verbatim would result in unwanted behavior like the path for the locale "xx" defaulting to the custom path for `en` because `en` is the default locale.

I think there would need to be a separate mechanism for this feature.

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
