### ISSUE TITLE
Enable detectBrowserLanguage not only on root, but on several other pages

### ISSUE THREAD

**Issue by artrayd** [nuxt-modules/i18n#1178]
Hi guys, I need your help, please

For example, at nuxt.config.js I set:

```
i18n: {
    detectBrowserLanguage: {
      onlyOnRoot: true // for better SEO
   }
}
```

But on several specific pages, I still want to auto-detect and redirect users to their language.

Is that possible to set "onlyOnRoot: false" on some pages?

**Comment by rchl** [comment]
The module doesn't provide such functionality.
