### ISSUE TITLE
Is it possible to define defaultLocale at runtime for production?

### ISSUE THREAD

**Issue by existe-deja** [nuxt-modules/i18n#1180]
Hi,

I tried to find a solution on stackoverflow, github, discord, but my question doesn't seem to be covered.

The initial problem I'm trying to solve
I need to define `defaultLocale` at runtime because I need to have translated urls without prefix.

The solution I found
I can launch one instance per locale with a custom defaultLocale.

The problem I'm facing
It works great in dev, process.env overwrite the settings. But after I build the app, process.env can't override the defaultLocale.

Is it possible to do it?
Is it a nuxt problem?
Should I also make one build per locale?

Thanks for your help

**Comment by rchl** [comment]
`defaultLocale` can affect the generation of routes which has to happen at build time.
So even if it would be possible to change it at runtime, it would likely make something not work as expected.

**Comment by existe-deja** [comment]
So the only workaround is to make one build per locale?

**Comment by rchl** [comment]
Currently I would say so, yes.

**Comment by existe-deja** [comment]
Thanks for making things clearer.
