### ISSUE TITLE
trailingSlash not getting added in localePath even on setting `trailingSlash: true`

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt-modules/i18n#1181]
### Version
nuxt-i18n: 6.21.0
nuxt: 2.15.5

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode):
 - [x] universal

### Nuxt-i18n configuration
```js
  i18n: {
    locales: [{
      code: 'en',
      iso: 'en',
      name: 'English',
    }, {
      code: 'hi',
      iso: 'hi',
      name: 'हिन्दी',
    }],
    defaultLocale: 'en',
    strategy: 'prefix',
    // noPrefixDefaultLocale: true,
    vueI18nLoader: true,
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: require('./i18n/en.js'),
        hi: require('./i18n/hi.js'),
      },
    }
  },
```
### Set up
In the `pages` folder:
```
index.vue
  - 📁 browse
     - index.vue
```

### Steps to reproduce
1. Add `route: { trailingSlash: true }` in nuxtconfig.js
2. Use 
   1. `<nuxt-link :to="localePath('index')">Home</nuxt-link>`
   2. `<nuxt-link :to="localePath('browse')">Home</nuxt-link>`

### What is Expected?
The link should go to `example.com/en/` AND `example.com/en/browse/`

### What is actually happening?
It is going to `example.com/en` AND `example.com/en/browse`

On Firebase hosting, the URLs always has a slash, so I don't want to generate the non-slash pages anyway to avoid duplication.

**Comment by divine** [comment]
Hello,

I can't reproduce.

Also, why you've omitted the reproduction link when creating this issue?

> A minimal test case on codesandbox or in a repository that can be used to reproduce the bug.
>     An example codesandbox that can be forked and used as a base can be found at:
>     https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-sty4f
> 

?

`route: { trailingSlash: true }`

Maybe this should be a [router](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router
) instead?



Thanks!

**Comment by ManasMadrecha** [comment]
Omg, no doubt I was unable to solve it even with so much trial and error. The cause was a typo (yes, it should be `router`). Thank you so much. It works great now. 😊
