### ISSUE TITLE
How to remove hreflangs for specific sections

### ISSUE THREAD

**Issue by wojciech-szymanski** [nuxt-modules/i18n#1182]
Hi,

On a website were are building, there is a section that has non-localised content pages that are related strictly to geographic regions of a given locale so we do not have a translated version of them, unlike homepage or more generic high level pages.

Using `6.21.1`, we tried to follow this guide https://github.com/nuxt-community/i18n-module/blob/67eccfe6123ce5240e9cb3d720e3b8c4a130b61c/docs/content/en/migrating.md#ignored-paths

As the option `i18n` throws plenty Typescript errors etc. I went through your code and found that you actually check for constant `nuxtI18n` being false or `{ seo: false }` but nothing works and I still get plenty hreflangs for each page. Are the docs missing something or am I doing sth rly wrong? 

Thanks,
Wojciech

**Comment by wojciech-szymanski** [comment]
My `pages/city/_slug.vue` code is sth like:

```
@Component({
  components: {
    LandingPage,
  },
  nuxtI18n: {
    seo: false,
  },
})
export default class CitySlug extends mixins(MixinLandingPage) {
  ...
}

**Comment by rchl** [comment]
The link you referred to is some old migration guide that concerns versions 2 and 3. We are at version 6 now. The currently supported syntax is mentioned in the documentation at https://i18n.nuxtjs.org/seo

That said, it's a bug (#932).

**Comment by wojciech-szymanski** [comment]
Hi, thanks for your response. Yes, I followed the guide to use `nuxtI18n: {
    seo: false,
  }` and this is indeed doing nothing. Is there an ETA for when this can be fixed? It's been open for quite a while now.

Regards,
Wojciech

**Comment by rchl** [comment]
No, no ETA. It requires a bit more involved changes and I'm not sure when I'll have time for that.

Contributions welcome.

**Comment by rchl** [comment]
Might add that using the deprecated module-level `seo` option should work with that way of disabling seo.

That said, it comes with performance penalty, as explained in the documenation.
