### ISSUE TITLE
Multiple files with translations

### ISSUE THREAD

**Issue by akadlec** [nuxt-modules/i18n#1185]
Is there way how to load multiple files for one language?

I'm trying to achieve code split: Nuxt app + x app modules with custom translations

/nuxt-app/

.../lang/
....../en.js

.../node_modules/
....../my-custom-package/
........./lang/
............/en.js

Does anybody know if it is possible?

**Comment by rchl** [comment]
Your main `en.js` can import and merge the `en.js` from the package.
