### ISSUE TITLE
How translate slug only once for dynamic pages

### ISSUE THREAD

**Issue by f3l1x** [nuxt-modules/i18n#1191]
Hi folks. I am struggling with nuxt-i18n. I have 2 locales. Let's say EN and CS, with prefix strategy. 

There is a dynamic page for articles = `/articles/:slug`

I have a nuxt-link like `<nuxt-link to="localePath('/articles/'+item.slug)">...</>`. The slug is different for each locale, `/cs/article/foo` and `/en/articles/bar`.

At this time, it generates 4 routes.

- /cs/article/foo
- /en/article/foo
- /cs/article/bar
- /en/article/bar

Is there any way how to generate only one for each locale? 
Thank you.

**Comment by rchl** [comment]
For statically generated pages (nuxt generate), Nuxt needs to create a separate page for each as otherwise those would not be SEO-friendly.

As for Nuxt running on a Node server, it doesn't generate separate route for each slug.

**Comment by f3l1x** [comment]
Hi @rchl. If I understand correctly, there is no way how to disable some lang for dynamic pages? Thank you.

**Comment by rchl** [comment]
I did some rudimentary testing and I don't see that issue. Only pages with relevant (used) slugs are generated for each locale.

You might have to create a reproduction if you want more help.
