### ISSUE TITLE
Duplicate, submitted URL not selected as canonical

### ISSUE THREAD

**Issue by retroriff** [nuxt-modules/i18n#1192]
I have created a couple of multilingual websites using this module. However Google Search Console is warning me that the translated pages are not being accepted :

`Duplicate, submitted URL not selected as canonical`

When I check the canonical tags using Google Inspection URL tool they are apparently fine:

![Screenshot 2021-06-09 at 16 17 04](https://user-images.githubusercontent.com/2946239/121361720-3a684780-c93e-11eb-807e-1a7cf95bf0cb.png)

I also checked them using curl and they look correct. Until now I have been using the default `detectBrowserLanguage` settings, which means that I didn't specify these settings. I suspect that this options may be generating SEO issues.

Has anybody experienced any indexing issue? Should I disable this redirect option with `detectBrowserLanguage: false`?

**Comment by divine** [comment]
Hello,

> Duplicate, submitted URL not selected as canonical

Where? You haven't shown where you get that error, there should be complete information that you didn't provide at all.

> Has anybody experienced any indexing issue? Should I disable this redirect option with `detectBrowserLanguage: false`?

No issues, you need to enable **`onlyOnRoot`** as well and have read the documentation at least which covers almost everything.

Thanks!

**Comment by retroriff** [comment]
Thanks @divine. [This](https://pallars74.com/) is one of the websites where I have this issue.

And these are the settings I was been using:

```
i18n: {
    baseUrl: process.env.BASE_URL || 'http://localhost:3000',
    defaultLocale: 'ca',
    locales: [
      {
        code: 'ca',
        iso: 'ca-CA',
        name: 'Català',
        file: 'ca-CA.json'
      },
      {
        code: 'es',
        iso: 'es-ES',
        name: 'Español',
        file: 'es-ES.json'
      },
      {
        code: 'en',
        iso: 'en-GB',
        name: 'English',
        file: 'en-GB.json'
      }
    ],
    langDir: 'locales/',
    lazy: true,
    parsePages: false,
    seo: false
}
```

So you suggest that the issue should be fixed adding `onlyOnRoot: true`?

**Comment by rchl** [comment]
Have you enabled the SEO features as described in https://i18n.nuxtjs.org/seo ? Without that the canonical tag is not added at all.

**Comment by retroriff** [comment]
@rchl Yes, the SEO features always have been enabled. The canonical tag is not missing. Google says that thr canonical address is pointing to a wrong page, which I cannot understand because it is shown correct to me when I check it. I suspect that the issue is because of a redirect caused by `detectBrowserLanguage`.

**Comment by divine** [comment]
Hello,

Yes, indeed redirection causes that duplicate error. You need to enable `onlyOnRoot` and wait until Google will reindex.

Thanks!

**Comment by retroriff** [comment]
@divine OK, these are my updated settings:

```
i18n: {
    defaultLocale: 'en',
    detectBrowserLanguage: {
      onlyOnRoot: true
    },
    locales: [
      {
        code: 'ca',
        iso: 'ca-CA',
        name: 'Català',
        file: 'ca-CA.json'
      },
      {
        code: 'en',
        iso: 'en-GB',
        name: 'English',
        file: 'en-GB.json'
      }
    ],
    langDir: 'locales/',
    lazy: true,
    parsePages: false,
    seo: false
}
```

Considering how Google process the default options, don't you think that `onlyOnRoot` should be enabled by default?

Thank you!

**Comment by rchl** [comment]
That's the plan for the next major version since it's a breaking change.

**Comment by divine** [comment]
> That's the plan for the next major version since it's a breaking change.

Just a small question, can we later* merge `onlyOnNoPrefix` into `onlyOnRoot`?

I somehow missed that PR changes, it indeed makes sense.

\* If yes, when these breaking changes will happen?

Thanks!

**Comment by rchl** [comment]
> Just a small question, can we later* merge `onlyOnNoPrefix` into `onlyOnRoot`?

Yes!

> * If yes, when these breaking changes will happen?

Not sure. Would need to have enough time and plan first. I'll create new issue for it.

**Comment by retroriff** [comment]
After a couple of months, I haven't been able to get all my translated pages indexed. Google still rejects to index [one of my pages](https://pallars74.com/en/) because `Duplicate, submitted URL not selected as canonical`.

I have checked several times the submitted sitemap and the generated canonical tags but they are apparently correct. Actually all translated pages have been accepted but there is one with exactly the same kind of tags which is being rejected week after week. 

I added the `onlyOnRoot`attribute that @divine recommended and this how it looks:

```
  i18n: {
    baseUrl: process.env.BASE_URL || 'http://localhost:3000',
    defaultLocale: 'ca',
    detectBrowserLanguage: {
      onlyOnRoot: true,
    },
    locales: [
      {
        code: 'ca',
        iso: 'ca-CA',
        name: 'Català',
        file: 'ca-CA.json'
      },
      {
        code: 'es',
        iso: 'es-ES',
        name: 'Español',
        file: 'es-ES.json'
      },
      {
        code: 'en',
        iso: 'en-GB',
        name: 'English',
        file: 'en-GB.json'
      }
    ],
  sitemap: {
    hostname: 'https://pallars74.com',
    gzip: true,
    i18n: true,
    trailingSlash: true
  },
```

Any idea why Google is rejecting it?

**Comment by rchl** [comment]
I think that's because your site is statically served (through Netlify) and so the page fully loads and then redirects to /en/ with a client-side redirect. I imagine that can cause issues with google.

If Netlify provides some way to do the redirect on the server side then that would likely work better. But that would mean that the redirecting logic from this module would not apply anymore.

**Comment by rchl** [comment]
There is some info about redirect by language here: https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language

Maybe you could try redirect rules like those:
```
/  /en/  302  Language=en
/  /es/  302  Language=es
```

**Comment by retroriff** [comment]
Hi @rchl, thanks for your answer. As far as I know, Netlify rules allow to redirect visitors automatically to their language. That's not what I would like to achieve. I want to create different landing pages per language without redirects. 

This behaviour is quite weird because my site is statically served and it has the language index.html files inside the dist/ folder with the right canonical tags:

````

dist/en/index.html
dist/es/index.html
````
Should I use server-side rendering instead?

**Comment by rchl** [comment]
Then it sounds like you want to set `detectBrowserLanguage: false`?

**Comment by retroriff** [comment]
I thought that `detectBrowserLanguage` was disabled by default. I experienced this issue before adding this setting and I was recommended to add `detectBrowserLanguage: { onlyOnRoot: true}`. I will replace it by `detectBrowserLanguage: false` and will ask Google for an approval. I will post the result once it has been processed by GSC. Thank you.

**Comment by rchl** [comment]
If you don't need the functionality that `detectBrowserLanguage` provides then as far as google is concerned, this is the best option.

**Comment by retroriff** [comment]
@rchl Hi, this time Google indexed the page successfully 🙂 . Thank you!
