### ISSUE TITLE
Copyright ownership inconsistencies

### ISSUE THREAD

**Issue by gekkedev** [nuxt-modules/i18n#1193]
When trying to give proper attribution I came up with the following question: Who does this repo's copyright belong to?
The `README` says `Nuxt Community` but the file `LICENSE` still says `Paul Gascou-Vaillancourt`.  
I assume this repo was moved into the nuxt-namespace and the copyright got transferred, so it should say `Nuxt Community` in both places. If this is correct I would appreciate a short confirmation by the maintainer(s) and I'll create a quick PR to make it consistent again.

**Comment by rchl** [comment]
I'm pretty sure the original author would have to preserved but it should be fine to add `Copyright (c) 2021 Nuxt.js Community` or such.

@Atinux @pi0 @danielroe ?

**Comment by atinux** [comment]
Fine by me!

**Comment by gekkedev** [comment]
I've adjusted it in both files by preserving the old notice; hope that works for ya. However, the semantic PR bot doesn't like it. :stuck_out_tongue_closed_eyes:
