### ISSUE TITLE
Translations from composition api setup method

### ISSUE THREAD

**Issue by RobinBertilsson** [nuxt-modules/i18n#1196]
Hi,

We're using the i18n-loader, meaning we specify the translations in the components itself, and that works perfectly fine when accessing them directly from the template, for example
```
<i18n>
{
  "en": {
    "title": "Hello World"
  }
}
</i18n>

<template>
  <div>{{ $t('title') }}</div>
</template>
```

But when we're trying to access the messages, specified in the `<i18n>` block from within the setup method/context, the `i18n.messages` object/array is empty, is there any workaround or alternative way of doing this?

Here's a full example of what we're trying to do, but as stated above, this doesn't work.
```
<i18n>
{
  "en": {
    "title": "Hello World"
  }
}
</i18n>

<template>
  <!-- Expected output: Hello World -->
  <!-- Actual output: title -->
  <div>{{ text }}</div>
</template>

<script lang="ts">
import { defineComponent, useContext } from '@nuxtjs/composition-api'

export default defineComponent({
  setup() {
    const { app: { i18n } } = useContext()
    
    const text = i18n.t('title')
    
    return {
      text,
    }
  }
})
</script>
```

Thought it could be a timing issue at first, but i've tried accessing the messages property after the component is mounted, but that doesn't make any difference, it's still empty.

**Comment by rchl** [comment]
Composition API support is not implemented and since I haven't looked deeper into it, I'm not sure what it would take to implement it. The solution would potentially be based on https://github.com/intlify/vue-i18n-composable/blob/master/src/index.ts though.
