### ISSUE TITLE
How to get the current language name?

### ISSUE THREAD

**Issue by retroriff** [nuxt-modules/i18n#1197]
Hello,

in a component we can get the current language code with `$i18n.locale`, but how to retrieve its name? `$i18n.name` doesn't work.

Thank you

**Comment by divine** [comment]
Hello,

Have you seen this example https://i18n.nuxtjs.org/lang-switcher?

Thanks!

**Comment by retroriff** [comment]
@divine Yes, I can retrieve the language name inside a `for`. That works fine but I don't know how to retrieve the name outside of the `for` block.

**Comment by divine** [comment]
Hello,

What do you think about something likes this?

```javascript
computed: {
  currentLocale() {
    return this.$i18n.locales.find((i) => i.code === this.$i18n.locale)
  },
},
```

and later used like `{{ currentLocale }}`

Thanks!

**Comment by retroriff** [comment]
@divine Thank you! That works like a charm: `currentLocale.name`

**Comment by rchl** [comment]
`this.$i18n.localeProperties` has all the properties of the current locale so `this.$i18n.localeProperties.name` should work.
