### ISSUE TITLE
'/nuxt-i18n/options.js' does not provide an export named 'localeMessages'

### ISSUE THREAD

**Issue by flozero** [nuxt-modules/i18n#1202]
### Version

nuxt-vite: 0.1.1
nuxt: 2.15.7
"nuxt-i18n": "^6.27.1",

References: https://github.com/nuxt/vite/issues/156

**Comment by rchl** [comment]
Some more info? Repro?

EDIT: I will try with `nuxt/vite` and `nuxt-i18n` added later.

**Comment by rchl** [comment]
I believe that this was fixed.
