### ISSUE TITLE
Unwanted %2F appended to url when typed in the url bar

### ISSUE THREAD

**Issue by April-Gras** [nuxt-modules/i18n#1204]
### Version
nuxt-i18n: `^6.22.3`
nuxt: `^2.9.2`

 - [x] universal
 - [ ] spa

### Nuxt-i18n configuration
```javascript
import en from "./locales/en.json"
import fr from "./locales/fr.json"

// ...
export default {
  vueI18n: {
    locale: "en",
    fallbackLocale: "en",
    messages: { en, fr },
    locales: [
      {
        code: "en",
        name: "English",
        iso: "en-US",
      },
      {
        code: "fr",
        name: "Français",
        iso: "fr-FR",
      },
    ],
    seo: true,
    defaultLocale: "en",
    strategy: "prefix",
    lazy: false,
    langDir: "~/locales/",
    vuex: {
      moduleName: "i18n",
      syncLocale: true,
    },
    detectBrowserLanguage: {
      useCookie: true,
      alwaysRedirect: true,
    },
  },
}
```

### Steps to reproduce
We'll consider that in this example that the nuxt app supports `en` as it's language
For this given url : `/foo/bar/?q=value`
We would expect the app to resolve this into `/en/foo/bar/?q=value` when typed in the url bar
Sadly in my case the module just resolves this to `/en/foo/bar/?q=value%2F`

### What is Expected?
The url to remain without any `%2F` occurences

### What is actually happening?
The url should stay as is when first typed in

**Comment by rchl** [comment]
Forgot to add that this is with `router.trailingSlash: true`?

**Comment by April-Gras** [comment]
Hi @rchl 
Thanks for taking the time to reply
Yep I forgot to mention that `router.trailingSlash` is indeed set to `true`, but I still believe this shouldn't behave this way
Do you recon I should bring this forward to the `vue-router` team instead ?

**Comment by justlstn** [comment]
I've got the same issue. 
A 3rd party service on my frontend processing urls like `https://www.example.com/?key=value` and set it's value to cookie.
Instead of getting `value` I get `value/` which is wrong.

Upd:
Please correct me if I wrong, I guess it happens because of these url path transforms:
https://github.com/nuxt-community/i18n-module/blob/master/src/templates/plugin.routing.js#L89
https://github.com/nuxt-community/i18n-module/blob/master/src/helpers/routes.js#L152

**Comment by rchl** [comment]
It most likely is a bug in this module, yes, but I haven't looked deeper into it yet.

**Comment by divine** [comment]
Hello,

I can't reproduce both issues on the latest version static/server rendering.

> nuxt-i18n: ^6.22.3
> nuxt: ^2.9.2.

Maybe it's time to update or post a reproduction repo/codesandbox?

Thanks!

**Comment by justlstn** [comment]
Hello guys,

@divine thanks for reply.

I've created an example on [codesandbox](https://codesandbox.io/s/blissful-glitter-6wq5h) and [github repo](https://github.com/justlstn/nuxt-redirect-issue-example). 
I was able to reproduce the issue on both of examples.

### Steps to reproduce on codesandbox:
- follow the link on [codesandbox](https://codesandbox.io/s/blissful-glitter-6wq5h)
- wait for build and start an app
- use following url in browser there `https://6wq5h.sse.codesandbox.io/?key=value`. In case the origin (https://6wq5h.sse.codesandbox.io) will be changed, replace it with the actual one.
- the url will be changed to this one `/en/?key=value%2F` where `%2F` is actually encoded `/`


P.S. Indeed, the `router.trailingSlash` should be set to `true`.

**Comment by justlstn** [comment]
Hello guys,
I'm sorry for opening this issue again.

Is it possible to release the fix?

Thank you in advance!

**Comment by rchl** [comment]
Triggered new release now.
