### ISSUE TITLE
defaultLocale does not seems to work ?

### ISSUE THREAD

**Issue by FOG5490** [nuxt-modules/i18n#1211]
I have a website, in which I config nuxt.config.js like this:
```
  i18n: {
    locales: [
      { code: 'en', file: 'en.json' },
      { code: 'id', file: 'id.json' },
    ],
    langDir: 'locales/',
    lazy: true,
    defaultLocale: 'id',
    strategy: 'no_prefix',
    detectBrowserLanguage: false,
  },
```
But when I test it in Incognito mode, every first time the website is loaded, the value of the cookie field `i18n_redirected` is always `en` but not `id`, and the website always display in English. It only then changes locale on refresh or route change. I even set <HTML lang="id"> in the document already.

**Comment by rchl** [comment]
The cookie should not even be set when `detectBrowserLanguage` is false. Unless you are calling `setLocaleCookie` somewhere in your code.

**Comment by FOG5490** [comment]
@rchl I'm not sure I get you. As you see, I don't have any options related to cookie. And the key `i18n_redirected` is the default key of nuxt-i18n. 
P/s: right, I also don't have `setLocaleCookie` anywhere in the code. Still, the above cookie key still shows up.

**Comment by rchl** [comment]
`i18n_redirected` cookie should not be created with those settings.
If you delete the cookie first, does it get re-created? Maybe it's an old cookie that was set when the settings were different?

**Comment by FOG5490** [comment]
@rchl At first, I did not have `detectBrowserLanguage: false`. After I added it, the `i18n_redirected` key still shows up. I was testing with a new Incognito window every time I refresh the website. Let me try a deep-clean to see how it goes.

**Comment by rchl** [comment]
I can't reproduce that with `detectBrowserLanguage: false`.

**Comment by FOG5490** [comment]
@rchl Well, I think it was from my side. Not sure why it did not clear the cookie, even with Incognito mode.

In the end. I cleared all my cache/cookies, un-sync my account in Chrome, and restart my PC, now it worked with `detectBrowserLanguage: false`
