### ISSUE TITLE
localeRoute() only works in dev mode, but not upon generate

### ISSUE THREAD

**Issue by SimonKib** [nuxt-modules/i18n#1215]
Using localeRoute() with yarn dev my i18n pages and routing works. But once I yarn generate, the static site is not able to load content on the page route. Static pages are created, but the page is empty.
Is this a bug or do I need to change my configuration?

-----

I create static pages with the below folder structure:

- _cases
  - _slug.vue
- _stories
  - _slug.vue
- _slug.vue  

I use localeRoute() to resolve urls to these dynamic pages
````
NuxtLink(
            :to="localeRoute({ name: 'stories-slug', params: { stories: $t('slugs.news'), slug: newsPage.slug }})"
            ) {{newsPage.title}}
````
On my page (e.g. _stories/_slug.vue) I have this code to get the page content
````
export default Vue.extend({
  async asyncData ({ $strapi, i18n, route }) {
    try {
    const match = await $strapi.find('news-items', { _locale: i18n.locale, slug: route.params.slug })
    return {
      page: match[0]
    }
    } catch(e) {
      console.log('async on stories error ', e)
    }
  },
  data () {
    return {
      page: {}
    }
  }
})
````
### Version
nuxt-i18n: 6.27.2
nuxt: 2.15.7

### Nuxt configuration
 - Target: Static
 - Modules: ['bootstrap-vue/nuxt', '@nuxtjs/strapi', 'nuxt-i18n']

### Nuxt-i18n configuration
```
i18n: {
    strategy: 'prefix',
    locales: ['en', 'da'],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          slugs: {
            cases: 'cases', // used for slugs, don't get too fancy
            news: 'news',  // used for slugs, don't get too fancy
          }
        },
        da: {
          slugs: {
            cases: 'eksempler', // used for slugs, don't get too fancy
            news: 'nyheder',  // used for slugs, don't get too fancy
          }
        }
      }
    }
  },
```

**Comment by rchl** [comment]
Please create a small repro if you want me to have a look at it anytime soon.

Most likely the repro doesn't need to use any real API, can just return a hardcoded response from `asyncData`.
