### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by andorfermichael** [nuxt-modules/i18n#1217]
### Version
nuxt-i18n: 6.27.1
nuxt: 2.15.6

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt-i18n configuration
```
...
    i18n: {
        lazy: true,
        langDir: '~/locales/',
        defaultLocale: process.env.DEFAULT_LOCALE,
        detectBrowserLanguage: false,
        differentDomains: true,
        locales: locales(process.env.SUB_DOMAIN),
        vueI18n: {
            fallbackLocale: process.env.DEFAULT_LOCALE
        },
        vuex: {
            syncLocale: true
        }
    }
...
```

```
export const locales = (domain) => [
    {
        code: 'ar',
        iso: 'ar',
        file: 'ar.json',
        dir: 'rtl',
        domain: `${domain}.company.ae`,
        name: 'العَرَبِيَّة',
        enName: 'Arabic',
        defaultLanguage: true,
        languages: ['ar'],
        certified: false
    },
    {
        code: 'de',
        iso: 'de',
        file: 'de.json',
        dir: 'ltr',
        domain: `${domain}.company.de`,
        name: 'Deutsch',
        enName: 'German',
        defaultLanguage: true,
        languages: ['de'],
        certified: true
    },
    {
        code: 'en',
        iso: 'en',
        file: 'en.json',
        dir: 'ltr',
        domain: `${domain}.company.com`,
        name: 'English',
        enName: 'English',
        defaultLanguage: true,
        languages: ['en'],
        certified: true
    },
    ...
]
```

### Reproduction Link

Cannot provide reproduction link, since project is way too big with hundreds of i18n usages and I am not sure which piece of code might cause the issue.

### Steps to reproduce

n.a.

### What is Expected?

SPA running as it was before with `v6.27.0`

### What is actually happening?

Starting with nuxt-i18n `v6.27.1` I get the following error when running my SPA `Cannot assign to read only property 'exports' of object '#<Object>'`

It seems that you introduced either a new bug or a breaking change in release `v6.27.1`.

**Comment by rchl** [comment]
Sometimes Nuxt has issues with invalidating its cache when updating dependencies.
Try again after deleting `node_modules` and re-installing.

**Comment by andorfermichael** [comment]
> Sometimes Nuxt has issues with invalidating its cache when updating dependencies.
> Try again after deleting `node_modules` and re-installing.

did not change anything, unfortunately

**Comment by rchl** [comment]
Then you would need to try to minimize your project to create a repro.

For now your best bet is to pin the 2.27.0 version if that works.

**Comment by rchl** [comment]
Looking at the linked issue https://github.com/nuxt-community/axios-module/issues/501, it seems like it was not related to this module after all.

**Comment by andorfermichael** [comment]
@rchl 

I have to reopen this ticket. I created two code sandboxes for reproduction:

1) [nuxt-i18n v6.27.0 - working](https://codesandbox.io/s/ancient-butterfly-phxch)

2) [nuxt-i18n v6.27.1 - not working](https://codesandbox.io/s/festive-matan-tgvdl)

Everything > 6.27.1 (incl. @nuxtjs/i18n starting with v7) does not work.

**Comment by rchl** [comment]
What's the reason that you have customized the `build.babel` option? Is it just to enable corejs 3? If so then you can do it with a `build: { corejs: 3 }` instead and it should fix your problem.

I think that by customizing `build.babel` you have disabled support for some language constructs that the default config supports. Unless you know what you are doing, you should use the `corejs` option instead.
