### ISSUE TITLE
[SSR] [prefix_except_default strategy] In Arabic localization only the context called twice   

### ISSUE THREAD

**Issue by mgfouad** [nuxt-modules/i18n#1218]
### Version
nuxt-i18n: 6.27.2
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal
 - [] spa

### Nuxt-i18n configuration

i18n: {
    locales: [
      { code: "en-us", iso: "en-US", dir: "ltr", file: "en-us.json" },
      { code: "ar-eg", iso: "ar-EG", dir: "rtl", file: "ar-eg.json" },
      { code: "fr-fr", iso: "fr-FR", dir: "ltr", file: "fr-fr.json" }
    ],

    defaultLocale: "en-us",
    langDir: "~/locales/",
    vueI18n: {
      fallbackLocale: "en-us"
    }
  },

### Steps to reproduce
Adding a dynamic params (pages) ex: page1/page2/page3 , when I hit ar-eg/page1/page2 the context is called twice and cand detect the page2 params with the second call.

we can detect the second call from a router middleware  

### What is Expected?
to make only one request from node server so the context in the router middleware will be called once 

### What is actually happening?
two requests from node server and the second request can't detect the params correctly in the router middleware layer

**Comment by rchl** [comment]
Does it happen only in dev mode? If so then it looks like https://github.com/nuxt-community/i18n-module/issues/1160

**Comment by mgfouad** [comment]
It happens in both dev and build mode, and only with the arabic route , however it does not happen in case of french route !

ex:  
[domainName]/ar-eg/page1/page2 -> called twice 
[domainName]/fr-fr/page1/page2 -> only one call with no issues
[domainName]/page1/page2 -> only one call with no issues

**Comment by rchl** [comment]
Please create small reproduction repo/codesandbox.
