### ISSUE TITLE
Make `nuxtI18n` option accept a function to set custom paths coming from CMS API call

### ISSUE THREAD

**Issue by katerlouis** [nuxt-modules/i18n#1221]
### Is your feature request related to a problem? Please describe.
We want to use the paths provided by our CMS (Storyblok) for all pages. I.e:
`/impressum`, `/en/imprint`,
`/ueber-uns`, `/en/about`,

### Describe the solution you'd like
Since we pull the entire story object from storyblok in `asyncData()`, it would be ideal to access the component instance here. But I'm afraid that's not possible. So atleast being able to pull data again, would be nice.

```js
// /pages/imprint.vue
export default function {
  nuxtI18n() {
    // access  component instance (this) here
    // or atleast be able to make api call here
    return {
      paths: ....
    };
  },
};
```

### Describe alternatives you've considered
`/:slug` as path is not an option, since my `/pages/about.vue` is not dynamic. Most pages are custom front-ends.
I have no more ideas on how to set nuxtI18n custom paths coming from the CMS :(

**Comment by rchl** [comment]
Have you tried this https://i18n.nuxtjs.org/lang-switcher#dynamic-route-parameters ?

**Comment by davidsandoz** [comment]
@katerlouis Regarding the alternative you've considered, if you use [Unknown Dynamic Nested Routes](https://nuxtjs.org/docs/2.x/features/file-system-routing#unknown-dynamic-nested-routes), it will handle requests that do not match a more specific route, so you can still have the `/about` path using `/pages/about.vue` page.

**Comment by rchl** [comment]
I think the last two comments should be enough to resolve the issue so closing.
