### ISSUE TITLE
onLanguageSwitched callback doesn't get called when change lang on route path

### ISSUE THREAD

**Issue by csechuan** [nuxt-modules/i18n#1227]
### Version
nuxt-i18n: 6.27.2
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [] universal
 - [ X ] spa

### Nuxt-i18n configuration

```
i18n: {
    baseUrl: /* mask */,
    locales: [  /* mask */ ],
    lazy: true,
    langDir: /* mask */,
    strategy: 'prefix',
    defaultLocale: 'en',
    detectBrowserLanguage: {
      alwaysRedirect: true,
      fallbackLocale: 'en',
      onlyOnRoot: true,
      useCookie: true,
    },
    seo: false,
    vuex: false,
    vueI18n: {
      fallbackLocale: 'en',
      dateTimeFormats,
      numberFormats,
    },
}
```

### What is Expected?
Expecting callback get call.

### What is actually happening?
onLanguageSwitched callback get call perfectly when using lang switcher, but not when manually change the locale in the url path e.g. /en/sandbox --> /zh/sandbox. Doing this, message get translated,  $i18n.locale also changes, but callback get ignore. Currently, this callback is important to reflect the changes back to other module, for instance, trigger vee-validate locale changes.

**Comment by rchl** [comment]
When you are manually changing the URL then you are forcing full page reload from the server and so technically the language doesn't change but the new language is just loaded during page reload. That said, there exists now a new callback called `onBeforeLanguageSwitch` that is also triggered on initial page load. See https://i18n.nuxtjs.org/options-reference#onbeforelanguageswitch
