### ISSUE TITLE
How to set cookie without browser detection?

### ISSUE THREAD

**Issue by KStenK** [nuxt-modules/i18n#1231]
Hi!

I try to make routes and locale cookies work together.

I'm using the `prefix_except_default` strategy and for `defaultLocale` I have a foreign language.
Browser detection is enabled because then the locale cookie is set.

Currently, the goal is that when the user first time comes to the path `domain.com/*` without `en/` prefix, then automatically cookie for that locale (default locale) is set.
And when the user first time goes to the `domain.com/en/*` with the `en/` prefix, then the cookie with the `en` locale is set.

Most of us have browser language set to English by default so browser detection will always detect it as English, so I rather want to show the **default locale** when the user comes to the main domain without the `en/` prefix.

The thing is that our backend API is using cookies to detect which language content it needs to serve.

Any suggestions on how to do that?

For example, if I turn **Browser language detection** off, then is it possible to set locale cookie in any other way?

Or is it possible to force browser language detection to set cookies for the first request depending on prefix?

**Comment by rchl** [comment]
Sounds like you might want to disable browser language detection and save the cookie manually using the the public `setLocaleCookie` API.

Probably could do that from the `onBeforeLanguageSwitch` hook.

**Comment by KStenK** [comment]
Thanks for the suggestion.

I ended up disabling browser detection and used the Accept-Language HTTP header.
