### ISSUE TITLE
i18n cookie gets ignored

### ISSUE THREAD

**Issue by strebl** [nuxt-modules/i18n#1234]
### Version
nuxt-i18n: 6.27.3
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] `target: 'server'`
 - [x] `ssr: false`
 - [x] `ssr: true`
 
tested both, ssr true and false.

### Nuxt-i18n configuration
```
i18n: {
    defaultLocale: 'de',
    seo: false,
    langDir: 'lang/',
    strategy: 'prefix',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'language',
      onlyOnNoPrefix: true,
    },
    locales: [
      {
        code: 'de',
        iso: 'de-DE',
        name: 'Deutsch',
        file: 'de.js',
      },
      {
        code: 'en',
        iso: 'en-US',
        name: 'Englisch',
        file: 'en.js',
      },
    ],
  },
```

### Reproduction Link
App: https://i18n-test-novu.vercel.app
Repo: https://github.com/teamnovu/i18n-test

### Steps to reproduce
- Set `accept-language: de`
- Visit: https://i18n-test-novu.vercel.app
- You should be on `https://i18n-test-novu.vercel.app/de`
- Click on the English link
- You should be on `https://i18n-test-novu.vercel.app/en`
- You should have a language cookie with the value `en`
- Remove `/en` from the url
- You'll be back on `https://i18n-test-novu.vercel.app/de` (cookie ignored)

### What is Expected?
You should be on `https://i18n-test-novu.vercel.app/en` at the end.

### What is actually happening?
You are on `https://i18n-test-novu.vercel.app/de`.

After e long debugging time, I'm pretty sure the issue is here [plugin.main.js#L395-L400](https://github.com/nuxt-community/i18n-module/blob/master/src/templates/plugin.main.js#L395-L400).
I think line 399 should run if 397 returns an empty string, similar to [plugin.main.js#L403-L405](https://github.com/nuxt-community/i18n-module/blob/master/src/templates/plugin.main.js#L403-L405).

That fixes the issue, but I'm not sure if that's the way to go: https://github.com/nuxt-community/i18n-module/compare/master...teamnovu:fix/cookie-redirect?expand=1

**Comment by rchl** [comment]
I'd have to have a closer look but you could submit a PR and check which tests break (if any) and if for valid reason.

**Comment by divine** [comment]
Hello,

I can't reproduce, everything works fine for me?

Thanks!

**Comment by strebl** [comment]
Hi @divine Thanks for your test! Did you configure your browser with `accept-language: de`? All of our team have that problem, it seems weird that you can't reproduce it 🤔 

What language do you see, if you visit https://i18n-test-novu.vercel.app/ ?

**Comment by divine** [comment]
> Hi @divine Thanks for your test! Did you configure your browser with `accept-language: de`? All of our team have that problem, it seems weird that you can't reproduce it 🤔
> 
> What language do you see, if you visit https://i18n-test-novu.vercel.app/ ?

Hi @strebl,

I've changed the cookie via EditThisCookie and when visiting your site it shows:

```
Hallo
de
```

However, your deployment at Vercel target is `static`, not `server`.

Thanks!

**Comment by strebl** [comment]
Hi @divine 
After you've done that, switch to english and you should see that the cookie updates, right?

after that, visit https://i18n-test-novu.vercel.app/ again. what do you see now? If the problem occurs, you should see `Hallo de` again instead of `Hello en`.

You're right. I didn't deploy the test repo with SSR, I fixed that now. SSR is now enabled. However the issue is still there.

**Comment by divine** [comment]
> Hi @divine
> After you've done that, switch to english and you should see that the cookie updates, right?
> 
> after that, visit https://i18n-test-novu.vercel.app/ again. what do you see now? If the problem occurs, you should see `Hallo de` again instead of `Hello en`.
> 
> You're right. I didn't deploy the test repo with SSR, I fixed that now. SSR is now enabled. However the issue is still there.

Hi @strebl,

I see the issue now, it's indeed redirecting me to `/de` even though my cookie is set to `en`

Thanks!

**Comment by strebl** [comment]
Hi @divine,

Ah, I'm happy you can reproduce the issue now! You can take a look at #1235, maybe that's all it needs. At least that fixed the issue for us on our project.
