### ISSUE TITLE
Routes ending with an optional slug are not working anymore

### ISSUE THREAD

**Issue by arikw** [nuxt-modules/i18n#1242]
### Version
nuxt-i18n: 6.27.3
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal

### Nuxt-i18n configuration
```
i18n: {
    strategy: 'prefix',
    lazy: true,
    detectBrowserLanguage: false
}
```

### Steps to reproduce

`nuxt.config.js`
```js
i18n: {
    strategy: 'prefix',
    lazy: true,
    detectBrowserLanguage: false
},
router: {
    trailingSlash: true
}
modules: [
    '~/modules/routes'
]
```

`modules/routes.js`
```js
export default async function asyncModule() {
  this.extendRoutes(function extendRoutes(routes, resolve) {
    routes.push({
      name: 'product-page',
      path: `/:product(game|software)/:uid/:slug?`, // <-- notice the optional slug used with "?"
      component: resolve(__dirname, 'pages/product.vue')
    });
  }
}
```

### What is Expected?
1. A route with a path of `/es-ES/:product(game|software)/:uid/:slug?/` should be created and listed in `$nuxt.$router.options.routes`
2. Browsing to `/game/98f76a/cod/` should return the correct page as worked in `nuxt-i18n@6.27.2`

### What is actually happening?
1. A route with a path of `/es-ES/:product(game|software)/:uid/:slug/?` gets created (Notice the `?` got moved to the end of the path) and listed in `$nuxt.$router.options.routes`.
2. Browsing to `/game/98f76a/cod/` returns a `404` error page.

**Comment by divine** [comment]
Hello,

A simple reproduction? Might be related #1001.

Thanks!

**Comment by rchl** [comment]
I can reproduce. It's caused by #1214
