### ISSUE TITLE
[@nuxtjs/i18n migration] Set up netlify

### ISSUE THREAD

**Issue by rchl** [nuxt-modules/i18n#1250]
For the upcoming package name change, I'd like to have netlify setup in this way:
 1. `main` branch deploys documentation to https://i18n.nuxtjs.org/
 2. `legacy` branch deploys documentation to https://i18n-legacy.nuxtjs.org/

`master` branch can also keep deploying to https://i18n.nuxtjs.org/ for the time being.

@pi0 Would you or someone else be able to handle that?

**Comment by danielroe** [comment]
@rchl Let me know when you've set up those branches :+1:

**Comment by rchl** [comment]
Both branches exist now. Thanks

**Comment by pi0** [comment]
- Legacy: http://i18n-legacy.nuxtjs.org/ build only from `legacy` branch 
- Current: https://i18n.nuxtjs.org/ build from `master` branch (and all other branch previews)

~~@rchl Please ping when `main` was ready to be prod branch of main subdomain :)~~ (update you should be able to directly do this on netlify)

**Comment by rchl** [comment]
I've updated configuration for the `main` branch and all is done here now. Thanks.
