### ISSUE TITLE
Docker: This relative module was not found 

### ISSUE THREAD

**Issue by teaknig** [nuxt-modules/i18n#1260]
### Version
nuxt-i18n: ^6.15.4 - or any version
nuxt: ^2.15.3

### Nuxt configuration

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```js
  i18n: {
    locales: [{ code: 'ru', iso: 'ru-RU', file: 'ru-RU.js', name: 'Рус' }],
    defaultLocale: 'ru',
    langDir: 'lang/',
    lazy: true,
  },
  srcDir: 'src/', // it is important
```

### Structure
![изображение](https://user-images.githubusercontent.com/34206915/129041804-8a6dc641-9320-4af5-b7bd-0c3d6a6fa07f.png)

### Dockerfile
```yaml
FROM node:14-alpine

WORKDIR /app
COPY . /app

RUN yarn install \ 
    --frozen-lockfile \ 
    --prefer-offline \ 
    --non-interactive

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "yarn", "serve" ]
```

### Steps to reproduce
- need docker
- command `docker build -t test .`
- command `docker run -p 3000:3000 --name=test test`

### What is Expected?
 - the container starts

### What is actually happening?
![изображение](https://user-images.githubusercontent.com/34206915/129042449-03c51399-70b1-48af-969f-002c8e01169c.png)

### nuxt-i18n/options.js
```js
export const localeMessages = {
  'ru-RU.js': () => import('../../src/lang/ru-RU.js' /* webpackChunkName: "lang-ru-RU.js" */),
}
```

**Comment by rchl** [comment]
I think the issue is that the filename case doens't match - `ru-RU.js` vs `ru-Ru.js`.

Your local file system might not be sensitive to it but Linux is.

**Comment by teaknig** [comment]
I puzzled a lot, but, i really didnt notice the difference in "u" letter. U helped me a lot!
