### ISSUE TITLE
dynamic domains

### ISSUE THREAD

**Issue by mariodro** [nuxt-modules/i18n#1261]
https://github.com/nuxt-community/i18n-module/blob/2270bd19eda0cd18f2729df8907b266034a7fef6/src/templates/plugin.main.js#L365

This line must be:

`for (const locale of options.normalizedLocales) { 
`

**Comment by rchl** [comment]
Why is that? It would simplify the code but I don't see why it would be necessary.

**Comment by rchl** [comment]
Oh, I see now. Because it modifies `locale.domain` and there is code that expects to read the `domain` from `normalizedLocales`.

There is an existing PR that fixes it at https://github.com/nuxt-community/i18n-module/pull/1183 but I was not happy with it mutating some options.

**Comment by rchl** [comment]
Released the fix in https://github.com/nuxt-community/i18n-module/releases/tag/v7.0.2
