### ISSUE TITLE
Allow for some routes to be prefixed and others not.

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-modules/i18n#1262]
### Is your feature request related to a problem? Please describe.
I got the request for static pages to have prefixes eg. `/es/pricing` `/fr/products`
but for app routes to not have prefixes eg. `/profile` , `/messages`

Currently `setLocale()` will change the route aswell with any prefix strategy other than "no_prefix"

### Describe the solution you'd like
A second function call `swapLocale()` which only switches locale, without changing the route.

### Describe alternatives you've considered
Another solution, but probably more confusing due to already plenty of options: add another strategy.

**Comment by rchl** [comment]
Try `nuxtI18n: false` for pages that shouldn't have prefixes (https://i18n.nuxtjs.org/routing#ignore-routes).

I'm not sure now how it affects various behavior but it might work for you.

**Comment by rahulkumarsingh73690** [comment]
What if I have too many pages #1360
