### ISSUE TITLE
Support this.$nuxtI18nHead in nuxt.config.js

### ISSUE THREAD

**Issue by dword-design** [nuxt-modules/i18n#1266]
### Is your feature request related to a problem? Please describe.

After the major update to 7, the `seo` variable has been replaced by a `this.$nuxtI18nHead` function, which can be used to provide language meta tags to Nuxt (see [the docs](https://i18n.nuxtjs.org/seo/) for details). Problem with the current solution in contrast to the old one is that you can only use `this.$nuxtI18nHead` inside pages and layouts. Using it in `nuxt.config.js` `head` function will lead to `Cannot read property 'req' of undefined`, and replicating the old mixin behavior will lead to client-side errors because `this.$nuxtI18nHead` is registered lately.

Being restricted to pages and layouts makes it hard to refactor out duplicated code. Nuxt offers the module system, allowing to update the config dynamically. Currently, you will have to add the meta tags in each project individually.

### Describe the solution you'd like
Adjust the current behavior so that you can also implement the `head` function inside `nuxt.config.js` like so:

```js
export default {
  head() {
    return this.$nuxtI18nHead({ addSeoAttributes: true })
  },
  modules: [
    ['@nuxtjs/i18n', {
      // ...
    }],
  ],
}
```

### Additional context

See the [minimal example repo](https://github.com/dword-design/try-nuxt-i18n-seo).

<img width="1440" alt="Bildschirmfoto 2021-08-18 um 02 51 36" src="https://user-images.githubusercontent.com/13484795/129819259-4497cb87-b574-407d-8fb3-f13efbf302a1.png">

**Comment by rchl** [comment]
You could replicate the previous behavior if you really want to by creating a simple module that adds a plugin with a mixin. Then you would register that plugin **before** `@nuxtjs/i18n` and it should work.

Not recommended though as it's a very inefficient solution due to mixin running for every component used on the page.

It's not possible to support `$nuxtI18nHead` within the `head` function in the config as that function doesn't have access to the Nuxt or Vue Context.

What kind of duplication are you trying to avoid that the global head data would solve? Do you have that many layouts?

**Comment by dword-design** [comment]
@rchl Thanks for the quick reply! I'm using a bootstrapping module for all my projects that sets up stuff and adds config. Comparable to [nuxt/pwa](https://pwa.nuxtjs.org/) from a conceptual point of view. Since 90 % of my projects use roughly the same config.

* Title format
* Meta tags
* Commonly used functionality like axios, i18n, dotenv, HTTP auth

The question is which things from the context `$nuxtI18nHead` uses, because generally you also have access to `this` and all injected variables from `nuxt.config.js`es `head` function. I updated the linked repo for this purpose.

**Comment by rchl** [comment]
Oh, interesting. I didn't know about that. In that case there might be a way to get the necessary data from this context.
Basically what is needed is access to the `req` object. Currently that is done through `this.$ssrContext` but that is not defined at the point of the `head` being evaluated.

**Comment by rchl** [comment]
In fact, the seo functionality (`$nuxtI18nHead`) itself might not strictly require the `req` so there might be a way to make it work without having to make it accessible at this point.

**Comment by dword-design** [comment]
@rchl Sounds promising. Should be possible to access `req` via `this`.

**Comment by dword-design** [comment]
@rchl `this.context.req` seems to contain the request.

**Comment by rchl** [comment]
Fix released in https://github.com/nuxt-community/i18n-module/releases/tag/v7.0.3

Also documentation around that was updated to recommend using the `head()` function in the `nuxt.config.js` instead of layouts - https://i18n.nuxtjs.org/seo#setup

**Comment by wimil** [comment]
> Fix released in https://github.com/nuxt-community/i18n-module/releases/tag/v7.0.3
> 
> Also documentation around that was updated to recommend using the `head()` function in the `nuxt.config.js` instead of layouts - https://i18n.nuxtjs.org/seo#setup

 I am using the new version, as the documentation fixes, there is an annoying alert for using the head function in nuxt.config

```WARN  Cannot merge meta. Avoid using head as a function!```

**Comment by rchl** [comment]
I don't think that warning comes from Nuxt. Probably from some module.

**Comment by wimil** [comment]
that alert occurs when adding the module in the nuxt.config.js

**Comment by rchl** [comment]
But it's the https://github.com/nuxt-community/pwa-module that is complaining.

Options:
- update documentation to also mention the previous layout-based solution
- raise an issue in pwa-module to see if this restriction could be removed 

And you can of course continue using layout-based solution which causes no issues.

**Comment by dword-design** [comment]
There are other modules complaining about this like [@nuxtjs/google-gtag](https://www.npmjs.com/package/@nuxtjs/google-gtag). It always happens when a module tries to add data to `head` because it assumes head to be an object. It's not an ideal solution right now but I also cannot think of a better one. Probably Nuxt should handle the merging somehow.

**Comment by poldixd** [comment]
> There are other modules complaining about this like [@nuxtjs/google-gtag](https://www.npmjs.com/package/@nuxtjs/google-gtag). It always happens when a module tries to add data to `head` because it assumes head to be an object. It's not an ideal solution right now but I also cannot think of a better one. Probably Nuxt should handle the merging somehow.

Same with [nuxt-matomo](https://github.com/pimlie/nuxt-matomo). The author pushes the external script to the `head` object. I changed `head` to a function and `nuxt-matomo` didn't work.

https://github.com/pimlie/nuxt-matomo/blob/3d0e57cc11bdc2fc490cc35b917116c9d4b6f6bc/lib/module.js#L34

**Comment by neuromask** [comment]
Same here with PWA and G-tag, I tried to use head() as a function and got warning Avoid using head as a function!
Also g-tag stopped to work in analytics.
Solution: switched to layout mode, just use head object in config and head() function in default.vue layout

**Comment by elkhayder** [comment]
> But it's the https://github.com/nuxt-community/pwa-module that is complaining.

I confirm this one. I got rid of the warning after disabling the PWA module (I had no use for it)

Edit: typo

**Comment by kane-mason** [comment]
I am trying to access `this.$nuxtI18nHead` within the `head` function of `nuxt.config.js` but `this` is not defined, what am i doing wrong? I am using nuxt 2.15.8

**Comment by kane-mason** [comment]
so turns out this happens with `ssr:false`, i logged with nuxt team here https://github.com/nuxt/nuxt.js/issues/10843 but they just shut me down, anyone know anyhing?

**Comment by may820806** [comment]
today I tried to add head function in nuxt.config.ts acrroding to [docs](https://i18n.nuxtjs.org/seo#feature-details) for SEO tag
seems head must be an object
![截圖 2023-04-20 下午1 33 01](https://user-images.githubusercontent.com/62415107/233267931-d4487aeb-33a2-4c38-98bc-0f23c5251b34.png)

    "nuxt": "^3.4.0",
    "@nuxtjs/i18n": "^8.0.0-beta.11",

**Comment by ItsRyanWu** [comment]
@kane-mason @may820806 
Check out the new document here: https://v8.i18n.nuxtjs.org/guide/seo#setup

```
const head = useLocaleHead({
  addDirAttribute: true,
  identifierAttribute: 'id',
  addSeoAttributes: true,
})

useHead(head)
```

You must have been trapped by the outdated copy of documentation website
![image](https://github.com/nuxt-modules/i18n/assets/17338101/da1e9d89-d332-4fce-8212-e1609ea10e5b)

Related issues: https://github.com/nuxt-modules/i18n/issues/1675
