### ISSUE TITLE
og:locale:alternate?

### ISSUE THREAD

**Issue by MartinMalinda** [nuxt-modules/i18n#1272]
https://stackoverflow.com/questions/20827882/in-open-graph-markup-whats-the-use-of-oglocalealternate-without-the-locati

nuxt-i18n currently generated the first part of this: the meta tags for `og:locale:alternate`. But the `fb_locale` is not handled right?

I'm not sure if this is still responsibility of `nuxt-i18n` but I gues it could be 🤔

**Comment by MartinMalinda** [comment]
Hm it seems like `og:locale:alternate` is not used by facebook anymore. I guess it still exists in the spec but I couldn't find if it's practically used anywhere.

**Comment by rchl** [comment]
> But the `fb_locale` is not handled right?

How would you expect the module to handle it? As far as I understand, the `fb_locale` is supposed to affect the data returned by open graph tags (`og:*` tags). But this module doesn't specify any besides `og:locale:*` so I don't think that there is anything to do for this module.

If you are adding more specific open graph tags that describe your content then this is where you should handle that query parameter. At least that's how I understand it after just reading that thread.
