### ISSUE TITLE
How to extend routes

### ISSUE THREAD

**Issue by michele-spider** [nuxt-modules/i18n#1275]
Hello, i'm trying to handle page rewrites coming from an Api in nuxt.js with nuxt/i18n module.
So far i figured out to add routes via extendRoutes function in nuxt.config.
There i can add new routes but:
- i am unable to set a path related to a specific language
- nuxt warn me i cannot have more than one route for the same page

Soo i'm a bit lost here, online i didn't found so much and made me think im not focusing on the right spot.
Do you have any tip? Thanks!

**Comment by rchl** [comment]
I think you want to use this solution: https://i18n.nuxtjs.org/lang-switcher#dynamic-route-parameters

**Comment by michele-spider** [comment]
I am not trying to use it with dynamic routes.

example, /about.vue:
```
<script>
export default {
	name: 'About',
	nuxtI18n: {
		paths: {
			en: '/about-us',
			it: '/chi-siamo',
		},
	},
	async asyncData({ app, $axios }) {
		return { }
	},
	data: () => {
		return {}
	},
}
</script>
```
I want to set those page paths from an external api

**Comment by rchl** [comment]
The custom routes you can only define at build time so it's not gonna work for dynamic case like that. You have to use dynamic route for that.

**Comment by michele-spider** [comment]
Ok i think i understand.
Thank you!

**Comment by rchl** [comment]
BTW. I don't think the documentation is explaining that very clear so wouldn't mind suggestions for improvements.
