### ISSUE TITLE
Method Documentation missing

### ISSUE THREAD

**Issue by warlock1996** [nuxt-modules/i18n#1276]
https://i18n.nuxtjs.org/api#methods

if u go to api reference and then click on methods documentation, it is not on that page !

**Comment by rchl** [comment]
Where did you find the https://i18n.nuxtjs.org/api#methods link being referenced?

**Comment by rchl** [comment]
I found and fixed two references - https://github.com/nuxt-community/i18n-module/commit/c710ad18d30dc80c9e71502fbf0e722e596952c7

Hopefully that's all.
