### ISSUE TITLE
`switchLocalePath` does not change the page's `dir` attribute

### ISSUE THREAD

**Issue by majdal** [nuxt-modules/i18n#1277]
### Version
@nuxtjs/i18n: 6.27.0
nuxt: 2.14.12

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
i18n: {
    locales: [
      { code: "en", name: "English", dir: "ltr" },
      { code: "ar", name: "العربيّة", dir: "rtl" }
    ],
}
```

### Reproduction Link

I can create one if necessary

### Steps to reproduce

- Create an app with two language options, one has `dir: "rtl"`, the other `dir: "ltr"`
- Use `switchLocalePath` to switch locale path

### What is Expected?
The locale changes, and the `dir` attribute of the root html element should change as well. 

### What is actually happening?
`dir` does not change using `switchLocalePath`, but does change if page is refreshed. Looking at the [code](https://github.com/nuxt-community/i18n-module/blob/b4aae9dc748c2cee4d4c0b4ff9bb67b61a01969f/src/templates/plugin.routing.js#L118), looks like the implementation does not actually attempt to change the `dir` attribute.

**Comment by rchl** [comment]
`switchLocalePath` just generates a link to the same page in another locale. Navigating to that link is what changes the locale and potentially `dir` value.

Did you set up https://i18n.nuxtjs.org/seo? You need that if you want the `dir` to be changed.

**Comment by majdal** [comment]
Hello hello - thanks for the quick reply! 

After seeing this, I did update my code, and it worked as expected. 

However, while the logic of operations makes a lot of sense, but it's not very intuitive. I suggest that we add a section in the docs under the Lang Switcher that points out this logic. I'm happy to contribute that if you think it's appropriate. 

Many thanks!

**Comment by rchl** [comment]
Feel free to suggest an improvement (PR). We can evaluate whether it makes sense there.
