### ISSUE TITLE
Automatic redirect from main page to language page uses wrong hostname

### ISSUE THREAD

**Issue by cropr** [nuxt-modules/i18n#1283]
I have a multilingual SSG  website https://www.bycco.be with i18n.strategy = "prefix"  and i18n.defaultLocale = "nl"   running behind a proxy.

When I visit the main page https://www.bycco.be/ a redirect is happening to the default language (Dutch), but instead of redirecting it to https://www.bycco.be/nl/  it is redirected to http://127.0.0.01/nl/ which is of course failing.

All other pages and links work correctly, so I can assume that the issue is not with the proxy but with the i18n module.  I assume that the i18n has a detection/configuration function that instructs to use 127.0.0.1,

**Comment by rchl** [comment]
You probably have to set the `baseUrl` option (https://i18n.nuxtjs.org/options-reference#baseurl) correctly, based on the environment.

**Comment by cropr** [comment]
OK that soilved the issue. Thanks
