### ISSUE TITLE
detectBrowserLanguage with redirectOn 'root' not working when cookie disabled

### ISSUE THREAD

**Issue by philipptrenz** [nuxt-modules/i18n#1286]
### Version
@nuxtjs/i18n: ^6.27.1
nuxt: ^2.15.3

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
  i18n: {
    locales: ['en', 'de' , 'fr', 'es', 'it', 'ru', 'tr', 'ar' ],
    defaultLocale: 'en',
    strategy: 'prefix',
    vueI18n: i18n,
    detectBrowserLanguage: { 
      fallbackLocale: 'en', 
      redirectOn: 'root', 
      useCookie: false,
    }
  },
```

### Reproduction Link
see on [dev.covidpass.eu](https://dev.covidpass.eu)

### Steps to reproduce

- Navigate to [https://dev.covidpass.eu/de](https://dev.covidpass.eu/de) and you get redirected to the detected language
- Navigate to [https://dev.covidpass.eu/it](https://dev.covidpass.eu/it) and you get redirected to the detected language
- ...

### What is Expected?

Should only detect browser language when navigating to [https://dev.covidpass.eu/](https://dev.covidpass.eu/) and use locale in path when navigating to `/de`, `/it` and so on

### What is actually happening?

Browser language also gets detected on `/de`, `/it` etc and user gets redirected to the detected language subpath.

**Comment by rchl** [comment]
You have to migrate to version 7. Version 6 doesn't support `redirectOn`.

**Comment by rchl** [comment]
Or if you don't want to migrate yet, you can find documentation for v6 at https://i18n-legacy.nuxtjs.org/ . It has equivalent setting `onlyOnRoot`.

**Comment by philipptrenz** [comment]
Thanks for the quick reply! You're right, didn't notice that 😅
