### ISSUE TITLE
Issue with NUXT SSR site with i18n on firebase hosting.

### ISSUE THREAD

**Issue by mpro-madhu** [nuxt-modules/i18n#1289]
We have NUXT SSR site hosted on firebase hosting for which we wanted to use i18n library. We followed the set up instructions as per documentation https://i18n.nuxtjs.org/setup. The site was working as expected when we run in local machine. But when we hosted on firebase, the requests are resulting in 500 errors. Our logs have below entries.

```
at Object.<anonymous> (webpack:/external "js-cookie":1:0) 
at Object.<anonymous> (server.js:1499:18)
at node_modules/vue-server-renderer/build.prod.js:1:77623
at Function.resolveSync [as sync] (node_modules/resolve/lib/sync.js:102:15)
at __webpack_require__ (webpack/bootstrap:25:0)
at Module.<anonymous> (server.js:8594:27) 
ERROR  Cannot find module 'js-cookie' from '/workspace'


Below is our nuxt config 

i18n: {
    locales: [
      {
        code: 'en',
        file: 'en-US.js',
      },
    ],
    lazy: true,
    langDir: 'lang/',
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
    },
  },
```

Looking at the function log, we checked of js-cookie dependency is injected or not. But it is available but still we see this issue.

Anybody used this library with NUXT SSR and hosted on firebase hosting ? Anything different we need to do here ? 

Thanks,
Madhu

**Comment by rchl** [comment]
I don't have any experience with firebase. I suggest that you ask for help in the Nuxt Discord.

That said, does the site work without the i18n module?

**Comment by mpro-madhu** [comment]
@rchl Yes it does work without i18n module.
