### ISSUE TITLE
Infinite loop on routing

### ISSUE THREAD

**Issue by Maxime-Asphalte** [nuxt-modules/i18n#1292]
## Version
@nuxtjs/i18n: 7.0.3
nuxt: 2.15.8

## Step to reproduce

Go there : https://asphalte-rebrand.netlify.app/collections/eshop/

## Questions

https://github.com/nuxt-community/i18n-module/blob/c710ad18d30dc80c9e71502fbf0e722e596952c7/src/templates/plugin.main.js#L181

Are we sure about that test ?? If I understand correctly with my logic and the help of the comment, It should be :
````
if (redirectOn === Constants.REDIRECT_ON_OPTIONS.ALL || (locale === options.defaultLocale && options.strategy === Constants.STRATEGIES.PREFIX_AND_DEFAULT)) {
    return ''
}
````

I'm facing an issue where on a static build with prefix_and_default set as strategy my page reload infinitely...

If I try to print : `redirectPath` and `route.fullPath` I get respectively `/collections/eshop` and `/collection/eshop/`

How can I fix my infinite redirect loop ???

**Comment by rchl** [comment]
~~Your change to that logic is actually equivalent to the old one. Just written differently.~~ EDIT: no sorry, it's not. But it's not a correct suggestion. When dealing with the `defaultLocale` and `prefix_and_default` strategy we want to not return but let the code below handle the redirection.

I do find thought the `redirectOn === Constants.REDIRECT_ON_OPTIONS.ALL` condition a bit weird and potentially out of place. I'm investigating removing it in #1304. But that won't have any relevance to your issue...

As far as your actual issue, this can be tricky. Static generation and trailing slashes can act weirdly depending on the hosting and Nuxt configuration of `router.trailingSlash`.

You could try setting `router.trailingSlash` to true in nuxt.config and checking how that goes.

**Comment by Maxime-Asphalte** [comment]
Ok !! I'll roll back to the old version at the moment ! As I have to deploy a new design next week. 
I'll try today or tomorrow with the `router.trailingSlash` to see if it solve the issue. 

Is it a good idea for you to test if the last character of the url is a slash and if so removing it ? I'm not sure if it is... 

Thank you by the way !! ;)

**Comment by darrenchiu** [comment]
Hi @Maxime-Asphalte you mentioned that if you roll back to a previous version, then it would work. Which version you were using before? I also need to deploy a new version soon but this is a roadblocker to us....

thanks in advance for sharing the working previous version

**Comment by Maxime-Asphalte** [comment]
Hello,
I roll back to `nuxt-i18n@6.28.1`

You can see it live on https://www.asphalte.com 

I try to add `router.trailingSlash`, it seems to fix this case but that seems to break the navigation with multiples 404..

**Comment by darrenchiu** [comment]
Thanks @Maxime-Asphalte . I will try to use the 6.28.1 version

For router.trailingSlash, it's not really an option for me as it would produce a lot of 404 (i.e.you can either have url with trailing slash or without, not both). I think this is not an option for modern websites

**Comment by darrenchiu** [comment]
I tried with 6.28.1, it seems that it would only work if I also disable the detectBrowserLanguage setting altogether. Not sure if this is the root cause.
