### ISSUE TITLE
how to validate only part of the form ? scope validation ?

### ISSUE THREAD

**Issue by MathieuDerelle** [nuxt-modules/i18n#1295]
Is there an equivalent to scope validation in `vuelidate` ?
https://vuelidate-next.netlify.app/advanced_usage.html#validation-scopes

That is, give each field a "scope"; then validating a scope, will only trigger validation on fields tagged with this scope

**Comment by MathieuDerelle** [comment]
wow, wrong repo, sorry

**Comment by divine** [comment]
I was a bit shocked for a minute but you've made my day.
Hahaha!
