### ISSUE TITLE
Strategy `prefix` results in `404` for pages with disabled i18n `nuxti18n: false`

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-modules/i18n#1296]
### Version
@nuxtjs/i18n: 7.0.2 
nuxt: 2.15.7

 - [x ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
i18n: {
    strategy: 'prefix',
    ...
}
```

### Steps to reproduce
Set prefix strategy to `prefix`.
Set `nuxti18n: false` on a page example: `/login`

### What is Expected?
`/login` is still accessible and has no prefix.

### What is actually happening?
`/login` throws 404

# Asking for Workaround Ideas:
1. Set prefix strategy to `prefix_and_default` => fixes `404` for `/login` route.
Force prefix manually via `forcePrefix(currentLocale)` for other routes. Is there an API?

2. Set prefix strategy to `prefix` but generate routes manually for `nuxtI18n: false` routes.?

**Comment by rchl** [comment]
The name of the component option is `nuxtI18n`, not `nuxti18n`.
