### ISSUE TITLE
too many hreflang generation

### ISSUE THREAD

**Issue by AlexyOd** [nuxt-modules/i18n#1300]
Hi i can't finde answer on documentation

the plugin create 4(!) hreflang !! 
How to fix this ??? 

` locales: [
          {
            name: "lang",
            code: "ua",
            iso: "ua-FR",
            file: "ua-FR.js"
          },
          {
            name: "lang2",
            code: "fr",
            iso: "fr-FR",
            file: "fr-FR.js"
          }
        ],`

and i got in header 
`
link data-n-head="ssr" data-hid="alternate-hreflang-ua" rel="alternate" href="http://web.work/" hreflang="ua"
link data-n-head="ssr" data-hid="alternate-hreflang-ua-FR" rel="alternate" href="http://web.work/" hreflang="ua-FR"
link data-n-head="ssr" data-hid="alternate-hreflang-fr" rel="alternate" href="http://web.work/ua" hreflang="fr"
link data-n-head="ssr" data-hid="alternate-hreflang-fr-FR" rel="alternate" href="http://web.work/ua" hreflang="fr-FR"
`

but i need only 
        link data-n-head="ssr" data-hid="alternate-hreflang-ua-FR" rel="alternate" href="http://web.work/" hreflang="ua-FR"
link data-n-head="ssr" data-hid="alternate-hreflang-fr-FR" rel="alternate" href="http://web.work/ua" hreflang="fr-FR"

**Comment by rchl** [comment]
Those are catch-all locales and it works as designed and is explained at https://i18n.nuxtjs.org/seo/#feature-details.

**Comment by AlexyOd** [comment]
there is no answer there

**Comment by rchl** [comment]
The documention has a link to https://support.google.com/webmasters/answer/189077 that specifies that it's a recommended practice to include those catchall locales (search for "catchall" on that page).

**Comment by AlexyOd** [comment]
so, 4 hreflang is good ? and "works as designed and is explained at https://i18n.nuxtjs.org/seo/#feature-details." ??? 
![image](https://user-images.githubusercontent.com/13238444/134680481-9e65cb1f-50c0-4047-8a2e-abc3d6bd0e31.png)

**Comment by rchl** [comment]
Did you even read my last comment?

**Comment by AlexyOd** [comment]
yes

**Comment by AlexyOd** [comment]
i stell can't remove hreflang="en"

**Comment by rchl** [comment]
What's the issue you are trying to fix? You just don't like it being there? Then don't use `$nuxtI18nHead` and create your own meta from scratch.
As I said, it's by design and recommended by google.
