### ISSUE TITLE
Encoded components does not preserve in `params.pathMatch`

### ISSUE THREAD

**Issue by farnabaz** [nuxt-modules/i18n#1301]
### Version
@nuxtjs/i18n: ^7.0.3
nuxt: ^2.16.0-27205934.39779d8f

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [X] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [X] Applies to a site deployed to a server with a Node backend

### Reproduction Link

https://github.com/farnabaz/nuxt-i18n-url-encode

### Steps to reproduce

- Clone the repo
- Run `yarn & yarn dev`
- Visit the website and click on `encoded url`

### What is Expected?
Encoded components of url should be preserved.

```
{
  "path": "/en/encoded%2Furl",
  "params": {
    "pathMatch": "encoded%2Furl"
-------------------------^
  }
}
```

### What is actually happening?
`pathMatched` value contains decoded components and it leads to invalid url

```
{
  "path": "/en/encoded%2Furl",
  "params": {
    "pathMatch": "encoded/url"
-------------------------^
  }
}
```

**Comment by rchl** [comment]
Did you mean to report it in vue-router? I don't see i18n being relevant or used here.

**Comment by rchl** [comment]
Closing as it doesn't seem specific to this module.
