### ISSUE TITLE
Dynamic route parameters: how to use i18n/setRouteParams to skip param?

### ISSUE THREAD

**Issue by leopoldkristjansson** [nuxt-modules/i18n#1305]
I am referring to this part of the docs:

https://i18n.nuxtjs.org/lang-switcher/#dynamic-route-parameters

The following example from the docs is exactly what I need - except that it doesn't show what to do when the post does not exist in some language.

```js
<template>
  <!-- pages/post/_postId.vue -->
</template>

<script>
export default {
  async asyncData ({ store }) {
    await store.dispatch('i18n/setRouteParams', {
      en: { postId: 'my-post' },
      fr: { postId: 'mon-article' }
    })
    return {
      // your data
    }
  }
}
</script>

```

The example above translates the routes to `/post/my-post` and `/post/mon-article`.

How would I however achieve the following:

```js
<script>
export default {
  async asyncData ({ store }) {
    await store.dispatch('i18n/setRouteParams', {
      en: { postId: 'my-post' },
      fr: { postId: 'mon-article' },
      is: { // In this lang the post does not exist, I want the link to route to some specific page (e.g. my post overview page }      
    })
    return {
      // your data
    }
  }
}
</script>

```

**Comment by rchl** [comment]
Maybe just [redirect](https://nuxtjs.org/docs/internals-glossary/context/#redirect) if the current locale (`app.i18n.locale`) is not supported.

**Comment by leopoldkristjansson** [comment]
> 



> Maybe just [redirect](https://nuxtjs.org/docs/internals-glossary/context/#redirect) if the current locale (`app.i18n.locale`) is not supported.

Yes, redirecting would be great. But how would you set that up within the `setRouteParams` object?

**Comment by Fillsen** [comment]
same issue

**Comment by leopoldkristjansson** [comment]
Here is a hacky solution to this issue, since it seems to be alive still. If someone has something better, that would of course be great.

In short, if I do not have a translation for a certain language I set the `postId` to a fixed string (e.g. `'redirect-to-article-overview'`). I've than set up a `server-middleware` that removes that string from URL's.

In practice this means that the following URL:

`https://www.mywebsite.foo/articles/redirect-to-article-overview/`

redirects to

`https://www.mywebsite.foo/articles/`

```
<script>
export default {
  async asyncData ({ store }) {
    await store.dispatch('i18n/setRouteParams', {
      en: { postId: 'my-post' }, // I have the article in this language.
      fr: { postId: 'mon-article' }, // I have the article in this language.
      is: { postId: 'redirect-to-article-overview'' } // I do not have the article in this language.
    })
    return {
      // your data
    }
  }
}
</script>

```

The `server-middleware` would work something like this:

```
module.exports = function (req, res, next) {
    const isArticleNotFound = req.url.includes('redirect-to-article-overview')

    if (isArticleNotFound) {
        res.writeHead(307, { Location: req.url.replace('redirect-to-article-overview', '') });
        res.end();
    } else {
        next();
    }
}
```
