### ISSUE TITLE
Expose a nuxt hook when translation file is ready to be injected

### ISSUE THREAD

**Issue by existe-deja** [nuxt-modules/i18n#1308]
### Is your feature request related to a problem? Please describe.
I am developing an internal ui library and I need to have some translations inside it and for now I rely on slots
But, as the project grows, I'm copy pasting `$t('actions.submit')` (and many others) over and over.
I want my components to have a **default slot with translated content** that could be overridden by theirs parents.

### Describe the solution you'd like
As I already do for merging my components into the nuxt app or with tailwindcss when I merge the configs together, I'm wondering if something similar is doable with the i18n module?
```javascript
  // auto import components into the nuxt app
  nuxt.hook('components:dirs', (dirs) => {
    // Add ./components dir to the list
    dirs.push({
      path: join(__dirname, '../src/components')
    })
  })
```
Wanted solution
```javascript
// my-library/setup/index.js
import defu from 'defu'
import libraryLocales from 'path-to-library-locales.json'

export default function () {
  const { nuxt } = this

  nuxt.hook('i18n:locales-ready', (locales) => {
    Object.assign(locales, defu(locales, libraryLocales))
  })
}
```
```javascript
// my-nuxt-app/nuxt.config.js
export default {
  ...,
  buildModules: [
    '@my-org/my-library/setup'
  ]
}
```

### Describe alternatives you've considered
I can just rely on the app to include the good translations keys but it's risky and not futur proof. Otherwise I can keep copy paste the main translation in the nuxt app.

**Comment by rchl** [comment]
Handling the case when translations are provided as a plain object in the module settings would be easy but handling the case when translations are loaded from a `langDir` directory would be tricky to handle.

We don't load the translations from `langDir` at module processing stage so we wouldn't have access to `locales` in this case. It probably would be much easier to make work if the hook would look more like this:

```js
  nuxt.hook('i18n:extend-locales', () => {
    return libraryLocales
  })
```

**Comment by existe-deja** [comment]
I didn't have enough background on this but the solution you recommend sounds good to me.
