### ISSUE TITLE
Change locale in the middleware does not set locale in the browser

### ISSUE THREAD

**Issue by sdq-sts** [nuxt-modules/i18n#1310]
### Version
@nuxtjs/i18n: 7.0.3
nuxt: 2.15.7

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```js
import { Options } from '@nuxtjs/i18n';

export default {
  lazy: false,
  langDir: 'i18n/locales/',
  defaultLocale: 'en_US',
  strategy: 'no_prefix',
  vuex: {
    moduleName: 'i18n',
    syncLocale: true,
  },
  vueI18n: {
    fallbackLocale: 'en_US',
    fallbackRoot: true,
    silentFallbackWarn: true,
  },
  locales: [
    {
      code: 'en_US',
      iso: 'en-US',
      file: 'en_US.json',
      name: 'English',
    },
    {
      code: 'pt_BR',
      iso: 'pt-BR',
      file: 'pt_BR.json',
      name: 'Português Brasil',
    },
  ],
} as Options;
```

### Steps to reproduce
I'm trying to redirect the user based on a queryString using middleware. I know that the middleware runs in the server but I couldn't find a way to sync with the browser so even if I use `i18n.setLocale('pt_BR')` in the middleware the application sets it back to `en_US` in the browser. Code:

```js
export default async function languageMiddleware({ route, i18n }) {
  const { lang } = route.query;

  if (lang) {
    // the lang is pt_BR for example
    await i18n.setLocale(lang);
  }
}
```

### What is Expected?
To the browser load the page with the set language

### What is actually happening?
Browser is defaulting to the default language.

I found an issue saying to use the `vuex.syncLocale` but apparently it does not work anymore.
Am I using a bad strategy here or it is just a bug?

**Comment by rchl** [comment]
Maybe try to use the `onBeforeLanguageSwitch` hook. Something like:

```js
    onBeforeLanguageSwitch: function(oldLocale, newLocale, initialSetup, { route }) {
      const { lang } = route.query
      if (lang) {
        return lang
      }
    },
```
