### ISSUE TITLE
locales in in-component option does not work

### ISSUE THREAD

**Issue by otk-wa-ko** [nuxt-modules/i18n#1311]
I would like to make sure that translations are only applied to specific pages.
However, specifying nuxtI18n.locales in Component does not make it accessible in the specified language.
Is there an error in the way it is specified?

I have placed the environment in codesandbox, which reproduces this problem.

https://codesandbox.io/s/snowy-breeze-2xn36

I expect the following results.

| path | is accessible |
----|---- 
| / | true |
| /ja | false |
| /hasja | true |
| /ja/hasja | true |

However, in practice, the results are as follows.

| path | is accessible |
----|---- 
| / | true |
| /ja | false |
| /hasja | true |
| /ja/hasja | false |

I have set up the options as follows.

- nuxt.config.js

```
  modules: [
    [
      "@nuxtjs/i18n",
      {
        defaultLocale: "en",
        vueI18nLoader: true,
        locales: []
      }
    ]
  ],
```

- hasja.vue

```
<script>
export default {
  nuxtI18n: {
    locales: ["ja", "en"],
  },
};
</script>
```

nuxt: 2.15.8
@nuxtjs/i18n: 7.0.3

**Comment by rchl** [comment]
The idea is that the global options specify available locales and the page can can select a subset of those that are enabled. It won't work with empty global `locales`.

**Comment by otk-wa-ko** [comment]
I understand now. Thank you for your answer.
