### ISSUE TITLE
`app.localePath()` return with trailing slash when redirected (nested route)

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/i18n#1312]
### Version
@nuxtjs/i18n: 7.0.1
nuxt: 2.15.3

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```js
// nuxt.config.js
i18n: {
    // Options
    vueI18nLoader: true,
    locales: [
        {
            code: 'fr',
            name: 'Français',
            iso: 'fr-CA',
        },
        {
            code: 'en',
            name: 'English',
            iso: 'en-CA',
        },
    ],
    defaultLocale: 'fr',
}

// router.js
{
    path: '/repertoire',
    component: Directory,
    children: [
        {
            path: '',
            name: 'directory___fr',
            redirect: { name: 'directory-professionals___fr' },
        },
        {
            path: 'professionnels',
            name: 'directory-professionals___fr',
            component: DirectoryProfessionals,
        },
        {
            path: 'organismes',
            name: 'directory-organizations___fr',
            component: DirectoryOrganizations,
        },
        {
            path: 'outils',
            name: 'directory-tools___fr',
            component: DirectoryTools,
        },
    ],
},
{
    path: '/en/directory',
    component: Directory,
    children: [
        {
            path: '',
            name: 'directory___en',
            redirect: { name: 'directory-professionals___en' },
        },
        {
            path: 'professionals',
            name: 'directory-professionals___en',
            component: DirectoryProfessionals,
        },
        {
            path: 'organizations',
            name: 'directory-organizations___en',
            component: DirectoryOrganizations,
        },
        {
            path: 'tools',
            name: 'directory-tools___en',
            component: DirectoryTools,
        },
    ],
},
```

### Reproduction Link

https://codesandbox.io/s/angry-haibt-d2t97?file=/router.js

### Steps to reproduce
- Create a router with nested route
- Add a redirect to the default children route
- This might be related to #1248

### What is Expected?
`app.localePath({ name: 'directory' })` return the `redirectedFrom` which contain a trailing slash.
I don't think there should be a trailing slash since `route.matched` doesn't contain the trailing slash.

### What is actually happening?
Here's what I'm trying to do in a middleware
```
const isDirectory = route.matched.some((r) => {
    console.log(r.path, app.localePath({ name: 'directory' }));
    // output (iteration 1): `/repertoire`, `/repertoire/`
    // output (iteration 2): `/repertoire/professionnels`, `/repertoire/`
    return r.path === app.localePath({ name: 'directory' }); // output: false
});
```
Here is the output or `route.matched` as additional context:
```
[
  {
    path: '/repertoire',
    regex: /^\/repertoire(?:\/(?=$))?$/i { keys: [] },
    components: { default: [Function] },
    alias: [],
    instances: {},
    enteredCbs: {},
    name: undefined,
    parent: undefined,
    matchAs: undefined,
    redirect: undefined,
    beforeEnter: undefined,
    meta: {},
    props: {}
  },
  {
    path: '/repertoire/professionnels',
    regex: /^\/repertoire\/professionnels(?:\/(?=$))?$/i { keys: [] },
    components: { default: [Function] },
    alias: [],
    instances: {},
    enteredCbs: {},
    name: 'directory-professionals___fr',
    parent: {
      path: '/repertoire',
      regex: /^\/repertoire(?:\/(?=$))?$/i,
      components: [Object],
      alias: [],
      instances: {},
      enteredCbs: {},
      name: undefined,
      parent: undefined,
      matchAs: undefined,
      redirect: undefined,
      beforeEnter: undefined,
      meta: {},
      props: {}
    },
    matchAs: undefined,
    redirect: undefined,
    beforeEnter: undefined,
    meta: {},
    props: {}
  }
]
```

**Comment by mrleblanc101** [comment]
I also notice that my `<nuxt-link :to="localePath({ name: 'directory' })" />` will output the link with a trailing slash which should be the case.
![Capture d’écran, le 2021-10-06 à 11 03 17](https://user-images.githubusercontent.com/17392251/136230661-4f6c239c-2df9-4508-8e30-59c2c84604e2.png)

**Comment by rchl** [comment]
Will you be able to get around to creating a repro? I'm not sure how exactly are you creating those routes.

> I also notice that my `<nuxt-link :to="localePath({ name: 'directory' })" />` will output the link with a trailing slash which should be the case.

Should or should not?

**Comment by mrleblanc101** [comment]
https://codesandbox.io/s/angry-haibt-d2t97?file=/router.js

**Comment by rchl** [comment]
I've looked at it finally but it seem that VueRouter just returns those seemingly inconsistent results.

The screenshot below is a result of calling `router.resolve` with a `{ name: 'directory___en' }` argument:

![Screenshot 2022-01-13 at 23 45 06](https://user-images.githubusercontent.com/153197/149420901-42efb4ba-4fa2-4aca-854b-d0c2091496bf.png)

It contains paths both with and without the trailing slash.

I don't know if it's a bug or it has a good reason for doing that.

**Comment by mrleblanc101** [comment]
I've noticed that. Doesn't Vue-router has an option to always add/remove trailing slash at the end of URL ? 
Maybe nuxt-i18n should check the value a post-process the URL to match the value in the URL even if router.resolve is inconsistent.

**Comment by rchl** [comment]
I don't want to do any hacking like that, not unless I understand the reasoning for VueRouter doing it (whether it's a bug or on purpose).

The next step should be to just create a minimal reproduction and report this to VueRouter and see what they say.
