### ISSUE TITLE
Environment variables in lazy-loading-file are undefined

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-modules/i18n#1317]
### Version
@nuxtjs/i18n: ^6.28.0
nuxt: "^2.15.7"

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ x] Applies to a site deployed to a server with a Node backend

### Steps to reproduce
Like here https://i18n.nuxtjs.org/lazy-load-translations

I have a `lang/en-US.js` file and am lazy loading the translations from a server, and hoped to use environment variables for the URL.

```js
const TRANSLATION = await context.$axios.$post(
    process.env.API + '/translation/en',
  )

```

### What is Expected?
The environment variable `process.env.API` is read correctly. 

### What is actually happening?
`process.env.API` is `undefined`

**Comment by rchl** [comment]
That lang file is treated the same as any other file processed by webpack (any file that is not a server middleware but is part of the bundle) so this is expected.

Since you have access to `context`, just add that variable to `env` object in `nuxt.config.js` and you will have access to it through `context.env`.

**Comment by sugoidesune** [comment]
Thats a perfect workaround. I did expect the `process.env` to work if the file is going through webpack though.

oh well, Thank you!

**Comment by rchl** [comment]
I forgot how exactly Nuxt works with those but it could be that after you add it to the `env` configuration option then it will also work automatically, without having to get it from `context.env`.

At the end of https://nuxtjs.org/docs/configuration-glossary/configuration-env#processenv-- it's mentioned that webpack will replace instances of process.env.foo but only if added to to the env configuration first.
