### ISSUE TITLE
throwing Error after adding it to a newly created nuxt 3 project

### ISSUE THREAD

**Issue by shidcordero** [nuxt-modules/i18n#1320]
I am getting this error when added in a newly created nuxt 3 project

```
Cannot restart nuxt:  Cannot read properties of undefined (reading 'resolveAlias')                                                                                                                                                                         15:23:23  
  at Object._default (node_modules\@nuxtjs\i18n\src\index.js:34:42)
```
Version:
"@nuxtjs/i18n": "^7.0.3"

Added in tsconfig.json

```
    "types": [
      "node",
      "@nuxt/types",
      "@nuxtjs/i18n",
   ]
```

**Comment by bastienrobert** [comment]
Related with [i18n-module/discussions#1287](https://github.com/nuxt-community/i18n-module/discussions/1287)

**Comment by rchl** [comment]
Nuxt 3 is not supported at the time of writing.
Work on Nuxt 3-compatible version is progressing in https://github.com/nuxt-community/i18n-module/tree/next branch (released as [@nuxtjs/i18n-edge](https://www.npmjs.com/package/@nuxtjs/i18n-edge) package)
