### ISSUE TITLE
Dynamic routes loading wrong local because of locale as substring of route

### ISSUE THREAD

**Issue by janericwinkelmann** [nuxt-modules/i18n#1321]
### Version
@nuxtjs/i18n: 
nuxt: 

 - [x ] Applies to a site deployed to a server with a Node backend

### What is actually happening?
I have a very dynamic nuxt page where all pages and slugs are resolved through a headless cos system. Therefore in my pages folder I only have a "_.vue" to handle every route.

Everything is working fine, all routes, all locales are resolved correctly except for one url:
If my slug starts with something like "/entspannen" it should resolve to the default locale, in this instance German (de). But nuxt i18n interprets the the starting of the slug "/en" as a English page. However the English version is located at "/en/entspannen". 

I believe the i18n module should only search for the exact matches of locales in the route path. Right now it seams like it's also picking up dynamic routes with en as a starting substring. 

Maybe I have configured something wrong. A quick help would me much appreciated. :)

**Comment by rchl** [comment]
How do the routes like in your `.nuxt/router.js`?
It's the part that starts with `export const routerOptions`.

**Comment by janericwinkelmann** [comment]
Hi @rchl,

have a look at the generated routes:

```
routes: [{
    path: "/en*/",
    component: _17b09162,
    name: "home___en"
  }, {
    path: "/en/*/",
    component: _17b09162,
    pathToRegexpOptions: {"strict":true},
    name: "all___en"
  }, {
    path: "/*/",
    component: _17b09162,
    pathToRegexpOptions: {"strict":true},
    name: "all___de"
  }, {
    path: "*/",
    component: _17b09162,
    name: "home___de"
  }],
```

Looks like the first path for the "en" local should be something like path: `"/en/"` instead if I am not wrong?

**Comment by rchl** [comment]
That would be the issue, yes.
Where does the `home` route come from?
