### ISSUE TITLE
Get undefined error on fresh install v7.0.1

### ISSUE THREAD

**Issue by Sovai** [nuxt-modules/i18n#1331]
### Version
@nuxtjs/i18n: 
nuxt: 

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
...
modules: [
    '@nuxtjs/axios',
    '@nuxtjs/i18n',
  ],
i18n: {
    locales: ['en', 'fr', 'es'],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          welcome: 'Welcome',
        },
        fr: {
          welcome: 'Bienvenue',
        },
        es: {
          welcome: 'Bienvenido',
        },
      },
    },
  },
...
```

### Steps to reproduce
1. yarn create-nuxt-app nuxt-i18n 
2. Fresh install the latest version (v7.0.1 at the time of this post)
3. Setup in nuxt.config.js copied from official nuxt/i18n site as above 
4. yarn dev

### What is Expected?
no error in the console log

### What is actually happening?
I got a console error 
![image](https://user-images.githubusercontent.com/8064796/138802935-534224dc-f8fe-4dea-8678-71865887f8a2.png)

**Comment by rchl** [comment]
Make sure that you are using at least Node 14.
If it still reproduces, provide a repo since following the steps doesn't reproduce.

**Comment by Sovai** [comment]
Turned out the error is from my browser extension. Thank you, I'll close the issue
