### ISSUE TITLE
Nuxt start nuxti18n unknown middleware error

### ISSUE THREAD

**Issue by seonglae** [nuxt-modules/i18n#1337]
### Version
@nuxtjs/i18n: 7.1.0
nuxt: 2.15.8

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```js
{
      vueI18nLoader: true,
      defaultLocale: 'ko',
      strategy: 'no_prefix',
      vueI18n: {
        fallbackLocale: 'ko',
        messages: {
          en: {
            apply: 'Apply',
            remove: 'Remove',
            upload: 'Upload',
            cancel: 'Cancel'
          },
          ko: {
            apply: '적용',
            remove: '제거',
            upload: '업로드',
            cancel: '취소'
          }
        }
      },
      locales: [
        { code: 'en', iso: 'en-US' },
        { code: 'ko', iso: 'ko-KR' }
      ]
    }
target: 'server',
  ssr: false,
```
![image](https://user-images.githubusercontent.com/27716524/139811772-2deab7e5-d489-4b4e-a2da-c094fac3f712.png)

When I run as `nuxt dev` - error does not appear, but when I run `nuxt build` and `nuxt start` I only can see this page

**Comment by rchl** [comment]
Where did you register the module in nuxt config? Should be in `modules`, not `buildModules`.

**Comment by seonglae** [comment]
Of course current in `modules` not `buildModules`

**Comment by rchl** [comment]
I can't reproduce. Can you create a repo that reproduces or provide more complete configuration?

**Comment by rchl** [comment]
Also, how do you start the server exactly after building?

**Comment by seonglae** [comment]
I  reproduced with repository
https://github.com/seonglae/nuxt-i18n-error

**Comment by rchl** [comment]
Thanks for a nice reproduction.

It looks like it happens due to `"sideEffects": false` in package.json but I haven't looked deeper.

The way the middleware is added is kinda magic due to Nuxt not providing a proper way to register a middleware. I guess that problems like that might be expected when treeshaking but hard to say without digging into webpack.

**Comment by seonglae** [comment]
Wow thanks for solution even though that was not exact nuxt i18n problem!
