### ISSUE TITLE
Pinia Store Support for dynamic route params.

### ISSUE THREAD

**Issue by D4RKAR117** [nuxt-modules/i18n#1338]
### Is your feature request related to a problem? Please describe.

When using [pinia ](https://pinia.esm.dev/) store, is very difficult to achieve a fast  dynamic routing paramaters change as described [here ](https://i18n.nuxtjs.org/lang-switcher#dynamic-route-parameters).

### Describe the solution you'd like

When the plugin of nuxt pinia is installed like is described [here](https://pinia.esm.dev/ssr/nuxt.html#installation), prefer that the mutation/action of vuex `i18n/setRouteParams` is performed at pinia over vuex, only if the option of using alongside vuex is at his default value `false` like is described [here](https://pinia.esm.dev/ssr/nuxt.html#using-pinia-alongside-vuex).

### Describe alternatives you've considered

Describe at the docs that when using pinia you must enable vuex usage alongside pinia like is described [here](https://pinia.esm.dev/ssr/nuxt.html#using-pinia-alongside-vuex).

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
