### ISSUE TITLE
 localeLocation is not defined

### ISSUE THREAD

**Issue by zhaoxiaoxiao123** [nuxt-modules/i18n#1339]
<a href="#" @click="$router.push(localeLocation('purchase'))">Navigate</a> 正常跳转

跳转异常 ReferenceError: localeLocation is not defined
<a href="#" @click="jump">Navigate</a> 
jump() {this.$router.push(localeLocation('purchase'))}

**Comment by rchl** [comment]
Please fill out the issue template when reporting an issue.
