### ISSUE TITLE
Extreme memory usage

### ISSUE THREAD

**Issue by ahas** [nuxt-modules/i18n#1343]
### Version
@nuxtjs/i18n: 7.2.0
nuxt: 2.15.7

### Nuxt configuration
Just default configuration created by create-nuxt-app
```js
import colors from "vuetify/es5/util/colors";

export default {
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    titleTemplate: "%s - nuxt-i18n",
    title: "nuxt-i18n",
    htmlAttrs: {
      lang: "en",
    },
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { hid: "description", name: "description", content: "" },
      { name: "format-detection", content: "telephone=no" },
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }],
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    "@nuxt/typescript-build",
    // https://go.nuxtjs.dev/vuetify
    "@nuxtjs/vuetify",
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    "@nuxtjs/axios",
    "@nuxtjs/i18n",
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {},

  // Vuetify module configuration: https://go.nuxtjs.dev/config-vuetify
  vuetify: {
    customVariables: ["~/assets/variables.scss"],
    theme: {
      dark: true,
      themes: {
        dark: {
          primary: colors.blue.darken2,
          accent: colors.grey.darken3,
          secondary: colors.amber.darken3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3,
        },
      },
    },
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {},
};
```

### @nuxtjs/i18n configuration
No config, it will be happen when you just add module.

### Steps to reproduce
1. create-nuxt-app, follow configurations below

create-nuxt-app v3.7.1
✨  Generating Nuxt.js project in .
? Project name: nuxt-i18n
? Programming language: TypeScript
? Package manager: Yarn
? UI framework: Vuetify.js
? Nuxt.js modules: Axios - Promise based HTTP client
? Linting tools: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? What is your GitHub username? ahas
? Version control system: None

2. yarn add @nuxtjs/i18n
3. add @nuxtjs/i18n to modules in nuxt.config.js
4. yarn dev or npm start dev
5. locate browser to nuxt page (default localhost:3000)
6. refresh refresh and refresh again

### What is Expected?
Memory will be released by garbage collector

### What is actually happening?
memory usage is over 4GB
then FATAL ERROR: Reached heap limit Allocation failed

**Comment by ahas** [comment]
Quick Fix: Adding { build: { standalone: true } } option can solve the problem.

**Comment by rchl** [comment]
Development mode plugin leak: https://github.com/nuxt-community/i18n-module/issues/1039

**Comment by rahulkumarsingh73690** [comment]
+1

**Comment by matystu** [comment]
+1
