### ISSUE TITLE
Is it possible to use <i18n> inside pages?

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt-modules/i18n#1350]
```
<i18n>
{
  "en": {
    "hello": "hello world!"
  },
  "es": {
    "hello": "Hola"
  }
}
</i18n>
```

This doesn't work inside pages

**Comment by rchl** [comment]
Where else would it be used?

Have you read documentation?

https://i18n.nuxtjs.org/per-component-translations

**Comment by rahulkumarsingh73690** [comment]
Thanks 

`i18n: {
  vueI18nLoader: true
}`
