### ISSUE TITLE
Enable nuxt i18n translation in few pages

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt-modules/i18n#1360]
Hi,

I have a nuxt.js site with more than 150+ pages and I want to translate only 10 pages in different languages. 

Can you please guide me?

I don't want to place this on `nuxtI18n: false` on more than 140 pages. Please suggest anything better.

**Comment by rahulkumarsingh73690** [comment]
@rchl

**Comment by rchl** [comment]
Don't think that's possible right now.

PRs welcome.

**Comment by rchl** [comment]
Note that due https://github.com/nuxt-community/i18n-module/issues/984, there might be issues when dealing with routes on which i18n is disabled. At least `detectBrowserLanguage` would probably have to be disabled.

**Comment by rahulkumarsingh73690** [comment]
I think this feature is required. Please add feature request in this issue

**Comment by rahulkumarsingh73690** [comment]
Any update?

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
