### ISSUE TITLE
Router replace and router push resets component state

### ISSUE THREAD

**Issue by radonichn** [nuxt-modules/i18n#1361]
### Version
@nuxtjs/i18n: 7.2.0
nuxt: 2.15.8

### @nuxtjs/i18n configuration

`
i18n: {
    locales: [
      {
        code: 'uk',
        iso: 'uk',
        file: 'uk.js',
      },
      {
        code: 'ru',
        iso: 'ru',
        file: 'ru.js',
      },
      {
        code: 'en',
        iso: 'en',
        file: 'en.js',
      },
    ],
    defaultLocale: 'uk',
    langDir: 'lang/',
  },
`

### Files structure
![image](https://user-images.githubusercontent.com/30216975/145980325-49921117-244e-42c3-9249-de7abb8aa9da.png)

### Routes definition in file
```
nuxtI18n: {
  paths: {
    uk: '/test/:id',
    ru: '/testasd/:id',
    en: '/teszxtasd/:id',
  },
},
```

![image](https://user-images.githubusercontent.com/30216975/145980550-8710df76-bc67-4c47-9754-5a7cffa67c01.png)

### Reproduction link
https://codesandbox.io/s/wispy-platform-6f0t7?file=/pages/test/_id.vue

### Steps to reproduce
Go to the page https://6f0t7.sse.codesandbox.io/test/2 and click the button. In console, you will see the watcher, which worked then the data property was updated.

### What is Expected?
The component's data doesn't change.

### What is actually happening?
The component's data resets to the default (init) state.

**Comment by rchl** [comment]
Can you provide a simple repo?
Does it only reproduce with i18n enabled?

**Comment by radonichn** [comment]
only if I define routes with i18n, otherwise everything is ok

**Comment by radonichn** [comment]
@rhcl updated the bug description - added repro link

**Comment by rchl** [comment]
You have not even registered the module in `modules` so `nuxtI18n` does nothing which means it reproduces also without this module.

**Comment by radonichn** [comment]
hmmm..., sorry I tried to reproduce it on local machine without i18n and it worked
thanks
