### ISSUE TITLE
Our website has 13 languages and many pages. I18in generates a lot of routes, which greatly affects the js running speed of the website

### ISSUE THREAD

**Issue by yaowei520** [nuxt-modules/i18n#1363]
Our website has 13 languages and many pages. I18in generates a lot of routes, which greatly affects the js running speed of the website
![image](https://user-images.githubusercontent.com/20491714/146030116-0c24508e-9f40-4244-ba9c-74579204006f.png)

**Comment by ccaa7530** [comment]
I don't have this problem, maybe you can try lazy translation.
See https://i18n.nuxtjs.org/lazy-load-translations
<details>
  <summary>screenshots</summary>
  
<img width="400" alt="截圖 2021-12-15 下午5 10 35" src="https://user-images.githubusercontent.com/23519638/146157430-c237f095-4ed7-404c-aae1-7eec215a0c5f.png">
<img width="251" alt="截圖 2021-12-15 下午5 14 56" src="https://user-images.githubusercontent.com/23519638/146157839-a4449863-bc60-406e-b2d3-e6722b7fff11.png">
</details>

**Comment by rchl** [comment]
Large number of routes is known to cause performance issues. See #690.
