### ISSUE TITLE
BrowserDetection only works at client runtime not with Accept-Language Header

### ISSUE THREAD

**Issue by janwendt** [nuxt-modules/i18n#1364]
### Version
@nuxtjs/i18n: 7.2.0
nuxt: 2.15.8

### Nuxt configuration

Please change to `[x]` if relevant for this issue:
 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
i18n: {
  baseUrl: 'https://settlers-united.com',
  locales: [
    {code: 'en', iso: 'en', file: 'en.js'},
    {code: 'de', iso: 'de', file: 'de.js'},
  ],
  defaultLocale: 'en',    
  strategy: 'prefix_except_default',
  langDir: 'lang/',
  detectBrowserLanguage: {
    fallbackLocale: 'en',
    useCookie: true,
    cookieKey: 'i18n_redirected',
    alwaysRedirect: true,
    redirectOn: 'all'
  }
},
```

### Reproduction Link
https://settlers-united.com with GERMAN BROWSER LANGUAGE

### Steps to reproduce
Visit https://settlers-united.com with GERMAN BROWSER LANGUAGE. Tip: make a bookmark with https://settlers-united.com and click it several times with a german brwoser then it is easy to recognize. Nothing changes even if i set useCookie to false.

### What is Expected?
Server should answer with https://settlers-united.com/de because of "Accept-Language | de,en-US;q=0.7,en;q=0.3".

### What is actually happening?
Server answers with https://settlers-united.com (english) page and after a short time when the website gets executed the redirect happens to https://settlers-united.com/de. This means that the English version is shown briefly and only then the redirect to the german version takes place.

**Comment by rchl** [comment]
Static pages don't have access to request headers. The only way to handle that is to redirect after the page has loaded since the page Javascript needs to run to get the language from the browser API.

**Comment by rchl** [comment]
If you want your expected behavior then you need to handle language detection and redirection on the web server (apache/nginx) level.
