### ISSUE TITLE
How to watch locale changing

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [nuxt-modules/i18n#1365]
Is there any way to watch locale changing?

Our app create messages array from users current locale.

like this
```
<select v-model="currentOption">
  <option v-for="option in options" :value="option.value">{{option.label}}</option>  ​
</select>
<p>{{ getCurrentOptionLabel() }}</p>
```

```
private options =[
    {
      value: 1,
      label: this.$tc("xxx.yyy.zzz")
    }
  ]

private getCurrentOptionLabel() {
  options.find((option) => 
    option.value === this.currentOption)
}
```

And we don't use prefix.
```
strategy: 'no_prefix',
```

Unless locale isn't changed, this code works well.
But, locale changed, the options is still previous language.

I must detect locale changing and re create option, 
but I have no idea to do this.

**Comment by rchl** [comment]
Can possibly change `label` to be a function. Then it would be evaluated every time the Vue component is updated rather than only on initial creation of `options`.

This is not really a question specific to this module but rather to Vue reactivity.

**Comment by rchl** [comment]
There is also a hook (https://i18n.nuxtjs.org/options-reference/#onlanguageswitched) that can be used to notify when locale changes. You could potentially update the properties when it is triggered.
