### ISSUE TITLE
@nuxtjs/i18n doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module

### ISSUE THREAD

**Issue by n4an** [nuxt-modules/i18n#1367]
### Version
@nuxtjs/i18n: 
nuxt: 
"@nuxtjs/i18n": "^7.2.0",
"nuxt-edge": "latest",
"@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27338323.1e98259",

### @nuxtjs/i18n configuration

-->
i18n: {
    defaultLocale: 'en',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
      // onlyOnRoot: true
    },
    langDir: 'locales/',
    lazy: true,
    locales: [
      {
        code: 'en',
        file: 'en.js',
        iso: 'en-US',
        name: 'English'
      }
    ],
    noPrefixDefaultLocale: false,
    parsePages: false,
    pages: {
      about: {
        en: '/about-us'
      }
    },
    seo: false,
    strategy: 'prefix',
    vueI18n: {
      fallbackLocale: 'en'
      // silentFallbackWarn: true
    },
    vueI18nLoader: true
  },

### What is actually happening?
[SSR] Error transforming /var/www/html/test/nuxt/.nuxt/middleware.js: Failed to resolve import "/var/www/html/test/nuxt/src/middleware/nuxti18n" from ".nuxt/middleware.js". Does the file exist?

**Comment by rchl** [comment]
Does it reproduce with latest stable Nuxt? If not then maybe it should be reported as a Nuxt issue instead? I don't really want to spend time on bugs that might affect some nightly builds only.

**Comment by rchl** [comment]
Work on Bridge-compatible version is ongoing on `next` branch (https://github.com/nuxt-community/i18n-module/tree/next)
