### ISSUE TITLE
dir attribute not adding to head tag

### ISSUE THREAD

**Issue by daeehamid** [nuxt-modules/i18n#1370]
### Version
@nuxtjs/i18n: ^7.2.0
nuxt: 2.15.8

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
i18n: {
locales: [
    {
      code: 'fa',
      iso: 'fa-IR',
      dir: 'rtl',
      name: 'Persian',
      file: 'fa.js'
    },
    {
      code: 'en',
      iso: 'en-US',
      dir: 'ltr',
      name: 'English',
      file: 'en.js'
    }
  ],
  seo: true,
  detectBrowserLanguage: false,
  defaultLocale: 'fa',
  langDir: 'lang/',
  vueI18n: {
    fallbackLocale: 'fa',
  }
}
```

### Steps to reproduce
this is head section in my default layouts
```
  head() {
    const i18nHead = this.$nuxtI18nHead({addSeoAttributes: true})
    return {
      ...i18nHead
    }
  },
```

### What is Expected?
```
<html lang="fa-IR" dir="rtl">
```

### What is actually happening?
```
<html lang="fa-IR">
```

**Comment by divine** [comment]
Hello,

Maybe you had a chance to read the [documentation](https://i18n.nuxtjs.org/api#nuxti18nhead).

`const i18nHead = this.$nuxtI18nHead({addSeoAttributes: true, addDirAttribute: true})`

Thanks!

**Comment by rchl** [comment]
Let us know if that doesn't address your issue.

**Comment by daeehamid** [comment]
thanks @rchl , my problem was solved 🙏🙏
