### ISSUE TITLE
Browser language detection

### ISSUE THREAD

**Issue by tillmon** [nuxt-modules/i18n#1372]
### Problem

Using browser language detection and default language of **not** `en`, Google crawler is redirected to the `en` version, not crawling the default locale version. Google crawler is not setting the `accept-language` header, therefore I suspect this is happening because of the `navigator` setting.

### Solution

This module is checking the `navigator` setting first and afterwards the `accept-language` header. But no `accept-langauge` header is an indicator for a crawler and should be checked first.

https://github.com/nuxt-community/i18n-module/blob/78a83639e3d802ac4e28d098bf949a8d5fdb2be9/src/templates/plugin.main.js#L249-L258

### Alternatives

Add an option to choose how the language is detected, either by `navigator`or `accept-language` header or both.

**Comment by rchl** [comment]
The order of the code is not relevant because one of those checks only runs on the client-side and the other one runs only on the server-side. Flipping the order would not change anything.

Do you know if google is getting redirected on the server or client side?

Do you have snapshot of the headers that Google is sending on crawling?

**Comment by tillmon** [comment]
> The order of the code is not relevant because one of those checks only runs on the client-side and the other one runs only on the server-side. Flipping the order would not change anything.

True, I overlooked this.

> Do you know if google is getting redirected on the server or client side?

I use a static build, so it must be on client side. I suspect browser language detection is not usable then.

> Do you have snapshot of the headers that Google is sending on crawling?

Unfortunately not.

**Comment by tillmon** [comment]
My solution is to set `detectBrowserLanguage: false` and use a server side redirect.

Here the example for Vercel:

```javascript
    {
      "source": "/",
      "has": [
        {
          "type": "header",
          "key": "accept-language",
          "value": "^en"
        }
      ],
      "destination": "/en",
      "permanent": false
    }
```
