### ISSUE TITLE
always redirect index page from locale page

### ISSUE THREAD

**Issue by kim00425** [nuxt-modules/i18n#1373]
mode:spa

i have problem. i config strategy prefix except default. And i try to enter locale pages. but pages redirect index page. my app have correctly router and i did check it.
what should i check more?

this is my module options:

['@nuxtjs/i18n', {
      strategy: 'prefix_except_default',
      vueI18nLoader: true,
      defaultLocale: 'ko',
      locales: [
        { code: '', iso: 'ko-KR', file: 'ko-KR.json' },
        { code: 'en', iso: 'en-US', file: 'en-US.json' },
      ],
      lazy: true,
      langDir: 'i18n',
      detectBrowserLanguage: {
        useCookie: true,
        onlyOnRoot: true,
        alwaysRedirect: true
      }
    }],

**Comment by rchl** [comment]
Please create a project that reproduces your issue. I don't know what is your issue.

**Comment by kim00425** [comment]
> Please create a project that reproduces your issue. I don't know what is your issue.

i solved this issue.
