### ISSUE TITLE
Missing fallback routes for custom paths of non-default locales

### ISSUE THREAD

**Issue by gekkedev** [nuxt-modules/i18n#1376]
### Version
@nuxtjs/i18n:7.2.0
nuxt: 2.15.8

### Nuxt configuration

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
i18n: {
    strategy: 'prefix'
    //+some locales
}
```
component:
```
nuxtI18n: {
    paths: {
      "en": "/about",
      "es": "/sobre",
    },
  },
```

### Steps to reproduce

1. implement `i18n-module` using prefixed routes
2. start using [custom route paths](https://i18n.nuxtjs.org/custom-paths)
  - e.g. `/es/sobre` instead of previously `/es/about`
3. visit a non-default locale path on it's previous URL (which might be listed in search engines already)

### What is Expected?
Forwarding of default-locale URLs to their custom URL (`/es/sobre`)
  - or alternatively switching to the default locale instead (`/en/about`)

### What is actually happening?
Non-default locales with custom paths will no longer work with their old URL (availability disruption). They just yield an error page as if the URL was made up.

**Comment by rchl** [comment]
This issue only applies in this specific case when route was renamed. It's not really a job of the module to handle that IMO. You should probably manually add a redirect route using `extendRoutes` for those cases.

**Comment by gekkedev** [comment]
Well, the issue I see is that although we may call URL localization "renaming", it is an unconscious renaming because we are so used to fallbacks but suddenly there is no handling. This is not only affecting people when localizing from a default-locale route, but also when adding one more language -> then they're unable to do so without covering everything by a custom handler in [`extendRoutes`](https://nuxtjs.org/docs/configuration-glossary/configuration-router/#extendroutes).
Maybe generating small files with a [clientside redirect tag](https://www.w3.org/TR/WCAG20-TECHS/H76.html) would be acceptable? :slightly_smiling_face: 

Even without handling this in the code, would you accept a PR adding a hint regarding SEO risks (if not handled by custom code) to this section?

**Comment by rchl** [comment]
I'll mark this as feature request.

I'd accept clarification in the documentation or a PR that adds an option for creating those fallback routes.

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
