### ISSUE TITLE
 navigation guard issue

### ISSUE THREAD

**Issue by kim00425** [nuxt-modules/i18n#1379]
when i try to setLocale(locale)

i got warning 

Error: Redirected when going from "/" to "/en" via a navigation guard.

this is my settings

i18n: {
    strategy: 'prefix_and_default',
    vueI18nLoader: true,
    locales: [
      { code: 'ko', iso: 'ko-KR', file: 'translate.ts' },
      { code: 'en', iso: 'en-US', file: 'translate.ts' },
    ],
    lazy: true,
    langDir: 'i18n',
    defaultLocale: 'ko',
    detectBrowserLanguage: {
      redirectOn: 'all',
      useCookie: true,
      onlyOnRoot: true,
      cookieKey: 'lang',
    }
  },

**Comment by rchl** [comment]
Please provide a reproduction repo (can be on codesandbox or some other online service like that).

**Comment by kim00425** [comment]
@rchl  i cant reproduction repo. 
translate.ts

export default async (context, locale) => {
  return await context.$axios.$get('translate', {params: {locale}}).then((res) => {
    const {data = {}} = res;
    return data;
  }).catch((e) => {
    return {};
  });
}

**Comment by kim00425** [comment]
@rchl we solve this
we solve this change code
   switchLanguage(language: string) {
   // this.$i18n.setLocale(language);
    window.open(this.switchLocalePath(language), '_self');
   }
