### ISSUE TITLE
start removing unwanted nullish coalescisors - ?. ?? etc.

### ISSUE THREAD

**Issue by mcdmaster** [nuxt-modules/i18n#1380]
### Version
@nuxtjs/i18n:  7.2.0
nuxt:  2.15.8
typescript - 4.5.4
-- any downgrade is not expected.

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### Reproduction Link

https://typescript.nuxtjs.org/guide/setup/

### Steps to reproduce
See: 
![スクリーンショット 2022-01-22 011331](https://user-images.githubusercontent.com/10361533/150588432-dda7e207-4f45-44fd-8533-a7c138fda4bc.png)

### What is Expected?
Grace end of build and perfect execution.

### What is actually happening?
Unsuccessful build of our core modules is a showstopper in the middle og our project schedule.

**Comment by rchl** [comment]
The version of Nuxt that you are using is configured to handle that syntax just fine.

It sounds like you have customized nuxt in a way that breaks support for that.

It's not the module's issue.

**Comment by rchl** [comment]
Also, did you see the info box within the page that you've linked?

![Screenshot_20220121-211311.jpg](https://user-images.githubusercontent.com/153197/150593949-292455e2-9db4-4546-9fa0-3904ecb555d2.jpg)

**Comment by mcdmaster** [comment]
@rchl

Please define "customization" of your own. Additionally, do explain why on the earth you think there is an engineer who may not have sufficient knowledge of specific softwaer which he/she is going to implement/deploy never read its documentation prior to be in the house.
I appreciate your feedback but, for now, it is too hard to understand for me as a non-English speaker

**Comment by rchl** [comment]
Please provide a reproduction repo. It doesn't reproduce for me with a fresh project created using `nuxt-app` preset (as described in https://nuxtjs.org/docs/get-started/installation) with typescript enabled.
