### ISSUE TITLE
No support for i18n-d tag?

### ISSUE THREAD

**Issue by hmalaud** [nuxt-modules/i18n#1383]
As per it's doc, vue i18n allows custom date formatting with the `<i18n-d>` tag (https://vue-i18n.intlify.dev/guide/essentials/datetime.html), but when trying to use it with nuxt i18n, tag is not recognized, even though the fellow custom tag `<i18n-n>` is supported. Am I missing something?

**Comment by rchl** [comment]
You are looking at v9 documentation that is for vue 3 only.

v8 (https://vue-i18n.intlify.dev/v8-docs.html) used by this module doesn't support that tag.
