### ISSUE TITLE
Vuex synchronized state is empty

### ISSUE THREAD

**Issue by louislebrault** [nuxt-modules/i18n#1386]
### Version
@nuxtjs/i18n: 7.2.0
nuxt: 2.15.8

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend
 
### Module config
```
i18n: {
    locales: [
      { code: "en", iso: "en-US", file: "en.json" },
      { code: "ru", iso: "ru-RU", file: "ru.json" },
      { code: "es", iso: "es-ES", file: "es.json" }
    ],
    langDir: "~/locales/",
    defaultLocale: "en",
    lazy: true,
    strategy: "prefix_except_default",
    detectBrowserLanguage: {
      alwaysRedirect: true,
      useCookie: true,
      cookieKey: "t_locale",
      fallbackLocale: "es"
    },
    vuex: {
      moduleName: "i18n",
      syncRouteParams: true
    }
  },
```

### Reproduction

https://codesandbox.io/s/nuxt-nuxtjs-i18n-base-template-forked-xyxeg?file=/pages/index.vue

Please check console, the store is logged from store/index.js

### What is Expected?

According to the documentation, i18n vuex module should be synchronized with $i18n state.

### What is actually happening?

There is only one field in this vuex module state, which is `routeParams`. Even the current locale is not accessible in the vuex module.
If option `syncRouteParams` is false, the vuex module state is empty.

**Comment by rchl** [comment]
It's only used for specifying dynamic route params. Previous version (6) synced more but that was removed due to not really being needed.

You have `i18n` available in most places, including store, so you could get stuff from there.

**Comment by louislebrault** [comment]
Thanks for the information.

`i18n` is only available in vuex **actions** context (this). This is pretty common to need such informations from a getter for example. Imho the documentation is misleading, and its also misleading to have a vuex config object where you can put `syncRouteParams` to false, if you do so it generate a dead vuex module.

**Comment by rchl** [comment]
We could:
 - not create the vuex module when `syncRouteParams` is false since that's the only use case currently
 - clarify documentation

But you are right that only actions have access to i18n.
I suppose the option you have right now is to manually sync the state you want to the store.
