### ISSUE TITLE
Is there any way to override or replace the default hreflang links of nuxt-i18n/SEO

### ISSUE THREAD

**Issue by duongvu-survive** [nuxt-modules/i18n#1389]
I have tried using hid to replace hreflang with no success.
I'm looking to create **LINK Href** with /blog/{slug_locale} for different languages
```
var i18nHead = this.$nuxtI18nHead({ addSeoAttributes: true });
 i18nHead.link = hiddenLink;
return {
link:[...i18nHead.link]
}
```

![image](https://user-images.githubusercontent.com/72527200/153062474-a33102ab-0a1d-4270-aa46-beaa5e102594.png)

**Comment by rchl** [comment]
`i18nHead` is a plain object that you can just iterate and modify as you please.
So, even if not super-straightforward, it's an option to just modify the items that are created.

**Comment by ElyseGiroux** [comment]
I've done this simple snippet in my app.vue to fix the trailing slash issue even with trailingSlash: false.
Just add it before useHead()

```
i18nHead.value.link.map((l) => {
  if (l.href.endsWith('/')) {
    l.href = l.href.replace(/\/$/, '');
  }
});
```
