### ISSUE TITLE
Accesing site from Google redirects to non-existing language prefix.

### ISSUE THREAD

**Issue by fcieminski** [nuxt-modules/i18n#1390]
### Version
@nuxtjs/i18n: 7.2.0
nuxt: 2.15.8

### Nuxt configuration

 - [X] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - 
### @nuxtjs/i18n configuration

```
  i18n: {
    defaultLocale: 'pl',
    strategy: 'prefix_except_default',
    locales: [
      {
        code: 'ua',
        iso: 'ua-ukr',
        name: 'український',
        file: 'ua.json'
      },
      {
        code: 'pl',
        iso: 'pl-pol',
        name: 'Polski',
        file: 'pl.json'
      }
    ],
    langDir: '@/locales',
    detectBrowserLanguage: false
  },
```
-->

### Steps to reproduce

search 'swiadomypodpis' in google, click first link

### What is Expected?

the page should be visited without any language prefixes, especially when theres no supported language for that page.

### What is actually happening?

Strange thing, It's only happening on mobile devices. When searching for my page from Google, and then going to it, users are redirected to non-existing language `/en`. So the netlify serves the generic 404 page, because we are not supporting english language for now. Firstly I thought it's something about detecting browser language, but I have disabled it without any success. I have even added the redirect inside netlify.toml

```
[[redirects]]
  from = "/en"
  to = "/"
  status = 200
```
but the link stays the same, with `/en` prefix, which breaks the page navigation.

**Comment by rchl** [comment]
The fact that the `/en` page is working in the first place seems wrong because if it's there then google will index it.

This module shouldn't be creating that route and you can verify that by looking at generated files in `dist/`.

> So the netlify serves the generic 404 page, because we are not supporting english language for now

That's not what I see. The `/en` page renders a normal index page.

I think you just need to fix it on netlify side if your generated files don't include that route.

**Comment by rchl** [comment]
BTW. 

> but the link stays the same, with `/en` prefix, which breaks the page navigation.

Check [netlify documentation ](https://docs.netlify.com/routing/redirects/redirect-options/). This is what you've asked for by setting status to 200. You want the default (301) if you want the URL to change.

**Comment by fcieminski** [comment]
> The fact that the `/en` page is working in the first place seems wrong because if it's there then google will index it.
> 
> This module shouldn't be creating that route and you can verify that by looking at generated files in `dist/`.
> 
> > So the netlify serves the generic 404 page, because we are not supporting english language for now
> 
> That's not what I see. The `/en` page renders a normal index page.
> 
> I think you just need to fix it on netlify side if your generated files don't include that route.

Exactly, there is no route `/en` in dist, and no `/en` in sitemap. It renders as a normal index page, because I have used the netlify redirect as a temporary work around, but without it it goes to 404. But still, the question is, why it even happen? Should i18n package prevent going to route which is not even existing, both in config and files, why do I have to change that in netlify? What If someone for example from Germany will visit my page and gets redirected to `/de` which also doesn't exists. I think that adding redirect file in netlify is not a good fix, because I have no idea what is the core issue here, and It may happen with other not supported languages too.

**Comment by rchl** [comment]
But why did Google index the `/en` page in the first place? It must have been a valid 200 response. And if Nuxt doesn't generate that route then it seems that you had Netlify misconfigured. It should have returned 404 for non-existing routes.

**Comment by fcieminski** [comment]
And indeed it does. I was getting 404 from netlify after visiting the page, directly from google on mobile devices, because of that `/en` prefix which somehow was indexed. Like I have said, I have added the netlify redirect in `netlify.toml` just because users couldn't visit page from google on mobile devices. I can turn it off, and you will see 404.

**Comment by rchl** [comment]
I believe you that the non-existent routes return 404 now (I can test that on random route like `/fooobar`) but since google has indexed `/en`, the only plausible explanation to me is that it was mis-configured before.

Even if the module or Nuxt would redirect to `/en` (which I don't think it does), google should still not index it if it was 404.
