### ISSUE TITLE
How to use "_.vue" with Dynamic route parameters

### ISSUE THREAD

**Issue by JeremDigi** [nuxt-modules/i18n#1400]
Hello !

Here is my structure:
```
pages
-> index.vue
-> _.vue
-> posts (folder)
---> _slug.vue
```

When I use this to translate the dynamic routes of my posts, it works : 

```js
async asyncData({ $sanity, route, error, app, store }) {
        await store.dispatch('i18n/setRouteParams', {
            en: { slug: 'my-post' },
            fr: { slug: 'mon-article' }
        })
}
```

But when I try to translate all other routes (which are not in a folder, thanks to _.vue), it doesn't work.

```js
await store.dispatch('i18n/setRouteParams', {
      en: { _: 'my-great-page' },
      fr: { _: 'ma-super-page' }
})
```

I need to use `_.vue` because some of my slugs are like this: `page-1/my-subpage-1`

It's possible?

Thank you

**Comment by rchl** [comment]
It needs to be `pathMatch`. I've added info about that to docs https://github.com/nuxt-community/i18n-module/commit/b6039d2215945319fdbd1acf8dc981cc55c3bc8d
