### ISSUE TITLE
Selectively disable redirects to prefixless for default locale routes with prefix_and_default strategy

### ISSUE THREAD

**Issue by eatyrghost** [nuxt-modules/i18n#1401]
**Problem**
We are using the `prefix_and_default` strategy with a default locale set to `en-us`.

If we visit a route with the default locale as the prefix, e.g. `/en-us/about-us`, we are redirected to the prefixless route, `/about-us`. This is acceptable for most of our pages.

In a handful of cases, we don't want to redirect - we want to specifically use the `/en-us` prefix.

**Desired Solution**
There might be two ways we could configure this.

1. A new property on the page component:

```
export default {
    disableDefaultRedirect: true
};
```

2. A configuration that accepts a boolean or an array of prefixless paths:

```
// Applies to all routes
i18n: {
    disableDefaultRedirect: true
}

// Applies to /about-us and /products only
i18n: {
    disableDefaultRedirect: [
        '/about-us',
        '/products'
    ]
}
```

**Comment by jeiksegovia** [comment]
That seems very useful

**Comment by jeiksegovia** [comment]
This feature is still relevant....

**Comment by jeiksegovia** [comment]
nice!!

**Comment by DanielHefti** [comment]
I'm looking for this feature as well!

**Comment by julioglobal100** [comment]
we need this! thanks

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
