### ISSUE TITLE
store.dispatch("i18n/setRouteParams") doesn't work when I switch language

### ISSUE THREAD

**Issue by JeremDigi** [nuxt-modules/i18n#1404]
Hello,

When I dynamically define the translation of the slugs, when I click on the language switcher, it works the first time, but not the following times.

```js
async asyncData({  route, error, app, store }) {
  const pageIdentify = app.store.state.pageIndentify;
  let pathMatchEn = pageIdentify.__i18n_ref.slug.current;
  let pathMatchFr = pageIdentify.__i18n_base.slug.current;
}

await store.dispatch("i18n/setRouteParams", {
      en: { pathMatch: pathMatchEn },
      fr: { pathMatch: pathMatchFr },
});
```

I guess it's because of asyncData() which only runs at server level.

But how to make it work when browsing? If change language, `i18n/setRouteParams` loses data

Thank you !

**Comment by rchl** [comment]
`asyncData` runs on both server and client side and so it also runs on changing routes and changing locales.

Can't help without more information/reproduction.

**Comment by JeremDigi** [comment]
Hi @rchl ,

Thanks for the quick return. I will try to be more specific.

In `store/index.js`, I have a `nuxtServerInit()` function which has the role of retrieving the basic information of the page which must be loaded (such as the available language versions).

I made this data available in VueX

```js
async nuxtServerInit({commit}, pContext) {
    const locale = pContext.i18n.locale;
    const slug = pContext.route.fullPath.substring(4);
    const type = pContext.$setTypeOfPost(pContext.route.name);

    const query = groq`{"page": 
            *[_type == '${type}' && slug.current == '${slug}' && __i18n_lang == '${locale}'][0]{
              __i18n_lang,
              __i18n_refs[]->{__i18n_lang, slug},
              __i18n_base->{slug},
              "page_template": template[0]._type,
            }
          }`;

    await pContext.$sanity.fetch(query)
        .then( (response) => {
            commit("SET_PAGE_IDENTIFY", response.page);
        } );
  },
```

With this data, I am trying to build a working Language Switcher. 

```js
<nuxt-link
      v-for="locale in availableLocales"
      :key="locale.code"
      :to="switchLocalePath(locale.code)"
      >{{ locale.name }}
</nuxt-link>
```

The rest happens in `_.vue` (for catch-all routes).
```js
async asyncData({ $sanity, route, error, app, store }) {
  const pageIdentify = app.store.state.pageIndentify;
  let pathMatchEn = "";
  let pathMatchFr = "";

  if (pageIdentify.__i18n_base) {
      pathMatchFr = pageIdentify.__i18n_base.slug.current;
    } else {
      pageIdentify.__i18n_refs.forEach((element) => {
        if (element.__i18n_lang === "en") {
          pathMatchEn = element.slug.current;
        }
      });
    }

  // For Language Switcher
    await store.dispatch("i18n/setRouteParams", {
      en: { pathMatch: pathMatchEn },
      fr: { pathMatch: pathMatchFr },
    });
}
```

When I reload the page, my language switcher works fine.

Let's imagine that `pathMatchFr` = `ma-page-fr` and `pathMatchEn` = `my-page-en`.

I click on the language switcher to switch from `pathMatchFr` to `pathMatchEn`. It works. Url is `my-page-en`.
But after clicking, when I want to switch back to French thanks to `pathMatchFr`, Url is `/fr`. But if I reload the page, it works.

Why ?

Thank you in advance !

**Comment by rchl** [comment]
`nuxtServerInit` runs only on initial server-side rendering. So it's not a good place for fetching the information that need to be specific to the current route.

You have to either fetch information about **all** pages from `nuxtServerInit` and store that (but that might be too big) or fetch that from the `asyncData` of the page itself.

**Comment by JeremDigi** [comment]
@rchl thank you for your help! 

I didn't know, I learned something today =)

I'm going to use middleware instead. Thank you !
