### ISSUE TITLE
Nuxt Bridge app.baseURL doesn't work with i18n module

### ISSUE THREAD

**Issue by thomas4Bitcraft** [nuxt-modules/i18n#1406]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `latest`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

_nuxt.config.js_

```
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
router: {
    base: '/d/'
  },
})
```

### Describe the bug

The base path in nuxt bridge seems to be broken. If I set it to the above `/d/` every preload link in the frontend is set to `/d/d/` and all files are also reachable only with this path.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/44415527/154579681-2e30740b-87a7-405e-b731-728ffe2eb3b9.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/44415527/154579710-74c27e43-2912-4e9f-b00d-0bb74a2b1c08.png">

It seems the only url which is not affected by this is the one to the header js file in production
<img width="426" alt="image" src="https://user-images.githubusercontent.com/44415527/154580901-74b4a660-e48c-4ca2-b2e2-710658e1d6b5.png">

What makes the thing worse - because the file lies under `/d/d/` and the whole site is broken

### Related Issue
[nuxt/bridge#16](nuxt/bridge#16)

**Comment by danielroe** [comment]
With Bridge & Nuxt 3, we have a different way of configuring a _dynamic_ base path:

```diff
  import { defineNuxtConfig } from '@nuxt/bridge'
  
  export default defineNuxtConfig({
-   router: {
-     base: '/d/'
-   },
+   app: {
+     baseURL: '/d/'
+   },
  })
```

This fixes the duplicated links in header but it doesn't seem to work with this module. Likely a change is needed to ensure that we pull not from router base but from the runtimeConfig, if it is set. (This should also be present on recent Nuxt 2 builds, even without Bridge).

**Comment by rchl** [comment]
There is the https://i18n.nuxtjs.org/options-reference#baseurl option that should be used to make meta URLs fully-qualified and the base path should be included in here also.

Otherwise this module fully relies on the resolved values from Vue-Router and doesn't explicitly use `router.base` or `app.baseURL` anywhere.

Though I must say that VueRouter provides paths that both include and don't include the base path but module typically uses ones that don't include the base path as `nuxt-link` expects those.

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
