### ISSUE TITLE
Cannot use @nuxtjs/i18n with nuxt-vite

### ISSUE THREAD

**Issue by ryochike** [nuxt-modules/i18n#1408]
### Version
@nuxtjs/i18n: 7.2.0
nuxt-vite: 0.3.5
nuxt: 2.15.8
Brave browser: Version: 1.36.109 Chromium: 99.0.4844.51

### Reproduction
nuxt.config.js

```
...

  buildModules: [
    '@nuxt/typescript-build',
    '@nuxtjs/vuetify',
    '@nuxt/postcss8',
    'nuxt-vite',
  ],

modules: [
    'nuxtjs/axios',
    'nuxtjs/i18n',
],

// https://i18n.nuxtjs.org/basic-usage
i18n: {
    locales: ['en', 'fr', 'es'],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          welcome: 'Welcome',
        },
        fr: {
          welcome: 'Bienvenue',
        },
        es: {
          welcome: 'Bienvenido',
        },
      },
    },
  },
...

```

### Describe the bug
When I try to use @nuxtjs/i18n in an environment using nuxt-vite, the load bar keeps spinning in 'npm run dev'.

Commenting out nuxt-vite from buildModules works fine.

Is there any way to implement i18n in a vite environment?

**Comment by rchl** [comment]
Work on Nuxt 3/Bridge compatible version is ongoing (https://github.com/nuxt-community/i18n-module/discussions/1287) and since Nuxt 3 uses Vite by default, it will of course work there.

I don't expect this to work with the v7 of this module.
