### ISSUE TITLE
Aliased "ufo" is not transpiled

### ISSUE THREAD

**Issue by rchl** [nuxt-modules/i18n#1413]
The client-side bundle includes a copy of `ufo` that is not transpiled (contains spread operator). I've tried to add our aliased `~i18n-ufo` import to `transpile` list but babel never picks it up so it doesn't get transpiled.

### Version
@nuxtjs/i18n: 7.2.0
nuxt: 2.15.8

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

**Comment by rchl** [comment]
Nuxt issue: https://github.com/nuxt/nuxt.js/issues/10339

**Comment by dargmuesli** [comment]
The Nuxt issue has been resolved, maybe this issue can be closed as well?
