### ISSUE TITLE
[next] ERROR `Cannot find module 'vue-i18n-routing/dist/vue-i18n-routing.es.js'`

### ISSUE THREAD

**Issue by jojomatik** [nuxt-modules/i18n#1416]
Hi there thanks for the great project, I've been trying to get this module (`@nuxtjs/i18n-edge`) working with my [nuxt-3-base](https://github.com/jojomatik/nuxt-3-base) template. I've created a PR https://github.com/jojomatik/nuxt-3-base/pull/20 that switches from `@intlify/nuxt3` to `@nuxtjs/i18n-edge`.

Unfortunately it is not possible to build the project after this change: https://github.com/jojomatik/nuxt-3-base/runs/5680435694?check_suite_focus=true

It throws an error: 
```
Error:  Cannot find module 'vue-i18n-routing/dist/vue-i18n-routing.es.js'
Require stack:
- /home/runner/work/nuxt-3-base/nuxt-3-base/index.js
  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:[10](https://github.com/jojomatik/nuxt-3-base/runs/5680435694?check_suite_focus=true#step:7:10)8:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:192796)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:220:29)
  at setup (node_modules/@nuxtjs/i18n/dist/module.mjs:274:46)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:500:5)
  at async installModule (node_modules/nuxt3/node_modules/@nuxt/kit/dist/index.mjs:380:3)
  at async initNuxt (node_modules/nuxt3/dist/chunks/index.mjs:[11](https://github.com/jojomatik/nuxt-3-base/runs/5680435694?check_suite_focus=true#step:7:11)16:7)
  at async loadNuxt (node_modules/nuxt3/dist/chunks/index.mjs:1[13](https://github.com/jojomatik/nuxt-3-base/runs/5680435694?check_suite_focus=true#step:7:13)6:5)
Error: Process completed with exit code 1.
```

I suppose it has something todo with the fact that `vue-i18n-routing` is placed in `node_modules/@nuxtjs/i18n/node_modules/vue-i18n-routing` instead of `node_modules/vue-i18n-routing`. Is this my fault or does this have to be fixed in this repository? Have I misconfigured the plugin? This is the change: https://github.com/jojomatik/nuxt-3-base/pull/20/commits/4b67d2637752e0706170194d6c63a2d6c9f438c9

I've also tried to recreate my `package-lock.json` with no effect.

Is there a template project which I could have a look at?

**Additional info:**
I tried installing `vue-i18n-routing` manually with `npm install vue-i18n-routing@edge`, but this leads to the following error as it somehow depends on vue 2:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@1.0.0-beta.6
npm ERR! Found: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@"^2.6.14 || ^3.2.0" from vue-i18n-routing@0.0.0-ab35914
npm ERR!   node_modules/vue-i18n-routing
npm ERR!     vue-i18n-routing@"0.0.0-ab35914" from the root project
npm ERR!   peer vue@">= 2.5 < 3" from @vue/composition-api@1.4.9
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from vue-i18n-routing@0.0.0-ab35914
npm ERR!     node_modules/vue-i18n-routing
npm ERR!       vue-i18n-routing@"0.0.0-ab35914" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.0.0" from vue-i18n@9.2.0-beta.33
npm ERR! node_modules/vue-i18n
npm ERR!   peer vue-i18n@"^8.26.1 || ^9.2.0-beta.30" from vue-i18n-routing@0.0.0-ab35914
npm ERR!   node_modules/vue-i18n-routing
npm ERR!     vue-i18n-routing@"0.0.0-ab35914" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by urbgimtam** [comment]
Haven't tried it yet, but I've found https://github.com/intlify/nuxt3 which is from the same author, and from the readme looks like it could work.

**Comment by brolnickij** [comment]
@urbgimtam https://github.com/intlify/nuxt3/issues/44#issuecomment-1061605139

**Comment by rchl** [comment]
1. I think you'll have more luck with using `yarn` instead of `npm`. It still looks like a bug in the module but if you want to try things out, you could try `yarn`.
2. You will still have issues because you haven't defined `locales` option which is mandatory. And it needs to be in object form that also specifies file name. See https://i18n.nuxtjs.org/options-reference#locales

@kazupon I suppose there are two or more bugs here.
For 1, the module should resolve paths to dependencies at module run time (or maybe it's a Nuxt 3 bug).
For 2, if `locales` is required then the module should warn/error with clear message if not provided.

**Comment by jojomatik** [comment]
> 2. You will still have issues because you haven't defined `locales` option which is mandatory. And it needs to be in object form that also specifies file name. See https://i18n.nuxtjs.org/options-reference#locales

Is this strictly necessary? I use vue 2 (without nuxt though) with vue-i18n in another project and the locales are automatically loaded from the language-files, is this not the case for this project?

**Comment by jojomatik** [comment]
I've tried my previous steps again with the new version of nuxt and this project: Same results 😞 I hoped that https://github.com/nuxt-community/i18n-module/commit/6b683556c46c43d22d8a96eeda7d65728d5a5277 would have an effect on this.

> 1. I think you'll have more luck with using `yarn` instead of `npm`. It still looks like a bug in the module but if you want to try things out, you could try `yarn`.

**I've tried two other things:**
1. Installing `vue-i18n-routing` manually with the force parameter `npm install vue-i18n-routing@edge --force`, which installs the package (ignoring the peer dependencies)
2. Installing everything with yarn.

Both lead me to the same result (another error):
```
 ERROR  Cannot read properties of undefined (reading 'replace')                                                                                                                                                                                                                                               21:02:06

  at Object.serialize (/path/jojomatik/nuxt-3-base/node_modules/@nuxtjs/i18n/node_modules/@nuxt/kit/dist/index.mjs:439:58)
  at /path/jojomatik/nuxt-3-base/node_modules/@nuxtjs/i18n/dist/module.mjs:206:103
  at Array.map (<anonymous>)
  at /path/jojomatik/nuxt-3-base/node_modules/@nuxtjs/i18n/dist/module.mjs:206:75
  at Array.map (<anonymous>)
  at generateLoaderOptions (/path/jojomatik/nuxt-3-base/node_modules/@nuxtjs/i18n/dist/module.mjs:189:46)
  at Object.getContents (/path/jojomatik/nuxt-3-base/node_modules/@nuxtjs/i18n/dist/module.mjs:295:16)
  at compileTemplate (/path/jojomatik/nuxt-3-base/node_modules/@nuxt/kit/dist/index.mjs:512:21)
  at /path/jojomatik/nuxt-3-base/node_modules/nuxt3/dist/chunks/index.mjs:1372:28
  at Array.map (<anonymous>)
```

To me this error is even more cryptic, any ideas?

I also tried adding the locales parameter as such:
```
modules: [
    [
      "@nuxtjs/i18n",
      {
        locales: ["en","de"],
        langDir: "locales", // set the `locales` directory at source directory of your Nuxt application
        vueI18n: {
          locale: process.env.VUE_APP_I18N_LOCALE || "en",
          fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || "en",
        },
      },
    ],
  ],
```
But it didn't help with that specific problem.

**Comment by rchl** [comment]
The new error you are getting is what I was referring to before.

As I said, when using lazy loading, the `locales` object must be an array of objects. Check https://i18n.nuxtjs.org/lazy-load-translations/

**Comment by jojomatik** [comment]
> The new error you are getting is what I was referring to before.
> 
> As I said, when using lazy loading, the `locales` object must be an array of objects. Check https://i18n.nuxtjs.org/lazy-load-translations/

Oh I'm sorry, I overlooked the second part of that point. It does seem to work with that, although I'll have to continue testing tomorrow. 

So there is no way to automatically load all translations from the directory defined in `langDir`?

**Comment by rchl** [comment]
No, there never was a way to do that in this module.

**Comment by jojomatik** [comment]
Ok, thanks. I've added a workaround to implement this for my project as such:

```ts
import fs from "fs";
const locales = fs.readdirSync("locales").map((file) => {
  return { code: file.replace(".json", ""), file: file };
});
```

```ts
    [
      "@nuxtjs/i18n",
      {
        locales: locales,
        defaultLocale: "en",
        langDir: "locales", // set the `locales` directory at source directory of your Nuxt application
        vueI18n: {
          locale: process.env.VUE_APP_I18N_LOCALE || "en",
          fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || "en",
        },
      },
    ],
```
This should do for now.

**Comment by jojomatik** [comment]
I've just switched to this module in https://github.com/jojomatik/nuxt-3-base/pull/20 after I migrated to `yarn`. Anyone else can try to follow these changes (https://github.com/jojomatik/nuxt-3-base/commit/6dbc8167dd4b4e1110eb2a74c289f7b0ea98a2d0).

**Comment by kazupon** [comment]
@nuxtjs/i18n has been already v8 beta
if you would have still issue, please open the new issue.
thanks!
