### ISSUE TITLE
How to specify Locale-specific page

### ISSUE THREAD

**Issue by TobiTenno** [nuxt-modules/i18n#1439]
I'm attempting to create a structure like...
```
pages/
├── _nested/
├──── _route/
├────── index.vue
├────── index_fr.vue
```

but can't figure out how to configure it to work like that.
The use-case is that the page is a large guide, and adding each paragraph/section of text to the messages object would get tedious and make debugging/updating much harder.

To be specific, I want 'index_fr.vue' to load when 'fr' is the specified locale, and otherwise fall back to 'index.vue'.

**Comment by rchl** [comment]
Maybe extract the locale-specific text into locale-specific components and show the respective ones based on `$i18n.locale`.

But essentially what you are trying to do is bypass this module entirely so that makes it into a matter that is not really related to this module anymore.
