### ISSUE TITLE
SCRIPT1053: Const in ie11

### ISSUE THREAD

**Issue by khackskjs** [nuxt-modules/i18n#1443]
### Version
@nuxtjs/i18n: 7.2.2, I think all 7.x and 6.latest
nuxt: 2.15.8

### Nuxt configuration

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)

### @nuxtjs/i18n configuration
```
build: {
  transpile: ['@nuxtjs/i18n'],
  babel: {
    presets: [
      ['@nuxt/babel-preset-app',
        {
          targets: { client: { browsers: ['last 2versions'], ie: 11 } }
        }
      ]
    ]
  }
}
```

### What is Expected?
generated page is working in IE11
(nuxt-i18n@6.23 I tested that fixed for IE11, it's working fine)

### What is actually happening?
I think unsupported syntax in IE11 causes this issue that is in i18n dependency module, ufo.

![image](https://user-images.githubusercontent.com/11523968/169085193-a904c853-460d-45aa-a7d0-ce23aa04f38d.png)

**Comment by rchl** [comment]
See https://github.com/unjs/ufo/issues/50 and https://github.com/nuxt/nuxt.js/issues/10339

**Comment by khackskjs** [comment]
I got it. when do you expect that PR is merged?

**Comment by bump44** [comment]
temporarily solve it
```
  build: {
    // transpile: ["@nuxtjs/i18n"],
    extend(config, ctx) {
      config.resolve.extensions.push(".сjs");
      const orig = config.module.rules[2].exclude;
      config.module.rules[2].test = /\.(m|c)?jsx?$/i;
      config.module.rules[2].exclude = function (file) {
        var res = orig(file);
        if (res) return !/ufo/.test(file);
        return res;
      };
    },
  },
```

**Comment by khackskjs** [comment]
@bump44 Thank you for you to save me. It works well.
