### ISSUE TITLE
Wrong order of unknown dynamic routes in .nuxt/router.js

### ISSUE THREAD

**Issue by memic84** [nuxt-modules/i18n#1446]
### Version
@nuxtjs/i18n: 7.2.2
nuxt: 2.15.8

### Nuxt configuration
 - [x] Applies to a site deployed to a server with a Node backend
 
I have upgraded from nuxt-i18n version 6 to version 7, and followed the migration guide. I also went through alle issues which seemed related to this one, but haven't found a working solution or workaround at this moment.

**I did some debugging and found out that the generated router.js, contains an incorrect order of pages (ex. catch-all, _.vue is always loaded before all the other pages from the dir /pages). In our current production running site with nuxt-i18n on version 6, this order is correct.**

I have tried the **sortRoutes** from nuxt utils, as described in the docs for extendedRoutes, without success.

When i manually change the order inside the .nuxt/router.js, than it works.

**Am i doing something wrong in my configuration? Is there a workaround for this?**

**Or could somebody point me in the right direction if this is a nuxt-i18n bug, i would be happy to contribute.**

### @nuxtjs/i18n configuration
```js
  // i18n options
  i18n: {
    encodePaths: false,
    parsePages: false,
    vueI18n: {
      fallbackLocale: 'en-eu',
    },
    defaultLocale: 'en-eu',
    strategy: 'prefix',
    pages: (function () {
      return Routes.Routes;
    })(),
    lazy: true,
    locales,
    langDir: 'locales/',
    vueI18nLoader: true,
    vuex: {
      // Module namespace
      moduleName: 'i18n',

      // Mutation to commit to set route parameters translations
      syncRouteParams: true,
    },
  },

  router: {
    extendRoutes(routes, resolve) {
      routes.push({
        name: 'catchall',
        path: '*',
        component: resolve(__dirname, 'pages/_.vue'),
      });
      routes.push({
        name: 'cookie',
        path: '*',
        component: resolve(__dirname, 'pages/_.vue'),
      });
      routes.push({
        name: 'index',
        path: '/',
        component: resolve(__dirname, 'pages/_.vue'),
      });
    },
    // prettier-ignore
    parseQuery: (query) => {
      // needed because imports are not included in nuxt router
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      return require('qs').parse(query);
    },
    // prettier-ignore
    stringifyQuery: (query) => {
      // needed because imports are not included in nuxt router
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const result = require('qs').stringify(query);

      return result ? '?' + result : '';
    },
  }
```

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-yrunt8?file=routes%2FRoutes.js,nuxt.config.js

### Steps to reproduce
1. Click the login button
2. Nuxt-link should send you to the login page, and not _.vue (catch-all)

### What is Expected?
I expect the filesystem pages which are defines in nuxt config pages (/routes/Routes.js) to load before the catch-all route.

**Comment by rchl** [comment]
Try using `/*` path instead of `*`.
This might be a solution for you but in any case the issue seems in the `sortRoutes` from nuxt utils.

**Comment by memic84** [comment]
Yes, the solution seems to work so far. Thank you!
