### ISSUE TITLE
[next]  i18n folder not generated

### ISSUE THREAD

**Issue by NidMo** [nuxt-modules/i18n#1450]
### Environment
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.0.0`
- Builder:          `vite`
- User Config:      `vite`, `publicRuntimeConfig`, `plugins`, `meta`, `build`, `buildModules`, `pageTransition`, `vueuse`, `strapi`, `i18n`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.4.2`, `@nuxtjs/tailwindcss@5.1.2`, `@pinia/nuxt@0.1.9`, `@nuxtjs/strapi@1.3.1`, `@nuxtjs/i18n@8.0.0-alpha.0-27551479.0f88897`
------------------------------

### Reproduction
1.   npm run dev

### Describe the  bug

![image](https://user-images.githubusercontent.com/24955673/171119821-196be8cb-9088-4dac-a356-defeb95b891e.png)

I found  .nuxt/tsconfig.json  is like this，but .nuxt/i18n folder not generated.Does this meet expectations？

This causes me to use i18n composables and throw an error that the module cannot be found
![image](https://user-images.githubusercontent.com/24955673/171120785-ee534c7d-ad94-4b8a-8e86-00f7383e443a.png)

**Comment by NidMo** [comment]
Or the generated path is incorrect？

**Comment by kazupon** [comment]
I think that compsable functions is auto imported in v8 beta
if you would have still issue, please open the new issue.

thanks!
