### ISSUE TITLE
switchLocalePath() using differentDomains does not include router.base into its path

### ISSUE THREAD

**Issue by hubret** [nuxt-modules/i18n#1453]
### Version
@nuxtjs/i18n: 7.2.0
nuxt: 2.15.8

### Nuxt configuration

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
  i18n: {
    locales: [
      { name: 'English', code: 'en', iso: 'en-CA', domain: 'hubretenglish.ca' },
      { name: 'Français', code: 'fr', iso: 'fr-CA', domain: 'hubretfrench.ca' }
    ],
    differentDomains: (process.env.NODE_ENV === 'production'),
    defaultLocale: 'en',
    strategy: 'prefix_except_default',
    vueI18nLoader: true
  },
  router: {
    base: '/conference/'
  }
```

### Reproduction Link

https://codesandbox.io/s/nuxt-nuxtjs-i18n-base-template-forked-eg6hl7?file=/nuxt.config.js

The button going to `hubretfrench.com` should go to `hubretfrench.com/conference`

### Steps to reproduce

Use the configuration above. 

### What is Expected?

The language toggle button (which in this case is now an `a` tag, since we are using differentDomains) should go to the page the user is on in the corresponding locale (the lang toggle at https://hubretenglish.ca/conference should link to https://hubretfrench.ca/conference)

### What is actually happening?

The lang toggle at https://hubretenglish.ca/conference is linking to https://hubretfrench.ca

This might be happening on `differentDomains : false` as well, but I haven't checked thoroughly.

For now, the workaround is to write a funny .replace() on the switchLocalePath() to insert the base between the domain name and the current route.

Not sure if this behaviour is actually intentional, since there isn't a way to translate `router.base` (that I know of).

**Comment by rchl** [comment]
Are you sure that `differentDomains` option is set to `true` during `nuxt generate`?

BTW. If you want more help, I'd need a project that I can just clone and run. I can configure fake domains locally using hosts file so that's not a problem but I won't have time to recreate the whole project.

**Comment by hubret** [comment]
the project is not being deployed with `nuxt generate`. I am certain that the option is being set since my example is running on a production site, with both domains (i.e. differentDomains is working).

I have a suspicion that this is also happening just with `router.base` set and i18n **without** `differentDomains`.

I'll try to get a reproduction for that

**Comment by hubret** [comment]
not an issue without `differentDomains`. Updated with a sandbox link https://codesandbox.io/s/nuxt-nuxtjs-i18n-base-template-forked-eg6hl7?file=/nuxt.config.js

Also going to add that maybe this was an intentional decision, since there isn't a way to translate `router.base` (that I know of), but somehow `router.base` will appear regardless of translation on `differentDomains: false`

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (hotfixes only), if this still applies to v8 and later please open a new issue!
