### ISSUE TITLE
[next] `js`-Files do not get imported

### ISSUE THREAD

**Issue by timgoeller** [nuxt-modules/i18n#1462]
### Version
@nuxtjs/i18n: `8.0.0-alpha.0-27596800.2df94e2`
nuxt: `3.0.0-rc.4`

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### Steps to reproduce
Create a `js` file for a language, eg. `en.js` that returns the messages.

### What is actually happening?
It seems like these files are mostly ignored right now, because the `resolveLocales` method in the utils only resolves `json,json5,yaml,yml`. It does work when I just add `js` there. Is there some more implementation work needed, or would that solve the issue? Or am I missing some configuration on my part?

**Comment by renardsas** [comment]
@timgoeller , js file is not available yet.
See this file : 
https://github.com/nuxt-community/i18n-module/blob/next/TODO.md
![Screenshot 2022-07-09 at 10-55-45 nuxt-community_i18n-module at next](https://user-images.githubusercontent.com/7579904/178099099-f035bac3-c2be-4a59-b127-534b854958c1.png)

See : https://github.com/nuxt-community/i18n-module/issues/1448

**Comment by huang-julien** [comment]
i see the lazy-load checkbox being checked, is it still planned to add the JS file support with async functions ?
