### ISSUE TITLE
Strategy prefix creates routes with and witouth prefix

### ISSUE THREAD

**Issue by arsapoz** [nuxt-modules/i18n#1465]
Hello, 
When I use the strategy 'prefix' and I want to build my website it creates routes with prefixes (de, en) and without which shouldn't be the case because that is bad for SEO. can you please help me with it?

this is my config:
i18n: {
    strategy: 'prefix',
    defaultLocale: 'de',
    seo: true,
    vueI18nLoader: true,
    vueI18n: {
      fallbackLocale: 'de'
    },
    locales: [
      {
        code: 'en',
        name: 'English',
        iso: 'en-US'
      },
      {
        code: 'de',
        name: 'Deutsch',
        iso: 'de'
      }
    ],
    pages: {
      contact: {
        de: '/kontakt',
        en: '/contact'
      },
      agb: {
        de: '/agb',
        en: '/terms'
      },
      // checkout: {
      //   de: '/agb',
      //   en: '/terms'
      // },
      // checkout: {
      //   de: '/kasse',
      //   en: '/cart'
      // },
      dsgvo: {
        de: '/dsgvo',
        en: '/gdpr'
      },
      faq: {
        de: '/faq',
        en: '/faq'
      },
      impressum: {
        de: '/impressum',
        en: '/imprint'
      },
      withdrawal: {
        de: '/wiederrufsbelehrung',
        en: '/widtdrawal'
      }
    }
  },
  
<img width="347" alt="image" src="https://user-images.githubusercontent.com/21250584/177318751-20963f5d-d197-4cf2-b889-b0749cde7b8e.png">

**Comment by rchl** [comment]
Duplicate of #1288.
