### ISSUE TITLE
Generation routes is looping when use @nuxtjs/i18n locales

### ISSUE THREAD

**Issue by golbergtx** [nuxt-modules/i18n#1466]
Hi everyone, i have a problem.

### Version
@nuxtjs/i18n: 7.2.2
nuxt: 2.15.8

### Nuxt configuration

```
generate: {
    routes: ['/', '/products'],
},
i18n: {
    locales: [
      { code: 'en' },
      { code: 'fr' },
      { code: 'es' }
    ],
    defaultLocale: 'en',
    strategy: 'prefix_except_default',
},
modules: [
    '@nuxtjs/i18n',
],
```

### GIT reproduction link with project
https://github.com/golbergtx/nuxt-i18n-app/tree/master

### Steps to reproduce
1) Create nuxt project;
2) Add @nuxtjs/i18n to project;
3) Setup nuxt config;
4) Add "_.vue" file to pages folder  for dynamically match nested paths (https://nuxtjs.org/docs/features/file-system-routing#unknown-dynamic-nested-routes);

5) Add Lang Switcher to component by example https://i18n.nuxtjs.org/lang-switcher

So, the main parts of the code are: 

- **.vue** - https://github.com/golbergtx/nuxt-i18n-app/blob/master/pages/_.vue#L1-L28
- **nuxt.config.js** - https://github.com/golbergtx/nuxt-i18n-app/blob/master/nuxt.config.js#L5-L16
- **LanguageSwitcher.vue** -https://github.com/golbergtx/nuxt-i18n-app/blob/master/components/LanguageSwitcher.vue#L1-L28

6) Run nuxt generate;

### What is Expected?

Generated next routers:

```
Generated route "/" 
Generated route "/products" 
Generated route "/fr" 
Generated route "/fr/products" 
Generated route "/es" 
Generated route "/es/products" 
```

### What is actually happening?

Generation routes is looping.
Consloe logs:

```
Generated route "/"                                                                                                                                                                                                  
Generated route "/products"
Generated route "/fr"                                                                                                                                                                                                   Generated route "/es"
Generated route "/fr/products"
Generated route "/es/products" 
Generated route "/fr/fr"
Generated route "/es/fr"
Generated route "/es/fr/products" 
Generated route "/fr/fr/products"
Generated route "/fr/es/products"     
```

**Comment by rchl** [comment]
This looks like a Nuxt bug to me.

Here is repro without using this module: https://github.com/rchl/nuxt-generate-issue

running `npm run generate` generates two routes:
 - `/`
 - `/es`

The expected routes are
 - `/`
 - `/es/`

The `/es/` route is what the link points to but Nuxt does some normalizing and removes trailing slash which ends up rendering different route than expected.

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (hotfixes only), if this still applies to v8 and later please open a new issue!
