### ISSUE TITLE
Translate a key in a different language than the global locale

### ISSUE THREAD

**Issue by learntheropes** [nuxt-modules/i18n#1467]
### Version
@nuxtjs/i18n: 7.2.2
nuxt: 2.15.8

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [X] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [X] Applies to a site deployed to a server with a Node backend

### Reproduction Link
[codesandbox](https://codesandbox.io/s/other-than-global-dnuq1m)

### Steps to reproduce
Try to return a key in a different language than the global locale in lazy mode.
Like: `{{ $t("hi", "es") }}`

### What is Expected?
the string in the provided locale should be returned

### What is actually happening?
the key is returned

There is a closed issue [here](https://github.com/kazupon/vue-i18n/issues/491) where it seams that the issue is not related to kazupon/vue-i18n

**Comment by rchl** [comment]
Duplicate of #740.

**Comment by learntheropes** [comment]
Oh. I didn't notice that. Thanks.
