### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS error in specific i18n condition

### ISSUE THREAD

**Issue by balfouri1210** [nuxt-modules/i18n#1469]
if there is encoded ampersand (%26) in the url as a params,

i can't refresh the page bcoz of the **ERR_TOO_MANY_REDIRECTS** error.

test url : `localhost:3000/apple-%26/12`

my strategy is '**prefix_and_default**' and

there is no problem if i change strategy to '**prefix_except_default**'

there is no problem if i add not default locale like this `localhost:3000/ko/apple-%26/12`

```
i18n: {
    locales: ['en', 'ko'],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          welcome: 'Welcome'
        },
        ko: {
          welcome: '환영합니다'
        }
      }
    },
    strategy: 'prefix_and_default'
  },
```

i tested based on nuxt boilerplate so only nuxt 2.15 and nuxt-i18n 7.2 are installed 

how can i handle this issue?

**Comment by rchl** [comment]
Can you provide a project (codesandbox?) that reproduces?

**Comment by balfouri1210** [comment]
here is the repo https://github.com/balfouri1210/nuxt-i18n-test

**Comment by rchl** [comment]
Should be fixed in https://github.com/nuxt-community/i18n-module/releases/tag/v7.2.3

Actually new version of `ufo` is what caused the issue in the first place.

**Comment by balfouri1210** [comment]
i just checked new version. thanks for fast fixing 👍
