### ISSUE TITLE
this.$nuxtI18nHead is not a function on a new nuxt v2.15.8 project

### ISSUE THREAD

**Issue by wlarch** [nuxt-modules/i18n#1470]
### Versions
@nuxtjs/i18n: v7.2.2
nuxt: v2.15.8
node: v16.16.0
npm: v8.11.0

### Nuxt configuration
```js
{
  ssr: false,
  target: 'static',
  head() {
    return this.$nuxtI18nHead({ addSeoAttributes: true })
  }
}
```

### @nuxtjs/i18n configuration
```js
i18n: {
    baseUrl: 'http://localhost:3000',
    locales: [
      {
        code: 'en',
        iso: 'en-US',
      },
      {
        code: 'es',
        iso: 'es-ES',
      },
      {
        code: 'fr',
        iso: 'fr-FR',
      },
    ],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          welcome: 'Welcome',
        },
        fr: {
          welcome: 'Bienvenue',
        },
        es: {
          welcome: 'Bienvenido',
        },
      },
    },
  },
```

### Steps to reproduce

1. `yarn create nuxt-app test-i18n`
2. `yarn add @nuxtjs/i18n`
3. Configure nuxt.config.js as mentioned above.
4. `yarn run dev`

### What is Expected?

As detailed in the documentation, we should expect the `$nuxtI18nHead` function to be available in the head() function of nuxt.config.js.

### What is actually happening?

On page load, I get a `Type Error : this.$nuxtI18nHead is not a function`.

**Comment by wlarch** [comment]
It seems I was able to fix part of the issue when adding a verification prior to using `$nuxtI18nHead` function in the `nuxt.config.js` file : 

```js
{
    head() {
        const i18nHead = this.$nuxtI18nHead
            ? this.$nuxtI18nHead({ addSeoAttributes: true })
            : { htmlAttrs: [], meta: [], link: [] }

        return i18nHead
}
```

My custom translations seem to load only when generating the static site.

**Comment by rchl** [comment]
Isn't that the issue that the orange info box talks about in https://i18n.nuxtjs.org/seo/ ?

**Comment by wlarch** [comment]
Thanks for the feedback. I thought it was not the case at first, as  was not generating the site statically yet (yarn run dev), but it seems the case! I was able to search through Github code repository for `nuxt.config.js` files using the same `$nuxtI18nHead` variable and found out null-checking `this.$nuxtI18nHead` before calling it would be the solution here.

**Comment by GabrielVeres95** [comment]
Can you please explain how you managed to null check? Thank you @wlarch
