### ISSUE TITLE
Can I use $t function in .js file

### ISSUE THREAD

**Issue by 449770779** [nuxt-modules/i18n#1476]
I want to use $t in .js file,like this.But I tried many ways without success。

`function getHello () {
  return $t('hello')
}
`

**Comment by rchl** [comment]
No, not like that. You'd need to pass it to that function from the Vue component.

Something like:

```js
function getHello($t) { return $t('hello') }
```

```vue
<script>
// ...
getHello(this.$i18n.t.bind(this.$i18n));
</script>
```

**Comment by 449770779** [comment]
> 

Can I set this function object in .js file like this?If I can do it,When will I do it？nuxtServerInit or other times？
(I just want to have a global object pointing to $t)
> ```js
>//myUtil.js
>let i18nT = null
>export function setI18n (i18n) {
>  i18nT = i18n
>}
>export function $t() {
> return i18nT ('hello')
>}
>```



> 不，不是那样的。您需要将其从 Vue 组件交给该函数。
> 
> 就像是：
> 
> ```js
> function getHello($t) { return $t('hello') }
> ```
> 
> ```
> <script>
> // ...
> getHello(this.$i18n.t.bind(this.$i18n));
> </script>
> ```

**Comment by rchl** [comment]
It's not something I would recommend but if you must, you can create a Nuxt plugin and set a global from there.

But i18n is not a global itself, it's created per request so storing its method in a global is potentially gonna cause issues like state sharing or other problems. Highly not recommended.
