### ISSUE TITLE
[Next] Cannot build Nuxt when translation message contains "@"

### ISSUE THREAD

**Issue by darthf1** [nuxt-modules/i18n#1481]
### Version
@nuxtjs/i18n: 8.0.0-alpha.0-27654621.987d743
nuxt: 3.0.0-rc.6

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [X] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
`package.json`
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxtjs/i18n-edge": "8.0.0-alpha.0-27654621.987d743",
    "nuxt": "3.0.0-rc.6",
    "vue": "3.2.37"
  }
}
```

`nuxt.config.ts`
```ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    modules: ['@nuxtjs/i18n-edge'],

    i18n: {
        defaultLocale: 'nl',
        locales: [
            { code: 'nl', name: 'Nederlands', file: 'nl.json' },
        ],
        langDir: 'translations/',
    },
})
```
`translations/nl.json`
```json
{
  "components.identity.login_card.lbl_email_placeholder": "name@example.com",
}
```

### Steps to reproduce
- Init new nuxt 3 project (`pnpm dlx nuxi init nuxt-app`)
- Replace `package.json` file contents with above
- Replace `nuxt.config.ts` file contents with above
- Add `translations/nl.json` file contents with above
- Run `pnpm i --shamefully-hoist`
- Run `pnpm build`

### What is Expected?
Build to be OK

### What is actually happening?
```
 ERROR  [unplugin-vue-i18n] Cannot read properties of undefined (reading 'message')                                                                                                                                   20:54:52
file: /home/xxx/www/xxx/translations/nl.json


 ERROR  Cannot read properties of undefined (reading 'message')                                                                                                                                                       20:54:52

  at Object.newOptions.onError (node_modules/.pnpm/@intlify+bundle-utils@3.1.0_vue-i18n@9.2.0-beta.40/node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
  at Object.newOptions.onError (node_modules/.pnpm/@intlify+bundle-utils@3.1.0_vue-i18n@9.2.0-beta.40/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
  at newOptions.onError (node_modules/.pnpm/@intlify+bundle-utils@3.1.0_vue-i18n@9.2.0-beta.40/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
  at emitError (node_modules/.pnpm/@intlify+message-compiler@9.2.0/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:196:13)
  at readTokenInLinked (node_modules/.pnpm/@intlify+message-compiler@9.2.0/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:764:21)
  at readToken (node_modules/.pnpm/@intlify+message-compiler@9.2.0/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:778:20)
  at Object.nextToken (node_modules/.pnpm/@intlify+message-compiler@9.2.0/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:822:16)
  at parseLinked (node_modules/.pnpm/@intlify+message-compiler@9.2.0/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:957:31)
  at parseMessage (node_modules/.pnpm/@intlify+message-compiler@9.2.0/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1056:36)
  at parseResource (node_modules/.pnpm/@intlify+message-compiler@9.2.0/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1095:25)
```

When the `@` is removed from the translation, build is OK.

**Comment by timgoeller** [comment]
A temporary fix for me was to write it as `name{'@'}example.com`

**Comment by kazupon** [comment]
As he mentions, `@` is a [special character](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters) in `@nuxtjs/i18n` v8 (vue-i18n v9) and later.
You need to use [literal interpolation](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation)

Thanks!

**Comment by rchl** [comment]
@kazupon I wonder how should people who use services like Lokalise to export their translations deal with this issue? Is it necessary to post-process the translation files after exporting from a service like that? I suppose this is vue-i18n-specific logic that would not be automatically handled by those services.

**Comment by kazupon** [comment]
@rchl 
Well, I think it would be better to provide a tool to convert vue-i18n v8 based resources to v9 based in the vue-i18n or intlify project.
If you are already using a localization service, it may happen that the translated resources do not work with the vue-i18n v9 base.

we already have [Intlify CLI](https://github.com/intlify/cli), it would be good to add `intlify transform` to it and have a tool to transform the resource.

**Comment by rchl** [comment]
I'm just thinking that if someone uses one of those services to manage translations then most likely he won't be using any features from the new message format (correct me if I'm wrong, i have not looked much into that yet). So in that case maybe it would make sense that the module provides an option to treat translations as being in the "legacy" format and apply conversion automatically?

**Comment by darthf1** [comment]
> As he mentions, `@` is a [special character](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters) in `@nuxtjs/i18n` v8 (vue-i18n v9) and later.
> You need to use [literal interpolation](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation)
> 
> Thanks!

Ah ok, I was not yet aware of the new feature of v9.

Thanks @rchl for the questions, because I'm in exact that situation.

I have a PHP Rest API and Nuxt as my frontend. All my translations are in Lokalize, and some of them are shared between PHP and Nuxt. If I would change my translations from `@` to `{'@'}` I need to create additional logic in PHP to revert that.

In my situation, all translation messages are formatted in ICU syntax. This means I would use the `named interpolation` function I guess, but none of all the other which require special character processing.

Edit:
I need to check; but is this specific syntax compatible with v8? Because migrating my project to Nuxt 3 will be done in a separate branch in my project, and translation is shared between all branches. So I cannot update my translations before I go live with Nuxt 3.
