### ISSUE TITLE
Why nuxt-i18n edge not work in SSR

### ISSUE THREAD

**Issue by max5432112345** [nuxt-modules/i18n#1484]
### Version
"nuxt": "npm:nuxt3@latest"
 "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
i18n: {
    defaultLocale: 'en',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
      // onlyOnRoot: true
    },
    langDir: 'locales/',
    lazy: true,
    locales: [
      {
        code: 'en',
        file: 'en.json',
        iso: 'en-US',
        name: 'US'
      },
      {
        code: 'gb',
        file: 'gb.json',
        iso: 'en-GB',
        name: 'GB'
      }
    ],
    noPrefixDefaultLocale: false,
    parsePages: false,
    seo: false,
    strategy: 'prefix',
    vueI18n: {
      fallbackLocale: 'en',
      // silentFallbackWarn: true
    },
    vueI18nLoader: true
  },

  target: 'static',

  // ssr: false,
```

### Reproduction Link
https://github.com/max5432112345/nuxt-error-1   (I also added Pinia, axios-alt, and auth-alt)

### Steps to reproduce
1. chage in nuxt config to SSR
```
  target: 'static',

  // ssr: false,
```
2. npm run dev

### What is Expected?
to translate text with `const $i18n = useNuxtApp().vueApp.i18n.t()` and in templates with `$t()`.

### What is actually happening?
text what is need to be translate disappeared

**Comment by danielroe** [comment]
Please see https://github.com/nuxt/nuxt.js/issues/14479. Here is a working stackblitz: https://stackblitz.com/edit/github-ktzuls?file=package.json.
