### ISSUE TITLE
[next] You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.

### ISSUE THREAD

**Issue by provokcx** [nuxt-modules/i18n#1496]
### Version
@nuxtjs/i18n: 8.0.0-alpha.0-27692209.a559121
nuxt: 3.0.0-rc.8

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

**Comment by kazupon** [comment]
Thank you for your reporting!
Sorry for my late reply.

I've already fixed in vue-i18n v9.3.0-beta
This version will be included in nuxtjs/i18n v8.0.0-alpha.2 soon.
When it will have been released, you would be check it!

Thanks!
