### ISSUE TITLE
[NEXT] Custom route paths with nested route pages (Module's configuration) : 404 Page not found

### ISSUE THREAD

**Issue by renardsas** [nuxt-modules/i18n#1502]
### Version
@nuxtjs/i18n : "npm:@nuxtjs/i18n-edge"  
nuxt : "3.0.0-rc.8" 

### @nuxtjs/i18n configuration

```
i18n: {
    langDir: 'locales',
    lazy: true,
    baseUrl: 'https://github-jozcb1--3000.local-corp.webcontainer.io',
    locales: [
      {
        code: 'en',
        iso: 'en-GB',
        file: 'en.json',
        name: 'English',
      },
      {
        code: 'fr',
        iso: 'fr-FR',
        file: 'fr.json',
        name: 'Français',
      },
    ],
    defaultLocale: 'en',
    strategy: 'prefix_except_default',
    parsePages: false,
    pages: {
      blog: {
        en: '/news',
        fr: '/les-actualites',
      },
      'blog/article': {
        en: '/news/article',
        fr: '/les-actualites/article',
      },
    },
    detectBrowserLanguage: false,
    vueI18n: {
      legacy: false,
      locale: 'en',
    },
  }
```

### Reproduction Link

https://stackblitz.com/edit/github-jozcb1?file=nuxt.config.ts

### Steps to reproduce
1. Fresh nuxt 3 project : npx nuxi init nuxt-app
2. Install i18n module : "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
3. Add Nested routes, ex : blog, blog/article
4. Add i18n configuration

### What is actually happening?
404 Page not found

**Comment by eveningforgery** [comment]
Can reproduce using:
nuxt: 3.0.0-rc.9
@nuxtjs/i18n: 8.0.0-alpha.1

**Comment by kazupon** [comment]
I've just fixed it!
Please check it in the edge version.
Thanks!
