### ISSUE TITLE
Component interpolation with slots on Nuxt 3

### ISSUE THREAD

**Issue by retroriff** [nuxt-modules/i18n#1506]
### Version
@nuxtjs/i18n: "yarn:@nuxtjs/i18n-edge"
nuxt: "3.0.0-rc.8"

### Reproduction Link
https://codesandbox.io/p/github/retroriff/nuxt3/draft/quirky-minsky

After migrating to Nuxt 3 the component interpolation with slots doesn't work:

```
<i18n path="homepage.title">
  <template v-slot:link>
  <a href="https://nuxtjs.org/">{{ $t('homepage.anchor') }}</a> 
  </template>
</i18n>
```

**Comment by yf-hk** [comment]
The problem is that it doesn't support `@intlify/vite-plugin-vue-i18n` yet, hopefully it will be implemented soon.

**Comment by dargmuesli** [comment]
Are you sure you took a look at the breaking changes and saw the maintainer's comment on this?
- https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-component
- https://github.com/nuxt-community/i18n-module/issues/1463#issuecomment-1229456906

**Comment by retroriff** [comment]
You are right. The syntax has changed. Thank you
