### ISSUE TITLE
<html> element does not have a [lang] attribute

### ISSUE THREAD

**Issue by retroriff** [nuxt-modules/i18n#1507]
### Version
@nuxtjs/i18n: "yarn:@nuxtjs/i18n-edge"
nuxt: "3.0.0-rc.8"

### Reproduction Link
https://codesandbox.io/p/github/retroriff/nuxt3/draft/quirky-minsky

### @nuxtjs/i18n configuration
```js
i18n: {
    baseUrl: process.env.BASE_URL || "http://localhost:3000",
    defaultLocale: "en",
    detectBrowserLanguage: false,
    locales: [
      {
        code: "en",
        iso: "en-GB",
        name: "English",
        file: "en-GB.json"
      }
    ],
    parsePages: false,
    lazy: true,
    langDir: "locales"
  }
```

<html> element does not have a [lang] attribute.

**Comment by senher** [comment]
Hello, maybe you need to check the usage in the document. It is different from that in nuxt2,
Scroll it to the end:[ https://v8.i18n.nuxtjs.org/guide/seo]( https://v8.i18n.nuxtjs.org/guide/seo)

**Comment by retroriff** [comment]
> The locales' ISO codes are used as hreflang values. A "catchall" locale hreflang link is provided for each locale group (e.g. en-*). By default, it is the first locale provided

By default the first item defined in the locales option should appear as default lang attribute. What am I missing?

**Comment by senher** [comment]
> > 语言环境的 ISO 代码用作 hreflang 值。为每个语言环境组（例如 en-*）提供了一个“catchall”语言环境 hreflang 链接。默认情况下，它是提供的第一个语言环境
> 
> 默认情况下，在 locales 选项中定义的第一项应显示为默认语言属性。我错过了什么？

I think it's necessary to add:
```
vueI18n: {
    legacy: false,
    fallbackLocale: "en",
    messages: {
      en,
      de,
      ...
    },
  },
```

**Comment by retroriff** [comment]
I tried this but doesn't work either:

```
    vueI18n: {
      fallbackLocale: 'en',
      legacy: false,
      messages: {
        en: require('./locales/en-GB.json'),
        fi: require('./locales/fi-FI.json'),
      },
    },
```

**Comment by senher** [comment]
> I tried this but doesn't work either:
> 
> ```
>     vueI18n: {
>       fallbackLocale: 'en',
>       legacy: false,
>       messages: {
>         en: require('./locales/en-GB.json'),
>         fi: require('./locales/fi-FI.json'),
>       },
>     },
> ```

Hi，try to upgrade nuxt & i18n
This is the version I am currently using
```
"nuxt": "3.0.0-rc.12"
"@nuxtjs/i18n": "^8.0.0-alpha.1",
```

**Comment by retroriff** [comment]
I was using:
```
"nuxt": "3.0.0-rc.13",
"@nuxtjs/i18n": "yarn:@nuxtjs/i18n-edge",
```
I upgraded them but it doesn't work either 🙁
```
"nuxt": "3.0.0-rc.13",
"@nuxtjs/i18n": "^8.0.0-alpha.1",
```
Could you share your i18n config settings?

**Comment by senher** [comment]
> I was using:
> 
> ```
> "nuxt": "3.0.0-rc.13",
> "@nuxtjs/i18n": "yarn:@nuxtjs/i18n-edge",
> ```
> 
> I upgraded them but it doesn't work either 🙁
> 
> ```
> "nuxt": "3.0.0-rc.13",
> "@nuxtjs/i18n": "^8.0.0-alpha.1",
> ```
> 
> Could you share your i18n config settings?

sure
```
export default {
  locales: [{
    code:'en',
    name:'English'
  },{
    code:'es',
    name:'ES'
  },
  {
    code:'de',
    name:'DE'
  }],
  defaultLocale: "en",
  vueI18n: {
    legacy: false,
    fallbackLocale: "en",
    messages: {
      en,
      es,
      de
    },
  },
}

```

**Comment by retroriff** [comment]
`Cannot start nuxt:  en is not defined`

Where do you define the language shorthand values on `messages`?

**Comment by senher** [comment]
> 

```
./en.js
export default {
  hello:"hello"
}

import en from './en'
import es from './es'
import de from './de'
export default {
  locales: [{
    code:'en',
    name:'English'
  },{
    code:'es',
    name:'ES'
  },
  {
    code:'de',
    name:'DE'
  }],
  defaultLocale: "en",
  vueI18n: {
    legacy: false,
    fallbackLocale: "en",
    messages: {
      en,
      es,
      de
    },
  },
}
```

**Comment by retroriff** [comment]
Doesn't work either to me. Maybe this is the problem:

`Property '$nuxtI18nHead' does not exist on type 'NuxtConfig'.ts(2339)`

<img width="709" alt="image" src="https://user-images.githubusercontent.com/2946239/201084114-d72fa6b3-7091-466b-946d-f8e7b255f018.png">

I will push a basic setup to Stackblitz so it can be debugged.

**Comment by kazupon** [comment]
I think that compsable functions is auto imported in v8 beta
if you would have still issue, please open the new issue.
thanks!

**Comment by retroriff** [comment]
https://github.com/nuxt-community/i18n-module/issues/1675
