### ISSUE TITLE
Support for `vueI18nLoader` (@intlify/vite-plugin-vue-i18n) for `next`?

### ISSUE THREAD

**Issue by yf-hk** [nuxt-modules/i18n#1508]
### Is your feature request related to a problem? Please describe.
Currently `vueI18nLoader` option in `next` branch doesn't work.

### Describe the solution you'd like
Add support for `@intlify/vite-plugin-vue-i18n`

**Comment by kazupon** [comment]
current v8.0.0-alpha.1, it hasn't been supported. 
We will support it for v8.beta.

**Comment by kazupon** [comment]
In v8.0.0-beta.1 or later, this option is deprecated. Per component translations is enabled on default.
Thanks!
https://v8.i18n.nuxtjs.org/guide/migrating#deprecated-vuei18nloader-option
