### ISSUE TITLE
Changing of language with a sleect [Element-UI]

### ISSUE THREAD

**Issue by IvanWala** [nuxt-modules/i18n#1509]
Hi I'm using nuxt 2 with Element UI and this pluguin for translation. The versión is:     "@nuxtjs/i18n": "^7.3.0",

In the nuxt.config.js i have this configuration

```
  modules: [
    '@nuxtjs/i18n',
  ],
  
  i18n: {
    locales: [
      {
        code: 'ca',
        iso: 'ca-ES',
        file: 'ca-ES.js'
      },
      {
        code: 'es',
        iso: 'es-ES',
        file: 'es-ES.js'
      },
      {
        code: 'en',
        iso: 'en-GB',
        file: 'en-GB.js'
      }
    ],
    lazy: true,
    langDir: 'langs/',
    defaultLocale: 'ca',
    vueI18n: {
      fallbackLocale: 'ca'
    },
  },
```

I'm fetching the langs with this code

```
import axios from 'axios';

export default async() => await axios.get(process.env.STRAPI_URL+'/api/language/i18n?locale=ca-ES')
                .then(res => {
                    return res.data;
                })
```

And I have a select component with this code

```
<template>
  <nav>
    <el-select v-model="$i18n.locale" :placeholder="$i18n.locale" @change="onChange">
		<el-option
		  v-for="item in $i18n.locales"
		  :key="item.code"
		  :label="item.code"
		  :value="item.code"
      >
		</el-option>
	 </el-select>
  </nav>
</template>

<script>
export default {
  computed: {

  },
  methods: {
    onChange(locale) {
      console.log(locale);
      this.$i18n.setLocale(locale);
      this.$i18n.setLocaleCookie(locale);
      //this.$router.replace(this.switchLocalePath(locale));
      this.$router.push(this.switchLocalePath(locale));
      this.$forceUpdate();
    },
  }
}
</script>
```

The question is all works perfectly when you access without change of language. The problem is when you change the language in the select it seems to change correctly the page (I has previously added the paths to the page), but a 404 appears. And you need to refresh manually the page for see all well again. Any idea of what's can be the error?

Thanks.

**Comment by rchl** [comment]
I think you should not directly modify `$i18n.locale` (not use it in the `v-model`).
Also calling `$i18n.setLocale` in `onChange` should be enough.

**Comment by szulcus** [comment]
`v-model` will only work with Nuxt 3 (@nuxtjs/i18n v8)

**Comment by BobbieGoede** [comment]
FYI `setLocale` or `switchLocalePath` should also be used in Nuxt 3 (v8 and higher), mutating `$i18n.locale` directly will cause issues. Closing this as it seems to have been resolved a while ago.
