### ISSUE TITLE
Character "@" in message value cause vite error

### ISSUE THREAD

**Issue by misaon** [nuxt-modules/i18n#1512]
### Version
@nuxtjs/i18n: v8.0.0-alpha.1
nuxt: 3 RC-9

### Nuxt configuration

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```json5
i18n: {
  locales: [
    {
      code: 'cs',
      iso: 'cs-CZ',
      file: 'cs-CZ.json'
    },
    {
      code: 'en',
      iso: 'en-US',
      file: 'en-US.json'
    }
  ],
  defaultLocale: 'cs',
  lazy: true,
  langDir: 'lang/',
  vueI18n: {
    legacy: false
  }
}
```

### Steps to reproduce
Add this message to your lazy loaded json file:
```
"contactUsForPrice": "Pro zobrazení ceny se přihlaste, nebo nás kontaktujte na obchod@dinotoys.cz",
```

### What is Expected?
No errors

### What is actually happening?

```
ERROR  Error while formatting vite error: {
  plugin: 'unplugin-vue-i18n',
  id: '/app/lang/en-US.json',
  pluginCode: '{\n' +
    '  "aboutUsButton": "Immerse yourself in the fantasy world with us",\n' +
    '  "acceptAll": "Accept all",\n' +
  ...
}

[@nuxtjs/i18n] Failed locale loading: Vite Error
```

change to html entity works:
```
"contactUsForPrice": "Pro zobrazení ceny se přihlaste, nebo nás kontaktujte na obchod\t&#64;dinotoys.cz"
```

**Comment by dargmuesli** [comment]
You need to escape the `@` as outlined on the breaking changes guide: https://vue-i18n.intlify.dev/guide/migration/breaking.html#message-format-syntax
