### ISSUE TITLE
Load pages from an api

### ISSUE THREAD

**Issue by Flowko** [nuxt-modules/i18n#1517]
Hi, is it possible to load the pages object from an api, so instead of storing the pages object inside the code, we save them in the db, to easily change them without having to deploy the app again.

**Comment by rchl** [comment]
You can do a request from your nuxt config and set module configuration based on that but it can only be done at app's build time as it affects what routes are generated.

**Comment by Flowko** [comment]
thanks for checking this, do u have an example on how to do that exactly?, will help me alot

**Comment by rchl** [comment]
Use async nuxt config: https://nuxtjs.org/docs/features/configuration/#asynchronous-configuration

**Comment by Flowko** [comment]
okay thanks alot
