### ISSUE TITLE
[NEXT] If there are multiple `og:locale:alternate`, only the last one wins

### ISSUE THREAD

**Issue by VeselyJan92** [nuxt-modules/i18n#1520]
### Version
@nuxtjs/i18n: 8.0.0-alpha.1
nuxt: ^3.0.0-rc.10

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [?] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### Steps to reproduce

`"@vueuse/head": "v0.7.12"` deduplicates meta besed on `name` field not `hid`. 

If there are multiple `og:locale:alternate`, only the last one wins
`<meta hid="i18n-og-alt-en" property="og:locale:alternate" content="en" name="i18n-og-alt-en">`
`<meta hid="i18n-og-alt-de" property="og:locale:alternate" content="de" name="i18n-og-alt-de">`

To fix the problem: `useLocalHead` could return the `name` field as well.
```
const head = useLocaleHead({ addSeoAttributes: true })

useHead({
  meta: head.value.meta.map(meta =>({...meta, name: meta.hid}))
})
````

### What is Expected?

All `og:locale:alternate` meta tags are rendered

### What is actually happening?

Only last `og:locale:alternate` is rendered rendered

**Comment by harlan-zw** [comment]
The issue is that you're using `hid` which is not used by @vueuse/head as a de-duping key.

You should change it to `key`, although I think we should support `hid` for backwards compatibility.

**Comment by kazupon** [comment]
I've just supported `idetifierAttribue` option for `useLocaleHead`
You can avoid with using it!
Please check it edge version!

Thanks!

**Comment by VeselyJan92** [comment]
With `identifierAttribute` it is working. 
```
const head = useLocaleHead({ addSeoAttributes: true, identifierAttribute: "key" })
```

Just for notice the default is still `hid`. 

https://github.com/intlify/routing/blob/798283f3fbfc97b9295dde7493da35618e5671d1/packages/vue-i18n-routing/src/composables/head.ts#L29

Thanks

**Comment by harlan-zw** [comment]
There is a PR to support these legacy keys now https://github.com/vueuse/head/pull/102

Also, I was considering adding array support to the `content` field to avoid having to deal with this at all
