### ISSUE TITLE
[NEXT] Route navigation resets locale

### ISSUE THREAD

**Issue by warflash** [nuxt-modules/i18n#1527]
### Version
@nuxtjs/i18n: 8.0.0-alpha.1
nuxt: 3.0.0-rc.11

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### Reproduction Link
https://stackblitz.com/edit/github-jzewpd-crebuq?file=package.json

### Steps to reproduce
Swap the locale using the button, then navigate with the link at the bottom. The locale will be reset to the fallbackLocale

### What is Expected?
locale selection should be persisted across route change

### What is actually happening?
the selected locale does not persist across navigation

**Comment by kazupon** [comment]
Thank you for your reporting as always!
I've just checked your reproduction!

`no_prefix` routing strategy is used in your repro.
`no_prefix` routing strategy is depended in browser & cookie detection
see also the docs: https://v8.i18n.nuxtjs.org/guide/routing-strategies#no_prefix

These features hasn't still implemented fully yet.
when we will have been completed it, please you will check it again 🙏

So, we will close this issue.
Thanks!
