### ISSUE TITLE
Bug with using useFetch and nuxt 3 server api

### ISSUE THREAD

**Issue by misochenk0** [nuxt-modules/i18n#1545]
### Version
@nuxtjs/i18n: 
nuxt: 

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### Steps to reproduce
using prefix strategy
setting via server middleware local by redirecting user (for example entering from Portugal redirects to https://.../pt/)

using useFetch method to get a data inside dynamic page from nuxt server api

const { data } = await useFetch(`/api/client/vacancies/${router.currentRoute.value.params.id}`)

### What is Expected?

request is sending to /api/client/vacancies/35

### What is actually happening?

request is sending to  /pt/api/client/vacancies/35

**Comment by tuannguyenminh2086** [comment]
@misochenk0  hi,
I'm facing the same problem as you. did you find the solution ?
