### ISSUE TITLE
v8: setLocale ts error

### ISSUE THREAD

**Issue by productdevbook** [nuxt-modules/i18n#1547]
"@nuxtjs/i18n": "^8.0.0-alpha.2",

![image](https://user-images.githubusercontent.com/38668796/194487609-5bcff958-8b8e-459c-9cca-bb648652b06f.png)

**Comment by kazupon** [comment]
Fixed in v8.0.0-beta.2!
Please check it!

**Comment by irux** [comment]
using beta.8 and it doesn't work @kazupon 

I get this on the console.

![image](https://user-images.githubusercontent.com/10131986/214138195-31916642-9ee2-4080-9ed3-23b00a1fca55.png)
