### ISSUE TITLE
[NEXT] How can I get `$i18n.localeProperties`?

### ISSUE THREAD

**Issue by szulcus** [nuxt-modules/i18n#1552]
![image](https://user-images.githubusercontent.com/48328739/194811481-d071fc58-29d4-44b2-9d02-492e270edb83.png)
![image](https://user-images.githubusercontent.com/48328739/194811549-e5498e61-dac4-4322-a326-8f21c2521dce.png)

**Comment by kazupon** [comment]
Fixed in v8.0.0-beta.2!
Please check it!

**Comment by szulcus** [comment]
@kazupon In `^8.0.0-alpha.4` I have:
![image](https://user-images.githubusercontent.com/48328739/198084426-42ee47d0-e127-4a1a-a9f9-4eef712a6ea8.png)
🤔

**Comment by dargmuesli** [comment]
But alpha (4) is not beta (2) :thinking:
Alpha is older than beta.

**Comment by szulcus** [comment]
@dargmuesli Yes, thank you for your vigilance. I'm a little surprised it's already beta😅. `localeProperties` works fine now 😁.
