### ISSUE TITLE
How to enable cookies through nuxt middleware?

### ISSUE THREAD

**Issue by wangrezon** [nuxt-modules/i18n#1554]
Due to the limitation of GDPR, cookies cannot be enabled for all users.

But I can know whether the user is allowed through other cookies

So I want to enable cookies dynamically, For example, nuxt middleware.

Is there any way?

Thanks

**Comment by rchl** [comment]
You can disable the cookie (`detectBrowserLanguage.useCookie`) but I'm not sure how this will affect the `detectBrowserLanguage` logic. Would need to check the code. You could potentially implement custom logic to store that cookie when needed, after disabling that option.

That said, even with GDPR you should be able to treat this cookie as "essential" and not have to avoid setting it.

**Comment by wangrezon** [comment]
When the `detectBrowserLanguage. useCookie` is set to false, the`setLocaleCookie` is invalid. Actively set i18n_ Redirected cookies and redirects do not work.

**Comment by jpsc** [comment]
> That said, even with GDPR you should be able to treat this cookie as "essential" and not have to avoid setting it.

Exactly. Functional cookies are exempted from needing to be disabled because of GDPR.

**Comment by rchl** [comment]
Yes, given the above, I don't see the need to do address this.
