### ISSUE TITLE
[NEXT] `mergeLocaleMessages` throws ` Hydration text content mismatch` warning

### ISSUE THREAD

**Issue by yoyo-checkout** [nuxt-modules/i18n#1561]
### Version
@nuxtjs/i18n: 8.0.0-alpha.3
nuxt: 3.0.0-rc.11

### Nuxt configuration
Please change to [x] if relevant for this issue:

- [ ] Applies to a site deployed to a static server (site generated with nuxt generate)
- [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```js
i18n: {
  locales: [
    { code: 'jp', file: 'jp.json' },
    { code: 'en', file: 'en.json' },
  ],
  lazy: true,
  langDir: 'locale/',
  defaultLocale: 'jp',
  strategy: 'prefix',
  detectBrowserLanguage: {
    useCookie: true,
    cookieKey: 'i18n_redirected',
    redirectOn: 'root',
  },
  vueI18n: {
    legacy: false,
  },
},
```

### Reproduction Link
[https://stackblitz.com/edit/github-ih5gur-6jrlvp?file=nuxt.config.ts](https://stackblitz.com/edit/github-ih5gur-6jrlvp?file=nuxt.config.ts)

### Steps to reproduce
```bash
npm run dev
```
Then modify the url in Preview container to `https://github-ih5gur-6jrlvp--3000.local.webcontainer.io/jp`

### What is Expected?
The app should be generated without errors

### What is actually happening?
```
[Vue warn]: Hydration text content mismatch in <h1>:
- Client: こんにちは
- Server: welcome 
```
<img width="644" alt="截圖 2022-10-13 下午6 14 46" src="https://user-images.githubusercontent.com/19576371/195570358-57bec37d-61fd-46e1-886b-a63e5827c2a4.png">

**Comment by kazupon** [comment]
Thank you for your reporting!
and, sorry, my late reply. 🙇‍♂️ 

Unfortunately, I could not reproduce your reporting repo.
Could you give us fully reproduction codes please? 🙏

**Comment by yoyo-checkout** [comment]
Thank you for your replying.
This are the least config codes that could reproduce.

###  Configs
#### package.json
```json
{
  "scripts": {
    "dev": "nuxt dev",
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.11"
  },
  "dependencies": {
    "@nuxtjs/i18n": "8.0.0-alpha.3"
  }
}
```

#### nuxt.config.ts
```ts
export default defineNuxtConfig({
  modules: ['@nuxtjs/i18n'],
  i18n: {
    locales: [
      { code: 'jp', file: 'jp.json' },
      { code: 'en', file: 'en.json' },
    ],
    lazy: true,
    langDir: 'locale/',
    defaultLocale: 'jp',
    strategy: 'prefix',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root',
    },
    vueI18n: {
      legacy: false,
    },
  },
});
```

#### app.vue
```vue
<script lang="ts" setup>
const { mergeLocaleMessage, locale } = useI18n();

// we use this to simulate fetching translation from the other api on server side
// then merge back to locale messages
onServerPrefetch(async () => {
  const translation = await new Promise((resolve) => {
    resolve({ welcome: 'こんにちは' });
  });
  mergeLocaleMessage(locale.value, translation);
});
</script>

<template>
  <h1>{{ $t('welcome') }}</h1>
</template>
```

### Reproduce
1. Run `npm run dev`
2. Then replace the url with `/jp` postfix. It may be like `http://localhost:3000/jp`. (Since we use localePath)
3. The h1 text displaying is correct at fisrt, but immediately change to untranslated text. And the browser devtool console the errors above.

**Comment by kazupon** [comment]
Sorry, my lately response.

In docs says, `onServerPrefetch` is SSR only
https://vuejs.org/api/composition-api-lifecycle.html#onserverprefetch

You need to use `onMount` to manage i18n resources with `mergeLocaleMessages` with server-side and client-side awareness as follows

```vue
<script lang="ts" setup>
const { mergeLocaleMessage, locale } = useI18n();

onServerPrefetch(async () => {
  return new Promise((resolve) => {
    if (locale.value === 'jp') {
      mergeLocaleMessage(locale.value, { welcome: 'こんにちは' });
    }
    resolve();
  });
});

onMounted(async () => {
  if (locale.value === 'jp') {
    mergeLocaleMessage(locale.value, { welcome: 'こんにちは' });
  }
});
</script>
```

So this issue is not a bug in `@nuxtjs/i18n` (`vue-i18n`).

Thanks!

**Comment by yoyo-checkout** [comment]
Thank you for your replying. This is very helpful and inspired me!

For some SEO reasons, we decide to fetch translations from api on server side.
So we need to keep the translation value. And here is our solution.
```js
<script lang="ts" setup>
const { mergeLocaleMessage, locale } = useI18n();
const translation = useState('translation-key');

onServerPrefetch(async () => {
  translation.value = await new Promise((resolve) => {
    resolve({ welcome: 'こんにちは' });
  });
  mergeLocaleMessage(locale.value, translation.value);
});

onMounted(() => {
  mergeLocaleMessage(locale.value, translation.value);
});
</script>
```

Although call `mergeLocaleMessage` twice both on server and client side seems a little weird and still have the console warnings.😅
But it works as we expected, hope it helps others.

Thank you again!
