### ISSUE TITLE
Interpolation (with JS variables) not working in build

### ISSUE THREAD

**Issue by Venegrad** [nuxt-modules/i18n#1569]
Im using Nuxt i18n with langDir options ('lang/');
```
i18n: {
    locales: [
      {
        code: 'en',
        file: 'en-US.js',
        iso: 'en-US',
        name: "English"
      },
      {
        code: 'ru',
        file: 'uk-UA.js',
        iso: 'uk-UA',
        name: 'Ukranian'
      }
    ],
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root',  // recommended
    },
    lazy: true,
    vueI18nLoader: true,
    langDir: 'lang/',
    defaultLocale: 'en',
    vueI18n: {
      silentTranslationWarn: true,
      silentFallbackWarn: true,
    },
  },
```

In en-US.js im using default i18n syntax:
```
export default async (context, locale) => {
  return await Promise.resolve({
    "tt136": "Only {code} can be transfered to this address",
    ...

```

and in component:
```
{{ $t('tt136', { 'code': transactionFull.currency })}}
```

But thats not working:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/LnuAk.png

**Comment by rchl** [comment]
How do the translation messages look like when entering `window.$nuxt.$i18n.messages ` in developer tools console on this page?

**Comment by TayCheng091** [comment]
I have same issue .

I use Nuxt 3 to do my project .

Variables work when develop mode .

But after npm build , vairables cant work.

**Comment by sandercoffee** [comment]
Any update?

**Comment by ineshbose** [comment]
See related PR for `.js` file support: https://github.com/nuxt-modules/i18n/pull/1576 (for Nuxt 3, i18n v8)

**Comment by larsalbrecht** [comment]
Locally it runs with me. When I build the project, it no longer runs and I get the output that Venegrad has as well.

**Comment by jianbin-lim** [comment]
> I have same issue .
> 
> I use Nuxt 3 to do my project .
> 
> Variables work when develop mode .
> 
> But after npm build , vairables cant work.

I have  the same question, any update?

**Comment by default64bit** [comment]
From what I've tested, variables only work on .json files.
So for example, if you're using `locales/en.js` try converting it to `locales/en.json`

**Comment by ineshbose** [comment]
Helpful reproduction: [Reproduction stackblitz](https://stackblitz.com/github/JulienHenrotin/test_nuxt_i18n)

(If anyone else could provide, that'll be really helpful)

**Comment by kazupon** [comment]
nuxt i18n module use prerender and server including no longer at v8.0.0-beta.13
So, I belive this issue is fixed that version.
I'll close this issue.
if you have still the issue, please you will open as new issue.
Thanks!
