### ISSUE TITLE
 Cannot read properties of undefined (reading 'locale')

### ISSUE THREAD

**Issue by n4an** [nuxt-modules/i18n#1580]
### Version
@nuxtjs/i18n-edge
nuxt: latest (rc13)
### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### Reproduction Link
https://github.com/n4an/nuxt-error-7

### Steps to reproduce
Uncomment i18 module from nuxt settings

### What is actually happening?

[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'locale')
  at getLocale (./node_modules/vue-i18n-routing/dist/vue-i18n-routing.mjs:103:229)

**Comment by n4an** [comment]
was ok prior

**Comment by n4an** [comment]
with en.js error

500
[vite-node] [VITE_ERROR] /.nuxt/i18n.options.mjs

**Comment by n4an** [comment]
@kazupon

**Comment by kazupon** [comment]
sorry, dely my response

I seem that this issus is same as #1581

**Comment by n4an** [comment]
@kazupon whe i copied my code to freshly installed nuxt  that issue disappeared, but now appered other https://github.com/nuxt/framework/issues/8520

**Comment by n4an** [comment]
or may be 8.0.0-beta.2-27779937.21419f0 published 19 hours ago helped me
