### ISSUE TITLE
[NEXT] 'langDir' path resolve does not work on windows. 'absolute paths must be valid file://'

### ISSUE THREAD

**Issue by Bcavez** [nuxt-modules/i18n#1582]
### Version
@nuxtjs/i18n: v8.0.0-beta.1
nuxt: rc.12

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
  i18n: {
    locales: [
      {
        code: 'en',
        file: 'en-US.json',
      },
      { code: 'tr', file: 'tr-TR.json' },
    ],
    defaultLocale: 'tr',
    lazy: true,
    langDir: 'locales/',
    strategy: 'prefix_except_default',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root', // recommended
    },
    vueI18n: {
      legacy: false,
      locale: 'tr',
      fallbackLocale: 'tr',
      availableLocales: ['en', 'tr'],
    },
  },
```

### Reproduction Link

https://github.com/productdevbook/oku-nuxt3-template

### Steps to reproduce

On windows, run

yarn install
yarn dev

You should see the error in the terminal.

### What is Expected?

There should be no errors and I should see translations.

### What is actually happening?

[nuxt] [request error] [unhandled] [500] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
  at new NodeError (node:internal/errors:371:5)
  at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:1016:11)
  at Loader.resolve (node:internal/modules/esm/loader:89:40)
  at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)

**Comment by kazupon** [comment]
Thank you for your reporting!
Same #1518, so this issue is duplicated

Thanks!
