### ISSUE TITLE
[8.0.0-beta.1 - Nuxt 3] Language preferences not working?

### ISSUE THREAD

**Issue by djimnz** [nuxt-modules/i18n#1590]
### Version
@nuxtjs/i18n: 8.0.0-beta.1
nuxt: 3 RC12

### @nuxtjs/i18n configuration
```
i18n: {
        locales: [
            { code: 'en', iso: 'en-US', file: 'en-US.json', name: 'English' },
            { code: 'ko', iso: 'ko', file: 'ko-KR.json', name: '한국어' },
            { code: 'es', iso: 'es-ES', file: 'es-ES.json', name: 'Español' },
            { code: 'fr', iso: 'fr-FR', file: 'fr-FR.json', name: 'Français' }
        ],
        vueI18n: {
            fallbackLocale: 'en'
        },
        detectBrowserLanguage: {
            useCookie: true,
            alwaysRedirect: false,
        },
        defaultLocale: 'en',
        lazy: true,
        langDir: 'lang/',
        strategy: 'no_prefix',
    },
```

### What is actually happening?
My browser is currently configured for Korean as a first language, but my App is not setting up the cookie for the language `ko` and doesn't use the language `ko`, seems like falling into the English one.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/949997/198662632-8083ef7e-e77d-4c67-9445-511babb9ad0a.png">

I would like to configure the language based on my users preferend browser languages for their first visit (if the cookie doesn't exist, or if they haven't selected a language by themselve via a dropdown for example).

Do you have an idea why?

Thank you!

**Comment by kazupon** [comment]
I've just released v8.0.0-beta.3
close
