### ISSUE TITLE
[8.0.0-beta.1 - Nuxt 3 RC12] i18n block not working?

### ISSUE THREAD

**Issue by djimnz** [nuxt-modules/i18n#1591]
### Version
@nuxtjs/i18n: 8.0.0-beta.1
nuxt: 3 RC2

### @nuxtjs/i18n configuration
```
i18n: {
        locales: [
            { code: 'en', iso: 'en-US', file: 'en-US.json', name: 'English' },
            { code: 'ko', iso: 'ko', file: 'ko-KR.json', name: '한국어' },
            { code: 'es', iso: 'es-ES', file: 'es-ES.json', name: 'Español' },
            { code: 'fr', iso: 'fr-FR', file: 'fr-FR.json', name: 'Français' }
        ],
        vueI18n: {
            fallbackLocale: 'en'
        },
        detectBrowserLanguage: {
            useCookie: true,
            alwaysRedirect: false
        },
        defaultLocale: 'en',
        lazy: true,
        langDir: 'lang/',
        strategy: 'no_prefix',
    },
```

### What is Expected?
Translations interpolation should work.

### What is actually happening?
Hello,

Does anyone have a work around for the usage of `<i18n>` blocks in the template? It seems like this is not working on Nuxt 3 RC12 - Or, perhaps, I'm not doing things in a proper way.

This is what I'm currently trying to achieve, for a translations that require a link slot (inside `<template>`:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/949997/198666625-195a7944-41df-4143-9616-5e578c3bce95.png">

`auth.login.baseline` contain a translated string with {link}, link should take in place from the slot using the translation `auth.login.baseline_link`

What I'm getting with this is a webpage source code with the exact same `<i18n>` block, and no rendering.

Thank you! :)

**Comment by Kapcash** [comment]
I'm facing the same problem but found a workaround:

The problem is using `$t()` directly. If you use `const { t } = useI18n()` it works fine (so without the `$` in the template).
I guess the globally injected `$t()` function has something wrong.

Example:

```vue
<template>
  <div>
    <h1>{{ $t('title') }}</h1> <!-- Fail -->
    <h1>{{ t('title') }}</h1>  <!-- Works -->
  </div>
</template>

<script setup>
const { t } = useI18n({ useScope: 'local' })
</script>

<i18n lang="json">
{
  "en": {
    "title": "Hello world"
  }
}
</i18n>
```

**Comment by Kapcash** [comment]
From what I understand, the `useScope` parameter refers to the vue-i18n translations scope (see [vue-i18n Scope](https://vue-i18n.intlify.dev/guide/essentials/scope.html#scope) and [Local Scope Based Localization](https://vue-i18n.intlify.dev/guide/essentials/local.html))

The bug appears to be that`$t` only has access to the global translations (i.e. the ones in the `locales/xx.json` files for example), and not the `<i18n>` blocks. It's the same as using `const { t } = useI18n({ useScope: 'global' })`

So `const { t } = useI18n({ useScope: 'local' })` has access to the component's `<i18n>` translations, and the global ones correctly.

I guess this a regression :/

**Comment by kazupon** [comment]
Same as #1591.

**Comment by djimnz** [comment]
Hello,

The mentioned issue for this issue ticket wasn't for the scope, but for the usages inside template block for translations interpolation, such as following (see: `<!-- HERE Interpolation START -->`):

```vue
<template>
    <NuxtLayout name="auth">
        <template #baseline>
            <h2 class="...">{{ $t('auth.login.title') }}</h2>
            <!-- HERE Interpolation START -->
            <i18n path="auth.login.baseline" tag="p" class="...">
                <template v-slot:link>
                    <NuxtLink to="/signup" class="...">{{ $t('auth.login.baseline_link') }}</NuxtLink>
                </template>
            </i18n>
            <!-- HERE Interpolation END -->
        </template>
        <!-- ... -->
    </NuxtLayout>
</template>
```

Where translation json equal to:
```json
"auth": {
        "login": {
            "baseline": "Join us {link}, and access all the features",
            "baseline_link": "by clicking here",
        }
}
```

Thank you all!

P.S: @kazupon thank you for all your contributions and time!

**Comment by kazupon** [comment]
@djimnz 
Ah, sorry for my miss-understand

Translation component tag has been changed to `<i18n-t>` from `<i18n>` at vue-i18n v9 (@nuxtjs/i18n v8)
https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-component

One of the reasons for this change is that it is confusing with the scope name of the i18n custom block.
You would need to change to `<i18n-t>` from `<i18n>`
