### ISSUE TITLE
[8.0.0-beta-2 - Nuxt 3 RC12] i18n block only works in lazy

### ISSUE THREAD

**Issue by ineshbose** [nuxt-modules/i18n#1594]
### Version
@nuxtjs/i18n: 8.0.0-beta-2
nuxt: 3.0.0-rc.12

### @nuxtjs/i18n configuration

```
i18n: {
  defaultLocale: 'en',
  locales: [
    {
      code: 'en',
      name: 'English',
    },
    {
      code: 'es',
      name: 'Español',
    },
  ],
  vueI18n: {
    legacy: false,
  },
}
```

### What is Expected?

The following to work:
```vue
<script setup>
const { t } = useI18n({ useScope: 'local' })
</script>

<template>
  <div>
    <h1>{{ t('title') }}</h1>
  </div>
</template>

<i18n lang="json">
{
  "en": {
    "title": "Hello world"
  },
  "es": {
    "title": "Hola mundo"
  }
}
</i18n>
```

### What is actually happening?

No errors displayed, but the per-component blocks only work with `lazy: true` that further requires files for the locales, so updated configuration would be

```
i18n: {
  lazy: true,
  langDir: 'locales',
  defaultLocale: 'en',
  locales: [
    {
      code: 'en',
      name: 'English',
      file: 'en.json',
    },
    {
      code: 'es',
      name: 'Español',
      file: 'es.json',
    },
  ],
  vueI18n: {
    legacy: false,
    locale: 'en',
  },
}
```

The files `locales/en.json` and `locales/es.json` are empty (`{}`), however I do not wish to make use of these in the first place! I'm not sure if this is design by choice or hopefully the blocks do not rely on this.

**Comment by kazupon** [comment]
I've just released v8.0.0-beta.3
close
