### ISSUE TITLE
[NEXT] Could not find de locale in localeMessages

### ISSUE THREAD

**Issue by juni0r** [nuxt-modules/i18n#1610]
### Version
@nuxtjs/i18n: 8.0.0-beta.3
nuxt: 3.0.0-rc.12

### Nuxt configuration

```javascript
import numberFormats from "./locales/numberFormats";

export default defineNuxtConfig({
  modules: ["@nuxt/content", "@nuxtjs/i18n"],
  content: {
    documentDriven: true,
  },
  i18n: {
    vueI18n: {
      fallbackLocale: "de",
      numberFormats,
    },
    locales: [{ code: "de", iso: "de-DE", file: "de.js" }],
    defaultLocale: "de",
    langDir: "~/locales/",
  },
});

```

### Reproduction Link

https://github.com/juni0r/nuxi18n

### What is Expected?
Locale file for 'de' is loaded from `~/locales/de.js`

### What is actually happening?

```
[@nuxtjs/i18n] Could not find de locale in localeMessages
[intlify] Not found 'amount' key in 'de' locale messages.
```

**Comment by mateusk** [comment]
Same here. I am on Nuxt 3.0.0-rc.12 and @nuxtjs/i18n-edge. I had to move my `/locales` folder from `/src` to the app root folder, only then are the locale files correctly loaded again.

**Comment by kazupon** [comment]
Thank you for your reporting!

>locales: [{ code: "de", iso: "de-DE", file: "de.js" }],

You need to use JSON format as locale resources, not JavaScript executable format.
(Currently support JSON, JSON5 and YAML)
https://v8.i18n.nuxtjs.org/guide/lazy-load-translations

>langDir: "~/locales/",

you need to specify relative path from nuxt app project on `langDir` options. (e.g `./locales`).

**Comment by joffreyBerrier** [comment]
Hi @kazupon, why you only use JSON, JSON5 and YAML and not Javascript? Today my nuxt@2 project works with the same library.
I have separated all my translation files so I can't import them into a JSON file. Do you see the problem? 🥺

Example :
```javascript
import { View1 } from "@/pages/views1/lang/fr";
import { View2 } from "@/pages/views2/lang/fr";
import { View3 } from "@/pages/views3/lang/fr";

export default {
  lang: "fr",
  ...views1,
  ...views2,
  ...views3
}
```

**Comment by kazupon** [comment]
I'm working on js/ts supporting.
please wait.
see details https://github.com/nuxt-modules/i18n/pull/1576#issuecomment-1288119399
