### ISSUE TITLE
[8.0.0-beta-3 - Nuxt 3 RC13] Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by ineshbose** [nuxt-modules/i18n#1611]
### Version
@nuxtjs/i18n: 8.0.0-beta.3
nuxt: 3.0.0-rc.12

### @nuxtjs/i18n configuration

```
i18n: {
  lazy: true,
  langDir: 'locales',
  strategy: 'prefix',
  defaultLocale: 'en',
  detectBrowserLanguage: {
    useCookie: true,
    cookieKey: 'i18n_redirected',
    redirectOn: 'root',
  },
  locales: [
    {
      code: 'en',
      name: 'English',
      file: 'en.json',
    },
    {
      code: 'es',
      name: 'Español',
      file: 'es.json',
    },
  ],
  vueI18n: {
    legacy: false,
    locale: 'en',
  },
}
```

### Reproduction Link

https://stackblitz.com/edit/github-azrltz?file=nuxt.config.ts

### Description

It causes the app to crash on `/` when `strategy: 'prefix'` (a dev environment would be okay but production crashes), however `/` should redirect to `/:defaultLocale`.

**Comment by kazupon** [comment]
Thank you for your reporting!
I've met this issue too.

>It causes the app to crash on / when strategy: 'prefix' (a dev environment would be okay but production crashes), however / should redirect to /:defaultLocale.

If `prefix` strategy routing accesses `/`, redirect to `defaultLocale` option, this is the same behavior as v7.x. In v8, for this reason, the same behavior is used for migration.

I seem that the error apparently occurs when `redirectTo` is performed after the locale persists to the cookie with `useCookie`.

In the nuxt/framework issues, I found out similar issue.
https://github.com/nuxt/nuxt.js/issues/14838
Maybe,  this issue is related to it.

**Comment by ineshbose** [comment]
Updated to Nuxt 3 RC13 on StackBlitz to confirm that it still persists!

**Comment by danielroe** [comment]
Taking a quick look, could it be because you don't await or return `navigate`?

https://github.com/nuxt-community/i18n-module/blob/next/src/runtime/plugin.ts#L164-L168

https://github.com/nuxt-community/i18n-module/blob/next/src/runtime/plugin.ts#L369-L373

**Comment by kazupon** [comment]
@danielroe 
Thanks!

I check again, but return & await did not solve the problem.
I traced it in the debug log and it seems that multiple requests are being generated when redirecting on the server side. The last request is `/__nuxt_error?url=/asd&statusCode=404&statusMessage=Page+not+found:+/asd&message=Page+not+found:+/asd&description&data)`

**Comment by ineshbose** [comment]
I've spent a while trying to investigate & debug this myself, and I'm struggling to point at the issue!

**Comment by kazupon** [comment]
Thanks for your research and interest in nuxtjs/i18n.
I'll try to work on this issue as well once I am done with other issues. I'm really happy that the community is contributing for the issue resolving :)

**Comment by lukaszflorczak** [comment]
Maybe someone could confirm this, but it seems that one of these PRs (or both) fixes the problem: https://github.com/nuxt/nuxt/pull/18443 / https://github.com/nuxt/nuxt/pull/18445.

To test, you need to install Nuxt from the edge channel:

```json
"devDependencies": {
  "nuxt": "npm:nuxt3@latest"
}  
```

**Comment by kazupon** [comment]
@lukaszflorczak 
Thank you for your mentioninig!

@ineshbose 
If it would possible, could you confirm this on your reproduction? 🙏

**Comment by ineshbose** [comment]
Yes, thank you - sorry, I forgot this issue was still open - I have not been encountering this much with the latest versions!

**Comment by kazupon** [comment]
Thank you! ❤️

**Comment by elpeyotl** [comment]
We are getting the same issue after upgrading to nuxt 3.2.0. Check this issue https://github.com/nuxt-modules/i18n/issues/1865

**Comment by lukaszflorczak** [comment]
Yeah... It looks it's back again in my project too...
