### ISSUE TITLE
[NEXT] Cannot find module vue-i18n.mjs

### ISSUE THREAD

**Issue by DaniGTA** [nuxt-modules/i18n#1613]
### Version
@nuxtjs/i18n: 8.0.0-beta.3
nuxt: 3.0.0-rc.13
vue-i18n: "^9.2.2"

### Steps to reproduce
Start nuxi dev

### What is Expected?
Starting dev

### What is actually happening?
Cannot start nuxt:  Cannot find module 'nuxt\node_modules\vue-i18n\dist\vue-i18n.mjs'

**Comment by kazupon** [comment]
Thank you for your reporting!
I seem this issue is same #1568

We need minimum reproduction with github repo or stackbliz, so to resolve this issue.
Could you give us to it please? 🙏

**Comment by DaniGTA** [comment]
Its an issue with npm with yarn it works.

**Comment by kazupon** [comment]
Thanks!

>vue-i18n: "^9.2.2"

I noticed vue-i18n is installed un-expected version
nuxtjs/i18n will install vue-i18n v9.3 beta version

Could you try to re-install (e.g. `rm -rf node_modules package-lock.json`) please?

**Comment by DaniGTA** [comment]
Now i get `Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs' ` with `npm i`. 

With yarn it still works

**Comment by kazupon** [comment]
I've just fixed and release edge version `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`
Please check it!

**Comment by ahoiroman** [comment]
For me, the i18edge-version you just released fixes the issue.
