### ISSUE TITLE
How do i add a i18n title to a Nuxt 3 page?

### ISSUE THREAD

**Issue by DaniGTA** [nuxt-modules/i18n#1623]
I want to add a title to a nuxt 3 page with i18n and `<script setup>`

My current example:
https://stackblitz.com/edit/github-afztvu?file=pages/index.vue

In `<script setup>` it says it cant find `$t` and `getCurrentInstance` is also not working with `getCurrentInstance().proxy.$t`

**Comment by rchl** [comment]
Follow the documentation: https://v8.i18n.nuxtjs.org/getting-started/basic-usage

You haven't even configured the module nor specified translations to use.

**Comment by DaniGTA** [comment]
sorry stackblitz didnt save the `nuxt.config.ts` changes but the error is still the same.

And the document is not helpful in this example because there is no example to set a title or description.

even with `const { t } = useI18n();` it doesnt recognized `t`

See: https://stackblitz.com/edit/github-afztvu?file=pages/index.vue

**Comment by rchl** [comment]
There are some examples in https://v8.i18n.nuxtjs.org/guide/per-component-translations but it appears to not be documented in the API section.

**Comment by DaniGTA** [comment]
These example in https://v8.i18n.nuxtjs.org/guide/per-component-translations works for using `t` in `<script setup>` but not for using `t` in `definePageMeta`. 

Is there another way to set title or is it currently not supported?

**Comment by kazupon** [comment]
I think it might be issue of `definePageMeta` 🤔 
As I know as, `definePageMeta` is worked  on `setup` context of Vue

**Comment by kazupon** [comment]
Ah, `definePageMeta` is compiler macro.
docs say the below:
https://v3.nuxtjs.org/guide/directory-structure/pages/#page-metadata

>Much like defineEmits or defineProps (see Vue docs), definePageMeta is a compiler macro. It will be compiled away so you cannot reference it within your component. Instead, the metadata passed to it will be hoisted out of the component. Therefore, the page meta object cannot reference the component (or values defined on the component). However, it can reference imported bindings.

**Comment by kazupon** [comment]
As work-around, You can use `useRoute`.
The below example code:

```vue
<script setup lang="ts">
const route = useRoute()
const { t } = useI18n({ useScope: true })
route.meta.title = t('welcome')
</script>
```

**Comment by DaniGTA** [comment]
```
<script setup lang="ts">
const route = useRoute()
const { t } = useI18n({ useScope: true })
route.meta.title = t('welcome')
</script>
```
This doesn´t work with `nuxi generate` (html file has no title) and when the user opens the html the title doesn´t updates.
And it dont work with `nuxi dev`.

**Comment by DaniGTA** [comment]
With
```vue
<script setup lang="ts">
  const { t } = useI18n()
  useHead({
    title: t('welcome')
  });
</script>
```
it works for ssr.
On `nuxt generate` title is not set in the html file but on execute the user gets the title.
