### ISSUE TITLE
nuxt instance unavailable at Module.useAsyncData and  [Vue warn]: onServerPrefetch is called when there is no active component

### ISSUE THREAD

**Issue by mittci** [nuxt-modules/i18n#1625]
### Version
@nuxtjs/i18n: 
nuxt: 

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ x] Applies to a site deployed to a server with a Node backend

### Reproduction Link
https://github.com/Maxp777/nuxt4

### Steps to reproduce
1. without enabling 18n module - error nuxt instance unavailable at Module.useAsyncData
2. with enabled i18n module - [Vue warn]: onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

https://github.com/nuxt/nuxt.js/issues/15414

**Comment by kazupon** [comment]
Thank you for your reporting!

I’ve just made sure your repro repo.
I’ve faced the below error:

```
at Module.useAsyncData (./node_modules/nuxt/dist/app/composables/asyncData.mjs:27:38)
at Proxy.updateList (./store/list.store.ts:26:50)
at Proxy. (./node_modules/pinia/dist/pinia.mjs:1365:30)
at update (./pages/index.js:45:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async setup (./pages/index.js:67:83)
```

I seem that the cause of this error is occured by pinia.

Thanks!

**Comment by mittci** [comment]
Daniel Roe say it's a limitation of running composables async https://github.com/nuxt/nuxt.js/issues/15418
