### ISSUE TITLE
Support v8.x composables for nuxtjs/i18n v7.4

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#1627]
> I mean we should first provide a version of nuxtjs/i18n v7.4 on the nuxt bridge that is guaranteed to work with the options API so that the nuxt community can migrate to nuxtjs/i18n v8. Then, once that is released, we should backport the composables API from the nuxtjs/i18n v8 version and the composable API such as `useI18n` in vue-i18n to a version that works on the nuxt bridge as nuxtjs/i18n v7.5.

> We believe that by preparing in the above release roadmap, it will be possible to migrate incrementally to nuxt2 + nuxtjs/i18n v7, -> nuxt2 + nuxt bridge + nuxtjs/i18n v7.4 or v7.5, and finally nuxt3 + nuxtjs/i18n v8.

_Originally posted by @kazupon in https://github.com/nuxt-community/i18n-module/pull/1521#discussion_r975451777_

**Comment by kazupon** [comment]
We need back-port some composable functions from v8.x

**Comment by wattanx** [comment]
Hi, I am going to work on this issue!
First, I am planning to add a test using Nuxt Bridge.

**Comment by kazupon** [comment]
@wattanx 
Thanks for your efforts in migrating from Nuxt 2!
And Thank you for your interesting!

First, let's tackle the composables support provided by nuxt i18n first!
If you have any questions, please ask me.
You can ask directly on Discord!

**Comment by BobbieGoede** [comment]
Since we're not actively working on v7 anymore I'm closing this, if this is still being worked let me know and I'll reopen!
