### ISSUE TITLE
Incorrect render of computed value with useState passed to $t()

### ISSUE THREAD

**Issue by vadim-works** [nuxt-modules/i18n#1630]
### Version
@nuxtjs/i18n: ^8.0.0-beta.2
nuxt: 3.0.0-rc.13

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          greeting: 'Hello world! {0}'
        },
        es: {
          greeting: '¡Hola mundo! {0}'
        }
      }
    }
}
```

### Reproduction Link
https://codesandbox.io/s/nuxt-i18n-usestate-with-computed-9264ct

### Steps to reproduce
Open the codesandbox link above and see an example.
Or try to pass a computed value to `t()`. 

### What is Expected?
Hello world! 123
Hello world! 123

### What is actually happening?
Hello world! { "_object": { "$snumber": 123 }, "_key": "$snumber", "__v_isRef": true }
Hello world! { "_object": { "$snumber": 123 }, "_key": "$snumber", "__v_isRef": true }

**Comment by kazupon** [comment]
Thank you for your reporting!

`useState` return the `Ref`
https://v3.nuxtjs.org/api/composables/use-state#usestate

You should not need wrap further with `computed`.
So, you need use the reactivity APIs correctly

Thanks!
