### ISSUE TITLE
v8 Documentation Site Navigation is Broken

### ISSUE THREAD

**Issue by daguitosama** [nuxt-modules/i18n#1631]
### Steps to reproduce
Just open the v8 docs [site](https://v8.i18n.nuxtjs.org)
   https://v8.i18n.nuxtjs.org

### What is Expected?
To be able to use the navigation

### What is actually happening?
When the document loads the navigation blinks, and disappears. When open in the console shows up a hydration  error:
```txt
Hydration completed but contains mismatches.
c @ entry.3712fd5b.js:1
```

<img width="1251" alt="Screen Shot 2022-11-09 at 16 26 38" src="https://user-images.githubusercontent.com/34744883/200945795-55981fd4-5cbe-480d-85cb-deb3d3bab076.png">

**Comment by kazupon** [comment]
Thank you for your reporting!

@nuxtjs/i18n v8 docs is built by docs
So, I think docs might have something issue 🤔  /cc @Atinux

**Comment by lustremedia** [comment]
Normal navigation towards the documentation from the entry page works (Get Started Link). Subsequent navigation also works, but if you **refresh** the page the blinkage starts to happen ... and the hydration error shows up in the console ... 

A hard refresh (f5) is the issue for me!

**Comment by atinux** [comment]
Could you try with latest Docus? https://docus.dev

**Comment by daguitosama** [comment]
Looks like navigation on v8 site is back, Docus good too. 
<img width="1179" alt="Screen Shot 2022-11-17 at 21 33 03" src="https://user-images.githubusercontent.com/34744883/202603491-aab6a9db-8a26-4311-96a9-695ce2a7191e.png">

**Comment by daguitosama** [comment]
So i think this issue it's done.
