### ISSUE TITLE
[8.0.0-beta.3 - Nuxt 3 RC13] `$te` is not auto-imported in template - _ctx.$te is not a function

### ISSUE THREAD

**Issue by TheAlexLichter** [nuxt-modules/i18n#1643]
### Version
@nuxtjs/i18n: 8.0.0-beta.3
nuxt:3.0.0-rc.13

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
i18n: {
    vueI18n: {
      legacy: false,
      locale: 'en',
      messages: {
        en: {
          welcome: 'Welcome',
        },
        fr: {
          welcome: 'Bienvenue',
        },
      },
    },
  },
```

### Reproduction Link

https://stackblitz.com/edit/i18n-module-1643?file=app.vue,nuxt.config.ts,package.json

### Steps to reproduce

1. Use any config
2. Write `$te` in template

### What is Expected?

* Having `$te` working out of the box

### What is actually happening?

See `_ctx.$te is not a function` as error.

**Comment by kazupon** [comment]
Thank you for your reproting!

`$te` injected into component is no longer provided by the Composition API (setup hook or script setup) from vue-i18n v9.
https://vue-i18n.intlify.dev/api/injection.html#componentcustomproperties

The reason for the deprecation is that having that API would complicate the i18n implementation by programmatically checking for the presence of keys.

As an alternative to checking for the presence of a key, vue-i18n by default outputs a warning if the key is not present.

And also, vue-i18n provides an eslint plugin that can be used to statically check for the presence of a key.
https://eslint-plugin-vue-i18n.intlify.dev/

**Comment by TheAlexLichter** [comment]
@kazupon Thanks for the info! So there is no way to programmatically check the existence of a key and e.g. render a component based on it (except with the legacy API)?

**Comment by kazupon** [comment]
@manniL 
Ah, sorry. vue-i18n have been still providing  Composition API equivalent to it. 😅 
You can use `te`:
https://vue-i18n.intlify.dev/api/composition.html#te-key-locale
```ts
const { te } = useI18n(); 
```

**Comment by TheAlexLichter** [comment]
Good to know!

But still, `$te` should be automatically injected without using composition API, similar to `$t`, right? That's not the case (see example above).

**Comment by kazupon** [comment]
Hi!
I supported `$te` globaly.
Please try to install edge version `@nuxtjs/i18n-edge@8.0.0-beta.4-27807388.1909184`
