### ISSUE TITLE
How to extendRoutes for dynamic pages from CMS with different paths per locale?

### ISSUE THREAD

**Issue by katerlouis** [nuxt-modules/i18n#1648]
## Context
We are using Storyblok as headless cms for a dual language website. Step by step we are moving our hardcoded pages to said storyblok. 

## Problem
Vue doesn't know the routes anymore, because we obviously got rid of the `.vue`-files in `/pages`. In situations where we have to hardcode a link to a storyblok page (in menu or footer for instance), we have a problem. The following no longer works:

`<NuxtLink to="team-internships">{{ $t('menu.internships') }}</NuxtLink>`

which would usually result in links with:
* de: `/team/praktika`
* en: `/en/team/internships`

## Failed solution attempt
With `router.extendRoutes()` in `nuxt.config.js` I cannot tell i18n that this page has different paths in different locales.

## Question
How would you recommend solving the issue of hardcoded links to dynamic pages with different paths per locale?

My `i18n.config.js`

```js
export default {
  locales: [
    {
      code: 'de',
      iso: 'de-DE', // https://www.science.co.il/language/Locale-codes.php
      name: 'Deutsch',
      file: 'de-DE.json',
    }, {
      code: 'en',
      iso: 'en-US',
      name: 'English',
      file: 'en-US.json',
    },
  ],

  vueI18nLoader: true,

  defaultLocale: 'de',

  // no `~/` necessary – nuxt automatically looks inside folder provided by `srcDir` in `nuxt.config.js`
  langDir: 'locales/',

  // needs to be `true` for language files to work
  lazy: true,

  seo: true,

  detectBrowserLanguage: false,

  vueI18n: {
    // some test messages for nuxt's automatic route generation setup
    // must be in this file and not in locale files
    messages: {
      en: {
        welcome: 'Welcome',
      },
      de: {
        welcome: 'Willkommen',
      },
    },
    fallbackLocale: 'de',
  },
};
```

**Comment by jbmolle** [comment]
Hi katerlouis,
You can overwrite route meta at runtime through the useRoute() composable in Nuxt3.
I've answered in this discussion
#1588 
Hope it helps!
JB

**Comment by katerlouis** [comment]
Thanks a lot @jbmolle – Unfortunately we are still on Nuxt2 and can't migrate now or in the foreseeable future :( – Is it possible to overwrite route meta in Nuxt2 aswell?

Also: As a reminder, I'm for translated route paths, not dynamic and reactive params– Your proposition does not add the routes to `router.js` so that I can use `localePath('my-site')`, right?

**Comment by BobbieGoede** [comment]
Closing this as v6/v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
