### ISSUE TITLE
alwaysRedirect in detectBrowserLanguage not working

### ISSUE THREAD

**Issue by blouflashdb** [nuxt-modules/i18n#1650]
### Version
@nuxtjs/i18n: 8.0.0-beta.4
nuxt: 3.0.0-rc.13

### Nuxt configuration
 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
i18n: {
    locales: [
      {
        code: "en",
        iso: "en-US",
        name: "lang_english",
      },
      {
        code: "de",
        iso: "de-DE",
        name: "lang_german",
      },
    ],
    defaultLocale: "en",
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: "i18n_redirected",
      redirectOn: "root",
      alwaysRedirect: true,
    },
    vueI18n: {
      legacy: false,
      locale: "en",
      messages: {
        en,
        de,
      },
    },
  },
```

### Reproduction Link
https://github.com/blouflashdb/Awesome-Nimiq

### Steps to reproduce
- call setLocale to a different language than the default language.
- open app root without the lang route in a new tab (http://localhost:3000/)

### What is Expected?
expected to be redirected to http://localhost:3000/de because "de" is the value in the cookie.

### What is actually happening?
no redirect to http://localhost:3000/de

**Comment by kazupon** [comment]
Thank you for your reporting!
and, sorry late my reply.
I'll try to fix this issue!

**Comment by shinesoftware** [comment]
Hello @kazupon thanks for your code. Have you any updates about this issue reported here? We have the same issue.
Keep me updated ;) and thanks again.
Regards
