### ISSUE TITLE
Per-component Translations

### ISSUE THREAD

**Issue by andreidmour** [nuxt-modules/i18n#1658]
In the documentation https://v8.i18n.nuxtjs.org/guide/per-component-translations the example doesn't seem to work. What shoud the configuration be to enable this funationality. setup: Nuxt 3.0.0  i18n v8 beta 4

**Component**

```vue
<template>
    <div>
      <p>{{ $t('welcome') }}</p>
    </div>
</template>

<script setup lang="ts">
const { t } = useI18n({
    useScope: 'local'
})
</script>

<i18n>
{
  "en": {
    "welcome": "Welcome"
  },
  "es": {
    "welcome": "Ola"
  }

}
</i18n>
```

**Nuxt Config**

```js
export default defineNuxtConfig({
  srcDir: 'src/',
  typescript: {
    strict: true,
  },
  modules: [
    '@nuxtjs/i18n'
  ],
  i18n: {
    locales: [
      {
        code: 'en',
        file: 'en.json'
      },
      {
        code: 'es',
        file: 'es.json'
      },
    ],
    defaultLocale: 'en',
    lazy: true,
    strategy: 'prefix_except_default',
    langDir: 'locale',
    vueI18n: {
      legacy: false,
      locale: 'en',
    }
  }
});
```

**Error in browser:**

```
[intlify] Not found 'welcome' key in 'en' locale messages.
```

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I could not reproduce this issue.
We need reproduction repo.
Could you give us your minimum reproduction repo or stackbliz please? 🙏

**Comment by jbmolle** [comment]
Did you try t('welcome') instead of $t('welcome') ? You're defining the t function in use I18n scope local.

**Comment by kazupon** [comment]
Thank you for your PR description updating.

You need use `t` which is exported by `useI18n`, **not `$t`**.
because, `$t` work in global scope.

I've update [v8 docs](https://v8.i18n.nuxtjs.org/guide/per-component-translations/) with [this PR](https://github.com/nuxt-community/i18n-module/commit/2bbf18d6ecffc659af256c5d1363112ebd58e57c)

Thanks!
