### ISSUE TITLE
useI18n() does not return locales when you use Per-component translations

### ISSUE THREAD

**Issue by phanect** [nuxt-modules/i18n#1659]
### Version
@nuxtjs/i18n: 8.0.0-beta.4-27812700.b832f07
nuxt: 3.0.0

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```js
i18n: {
  locales: [
    {
      code: 'en',
      iso: 'en',
      name: 'English',
    },
    {
      code: 'ja',
      iso: 'ja-JP',
      name: '日本語',
    },
  ],
  vueI18n: {
    legacy: false,
  },
},
```

### Reproduction Link

https://github.com/phanect/repro-nuxt-i18n-lang-switcher

### Steps to reproduce

If you use per-component translations (i.e. add `<i18n>` block in the Vue SFC), `useI18n()` returns `i18n` object without `locales`, therefore the lang switcher does not work.
If you remove the `<i18n>` block from the SFC, `useI18n()` works properly and you can access `i18n.locales` properly, so I think `<i18n>` block causes this problem.

1. Create a page component and add following code in `<script setup>` block:

```js
const { locales, t } = useI18n();
const switchLocalePath = useSwitchLocalePath();
```

2. Add `<i18n>` block in the page component
3. List available locales as following code:

```html
<a
  v-for="locale in locales"
  :key="locale.code"
  :href="switchLocalePath(locale.code)"
>
  {{ locale.name }}
</a>
```

### What is Expected?

List of available locales are shown

### What is actually happening?

List of available locales are not shown

**Comment by andreidmour** [comment]
Same problem #1658

**Comment by phanect** [comment]
@andreidmour I don't think this issue is a duplicate of #1658.

You didn't extract `locales` from the return value of `useI18n()` in #1658. This issue is about missing `locales`, so I think #1658 is a different problem from this issue.

**Comment by kazupon** [comment]
Thank you for your reporting!
I've just reproduce this issue.

This issue is a bug.
I'll try to fix.

**Comment by kazupon** [comment]
I've just fixed this issue.
You can use edge version `@nuxtjs/i18n-edge@8.0.0-beta.4-27816734.493bb8f`
Please try it!

Thanks!

**Comment by phanect** [comment]
@kazupon Thanks, I have confirmed the issue is fixed on my end.
Now `useI18n()` returns `i18n.locales` properly.
