### ISSUE TITLE
[NEXT] How can I use <i18n-t> component?

### ISSUE THREAD

**Issue by szulcus** [nuxt-modules/i18n#1664]
How can I use this component: https://vue-i18n.intlify.dev/guide/advanced/component.html#slots-syntax-usage. Theoretically, I can take the `Translation` component, but it has the wrong types, which is quite a pain. Is there any other way to do this?
```ts
import { Translation } from 'vue-i18n';
```
```
(property) Translation: {
    name: string;
    props: {
        keypath: {
            type: StringConstructor;
            required: boolean;
        };
        plural: {
            type: (StringConstructor | NumberConstructor)[];
            validator: (val: any) => boolean;
        };
    } & {
        ...;
    };
    setup(props: any, context: any): any;
}
Type '{ class: string; keypath: string; plural: number; tag: string; scope: string; }' is not assignable to type 'ComponentProps<{ name: string; props: { keypath: { type: StringConstructor; required: boolean; }; plural: { type: (StringConstructor | NumberConstructor)[]; validator: (val: any) => boolean; }; } & { ...; }; setup(props: any, context: any): any; }>'.
  Type '{ class: string; keypath: string; plural: number; tag: string; scope: string; }' is missing the following properties from type '{ name: string; props: { keypath: { type: StringConstructor; required: boolean; }; plural: { type: (StringConstructor | NumberConstructor)[]; validator: (val: any) => boolean; }; } & { ...; }; setup(props: any, context: any): any; }': name, props, setupts(2322)
```
![image](https://user-images.githubusercontent.com/48328739/203043007-786a9e72-3de8-40c1-91f9-e7010c192ea9.png)

**Comment by kazupon** [comment]
Translation component (`<i18n-t>`) is built-in nuxtjs/i18n.

Currently, there is a issue with type inference being unknown in Volar, but you can use it in template.
We are recognized of this issue and it needs to be fixed in vue-i18n.

**Comment by szulcus** [comment]
@kazupon I didn't think to use it globally because Volar was showing me type `unknown`, thanks!
![image](https://user-images.githubusercontent.com/48328739/203103451-9fb33354-482a-4d4a-9c9f-e4a25536bc3c.png)
