### ISSUE TITLE
Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'  

### ISSUE THREAD

**Issue by raducretu** [nuxt-modules/i18n#1665]
### Version
@nuxtjs/i18n: ^8.0.0-beta.4
nuxt: ^3.0.0

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
modules: [
        '@nuxtjs/tailwindcss',
        '@nuxtjs/i18n'
],
i18n: {
        locales: [{ code: 'ro', file: 'ro.json' }],
        defaultLocale: 'ro',
        langDir: 'locales/'
}
```

### Reproduction Link
Node v16.11.0

### What is Expected?
I would like to start the dev server, but I cannot due to this error.

I used to use @intlify/nuxt3 before nuxt 3, but when I updated nuxt and changed to this, I canot start the dev server.

I removed .nuxt .node_modules package-lock.json, used npm cache clean --force, but still cannot solve this

**Comment by kazupon** [comment]
duplicate issue as #1640 
You can use edge version `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`
Thanks!
