### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by jasonfeidt** [nuxt-modules/i18n#1666]
### Version
@nuxtjs/i18n:^7.3.0
nuxt:"3.0.0"

### Steps to reproduce
1. Setup New Nuxt3 Project with npx nuxi init nuxt-app
2. yarn install
3. yarn add  @nuxtjs/i18n
4. add module and options to nuxt.config.ts
{
  modules: [
    [
      '@nuxtjs/i18n',
      {
        locales: ['en', 'es'],
        defaultLocale: 'en',
        vueI18n: {
          fallbackLocale: 'en',
          messages: {
            en: {
              greeting: 'Hello world!'
            },
            es: {
              greeting: '¡Hola mundo!'
            }
          }
        }
      }
    ]
  ]
}
 
### What is Expected?
yarn dev should work.

### What is actually happening?
ERROR: Cannot restart nuxt:  Cannot read properties of undefined (reading 'options')

**Comment by larswww** [comment]
Same issue here. Doesn't matter if i supply my options in the modules array, or under i18n: {} in the nuxt.config.ts.

**Comment by jasonfeidt** [comment]
> Same issue here. Doesn't matter if i supply my options in the modules array, or under i18n: {} in the nuxt.config.ts.

Yes, I can confirm. It does not make a difference if options are defined or not.

**Comment by divine** [comment]
Hello,

Version 7.3.0 isn’t compatible with Nuxt v3, use version ^8.

Thanks!

**Comment by larswww** [comment]
Thats actually mentioned in the docs i clearly didn't read well enough! [nuxt3 i18n docs](https://v8.i18n.nuxtjs.org/) for anyone else who runs into the same thing in the future.

**Comment by jasonfeidt** [comment]
> Hello,
> 
> Version 7.3.0 isn’t compatible with Nuxt v3, use version ^8.
> 
> Thanks!

Thank you!
