### ISSUE TITLE
Issue of dependencies when installed through pnpm

### ISSUE THREAD

**Issue by lity** [nuxt-modules/i18n#1671]
### Version
@nuxtjs/i18n: 8.0.0-beta.4
nuxt: 3.0.0

After I run command "pnpm i" to install packages and start my project, errors occured,  @nuxtjs/i18n`s dependencies "cookie-es" "html-tags" "is-https" "js-cookie" "ufo" not found, so I had to mannually add these packages to my project.

No such problem with npm and yarn.

**Comment by kazupon** [comment]
Thank you for your feedback.

if we use `pnpm`, we need to use with `--shamefully-hoist` option.

```sh
pnpm i --shamefully-hoist
```

and if we have `.npmrc` in your project, you have to confirm `shamefully-hoist`
Nuxt official installation docs has already mentiond about it.
https://nuxt.com/docs/getting-started/installation

Thanks!
