### ISSUE TITLE
get json5 lang files

### ISSUE THREAD

**Issue by sangemi** [nuxt-modules/i18n#1672]
### Version
        "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
        "nuxt": "^3.0.0-rc.14",

### Nuxt configuration
Please change to `[x]` if relevant for this issue:
 - [v ] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

````
i18n: {
        locales: [
            { code: 'ko', iso: 'ko-KR', file: 'ko.json5' },
            { code: 'en', iso: 'en-US', file: 'en.json5' },
            { code: 'zh', iso: 'zh-CN', file: 'zh.json5' },
            //{ code: 'ja', iso: 'ja-JP', file: 'ja.js' },
        ],
        langDir: 'lang/',
        lazy: true,
        defaultLocale: 'en',
        strategy: 'no_prefix', // 'prefix_and_default',
        vueI18n: {
            fallbackLocale: 'en',
            availableLocales: ['en', 'ko', 'zh'],
        },
        detectBrowserLanguage: {
            useCookie: true,
            cookieKey: 'i18n_redirected',
            redirectOn: 'root',  // recommended
        }
}
````

### What is Expected?

I made ~/lang/en.json5
I think resolveLocales() can read my files well.

```` 
const files = await resolveFiles(path, "**/*{json,json5,yaml,yml}");
````

But I think another default nuxt part try to read .json5 file. So I encoutered 500 error.

### What is actually happening?

[nuxt] [request error] [unhandled] [500] Unknown file extension ".json5" for c:\Dev\Server\Git-Lawfirmy\lawfirmy2\lang\en.json5
  at new NodeError (node:internal/errors:387:5)
  at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:11)
  at defaultGetFormat (node:internal/modules/esm/get_format:117:38)
  at defaultLoad (node:internal/modules/esm/load:81:20)
  at nextLoad (node:internal/modules/esm/loader:163:28)
  at ESMLoader.load (node:internal/modules/esm/loader:601:26)
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
  at new ModuleJob (node:internal/modules/esm/module_job:63:26)
  at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:476:17)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)

If I delete
```
                locales: [
                    { code: 'ko', iso: 'ko-KR', file: 'ko.json5' },
                    { code: 'en', iso: 'en-US', file: 'en.json5' },
                    { code: 'zh', iso: 'zh-CN', file: 'zh.json5' },
                    //{ code: 'ja', iso: 'ja-JP', file: 'ja.js' },
                ],
                langDir: 'lang/',
                lazy: true,
```
the error is disappeared.

If I change ```langDir: 'lang/',``` to ```langDir: 'lang2/',```(wrong directory), the error is disappeared.

**Comment by kazupon** [comment]
Thank you for your reporting!
Same #1518
This issue is occured on windows 
We will fix this issue until v8 official release.
Thanks
