### ISSUE TITLE
[next] fix: all collection items must start at the same column #204 

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#1674]
Raising a ticket here for visibility of an upstream issue: https://github.com/intlify/bundle-tools/issues/204

### What is happening?
An error shows: `all collection items must start at the same column`

### What is expected?
That error does not show and the projects builds successfully.

### Steps to reproduce
Use `yaml` as i18n content.

### Reproduction Link
https://stackblitz.com/edit/github-a5wazj?file=app.vue,nuxt.config.ts

### Version
@nuxtjs/i18n: `npm:@nuxtjs/i18n-edge@8.0.0-beta.4-27808790.0c283db`
nuxt: `[3.0.0](npm:nuxt3@3.0.0-rc.14-27802701.2f53495)`

**Comment by dargmuesli** [comment]
For JSON input the error is different: https://stackblitz.com/edit/github-a5wazj-jxeg2f?file=app.vue

**Comment by dargmuesli** [comment]
A workaround is to to remove the `VueI18nPlugin` from `nuxt.config.js`'s vite plugin array. But what if I wanted to use custom options for that plugin? :thinking:

**Comment by kazupon** [comment]
As mentioned at here:
https://github.com/intlify/bundle-tools/issues/204

Thanks!

**Comment by kazupon** [comment]
> A workaround is to to remove the VueI18nPlugin from nuxt.config.js's vite plugin array. But what if I wanted to use custom options for that plugin? :thinking:

Ah, We should support like `bundle` option.

We will need to pick up the options you need from the URL below.
https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#-options

**Comment by kazupon** [comment]
I've just posted it as new issue.
https://github.com/nuxt-modules/i18n/issues/1720

so close.
