### ISSUE TITLE
<html> element does not have a [lang] attribute

### ISSUE THREAD

**Issue by retroriff** [nuxt-modules/i18n#1675]
### Version
"@nuxtjs/i18n": "^8.0.0-beta.4",
"nuxt": "3.0.0-rc.13"

### Reproduction Link
https://stackblitz.com/github/retroriff/nuxt-refresh

### @nuxtjs/i18n configuration
```js
i18n: {
    baseUrl: process.env.BASE_URL || "http://localhost:3000",
    defaultLocale: "en",
    detectBrowserLanguage: false,
    locales: [
      {
        code: "en",
        iso: "en-GB",
        name: "English",
        file: "en-GB.json"
      }
    ],
    parsePages: false,
    lazy: true,
    langDir: "locales"
  }
```

<html> element does not have a [lang] attribute.

**Comment by kazupon** [comment]
Thank you for your reporting!

I've just checked your stackblitz

You need to specify the i18n head meta info that is getten with `useLocaleHead` into `useHead` that is built-in composable in Nuxt.
nuxtjs/i18n v8 docs said:
https://v8.i18n.nuxtjs.org/guide/seo

Thanks!

**Comment by ItsRyanWu** [comment]
The issue is here: https://i18n.nuxtjs.org/api#nuxti18nhead
I somehow got trapped by this outdated document website and it still documents old API, I was so confused until I find the current thread!
![image](https://github.com/nuxt-modules/i18n/assets/17338101/dcaa0841-3ea0-49f5-826b-4d10b5a2374a)
