### ISSUE TITLE
Why `tm` function doesn't work with arrays, like vue-i18n nine version?

### ISSUE THREAD

**Issue by mohammadali0120** [nuxt-modules/i18n#1681]
Hi, I have some array/object items in my locale file like the example below:

```js
  i18n: {
    locales: [
      {
        name: "Farsi",
        code: "fa",
        link: "/",
        flagCode: "ir",
        direction: "rtl",
      },
      {
        name: "English",
        code: "en",
        link: "/en",
        flagCode: "us",
        direction: "ltr",
      },
    ],
    defaultLocale: "fa",
    vueI18n: {
      legacy: false,
      locale: "en",
      messages: {
        en: {
          welcome: "Welcome",
          subHeaderItems: {
            links: [
              { value: "Home", link: "/", icon: "fa-house" },
              { value: "Posts", link: "/posts", icon: "fa-book" },
              {
                value: "Podcasts",
                link: "/podcasts",
                icon: "fa-podcast",
              },
            ],
          },
        },
        fa: {
          welcome: "خوش اومدی",
          subHeaderItems: {
            links: [
              { value: "صفحه ی اصلی", link: "/", icon: "fa-house" },
              { value: "پست ها", link: "/posts", icon: "fa-book" },
              {
                value: "پادکست ها",
                link: "/podcasts",
                icon: "fa-podcast",
              },
            ],
          },
        },
      },
    },
  },
```

But it doesn't return the array or object it just returns an empty object or array, see in the image below:

![Capture](https://user-images.githubusercontent.com/59791091/204096916-a2c466ff-54e6-4c6f-965b-da8821cd42e1.PNG)

And here my Vue component code:

```js
<template>
  <div>
    {{ JSON.parse(JSON.stringify(items)) }} 
    <!-- It has no difference without/with converting the array/object to JSON -->
  </div>
</template>

<script setup>
const { tm } = useI18n();

const items = computed(() => {
  const myItems = tm("subHeaderItems.links");

  console.log(myItems);

  return myItems;
});
</script>
```
And the question is why it's happening?
it has no problem with `vue-i18n` nine version, and how should I solve this problem, Thanks

**Comment by kazupon** [comment]
Thank you for your reporting!

If you use `tm`, you must use `rt`.
It is also mentioned in the vue-i18n v9 documentation.
https://vue-i18n.intlify.dev/api/composition.html#tm-key

e.g.
```vue
<div class="container">
  <template v-for="content in tm('contents')">
    <h2>{{ rt(content.title) }}</h2>
    <p v-for="paragraph in content.paragraphs">
     {{ rt(paragraph) }}
    </p>
  </template>
</div>
```

Thanks!

**Comment by mohammadali0120** [comment]
@kazupon Thanks for your efforts and quick answer, one question, I have used vue-18n without `rt` function in my nuxt 3 app, and it works as expected, but why in this package do we need to use `rt` function? it wouldn't be annoying?
I don't know anything about the architect of the code, but there will be any chance to remove the need for the `rt` function in future versions? because I see this is a beta version.

**Comment by kazupon** [comment]
`rt` is vue-i18n APIs, nuxtjs/i18n use it and vue-i18n is stable.
So, we won't remove `rt` from vue-i18n currently.

`rt` is a function introduced in vue-i18n v9.
In earlier versions of vue-i18n, `t` could return resolved strings and arrays.
I have localization experience with applications using vue-i18n in my day job and other projects, and I realized that using `t` makes localization more complicated. So, starting with vue-i18n v9, I separated the function that returns arrays into `tm` and let `rt` transfer the array from that function.

The best practice in i18n is simply for resource messages to return a single string.

**Comment by mohammadali0120** [comment]
@kazupon  Hi again, sorry if I question again, I didn't find any result, I have an array, if I want to get one of its items, but not by object property like your example above, how can I do this: 

here is my code:


```js 
<script setup>
const { tm,rt } = useI18n();

const items = computed(() => {
  const myItems = tm("subHeaderItems.links");

  console.log(rt(myItems[0].text)); // not like this but like below

  console.log(myItems[0]); // here I want to get the first item of the array, the whole of the first object, not by property


  return myItems;
});
```
