### ISSUE TITLE
Missing "./node_modules/vue-i18n-routing/dist/vue-i18n-routing.mjs" export in "@nuxtjs/i18n" package

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/i18n#1683]
### Version
@nuxtjs/i18n: `8.0.0-beta.5`
nuxt: `npm:nuxt3@3.0.1-rc.0-27821553.ab125bd`

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### What is Expected?
Happens when bumping the `@nuxtjs/i18n` from `8.0.0-beta.4` to `8.0.0-beta.5`. Wish I could find the exact line where it's failing, as the error message is quite generic.

### What is actually happening?
![image](https://user-images.githubusercontent.com/48835293/204251397-9f22ad74-598b-43d0-802e-c9c47167e4f8.png)

**Comment by kazupon** [comment]
Could you give us minimum reproduction repo with github or stackbliz please? 🙏

**Comment by wanjee** [comment]
Hi, 

@nuxtjs/i18n: @nuxtjs/i18n-edge@8.0.0-beta.4-27817449.b065900
nuxt: 3.0.0

Not sure if totally related but I have an issue that might be similar.  However my colleagues, with same code base, cannot reproduced it. 

Error message is : 

[vite:load-fallback] Could not load /Users/xxxx/www/vwp_test/frontend/dist/vue-i18n-routing.mjs (imported by node_modules/@nuxtjs/i18n/dist/runtime/plugin.mjs): ENOENT: no such file or directory, open '/Users/xxxx/www/vwp_test/frontend/dist/vue-i18n-routing.mjs'

Hope it helps...

**Comment by Nobi322** [comment]
@wanjee have same issue

**Comment by kazupon** [comment]
I would like to resolve this issue, and would like the following information and debug logs.

- info
  - package manager & version
  - OS
  - node.js version
- log
  - npm using case: `DEBUG=@nuxtjs/i18n:* npm run dev`
  - yarn using case: `DEBUG=@nuxtjs/i18n:* yarn dev`
  - pnpm using case: `DEBUG=@nuxtjs/i18n:* pnpm run dev`

**Comment by wanjee** [comment]
- package manager & version: npm 8.19.2
- OS: OSX 13.0.1
- Node.js version: v16.18.0

Log attached

[i18n_issue_1683_npm_log.txt](https://github.com/nuxt-modules/i18n/files/10115197/i18n_issue_1683_npm_log.txt)

**Comment by Aareksio** [comment]
@kazupon 
Probably related, with a reproduction, started happening with beta.5

https://stackblitz.com/edit/github-hz9kaq-thtg5j
![image](https://user-images.githubusercontent.com/11166786/204742425-1f993c9f-f459-4b65-af36-f4d1345244fd.png)

It **works** on my Windows 10 and Debian, **does not** work on OSX (Intel) and StackBlitz.

**Comment by lukaszflorczak** [comment]
The same problem on:
* pnpm v7.17.1
* Node v18.11.9
* Mac OS 13.0.1 (Intel)

Tested with beta.5 and beta.6

<img width="1996" alt="Zrzut ekranu 2022-11-30 o 07 10 30" src="https://user-images.githubusercontent.com/1818979/204743940-faddb3a9-2292-4b2f-b1c8-5e3b3dc50741.png">

**Comment by wanjee** [comment]
I downloaded the code from @Aareksio's Stackblitz and gave it a try locally... no error for me.
While my own project still shows the error I mentioned yesterday

**Comment by AlexBa** [comment]
I have the same issue on OS X and 8.0.0-beta.6

**Comment by dargmuesli** [comment]
Here is a reproduction with the newest beta on Nuxt 3.0.0: https://stackblitz.com/edit/github-a5wazj-qxndro

**Comment by Bcavez** [comment]
> 

I'm on windows 10, same project/config as @wanjee. Everything works fine.
But when I clone that stackblitz repo (https://stackblitz.com/edit/github-hz9kaq-thtg5j) locally I do get the error.
![image](https://user-images.githubusercontent.com/52085295/205034231-d4db2040-f030-47ee-94b2-1ac641d02473.png)

**Comment by tux2nicolae** [comment]
I have the same issue here

**Comment by dargmuesli** [comment]
Everyone, please add a :+1: to the first post only and do not create "me too" comments. If you have information that helps to resolve the issue, please comment. Thanks!

**Comment by kazupon** [comment]
I've just released edge version `@nuxtjs/i18n-edge@8.0.0-beta.6-27835776.563d636`
please check it!

Thank you for your reproduction info!

**Comment by tux2nicolae** [comment]
I'm still getting the error on edge build `"@nuxtjs/i18n-edge": "^8.0.0-beta.6-27835776.563d636"`

```
✔ Nitro built in 200 ms                                                                                                                           nitro 16:26:23
✘ [ERROR] Could not read from file: /Users/nicolae/Documents/menoo/web/webapp/node_modules/dist/vue-i18n.mjs

    node_modules/@nuxtjs/i18n-edge/node_modules/vue-i18n-routing/node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14:
      10 │ export * from 'vue-i18n'
         ╵               ~~~~~~~~~~


 ERROR  16:26:24 [vite] error while updating dependencies:                                                                                              16:26:24
Error: Build failed with 1 error:
node_modules/@nuxtjs/i18n-edge/node_modules/vue-i18n-routing/node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14: ERROR: Could not read from file: /Users/nicolae/Documents/menoo/web/webapp/node_modules/dist/vue-i18n.mjs
    at failureErrorWithLog (/Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:1574:15)
    at /Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:1032:28
    at runOnEndCallbacks (/Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:1446:61)
    at buildResponseToResult (/Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:1030:7)
    at /Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:1142:14
    at responseCallbacks.<computed> (/Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:679:9)
    at handleIncomingPacket (/Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:734:9)
    at Socket.readFromStdout (/Users/nicolae/Documents/menoo/web/webapp/node_modules/esbuild/lib/main.js:655:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by kazupon** [comment]
Could you give us the below repro info, please?

- package manager & version
- OS
- node.js version
- node_modules structure info
- use simple project or monorepo project?

**Comment by tux2nicolae** [comment]
Sure

------------------

> package manager & version
```
nicolae@192 client % npm --v
8.19.2
```

> OS
```
nicolae@192 ~ % sw_vers
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```

> node.js version
```
nicolae@192 ~ % node -v 
v18.12.1
```

> node_modules structure info

Here's my [package-lock.json](https://github.com/nuxt-modules/i18n/files/10148916/package-lock.json.txt)

> use simple project or monorepo project?

monorepo

**Comment by lukaszflorczak** [comment]
The edge version seems to work. Thank you.

**Comment by kazupon** [comment]
@tux2nicolae 
Thank you!

When you use the edge version, you need npm alias.
example:
```json
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@8.0.0-beta.6-27835776.563d636"
```

**Comment by tux2nicolae** [comment]
@kazupon unfortunately I'm still not able to build even with the alias (it was my fault not using it in the first place).

Maybe it's only something on my end, as @lukaszflorczak confirmed it works properly with the edge version.

But still, I just noticed that the error message is a little bit different from the original post :

```
✘ [ERROR] Could not read from file: /Users/nicolae/Documents/menoo/web/webapp/node_modules/dist/vue-i18n.mjs
```

/node_modules/  **(mising-module-directory)** dist/vue-i18n.mjs

---------------------
edited:

ps. I'm using the module name ``@nuxtjs/i18n`` in ``nuxt.config.ts``

**Comment by kazupon** [comment]
@tux2nicolae 
Thank you for your more feedback!

I've realized that vue-i18n@v9.2.2 is inistalled your repo:

```
    "node_modules/vue-i18n": {
      "version": "9.2.2",
      "resolved": "https://registry.npmjs.org/vue-i18n/-/vue-i18n-9.2.2.tgz",
      "integrity": "sha512-yswpwtj89rTBhegUAv9Mu37LNznyu3NpyLQmozF3i1hYOhwpG8RjcjIFIIfnu+2MDZJGSZPXaKWvnQA71Yv9TQ==",
      "optional": true,
      "peer": true,
      "dependencies": {
        "@intlify/core-base": "9.2.2",
        "@intlify/shared": "9.2.2",
        "@intlify/vue-devtools": "9.2.2",
        "@vue/devtools-api": "^6.2.1"
      },
      "engines": {
        "node": ">= 14"
      },
      "peerDependencies": {
        "vue": "^3.0.0"
      }
    },
```

@nuxtjs/i18n doesn’t need that version. vue-i18n latest version is depended on @nuxtjs/i18n

**Comment by tux2nicolae** [comment]
@kazupon Thank you for your investigation.

Unfortunately I'm not sure I fully understand the problem, my [package.json](https://github.com/nuxt-modules/i18n/files/10178611/package.json.txt) does not contain any direct dependency on `vue-i18n@v9.2.2`

Now I'm just using `"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@8.0.0-beta.6-27839138.4e2aeb4"` (latest version on npm) and the problem still persists.

~~I'm not sure if I should do anything on my side or it's a dependency problem with `"@nuxtjs/i18n"`~~ (see bellow comment), thank you again for your patience investigating this

**Comment by tux2nicolae** [comment]
I think I possibly found the culprit. I'm using vuetify 3 with nuxt 3 which has the following peer dependencies

```
  "peerDependencies": {
    "vite-plugin-vuetify": "^1.0.0-alpha.12",
    "vue": "^3.2.0",
    "vue-i18n": "^9.0.0",
    "webpack-plugin-vuetify": "^2.0.0-alpha.11"
  },
```

and apparently this is where from I have the `vue-i18n@v9.2.2` dependency.

I've also tried to use `vue-i18n@9.3.0-beta.10` as package dependency and this is the error with conflicting dependencies

```
nicolae@192 webapp % npm install                                
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: vuetify@3.0.3
npm ERR! Found: vue-i18n@9.3.0-beta.10
npm ERR! node_modules/vue-i18n
npm ERR!   vue-i18n@"^9.3.0-beta.10" from the root project
npm ERR!   peerOptional vue-i18n@"*" from @intlify/unplugin-vue-i18n@0.8.0
npm ERR!   node_modules/@intlify/unplugin-vue-i18n
npm ERR!     @intlify/unplugin-vue-i18n@"^0.8.0" from @nuxtjs/i18n@8.0.0-beta.6-27839138.4e2aeb4
npm ERR!     node_modules/@nuxtjs/i18n
npm ERR!       dev @nuxtjs/i18n@"npm:@nuxtjs/i18n-edge@8.0.0-beta.6-27839138.4e2aeb4" from the root project
npm ERR!   3 more (@nuxtjs/i18n, vue-i18n-routing, @intlify/vue-i18n-bridge)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional vue-i18n@"^9.0.0" from vuetify@3.0.3
npm ERR! node_modules/vuetify
npm ERR!   vuetify@"^3.0.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue-i18n@9.2.2
npm ERR! node_modules/vue-i18n
npm ERR!   peerOptional vue-i18n@"^9.0.0" from vuetify@3.0.3
npm ERR!   node_modules/vuetify
npm ERR!     vuetify@"^3.0.3" from the root project
```

**Comment by DamianGlowala** [comment]
Could you try overriding the package version?
https://stackoverflow.com/a/70396201

**Comment by tux2nicolae** [comment]
@DamianGlowala Thank you!!!

Indeed, using 

```
  "overrides": {
    "vue-i18n": "^9.3.0-beta.10"
  }
```

I'm able at least to build the project

**Comment by wanjee** [comment]
I can confirm upgrading to latest solved the issue for us.  Thanks !
