### ISSUE TITLE
Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by abu-ab** [nuxt-modules/i18n#1687]
### Version
@nuxtjs/i18n:7.3.0
nuxt: 3.0.0

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

![image](https://user-images.githubusercontent.com/23444044/204488855-e0fbdd5d-9e45-4ca9-a5dd-bdaccb79c2ce.png)
![image](https://user-images.githubusercontent.com/23444044/204488911-5f587564-f260-44b1-971b-7f376b6f6d80.png)

### Steps to reproduce
initialize nuxt3 and install @nuxtjs/i18n

### What is actually happening?
in @nuxtjs/i18n/src/index.js, this is undefined

**Comment by rchl** [comment]
Follow https://v8.i18n.nuxtjs.org/ for Nuxt 3.

**Comment by LeonardoRick** [comment]
I'm facing the same problem now with a minimal setup and this package versions: 
```json
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/i18n": "^8.0.0-beta.12",
    "@types/node": "^18",
    "nuxt": "^3.6.1"
  }
```

This is the repo: https://github.com/LeonardoRick/temp-nuxti18n-bug

I literally just started a nuxt app and add the `i18n` module

I also added the same comment on [this nuxt issue](https://github.com/nuxt/nuxt/issues/15620), I think the problem is happening again.

This is critical because I really can't start the application just by adding the plugin

**Comment by hassankoktail** [comment]
Facing similar problem with @nuxtjs/recaptcha library

```
 ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'options')
   at module.exports (/home/hassan/workspace/koktail/lowkode/node_modules/@nuxtjs/recaptcha/lib/module.js:8:13)
   at installModule (/home/hassan/workspace/koktail/lowkode/node_modules/@nuxt/kit/dist/index.mjs:2407:101)
   at async initNuxt (/home/hassan/workspace/koktail/lowkode/node_modules/nuxt/dist/index.mjs:2928:7)
   at async load (/home/hassan/workspace/koktail/lowkode/node_modules/nuxi/dist/chunks/dev.mjs:204:9)
   at async _applyPromised (/home/hassan/workspace/koktail/lowkode/node_modules/nuxi/dist/chunks/dev.mjs:96:10)
```

**Comment by BobbieGoede** [comment]
@hassankoktail
You should open an issue on the repository associated with that module, locking this issue as it was resolved over a year ago.
