### ISSUE TITLE
Can lazy-load-translations directory accept en-US.js  ?

### ISSUE THREAD

**Issue by artmarydotir** [nuxt-modules/i18n#1690]
Hi, we used to create **.js** file at lang directory for **lazyloading** translation. but in i18n 8 version its not **possible**.
my directory is like:

nuxt-project/
├── lang/
│   ├── en-US.js
│   ├── fa-IR.js
├── nuxt.config.ts

and i18n config file: 
```
{
  locale: "fa",
  strategy: "prefix_and_default",
  locales: [
    {
      code: "en",
      iso: "en-US",
      name: "English",
      file: "en-US.js",
    },
    {
      code: "fa",
      iso: "fa-IR",
      name: "فارسی",
      file: "fa-IR.js",
    },
  ],
  lazy: true,
  langDir: "lang",
  defaultLocale: "fa",
}
```

and one of translation file: `  en-US.js`

```
export default {
  backHome: "Back to Home",
  pageNotFound: "Page Not Found",
  otherError: "An error accured.",
  welcome: "Welcome to my website",
};

```

but its not working. and the warning is:

_@nuxtjs/i18n Could not find en locale in localeMessages_          
_Not found 'backHome' key in 'en' locale messages._

_______
and i checked with .json type and its working correctly. but  with .js No.

**Comment by francescods** [comment]
Hi, the doc says "Currently, json,json5 and yaml are supported only".
https://v8.i18n.nuxtjs.org/guide/lazy-load-translations

**Comment by kazupon** [comment]
As mentioned in the comments, ts or js is not yet supported in the current version.
We are working on this so that it can be supported now.

Thanks!
