### ISSUE TITLE
load a de.yaml massage file with a @ symbol

### ISSUE THREAD

**Issue by Reocin** [nuxt-modules/i18n#1697]
### Version
@nuxtjs/i18n: 
nuxt: 

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ x] Applies to a site deployed to a server with a Node backend

### Reproduction Link

FILE: de.yaml

mailUs:
    title: Schreiben Sie uns
    subtitle: "solution@greengenieur.ch"

### Steps to reproduce

load the above mentioned de.yaml file

### What is Expected?

It should load

### What is actually happening?

I get en arrow because of the @ symbol. It is to mention, that it works without the @ symbol!

![image](https://user-images.githubusercontent.com/35258423/205950082-dae1a71e-3093-4b52-943b-35b9a8f5117d.png)

Can you help me?

**Comment by kazupon** [comment]
`@` is special characters on vue-i18n or Nuxt3 (Vue 3)
You can read the docs:
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

Thanks!
