### ISSUE TITLE
Injection of the massage path into the tm function

### ISSUE THREAD

**Issue by Reocin** [nuxt-modules/i18n#1698]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when i have to do loops over objects and have to insert the path to the massage multiple times. In particular, if you have nested massages. 

### Describe the solution you'd like

My idea is to have a function like $tm that injects the path to all the objects that are called. I solved it with additional plugin function:

``` js
import { get, mapValues, cloneDeep } from "lodash";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.provide("tmr", (pathString) => {
    const i18n = useI18n();

    const injectPath = (initial_obj, keyOffset = "") => {
      const res = mapValues(initial_obj, (value, key) => {
        if (
          typeof value === "object" &&
          !Array.isArray(value) &&
          value !== null
        ) {
          let newKey = keyOffset ? keyOffset + "." + key : key;
          return injectPath(value, newKey);
        } else {
          return value;
        }
      });

      Object.defineProperty(res, "tp", {
        enumerable: false,
        writable: true,
      });

      res.tp = keyOffset;

      return res;
    };

    const res = injectPath(cloneDeep(i18n.tm(pathString)), pathString);
    return res;
  });
});


```

if i call `$tmr('nav.items')` it  ends up in the following result:

``` json
{
  "services": {
    "tp": "nav.items.services",
    "items": {
      "1": {
        "tp": "nav.items.services.items.1"
      },
      "2": {
        "tp": "nav.items.services.items.2"
      },
      "3": {
        "tp": "nav.items.services.items.3"
      },
      "tp": "nav.items.services.items"
    }
  },
  "aboutUs": {
    "tp": "nav.items.aboutUs"
  },
  "news": {
    "tp": "nav.items.news"
  },
  "tp": "nav.items"
}

```

Now i can always call `tp` on the object and get the current path -->

``` html
  <template
    v-for="(value, key, i) in $tmr('nav.items')"
    :key="'a' + i"
  >
    <li v-if="$_.has(value, 'items')" tabindex="0">
      <a>
        {{ $t(value.tp + ".value") }}
        <div class="mdi mdi-chevron-down mdi-24px"></div>
      </a>
      <ul
        class="menu w-full shadow-md rounded-b-lg bg-neutral text-neutral-content"
      >
        <li
          v-for="(value2, key2, ii) in value.items"
          :key="'b' + ii"
          class="hover-bordered"
        >
          <NuxtLink :to="$t(value2.tp + '.link')">{{
            $t(value2.tp + ".value")
          }}</NuxtLink>
        </li>
      </ul>
    </li>
    <li v-else>
      <NuxtLink :to="$t(value.tp + '.value')">{{
        $t(value.tp + ".value")
      }}</NuxtLink>
    </li>
  </template>
```

Without this plugin, the massage path would have spread multiple times.  

### Additional context

It is to mention that the `tp` property is not enumerable, because i defined it like following. Therefore, you can loop normally over the returned objects and the` tp` property is not used.

```js
Object.defineProperty(res, "tp", {
        enumerable: false,
        writable: true,
      });

```

**Comment by kazupon** [comment]
Thank you for feedback.

Your feedback is an issue of vue-i18n.
vue-i18n repository is here
https://github.com/intlify/vue-i18n-next

`@nuxtjs/i18n` is the Nuxt module that integrates vue-i18n and specializes in i18n routing.
https://v8.i18n.nuxtjs.org/

`tm` API is a feature of vue-i18n. I'm also the author of vue-i18n, and currently contributing to the OSS as nuxtjs/i18n developer and maintaner
I appreciate for your feedback, but this repository is nuxtjs/i18n. So I will close it once.
