### ISSUE TITLE
nuxt-i18n server side translation only?

### ISSUE THREAD

**Issue by prodonly** [nuxt-modules/i18n#1701]
Hello folks,

I am working on a project with nuxt-i18n. I am only expecting server side translation, but I found browser also do translation. Looking for help to see if I can do server side translation only?  

The context:
1. We doesn't need language switch on browser side. We purely depends on domain to decide language. fr.xxx.com  us.xxx.com de.xxx.com
2. When I open fr.xxx.com, I surprisedly found the html content changes from French->English->French .
3. I also noticed our bundle size is huge. By nuxt analysis, I found 70% of them are language.json. 

Questions:
1. Can I totally disable browser side translation? 
2. Can I remove language jsons in the client js? 

Thanks!

**Comment by rchl** [comment]
No, that is not a supported and I don't see how it could be given how Nuxt/Vue works.

If the main issue for you is:

> When I open fr.xxx.com, I surprisedly found the html content changes from French->English->French .

then you should focus on fixing that as it's not something that should be happening.

**Comment by prodonly** [comment]
Thanks @rchl   French->English->French problem solved. 

But all language jsons are still loaded when I open a page. They are big... Is there any way to avoid this?

**Comment by rchl** [comment]
"lazy" option makes it so that only the currently used (and potentially fallback) language is loaded.

**Comment by smares** [comment]
Nuxt with nuxt-i18n injects the corresponding strings from the configured locale into the HTML so the page comes with the localization pre-rendered if I am not mistaken. I was hoping there was a way to _really_ lazy load the locale only when needed.

**Comment by rchl** [comment]
> I was hoping there was a way to _really_ lazy load the locale only when needed.

It might be possible to make it work but I'm not sure what are you trying to achieve with that. The locales would still have to be loaded before the page could be made interactive so it would only slow down things without adding any benefit that I can see.

**Comment by prodonly** [comment]
> > I was hoping there was a way to _really_ lazy load the locale only when needed.
> 
> It might be possible to make it work but I'm not sure what are you trying to achieve with that. The locales would still have to be loaded before the page could be made interactive so it would only slow down things without adding any benefit that I can see.

For example, in our case, we don't need users switch language. We just need the server prepare the translated HTML. So loading locales in brower is not needed at all.  There are many cases like us for people developing international apps.

**Comment by prodonly** [comment]
If would be great if you can give us some directions on how to achieve that.

**Comment by rchl** [comment]
It's possible that a custom implementation of the [server directive `t`](https://github.com/nuxt-modules/i18n/blob/696bd1260d731feade80eaa0ad8ff0febe53f3a7/src/index.js#L103-L104) could be made to make it so that server-rendered page would hardcode the translation rather than creating dynamic code.

But I can't think of how things could work when using `$i18n.t` API in script tag.

Also, things would break badly when doing SPA navigation.

I don't think Nuxt/Vue and this module are suitable for your use case.
