### ISSUE TITLE
completion does not work correctly for `t` from `$i18n`

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#1703]
This issue from discord
https://discord.com/channels/473401852243869706/859855705276153896/1049682398612307989

>i recently installed nuxt/i18n the way it is described here: https://v8.i18n.nuxtjs.org/getting-started/setup
Everything works very well, but my IDE keeps complaining, even tho the code works perfectly fine. Is there maybe any typed i should add to avoid?

![image.png](https://volta.s3.fr-par.scw.cloud/image_eeb79b6b55.png)

**Comment by apss-pohl** [comment]
Some more detail:
Within a plugin context "nuxtApp" it is fine:
![image](https://user-images.githubusercontent.com/95089598/206371210-452f1f57-59e0-4471-9a14-1885277e0e0e.png)
this happens basically on a store context with the use of "useNuxtApp()"
