### ISSUE TITLE
Problem when using tm from i18n

### ISSUE THREAD

**Issue by suchorski** [nuxt-modules/i18n#1706]
I have a translation with
`... foo: ['bar', 'baz'], ...`

When using:
```html
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { tm } = useI18n()
const foo = tm('foo')
console.log(foo)
</script>

<template>
  <div>{{ foo }}</div>
</template>
```

I got `[ null, null ]` in template, but in console i got ['bar', 'baz'].

Is that an issue? Am I doing anything wrong? Thanks!

**Comment by kazupon** [comment]
Thank you for your feedback!

Could you give us your minimal reproduction with stackblitz please? 🙏 
https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

**Comment by suchorski** [comment]
> Thank you for your feedback!
> 
> Could you give us your minimal reproduction with stackblitz please? 🙏 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

There is it (updated): https://stackblitz.com/edit/github-nzjyka
* Worked with a.source (Is that correct?) ☝️

**Comment by kazupon** [comment]
Thank you for your reproduction!

Locale messages resolved with `tm` are currently not allowed in vue-i18n for direct use in templates.
This is because the function will be detoxified by the compiler on the vue side, as you can see from the result `[null, null, ...]`.

So vue-i18n provides `rt`.
The use cases are as follows:

```vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n';

const { tm, rt } = useI18n();
</script>

<template>
  <div>
    <p v-for="a in tm('animals')" :key="a">
      {{ rt(a) }}
    </p>
  </div>
</template>
```

Thanks!

**Comment by suchorski** [comment]
> Thank you for your reproduction!
> 
> Locale messages resolved with `tm` are currently not allowed in vue-i18n for direct use in templates. This is because the function will be detoxified by the compiler on the vue side, as you can see from the result `[null, null, ...]`.
> 
> So vue-i18n provides `rt`. The use cases are as follows:
> 
> ```
> <script setup lang="ts">
> import { useI18n } from 'vue-i18n';
> 
> const { tm, rt } = useI18n();
> </script>
> 
> <template>
>   <div>
>     <p v-for="a in tm('animals')" :key="a">
>       {{ rt(a) }}
>     </p>
>   </div>
> </template>
> ```
> 
> Thanks!

Thanks. But what about if animals was an array of objects like `animals: [{ name: 'Bee' }, { name: 'Cat' }, { name: 'Dog' }]`. This approach didn't work for me.

**Comment by Ischafak** [comment]
Hi, first of all thank you for your answer.
I guess that approach dont work me aswell because i will not use something like v-for. I will just pass the array to a v-select component so i need an array. I am searching a solution but i cant find it.

Can you help me please?

**Comment by kazupon** [comment]
You can wrap with javascript.
e.g: wrap with function
```vue
<script setup lang="ts">
const { tm, rt } = useI18n();

const animals = () => tm('animals').map((a) => rt(a));
console.log('animals', animals());
</script>

<template>
  <div>
    <ul v-for="a in $tm('animals')" :key="a">
      <li>{{ rt(a) }}</li>
    </ul>
  </div>
  <form>
    <select>
      <template v-for="a in animals()">
        <option :value="a">{{ a }}</option>
      </template>
    </select>
  </form>
</template>
```

https://stackblitz.com/edit/github-nzjyka-gxc5ge?file=app.vue

**Comment by Ischafak** [comment]
ok that was what i need. Thank you so much it works perfectly.

**Comment by ngekoding** [comment]
Sorry, I try to use this approach but not working with array of objecs.

It is like what @suchorski ask above.

How to make it works?

**Comment by suchorski** [comment]
> Sorry, I try to use this approach but not working with array of objecs.
> 
> It is like what @suchorski ask above.
> 
> How to make it works?

With the newer version I got working only using $t

**Comment by ngekoding** [comment]
> With the newer version I got working only using $t

Which version do you use?

**Comment by suchorski** [comment]
> > With the newer version I got working only using $t
> 
> Which version do you use?

"@nuxtjs/i18n": "8.0.0-rc.5"

**Comment by ngekoding** [comment]
I don't understand, I just follow yours but still doesn't works.

I try to use:

```js
animals: [{ name: 'Bee' }, { name: 'Cat' }, { name: 'Dog' }],
```

and the app.vue

```vue
<script setup lang="ts">
const { tm, rt } = useI18n();

const animals = () => tm('animals').map((a) => rt(a));
console.log('animals', animals());
</script>

<template>
  <div>
    <ul v-for="a in $tm('animals')" :key="a">
      <li>{{ rt(a) }}</li>
    </ul>
  </div>
</template>
```

then get the errors:

![Screen Shot 2023-12-10 at 11 33 35](https://github.com/nuxt-modules/i18n/assets/11625690/5ca235b3-39f1-42f3-aafa-b89124c2eec4)

Can you please check it here? 
https://stackblitz.com/edit/github-nzjyka-ahgyzh?file=app.vue

Thanks in advance

**Comment by ngekoding** [comment]
Solved with this:

```vue
<script setup lang="ts">
const { tm, rt } = useI18n();
</script>

<template>
  <div>
    <ul v-for="(a, key) in tm('animals')" :key="key">
      <li>{{ rt(a.name) }}</li>
    </ul>
  </div>
</template>
```

Thank you

**Comment by erik-Ak** [comment]
> Solved with this:
> 
> <script setup lang="ts">
> const { tm, rt } = useI18n();
> </script>
> 
> <template>
>   <div>
>     <ul v-for="(a, key) in tm('animals')" :key="key">
>       <li>{{ rt(a.name) }}</li>
>     </ul>
>   </div>
> </template>
> Thank you

i will pray for you tonight. thanks for the solution
