### ISSUE TITLE
[8.0.0-beta.7] Cannot resolve @intlify/vue-router-bridge on pnpm monorepo

### ISSUE THREAD

**Issue by cuebit** [nuxt-modules/i18n#1710]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.13.6`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/github-dqc1up?file=packages%2Fapp%2Fnuxt.config.ts)

### Describe the bug

Subsequent `nuxt prepare` commands fail after adding `modules: ['@nuxtjs/i18n']` to nuxt.config within a monorepo.

### Logs

```shell
packages/app postinstall$ nuxt prepare
│ Nuxi 3.0.0
│  ERROR  Cannot resolve @intlify/vue-router-bridge on pnpm! please install it on 'node_modules'
│   at tryResolve (file:///home/projects/github-dqc1up/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.7_vue@3.2.45/node_modules/@nuxtjs/i18n/dist/module.mjs:126:9)
│   at async setupAlias (file:///home/projects/github-dqc1up/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.7_vue@3.2.45/node_modules/@nuxtjs/i18n/dist/module.mjs:248:47)
│   at async setup (file:///home/projects/github-dqc1up/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.7_vue@3.2.45/node_modules/@nuxtjs/i18n/dist/module.mjs:880:5)
│   at async normalizedModule (file:///home/projects/github-dqc1up/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:238:5)
│   at async Module.installModule (file:///home/projects/github-dqc1up/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:487:3)
│   at async initNuxt (file:///home/projects/github-dqc1up/node_modules/.pnpm/nuxt@3.0.0/node_modules/nuxt/dist/index.mjs:1842:7)
│   at async loadNuxt (file:///home/projects/github-dqc1up/node_modules/.pnpm/nuxt@3.0.0/node_modules/nuxt/dist/index.mjs:1874:5)
│   at async loadNuxt (file:///home/projects/github-dqc1up/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:564:19)
│   at async Object.invoke (file:///home/projects/github-dqc1up/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/prepare.mjs:45:18)
│   at async _main (file:///home/projects/github-dqc1up/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/cli.mjs:65:20)
└─ Failed in 1.1s
```

**Comment by memic84** [comment]
Same problem here with turborepo and yarn (1.x)

`Cannot resolve @intlify/vue-router-bridge on yarn! please install it on 'node_modules'`

seems to have started since `^8.0.0-beta.5`

**Comment by kazupon** [comment]
@memic84 
Do you use monorepo in your project?

**Comment by memic84** [comment]
@kazupon yes, it is a monorepo and also uses nuxt config extends.

I have tried installing `@intlify/vue-router-bridge` myself, but that doesn't do the trick.

I see that there has been some refactors on how the @intlify/vue-router-bridge gets resolved in this package, but couldn't figure out what's exactly wrong.

I think the cause might have been this commit: https://github.com/nuxt-modules/i18n/commit/b832f07bd642c3b84e3a451f59a94fce1795b762#diff-a972e02c688aae6e9fadd2b44ca3eb82af76f5c4b539b3c141fe5e9332fabb0fR27

**Comment by kazupon** [comment]
I fixed this issue.
You can try to use edge version `8.0.0-beta.7-27844220.ef240c9`

Thanks!

**Comment by cuebit** [comment]
@kazupon can confirm this is now resolved. Thank you so much for your swift resolution 🙏

**Comment by gyhyfj** [comment]
ERROR  Cannot start nuxt:  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'
