### ISSUE TITLE
[Feature request]:  support `unplugin-vue-i18n` option for nuxt.confg

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#1720]
> A workaround is to to remove the VueI18nPlugin from nuxt.config.js's vite plugin array. But what if I wanted to use custom options for that plugin? :thinking:

We will need to pick up the options you need from the URL below.
https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#-options

_Originally posted by @kazupon in https://github.com/nuxt-modules/i18n/issues/1674#issuecomment-1345560907_

**Comment by AnzhiZhang** [comment]
Please, this is important.
In Nuxt2, I have to manully add `lang="yaml"` in all i18n blocks because I like to use yaml, `defaultSFCLang` is really helpful!

**Comment by kazupon** [comment]
Contribution welcom!
