### ISSUE TITLE
hydration mismatches error in nuxt 3 static generated ssr mode

### ISSUE THREAD

**Issue by 1isten** [nuxt-modules/i18n#1721]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.21.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`
- Build Modules:    `-`

### Reproduction

https://euphonious-crepe-e4239a.netlify.app
Try to select a different locale and **refresh** the page
After page refresh the `.selected` underline style always applied to EN
Got `Hydration completed but contains mismatches.` error message in console and the UI rendering issue
<img width="631" alt="ui" src="https://user-images.githubusercontent.com/11518941/206646012-1272316d-b42f-4d04-bcc9-f485bfd292de.png">
<img width="270" alt="dom" src="https://user-images.githubusercontent.com/11518941/206646028-cc31074c-57e0-40db-ae8e-62d45f253982.png">

### Describe the bug

The bug happens when`detectBrowserLanguage.useCookie` config is `true` and nuxt is in `ssr: true`  SSR mode.

No problem in SPA mode.

### Additional context

Full code for reproduction:
![code](https://user-images.githubusercontent.com/11518941/206645808-6cb4f9eb-aeee-4316-990b-ab5ae4d89662.png)

**Comment by kazupon** [comment]
Thank you for you reporting!

I checked your reproduction minimum app on netlify!
However, We would like to get your that codes, because we would like to debug it!

Could you provide your codes please? 🙏

**Comment by 1isten** [comment]
Hi @kazupon here is the code https://github.com/1isten/nuxt3-i18n-bug

**Comment by kazupon** [comment]
I've just fixed this issue, and published edge version
If you would try to use, you can use `@nuxtjs/i18n-edge@8.0.0-beta.7-27851181.caaea70`

Thanks!

**Comment by 1isten** [comment]
@kazupon Thank you it works
