### ISSUE TITLE
`i18n-t` only works with `useI18n`, eventhough it's unused

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#1731]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.13.6`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7-27847653.226e24b`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-a5wazj-rqd1am?file=app.vue

### Describe the bug

When I use the `i18n-t` component it does not load the translation and only uses its key as fallback **unless** I add some `const x = useI18n()` to the script setup.

As I'm not using anything out of `x` in the component I instead expect `i18n-t` to work right away, without the `const`.
Adding the `use` leads to an "unused variable" (`x`).

See the linked reproduction as an example.

**Comment by kazupon** [comment]
Thank you for your reporting!
This issue is vue-i18n.
please open the same issue on vue-i18n 🙏 

Thanks!

**Comment by dargmuesli** [comment]
Done: https://github.com/intlify/vue-i18n-next/issues/1274
