### ISSUE TITLE
i18n with array data

### ISSUE THREAD

**Issue by Ischafak** [nuxt-modules/i18n#1732]
### Environment

Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

"@nuxtjs/i18n": "^8.0.0-beta.7",

### Reproduction

https://stackblitz.com/edit/github-lsfve7?file=app.vue

### Describe the bug

Hi, i am just trying to use array in i18n json data

i just need an array to give component so i will not use v-for or something else 

test: [
      "the USA",
      "the UK",
      "Estonia",
      "Germany",
      "the Netherlands",
      "Türkiye"
] 
i have this in my en.json 
when i try to console log {{$t('test')}} i see "test" string. I need to access all array data. What can i do can you help me?

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is same #1706
I mentioned about it
https://github.com/nuxt-modules/i18n/issues/1706#issuecomment-1345486351

The vue-i18n locale resources array can only be used in templates with `rt`. This is a limitation.

Thanks!
