### ISSUE TITLE
每次启动nuxt都会出现的问题

### ISSUE THREAD

**Issue by flowers-10** [nuxt-modules/i18n#1741]
[warn] [nuxt] Some plugins are not exposing a function and skipped: [                                                                                                                                                        08:49:08
  {
    locales: [ 'en', 'zh' ],
    defaultLocale: 'en',
    vueI18n: { fallbackLocale: 'en', messages: [Object] }
  }
]

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

However, We need minimul reproduction github repo or stackbliz, because we can reproduce this issue.
Could you give us your reproduction please?

**Comment by kazupon** [comment]
close in-activity
if you have still issue, please you would open as new issue.
Thanks!
