### ISSUE TITLE
Support for extends

### ISSUE THREAD

**Issue by pimboden** [nuxt-modules/i18n#1743]
### Describe the feature

Nuxt 3 has now this amazing "extends* feature where we can split our template project  in parts.

In our case we have a template project that has a "base"- extends that contains all the minimal settings, pgaes , components,etc. of a project, then we have a second extension with sample custom-configurations,pages, forms, etc.

It would be nice if nuxt/i18n would also support this, so we could have loacale json-files in our extends "projects" and it would merge all the  files depending on the nuxt.config.

For example if the project has the folowinfg config:
 
```
export default defineNuxtConfig({
  extends: ['./_extends/base', './_extends/samples'],
  modules: [
    [
    '@nuxtjs/i18n',
  ],
  i18n: {
    debug: false,
    lazy: true,
    langDir: 'data/locales',
    locales: [
      { code: 'de', iso: 'de-CH', file: 'de.json' },
      { code: 'en', iso: 'en-GB', file: 'en.json' },
    ], // used in URL path prefix
    defaultLocale: 'de', // default locale of your project for Nuxt pages and routings,
    strategy: 'prefix_except_default',
    vueI18n: {
      legacy: false,
      locale: 'de',
    },
  },


```
It would go and find all the languague files in the repective directories on all supported "extends" configured

so it would merge

/_extends/base/data/locales/de.json
/_extends/sample/data/locales/de.json  and  
/data/locales/de.json    

into one objext and have so the "complete" language object for the project..

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by ineshbose** [comment]
Also see issue related to layers: https://github.com/nuxt-modules/i18n/issues/1740

**Comment by bgrand-ch** [comment]
+1

**Comment by kazupon** [comment]
nuxt i18n module supported nuxt layers, so close
