### ISSUE TITLE
[NEXT] Pluarization not working for 0

### ISSUE THREAD

**Issue by szulcus** [nuxt-modules/i18n#1746]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `extends`, `app`, `ssr`, `css`, `modules`, `vite`, `runtimeConfig`, `hooks`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.7`, `nuxt-icons@3.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dqfkg5?file=app.vue

### Describe the bug

Pluarization not working for 0

**Comment by kazupon** [comment]
Thank you for your reporting!
Sorry, I could not understand this issue.
I seem that your repo is correctly for me.
Could you give us more explanation please? 🙏

**Comment by szulcus** [comment]
@kazupon I want to get "0 skrzyń" and I get "0 skrzynia" (https://kazupon.github.io/vue-i18n/guide/pluralization.html#accessing-the-number-via-the-pre-defined-argument)
![image](https://user-images.githubusercontent.com/48328739/208490942-12b24c73-3e69-42fd-b65e-c39d2a02d629.png)

**Comment by shymelon** [comment]
It seems like custom pluralization doesn't work, only english are supported. Also, custom pluralizations should be called from $tc method which isn't injected in a context

**Comment by kazupon** [comment]
@szulcus 
I've check you repro codes again, so I realized that your repo isn't correctly custom plural rules on `nuxt.config.ts`
we need to set `pluralRules` inside `vueI18n` options.
See vue-18n v9 docs:
https://vue-i18n.intlify.dev/guide/essentials/pluralization.html#custom-pluralization

**Comment by kazupon** [comment]
My stackbliz is here:
https://stackblitz.com/edit/github-dqfkg5?file=nuxt.config.ts

If you can't get it to work for you, please comment.
I will close.

Thanks!
