### ISSUE TITLE
[NEXT] Trailing slashes not working in `localePath`

### ISSUE THREAD

**Issue by szulcus** [nuxt-modules/i18n#1747]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `extends`, `app`, `ssr`, `css`, `modules`, `vite`, `runtimeConfig`, `hooks`, `router`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.7`, `nuxt-icons@3.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction
In any `.vue` file:
```ts
router.push(localePath({ name: '<route-name>', hash: `#${<uuid>}` }));
```
In `nuxt.config.ts`:
```ts
export default defineNuxtConfig({
	// ...
	router: {
		options: {
			strict: true,
		},
	},
});
```
I guess it worked when I set `router.trailingSlash` to true in Nuxt 2

### Describe the bug

I get this warning in console:
```
[Vue Router warn]: The selector "#<uuid>" is invalid. If you are using an id selector, make sure to escape it. You can find more information about escaping characters in selectors at https://mathiasbynens.be/notes/css-escapes or use CSS.escape (https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape).
```

**Comment by ineshbose** [comment]
Hi, thanks for reporting your issue. Does the issue persist without passing `hash`? `router.push(localePath({ name: '<route-name>' }));` (I understand you may require it, but curious)

**Comment by szulcus** [comment]
@ineshbose Every time without specifying a hash, or if the hash is an empty string, I get the link without the slash at the end. It would be great if this functionality could be added ❤️

**Comment by kazupon** [comment]
Hi!
nuxtjs/i18n v8 beta has already provide `trailingSlash` option.
Could you try to it on `nuxt.config.ts`?

**Comment by szulcus** [comment]
@kazupon I have configs in seperate files, but this option works. Thanks you very much!
```ts
const options: NuxtI18nOptions = {
	trailingSlash: true,
	// ...
};
export default options;
```
