### ISSUE TITLE
Could not read from file: /errori18n/node_modules/dist/vue-i18n.mjs

### ISSUE THREAD

**Issue by artmarydotir** [nuxt-modules/i18n#1754]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `build`, `vite`, `modules`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`, `()`
- Build Modules:    `-`

### Reproduction

link to a repo:

[Reproduction repo](https://github.com/artmarydotir/nuxt-i18n-error)

### Describe the bug

When running: **npm run dev** error accrued.

```
node_modules/@nuxtjs/i18n/node_modules/vue-i18n-routing/node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14:
      10 │ export * from 'vue-i18n'
         ╵               ~~~~~~~~~
 ```
![Screenshot from 2022-12-20 22-25-19](https://user-images.githubusercontent.com/11363931/208744489-3109a4b6-b94e-490e-bda3-6e0ce6b00e6b.png)

**Comment by ineshbose** [comment]
Putting handy link to Stackblitz with the provided repo: https://stackblitz.com/github/artmarydotir/nuxt-i18n-error

The error messages here say:
```
 ERROR  Error while requiring module @nuxtjs/i18n: Error: @intlify/unplugin-vue-i18n requires 'vue-i18n' or 'petite-vue-i18n' to be present in the dependency tree.


 ERROR  Cannot start nuxt:  @intlify/unplugin-vue-i18n requires 'vue-i18n' or 'petite-vue-i18n' to be present in the dependency tree.
                                                                                                                  19:15:16
  at async Module.installModule (file://node_modules/@nuxt/kit/dist/index.mjs:486:41)
  at async initNuxt (file://node_modules/nuxt/dist/index.mjs:1840:7)
  at async load (file://node_modules/nuxi/dist/chunks/dev.mjs:6794:9)
```

**Comment by ineshbose** [comment]
Hi @artmarydotir, thanks for reporting your issue. I was investigating the repository through stackblitz with the link above, and may I ask if you had restricted installing peer dependencies? I deleted `package-lock.json` and reinstalled and it works on stackblitz!

**Comment by artmarydotir** [comment]
I also added  "vue-i18n": "^9.2.2", but still have this error.

**Comment by artmarydotir** [comment]
@ineshbose 
Hi, thank you. yes i did.
i removed .nuxt/ and package-lock.json  and node_modules.  but nothing change. :(

*but if you removed _package-lock.json_ , did you saw the translated message at index.vue page?

**Comment by ineshbose** [comment]
> *but if you removed package-lock.json , did you saw the translated message at index.vue page?

The Nuxt app was working without any errors or warnings, but I did not see the content in `index.vue` since I see that there's no `app.vue` with `<NuxtPage />` component (to make use of `pages/` and `vue-router`).

Edit: I may be wrong, you may not need it at all!

> i removed .nuxt/ and package-lock.json and node_modules. but nothing change. :(

Could I know what steps did you perform exactly to reinstall and run the app again please?

**Comment by artmarydotir** [comment]
> `app.vue`

oh, i see. i removed app.vue by mistake. but still have error.
The steps:
i just clone the repo.
remove package-lock.json
remove node_modules/
npm install
npm run dev

and get the error.

**Comment by artmarydotir** [comment]
I started to remove all packages one by one, and in every step removed package-lock.json,  and run the nuxt dev.
and i figured out when i install "vuetify": "^3.0" , i get this error.
is it possible that there is some conflict or overwritten routing by installing vuetify?

**Comment by kazupon** [comment]
>I also added  "vue-i18n": "^9.2.2", but still have this error.

nuxtjs/i18n will install vue-i18n latest version (currently v9.3.0-beta.10)
so, you wouldn't need to add manually it!

**Comment by artmarydotir** [comment]
> > I also added  "vue-i18n": "^9.2.2", but still have this error.
> 
> nuxtjs/i18n will install vue-i18n latest version (currently v9.3.0-beta.10) so, you wouldn't need to add manually it!


Yes, i removed vue-i18n.
i find when i  installing vuetify after i18n will change some packages version. i checked package-lock git diff.
could it be a problem with this package(vuetify)?

1/
![Mergely - Diff online, merge documents(2)](https://user-images.githubusercontent.com/11363931/208853096-8a3c2018-710e-4f0a-ae9f-90821ee0087e.png)

2/
![Screenshot from 2022-12-21 11-27-48](https://user-images.githubusercontent.com/11363931/208852784-ddc4c810-33a9-48e2-9a3d-5fc03118ef28.png)

3/
![Screenshot from 2022-12-21 11-33-37](https://user-images.githubusercontent.com/11363931/208852834-76eb2536-f050-47aa-82b1-840b36fecf78.png)

**Comment by artmarydotir** [comment]
Im closing this issue, i update node version from 16 to 18. its works now.

**Comment by gaetansenn** [comment]
I have the same issue with the error:

[ERROR] Could not read from file: ../nuxt-loco/playground/node_modules/dist/vue-i18n.mjs

I assume this is due to the architecture of the projet as playground is inside another folder. relative access path ? 
This is working if i do `npx nuxi dev` inside the playground folder.

I need to use node 16 because of my hosting.
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

Here the reproduction link in the playground : https://github.com/gaetansenn/nuxt-loco
