### ISSUE TITLE
module not generating proper router pages

### ISSUE THREAD

**Issue by vis97c** [nuxt-modules/i18n#1755]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-26jptm?file=nuxt.config.ts

### Describe the bug

After setting up the module (beta) on nuxt 3, the choosen strategy should generate multiple view on the router related to each provided locale.

In my particular case I'm using lazyload to provide locales for english and spanish but the app seems to only recognize one of the locales. So the default locale pages will return /404 errors, but the /es/ will actually work. I wasn't able to replicate it on the module playground but the reproduction is very clear over the problem.

Thanks in advance.

### Additional context

No errors are thrown appart from the missing key warnings

**Comment by ineshbose** [comment]
Hi, thanks for reporting your issue.

I see that the problem may be in the usage of `definePageMeta` in `pages/index.vue`. It seems to be the `name` property you are passing that is interferring. Moreover, I think `pageTransition` accepts `boolean` or `TransitionProps` (https://vuejs.org/api/built-in-components.html#transition).

**Comment by vis97c** [comment]
> Hi, thanks for reporting your issue.
> 
> I see that the problem may be in the usage of `definePageMeta` in `pages/index.vue`. It seems to be the `name` property you are passing that is interferring. Moreover, I think `pageTransition` accepts `boolean` or `TransitionProps` (https://vuejs.org/api/built-in-components.html#transition).

The name on definePageMeta was indeed the issue. Is this a bug? If not a comment on the docs would help a lot.

**Comment by ineshbose** [comment]
`name` is in the page special metadata that is used by the router I think. Here you go - https://nuxt.com/docs/guide/directory-structure/pages/#special-metadata
