### ISSUE TITLE
Fallback messages added through `i18n:extend-messages` aren't loaded automatically

### ISSUE THREAD

**Issue by okj579** [nuxt-modules/i18n#1757]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `app`, `components`, `modules`, `postcss`, `routeRules`, `i18n`, `runtimeConfig`, `vite`, `srcDir`, `tailwindcss`, `typescript`, `hooks`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.6.0`, `@nuxtjs/i18n@8.0.0-beta.7`, `@nuxtjs/tailwindcss@6.1.3`, `~/modules/onsite/index.ts`, `~/modules/outfits/index.ts`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/nuxt-i18n-extending-messages-fallback-yu9dmx?file=/nuxt.config.ts

### Describe the bug

When visiting for the first time or refreshing the page, fallbacks for messages that were added with the `i18n:extend-messages` hook are not shown.

After navigating to the fallback language and back (with client-side navigation), all fallbacks work correctly.

**Comment by hennihaus** [comment]
@okj579 Did you find a solution? I still have this issue. @kazupon Do I need to add `nuxtOptions: Required<NuxtI18nOptions>` as a parameter? The hook is unfortunately not triggered. The module is registered in nuxt.config.ts and other hooks are executed. Maybe the documentation must be updated after fixing this issue.

**Comment by okj579** [comment]
@hennihaus The new version (beta.9) resolves this issue for me, see the updated sandbox here: https://codesandbox.io/p/sandbox/nuxt-i18n-extending-messages-fallback-forked-69r5m8

What I haven't gotten to work is adding the hook after the module has initialized. If I want to add the hook in a module, that module needs to come before `@nuxtjs/i18n` in the `modules`-config.

**Comment by hennihaus** [comment]
Thanks for the reply and help!
