### ISSUE TITLE
Is possible to get data from cms and then import it in nuxt i18n

### ISSUE THREAD

**Issue by plcdnl** [nuxt-modules/i18n#1761]
### Describe the feature

It would be very useful if I could make a graphql call after the module has already been initialized to add the inserted labels inside the cms

### Additional information

- [x] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by ineshbose** [comment]
Hi, thank you for opening an issue. Could I ask what version of Nuxt and `@nuxtjs/i18n` are you looking into?

**Comment by plcdnl** [comment]
I'm using nuxt 3, so i'm trying to do this with v8 beta

**Comment by ineshbose** [comment]
Related GitHub discussion: https://github.com/nuxt-modules/i18n/discussions/1749

**Comment by plcdnl** [comment]
Thank you. So unfortunately is not possible to use it with nuxt3 at the moment 😢
