### ISSUE TITLE
Head meta tags are wrong (x-default and hreflang)

### ISSUE THREAD

**Issue by notflip** [nuxt-modules/i18n#1769]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `css`, `modules`, `i18n`, `image`, `postcss`, `swiper`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `nuxt-swiper@0.1.6`
- Build Modules:    `-`
------------------------------
```

### Reproduction

```
  i18n: {
    baseUrl: process.env.BASE_URL,
    strategy: 'prefix',
    defaultLocale: 'nl',
    skipSettingLocaleOnNavigate: true,
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
    },
    locales: [
      {
        name: 'Nederlands',
        code: 'nl',
        iso: 'nl',
        file: 'nl.json',
      },
      {
        name: 'English',
        code: 'en',
        iso: 'en',
        file: 'en.json',
      },
    ],
    langDir: 'lang'
  },
```

### Describe the bug

- The tags should have the full qualified url name, including http/https
- the x-default tag should not have a language added to it (so mysite.com/ instead of mysite.com/en) see https://developers.google.com/search/docs/specialty/international/localized-versions
- shouldn't the canonical be the root of the site as well? I'm not sure.

```
<link id="i18n-alt-nl" rel="alternate" href="https://site.be/nl" hreflang="nl">
<link id="i18n-alt-en" rel="alternate" href="https://site.be/en" hreflang="en">
<link id="i18n-xd" rel="alternate" href="https://site.be/nl" hreflang="x-default">
<link id="i18n-can" rel="canonical" href="https://site.be/nl">
```

**Comment by kazupon** [comment]
Thank you for your feedback!

Hmm, `prefix` strategy

I think the case of the `prefix` strategy is that the generation of the head meta by `localeHead` or `useLoaleHead` is the result. This is a specification from v7.
If you want to comply with the search engine guide, unfortunately you will need to use another routing strategy, such as the `prefix_and_default` strategy.

**Comment by notflip** [comment]
Hi @kazupon I'll give the `prefix_and_default` strategy a shot, thanks.
