### ISSUE TITLE
`nuxtApp.$i18n.locales` has type `LocaleObject[]` but is `ComputedRef<LocaleObject[]>`

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/i18n#1777]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `i18n`, `piniaPersistedstate`, `googleFonts`, `colorMode`, `postcss`, `build`, `vite`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`, `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/google-fonts@3.0.0-1`, `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

```js
// nuxt.config.js

import messages from './src/i18n';

export default defineNuxtConfig({
    i18n: {
        strategy: 'prefix_except_default',
        defaultLocale: 'fr',
        locales: [
            {
                code: 'fr',
                name: 'Français',
                iso: 'fr-CA',
                momentLocale: 'fr-ca',
            },
            {
                code: 'en',
                name: 'English',
                iso: 'en-CA',
                momentLocale: 'en',
            },
        ],
        vueI18n: {
            legacy: false,
            messages,
        },
    },
});
```

```js
// plugin/moment.js

import moment from 'moment';
import 'moment/dist/locale/fr-ca';
import momentDurationFormatSetup from 'moment-duration-format';

export default defineNuxtPlugin((nuxtApp) => {
    const locale = nuxtApp.$i18n.locale.value;
    const momentLocale = nuxtApp.$i18n.locales.value.find((l) => l.code === locale).momentLocale;
    momentDurationFormatSetup(moment);
    moment.locale(momentLocale);

    nuxtApp.$i18n.onBeforeLanguageSwitch = (oldLocale, newLocale, isInitialSetup, nuxtApp) => {
        const momentLocale = nuxtApp.$i18n.locales.value.find((l) => l.code === newLocale).momentLocale;

        moment.locale(momentLocale);
    };

    return {
        provide: {
            moment,
        },
    };
});
```

### Describe the bug

> Parameter 'oldLocale' implicitly has an 'any' type.
> Parameter 'newLocale' implicitly has an 'any' type.
> Parameter 'isInitialSetup' implicitly has an 'any' type.
> Parameter 'nuxtApp' implicitly has an 'any' type.

> Property 'code' does not exist on type 'string | LocaleObject'.

> Parameter 'l' implicitly has an 'any' type.

### Additional context

I see in the source code that the types for `onBeforeLanguageSwitch`, but they don't seem to be infered correctly in a Nuxt 3 plugin.

I tried adding the types manually on the parmas like so, but nuxtApp type is not found.
```js
nuxtApp.$i18n.onBeforeLanguageSwitch = (oldLocale: string, newLocale: string, isInitialSetup: boolean, nuxtApp: nuxtApp) => {
    const isoLocale = nuxtApp.$i18n.locales.value.find((l) => l.code === newLocale).momentLocale;

    moment.locale(isoLocale);
};
```

I tried importing it manually, but it also doesn't work.
```
import type { NuxtApp } from '#imports'
```
I get this message:
> Module '"#imports"' has no exported member 'NuxtApp'.

**Comment by mrleblanc101** [comment]
I partially solved the problem, the type `NuxtApp` is on `#app`, not `#imports`.
I think the type should be infered as we dont need to type the params for `export default defineNuxtPlugin((nuxtApp) => {`

**Comment by mrleblanc101** [comment]
Now I have 2 new errors:

For this code:
```
nuxtApp.$i18n.onBeforeLanguageSwitch = (oldLocale: string, newLocale: string, isInitialSetup: boolean, nuxtApp: NuxtApp) => {
    const momentLocale = nuxtApp.$i18n.locales.value.find((l: LocaleObject) => l.code === newLocale).momentLocale;

    moment.locale(momentLocale);
};
 ```
 I have this error:
> Property 'value' does not exist on type 'string[] | LocaleObject[]'. Did you mean 'values'?
  Property 'value' does not exist on type 'string[]'.

But `nuxtApp.$i18n.locales` does not return a `LocaleObject[]` but a `Ref`. :thinking:
  
  
  For this code:
  ```
  const nextLocale = computed(() => {
    const index = locales.value.findIndex((l: LocaleObject) => l.code === locale.value);
    const nextIndex = index !== locales.value.length - 1 ? index + 1 : 0;

    return (locales.value.at(nextIndex) as LocaleObject).code;
});
```
I have:
  > Argument of type '(l: LocaleObject) => boolean' is not assignable to parameter of type '((value: string, index: number, obj: string[]) => unknown) & ((value: LocaleObject, index: number, obj: LocaleObject[]) => unknown)'.
  Type '(l: LocaleObject) => boolean' is not assignable to type '(value: string, index: number, obj: string[]) => unknown'.

**Comment by mrleblanc101** [comment]
Ok, I also fixed the second issue in my previous message.
I had to define the type correctly:
` const index = (locales.value as LocaleObject[]).findIndex((l) => l.code === locale.value);`
instead of:
`const index = locales.value.findIndex((l: LocaleObject) => l.code === locale.value);`.

So there is only the first error of my previous message left, which seems like a bug. 
The other were me just being a TypeScript noob I guess.

**Comment by mrleblanc101** [comment]
My last idea was to change the type to `ComputedRef<LocaleObject[]>` like so `const locales = (nuxtApp.$i18n.locales as ComputedRef<LocaleObject[]>).value
`, but I get 
>Conversion of type 'string[] | LocaleObject[]' to type 'ComputedRef<LocaleObject[]>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'LocaleObject[]' is missing the following properties from type 'ComputedRef<LocaleObject[]>': value, [ComputedRefSymbol], effect, [RefSymbol]

  So I will just use `as any` for now as everything is working.

```
    nuxtApp.$i18n.onBeforeLanguageSwitch = (
        oldLocale: string,
        newLocale: string,
        isInitialSetup: boolean,
        nuxtApp: NuxtApp,
    ) => {
        const locales = (nuxtApp.$i18n.locales as ComputedRef<LocaleObject[]>).value
        const momentLocale = locales.find((l: LocaleObject) => l.code === newLocale)?.momentLocale;

        moment.locale(momentLocale);
    };
    ```

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue on this repository. Sharing your updates as you work through this issue is really appreciated, and type definitions will be looked into ASAP!

**Comment by mrleblanc101** [comment]
No problem, I can also open a new clean issue without all the noise if necessary.
It seems like a very minor problem., but for someone new to Vue3/Nuxt3/TypeScript, I was at a lost haha.

**Comment by mrleblanc101** [comment]
This seem fixed in `@nuxtjs/i18n-edge`, but not 100% sure.

If I do `const locales = nuxtApp.$i18n.locales.value;`, it thinks `locales` is `string[] | LocaleObject[]`.
So I did `const locales = (nuxtApp.$i18n.locales as ComputedRef).value;` and now it works in Edge.
It wasn't working in `"@nuxtjs/i18n": "^8.0.0-beta.7"` as it says the 2 types do not overlaps.

Now I see the new type is `(string[] | LocaleObject[]) & ComputedRef<string[] | LocaleObject[]>` instead of just `string[] | LocaleObject[]`
