### ISSUE TITLE
i18n module is breaking Nuxt plugin auto typing from useNuxtApp

### ISSUE THREAD

**Issue by jbreuil** [nuxt-modules/i18n#1779]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.1`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jbreuil/i18n-typing-reproduction

pnpm install

In app.vue, $hello type is inferred correctly.
Uncomment i18n module in nuxt.config.ts, pnpm run dev
 $hello is now any type

### Describe the bug

When enabling i18n module for nuxt it breaks the [auto typing of plugins ](https://nuxt.com/docs/guide/directory-structure/plugins#typing-plugins)

### Additional context

Might be related to #1778

**Comment by ineshbose** [comment]
Stackblitz link for the provided repo: https://stackblitz.com/github/jbreuil/i18n-typing-reproduction

Related issue: #1759 
Could you switch to edge (until beta 8 is released) and confirm if the issue still persists please?

**Comment by jbreuil** [comment]
I haven't found the issue #1759 when searching but it's clearly the same issue so I close as duplicate.

Will be fixed in v8
