### ISSUE TITLE
Incorrect type of `locale` when using locally scoped `useI18n` composable

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/i18n#1783]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.1-rc.0-27848798.0cb9a4c`
- Nitro Version:    `2.0.0-27847631.8186a02`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`, `css`, `app`, `i18n`, `googleFonts`, `fontMetrics`, `headlessui`, `image`, `build`, `typescript`, `runtimeConfig`, `security`, `nitro`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/i18n@8.0.0-beta.7-27867903.cc6cc78`, `@nuxtjs/google-fonts@3.0.0-1`, `nuxt-headlessui@1.0.4`, `@vueuse/nuxt@9.9.0`, `@formkit/nuxt@1.0.0-beta.12`, `nuxt-icon@0.1.8`, `@nuxtjs/fontaine@0.2.4`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`
- Build Modules:    `-`
------------------------------

### Reproduction

n/a

### Describe the bug

![image](https://user-images.githubusercontent.com/48835293/210563813-3d2a355c-84af-4249-af53-6b78b23e314c.png)

vs

![image](https://user-images.githubusercontent.com/48835293/210563911-3c51a26a-87ee-4f4f-95ee-5cfd1e0a1347.png)

**Comment by kazupon** [comment]
I seem this issue is vue-i18n, not nuxtjs/i18n
If you have getting issue with vue-i18n alone, please open an issue on vue-i18n-next! 🙏

**Comment by DamianGlowala** [comment]
Transferred to https://github.com/intlify/vue-i18n-next/issues/1304. Thanks!
