### ISSUE TITLE
`{{ $t() }}` get expanded to `{{ $nextTick() }}` with Volar

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/i18n#1790]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `ssr`, `modules`, `i18n`, `piniaPersistedstate`, `googleFonts`, `colorMode`, `postcss`, `build`, `vite`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7-27867903.cc6cc78`, `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/google-fonts@3.0.0-1`, `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@vueuse/nuxt@9.10.0`
- Build Modules:    `-`
------------------------------

### Reproduction

![2023-01-09 13 15 25](https://user-images.githubusercontent.com/17392251/211378676-ec566d8d-a125-4bd6-ac63-b667b1486bee.gif)

Nuxt 3:
https://user-images.githubusercontent.com/17392251/211381894-9c94b98c-2045-40bd-85e1-ad31666f523f.mov

Nuxt 2:
https://user-images.githubusercontent.com/17392251/211381922-2ee3f353-bc4c-40ce-a908-85b8997721c7.mov

### Describe the bug

Not sure if I should open this in the Volar repository, so let me know.
But `{{ $t() }}` get expanded to `{{ $nextTick() }}` with Volar.
This is quite annoying.
Can't the extension provide autocomplete hints to Volar ?

**Comment by rchl** [comment]
It expands to whatever completion item is selected.

Module can not influence what your editor prefers to match. Is a `$t` entry even present in your completions?

**Comment by rchl** [comment]
BTW. The gifs are so annoying since it's impossible to pause and look at specific frames...

**Comment by mrleblanc101** [comment]
@rchl Not in Nuxt 3 with `nuxtjs/i18n@next`.
But it's there and work properly in Vue 2 (also with Volar).

Nuxt 2 project:
<img width="602" alt="Capture d’écran, le 2023-01-09 à 13 23 34" src="https://user-images.githubusercontent.com/17392251/211380275-7e0a5b73-b03e-4d09-946b-1f3992f6640d.png">

Nuxt 3 project: 
<img width="580" alt="Capture d’écran, le 2023-01-09 à 13 25 36" src="https://user-images.githubusercontent.com/17392251/211380494-8fe60405-3090-4826-8c97-ac05c9e66463.png">

Sorry for the GIF, I keep forgetting that Github now support video. 
It didn't for the longest time which is why I always attached GIFs.

**Comment by mrleblanc101** [comment]
Also, not quite sure why it expand.
Shouldn't  VS Code/Emmet only expand on `Enter` and `Tabs` key ?
It expanded when I typed `(` even if it's not a exact match which does not happen in my Nuxt 2 project.

**Comment by mrleblanc101** [comment]
@rchl I added video to the original message if you need.

**Comment by rchl** [comment]
If `$t` is not there in the list then I suppose this is the root issue.

As for auto-expanding, that would be the behavior of Volar and/or Editor combined. I suppose that it determined that no other completion matched those characters and decided to pick the only possible option. If the `$t` would be there then it wouldn't do it.

**Comment by mrleblanc101** [comment]
@rchl Then is the missing $t suggestion a Volar or a nuxtjs/i18n issue ?

**Comment by rchl** [comment]
It's a nuxtjs/i18n issue most likely. Could also be a Volar configuration issue.

**Comment by kazupon** [comment]
if you could not `$t` completion, that is occured by vue-i18n-next bug.
I already fixed that issue. you can read the below link:
https://github.com/nuxt-modules/i18n/issues/1778#issuecomment-1376828729

**Comment by mrleblanc101** [comment]
I confirm this is fixed, I had to restart VS Code after upgrading the package.
