### ISSUE TITLE
Custom routes don't work as expected

### ISSUE THREAD

**Issue by mikhgaus** [nuxt-modules/i18n#1802]
### Environment

Nuxi 3.0.0

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `modules`, `i18n`, `build`, `css`, `vite`
- Runtime Modules:  `()`, `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.7`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-w7smfy?file=nuxt.config.ts

### Describe the bug

`strategy: 'prefix_except_default'`

Expected `http://localhost:3000/karriere/standorte` to work.
Actually works: `http://localhost:3000/arriere/standorte`

Expected `http://localhost:3000/en/career/locations` to work.
Actually works: `http://localhost:3000/en/areer/locations`

**Comment by StefanoTesla** [comment]
You are using the wrong i18n version:

```
  "devDependencies": {
    "@nuxtjs/i18n": "^8.0.0-beta.7",
    "nuxt": "^3.0.0"
  }
```

use this: `"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"`

You olso forget to add `pages:true,` in order to use nuxt page processing in your defineNuxtConfig

**Comment by mikhgaus** [comment]
@StefanoTesla `pages: true` is not necessary, according to https://nuxt.com/docs/api/configuration/nuxt-config#pages-1

I did both of your advice nonetheless, but it didn't help.

**Comment by StefanoTesla** [comment]
Yes, I don't knwo why two days ago it didn't worked for me without pages.

Anyway!

I found the problem and it's how you configure the routes (I had a similar headhake, documentation example are non very exhaustive


First, update dev dependency, then `npm install`


After this change your routes configuration:

All routes shuold strart with `/`  ex: `lang: '/your-path'`

Index page path **is wrong**:
```
      'karriere/standorte/index': {
        de: 'karriere/standorte',
        en: 'career/locations',
      },
```

The path don't start with `/` **this is correct**:

```
      'karriere/standorte/index': {
        de: '/karriere/standorte',
        en: '/career/locations',
      },
```
Dynamic slug is **wrong** in the second part:
```
      'karriere/standorte/detail/[location-name]': {
        de: 'karriere/standorte/detail/[location-name]',
        en: 'career/locations/detail/[location-name]',
      },
```
**Correct** form is:

```
      'karriere/standorte/detail/[location-name]': {
        de: '/karriere/standorte/detail/[location-name]',
        en: '/career/locations/detail/[location-name]',
      },
```

or:

```
      'karriere/standorte/detail/[location-name]': {
        de: '/karriere/standorte/detail/:location-name',
        en: '/career/locations/detail/:location-name',
      },
```

**Comment by mikhgaus** [comment]
'/' does work, thank you very much. But it also does work with dynamic parameters being in [ ], as it's stated in documentation.

https://v8.i18n.nuxtjs.org/guide/custom-paths
![image](https://user-images.githubusercontent.com/62499825/213701273-4b088537-3071-4d1d-af90-1cb531ca2046.png)

**Comment by mikhgaus** [comment]
I overlooked the slash at the beginning, sry for the inconvenience.
