### ISSUE TITLE
ERROR: Module not found: Error: Can't resolve 'vue-i18n' in "...path"

### ISSUE THREAD

**Issue by tommasogangemi** [nuxt-modules/i18n#1806]
### Environment

Nuxt project info:              
                                                                                                                                                                                    
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `ssr`, `builder`, `webpack`, `css`, `modules`, `app`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`
- Build Modules:    `-`
------------------------------

### Reproduction

I managed to reliably replicate the bug by:

- creating a new nuxt 3 project with `npx nuxi init`
- copying and pasting my `nuxt.config` and `package.json`
- running `npm i`
- running `npm run dev`

### Describe the bug

When trying to run the local server errors pop up in the terminal. 

By scanning the package.json "vue-i18n" seems to be correctly installed.

I tried removing node_modules, cleaning the npm cache, and re-installing the dependencies and it didn't work.

### Additional context

This is the error message that appears:

![image](https://user-images.githubusercontent.com/72601419/213756101-f2098e67-e37e-4b03-ac44-0a95c9ed278a.png)

Below my nuxt config:
```
export default defineNuxtConfig({
  ssr: false,
  builder: 'webpack',
  css: ['~/assets/styles/main.scss'],
  modules: ['@nuxtjs/i18n'],
  i18n: {
    strategy: 'prefix_except_default',
    locales: [
      {
        code: 'en',
        file: 'en-US.json',
      },
      {
        code: 'it',
        file: 'it-IT.json',
      },
    ],
    defaultLocale: 'en',
    langDir: 'lang',
  },
})
```

And here my package.json:
```
{
    "private": true,
    "scripts": {
        "build": "nuxt build",
        "dev": "nuxt dev",
        "generate": "nuxt generate",
        "preview": "nuxt preview",
        "postinstall": "nuxt prepare"
    },
    "devDependencies": {
        "@nuxt/webpack-builder": "^3.0.0",
        "@nuxtjs/i18n": "^8.0.0-beta.7",
        "nuxt": "3.0.0",
        "sass": "^1.57.1",
        "sass-loader": "^13.2.0"
    },
    "dependencies": {
        "vuetify": "^3.1.1",
        "webpack-plugin-vuetify": "^2.0.0"
    }
}
```

**Comment by kazupon** [comment]
That's duplicate #1568
Could you try to use edge version?

**Comment by kazupon** [comment]
related #1754 #1794

**Comment by tommasogangemi** [comment]
@kazupon Thanks, I'll try the edge version, should that work fine on a nuxt 3 project?

Is it possible to have a rough estimate on which version of the beta (or final release) it will be fixed?

[Edit]: edge version works like a charm!

**Comment by skoenfaelt** [comment]
For PNPM Users, had the same issue, solved it via the .npmrc file

![image](https://user-images.githubusercontent.com/53934248/232249619-cb7b9596-ef0a-4edd-8cdb-8353f12c05dd.png)

[Docs](https://nuxt.com/docs/getting-started/installation)
