### ISSUE TITLE
Wrong locale at SSG's payload extraction time

### ISSUE THREAD

**Issue by provokcx** [nuxt-modules/i18n#1807]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.2.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `generateSvgsViewboxes`, `i18n`, `svgo`, `image`, `robots`, `runtimeConfig`, `vite`, `nitro`, `css`, `app`
- Runtime Modules:  `~/modules/generate-svgs-viewboxes/index.ts`, `~/modules/cms-redirections/index.ts`, `@nuxtjs/i18n@8.0.0-beta.7`, `nuxt-svgo@1.1.0`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

### Reproduction

- At least two locales configured
- Create a dynamic page
- Fetch data from nitro server
- Generate the site

[Reproduction link](https://stackblitz.com/edit/github-dqwz7l-tvcn4f?file=pages/[basic-page].vue)

### Describe the bug

When generating the _payload.js files, useI18n().locale returns the wrong locale.
For me it switches en to fr and vice versa.

To be clear, when generating it looks like this:

/mentions-legales => fr
/en/legal-notice => en
/mentions-legales/_payload.js => en
/en/legal-notice/_payload.js => fr

**Comment by kazupon** [comment]
Thanks for your feedback.
However, just we need minimal repo.
Could you give it in stackbliz or github repo, please? 🙏 
Providing a minimal repo is the guideline for bug reports.

**Comment by provokcx** [comment]
@kazupon 
[Here's the link](https://stackblitz.com/edit/github-dqwz7l-tvcn4f?file=pages/[basic-page].vue)

I found where the bug really comes from. It is related to the lang switcher.
If you comment the NuxtLink in the Header.vue SSG works as expected.


It is because Header.vue has no idea of the pageData during SSR so without setting the route params early on Nuxt will generate a link to an inexistent page.
So in fine the bug is really related to a nice way to set route params that works well with CMS and data fetching.

**Comment by kazupon** [comment]
Thank you for your reproduction!
I'll check see your repo !

**Comment by provokcx** [comment]
@kazupon I found a way to do it.

I used a route middleware that fetches the urls data, restructures them and then passes the restructured object to `routeTo.meta.nuxtI18n `.

By doing this. I am able to generate all the dynamic pages with SSR 👌

All we need is a clean way to add the custom paths localized urls without using a compiler macro like `defineI18nRoute` and without using my hack `routeTo.meta.nuxtI18n = localizedRouteUrls;`

**Comment by madc** [comment]
Using this route middleware means, you are making the API calls twice, right? Once in th emiddleware and once in the setup?

**Comment by provokcx** [comment]
Nope @madc.

To avoid making calls on route change all the time, I made a custom local module that fetches all my dynamic URLs from the CMS before Nuxt even starts.

Then in the route middleware, I restructure the data to get the route params I'm interested in.

And finally, I use the hack just above with `routeTo.meta.nuxtI18n = localizedRouteUrls;`

**Comment by kaname-png** [comment]
Any way to solve this?
1. No cookie is set by default when the user visits the page for the first time.
2. Even if the page is reloaded it does not save any cookies.
3. The cookie is only saved if the user switches to any other language and then switches back to the preferred language.
4. It happens when the page is pre-rendered (SSG), when the page is SSR the problem does not occur but the default cookie is still not saved.

```ts
	i18n: {
		baseUrl: 'https://next.naeko.moe',
		defaultLocale: 'en',
		strategy: 'prefix_except_default',
		langDir: 'locales',
		lazy: true,
		locales: [
			{
				name: 'English',
				code: 'en',
				iso: 'en-US',
				file: 'en.json',
			},
			{
				name: 'Español',
				code: 'es',
				file: 'es.json',
				iso: 'es-ES',
			},
		],
		detectBrowserLanguage: {
			alwaysRedirect: true,
			redirectOn: 'all',
			cookieKey: 'neko-lang',
		},
	},
```

https://user-images.githubusercontent.com/56084970/214631082-c22f7dd7-5cdb-404d-bbf2-2f9b09f620e7.mp4

**Comment by madc** [comment]
Thanks for explaining.

I have issues with `switchLocalePath` using your `routeTo.meta.nuxtI18n = localizedRouteUrls;` hack.
It does ignore the translated slugs. Does that work for you?

**Comment by provokcx** [comment]
For it to work, your project needs to run `routeTo.meta.nuxtI18n = localizedRouteUrls;` before instantiating the component using `switchLocalePath`. Using a router middleware does the trick for me.


Don't forget to force `switchLocalePath` to update on language changes.

Here's the code for my lang switcher:
```ts
<script lang="ts" setup>
  import type { ComputedRef } from "vue";
  import type { LocaleObject } from "vue-i18n-routing";

  const { locales } = useI18n();
  const fullLocales = locales as ComputedRef<LocaleObject[]>;
  const switchLocalePath = useSwitchLocalePath();
  const availableLocales = computed(() => fullLocales.value.map((locale) => locale));
</script>
```

Then use it like this in your template:
```html
<NuxtLink :to="switchLocalePath(locale.code)">{{ locale.name }}</NuxtLink>
```

**Comment by madc** [comment]
Thanks for the detailed reply! I have to look into this and don't want to take this more off-topic!
You approach is definitely a big help!

**Comment by luca-smartpricing** [comment]
> Nope @madc.
> 
> To avoid making calls on route change all the time, I made a custom local module that fetches all my dynamic URLs from the CMS before Nuxt even starts.
> 
> Then in the route middleware, I restructure the data to get the route params I'm interested in.
> 
> And finally, I use the hack just above with `routeTo.meta.nuxtI18n = localizedRouteUrls;`

Hi! I'm not confident with Nuxt Modules. Where did you store all the fetched URLs? Could using `runtimeConfig` be a good idea?

**Comment by kazupon** [comment]
close in-activity.
if you have still an issue, please open as new issue.
thanks!
