### ISSUE TITLE
Hydration text mismatch with SSR

### ISSUE THREAD

**Issue by dsvgl** [nuxt-modules/i18n#1812]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.25.1`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.8-27906685.5bd81af`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gfwhki?file=nuxt.config.ts

### Describe the bug

I previously was on this edge version where it worked fine: `8.0.0-beta.7-27893843.b72135e`.

After updating to latest beta.8 or even latest edge, I get the following warning in browser console:

```
[Vue warn]: Hydration text mismatch:
- Client: " => homepage"
- Server: " => Startseite" 
  at <App key=1 > 
  at <NuxtRoot>
```

In the app.vue I display a locale variable. When refreshing the page, you can see that it briefly displays the name of the key and then changes to display the actual (correct) value.

In server console it logs `[intlify] Not found 'homepage' key in 'de' locale messages.`

### Additional context

This doesn't happen with `ssr: false`.

**Comment by StefanoTesla** [comment]
same problem

**Comment by StefanoTesla** [comment]
Related to #1804 now in SSG html there's language file string name

**Comment by kazupon** [comment]
I've just fixed this issue.
You can try to use edge version

Thanks!

**Comment by sawa-ko** [comment]
Same problem here `"@nuxtjs/i18n": "8.0.0-beta.8"`

![image](https://user-images.githubusercontent.com/56084970/214196873-3c4aa234-1fb5-493a-a7f2-03a589f21654.png)

```ts
	i18n: {
		baseUrl: 'https://next.naeko.moe',
		strategy: 'prefix_except_default',
		lazy: true,
		langDir: 'locales/',
		defaultLocale: 'es',
		detectBrowserLanguage: {
			alwaysRedirect: true,
			fallbackLocale: 'es',
		},
		locales: [
			{
				code: 'es',
				name: 'Español',
				file: 'es.json',
			},
		],
		vueI18n: {
			locale: 'es',
			legacy: false,
		},
	},
```

![image](https://user-images.githubusercontent.com/56084970/214196936-db27c5df-e9aa-40d5-997e-22ee191b84d5.png)

![image](https://user-images.githubusercontent.com/56084970/214196962-3160822d-8d7a-4c10-af12-90b62291829e.png)

**Comment by sawa-ko** [comment]
@kazupon any idea?
The page is SSG.

**Comment by dsvgl** [comment]
@kaname-png try edge version. There, it works for me.

**Comment by StefanoTesla** [comment]
> Same problem here `"@nuxtjs/i18n": "8.0.0-beta.8"`
> 
> ![image](https://user-images.githubusercontent.com/56084970/214196873-3c4aa234-1fb5-493a-a7f2-03a589f21654.png)
> 
> ```ts
> 	i18n: {
> 		baseUrl: 'https://next.naeko.moe',
> 		strategy: 'prefix_except_default',
> 		lazy: true,
> 		langDir: 'locales/',
> 		defaultLocale: 'es',
> 		detectBrowserLanguage: {
> 			alwaysRedirect: true,
> 			fallbackLocale: 'es',
> 		},
> 		locales: [
> 			{
> 				code: 'es',
> 				name: 'Español',
> 				file: 'es.json',
> 			},
> 		],
> 		vueI18n: {
> 			locale: 'es',
> 			legacy: false,
> 		},
> 	},
> ```
> 
> ![image](https://user-images.githubusercontent.com/56084970/214196936-db27c5df-e9aa-40d5-997e-22ee191b84d5.png)
> 
> ![image](https://user-images.githubusercontent.com/56084970/214196962-3160822d-8d7a-4c10-af12-90b62291829e.png)

Remove the / from langDir, just 'locales'

**Comment by sawa-ko** [comment]
> > Same problem here `"@nuxtjs/i18n": "8.0.0-beta.8"`
> > 
> > ![image](https://user-images.githubusercontent.com/56084970/214196873-3c4aa234-1fb5-493a-a7f2-03a589f21654.png)
> > 
> > ```ts
> > 	i18n: {
> > 		baseUrl: 'https://next.naeko.moe',
> > 		strategy: 'prefix_except_default',
> > 		lazy: true,
> > 		langDir: 'locales/',
> > 		defaultLocale: 'es',
> > 		detectBrowserLanguage: {
> > 			alwaysRedirect: true,
> > 			fallbackLocale: 'es',
> > 		},
> > 		locales: [
> > 			{
> > 				code: 'es',
> > 				name: 'Español',
> > 				file: 'es.json',
> > 			},
> > 		],
> > 		vueI18n: {
> > 			locale: 'es',
> > 			legacy: false,
> > 		},
> > 	},
> > ```
> > 
> > ![image](https://user-images.githubusercontent.com/56084970/214196936-db27c5df-e9aa-40d5-997e-22ee191b84d5.png)
> > 
> > ![image](https://user-images.githubusercontent.com/56084970/214196962-3160822d-8d7a-4c10-af12-90b62291829e.png)
> 
> Remove the / from langDir, just 'locales' 

If I remove it, the lazy option asks me for it.

**Comment by sawa-ko** [comment]
> @kaname-png try edge version. There, it works for me.

What is the Edge version?

**Comment by dsvgl** [comment]
> > @kaname-png try edge version. There, it works for me.
> 
> What is the Edge version?

https://github.com/nuxt-modules/i18n#install-edge-version

**Comment by urbgimtam** [comment]
Having the exact same issue, even after installing edge version.

https://stackblitz.com/edit/github-us1wuk?file=nuxt.config.ts

**Comment by kazupon** [comment]
@urbgimtam 
Hi!
Could you try to re-install from clean (`rm -rf node_modules package-lock.json`) please? 🙏 

I've just tried to download your repo and re-install, so I could not reproduce hydration miss-match.
I think it has already fixed in the latest edge version

**Comment by StefanoTesla** [comment]
I confirm, in my 3 installations problem is solved

> @urbgimtam Hi! Could you try to re-install from clean (`rm -rf node_modules package-lock.json`) please? 🙏
> 
> I've just tried to download your repo and re-install, so I could not reproduce hydration miss-match. I think it has already fixed in the latest edge version

**Comment by sawa-ko** [comment]
Any way to solve this?
1. No cookie is set by default when the user visits the page for the first time.
2. Even if the page is reloaded it does not save any cookies.
3. The cookie is only saved if the user switches to any other language and then switches back to the preferred language.
4. It happens when the page is pre-rendered (SSG), when the page is SSR the problem does not occur but the default cookie is still not saved.

```ts
	i18n: {
		baseUrl: 'https://next.naeko.moe',
		defaultLocale: 'en',
		strategy: 'prefix_except_default',
		langDir: 'locales',
		lazy: true,
		locales: [
			{
				name: 'English',
				code: 'en',
				iso: 'en-US',
				file: 'en.json',
			},
			{
				name: 'Español',
				code: 'es',
				file: 'es.json',
				iso: 'es-ES',
			},
		],
		detectBrowserLanguage: {
			alwaysRedirect: true,
			redirectOn: 'all',
			cookieKey: 'neko-lang',
		},
	},
```

https://user-images.githubusercontent.com/56084970/214631082-c22f7dd7-5cdb-404d-bbf2-2f9b09f620e7.mp4

**Comment by dsvgl** [comment]
@kaname-png 
have you tried a clean install like mentioned above?
`rm -rf node_modules package-lock.json`

I also got the example from @urbgimtam working with this approach. See this forked Stackblitz with newly created lock file: https://stackblitz.com/edit/github-us1wuk-bsbjoa?file=package.json

**Comment by sawa-ko** [comment]
@dsvgl Same problem. :(
The cookie is not set by default and also shows the flash of switching from English to Spanish (current browser language) on SSG pages (as I showed in the previous video).

**Comment by supermar1010** [comment]
What version do you use? I'm on beta9 now and there everything works as expected, maybe try that? But edge should work as well

**Comment by Milenoi** [comment]
Hi, 

i am using  "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge" in my nuxt project. Nuxt 3.4.1, ssr true. 

I am using dynamic language files: 
de.de.js: 

export default defineI18nLocale(async (context, locale) => {
    const keys = await useFetchTranslations();
    return keys.value
})

This causes Hydration mismatch errors. All text strings are not rendered on server. 
Is there a fix for this?

**Comment by n4an** [comment]
https://github.com/nuxt-modules/i18n/issues/2300

**Comment by alexcroox** [comment]
setting `lazy: false` was the fix for me

**Comment by tewnut** [comment]
> setting `lazy: false` was the fix for me

Instead of this workaround, upgrading to "@nuxtjs/i18n": "8.1.1" fixes it.

**Comment by bulestudio** [comment]
Edge fixed the issue too!
