### ISSUE TITLE
Typed in the composable `useI18n('key')` and in `$t('key')`

### ISSUE THREAD

**Issue by sawa-ko** [nuxt-modules/i18n#1817]
### Describe the feature

It would be great if when setting a translation key it would come with typescript typing based on the default language json file structure, this way you can avoid accidental typing errors in translation keys and provide the developer with a better environment as he can see what translation keys he has available in a list without the need for external tools.

I have seen this idea in next-intl and it looks very interesting.
https://next-intl-docs.vercel.app/docs/usage/typescript

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by ineshbose** [comment]
#1753

**Comment by kazupon** [comment]
Hi! 
Thank you for your feedback!
The same issue is already in #1753.

So, close
