### ISSUE TITLE
useSwitchLocalePath not changing locale

### ISSUE THREAD

**Issue by ineshbose** [nuxt-modules/i18n#1827]
### Discussed in https://github.com/nuxt-modules/i18n/discussions/1826

<div type='discussions-op-text'>

<sup>Originally posted by **zozulinskyi** January 26, 2023</sup>
Hello everyone. I like a `strategy: no_prefix`
But I can't change locale when I use next code:
```
const switchLocalePath = useSwitchLocalePath();
....

<nuxt-link :to="switchLocalePath('en')">English</nuxt-link>
```

Any ideas how I can fix that?
Nuxt: 3.1.0
Nuxtjs/i18n: 8.0.0-beta.8</div>

Reproduction: https://stackblitz.com/edit/nuxt3-jmqbek?file=README.md

**Comment by kazupon** [comment]
Thanks for always commenting on our github discussions and discord!
I would appreciate your kind support. 

I've commented about this issue.
https://github.com/nuxt-modules/i18n/discussions/1826#discussioncomment-4809422

This issue not bug.
Close
