### ISSUE TITLE
[next] Async load of translation files

### ISSUE THREAD

**Issue by JBustin** [nuxt-modules/i18n#1829]
### Describe the feature

Hello,

With nuxt2 and nuxt-i18n, we can asynchronously load the translation files by doing this kind of thing: https://github.com/nuxt-modules/i18n/issues/1042#issuecomment-766424969

It is not possible with nuxt3 and nuxt-i18n@next.
https://github.com/nuxt-modules/i18n/issues/1448
https://github.com/nuxt-modules/i18n/blob/next/TODO.md

**Is it planned for the future ?**

I need to know because my huge current project is based on translations that can be updated anytime, and we don't want to restart the servers each time to reload the translations. I'm working on the migration from nuxt2 to nuxt3, so this feature is essential. If it is not planned, I have to find an alternative.

By the way, thanks for your great job !

Regards

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by pumano** [comment]
I also trying to migrate from nuxt 2 and that feature is not implemented :(

Hope will be added soon

**Comment by JBustin** [comment]
Hello contributors, could you please just first tell us if this feature is planned or not ?
Regards

**Comment by kazupon** [comment]
close with #1938
