### ISSUE TITLE
NuxtLink / localePath removes href attribute when passed an absolute external path

### ISSUE THREAD

**Issue by dixhuit** [nuxt-modules/i18n#1830]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `i18n`, `modules`, `runtimeConfig`, `vite`, `vue`
- Runtime Modules:  `nuxt-icon@0.2.6`, `@nuxtjs/i18n@8.0.0-beta.9`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

```html
<NuxtLink :to="localePath('https://github.com')">GitHub</NuxtLink>
```

### Describe the bug

Passing an absolute external path to `localePath()` (in the context of NuxtLink's `to` prop) results in an anchor element with no `href` attribute.

I would expect `localePath()` to just leave the path alone in this instance and return it as-is. This would make it a lot easier to programmatically build out many links (e.g. a menu) that makes use of both internal and external URLs without having to check if a path is internal or external for each link.

**Comment by ineshbose** [comment]
This is also related to `vue-i18n-routing` - would be useful to take a look there!

**Comment by kazupon** [comment]
`localPath` is not designed to pass such URLs as is when received. This is also true for nuxt i18n module v7.x.

If we need to support it, we need to extend vue-i18n-routing.
welcome contribution!

**Comment by dixhuit** [comment]
Understood. I think we should extend it then as the current behaviour in Nuxt is not expected and I feel this use-case is common enough.
