### ISSUE TITLE
Use i18n instance outside of setup function

### ISSUE THREAD

**Issue by dvdmlln** [nuxt-modules/i18n#1831]
### Describe the feature

Hi,

I'm looking for a way using the i18n instance outside a setup function, in my case in a middleware.
Currently I am using vue-i18n without the nuxt module as a workaround, see [this issue](https://github.com/intlify/nuxt3/issues/76).
Or am I missing something and this is somehow already possible?

Best regards
David

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by ananthachetan** [comment]
I have a similar issue where I need access to the i18n instance. I'm using Vuetify 3 with Nuxt 3. According to their documentation here: https://dev.vuetifyjs.com/en/features/internationalization/#vue-i18n we need to pass an instance created by createI18n() to their adapter createVueI18nAdapter(). Since this nuxt module takes care of the instantiation I have no way to pass the object.

**Comment by rchl** [comment]
This module dynamically loads translations on a per-request basis. In theory (even if not very realistic) every request could have different translations loaded depending on some request data. Also, with lazy loading, only translations specific to user's locale are loaded. And, depending on the page being loaded, the translations can also differ since specific pages can have its own locales specified in i18n blocks.

So if there would exist a global i18n instance that you could use outside of the setup block, I think that it wouldn't be very well defined what locales it should contain.

(I'm speaking based on my knowledge of the Nuxt 2 version. Can't speak for Nuxt 3 version although I would assume this still applies.)

**Comment by rchl** [comment]
That said, Nuxt plugins and Nuxt middlewares should have access to the instance as those are not "global" contexts. So maybe that's a bug or missing feature in Nuxt 3 version.

My answer should still apply to @ananthachetan's question.

**Comment by ananthachetan** [comment]
> That said, Nuxt plugins and Nuxt middlewares should have access to the instance as those are not "global" contexts. So maybe that's a bug or missing feature in Nuxt 3 version.
> 
Right! Because currently the nuxtApp instance inside the plugin has only access to the global composer ($i18n) and not i18n instance. 
I've written the following code (in case anyone needs this) to workaround this as the createVueI18nAdapter() function only needs the global object of i18n instance:

```
import { createVuetify } from "vuetify";
import { createVueI18nAdapter } from "vuetify/locale/adapters/vue-i18n";
...
export default defineNuxtPlugin((nuxtApp) => {
    const i18n = { global: nuxtApp.$i18n };
    const vuetify = createVuetify({
        ...
        locale: {
            adapter: createVueI18nAdapter({ i18n, useI18n }),
        },
    });

    nuxtApp.vueApp.use(vuetify);
});
```

**Comment by the94air** [comment]
I am looking to access i18n inside of a nuxt middleware to show a message but getting an error that it can't be used outside of setup
```ts
export default defineNuxtRouteMiddleware(() => {
  const { $i18n } = useNuxtApp();
  // ...
  if (isAuth === false) {
    message.info($i18n.t("you-cant-access-this-page"));
    return navigateTo("/some-where");
  }
});
```

**Comment by rutgerbakker95** [comment]
This is working for me in `defineNuxtRouteMiddleware`

```js
const nuxtApp = useNuxtApp();

await nuxtApp.$i18n.setLocale('en');
```

- Operating System: `Darwin`
- Node Version:     `v18.14.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `runtimeConfig`, `vite`, `modules`, `i18n`, `tailwindcss`, `apollo`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/tailwindcss@6.6.4`, `@nuxtjs/apollo@5.0.0-alpha.6`
- Build Modules:    `-`

**Comment by kazupon** [comment]
This issue has fixed on #2146 
So close

**Comment by the-loker** [comment]
How to add typing to $i18n?

**Comment by lukas-pierce** [comment]
1. Create a plugin `plugins/i18n.ts` as described in the official manual <br>https://vue-i18n.intlify.dev/guide/integrations/nuxt3.html#setup-nuxt-plugin

2. In this plugin add return statement with provide

```ts
// plugins/i18n.ts
import { createI18n } from 'vue-i18n'

export default defineNuxtPlugin(({ vueApp }) => {
  const i18n = createI18n({
    legacy: false,
    globalInjection: true,
    locale: 'en',
    messages: {
      en: {
        hello: 'Hello, {name}!'
      }
    }
  })

  vueApp.use(i18n)

  // ---------------- add return provide ----------------
  return {
    provide: {
      i18nGlobal: i18n.global
    }
  }
})
```

3. Now `$i18nGlobal` accessible using useNuxtApp().
```ts
// middleware/my-middleware.ts
export default defineNuxtRouteMiddleware(() => {
  const { $i18nGlobal } = useNuxtApp()
  const message = $i18nGlobal.t('hello', { name: 'Lukas' })
  console.log(message)
})
```

It can be used outside setup function. And at the same time, you won’t lose any of the benefits of the standard vue-i18n approach.

For more convenience, you can add composable:

```ts
// composables/useI18nGlobal.ts
export const useI18nGlobal = () => {
  const { $i18nGlobal } = useNuxtApp()
  return $i18nGlobal
}
```

After recompile (rerun npm run dev) you can use global composable:

```ts
// middleware/my-middleware.ts
export default defineNuxtRouteMiddleware(() => {
  const i18n = useI18nGlobal()
  const message = i18n.t('hello', { name: 'Lukas' })
  console.log(message)
})
```
