### ISSUE TITLE
i18n issues when running "node .output/server/index.mjs", while "nuxt dev" and "nuxt preview" works fine

### ISSUE THREAD

**Issue by martinsjek** [nuxt-modules/i18n#1833]
### Environment

- Nuxt Version: 3.1.1
- Nitro Version: 2.1.1
- Package Manager: npm@8.19.3
- Builder: vite
- User Config: modules, css, vite, nitro, runtimeConfig, router, app, image, i18n, telemetry
- Runtime Modules: @nuxtjs/i18n@8.0.0-beta.9, @nuxt/image-edge@1.0.0-27919678.2f5b64b, @pinia/nuxt, @vueuse/nuxt@9.12.0
- Build Modules: -

### Reproduction

in app.vue:

const runtimeConfig = useRuntimeConfig();
const nuxtApp = useNuxtApp();

const { data } = await useFetch(${runtimeConfig.apiBaseUrl}/api/translations);

const translationsData = data.value;

nuxtApp.$i18n.warnHtmlMessage = false;

for (const i in translationsData) {
const translations = translationsData[i];
nuxtApp.$i18n.setLocaleMessage(i, translations);
}

### Describe the bug

While running "nuxt dev" or "nuxt preview" everything works fine without any issues, but when running "node .output/server/index.mjs", then i get this error in console "[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format.". And half of my translations show keys instead of translation in UI.

**Comment by kazupon** [comment]
Thank you for your feedback!

>"intlify The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format.".

vue-i18n (`@intlify/unpluign-vue-i18n`) pre-compiles locale messages (translations) is built for production, If these are used by `import` syntax in non-back-end code such as Vue Component or plugins.
https://vue-i18n.intlify.dev/guide/advanced/optimization.html#optimization

Unfortunately, in the case of back-end, such as Nuxt's API, vue-i18n cannot pre-compile it. 😞 
If you would like to pass locale messages to the client-side from your API, you will need to pre-compile them in your API logic using [intlify cli](https://github.com/intlify/cli) or [compile API](https://github.com/intlify/cli/blob/main/api.md#compile)

**Comment by jianbin-lim** [comment]
> Thank you for your feedback!
> 
> > "intlify The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format.".
> 
> vue-i18n (`@intlify/unpluign-vue-i18n`) pre-compiles locale messages (translations) is built for production, If these are used by `import` syntax in non-back-end code such as Vue Component or plugins. https://vue-i18n.intlify.dev/guide/advanced/optimization.html#optimization
> 
> Unfortunately, in the case of back-end, such as Nuxt's API, vue-i18n cannot pre-compile it. 😞 If you would like to pass locale messages to the client-side from your API, you will need to pre-compile them in your API logic using [intlify cli](https://github.com/intlify/cli) or [compile API](https://github.com/intlify/cli/blob/main/api.md#compile)

Thank for your information, Is there a solution that can be fixed it on the front end(nuxt3)?

**Comment by kazupon** [comment]
I’m working on i18n resource pre-compilation that is possible using the current nuxt (nirto) prerender mechanism.
Maybe, we will include into this PR as experimental features.
https://github.com/nuxt-modules/i18n/pull/1938

**Comment by jianbin-lim** [comment]
> I’m working on i18n resource pre-compilation that is possible using the current nuxt (nirto) prerender mechanism. Maybe, we will include into this PR as experimental features. #1938

Looking forward to this feature

**Comment by perenstrom** [comment]
Any updates on this @kazupon ? :)
