### ISSUE TITLE
does not provide an export named 'assign'

### ISSUE THREAD

**Issue by cyperdark** [nuxt-modules/i18n#1840]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `telemetry`, `app`, `vue`, `ssr`, `components`, `router`, `runtimeConfig`, `nitro`, `vite`, `imports`, `modules`, `i18n`, `extends`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`
- Build Modules:    `-`
------------------------------

### Reproduction

I just installed package and add to modules in nuxt.config.ts

### Describe the bug

I run my project in dev mode and in browser console i got this issue:
 
```Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/@intlify_shared.js?v=a67894b1' does not provide an export named 'assign' (at message-compiler.mjs?v=a67894b1:6:18)```

**Comment by kazupon** [comment]
Thank you for your reporting!

We need minimul reporduction, so we can't find out the cause.
Could you give us your minimal reproduction code please? 🙏

**Comment by cyperdark** [comment]
nvm. It was issue at my end

If someone looking for solution, here what i did: i uninstall those packages:
```
@intlify/unplugin-vue-i18n
```
and
```
vue-i18n
```

Then i deleted ``node_modules`` folder and installed all packages again: 
```
npm i
```
or
```
yarn install
```
