### ISSUE TITLE
strategy prefix not work on spa mode

### ISSUE THREAD

**Issue by just-another-peter** [nuxt-modules/i18n#1843]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.0.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `ssr`, `swiper`, `app`, `runtimeConfig`, `vite`, `postcss`, `i18n`
- Runtime Modules:  `nuxt-swiper@0.1.9`, `@vueuse/nuxt@9.11.0`, `@nuxtjs/device@3.0.0`, `@nuxtjs/i18n@8.0.0-beta.9`
- Build Modules:    `-`
------------------------------

### Reproduction

`nuxt.config.ts`
```javascript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ["@nuxtjs/i18n"],
  css: ["~/assets/css/main.css"],
  ssr: false,
  vite: {
    css: {
      preprocessorOptions: {
        sass: {
          additionalData: '@import "@/assets/styles/variable.sass"',
        },
      },
    },
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  i18n: {
    strategy: "prefix",
    defaultLocale: "zh",
    locales: [
      {
        name: "English",
        code: "en",
        iso: "en-hk",
        file: "en.json",
      },
      {
        name: "繁體",
        code: "zh",
        iso: "zh-hant-hk",
        file: "zh.json",
      },
    ],
    lazy: true,
    langDir: "locales/",
    vueI18n: {
      silentTranslationWarn: true,
      legacy: false,
    },
  },
});

```

### Describe the bug

As [nuxt.i18n documentation](https://v8.i18n.nuxtjs.org/guide/routing-strategies) mentioned that `all routes will have a locale prefix.`, but in my case, the default locale will NOT auto add the locale in URL.

### Additional context

My Excecptaion:
When user enter home route (localhost:3000) , it will auto go to localhost:3000/zh

If I set `ssr` to `true` in `nuxt.config.ts`, it will works as expect, but my application is static(`npm run generate`), instead of SSR(`npm run build`)

**Comment by kazupon** [comment]
Thank you for your feedback!

I've tried to reproduce your reporting info.
Unfortunately, I could not reproduce this issue.
We need your minimal repro code.
Could you give us your it via github repo or stackbliz, please? 🙏

**Comment by just-another-peter** [comment]
> Thank you for your feedback!
> 
> I've tried to reproduce your reporting info. Unfortunately, I could not reproduce this issue. We need your minimal repro code. Could you give us your it via github repo or stackbliz, please? 🙏

Here is the stackblitz demo, I expect the index page will have a default locale on URL, in my demo /zh
https://stackblitz.com/edit/nuxt-starter-4buutf?file=nuxt.config.ts

**Comment by awais-afoxtech** [comment]
It is also not working on `ssr: true` mode.

`export default defineNuxtConfig({
  modules: ["@nuxtjs/i18n"],
  ssr: true,
  i18n: {
    strategy: "prefix",
    defaultLocale: "zh",
    locales: [
      {
        name: "English",
        code: "en",
        iso: "en-hk",
      },
      {
        name: "繁體",
        code: "zh",
        iso: "zh-hant-hk",
      },
    ],
    vueI18n: {
      silentTranslationWarn: true,
      legacy: false,
    },
  },
});`
