### ISSUE TITLE
bug: inconsistent redirects and locale detection

### ISSUE THREAD

**Issue by tafelnl** [nuxt-modules/i18n#1850]
### Environment

- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `i18n`, `typescript`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-8hn8cb

### Describe the bug

I think there's quite some inconsistencies/unclarity in this plugin regarding redirection and locale detection.

---

For the rest of this issue, suppose we have the following base config set:

```ts
  i18n: {
    locales: [
      {
        code: 'en',
        name: 'English',
        iso: 'en-GB',
      },
      {
        code: 'nl',
        name: 'Nederlands',
        iso: 'nl-NL',
      },
    ],
    defaultLocale: 'en',
  },
```

---

A few examples:

---

### 1.

with the following settings:

```ts
  i18n: {
    // ... base config ...
    strategy: 'prefix',
  },
```

If your browser locale is set to `nl` and you navigate to `/`, the following will happen:

- the logs will detect `nl` is your browser locale
- not redirected anywhere (stays on `/`) [1]
- ends with a `302 Found` status code [2]
- locale wrongly set to `en` instead of `nl` [3]
- cookie wrongly set to `en` instead of `nl` [4]

[1] although from the docs I understand the `prefix` strategy should redirect to the correct locale.
[2] which is not good for SEO and just in general unexpected I guess
[3] I don't know why this would happen
[4] I don't understand when a cookie will be or will not be set (see example 2. also)

---

### 2.

with the following settings:

```ts
  i18n: {
    // ... base config ...
    detectBrowserLanguage: {
      alwaysRedirect: true,
    },
    strategy: 'prefix',
  },
```

If your browser locale is set to `nl` and you navigate to `/`, the following will happen:

- the logs will detect `nl` is your browser locale
- not redirected anywhere (stays on `/`) [1]
- ends with a `302 Found` status code [2]
- locale correctly set to `nl`
- **no** cookie will be set [5]

[5] Weird because in the previous example, it was set (incorrectly, but that doesn't matter here for now). So I think it's unexpected to not set it here.

---

### 3.

with the following settings:

```ts
  i18n: {
    // ... base config ...
    detectBrowserLanguage: {
      alwaysRedirect: true,
      redirectOn: 'no prefix',
    },
    strategy: 'prefix',
  },
```

If your browser locale is set to `nl` and you navigate to `/foobar`, the following will happen:

- the logs will detect `nl` is your browser locale
- not redirected anywhere (stays on `/foobar`) [1]
- ends with a `302 Found` status code [2]
- locale wrongly set to `en` instead of `nl` [6]
- cookie wrongly set to `en` instead of `nl` [4]

[6] Which is weird, because as we saw in the previous example, for the root it was correctly set to `nl`

### Additional context

Maybe these examples should have been split up into separate issues. But I'm not sure if they are or are not related to each other.

**Comment by Suniron** [comment]
Same error with nuxt bridge

**Comment by ashour** [comment]
I've encountered similar behaviour
