### ISSUE TITLE
Custom path doesn't work

### ISSUE THREAD

**Issue by kenan-dfrn** [nuxt-modules/i18n#1852]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `meta`, `components`, `vite`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/i18n-edge@8.0.0-beta.9-27933522.1266c91`, `@nuxt/devtools@0.1.0`
- Build Modules:    `-`

### Reproduction

i can give repo link in private (#NEEFT Anebris#3886 on discord)

### Describe the bug

i want to create a custom path inside my pages. i've tried to do that dirrectly inside my page but it doesn't work and inside my nuxt config. The nuxt config rewrite my path but only when the file is in pages root.

'pages/teams/index.vue' (doesn't work)
```
  setup () {
    defineI18nRoute({
      paths: {
        fr: '/equipes',
      }
    })
  }
```

'pages/test.vue' (doesn't-work)
```
  setup () {
    defineI18nRoute({
      paths: {
        fr: '/a-propos',
      }
    })
  }
```

'package.json'
```
  "devDependencies": {
    "@nuxtjs/i18n-edge": "^8.0.0-beta.9-27933522.1266c91",
```

'nuxt.config'
```
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxtjs/i18n-edge',
    '@nuxt/devtools'
  ],

  i18n: {
    strategy: 'prefix_except_default',
    defaultLocale: 'en',
    langDir: 'langs',
    baseUrl: 'http://localhost:3000',
    locales: [
      { code: 'en', iso: 'en-US', file: 'en.json', dir: 'ltr' },
      { code: 'fr', iso: 'fr-FR', file: 'fr.json', dir: 'ltr' }
    ],
    lazy: true,
    types: 'composition',
    vueI18n: {
      fallbackLocale: 'en',
      legacy: false,
      locale: 'en'
    },
    customRoutes: 'config', 
    pages: {
      teams: {
        fr: '/equipes',  // (doesn't work)
      },
      test: {
        fr: '/test-fr' // (work)
      }
    }
```

**Comment by kazupon** [comment]
Thank you for your reporting!
We need the **minimul reproduction with github repo or stackbliz.**
issue guideline said:
>Please provide a link to a repo that can reproduce the problem you ran into. A minimal reproduction is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided we might close it.

Could you give us it please? 🙏

**Comment by kazupon** [comment]
close in-activity.
if you still would have the issue, please open as new issue.
Thanks!
