### ISSUE TITLE
Hook i18n:extend-messages does not work as expected

### ISSUE THREAD

**Issue by devonik** [nuxt-modules/i18n#1855]
### Environment

I am writing a nuxt module and have added the hook snippet within the module setup()

`nuxt.hook('i18n:extend-messages', async (additionalMessages, localeCodes) => {
      console.log("additionalMessages", additionalMessages)
      additionalMessages.push({
        de: {
          'my-module-exemple': {
            hello: 'Hello from external module'
          }
        },
        en: {
          'my-module-exemple': {
            hello: 'Bonjour depuis le module externe'
          }
        }
      })
    })`

The hook seems called but the i18n messages looks weird and seems not correct.
I18n instance:
`{ "id": 1, "locale": "de", "fallbackLocale": false, "inheritLocale": true, "availableLocales": [ "de" ], "messages": { "de": { "my-module-exemple": {} } }, "modifiers": {}, "pluralRules": {}, "isGlobal": true, "missingWarn": true, "fallbackWarn": true, "fallbackRoot": true, "fallbackFormat": false, "warnHtmlMessage": true, "escapeParameter": false, "datetimeFormats": { "de": {} }, "numberFormats": { "de": {} }, "locales": [], "localeCodes": [], "baseUrl": "", "strategy": "prefix_except_default", "localeProperties": { "code": "de" }, "differentDomains": false }`

### Reproduction

Add the hook snippet from doc https://i18n.nuxtjs.org/extend-messages to the module.ts 

`nuxt.hook('i18n:extend-messages', async (additionalMessages, localeCodes) => {
      console.log("additionalMessages", additionalMessages)
      additionalMessages.push({
        de: {
          'my-module-exemple': {
            hello: 'Hello from external module'
          }
        },
        en: {
          'my-module-exemple': {
            hello: 'Bonjour depuis le module externe'
          }
        }
      })
    })`

### Describe the bug

The message added to vue i18n instance are broken

**Comment by kazupon** [comment]
Thank you for your reporting!

We need the **minimul reproduction with github repo or stackbliz**.
Could you give us it please? 🙏

**Comment by xibman** [comment]
Same here with last beta version 8.0.0-beta.9-27941261.23fe238

Hook is not called

**Comment by devonik** [comment]
Hey, sorry i was a bit busy. Here is a Stackblitz example: https://stackblitz.com/edit/nuxt-starter-pkguyh?file=nuxt.config.ts,package.json,module%2Fmodule.ts,app.vue

Seems working oO Then i was just confused the logged messages.de.my-module-exemple object is empty.
@xibman check the stackblitz to see how it's working. I'm using "next" version of @nuxt/i18n

**Comment by xibman** [comment]
It works also with last version but the custom module must be inserted before nuxtI18n declaration.

Work 
```
modules: [
    resolve('./modules/custom/index.ts'),
    '@nuxtjs/i18n-edge',
],
```

but 

```
modules: [
  '@nuxtjs/i18n-edge',
    resolve('./modules/custom/index.ts'),
],
```
not working the hook is never called  @devonik

**Comment by kazupon** [comment]
>It works also with last version but the custom module must be inserted before nuxtI18n declaration.

Yes, We need insert custom module before nuxtI18n declaration
