### ISSUE TITLE
redirect loop

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#1856]
### Environment

nuxt generate + nginx

nuxt 3.2.0
@nuxtjs/i18n-edge@8.0.0-beta.9-27936380.225e0b6

### Reproduction

https://test.stefanotesla.it/en/
https://b0d8d43b.jonas-thelemann.pages.dev/legal-notice/

### Describe the bug

The page redirects endlessly.

### Additional context

https://test.stefanotesla.it works fine.
https://b0d8d43b.jonas-thelemann.pages.dev/ works fine.

**Comment by StefanoTesla** [comment]
it can be a possible redirect caused by nginix cause vue route default is without final trailing slash, but standard server works wit directory path so it try to go on link.domain/page/ but vue route redirrect to link.domain/page causing an infinite loop?

**Comment by dargmuesli** [comment]
For me, it does that once, then it reloads on the path without a trailing slash.

**Comment by StefanoTesla** [comment]
from my mobile `https://test.stefanotesla.it/en/` don't work but `https://test.stefanotesla.it/en` works, but on pc anyone work, I tried to force via .htacess but I don't find the way

**Comment by kazupon** [comment]
I think I could fix this issue with #1858 
Please check it with edge channel version

**Comment by dargmuesli** [comment]
[Looks good to me](https://github.com/dargmuesli/jonas-thelemann/actions/runs/4177752855)! Thank you <3
