### ISSUE TITLE
`redirectOn` is not work on `prefix_and_default`

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#1859]
> Seems to work on the root page ("/") or with strategy no_prefix, but NOT on sub pages with `prefix_and_default`, even though redirectOn is set to "all" or "no prefix".
Somehow `detectBrowserLanguage` gets called twice (once through the plugin init and once in the middleware), and the second time it just returns no language because both checks ( https://github.com/nuxt-modules/i18n/blob/next/src/runtime/internal.ts#L407 and https://github.com/nuxt-modules/i18n/blob/next/src/runtime/internal.ts#L411) are false.

Reproduction: https://stackblitz.com/edit/github-agwtyv-1bsafu

_Originally posted by @Alex--C in https://github.com/nuxt-modules/i18n/issues/1632#issuecomment-1419531146_

**Comment by borghol** [comment]
@kazupon I believe this issue can be closed

**Comment by kazupon** [comment]
Oh, Oops.
I'll close this issue.
I appreciate your contribution!

Thanks!
