### ISSUE TITLE
fix: navigation breaks

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#1860]
### Environment

v8.0.0-beta.9-27939896.9b0ebb4

### Reproduction

https://dc2a4eb3.jonas-thelemann.pages.dev/

### Describe the bug

Following the just fixed #1856, I noticed that there is an issue still: when I go to https://dc2a4eb3.jonas-thelemann.pages.dev/ and (scroll down to) click on "Legal Notice" I get directed to https://dc2a4eb3.jonas-thelemann.pages.dev/legal-notice as expected but then right away to https://dc2a4eb3.jonas-thelemann.pages.dev/legal-notice/ with a trailing slash.
Also, navigating back in the browser does *not* work as well. The first navigation back practically does not change the page the page. Also a second navigation back does not change anything visually.

**Comment by kazupon** [comment]
Hmm, that is weired.
The issues around web and Nuxt trailing slash are very complicated.

The behavior of nuxt is as follows
https://github.com/nuxt/nuxt/discussions/10237

And it seems that different hosting services handle trailing slashes differently, so nuxt also has issues.
https://github.com/nuxt/nuxt/issues/15462

**Comment by kazupon** [comment]
Hi!
I've just fixed this issue.
Please try to use edge channel version.
Thanks!

**Comment by dargmuesli** [comment]
Can confirm this to be working! Thank a lot :heart:
