### ISSUE TITLE
Navigation regression between c5960fd and c439ae7

### ISSUE THREAD

**Issue by Extarys** [nuxt-modules/i18n#1864]
### Environment

```
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `ssr`, `app`, `modules`, `unhead`, `nitro`, `build`, `vite`, `buildModules`, `i18n`, `routeRules`, `content`, `css`, `windicss`
- Runtime Modules:  `nuxt-windicss@2.6.0`, `@nuxtjs/i18n@8.0.0-beta.9-27925188.c5960fd`, `@nuxt/content@2.4.3`, `nuxt-simple-sitemap@1.0.7`, `nuxt-simple-robots@1.0.2`, `nuxt-unhead@1.3.4`
- Build Modules:    `-`
```

### Reproduction

Unsure

### Describe the bug

All links (`NuxtLink :to=""` and `<a href="#something">`) on a project I was working on stopped working. I can see the path on mouse over in the browser's bottom left side of the screen, but clicking on it didn't do anything. The hash path flashed real quick in the URI address bar, but nothing else happened.

I disabled some plugins, tried some things, but couldn't find the cause. The only thing that worked was to roll back nuxt-i18n version.

I managed to isolate the last version where it worked.

Works: 8.0.0-beta.9-27925188.c5960fd
Stopped working at: 8.0.0-beta.9-27925536.c439ae7

I tested from the latest until it worked, skipping 1 version each time until I found a working version and then go back up one version until the problem appear. 
Tested versions that didn't work:
1. 23fe238
2. 225e0b6
3. 891e694
4. c439ae7
5. bca8cdf

### Logs

```shell
No log were produced by the browser or Nuxi.
```

**Comment by kazupon** [comment]
related issue #1860

**Comment by kazupon** [comment]
Hi!
I've just fixed this issue.
Please try to use edge channel version.
Thanks!

**Comment by Extarys** [comment]
Doesn't appear to be working on my end. I removed the version tag in packages.json and ran `yarn` then tested. This is what is inside yarn.lock file:
```
"@nuxtjs/i18n@npm:@nuxtjs/i18n-edge":
  version "8.0.0-beta.9-27947021.50866fa"
```

**Comment by kazupon** [comment]
Could you provide minimal reproduction github repo or stackblize please?
I seem that your issue is different case.

**Comment by Extarys** [comment]
Argh, where can I create a sandbox without creating an account?
I believe I found the issue, at least on my end.
Setting `strategy` to `prefix_and_default` makes all NuxtLink broken (they don't do anything), switching to `prefix` works like a charm.

**Comment by ineshbose** [comment]
You can create a repository on GitHub for a reproduction!

**Comment by kazupon** [comment]
close in-activity.
If you have still issue, please you will open as new.

thanks!
