### ISSUE TITLE
Strategy "prefix" not working for root page in Nuxt 3.2.0 

### ISSUE THREAD

**Issue by elpeyotl** [nuxt-modules/i18n#1865]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `modules`, `app`, `vite`, `build`, `runtimeConfig`, `telemetry`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/tailwindcss@6.3.1`, `@nuxtjs/i18n@8.0.0-beta.9`
- Build Modules:    `-`

### Reproduction

i18nOptions.ts
```
import { NuxtI18nOptions } from '@nuxtjs/i18n'
import de from './lang/de-DE.json'
import en from './lang/en-US.json'

export const i18nOptions: NuxtI18nOptions<unknown> = {
  locales: [
    { code: 'en', name: 'English', file: 'en-US.json' },
    { code: 'de', name: 'Deutsch', file: 'de-DE.json' },
  ],
  defaultLocale: 'en',
  strategy: 'prefix',
  langDir: 'i18n/lang',
  lazy: true,
  vueI18n: {
    fallbackLocale: 'en',
    legacy: false,
    messages: { en, de },
  },
}
```

nuxt.config.ts
```
import { i18nOptions } from './i18n'

export default defineNuxtConfig({
  modules: [
    '@pinia/nuxt',
    '@nuxtjs/tailwindcss',
    [
      '@nuxtjs/i18n',
      {
        ...i18nOptions,
      },
    ],
  ],
  app: {
    head: {
      link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.svg' }],
      title: 'Hello Today',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      ],
    },
  },
  vite: {
    define: {
      __DEV__: (process.env.NODE_ENV === 'development').toString(),
    },
  },
  build: {
    transpile: [
      '@heroicons/vue',
      '@vuepic/vue-datepicker',
      '@apollo/client',
      '@vue/apollo-composable',
      'ts-invariant/process',
    ],
  },
  runtimeConfig: {
    public: {
      keycloakAuth: '',
      backendEndpoint: '',
      backendGraphqlEndpoint: '',
    },
  },
  telemetry: false,
})
```

### Describe the bug

When I set `strategy: 'prefix'` in the config i expect to receive an url like `http://localhost:3000/en` when I start the app. It adds the locale when i navigate around the app.

**Comment by ineshbose** [comment]
Possibly related #1843 (it is rather in `ssr: false` though) - could you check the edge version to confirm if this issue persists?

**Comment by elpeyotl** [comment]
I checked it witch the edge version. Problem is still here.

**Comment by tiees288** [comment]
I got a same problem after upgraded to Nuxt 3.2.0

**Comment by elpeyotl** [comment]
We found out that there is no local header present on the root. Thats were we detected that there is a issue:

Page is working but Kubernetes healtcheck throws an error. 
When i navigate to `localhost:3000/en` everything works fine. But the initial load should be with prefix. 

At the moment I try to write a workaround in a middleware. 

![Bildschirmfoto 2023-02-20 um 10 43 15](https://user-images.githubusercontent.com/3061225/220070264-191fc7f1-f166-4f76-ace6-4a162121ec55.png)

**Comment by ineshbose** [comment]
> We found out that there is no local header present on the root.

Could this also be related in that regard - #1611?

It would make investigate much easier if you could provide a reproduction on Stackblitz - possibly use the one in #1843 (https://stackblitz.com/edit/nuxt-starter-4buutf?file=package.json) as base but removing `ssr: false` and updating to edge and `nuxt@^3.2.0`

**Comment by tiees288** [comment]
First, Sorry about my bad english.

As my code (attached below)
Could you help me why it doesn't redirect to /th
when i entered path "/" before upgrading to 3.2.0 it's works fine.

I tried to debug but a navigate function doesn't navigate.

`navigate(
        {
          i18n,
          redirectPath,
          locale,
          route: to
        },
        {
          differentDomains,
          skipSettingLocaleOnNavigate,
          rootRedirect
        }
      );`


https://stackblitz.com/edit/nuxt-starter-wq1jrt?file=nuxt.config.ts

**Comment by elpeyotl** [comment]
@ineshbose I created a stackblitz as requested. As you can see on InitialLoad it is not adding the locale. 
https://stackblitz.com/edit/nuxt-starter-zgavu5?file=nuxt.config.ts,package.json,package-lock.json

It looks like the same issue in https://github.com/nuxt-modules/i18n/issues/1611 after the update to Nuxt 3.2.0

**Comment by kazupon** [comment]
Hi!
Could you try to remove `package-lock.json` and re-install ?
I could work on my enviroment.

**Comment by elpeyotl** [comment]
> Hi! Could you try to remove `package-lock.json` and re-install ? I could work on my enviroment.

Which version from the i18n module are you installing?

**Comment by elpeyotl** [comment]
> Hi! Could you try to remove `package-lock.json` and re-install ? I could work on my enviroment.

You are right! Its working again. Realized that nuxt did an update. 

So with nuxt 3.2.2 and `"@nuxtjs/i18n": "^8.0.0-beta.9",` it is working. 

So i close this issue.

**Comment by letoast** [comment]
This is still not working, please reopen the issue. nuxt 3.4.0, @nuxtjs/i18n@npm:@nuxtjs/i18n-edge
https://stackblitz.com/edit/nuxt-starter-8xdtod?file=nuxt.config.ts
