### ISSUE TITLE
missingHandler doesn't seem to be supported

### ISSUE THREAD

**Issue by MartijnCuppens** [nuxt-modules/i18n#1881]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `runtimeConfig`, `modules`, `vite`, `plugins`, `components`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxtjs/tailwindcss@6.4.0`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

Nuxt config
```js
{
modules: [
    [
      '@nuxtjs/i18n',
      {
        missing: (locale, key, vm, values) => {
          console.log('Never reaches this code');
        },
      },
    ],
  ],
}
```

### Describe the bug

It doesn't seem to be possible to set the missingHandler.

**Comment by kazupon** [comment]
Thank you for your reporting.
You need to set in `vueI18n` option the below:

```nuxt.config.ts
i18n: {
  // ...
  vueI18n: {
     // ...
      missing(...) {
        // something todo.
      },
    },
  }
}
```

 Thanks!

**Comment by fahmifitu** [comment]
> Thank you for your reporting. You need to set in `vueI18n` option the below:
> 
> ```ts
> i18n: {
>   // ...
>   vueI18n: {
>      // ...
>       missing(...) {
>         // something todo.
>       },
>     },
>   }
> }
> ```
> 
> Thanks!

This solution is not working.

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-rym3wa?file=nuxt.config.ts

Throws the following error:
```ERROR  Cannot restart nuxt:  input.replace is not a function```
