### ISSUE TITLE
pluralizationRules not working

### ISSUE THREAD

**Issue by sereda93** [nuxt-modules/i18n#1882]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `typescript`, `imports`, `modules`, `css`, `vite`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/device@3.1.0`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.9-27948515.3db6367`
- Build Modules:    `-`
------------------------------

### Reproduction

```ts
export default defineNuxtPlugin((nuxtApp) => {

  function customRule(choice: number, choicesLength: number) {
    if (choice === 0) {
      return 0
    }
  
    const teen = choice > 10 && choice < 20
    const endsWithOne = choice % 10 === 1

    if (!teen && endsWithOne) {
      return 1
    }
    if (!teen && choice % 10 >= 2 && choice % 10 <= 4) {
      return 2
    }
  
    return choicesLength < 4 ? 2 : 3
  }

  nuxtApp.$i18n.pluralizationRules = {
    'ru': customRule,
    'ua': customRule
  }
})
```

### Describe the bug

I add nuxt plugin for i18n but pluralization not working. I use i18n-edge version.

**Comment by ineshbose** [comment]
Hi, thanks for reporting an issue with the module - since you're using it in a plugin, I wonder about the configuration handling. To help you further, could I please ask you to provide a reproduction over Stackblitz so it's easier to investigate and ensure that we haven't missed anything?

You can use https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz as the base!

**Comment by kazupon** [comment]
BTW, from nuxt i18n v8 (vue-i18n v9), you need to use `pluralizationRules`, not `pluralRules`
ref vue-i18n v9 migration docs:
https://vue-i18n.intlify.dev/guide/migration/breaking.html#remove-getchoiceindex

**Comment by nazar1ua** [comment]
Yes, I use `puralRules` at the almost the same environment, and it's working. I think that this issue can be closed

**Comment by sanjarbarakayev** [comment]
When I tried to reassign `pluralRules` it giver error:

`[nuxt] error caught during app initialization TypeError: Cannot set property pluralRules of #<Object> which has only a getter`


@nazar1ua can you share your code and your `@nuxtjs/i18n` version

**Comment by nazar1ua** [comment]
Hello @sanjarbarakayev, what is your file structure?

**Comment by aloky** [comment]
in `app.vue`, im use `setPluralRules`
```
const i18n = useI18n();

i18n[Object.getOwnPropertySymbols(i18n)[0]]({
  ru: customRule,
});
```

**Comment by nazar1ua** [comment]
I'm sorry, I don't understand your complete file structure. But you can see how I did it here https://github.com/greenrute/frontend

**Comment by aloky** [comment]
> I'm sorry, I don't understand your complete file structure. But you can see how I did it here https://github.com/greenrute/frontend

ty, for example

**Comment by Gaspadlo** [comment]
> I'm sorry, I don't understand your complete file structure. But you can see how I did it here https://github.com/greenrute/frontend

The nuxt i18n docks for this are kind of bad - in the end I had to hunt down this thread and your post, that I in fact HAVE to use "pluralRules" and not "pluralizationRules" key and that I MUST NOT specify i18n.config.ts path in nuxt.config.ts - those where the final changes, that made custom pluralization rules work...

Frustrating.

**Comment by BobbieGoede** [comment]
@Gaspadlo 
The change from `pluralRules` to `plurarlizationRules` is a change in vue-i18n, this functionality is not provided by nuxt-i18n.

As for the path to `i18n.config`, this is optional and the error/warning should be descriptive enough if nuxt-i18n can't locate it. Could you be more descriptive on what could be improved in the docs? A PR would be much appreciated too 🙏

**Comment by Gaspadlo** [comment]
@BobbieGoede 
The pluralRules / plurarlizationRules is kind of on me  - I skimmed through the docs and clicked the first search result inside the vue-i18n docs not realizing, there's a "legacy" mode althogether. (and the first search result not being what I actually wanted)

Now with the nuxt-i18n - I am on a "9.3.1" version.
Inside nuxt.config.ts I have a i18n object with vueI18n property.
I don't know when / how is the path being resolved, but neither of those lines worked:

```
    //vueI18n: "../i18n/i18n.config.ts", // in case it was being resolved form the .nuxt/ folder?
    //vueI18n: "/i18n/i18n.config.ts",
    //vueI18n: "./i18n/i18n.config.ts",
    //vueI18n: "i18n/i18n.config.ts",
```
removing the line completely loaded the file from the exact place implicitly.

**Comment by BobbieGoede** [comment]
@Gaspadlo 
If you're on 9.3.1 or higher you should be seeing a warning if a path was provided but could not be found, including the directory from which nuxt-i18n is resolving the provided path. Could you check if this warning is logged?
