### ISSUE TITLE
Converting circular  structure to JSON

### ISSUE THREAD

**Issue by mahmutatmaca** [nuxt-modules/i18n#1885]
### Environment

 "nuxt": "^2.14.12",
"@nuxtjs/i18n": "^7.3.1"

### Reproduction

Converting circular  structure to JSON

### Describe the bug

✖ Nuxt Fatal Error                                                                                                                                                     │
   │                                                                                                                                                                          │
   │   Error: Could not compile template C:\Users\...\node_modules\@nuxtjs\i18n\src\templates\options.js: Converting circular   │
   │   structure to JSON                                                                                                                                                      │
   │   --> starting at object with constructor 'Object'                                                                                                                       │
   │   --- property 'default' closes the circle         

what is the solve?

**Comment by ineshbose** [comment]
More context on your issue would be helpful!

**Comment by mahmutatmaca** [comment]
it has been trying. when run build its get this error and break running. cause of error i18n json files

**Comment by kazupon** [comment]
Could you provide minimual reproduction please?

**Comment by MikeCheng1208** [comment]
HI~ I also encountered the same problem, I just imported JSON and this error appeared.

```javascript
"i18n": {
    "vueI18n": {
      "legacy": false,
      "locale": 'zh-TW',
      "messages": {
        'zh-TW': require('./language/zh-TW.json'),
        'en-US': require('./language/en-US.json'),
        'ja-JP': require('./language/ja-JP.json'),
      }
    }
  },
```

```
"nuxt": "^3.2.0",
"@nuxtjs/i18n": "^8.0.0-beta.10",
```
ERROR
```
 Cannot restart nuxt:  Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'default' closes the circle

  --> starting at object with constructor 'Object'
  --- property 'default' closes the circle
```

How should I solve it?

**Comment by kazupon** [comment]
Nuxt need esm module.
please, see the guide.
https://nuxt.com/docs/guide/concepts/esm

And, we would recommend that you should use locale mesasges lazy loading.
you can read the docs:
https://v8.i18n.nuxtjs.org/guide/lazy-load-translations

**Comment by paramula** [comment]
> HI~ I also encountered the same problem, I just imported JSON and this error appeared.
> 
> ```js
> "i18n": {
>     "vueI18n": {
>       "legacy": false,
>       "locale": 'zh-TW',
>       "messages": {
>         'zh-TW': require('./language/zh-TW.json'),
>         'en-US': require('./language/en-US.json'),
>         'ja-JP': require('./language/ja-JP.json'),
>       }
>     }
>   },
> ```
> 
> ```
> "nuxt": "^3.2.0",
> "@nuxtjs/i18n": "^8.0.0-beta.10",
> ```
> 
> ERROR
> 
> ```
>  Cannot restart nuxt:  Converting circular structure to JSON
>     --> starting at object with constructor 'Object'
>     --- property 'default' closes the circle
> 
>   --> starting at object with constructor 'Object'
>   --- property 'default' closes the circle
> ```
> 
> How should I solve it?

this is my solution


/* NUXT CONFIG.JS */
import langTr from './lang/tr'
vueI18n: {
  messages: {
    tr: langTr
  },
},

/* JS FILE */
export default JSON.parse(
  JSON.stringify({
    "Merhaba":"Merhaba"
  })
)

**Comment by paramula** [comment]
> HI~ I also encountered the same problem, I just imported JSON and this error appeared.
> 
> ```js
> "i18n": {
>     "vueI18n": {
>       "legacy": false,
>       "locale": 'zh-TW',
>       "messages": {
>         'zh-TW': require('./language/zh-TW.json'),
>         'en-US': require('./language/en-US.json'),
>         'ja-JP': require('./language/ja-JP.json'),
>       }
>     }
>   },
> ```
> 
> ```
> "nuxt": "^3.2.0",
> "@nuxtjs/i18n": "^8.0.0-beta.10",
> ```
> 
> ERROR
> 
> ```
>  Cannot restart nuxt:  Converting circular structure to JSON
>     --> starting at object with constructor 'Object'
>     --- property 'default' closes the circle
> 
>   --> starting at object with constructor 'Object'
>   --- property 'default' closes the circle
> ```
> 
> How should I solve it?
this is my solution

`
/* NUXT CONFIG.JS */
import langTr from './lang/tr'
vueI18n: {
messages: {
tr: langTr
},
},

/* JS FILE */
export default JSON.parse(
JSON.stringify({
"Merhaba":"Merhaba"
})
)`

**Comment by paramula** [comment]
> HI~ I also encountered the same problem, I just imported JSON and this error appeared.
> 
> ```js
> "i18n": {
>     "vueI18n": {
>       "legacy": false,
>       "locale": 'zh-TW',
>       "messages": {
>         'zh-TW': require('./language/zh-TW.json'),
>         'en-US': require('./language/en-US.json'),
>         'ja-JP': require('./language/ja-JP.json'),
>       }
>     }
>   },
> ```
> 
> ```
> "nuxt": "^3.2.0",
> "@nuxtjs/i18n": "^8.0.0-beta.10",
> ```
> 
> ERROR
> 
> ```
>  Cannot restart nuxt:  Converting circular structure to JSON
>     --> starting at object with constructor 'Object'
>     --- property 'default' closes the circle
> 
>   --> starting at object with constructor 'Object'
>   --- property 'default' closes the circle
> ```
> 
> How should I solve it?

    this is my solution

/* NUXT CONFIG.JS */
`
import langTr from './lang/tr'
vueI18n: {
messages: {
tr: langTr
},
},

/* JS FILE */
`
export default JSON.parse(
JSON.stringify({
"Merhaba":"Merhaba"
})
)
`

**Comment by mahmutatmaca** [comment]
> HI~ I also encountered the same problem, I just imported JSON and this error appeared.
> 
> ```js
> "i18n": {
>     "vueI18n": {
>       "legacy": false,
>       "locale": 'zh-TW',
>       "messages": {
>         'zh-TW': require('./language/zh-TW.json'),
>         'en-US': require('./language/en-US.json'),
>         'ja-JP': require('./language/ja-JP.json'),
>       }
>     }
>   },
> ```
> 
> ```
> "nuxt": "^3.2.0",
> "@nuxtjs/i18n": "^8.0.0-beta.10",
> ```
> 
> ERROR
> 
> ```
>  Cannot restart nuxt:  Converting circular structure to JSON
>     --> starting at object with constructor 'Object'
>     --- property 'default' closes the circle
> 
>   --> starting at object with constructor 'Object'
>   --- property 'default' closes the circle
> ```
> 
> How should I solve it?


this is my solution

/* NUXT CONFIG.JS */

```
import langTr from './lang/tr'
vueI18n: {
  messages: {
   tr: langTr
  },
}
```


/* JS FILE */
```
export default JSON.parse(
  JSON.stringify({
    "Merhaba":"Merhaba"
  })
)
```

**Comment by kazupon** [comment]
Close in-activity.
If you have still the issue, please you will open new issue.
Thanks!
