### ISSUE TITLE
Can't navigate to page with `defineI18nRoute(false)`

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt-modules/i18n#1889]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.6.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-c377bi?file=app.vue

### Describe the bug

If the page component has `defineI18nRoute(false)` it is not possible to navigate to this page on the client side.

I would expect that I can visit that page (URL has no lang prefix), and after returning to another (localized), I will still have the original language set.

**Comment by kazupon** [comment]
This issue has been fixed.
You can install the edge channel version.
Thanks!

**Comment by kazupon** [comment]
re-open, I've reverted this PR.
https://github.com/nuxt-modules/i18n/pull/2153

**Comment by lukaszflorczak** [comment]
Hi @kazupon! 

What is the current situation of this issue? Unfortunately, this bug disqualifies beta.13 for me 😔

**Comment by kazupon** [comment]
Oops. I'll work on this issue!

**Comment by saifobeidat** [comment]
this is happening with me as well,. did you find any workaround?

or is there any version that doesn't have this issue?

**Comment by lukaszflorczak** [comment]
@saifobeidat At this moment I use `8.0.0-beta.12`

**Comment by kazupon** [comment]
@lukaszflorczak 
Hi!
I fixed this issue, so you can try to install edge channel version.
Happy coding!
