### ISSUE TITLE
next - beta-10: type issue with nuxt config 

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/i18n#1891]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.2`
- CLI Version:      `0.1.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `modules`, `devtools`, `build`, `vite`
- Runtime Modules:  `@nuxt/devtools@0.1.4`, `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/tailwindcss@6.4.1`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ymxb49?file=nuxt.config.ts,package.json,lang%2Ffr-FR.json

### Describe the bug

There's an issue when using the `no_prefix` strategy. Seems like the messages key is not accepted within `i18n` property. However moving the `i18n` within a module array remove the type warning.

**Comment by kazupon** [comment]
Thank you for your reporting!

You need to set `messages` options in `i18n.vueI18n`, not `i18n.messages`.
Thanks!

**Comment by huang-julien** [comment]
ah yes ... I'm so blind :neutral_face: ... a bit strange to not have the type issue on the first one
