### ISSUE TITLE
Roll back to just before the class was executed after a refresh in the development environment

### ISSUE THREAD

**Issue by dungsil** [nuxt-modules/i18n#1893]
### Environment

```

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.7.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `srcDir`, `experimental`, `modules`, `css`, `i18n`, `unocss`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `@unocss/nuxt@0.50.1`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://github.com/dungsil/nuxt3-starter-template/

### Describe the bug

If you run the development server (`nuxi dev`), change the code, and then refresh the page, the web page rolls back to just after the development server was run, or does not reload properly after the change.

The problem occurs after the i18n module is enabled, so it is expected to be a problem with the i18n module.

### Additional context

https://user-images.githubusercontent.com/39783731/221768476-646f67cd-8d9e-4d0f-bb53-b15a5a1bb1b3.mp4

### Logs

```shell
no log
```

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortuantely, I could not reproduce your repo.
We need reproduce fully step.
Could you give it to us please?

**Comment by dungsil** [comment]
Hello @kazupon,

I checked with the same source (`dungsil/nuxt3-starter-template`), but the same was reproduced on another PC.

This is the information of the tested PC.
```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `pnpm@7.14.2`
- Builder:          `vite`
- User Config:      `srcDir`, `experimental`, `nitro`, `app`, `modules`, `vueuse`, `colorMode`, `i18n`, `unocss`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/color-mode@3.2.0`, `@vueuse/nuxt@9.12.0`, `@unocss/nuxt@0.50.0`
- Build Modules:    `-`
------------------------------
```

The test I did is below.
1. `git clone https://github.com/dungsil/nuxt3-starter-template.git`
2. `cd nuxt3-starter-template`
3. `pnpm install`
4. `pnpm dev`
6. (When the build is complete) Open `src/pages/index.vue` file
7. add `bg-green` class
8. browser refresh
9. `bg-green` class disappears from browser

**Comment by kazupon** [comment]
Unfortunately, I could not reproduce this issue. 😞 

I do not know what is causing this.
I think you should first isolate if this problem occurs before setting up the nuxt i18n module.

**Comment by dungsil** [comment]
Hello @kazupon,
I've done some testing and it's fine when each module is used alone, but it seems to happen when `@unocss/nuxt` and `@nuxt/i18n` are used together. 

I think it's an issue with generating CSS in UnoCSS, so I'll close the issue.
