### ISSUE TITLE
`useLocaleHead` and `useHead`: duplicate SeoAttributes head content being added

### ISSUE THREAD

**Issue by AnzhiZhang** [nuxt-modules/i18n#1899]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-orzjqc

### Describe the bug

When using `useLocaleHead` and `useHead` with addSeoAttributes in <script setup>, duplicate head link and meta have being added.
Also `hid` attribute seems have not being added.
![image](https://user-images.githubusercontent.com/37402126/222273113-47536dec-9119-4cd0-9ac4-c2a4db786d6b.png)

**Comment by kazupon** [comment]
Thank you for your reporting!

I seem that this issue is on `useHead`.

To isolate, I tried with stackbrliz.
https://stackblitz.com/edit/github-orzjqc-p75dte?file=app.vue

I can confirm there that `useLocaleHead` is not outputting duplicate values.

**Comment by AnzhiZhang** [comment]
But your example does not add i18n head in to the document.
![image](https://user-images.githubusercontent.com/37402126/222836003-7dc63c24-9ce8-4896-9792-3fc0f1b9258a.png)

**Comment by kazupon** [comment]
I mean that my stackbliz example says `useLocaleHead` returns the correct value.
This issue occurs when that value is passed to `useHead`, so I think `useHead` has the issue.

**Comment by AnzhiZhang** [comment]
I see, thank you
