### ISSUE TITLE
Doesn't read the locales folder

### ISSUE THREAD

**Issue by ennioVisco** [nuxt-modules/i18n#1900]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@3.4.1`
- Builder:          `vite`
- User Config:      `extends`, `ssr`, `routeRules`, `runtimeConfig`, `typescript`, `css`, `i18n`, `modules`, `alias`, `vite`
- Runtime Modules:  `nuxt-icon@^0.3.2`, `@nuxtjs/i18n@8.0.0-beta.10`, `@vueuse/nuxt@9.13.0`, `@nuxt/devtools@0.2.5`
- Build Modules:    `-`
------------------------------

### Reproduction

~~- Create a `locales` dir and add a file `en.yml` with a text line used in the app.~~
https://stackblitz.com/edit/github-ev7oxu?file=nuxt.config.ts

### Describe the bug

Contrary to what `@intlify/nuxt3` was doing, `@nuxtjs/i18n` doesn't read the `./locales` folder by default, nor it allows to define a `localeDir`.

Possibly related to https://github.com/nuxt-modules/i18n/issues/1890.

**Comment by BobbieGoede** [comment]
The directory can be set using the `langDir` key, it's a bit hidden in the docs as it's described on the options page for lazy loading [here](https://v8.i18n.nuxtjs.org/options/lazy#langdir).

So you probably want to do the following, if you haven't changed the `srcDir`, this config will resolve to `./locales`.
```ts
// nuxt.config inside your config
i18n: {
  langDir: 'locales',
}
```

The docs doesn't mention this, but `langDir` is relative to the `srcDir` of your project as seen here.
https://github.com/nuxt-modules/i18n/blob/045d7e6bd45f38b77d61f1c280637892dd68f0d0/src/module.ts#L67

**Comment by ennioVisco** [comment]
> 
Well, I tried, but it gives the following error:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/740025/222762135-cb73b7e3-e12e-4758-9e4d-cc5bec7a7a51.png">

**Comment by kazupon** [comment]
Thank you for your reporting!
Could you give us your minimal repo or stackbliz please?

**Comment by ennioVisco** [comment]
> ```ts
> i18n: {
>   langDir: 'locales',
> }
> ```

Updated the issue with the stackblitz link!

**Comment by ennioVisco** [comment]
> Thank you for your reporting! Could you give us your minimal repo or stackbliz please?

Updated the issue with the reproduction link!

**Comment by BobbieGoede** [comment]
You need to configure which locales and files are to be used by the module as the error message notes, this is done in a list of object on key `locales` (read more about it in the docs [here](https://v8.i18n.nuxtjs.org/guide/lazy-load-translations#basic-usage)).

If you change your i18n config to the following it should all work as expected.
```ts
i18n: {
    langDir: 'locales',
    locales: [{ code: 'en', file: 'en.yml' }],
},
```

Check out the guides in the docs for more info, if anything is unclear perhaps we may be able to improve the docs.

**Comment by ennioVisco** [comment]
> You need to configure which locales and files are to be used by the module as the error message notes, this is done in a list of object on key `locales` (read more about it in the docs [here](https://v8.i18n.nuxtjs.org/guide/lazy-load-translations#basic-usage)).
> 
> If you change your i18n config to the following it should all work as expected.
> 
> ```ts
> i18n: {
>     langDir: 'locales',
>     locales: [{ code: 'en', file: 'en.yml' }],
> },
> ```
> 
> Check out the guides in the docs for more info, if anything is unclear perhaps we may be able to improve the docs.

Thanks a lot, it works! But then I have two observations:

### All these information are missing in the migration guide from `@intlify/nuxt3`, namely:

- `localeDir` renamed to `langDir`
- `langDir` not having `locales` as default
- `locales` that must be explicitly set and is not derived automatically

### Design perspective
I think the fact that these must be set explicitly makes perfect sense, however, I think it previously was more in line with the zero-config philosophy of nuxt, where there is a "magic" folder already set (be it `i18n`, `locales` or something else), just like nuxt does with `components`, `composables`, `pages`, `content`, etc., and where the default config possibly already satisfies "realistic" base cases (e.g. when `locales` is not set, it automatically derives `locales: [{ code: 'en', file: 'en.yml' }]`).

**Comment by ennioVisco** [comment]
Addressed in https://github.com/nuxt-modules/i18n/pull/1921.
