### ISSUE TITLE
Cannot set default locale by `switchLocalePath()`

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt-modules/i18n#1905]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.6.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

https://github.com/lukaszflorczak/nuxt-i18n-playground

### Describe the bug

If the `prefix_except_default` strategy is set is not possible to set the default locale (`en` in my example) by `switchLocalePath('en')`. 

https://user-images.githubusercontent.com/1818979/222671433-a67c97b4-375f-4907-a39d-388c8bf7d05e.mov

**Comment by BobbieGoede** [comment]
It seems like `alwaysRedirect` prevents navigation to `/` when the redirect cookie has been set to something other than the default/fallback language. I made a workaround by changing the default behavior of `NuxtLink`, setting the cookie and navigating via a function, while keeping the anchor tag for SEO. 

You can find that here https://stackblitz.com/edit/nuxt-starter-ynybkp?file=app.vue,nuxt.config.ts

**Comment by BobbieGoede** [comment]
After updating the dependencies in your reproduction I am unable to replicate the issue, closing this as it seems to have been fixed 😅. Reproduction with updated deps [here](https://stackblitz.com/edit/lukaszflorczak-nuxt-i18n-playground-u6zacv?file=package.json).

Let me know if you're still experiencing this issue with the latest version, will reopen this in that case!
