### ISSUE TITLE
useCookieLocale composable does not work

### ISSUE THREAD

**Issue by BobbieGoede** [nuxt-modules/i18n#1907]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-g6uubx?file=app.vue,pages%2Ftest1.vue,pages%2Ftest2.vue

### Describe the bug

Trying to use `useCookieLocale` throws an error `Cannot read properties of undefined (reading 'useCookie')`. It seems like the parameter default values for the composable are not being set. 

See here: https://github.com/nuxt-modules/i18n/blob/182098bebc9cb8c952ec849333c133c920288048/src/runtime/composables.ts#L165-L166

By passing the parameters myself I get a bit further `useCookieLocale({ useCookie: true, cookieKey: 'i18n_redirected' });` except this time I get the following error `ReferenceError: ref is not defined`. 

That's here: https://github.com/nuxt-modules/i18n/blob/182098bebc9cb8c952ec849333c133c920288048/src/runtime/composables.ts#L172

### Additional context

I ran into this issue while trying to create a workaround for #1905

**Comment by issenn** [comment]
Error `ReferenceError: ref is not defined.` still exists.

**Comment by BobbieGoede** [comment]
@issenn ~~can you reproduce the error using the `next` branch? It should be fixed but I don't think the latest release `@nuxtjs/i18n@8.0.0-beta.10` includes this change yet.~~

Actually, after testing with `@nuxtjs/i18n-edge` it seems like that error does still exist.
