### ISSUE TITLE
Allow defining `baseUrl` via `runtimeConfig`

### ISSUE THREAD

**Issue by TheAlexLichter** [nuxt-modules/i18n#1908]
### Describe the feature

Hey all 👋 

Right now, you can only hardcode the baseUrl via `nuxt.config.ts`. To change it per deploy (without rebuild), using `runtimeConfig` as additional source would be great.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by BobbieGoede** [comment]
I haven't tested changing it after build but this may be possible this way:

```ts

export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      i18n: {
        baseUrl: 'https://example.com',
      },
    },
  },
  modules: ['@nuxtjs/i18n'],
  i18n: {
    baseUrl: () => {
      const config = useRuntimeConfig();
      return config?.public.i18n?.baseUrl ?? '';
    },
    // .. other config
}
```

Passing the env variable to update the config seems to work, here is a working example https://stackblitz.com/edit/github-kvjw8r?file=nuxt.config.ts,app.vue,package.json

**Comment by TheAlexLichter** [comment]
@BobbieGoede I built a similar workaround by using the provided context 😄 

That should indeed work fine as the fn is executed during runtime, but a more straightforward implementation wouldn't hurt either I suppose ☺️
