### ISSUE TITLE
Optional route params get merged into one

### ISSUE THREAD

**Issue by Bcavez** [nuxt-modules/i18n#1910]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `modules`, `i18n`, `algolia`, `unocss`, `typescript`, `image`, `runtimeConfig`, `css`, `vite`, `build`, `app`
- Runtime Modules:  `@nuxtjs/i18n-edge@8.0.0-beta.10-27955677.afd9ab2`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@vueuse/nuxt@9.6.0`, `@unocss/nuxt@0.47.5`, `~/modules/purge-comments`, `@nuxtjs/algolia@1.5.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-6n61vd?file=nuxt.config.ts

### Describe the bug

When using optional route params and nuxti18n to translate the route, the optional params get merged into one single param.

Considering the following directory:
![image](https://user-images.githubusercontent.com/52085295/223102216-eb3d2342-ea54-40d1-94b3-31ac2ffcda73.png)
And the following route translations:
    pages: {
        'products/[[category]]/[[subcategory]]/index': {
            en: '/products/[[category]]/[[subcategory]]',
            fr: '/produits/[[category]]/[[subcategory]]',
            de: '/produkte/[[category]]/[[subcategory]]'
        },
        'products/[category]/[subcategory]/[slug]': {
            en: '/products/[category]/[subcategory]/[slug]',
            fr: '/produits/[category]/[subcategory]/[slug]',
            de: '/produkte/[category]/[subcategory]/[slug]'
        }
    }

If I navigate to /en/products/some-category/some-subcategory, I expect to see this on my route params:
params: { "category": "some-category", "subcategory":  "some-subcategory"}
Instead I get a 404.

If I navigate to /en/products/some-category, I expect to see this on my route params:
params: { "category": "some-category" }
Instead what I have is this:
params: { "categorysubcategory": "some-category" }

As you can see both optional params are merged.

This is not the case for non-optional params, everything is fine if you go to /en/products/some-category/some-subcategory/some-slug

**Comment by BrutCZE** [comment]
Same here. Can someone please take look at this?

**Comment by JakubGoldbricht** [comment]
its a BIG problem, can u please try to fix it ?:)

**Comment by patrob1** [comment]
I have the same problem, it basically makes the package unusable for me :( Can someone take a look at this please?
