### ISSUE TITLE
Absolute `langDir` path isn't validated/resolved correctly

### ISSUE THREAD

**Issue by Ni55aN** [nuxt-modules/i18n#1913]
### Environment

https://stackblitz.com/edit/github-wfnczp-7tzsju?file=nuxt.config.ts

### a. Dev mode

```
npm run dev
```

✔ The page contains
```
Hello!

Welcome issue
```

### b. Build

```bash
npm run build 
node .output/server/index.mjs
 ```
 
 Open preview page with disabled JS
 
❌ The page contains
```
hello

welcome
```
It indicates that the translations were not loaded at all

### c. Generate

```bash
npm run generate
npx serve .output/public/
 ```

❌ The page contains:

```
Hello!

Welcome {name}
```
Translations are loaded at `generate`, but interpolation doesn't work correctly

### Describe the bug

First of all, at build stage `langDir: '/locales'` is accepted. Looks like it isn't recognized as an absolute path because somewhere `join` is used instead of `resolve`.

When I specify `resolve('locales')`, it throws an error `Could not resolve "../home/username/i18n-interpolation-issue/locales/en.json" from ".nuxt/i18n.options.mjs"`

### Additional context

The most confusing things are"

- regular message is translated correctly on the client side (with enabled JS, after hydration) or after `npm run generate`, but not message with interpolation. 
- everything works fine while development (`npm run dev`)

**Comment by BobbieGoede** [comment]
`langDir` is resolved relative to `srcDir`, your project should work with `langDir: 'locales'`. I think the docs probably need to explain this.

For reference:
https://github.com/nuxt-modules/i18n/blob/029c634be73ee39942770b3d174f2130b333f24e/src/module.ts#L67

**Comment by Ni55aN** [comment]
@BobbieGoede in this case `langPath` must be equal to `langDir` if `langDir` is an absolute path.

```js
p.resolve('/path/to/project', '/locales') === '/locales'
```

But in dev mode and during `generate` it correctly extracts locales from `/path/to/project/locales`

**Comment by BobbieGoede** [comment]
@Ni55aN 
> ```ts
> p.resolve('/path/to/project', '/locales') === '/locales'
> ```

I think that's the issue, as the following is what happens when passing a relative path. 
```ts
p.resolve('/path/to/project', 'locales') === '/path/to/project/locales'
p.resolve('/path/to/project', './locales') === '/path/to/project/locales'
```

I'm not sure why it does work in dev mode however.

**Comment by Ni55aN** [comment]
Probably the issue is that `generateLoaderOptions` accepts unresolved options.langDir

https://github.com/nuxt-modules/i18n/blob/029c634be73ee39942770b3d174f2130b333f24e/src/module.ts#L145-L148

which is "resolved" inside by `resolveLocaleRelativePath`

https://github.com/nuxt-modules/i18n/blob/029c634be73ee39942770b3d174f2130b333f24e/src/gen.ts#L171-L173
