### ISSUE TITLE
Random empty string

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/i18n#1918]
### Environment

Nuxi 3.2.3                                                                                                        10:32:35
                                                                                                                  10:32:36
RootDir: /home/projects/nuxt-starter-zlr4ir                                                                       10:32:36
Nuxt project info:                                                                                                10:32:36

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/i18n-edge@8.0.0-beta.9-27948515.3db6367`, `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       10:32:36

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zlr4ir

### Describe the bug

When i force refresh (CTRL + F5) in same ocasions (random) the translated string is empty

![image](https://user-images.githubusercontent.com/77386602/223980593-0b0bfb02-8097-498d-8ed5-16a22fa6f6d4.png)
![image](https://user-images.githubusercontent.com/77386602/223980659-f696996f-5b0c-4961-a0ee-89098840cc3c.png)

**Comment by ineshbose** [comment]
I'm unable to replicate the issue on the stackblitz, but I do want to point out that there are 2 versions of the module, and the `useTranslation` composable logic that can rather use `useI18n` (though not necessary, but may make a difference)

**Comment by kazupon** [comment]
Thank you for your reporting!

>but I do want to point out that there are 2 versions of the module,

I thought so as well.
I could not understand why you are installing different versions.
i18n module is not designed to work that way.

**Comment by agracia-foticos** [comment]
Solved!
