### ISSUE TITLE
Functional component not working

### ISSUE THREAD

**Issue by ennioVisco** [nuxt-modules/i18n#1922]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@3.4.1`
- Builder:          `vite`
- User Config:      `extends`, `ssr`, `routeRules`, `runtimeConfig`, `css`, `i18n`, `modules`, `alias`, `vite`
- Runtime Modules:  `nuxt-icon@^0.3.2`, `@nuxtjs/i18n@8.0.0-beta.10`, `@vueuse/nuxt@9.13.0`, `@nuxt/devtools@0.2.5`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-gnsutb?file=nuxt.config.ts

### Describe the bug

It seems that the `<i18n>` functional component from `vue-i18n` (https://kazupon.github.io/vue-i18n/api/#i18n-functional-component) is not working with this module.

**Comment by kazupon** [comment]
Thank you for your reporting!
`i18n` component has deprecated from vue-i18n v9.
you need to renane to `i18n-t` from `i18n`
breaking changeing docs is here
https://vue-i18n.intlify.dev/guide/migration/breaking.html#rename-to-i18n-tfrom-i18n

nuxt i18n module is using that version.

Thanks!

**Comment by ennioVisco** [comment]
> Thank you for your reporting! `i18n` component has deprecated from vue-i18n v9. you need to renane to `i18n-t` from `i18n` breaking changeing docs is here https://vue-i18n.intlify.dev/guide/migration/breaking.html#rename-to-i18n-tfrom-i18n
> 
> nuxt i18n module is using that version.
> 
> Thanks!

thanks a lot, I missed it! But then, the docs should be saying that it's deprecated here: https://kazupon.github.io/vue-i18n/api/#i18n-functional-component !!
