### ISSUE TITLE
Different domains not working

### ISSUE THREAD

**Issue by MmKargar** [nuxt-modules/i18n#1937]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/multidomain-lang?file=nuxt.config.ts

### Describe the bug

I'm trying to load different languages for different domains, but it's not working when I test it in production. I followed the documentation, but I might be doing something wrong. Here's my nuxt.config.ts file:
```javascript
export default defineNuxtConfig({
    ssr: true,
    css: ["~/assets/css/app.scss"],
    modules: ['@pinia/nuxt', '@nuxtjs/tailwindcss', '@nuxtjs/i18n'],
    i18n: {
        differentDomains: true,
        detectBrowserLanguage: false,
        defaultLocale: 'fa',
        locales: [
            {
                code: 'fa',
                domain: 'https://example.de'
            },
            {
                code: 'en',
                domain: 'https://example.io'
            }
        ]
    }
})
```

When I log the language code in my app, it returns the wrong code for each domain:
```javascript
<script setup>
    const { locale } = useI18n()
    console.log(locale)
</script>
```

Please check out the Reproduction link and let me know if you can help. Thank you!

**Comment by sahmadreza** [comment]
@kazupon @Tahul @ineshbose  I have same issue

**Comment by kazupon** [comment]
Hi!
Thank you for your reproduction.

Unfortunately, I could not reproduce this issue.
In my enviroments, `locale` is correctly value for each domain.
so, when I try to access to localhost:3060, `locale` return `fr`.
and access to localhost:3050, `locale` return `en`

**Comment by MmKargar** [comment]
Hi, thanks for your attention and sorry for late response.
Base on this code 
```javascript
    locales: [
      {
        code: 'en',
        domain: 'http://localhost:3060',
      },
      {
        code: 'fr',
        domain: 'http://localhost:3050',
      },
    ],
```
When you try to access `localhost:3060` you should get the `en` not `fr`.
Please take a look at this picture, I served it on `localhost:3050` and it should return the `fr` code and the `Bienvenue` word instead of `Welcome` but it's loaded on english.

![Screenshot from 2023-03-25 11-13-13](https://user-images.githubusercontent.com/11253027/227704869-d734fdaa-2bca-432e-a620-9ad5b4c56a7e.png)


Once again, thank you for your help and prompt response.

**Comment by Eddie344** [comment]
@MmKargar Hi! I think this happens because domains have protocols. A good question why it's not working, because docs example has protocol. 
And it's not work on stackblitz because there is another link (not localhost)
![image](https://user-images.githubusercontent.com/53879350/227855410-c0f4391b-4ce6-4bc7-b8f0-961560d70b24.png)

**Comment by MmKargar** [comment]
Hi @Eddie344,

Thank you for taking the time to respond. I appreciate your input.

You are correct about Stackblitz. I tested it multiple times on actual domains and it didn't seem to work, but now it appears to be working. I am not sure why this is the case, but your response encouraged me to try again. Thank you again for your help!

And, @kazupon, thank you as well for your assistance with this issue.

Best regards.

**Comment by studentofcoding** [comment]
Hi @MmKargar, could you share where you deploy the site? and is it a full SSR or Client side? thanks

**Comment by MmKargar** [comment]
Hi @studentofcoding 
https://codetrend.ir
https://codetrend.io
Its full SSR.

**Comment by studentofcoding** [comment]
Hmm interesting @MmKargar

We’ve using full SSR aswell but isn’t working in my case

Could you share the nuxt config for these? Thanks

**Comment by MmKargar** [comment]
Sure.

`nuxt.config.ts`
```javascript
import i18nConfig from './i18n.config';

export default defineNuxtConfig({
    ssr: true,
    ...
    i18n: i18nConfig,
    ...
})

```

`i18n.config.js`
```javascript
export default {
    differentDomains: true,
    detectBrowserLanguage: false,
    defaultLocale: 'fa-IR',
    lazy: true,
    langDir: 'lang/',
    locales: [
      {
        code: 'fa-IR',
        domain: 'codetrend.ir',
        full_url: 'https://codetrend.ir',
        file: 'fa.js',
        dir: 'rtl',
        name: 'persian',
      },
      {
        code: 'en-US',
        domain: 'codetrend.io',
        full_url: 'https://codetrend.io',
        file: 'en.js',
        dir: 'ltr',
        name: 'english',
      },
    ],
  };
  
```
