### ISSUE TITLE
pn

### ISSUE THREAD

**Issue by TomMiller-mas** [nuxt-modules/i18n#1944]
### Environment

node 16.15
nuxt 3.3

### Reproduction

C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-appv2>pnpm install --shamefully-hoist -D @nuxtjs/i18n@next
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
Already up to date
Progress: resolved 627, reused 584, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
└─┬ @nuxtjs/i18n 8.0.0-beta.10
  ├─┬ vue-i18n 9.3.0-beta.16
  │ └── ✕ missing peer vue@^3.0.0
  └─┬ vue-i18n-routing 0.12.2
    ├── ✕ missing peer vue@"^2.6.14 || ^2.7.0 || ^3.2.0"
    └─┬ @intlify/vue-router-bridge 0.8.0
      └─┬ vue-demi 0.13.11
        └── ✕ missing peer vue@"^3.0.0-0 || ^2.6.0"
Peer dependencies that should be installed:
  vue@">=3.2.0 <4.0.0"

### Describe the bug

Try to install on a fresh install of nuxt 3.3 project 
I used the code below to stub out the project. 

       pnpm dlx nuxi init <project-name>

**Comment by ineshbose** [comment]
Sorry - I'm unable to understand your issue. Is it just the warnings from pnpm? Those can be ignored (or resolved using `package.json` if you really want).

**Comment by TomMiller-mas** [comment]
OK, I figured if there was a dependency, it would install it. I can install VUE 3.x.  Maybe update the install instruction. Perhaps that is obvious for long-time node/javascript users, but I am new to the Ecosystem.
