### ISSUE TITLE
Method missing is not working

### ISSUE THREAD

**Issue by MissedWarrior** [nuxt-modules/i18n#1946]
### Environment

Nuxt project info: 

------------------------------                                                                                                                                                                                                  
- Operating System: `Linux`
- Node Version:     `v18.14.2`
- Nuxt Version:     `2.16.3`
- Nitro Version:    `-`
- Package Manager:  `npm@9.5.0`
- Builder:          `webpack`
- User Config:      `ssr`, `components`, `buildModules`, `modules`, `i18n`, `axios`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/i18n@7.3.1`
- Build Modules:    `@nuxt/typescript-build@3.0.0`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xohe6a

To reproduce the bug simply set your language to anything else than english(and add that locale to locales list) and open console

Expected behaviour:
There is a log in console with locale name

Current behaviour:
Default warning about missing translation

### Describe the bug

I'm trying to setup custom logger for missing translations but it seems that method `missing` doesn't do anything. I tried it both on my local computer with typescript and on stackblitz without typescript but I couldn't make it works

**Comment by ineshbose** [comment]
Where is `missing` being used? 😅 

For `vue-i18n` configuration you can see: https://kazupon.github.io/vue-i18n/ or https://vue-i18n.intlify.dev/guide/essentials/syntax.html#custom-modifiers

Edit: found it - https://kazupon.github.io/vue-i18n/api/#missing

**Comment by MissedWarrior** [comment]
yeah, I also found it in api section(and in typescript declarations) but there are no any mentions of it in the guide

**Comment by MissedWarrior** [comment]
I checked the `missing` handler in the standalone Vue 2 project(version `8.28.2` and without Nuxt) and it works but default warnings are still in the console which is not aligned with the docs(as far as I understand)

**Comment by MissedWarrior** [comment]
After some digging I found that `context.i18n._missing` is equal to null so I think there might be a problem with options merging. If I assign `context.i18n._missing` to some fn, it works correctly(but still produces default warning in console)

**Comment by MissedWarrior** [comment]
Gotcha! The problem is [here](https://github.com/nuxt-modules/i18n/blob/main/src/templates/options.js#L32). JSON.stringify kills all methods so thats why `missing` handler equals to null

**Comment by ineshbose** [comment]
Incredible investigation! Thanks for the notes. It seems that would continue to be the case as we're currently looking into doing away with functions from the config for v8 safely somehow. For now what I could suggest is creating a Nuxt plugin based on the logic and your configuration passed in directly to VueI18n.

**Comment by MissedWarrior** [comment]
Oh, I see. If you want to drop functions from the config will there be any possibility to log missing translations? We want to send events to Sentry so if there will be no translation we could fix it asap.

Talking about workarounds. I found 2 approaches:
1) Add `missing` handler in a plugin
```ts
import { Context } from '@nuxt/types'

export default function (context: Context) {
    context.i18n.missing = (locale) => {
        console.log(locale)
    }
}
```

2) Much more convenient way with providing path to configuration

```ts
// nuxt-config.ts

const config = {
    // ...

    i18n: {
        // ...
        vueI18n: '~/plugins/i18n',
    },
}
```
```ts
// ~/plugins/i18n.ts
import type { Options } from '@nuxtjs/i18n'

export default function (): Options['vueI18n'] {
    return {
        fallbackLocale: 'en',
        missing(locale) {
            console.log(locale)
        },
    }
}
```
Note: it is not really a plugin, I placed this file there because it is simply comfortable for me. You can place it anywhere you want.

**Important note:** missing handler is only triggered when there is no translation at all. For example, if you have key `foo` in en locale but not in ja locale AND you have enabled `fallbackLocale` to en then there will be no trigger. Trigger will only occure if library didn't find any translation and displayed a key instead(for example, if you haven't enabled `fallbackLocale`).

**Comment by MissedWarrior** [comment]
I think this issue can be closed since I found the solution and figure out the behaviour. I'll close it tomorrow unless you want to do smth with it. Thanks for help!
