### ISSUE TITLE
[NEXT]Could not find en locale code in localeMessages

### ISSUE THREAD

**Issue by zenonux** [nuxt-modules/i18n#1947]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `experimental`, `app`, `css`, `postcss`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `nuxt-icons@3.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-6tlwl1?file=README.md

### Describe the bug

show "Could not find en locale code in localeMessages" waring only in production environment.it works fine in development environment
![image](https://user-images.githubusercontent.com/8474239/226506383-085dc481-fbcb-4cfa-89df-ff4fa91d553a.png)

**Comment by zenonux** [comment]
youi can run npm run preview to reproduce

**Comment by ineshbose** [comment]
I ran a build and then preview and I was not able to replicate it. Did you create a fresh build for your project?

**Comment by zenonux** [comment]
> I ran a build and then preview and I was not able to replicate it. Did you create a fresh build for your project?

![image](https://user-images.githubusercontent.com/8474239/226876481-0c59f17f-7804-4792-beb5-22375a97ba34.png)
![image](https://user-images.githubusercontent.com/8474239/226876624-d23e63f6-909c-4f79-9d19-9b5e8abc9313.png)

**Comment by ineshbose** [comment]
Maybe my browser configuration is causing this to pass..

**Comment by pont1s** [comment]
+1.
On server log:
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'welcome'.

This may be due to the format .ts locale file
