### ISSUE TITLE
defineI18nLocale is not defined

### ISSUE THREAD

**Issue by Eddie344** [nuxt-modules/i18n#1954]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

[stackblitz.com](https://stackblitz.com/edit/github-9airxq?file=app.vue)

### Describe the bug

After installing module and configure for work with lazy loaded messages, I have an error message:
`Failed locale loading: defineI18nLocale is not defined`
I check a dist folder in node_modules, there is no `defineI18nLocale` function export in `dist/runtime/composables.mjs`

### Logs

```shell
@nuxtjs/i18n Failed locale loading: defineI18nLocale is not defined 
```

**Comment by Eddie344** [comment]
So, I find it in edge version. I think it's worth mentioning somewhere in the documentation

**Comment by IvanWala** [comment]
I have the same problem than you with @nuxtjs/i18n@8.0.0-beta.10

When I try to use defineI18nLocale like this in langs/en-GB.js

> export default defineI18nLocale((context, locale) => {
>  // for example, fetch locale messages from nuxt server
>      return $fetch(`{{mi api url}}/api/language/i18n?locale=en-GB}`);
> }))

throws the error Failed locale loading: defineI18nLocale is not defined.

when i try to do this:

> export default () => {
>     return $fetch({{mi api url}}/api/language/i18n?locale=en-GB');
> };             

or this

> export default async() => {
>     return await $fetch({{mi api url}}/api/language/i18n?locale=en-GB');
> };              

throws another error:
@nuxtjs/i18n Not support executable file (e.g. js, cjs, mjs)

PD: {{my api url}} is a right url.

**Comment by Eddie344** [comment]
> I have the same problem than you with @nuxtjs/i18n@8.0.0-beta.10
> 
> When I try to use defineI18nLocale like this in langs/en-GB.js
> 
> > export default defineI18nLocale((context, locale) => {
> > // for example, fetch locale messages from nuxt server
> > return $fetch(`{{mi api url}}/api/language/i18n?locale=en-GB}`);
> > }))
> 
> throws the error Failed locale loading: defineI18nLocale is not defined.
> 
> when i try to do this:
> 
> > export default () => {
> > return $fetch({{mi api url}}/api/language/i18n?locale=en-GB');
> > };
> 
> or this
> 
> > export default async() => {
> > return await $fetch({{mi api url}}/api/language/i18n?locale=en-GB');
> > };
> 
> throws another error: @nuxtjs/i18n Not support executable file (e.g. js, cjs, mjs)
> 
> PD: {{my api url}} is a right url.

@IvanWala use this variant of installation
https://github.com/nuxt-modules/i18n#install-edge-version

**Comment by IvanWala** [comment]
Thanks @Eddie344. 

I removed "next" and added "edge",

Now the problem is different when i use this inside langs/en-GB.js it return an empty object

> export default defineI18nLocale((context, locale) => {
> // for example, fetch locale messages from nuxt server
> return $fetch({{mi api url}}/api/language/i18n?locale=en-GB});
> }))

But if you access to the langs by browser url the json is correct.

**Comment by kazupon** [comment]
Docs said:
>If the function returns an Object available in nuxt i18n module, you can configure the dynamic locale messages, like the API (including external API) or back-end, via fetch:

https://v8.i18n.nuxtjs.org/guide/lazy-load-translations

You need return the **object**.
your reproduction have returned `undefined` from external site with `$fetch`

Thanks.

**Comment by AlenDosev** [comment]
Why is this closed? I still have that error message. 
`@nuxtjs/i18n Failed locale loading: defineI18nLocale is not defined `
I tried installing the edge version, it didn't help. I am trying to do the example -> 
`export default defineI18nLocale(async (context, locale) => {
  return {
    welcome: 'Welcome'
  }
})`

From where do I import defineI18nLocale ?

**Comment by hahatulk** [comment]
> Why is this closed? I still have that error message. `@nuxtjs/i18n Failed locale loading: defineI18nLocale is not defined ` I tried installing the edge version, it didn't help. I am trying to do the example -> `export default defineI18nLocale(async (context, locale) => { return { welcome: 'Welcome' } })`
> 
> From where do I import defineI18nLocale ?

Same problem. Please help!

**Comment by hahatulk** [comment]
> Why is this closed? I still have that error message. `@nuxtjs/i18n Failed locale loading: defineI18nLocale is not defined ` I tried installing the edge version, it didn't help. I am trying to do the example -> `export default defineI18nLocale(async (context, locale) => { return { welcome: 'Welcome' } })`
> 
> From where do I import defineI18nLocale ?

Do `npm remove` first, without it edge will not be installed

**Comment by letoast** [comment]
> Why is this closed? I still have that error message. `@nuxtjs/i18n Failed locale loading: defineI18nLocale is not defined ` I tried installing the edge version, it didn't help. I am trying to do the example -> `export default defineI18nLocale(async (context, locale) => { return { welcome: 'Welcome' } })`
> 
> From where do I import defineI18nLocale ?

import { defineI18nLocale } from '#imports'
