### ISSUE TITLE
defineI18nRoute does not work

### ISSUE THREAD

**Issue by visko83** [nuxt-modules/i18n#1958]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `pages`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

nuxt.config.ts:
```
...
customRoutes: 'config',
    pages: {
      blog: {
        hu: '/jegyzet',
        en: '/blog',
      },
    },
```
pages/blog.vue exists and routing works for this page.

But routing defined in pages/agency.vue has no effect, /iroda cannot be found, agency.vue's content:
```
<script setup lang="ts">
defineI18nRoute({
  paths: {
    hu: '/iroda',
    en: '/agency',
  },
});
</script>
```
https://stackblitz.com/edit/github-w7smfy-beadgd

### Describe the bug

Paths defined in pages (`defineI18nRoute` in `<script setup>`) don't work, in the reproduction steps above /iroda or /en/agency goes to 404.

**Comment by icelandcruiser** [comment]
I had to remove **customRoutes: 'config'** from the nuxt.config.ts to use defineI18nRoute

**Comment by alexelker** [comment]
Did anyone solve this?

**Comment by BobbieGoede** [comment]
Sorry for the late response, `customRoutes` has to be set to `'page'` (which is the default) to be able to set paths using `defineI18nRoute`, see https://i18n.nuxtjs.org/options/routing#customroutes and https://i18n.nuxtjs.org/guide/custom-paths for more info.
