### ISSUE TITLE
Can't install edge version

### ISSUE THREAD

**Issue by smebrahimi** [nuxt-modules/i18n#1959]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@3.5.0`
- Builder:          `vite`
- Build Modules:    `-`

### Reproduction

I couldn't install it according to the document ([doc](https://nuxt.com/modules/i18n)),
I think it is because of the `yarn` used also I won't use `npm`
So I run the `yarn add @nuxtjs/i18n-edge`. like [here](https://openbase.com/js/@nuxtjs/i18n-edge/versions).

### Describe the bug

I need to install the edge version in my project, but I can't install it.

I have an error when installing:

<img width="779" alt="Screen Shot 2023-03-28 at 12 25 26 PM" src="https://user-images.githubusercontent.com/8133270/228184031-304b492c-2871-43de-ae19-9a52bc3723ce.png">

**Comment by smebrahimi** [comment]
I did it on an empty project and noticed a problem on the documentation for installing the edge version part.
First, run `yarn add @nuxtjs/i18n-edge` after that adds @nuxtjs/i18n-edge in modules of nuxt.config file instead of @nuxtjs/i18n and fixed it.

I think the documentation needs to update for this part.

<img width="400" alt="Screen Shot 2023-03-28 at 5 06 24 PM" src="https://user-images.githubusercontent.com/8133270/228256015-60329974-cba1-4272-b019-1f1c84d1ee1e.png">

**Comment by kazupon** [comment]
Thank you for your reporting!
Could you give us minimu reproduction with GitHub repo or stackblize please?

Issue guide line says:

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
>👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

**Comment by kazupon** [comment]
close due to no-active.
if you would have still issue, please open the new issue.
Thanks!
