### ISSUE TITLE
Nuxt3 uses lazy, when I modify the code, the hot update does not take effect

### ISSUE THREAD

**Issue by zzzhim** [nuxt-modules/i18n#1960]
### Environment

![image](https://user-images.githubusercontent.com/39826534/228223146-be5f2db7-54fa-4bc6-ba85-6f95c9edb59a.png)

### Reproduction

![image](https://user-images.githubusercontent.com/39826534/228221385-5575eb1c-dd65-437e-84cc-6860eed8c700.png)

### Describe the bug

I used "@nuxtjs/i18n": "^8.0.0-beta.10" in the project and configured lazy. I found that the modification in the language file will trigger the hot update, but when I modify the code, the hot update will not trigger.

我在项目中使用了"@nuxtjs/i18n": "^8.0.0-beta.10"，配置了lazy，我发现在语言文件中修改会触发热更新，但是我在修改代码时热更新不会触发。

**Comment by kazupon** [comment]
Thank you for your reporting!
Unfortunately, We could not reporoduce this issue.
Issue guideline says:

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
>👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

We need minimul reproduction. 🙏

**Comment by kazupon** [comment]
close due to non-active.
if you would have still issue, please open the new issue.
Thanks!
