### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by dexter-fabrikapp** [nuxt-modules/i18n#1962]
### Environment

"@nuxtjs/i18n": "next",
"nuxt": "^3.3.0",

### Reproduction

**Steps to reproduce**
1. yarn / yarn install
2. yarn dev

**What is Expected?**
yarn dev should work.

**What is actually happening?**
ERROR: Cannot restart nuxt: Cannot read properties of undefined (reading 'options')

### Describe the bug

ERROR: Cannot restart nuxt: Cannot read properties of undefined (reading 'options')

![image](https://user-images.githubusercontent.com/129273463/228487963-abc4934e-4b2a-4195-b3b4-3c9f8de643af.png)

**Comment by kazupon** [comment]
Thank you for your reporting!
Unfortunately, We could not reporoduce this issue.
Issue guideline says:

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
>👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

We need minimul reproduction. 🙏

**Comment by kazupon** [comment]
close due to non-active.
if you would have still issue, please open the new issue.
Thanks!
