### ISSUE TITLE
Spaces in YAML translation files with nuxt `srcDir` config

### ISSUE THREAD

**Issue by WolfgangDrescher** [nuxt-modules/i18n#1963]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `ssr`, `srcDir`, `modules`, `vite`, `nitro`, `googleFonts`, `i18n`, `content`, `plausible`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.4`, `@pinia/nuxt@0.4.7`, `@nuxtjs/google-fonts@3.0.0`, `nuxt-icon@0.3.3`, `@nuxtjs/i18n-edge@8.0.0-beta.10-27995650.c1d4ec9`, `@nuxt/content@2.5.2`, `@nuxtjs/plausible@0.2.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-rg81ao
https://stackblitz.com/edit/github-rg81ao-u5wrhd (without srcDir)

### Describe the bug

Updating from `8.0.0-beta.10-27985006.4ff543e` to `8.0.0-beta.10-27995650.c1d4ec9` it seems that strings with spaces are no longer accepted in YAML translation files when not wrapped into quotes:

```yaml
demoStringQuotes: 'String with spaces with quotes'
demoString: String with spaces
```

Run `npm run generate` in the [reproduction repo on StackBlitz](https://stackblitz.com/edit/github-rg81ao) to see how the build fails.

This seems to be related to the nuxt `srcDir` config. Without this everything works as expected. Compare with `npm run generate` in the [reproduction repo without srcDir](https://stackblitz.com/edit/github-rg81ao-u5wrhd).

### Logs

<img width="916" alt="Bildschirm­foto 2023-03-29 um 11 34 05" src="https://user-images.githubusercontent.com/865594/228494881-781149fe-9d56-412f-af9b-79a3c7b50f21.png">

**Comment by WolfgangDrescher** [comment]
I did test the recent npm edge releases. `8.0.0-beta.10-27993103.e65d8f2` works. `8.0.0-beta.10-27995650.c1d4ec9` fails.

See: https://github.com/nuxt-modules/i18n/compare/e65d8f2...c1d4ec9

**Comment by WolfgangDrescher** [comment]
It looks like `getLayerLangPaths` is missing `srcDir` in the path:

layers.ts

```ts
export const getLayerLangPaths = (nuxt: Nuxt) => {
  return (
    nuxt.options._layers
      .filter(layer => layer.config.i18n?.langDir != null)
      // @ts-ignore
      .map(layer => pathe.resolve(layer.config.rootDir, layer.config.i18n.langDir)) as string[]
  )
}
```

vs. module.ts

```ts
const langPath = isString(options.langDir) ? resolve(nuxt.options.srcDir, options.langDir) : null
```

But this does not yet solve the issue. When I add `srcDir` to the resolve method in `getLayerLangPaths` I get another error message from rollup instead:

```
[vite]: Rollup failed to resolve import "js-cookie" from "virtual:nuxt:~/.nuxt/i18n.internal.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by BobbieGoede** [comment]
Sorry! Looks like I introduced this bug, I have tried it locally and it seems to work when adding `srcDir` to `getLayerLangPaths` path resolving. 

I'm not sure why the quotes in yaml changes the behaviour though...

**Comment by WolfgangDrescher** [comment]
Maybe #1964 fixes the problem after all. Running this fix with `npm link` I got the `js-cookie` error message (not only in my project, but also in a fresh nuxt project). But when I edit this directly in `node_modules/@nuxtjs/i18n-edge/dist/module.mjs` is seems to work. No clue though how this should be related to `js-cookie` or YAML strings without quotes…
