### ISSUE TITLE
Cannot resolve langDir path

### ISSUE THREAD

**Issue by kleinpetr** [nuxt-modules/i18n#1966]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.0.0`
- Builder:          `vite`
- User Config:      `app`, `css`, `postcss`, `nitro`, `modules`, `i18n`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxt/devtools@0.3.1`

### Reproduction

https://stackblitz.com/edit/github-xyyk6u
```

### Describe the bug

I am getting this error

```
Failed to resolve import "../locales/en.json," from ".nuxt/i18n.options.mjs". Does the file exist? (x3)
```

### Additional context

I've tried to use resolver for the path and also absolute path, but nothing helped

### Logs

_No response_

**Comment by kazupon** [comment]
Thank you for your reporting!
Unfortunately, We could not reporoduce this issue.
Issue guideline says:

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
>👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

We need minimul reproduction. 🙏

**Comment by kleinpetr** [comment]
Ok I've updated it by https://stackblitz.com/edit/github-xyyk6u cc @kazupon

**Comment by kazupon** [comment]
Thank you for your reproduction!

I've checked it!
I've found out typo on i18n module options:

```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ['@nuxtjs/i18n'],
  i18n: {
    langDir: './locales',
    strategy: 'no_prefix',
    locales: [
      {
        code: 'en',
        iso: 'en',
        name: 'English',
        file: 'en.json,', // <-- comma ...
      },
      {
        code: 'cs',
        iso: 'cs',
        name: 'Czech',
        file: 'cs.json',
      },
    ],
    detectBrowserLanguage: {
      alwaysRedirect: false,
      fallbackLocale: 'en',
      redirectOn: 'all',
      useCookie: false,
    },
    vueI18n: {
      fallbackLocale: 'en',
    },
  },
});
```

**Comment by danielklein-arch** [comment]
I've tried removing the typo in stackblitz, but still got 404 error mentioned above.

**Comment by kleinpetr** [comment]
Thanks, it works now, there is now the last comma, but the comma inside the qutes. Thanks :+1:
