### ISSUE TITLE
useLocalePath remove query from string url

### ISSUE THREAD

**Issue by tung1998** [nuxt-modules/i18n#1967]
### Environment

node 18.15

### Reproduction

need reproduction

### Describe the bug

when i use localePath with parameter is stringUrl has query, return url is missing this query.
ex:   
 input url : /test-change-default-color-123/women's-standard-t-shirt?color=royal&size=xl 
 output url -  /test-change-default-color-123/women's-standard-t-shirt

**Comment by kazupon** [comment]
Thank you for your reproting!

> Environment
> node 18.15

We need more context enviroment information.
Could you do `npx nuxi info` and give us it please? 🙏 

And one more thing,  issue gudeline saying.

> Please use a template below to create a minimal reproduction, and provide to us your issue cases
> 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
> 👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Could you give us minimum reproduction please? 🙏

**Comment by kazupon** [comment]
close due to non-active.
if you would have still issue, please open the new issue.
Thanks!
