### ISSUE TITLE
Cannot disable warnHtmlMessage

### ISSUE THREAD

**Issue by memic84** [nuxt-modules/i18n#1970]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Just use some html tags in your locales values.

### Describe the bug

I have tried to add `warnHtmlMessage` and the other variant, to both the nuxt config i18n and vueI18n, but nothing changes, i keep ketting these errors

```
ERROR  [unplugin-vue-i18n]
```

This happend first when i switched to the edge version, on beta.9 this didn't happen. Has something changed in between?

**Comment by lukaszflorczak** [comment]
I have the same problem. The latest working version is `npm:@nuxtjs/i18n-edge@8.0.0-beta.10-27985006.4ff543e`

**Comment by memic84** [comment]
Same here, also haven't found anything in the last commits that could have caused this.
Also checkout out the source code, and no mention of the warnHtmlMessage or such.

My best guest, is that it's a option that gets passed to the VueI18n?

**Comment by kazupon** [comment]
I think you need to configure `precompile` option.
docs here:
https://v8.i18n.nuxtjs.org/options/misc#precompile

That option was supported in this commit
https://github.com/nuxt-modules/i18n/commit/c0b701c7ec36d2b1988defbf4e4079da7e011ba3#diff-a37a61944287c52dcb3c22edfe922d38fc02c80a592d903935f3fdfd683807ccR25

**Comment by memic84** [comment]
It works, thank you!

**Comment by letoast** [comment]
> I think you need to configure `precompile` option. docs here: https://v8.i18n.nuxtjs.org/options/misc#precompile
> 
> That option was supported in this commit [c0b701c#diff-a37a61944287c52dcb3c22edfe922d38fc02c80a592d903935f3fdfd683807ccR25](https://github.com/nuxt-modules/i18n/commit/c0b701c7ec36d2b1988defbf4e4079da7e011ba3#diff-a37a61944287c52dcb3c22edfe922d38fc02c80a592d903935f3fdfd683807ccR25)

You have changed this to a key called "compilation", "precompile" doesn't exist anymore.
https://v8.i18n.nuxtjs.org/options/compilation#strictmessage
