### ISSUE TITLE
@nuxtjs/i18n Failed locale loading: Unknown file extension ".ts"

### ISSUE THREAD

**Issue by margintopt** [nuxt-modules/i18n#1971]
### Environment

Nuxi 3.3.2                                                                                                                                                                                   
Nuxt project info:                                                                                                                                                                           11:29:15

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.8.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `css`, `build`, `typescript`, `vite`, `nitro`, `modules`, `i18n`, `pwa`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `nuxt-lodash@2.4.1`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `@nuxtjs/i18n@8.0.0-beta.10`, `@vite-pwa/n
uxt@0.0.7`
- Build Modules:    `-`
------------------------------

### Reproduction
```
i18n: {
    strategy: 'no_prefix',
    locales: [
      {
        code: 'en',
        name: 'English',
        file: 'en-US.ts',
      },
      {
        code: 'zh-CN',
        name: '简体中文',
        file: 'zh-CN.ts',
      },
      {
        code: 'zh-TW',
        name: '繁體中文',
        file: 'zh-TW.ts',
      },
    ],
    lazy: true,
    langDir: 'locales',
    defaultLocale: 'zh-TW',
  },
````

### Describe the bug

![image](https://user-images.githubusercontent.com/30163907/229015830-222f69e0-03f1-4af2-9185-f8e06510e837.png)

en-US.ts
```
import common from './en-US/common';
import item from './en-US/item';

export default {
  ...common,
  ...item,
};
```
But the actual operation effect is normal, the language can be displayed normally, I want to know how to eliminate this error,

**Comment by kazupon** [comment]
Hi! 
Thank you for your reporting!

`js` and `ts` extension haven't still released as 8.0.0-beta.11
You need to use edge version. 
about edge, please see the here:
https://github.com/nuxt-modules/i18n#install-edge-version

**Comment by marr** [comment]
@kazupon from what I can tell the current edge version is `8.0.0-beta.11-28025896.b896eaa` -- can you say if `js` is supported there? I am not seeing my messages loaded using the extension.

Thanks

**Comment by kazupon** [comment]
I'm working on this PR. Please just wait.
https://github.com/nuxt-modules/i18n/pull/2025
