### ISSUE TITLE
`definePageMeta({ name: ... })` create issue with `prefix` and `prefix_and_default` strategy

### ISSUE THREAD

**Issue by MrSociety404** [nuxt-modules/i18n#1972]
### Environment

- Operating System: `Windows`
- Node Version: `v16.14.0`
- Nuxt Version: `3.3.2`
- Package Manager: `yarn@1.22.19`
- Builder: `vite`
- User Config: `modules, i18n`
- Runtime Modules: `@nuxtjs/i18n@8.0.0-beta.10` 

### Reproduction

I've added the `definePageMeta `composable into my pages with the strategy `prefix` or `prefix_and_default`

```
definePageMeta({
  name: 'home',
});
```

### Describe the bug

An error `404  Page not found` appear when I want to go directly to my url with the locale who isn't my default locale.

For exemple, If my default locale is `en`  and I want to go to `http://localhost:3000/fr` to switch to the `fr` locale. the error appear

See also the reproduction link here:
https://stackblitz.com/edit/nuxt-starter-vcwmdu?file=pages%2Findex.vue,nuxt.config.ts

**Comment by kazupon** [comment]
Thank you for your reporting!

You need `app.vue` that is used `<NuxtPage>` component llike the below:

```vue
<template>
  <div>
    <NuxtPage />
  </div>
</template>
```

nuxt i18n is base on nuxt pages.
You need to setup nuxt pages correctly
About detail it, please see the docs the below:
https://nuxt.com/docs/guide/directory-structure/pages

Thanks!

**Comment by MrSociety404** [comment]
Am I missing something or it's still not fix the issue ? I have updated the stackblitz if it's needed

**Comment by mwesto** [comment]
same problem for me any news ?

**Comment by Upd4ting** [comment]
@kazupon Same issue here, have you an other idea from what the issue could be caused? Adding `<NuxtPage>` into `app.vue` does not help with the issue.

**Comment by kazupon** [comment]
This issue occurs because the nuxt i18n module is not getting the page of the named route defined by `definePageMeta({ name ... })` in `extendPages`.

**Comment by BobbieGoede** [comment]
I believe this issue is the same as https://github.com/nuxt-modules/i18n/issues/2581, I'm closing this issue in favor of tracking it in the newer issue as it and its reproduction are more up to date. 

We're working on fixing this, thank you for reporting and providing the reproduction! 💪
