### ISSUE TITLE
Lazy-load translations + dynamic locale messages - no reaction on locale switch

### ISSUE THREAD

**Issue by denis-gorin** [nuxt-modules/i18n#1975]
Error: `Hydration completed but contains mismatches.` (Open in new window)

Reproduction https://stackblitz.com/edit/github-jmp47v

**Comment by vervelover** [comment]
I confirm this in beta 11

**Comment by BobbieGoede** [comment]
It looks like this issue has been fixed, I am unable to replicate the issue after updating the dependencies in [your reproduction](https://stackblitz.com/edit/github-jmp47v-fb8wtj?file=app.vue). Please let me know if you are still experiencing this issue using the latest version.
