### ISSUE TITLE
Load external .json File

### ISSUE THREAD

**Issue by noxsii** [nuxt-modules/i18n#1979]
### Describe the feature

Hello, is there a solution to load an external .json file? So that you can translate strings also via API. 

### Additional information

- [x] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by dolbex** [comment]
Lang directory seems to append "../" in front of the resolved path. 

With the following configuration:

```
 i18n: {
    defaultLocale: 'en',
    langDir: resolve('./locales'),
    locales: [
      {
        name: 'English',
        code: 'en',
        file: './en.json',
        no_prefix: true,
      },
      {
        name: 'Espanol',
        code: 'es',
        file: './es.json',
        no_prefix: true,
      },
    ],

    vueI18n: {
      legacy: false,
      locale: 'en',
    },
  },
```

You end up getting:

```Failed to resolve import "../home/projects/github-aqi6ox-gs68oh/locales/en.json" from ".nuxt/i18n.options.mjs". Does the file exist? (x3)```


I've created a reproduction it here:

https://stackblitz.com/edit/github-aqi6ox-gs68oh?file=nuxt.config.ts

**Comment by BobbieGoede** [comment]
@dolbex `langDir` should be a relative path, by using `resolve` to set `langDir` it will be set to an absolute path, a warning was added in [the docs](https://v8.i18n.nuxtjs.org/options/lazy#langdir) for clarification. Just using `langDir: './locales'` should work in your reproduction.

**Comment by hahatulk** [comment]
example playground in this repo with this feature demo

https://github.com/nuxt-modules/i18n/tree/next/playground

**Comment by noxsii** [comment]
@hahatulk and that is supposed to help?

**Comment by hahatulk** [comment]
> @hahatulk and that is supposed to help? 

There is example of loading file from api. Works but buggy when changing locale

**Comment by dolbex** [comment]
> @dolbex `langDir` should be a relative path, by using `resolve` to set `langDir` it will be set to an absolute path, a warning was added in [the docs](https://v8.i18n.nuxtjs.org/options/lazy#langdir) for clarification. Just using `langDir: './locales'` should work in your reproduction.

Aaaaahh.. man, I swear I tried that before but you're right. I must have not. Just so you know I was actually going off this section of the documentation which does need to resolve it (I suppose b/c it's a module) https://v8.i18n.nuxtjs.org/guide/extend-messages.
