### ISSUE TITLE
Issues with peer dependencies found

### ISSUE THREAD

**Issue by xfq** [nuxt-modules/i18n#1982]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=README.md

### Describe the bug

There's a warning after installing `@nuxtjs/i18n`:

```
 WARN  Issues with peer dependencies found
.
└─┬ @nuxtjs/i18n 8.0.0-beta.10
  ├─┬ vue-i18n 9.3.0-beta.16
  │ └── ✕ missing peer vue@^3.0.0
  └─┬ vue-i18n-routing 0.12.2
    ├── ✕ missing peer vue@"^2.6.14 || ^2.7.0 || ^3.2.0"
    └─┬ @intlify/vue-router-bridge 0.8.0
      └─┬ vue-demi 0.13.11
        └── ✕ missing peer vue@"^3.0.0-0 || ^2.6.0"
Peer dependencies that should be installed:
  vue@">=3.2.0 <4.0.0"  
```

I installed Nuxt by using the method at https://nuxt.com/docs/getting-started/installation

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue on this repository.

This is a minor thing in Nuxt often faced with `pnpm`. Usually installing latest version with refreshed lock-files can help, or you can also add `vue` if you really want. Please see https://github.com/nuxt/nuxt/issues/14146 for `pnpm` support. Closing this as it is not an issue for this module.
