### ISSUE TITLE
ERROR  Cannot resolve @intlify/vue-i18n-bridge on pnpm! please install it on 'node_modules'

### ISSUE THREAD

**Issue by RodrigoProjects** [nuxt-modules/i18n#1983]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.3.0`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `devServer`, `modules`, `devtools`, `imports`, `vite`, `nitro`, `components`, `apollo`, `pinia`, `i18n`, `router`, `runtimeConfig`
- Runtime Modules:  `@nuxt/devtools@0.3.2-28018730.d9a4d6b`, `@nuxtjs/i18n@8.0.0-beta.10-28003311.2c39470`, `@nuxtjs/apollo@5.0.0-alpha.6`, `@pinia/nuxt@0.4.8`, `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.8`, `@worten/module-logger@1.0.0`, `@worten/module-proxy@1.0.0`, `@worten/storybook/module@2.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

I don't believe reproduction is needed here but tell me otherwise! :)

### Describe the bug

- pnpm i --shamefully-hoist
- ERROR  Cannot resolve @intlify/vue-i18n-bridge on pnpm! please install it on 'node_modules'

Package.json:
  "dependencies": {
        "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
    ...
  }

**Comment by RodrigoProjects** [comment]
pnpm --shamefully-hoist was not set correctly

**Comment by gyhyfj** [comment]
I'm stucked, how to resolve it ?
