### ISSUE TITLE
request error Context conflict

### ISSUE THREAD

**Issue by EduardoMateos** [nuxt-modules/i18n#1984]
### Environment

production and dev

### Reproduction

https://stackblitz.com/edit/nuxt-issue-20070

It is also related to the package "@nuxtjs/i18n" and "useCookie".

**1**. On a clean nuxt 3 project, install:
"@nuxtjs/i18n": "^8.0.0-beta.10"

**2**. Create global middleware like this:
```
export default defineNuxtRouteMiddleware(() => {
  const session = useCookie<string>("uuidSession");
});
```
**3**. Use siege and gtimeout to send multiple concurrent requests:
brew install siege                            
brew install coreutils
gtimeout 30 siege -c 5 http://localhost:3000

then sometimes I will get the error:
[nuxt] [request error] [unhandled] [500] Context conflict   

### Describe the bug

Error appears in production and local logs: 
[nuxt] [request error] [unhandled] [500] Context conflict
![image](https://user-images.githubusercontent.com/11529050/231140052-f5331b0f-4dd2-4919-a121-8764097ed764.png)

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Context conflict                                                                                                             12:51:26
  at checkConflict (./node_modules/unctx/dist/index.mjs:6:13)  
  at Object.call (./node_modules/unctx/dist/index.mjs:31:7)  
  at contextCaller (./node_modules/nuxt/dist/app/nuxt.js:61:26)  
  at Hookable.callHookWith (./node_modules/hookable/dist/index.mjs:198:20)  
  at Hookable.nuxtApp.hooks.callHook (./node_modules/nuxt/dist/app/nuxt.js:64:63)  
  at ./.nuxt/dev/index.mjs:723:32  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ./.nuxt/dev/index.mjs:394:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
```

**Comment by c-schwan** [comment]
@kazupon can you please provide a workaround?

**Comment by hahatulk** [comment]
same! @kazupon please we need your help, it is blocking issue

**Comment by c-schwan** [comment]
@kazupon useCookie is not the issue, i tried without and the same error happened

**Comment by EduardoMateos** [comment]
I don't know how to further debug the problem. I hope someone can help. The problem is affecting us in production and we urgently need to solve it @kazupon

**Comment by hahatulk** [comment]
> @kazupon useCookie is not the issue, i tried without and the same error happened

For me removing useCookie helps, but I need it

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

I would like you to sepelate this issue if this issue can be reproduced with your cusomt module without using nuxt i18n first. 🙏 
If so, you should report it to nuxt as an issue, as it is probably a problem with `useCookie`.

**Comment by c-schwan** [comment]
> Hi! Thank you for your reporting!
> 
> I would like you to sepelate this issue if this issue can be reproduced with your cusomt module without using nuxt i18n first. 🙏 If so, you should report it to nuxt as an issue, as it is probably a problem with `useCookie`.

👍 thx @kazupon after digging deeper it stuck in the app:render hook. The unctx is checking the currentContext vs instance ctx and throws an 500 error. I dont think ist ein i18n issue

**Comment by c-schwan** [comment]
@EduardoMateos 

can you please try below Nuxt 3.3.2?

See: https://github.com/nuxt/nuxt/pull/19753

**Comment by EduardoMateos** [comment]
@c-schwan you're right. in version 3.3.0 it doesn't happen.

![Captura de pantalla 2023-04-13 a las 7 26 09](https://user-images.githubusercontent.com/11529050/231661997-1d8bb7a4-60df-4ea7-95a7-0dbadcfce7e5.png)

**Comment by elzodxon** [comment]
How can we resolve it?

**Comment by EduardoMateos** [comment]
fixed: https://github.com/nuxt/nuxt/pull/20510

version 3.4.3
