### ISSUE TITLE
defineI18nConfig is not defined in i18n.config.ts

### ISSUE THREAD

**Issue by AnyFork** [nuxt-modules/i18n#1987]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `app`, `modules`, `i18n`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-28020728.5df24eb`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ezxqtb

### Describe the bug

defineI18nConfig is not defined in i18n.config.ts

### Logs

```shell
[nuxt] [request error] [unhandled] [500] defineI18nConfig is not defined                                                               16:36:37
  at eval (./i18n.config.ts:1:217)  
  at ViteNodeRunner.directRequest (file://./node_modules/vite-node/dist/client.mjs:348:11)
[nuxt] [request error] [unhandled] [500] defineI18nConfig is not defined                                                               16:36:37
  at eval (./i18n.config.ts:1:217)  
  at ViteNodeRunner.directRequest (file://./node_modules/vite-node/dist/client.mjs:348:11)
[nuxt] [request error] [unhandled] [500] defineI18nConfig is not defined                                                               16:36:37
  at eval (./i18n.config.ts:1:217)  
  at ViteNodeRunner.directRequest (file://./node_modules/vite-node/dist/client.mjs:348:11)
```

**Comment by kazupon** [comment]
Thank you for your reporting!

Sorry, `defineI18nConfig` is still only available in the edge channel version.
Could you try to edge channel version, please?
https://github.com/nuxt-modules/i18n#install-edge-version

**Comment by AnyFork** [comment]
> Thank you for your reporting!
> 
> Sorry, `defineI18nConfig` is still only available in the edge channel version. Could you try to edge channel version, please? https://github.com/nuxt-modules/i18n#install-edge-version

If I use objects without methods, as in the following example, there will also be errors
```js
export default {
    legacy: false,
    locale: 'en',
    messages: {
        en: {
            welcome: 'Welcome'
        },
        fr: {
            welcome: 'Bienvenue'
        }
    }
}
```
errors: [nuxt] [request error] [unhandled] [500] (r.default || r) is not a function

**Comment by kazupon** [comment]
Hi!
I've tried to reproduce your stackbliz codes + edge channel version.
Unfortunately, I could not reproduce this issue.
Could you try to use edge channel version, please?

**Comment by AnyFork** [comment]
Using the edge version can solve the above problem, and no errors will be reported whether using objects or methods.

**Comment by kazupon** [comment]
I am happy to hear it from you.
Happy coding!

**Comment by Babaktrad** [comment]
I have the same issue. I migrated the package to the edge version `npm:@nuxtjs/i18n-edge`. I got the following error when reinstalling the dependencies using yarn.
```
ERROR (0 , _debug.default) is not a function

  at node_modules/@nuxtjs/i18n/dist/module.mjs:78:36
  at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
  at jiti (node_modules/jiti/dist/jiti.js:1:253034)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2244:26)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2435:90)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2408:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3238:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3314:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

error Command failed with exit code 1.
```

- Operating System: `Ubuntu 23.04`
- Node Version: `v18.17.0`
- Nuxt Version: `3.2.2`
- Nitro Version: `2.3.3`
- Package Manager: `yarn@1.22.19`
- Builder: `vite`

**Comment by Babaktrad** [comment]
> I have the same issue. I migrated the package to the edge version `npm:@nuxtjs/i18n-edge`. I got the following error when reinstalling the dependencies using yarn.
> 
> ```
> ERROR (0 , _debug.default) is not a function
> 
>   at node_modules/@nuxtjs/i18n/dist/module.mjs:78:36
>   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
>   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
>   at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2244:26)
>   at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2435:90)
>   at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2408:47)
>   at async initNuxt (node_modules/nuxt/dist/index.mjs:3238:7)
>   at async loadNuxt (node_modules/nuxt/dist/index.mjs:3314:5)
>   at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
>   at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
>   at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
> 
> error Command failed with exit code 1.
> ```
> 
> * Operating System: `Ubuntu 23.04`
> * Node Version: `v18.17.0`
> * Nuxt Version: `3.2.2`
> * Nitro Version: `2.3.3`
> * Package Manager: `yarn@1.22.19`
> * Builder: `vite`

It fixed by removing `node_modules` folder and reinstalling dependencies again.
