### ISSUE TITLE
Can not use html format in lazy load i18n (error: 400 Detected HTML in ....)

### ISSUE THREAD

**Issue by esbb48** [nuxt-modules/i18n#1991]
### Environment
------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-o4x9nn?file=locales/getFromApi.js

<img width="955" alt="Screen Shot 2023-04-14 at 1 24 05 AM" src="https://user-images.githubusercontent.com/5118200/231837032-1788438e-3fd3-4ec8-a2a2-0efee4654412.png">

### Describe the bug

can not use html format in lazy load i18n

it will get error like:

```
 @nuxtjs/i18n Failed locale loading:  (400 Detected HTML in '<p>will get error</p>' message.|Detected HTML in '<p>will get error</p>' message.
 ```

**Comment by kazupon** [comment]
Thank you for your reporting!

From v8.0.0-beta.11, vue-i18n now outputs a warning if the message contains html. This is for security reasons to avoid XSS.

If you would like to use messages containing html, you can use them by setting the `precompile` option.
you need to configure `strictMessage: true` on nuxt i18n module option.

see more about `precompile` option details:
https://v8.i18n.nuxtjs.org/options/misc#precompile

Thanks!

**Comment by esbb48** [comment]
Hi @kazupon,

- I check the precompile document:
```
If you do not want the error to be thrown, you can work around it by setting it to false. However, this means that the locale message might cause security issues with XSS. In that case, we recommend setting the escapeHtml option to true.
```

I think I should configure `strictMessage: false`

Evan I use `strictMessage:true` ... console still get 400 error

Thanks

**Comment by kazupon** [comment]
I'm sorry. My comment was wrong.
You are right `strictMessage: false`. 🙇

**Comment by Ingramz** [comment]
Hi! I'm currently facing the same issue. Setting `strictMessage: false` in the stackblitz example above has no effect.

Edit: Found the culprit

https://github.com/nuxt-modules/i18n/blob/e3e446ebb38573217feadb197533a18ef1e293ff/src/runtime/server/precompile.ts#L86

should be `i18n: { precompile: { strictMessage, escapeHtml }}`

**Comment by kazupon** [comment]
Hi!
I've just fixed this issue.
You can try to install edge channel version
```
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
```

**Comment by antlionguard** [comment]
after beta.11 i got this error. i think this related with this issue.

`yarn build`
`yarn start`

```
[nuxt] [request error] [unhandled] [400]  (400 13|13|13|13|10|14|13|13|13|13|13|13|13|13|13|10|14|13|13|13 (/__i18n__/precompile))
  at async precompileMessages (./.output/server/chunks/app/server.mjs:3409:29)
  at async i18n_options (./.output/server/chunks/app/_nuxt/i18n.options-1f8e8eba.mjs:39:23)
  at async vueI18nConfigLoader (./.output/server/chunks/app/server.mjs:3052:81)
  at async resolveNuxtI18nOptions (./.output/server/chunks/app/server.mjs:3054:19)
  at async Object.setup (./.output/server/chunks/app/server.mjs:3684:116)
  at async Object.callAsync (./.output/server/node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (./.output/server/chunks/app/server.mjs:141:33)
  at async applyPlugins (./.output/server/chunks/app/server.mjs:150:5)
  at async createNuxtAppServer (./.output/server/chunks/app/server.mjs:4617:7)
  at async Object.renderToString (./.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
```




after this settings i got this weird error on development.
```
    precompile: {
      strictMessage: false
    },
```

error: 
```
400 Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Invalid linked format|Unexpected lexical analysis in token: 'startupce'|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key|Invalid linked format|Unexpected lexical analysis in token: 'startupce'|Unexpected empty linked key|Unexpected empty linked key|Unexpected empty linked key (/__i18n__/precompile))
```

beta 10 works fine.

**Comment by jaredbash** [comment]
@antlionguard : I had this error as well, and it was because of the formatting used in my linked messages in my language files. Specifically, we still had language files with this syntax: @:{'foo.bar'}, and we needed to change them to @:foo.bar

Also check if there are any special characters that are not properly escaped.

**Comment by mv92** [comment]
> Hi! I've just fixed this issue. You can try to install edge channel version
> 
> ```
> "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
> ```
Thanks!

Any estimates when this fix will come to a beta version?

**Comment by JaZo** [comment]
Can we add a note about this in the release notes please? It's a breaking change and the release notes don't mention it, not even as feature. It cost us a few hours to find the cause of this issue and the solution.

**Comment by lukaszarpak** [comment]
Why is this issue closed? It's still persistent in new releases of the package. Setting `strictMessage: false` or `escapeHtml: true` doesn't seem to have any effect.

**Comment by JaZo** [comment]
@lukaszarpak, some option names have changed. This is how I disable this check now (I'm currently on beta 13):
```
i18n: {
    compilation: {
        strictMessage: false,
    },
},
```

**Comment by davemg3** [comment]
> Why is this issue closed? It's still persistent in new releases of the package. Setting `strictMessage: false` or `escapeHtml: true` doesn't seem to have any effect.

Try to use it in nuxt.config.ts and not i18n.config.ts

**Comment by pmiramonteso** [comment]
Hi! I'm currently having this problem, and it doesn't even work with StrictMessage. Does anyone know the solution?
