### ISSUE TITLE
v8.0.0-beta.11 Cannot be used in deno deploy

### ISSUE THREAD

**Issue by so1ve** [nuxt-modules/i18n#1993]
### Environment

```
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@7.32.0
- Builder:          vite
- User Config:      srcDir, build, vite, modules, css, colorMode, googleFonts, i18n, nitro, experimental, typescript
- Runtime Modules:  @vueuse/nuxt@9.13.0, @pinia/nuxt@0.4.8, @nuxtjs/i18n@8.0.0-beta.11, @nuxtjs/color-mode@3.2.0, @nuxtjs/google-fonts@3.0.0, @nuxtjs/critters@0.4.0, @nuxtjs/robots@3.0.0, unplugin-icons/nuxt
- Build Modules:    -
```

Note: This is my project configuration. The configuration causes this problem is installing `@nuxtjs/i18n`.

### Reproduction

https://github.com/so1ve/nuxt-process-versions-node-undefined-repro

Just create a fresh nuxt app with latest nuxt-i18n. Set `NITRO_PRESET` environment to `deno`. Build this project, cd .output and run `deno run server/index.ts`.
Stackblitz reproduction is not available because we need to use deno.

### Describe the bug

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'split')
const [maj, min] = process.versions.node.split('.').slice(0, 2).map(n => Number.parseInt(n, 10))
```

It seems that some dependency of nuxt-i18n is using readdirp (I can check later), which includes the following code:
```ts
const [maj, min] = process.versions.node.split('.').slice(0, 2).map(n => Number.parseInt(n, 10));
```
`process.versions.node` is not shimed. So it became `undefined`.

### Additional context

Maybe this is an unenv issue?

**Comment by so1ve** [comment]
Wait - why is readdirp bundled into dist files? It is a chokidar dependency, and chokidar is a devDependency in nuxt.

**Comment by zsilbi** [comment]
This also breaks serverless deployments currently where `process.versions.node` is undefined as well.

**Comment by so1ve** [comment]
Repro here: https://github.com/so1ve/nuxt-process-versions-node-undefined-repro

**Comment by so1ve** [comment]
This change is introduced in https://github.com/nuxt-modules/i18n/pull/1938

**Comment by n-kort** [comment]
`netlify-edge` functions also fail to build nuxt/nuxt#21719

**Comment by kazupon** [comment]
This issue was fixed since `@intlify/bundle-utils` is no longer bundled on the server side as of v8.0.0-beta.13.
If you have still issue, please reply.

**Comment by so1ve** [comment]
Thanks!
