### ISSUE TITLE
Warning: Calling `useRoute` within middleware may lead to misleading results

### ISSUE THREAD

**Issue by darthf1** [nuxt-modules/i18n#1996]
Hi!

Im on `nuxt` `3.4.1` and `@nuxtjs/i18n` `8.0.0-beta.11`

In a middleware, I want to redirect a user to the login page with the localized URL:

```ts
import { defineNuxtRouteMiddleware, navigateTo } from '#app'
import { useLocalePath } from '#i18n'

export default defineNuxtRouteMiddleware(async (to) => {

  // ...some logic...

  return navigateTo(localePath('identity-Login'))
})
```

Using the `localePath` function generates the following warning in the console:

![image](https://user-images.githubusercontent.com/17253332/231970705-b668931c-3efe-4852-9bd0-678f9461ecce.png)

Is there a way to do it "better" so this warning is not displayed?

**Comment by kazupon** [comment]
I think you can use `$localePath()` via `useNuxtApp` the below:

```ts
const nuxt = useNuxtApp()
nuxt.$localePath()
```

`$localePath` is exported via nuxt instance.
Thanks!

**Comment by darthf1** [comment]
> I think you can use `$localePath()` via `useNuxtApp` the below:
> 
> ```ts
> const nuxt = useNuxtApp()
> nuxt.$localePath()
> ```
> 
> `$localePath` is exported via nuxt instance.
> Thanks!

Works! Thanks!
