### ISSUE TITLE
Test action unreliable - action fails then succeeds without code change

### ISSUE THREAD

**Issue by BobbieGoede** [nuxt-modules/i18n#1998]
### Environment

-

### Reproduction

Unable to reproduce reliably, first noticed on my PR https://github.com/nuxt-modules/i18n/pull/1997 but behaviour seems to be present as seen in actions triggered by latest commit https://github.com/nuxt-modules/i18n/actions/runs/4697036451

[Test run 1 (failed)](https://github.com/nuxt-modules/i18n/actions/runs/4699507910/attempts/1)
[Test run 2 (succeeded)](https://github.com/nuxt-modules/i18n/actions/runs/4699507910/attempts/2)

### Describe the bug

Noticed tests failed on a small PR and succeeded after rerunning the job without making changes. I'm not sure what the cause is, it may be a race condition or a change in test cleanup upstream. Since it's hard to reproduce it's also hard to pinpoint the cause, I suspect it could be caused by the recent bump in dependency versions.

[Test run 1 (failed)](https://github.com/nuxt-modules/i18n/actions/runs/4699507910/attempts/1)
[Test run 2 (succeeded)](https://github.com/nuxt-modules/i18n/actions/runs/4699507910/attempts/2)

**Comment by kazupon** [comment]
@BobbieGoede 
Can I close this issue?

**Comment by BobbieGoede** [comment]
I think we should keep this issue open, while I have not been able to reproduce it, this issue seems to still be present. As seen here:
* [fix: drop `vueI18n` option warning (succeeded)](https://github.com/nuxt-modules/i18n/actions/runs/5887232980)
* [fix: drop `vueI18n` option warning (failed)](https://github.com/nuxt-modules/i18n/actions/runs/5887298678)

And here as well:
* [docs: tweak docs contents structure (succeeded)](https://github.com/nuxt-modules/i18n/actions/runs/5887636094)
* [docs: tweak docs contents structure (failed)](https://github.com/nuxt-modules/i18n/actions/runs/5887707415)

As far as I can tell there is no code difference between the test runs, the jobs are triggered as they have been merged into `next`. But as demonstrated in this issue description it also happens on PRs before merge.

It's mostly an inconvenience, the tests usually succeed after rerunning, but it does prevent automatic releases and makes the test seem less trustworthy.
