### ISSUE TITLE
TS2345: Argument of type '"i18n:beforeLocaleSwitch"' is not assignable to parameter of type 'HookKeys '.

### ISSUE THREAD

**Issue by vasilistotskas** [nuxt-modules/i18n#1999]
Hello im trying to create an i18n plugin using runtime hooks based on docs here https://v8.i18n.nuxtjs.org/guide/runtime-hooks but im getting TS Errors 

![Screenshot_3](https://user-images.githubusercontent.com/60323306/232059895-c5c40feb-5767-444c-8251-642498ab7e16.png)

the package.json versions :
```
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
"nuxt": "3.4.1",
```

i have also tried this way :
![Screenshot_4](https://user-images.githubusercontent.com/60323306/232060494-6d965d0a-9ec4-4562-a8d1-c8a9824a8029.png)

im resolving it using // @ts-ignore but i should not , any ideas ?

**Comment by NathanD19** [comment]
Hey, I've run into the same issue. Did you find a fix?

**Comment by kazupon** [comment]
Could you give us **your minimal reproduction** with stackbliz or github repo please? 🙏

**Comment by vasilistotskas** [comment]
https://github.com/vasilistotskas/grooveShop/tree/master/storefrontUINodeNuxt/src

https://stackblitz.com/github/vasilistotskas/grooveShop/tree/master/storefrontUINodeNuxt/src?file=plugins%2Fi18n.ts

**Comment by BobbieGoede** [comment]
Closing this as I'm unable to reproduce this issue using the latest version, reproduction to demonstrate [here](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-zphjhd?file=plugins%2Fi18n.ts,nuxt.config.ts).
