### ISSUE TITLE
`baseUrl` in runtime config not working

### ISSUE THREAD

**Issue by trandaison** [nuxt-modules/i18n#2001]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, i18n, runtimeConfig
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-fkqezf?file=plugins%2Ffetch.ts

### Describe the bug

My nuxt app is running on `localhost:3000`, my API is running on `http://localhost:5555`.
If I override the global fetch and provide another `baseUrl` value as below.

```ts
const apiFetch = $fetch.create({
    baseURL: 'http://localhost:5555',
});
globalThis.$fetch = apiFetch;
```

The request to `/__i18n__/precompile` will be pointed to `http://localhost:5555/__i18n__/precompile`, and of course, it will be cause an 404 error.

It should maintain `localhost:3000` which was set in `runtimeConfig`.

**Comment by BobbieGoede** [comment]
I'm not sure if I can recommend overwriting `globalThis.$fetch`, [this issue](https://github.com/nuxt/nuxt/issues/14736) has some possible ways to configure and use `$fetch`. With your current approach any module that supplies and consumes [server routes](https://nuxt.com/docs/guide/directory-structure/server#server-routes) may stop working. 

Though if your approach is common I'm sure we could create a fetch instance with the expected configuration or something along those lines.

**Comment by trandaison** [comment]
@BobbieGoede According to [this](https://github.com/nuxt/bridge/blob/ddd8eccdcba58c61cc335a64acbc99fbf446b295/packages/bridge/src/runtime/nitro-bridge.client.mjs), I think it's okay to replace default `$fetch` by a preconfigured instance.

From this commit
https://github.com/nuxt-modules/i18n/commit/f7925d113a5c4ab3cadf5467c899d604f0d33214#diff-7755b40274cbd4ca5d224c6ed6953280e589110e9289595aeb246ff4a1c07448R522-R529
I think modify into this should work:

```diff ts
  const opts: FetchOptions = {
    method: 'POST',
+  baseURL: NUXT_PUBLIC_I18N_BASE_URL,
    body: {
      locale,
      type: 'locale',
      resource: loaded
    }
  };
+ const xfetch = $fetch.create();
- const precompiledCode = await $fetch<string | Blob>(NUXT_I18N_PRECOMPILE_ENDPOINT, opts)
+ const precompiledCode = await xfetch<string | Blob>(NUXT_I18N_PRECOMPILE_ENDPOINT, opts);
```

**Comment by kazupon** [comment]
I believe there should be no implementation that rewrites `$fetch`. `$fetch` is the fetch API provided by nuxt. And some modules, such as nuxt i18n, use the standard $fetch provided by nuxt. It is not expected that `$fetch` can be rewritten to something else.

**Comment by trandaison** [comment]
@kazupon The fact is `baseUrl` in runtime config is not working.
If I set the base url is `http://localhost:3000`, then it should be make a request to `http://localhost:3000/__i18n__/precompile`.

**Comment by kazupon** [comment]
nuxt i18n module use prerender and server including no longer at v8.0.0-beta.13
So, I think this issue is fixed that version.
I'll close this issue. 
if you have still the issue, please you will open as new issue.
Thanks!
