### ISSUE TITLE
Vercel deploy broken

### ISSUE THREAD

**Issue by marc-tech** [nuxt-modules/i18n#2004]
### Environment

Vercel

### Reproduction

use "@nuxtjs/i18n": "8.0.0-beta.11"
and deploy on vercel

### Describe the bug

On i18n call /__i18n__/precompile => Error 500

vercel log => [nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/vercel/path0/webapp/.nuxt/i18n/config-a7d47455.js'

I guess vercel can't create file after the build step, and i18n /precompile create the ./nuxt/i18n/config-....js after the build (when app is first loaded)

is there a way to precompile during the build or to allow vercel to create new build file ?

### Additional context

https://github.com/nuxt-modules/i18n/commit/f7925d113a5c4ab3cadf5467c899d604f0d33214#r109373991

### Logs

<img width="339" alt="Capture d’écran 2023-04-17 à 21 13 05" src="https://user-images.githubusercontent.com/15327831/232587725-f1bc87f2-2187-4d9c-8e21-35908f7c6fe8.png">

<img width="1341" alt="Capture d’écran 2023-04-17 à 21 08 32" src="https://user-images.githubusercontent.com/15327831/232587349-86213164-47d0-4331-ab85-971cddf23eda.png">

**Comment by marc-tech** [comment]
also link to this vercel issue : https://github.com/orgs/vercel/discussions/1396

**Comment by kazupon** [comment]
Thank you for your reporting!
This issue is same as #1990 
I'm working on this issue resolving.
please wait. 🙏
Thanks!
