### ISSUE TITLE
Can't use config from layer and locale files from main project in beta.11

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt-modules/i18n#2005]
### Environment

My app:
```
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      runtimeConfig, app, modules, extends, frontendUtils
- Build Modules:    -
------------------------------
```

My `Frontend Utils` extended layer:
```
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      components, modules, css, i18n
- Runtime Modules:  modules/init.ts, @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------
```

### Reproduction

I was not able to reproduce it on a clean project because I had an issue with `vue-i18n` dependency in a new project. I hope the description is clear, but if a reproduction is needed, I'll try to prepare it again.

### Describe the bug

I have an internal package - `frontend-utils`, where I keep common things used in many projects, including configs for i18n and additional composables. However, I store the translation files in the main project, in the `~/locales` directory.

Unfortunately, since beta 11, the such configuration has stopped working and the files are not found. I suspect that the problem is this change, which changes `rootDir` to `srcDir` and in the situation when I extend the layer, the translation files are searched within the layer, not in the main application – https://github.com/nuxt-modules/i18n/pull/1964/files.

**Comment by kazupon** [comment]
I've fixed this issue with #2025 
Please try to use edge channel 8.0.0-beta.11-28059008.d1499b6 version.
