### ISSUE TITLE
431 Request Header Fields Too Large using TS files

### ISSUE THREAD

**Issue by fskarmeta** [nuxt-modules/i18n#2008]
### Environment

node v16.18.1
nuxt 3.4.1
@nuxtjs/i18n 8.0.0-beta.11

### Reproduction

If my issue is not obvious for you, i would gladly take the time to reproduce the issue. 

### Describe the bug

Hi, first thanks for the module, this is probably a me problem and I also understand that this is a beta module. 
Until recently I was using nuxt 3.4.0 with 8.0.0-beta.8

I was importing in my nuxt.config.ts the module and in the `i18n.vue18n` options adding my config
```
{
  legacy: false,
  locale: 'es',
  defaultLocale: 'es',
  messages: {
    es: esES,
  },
}
```

This was working fine.
After updating to latest `nuxt` and `@nuxtjs/i18n` I started getting quite a few errors.
I came to the conclusion that now i need a separated `i18n.configs.ts` file, which i did. 

On build everything works fine but on dev 

**1. I get this warning**

```
i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release.                      @nuxtjs/i18n 12:35:11 AM
If you're using it, please use i18n:registerModule instead.
```

At this stage i'm a bit confused with the docs, should i add a plugin file and install vuei18n ? I thought this was not needed for nuxt3. 

But most importantly. 

**2. 431 Request Header Fields Too Large using TS files**

My translations collection is a .ts file, this is kinda important for me since I relay on having enums as keys. Not sure if this is an anti pattern and they should be json files. I was until recently using this pattern, before the package updates, and also in vue3 projects. 

The thing that i noticed, is that if I reduce the translation messages file to one single line of code `{hola: 'hi'}` and then delete the `.nuxt` folder and run dev everything works. Then if I input my large TS translation file it also keeps working. It just fails if I clear my `.nuxt` folder and run the first development environment having that large file.

**Comment by JustinJsn** [comment]
same

**Comment by kazupon** [comment]
Thank you for your reporting!
This issue is same as #2000 

I'm working on this issue resolving.
please wait. 🙏 

Thanks!

**Comment by AnyFork** [comment]
I also encountered the same problem, but my translation file format is JSON. If the `.nuxt` file is deleted and a translation file is configured as follows when the project starts in the development environment，everything is normal.
```js
import { zh, tw, en } from './locales'
export default defineI18nConfig(nuxt => ({
    legacy: false,
    locale: 'tw',
    messages: { tw }
}))
```
If I add both 'zh' and 'en' files during the runtime, there will be no error and it should be an incremental compilation. The code is as follows.
```js
import { zh, tw, en } from './locales'
export default defineI18nConfig(nuxt => ({
    legacy: false,
    locale: 'tw',
    messages: { tw, en, zh }
}))
```
If the service is stopped at this time, the '. nuxtt' file is deleted, and the development environment is restarted locally, the # 2008 issue will be triggered. Upon checking the exception stack, the translation file was fully loaded during project startup, exceeding the preset threshold of the 'max http header size' attribute header in HTTP.

**Comment by erickh115** [comment]
> I also encountered the same problem, but my translation file format is JSON. If the `.nuxt` file is deleted and a translation file is configured as follows when the project starts in the development environment，everything is normal.
> 
> ```js
> import { zh, tw, en } from './locales'
> export default defineI18nConfig(nuxt => ({
>     legacy: false,
>     locale: 'tw',
>     messages: { tw }
> }))
> ```
> 
> If I add both 'zh' and 'en' files during the runtime, there will be no error and it should be an incremental compilation. The code is as follows.
> 
> ```js
> import { zh, tw, en } from './locales'
> export default defineI18nConfig(nuxt => ({
>     legacy: false,
>     locale: 'tw',
>     messages: { tw, en, zh }
> }))
> ```
> 
> If the service is stopped at this time, the '. nuxtt' file is deleted, and the development environment is restarted locally, the # 2008 issue will be triggered. Upon checking the exception stack, the translation file was fully loaded during project startup, exceeding the preset threshold of the 'max http header size' attribute header in HTTP.

I think lazy load message is the way to prevent this issue 
below config work at dev and server
export default {
  legacy: false,
  locale: ["enUS", "zhCN", "zhHK"],
  defaultLocale: "zhHK",
  fallbackLng: "zhHK",
  messages: { zhHK, enUS, zhCN },
  lazy: true,
};

**Comment by AnyFork** [comment]
> > I also encountered the same problem, but my translation file format is JSON. If the `.nuxt` file is deleted and a translation file is configured as follows when the project starts in the development environment，everything is normal.
> > ```js
> > import { zh, tw, en } from './locales'
> > export default defineI18nConfig(nuxt => ({
> >     legacy: false,
> >     locale: 'tw',
> >     messages: { tw }
> > }))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I add both 'zh' and 'en' files during the runtime, there will be no error and it should be an incremental compilation. The code is as follows.
> > ```js
> > import { zh, tw, en } from './locales'
> > export default defineI18nConfig(nuxt => ({
> >     legacy: false,
> >     locale: 'tw',
> >     messages: { tw, en, zh }
> > }))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If the service is stopped at this time, the '. nuxtt' file is deleted, and the development environment is restarted locally, the # 2008 issue will be triggered. Upon checking the exception stack, the translation file was fully loaded during project startup, exceeding the preset threshold of the 'max http header size' attribute header in HTTP.
> 
> I think lazy load message is the way to prevent this issue below config work at dev and server export default { legacy: false, locale: ["enUS", "zhCN", "zhHK"], defaultLocale: "zhHK", fallbackLng: "zhHK", messages: { zhHK, enUS, zhCN }, lazy: true, };

Yes, the effect can be achieved through lazy loading
