### ISSUE TITLE
detectBrowserLanguage with redirection not working anymore in Beta11

### ISSUE THREAD

**Issue by codeflorist** [nuxt-modules/i18n#2011]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

With Beta10, redirection to `/de` (with german browser) _kind-of_* works, as you can see, if you open this stackblitz in a new tab:
https://stackblitz.com/edit/nuxt-starter-mmtt9z?file=nuxt.config.ts

(* i don't know, why it displays "404 Page not found" - it works as intended in my project.)

Here is the same stackblitz with Beta11:
https://stackblitz.com/edit/nuxt-starter-ddh7vo?file=nuxt.config.ts
No redirection is taking place here at all.

### Describe the bug

Consider this config:

```js
  i18n: {
    detectBrowserLanguage: {
      useCookie: false,
      alwaysRedirect: true,
    },
    strategy: 'prefix',
    locales: ['de', 'en', 'fr'],
  },
```

With Beta10 the root page correctly redirects me to `/de`.

But with Beta11 no redirection is taking place.

Have the options changed here, or is this a regression?

**Comment by kazupon** [comment]
I think this issue is resolved with #2025 
Please check edge channel version.

**Comment by codeflorist** [comment]
@kazupon thanks for your help! unfortunately `i18n-edge` seems to have the same problem. here is a stackblitz:
https://stackblitz.com/edit/nuxt-starter-iuuwws?file=package-lock.json

if i use `i18n-edge` in my project, i have the following effect:
i have `strategy: 'prefix'`, but the website root does not redirect to a prefixed-page, but instead delivers the page in the detected browser language.

**Comment by juandelperal** [comment]
is there any version of i18n-edge or i18n-next working/redirecting properly?

**Comment by yakovlev-code** [comment]
> is there any version of i18n-edge or i18n-next working/redirecting properly?

@juandelperal 8.0.0-beta.10 works for me

**Comment by BobbieGoede** [comment]
Closing this as I'm unable to replicate this issue using the latest version, let me know if you're still experiencing this issue (with an updated minimal reproduction)!
