### ISSUE TITLE
[NUXT] Deploys to Vercel Edge Targets are failing ,TypeError: Cannot read properties of undefined (reading 'node')     at (index.mjs:1:187011)     at (__nitro:middleware.js:1:17)

### ISSUE THREAD

**Issue by TangsWang** [nuxt-modules/i18n#2014]
### Environment

  "devDependencies": {
    "nuxt": "3.3.3",
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
  },

### Reproduction

  "devDependencies": {
    "nuxt": "3.3.3",
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
  },

### Describe the bug

vercel edge error log:
TypeError: Cannot read properties of undefined (reading 'node')
    at (index.mjs:1:187011)
    at (__nitro:middleware.js:1:17)

**Comment by kazupon** [comment]
maybe, Is this issue same #2016.

**Comment by kazupon** [comment]
I think this issue is resolved with #2025
