### ISSUE TITLE
Duplicated Lazy-load translations requests

### ISSUE THREAD

**Issue by Flowko** [nuxt-modules/i18n#2022]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      pagesData
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-grevuj?file=nuxt.config.ts

reportuction above will show that the log happens twice when you visit `/fr` page
```
en ( calls the default local, which calls the service that will get the translations )
fr ( calls the service that will get the translations as well )
```
 

### Describe the bug

I have noticed that when attempting to lazy load translations using a Promise/file format, the service is called twice (depending on the number of locales present) but only on the non-default locale. While I understand that this may be due to the non-fallback/default locale potentially failing and defaulting to another option, I do not believe this is the most optimal approach. Repeatedly calling the service to retrieve translations seems unnecessary.

Is there a way to address this issue or is this how it is intended to function?

**Comment by kazupon** [comment]
This is the intended behavior from v7.
I'm not a nuxt i18n creator, so I don't know why the lazy-loading implementation is that way.

Thanks!

**Comment by rchl** [comment]
It needs to load the currently used locale (for obvious reasons) and the default locale (if different than currently used locale) so that the missing translations can fall back to the default locale.

**Comment by imrim12** [comment]
It is calling twice for everything

![image](https://github.com/user-attachments/assets/ffe9fe77-a5f7-412c-8233-4b39a5159dae)

If choose another language, it would call the default language twice and the current language twice
![image](https://github.com/user-attachments/assets/864b9016-cc55-433a-80ad-a1d99b3ce861)

It's a minimal app with this config:

```
i18n: {
    lazy: true,
    strategy: 'no_prefix',
    defaultLocale: 'en',
    vueI18n: fileURLToPath(new URL('./i18n.config.ts', import.meta.url)),
    bundle: {
      runtimeOnly: true,
      compositionOnly: true,
    },
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'nuxt-template-language',
    },
    locales: [
      {
        code: 'en',
        language: 'en-US',
        name: 'English',
        dir: 'ltr',
        file: {
          path: fileURLToPath(new URL('./app/plugins/i18n/locale/en.ts', import.meta.url)),
          cache: true,
        },
      },
      {
        code: 'vi',
        language: 'vi-VN',
        name: 'Tiếng Việt',
        dir: 'ltr',
        file: {
          path: fileURLToPath(new URL('./app/plugins/i18n/locale/vi.ts', import.meta.url)),
          cache: true,
        },
      },
    ],
  },
```

**Comment by imrim12** [comment]
updated:
This happens because i use Nuxt layers, it fetches once for each layer, even when i only configure the 1st level layer and not the others
Now im using 3 levels of layers and it calls 3 times
![image](https://github.com/user-attachments/assets/91019f60-02d0-41ce-a015-1fc0ed610455)

![image](https://github.com/user-attachments/assets/96ca01ee-52d8-4a6f-ae28-48f6cab1757d)

In spite of using multiple translation files for multiple layers, my goal is to have only 1 translation file on the top `/public` folder, which i will push to AWS S3 later

And then use a single typescript locale file

```
export default defineI18nLocale(locale => {
  return $fetch(`${process.env.CLOUDFRONT_URL}/${locale}.json`)
})
```

**Comment by BobbieGoede** [comment]
@imrim12 
Can you open a new issue with a minimal reproduction? 🙏

**Comment by whoisarjen** [comment]
@BobbieGoede is there any update on this one?

**Comment by BobbieGoede** [comment]
@whoisarjen 
This issue and reproduction is quite old, could you open a new issue with a minimal reproduction? 🙏

**Comment by whoisarjen** [comment]
@BobbieGoede done https://github.com/nuxt-modules/i18n/issues/3543
