### ISSUE TITLE
Cross-Request Pollution of Router/SSRContext

### ISSUE THREAD

**Issue by SebastianBoergers** [nuxt-modules/i18n#2024]
### Environment

Node: 16.20.0 | 18
Nuxt: 3.3.1 | 3.4.1
i18n-nuxt-module: beta-9 | beta-11

### Reproduction

**Min-Repro:**
https://codesandbox.io/p/github/Meleemaru2k/nuxt-i18n-routingerror-repro/draft/gracious-browser

**How to:**
Add i18n Module to your nuxt project.
Open 3+ different URIs simultaneously (save them as favorite in a folder and just middleclick).
For example: /abc /123 /xyz

**Log-Examples**
We log the following In different parts of the app:
```
  useNuxtApp().ssrContext?.url,
  useRouter().currentRoute.value.path,
  useRoute().path
```

WITHOUT i18n:
`[Description] /abc /abc /abc`

WITH i18n:
`[Description] /123 /123 /abc`

Curiously useRoute() will have the right path, while useRouter() and ssrContext will contain mixed up paths from other requests. Async/await composables etc. are not the cause of this, neither is suspense (both included in the reproduction). If you remove the i18n-Module everything will work as expected.
EDIT: Or if any async/await is the issue, this should throw an Error (similar to the Nuxt Context Conflict?) in my eyes, as it's super hard to spot and nothing you'll find in developmen if you're not stumbling on it by accident.

### Describe the bug

If you have simultaneous requests hitting the server, useRouter() will show paths from another request, as will ssrContext.url. This makes opening multiple Tabs return one and the same url/path for useRouter(). useRoute() has the right path for some reason.

This bug exists since _beta-9 | Nuxt 3.3.1_ and is still present in _beta-11 | Nuxt 3.4.x_. It's not Node-Version related afaik.

**Comment by niklaswolf** [comment]
@kazupon I can observe something like this, too. See https://github.com/nuxt/nuxt/issues/20741#issuecomment-1540457101 
As described in the issue I additionally see that the `window.__NUXT__.data` is affected, too.

**Comment by iijaachok** [comment]
I've isolated this to a plugin that adds a routeMiddleware by using `defineNuxtRouteMiddleware`. It seems that any await inside that composable introduces context pollution. Working on a reproduction for Nuxt.
See where exactly that happens inside nuxtjs/i18n: 
https://github.com/nuxt-modules/i18n/blob/d40104cb6b20c13ce90c4e8fe003a8dd69a0c31c/src/runtime/plugins/i18n.ts#L425

**Comment by kazupon** [comment]
I seem that cross-request pollution has fixed on https://github.com/nuxt/nuxt/issues/20741
If you will try to confirm fixed on nuxt i18n too, please tell us about it.

**Comment by niklaswolf** [comment]
I can not reproduce the issue with Nuxt 3.5.2 using the original reproduction described here: https://github.com/nuxt/nuxt/issues/20741#issuecomment-1540457101 

This issue can be closed from my perspective :)
