### ISSUE TITLE
How to go back to the previous version?

### ISSUE THREAD

**Issue by szulcus** [nuxt-modules/i18n#2027]
### Describe the feature

After some time, I returned to a project that used the module version `^8.0.0-beta.10`. A lot of random things stopped working for me and I don't have the strength to track down all these bugs anymore. Why, despite not changing the version of the package, has it changed for me and is there any way to return to the previous, working version?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
I'm working on this PR!
https://github.com/nuxt-modules/i18n/pull/2025

8.0.0-beta.11 is buggy, so especially vue-i18n configuration and js/ts resources
Therefore, we recommend using v8.0.0-beta.10.

**Comment by kazupon** [comment]
> Why, despite not changing the version of the package, has it changed for me and is there any way to return to the previous, working version?

The changes in v8.0.0-beta.11 are explained in the release note. 
PRs or issues are linked to the items listed there.
https://github.com/nuxt-modules/i18n/releases/tag/v8.0.0-beta.11

The disruptive change in v8.0.0-beta.11 is that the `vueI18n` option is now a config file.
To back to the previous version, you can simply pin v8.0.0-beta.10 in package.json.

**Comment by szulcus** [comment]
@kazupon I do not understand this. I'm pretty sure I was using just that version in my project and still had the problem. Just to be sure, I switched to a different project which, after reinstalling the packages, still works. Sorry for the confusion.

I also found a problem that was largely responsible for my problems. I'll create an issue for this soon.
