### ISSUE TITLE
$i18n.defaultLocale doesn't work.

### ISSUE THREAD

**Issue by RajinCoding2007** [nuxt-modules/i18n#2030]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.13.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@9.4.0
- Builder:          vite
- User Config:      modules, postcss, vite, css, components, content, colorMode, googleFonts, i18n
- Runtime Modules:  @nuxtjs/color-mode@3.2.0, @nuxtjs/tailwindcss@6.6.6, @nuxt/content@2.6.0, @nuxtjs/i18n@8.0.0-beta.11, @nuxtjs/google-fonts@3.0.0, nuxt-icon@0.3.3
- Build Modules:    -

### Reproduction

Reproduction is simple - just use `$i18n.defaultLocale` inside component templates, it doesn't work...

### Describe the bug

In this [link](https://v8.i18n.nuxtjs.org/api/vue-i18n#defaultlocale) I found that we can use `$i18n.defaultLocale` to print default locale, but it doesn't do that.

**Comment by popeyeapi** [comment]
I'm also have same issue
