### ISSUE TITLE
Huge memory leak

### ISSUE THREAD

**Issue by cyperdark** [nuxt-modules/i18n#2034]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      telemetry, ssr, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -

### Reproduction

Source code: https://github.com/cyperdark/i18n

### Describe the bug

Memory leak video:
https://i.osuck.link/1683034408_ScxZCLgnzT.mp4

**Comment by cyperdark** [comment]
This is how memory graph look like in production (when memory go down it means app crashed)
![image](https://user-images.githubusercontent.com/21735205/236648930-0e099189-885e-43b9-bec2-045afb82991d.png)

**Comment by kazupon** [comment]
Thank you for your reporting!

I think that v8.0.0-beta.11 is buggy. I am fixing on it now, but that bug may have affected it.

we would like to see if memory leaks occur in the previous version v8.0.0-beta.10 to make sure this version is affected.
If you have the time we would appreciate your help. 🙏

**Comment by cyperdark** [comment]
I tried on versions below, and until version 8.0.0-beta.7 situation is the same
BUT on this version i got errors

thats weird, need more testing
![image](https://user-images.githubusercontent.com/21735205/236970075-5ace3783-8932-4e3e-8c09-5080cdbbb422.png)

**Comment by cyperdark** [comment]
Potentially i found what caused this leak


1. If i use **Head Title with $t**, memory went to **1gb** (1000 requests) then go to normal **~90**
![image](https://user-images.githubusercontent.com/21735205/236992899-0564ae82-d8c6-42fe-a406-05290e7b9f8c.png)


2. same situation with **useLang**, from **60** went to **1gb** then down to **85-90**
![image](https://user-images.githubusercontent.com/21735205/236992986-d2e338d9-4804-48e6-bf3e-f0d7fad195fe.png)
![image](https://user-images.githubusercontent.com/21735205/236993008-5464f17c-d3d3-4668-a4c3-094b8525085e.png)


3. but if i use **computed** title, from **60** to memory cap
![image](https://user-images.githubusercontent.com/21735205/236993451-3d2d8034-2f6b-4dec-b3ee-f8c8afa9a5bf.png)
![image](https://user-images.githubusercontent.com/21735205/236993468-e2869efd-49f4-48b6-bd90-861a71961170.png)
![image](https://user-images.githubusercontent.com/21735205/236993702-52e806f2-6c02-4ade-9d47-dd79114c4ce0.png)

4. Same as in 2 or 1
![image](https://user-images.githubusercontent.com/21735205/236994042-c2f8fc66-9b8b-4743-9a1d-1173ab1aa723.png)
![image](https://user-images.githubusercontent.com/21735205/236994065-680e87e3-ec6b-4a67-a406-cfe39fb27569.png)

5. Same as in 3
![image](https://user-images.githubusercontent.com/21735205/236994297-ac319e39-5cd0-46ce-9a21-9ba9b7c544bd.png)
![image](https://user-images.githubusercontent.com/21735205/236994332-3110b652-93e3-4406-9093-6609528b466f.png)

Tested only on local machine, on production will test tomorrow (need to fix a couple issues)
Also i noticed that in **dev mode** it'll load only used locale but in **prod mode** it'll load all locales

Dev:
![image](https://user-images.githubusercontent.com/21735205/236995150-c88fd474-9733-48ba-90cf-a3736891dec9.png)


Production:
![image](https://user-images.githubusercontent.com/21735205/236994871-ffce48f9-5f83-4431-93bd-8eb13720cb22.png)

Options:
![image](https://user-images.githubusercontent.com/21735205/236995709-08c9326c-0d24-464b-a596-f40261f30c12.png)

**Comment by hi-reeve** [comment]
i think i got the same error, works fine with my local machine. but i got javascript heap out of memory when building the project. im using docker, the resource works fine when memory is 5gb but less than that got the javascript heap out of memory error.

**Comment by cyperdark** [comment]
Look like changing **Head** to **useHead** / **useSeoMeta** solve the leak, and i think that it's because of computed properly been used in **<Head>**

So far memory look normal (below 150), will see how it'll go in 1-2 days

**Comment by kazupon** [comment]
I greatly appreciate your work ♥️

**Comment by cyperdark** [comment]
look like using **t()** inside computed property + using it with **Head** was causing problems, and after moving to useHead/useSeoMeta graph look like this
*the spike at the end is server thing, need to fix it. Have nothing to do with the module*
![image](https://github.com/nuxt-modules/i18n/assets/21735205/98dcb784-9179-482b-8267-569b6e1fdb39)

**Comment by hi-reeve** [comment]
> look like using **t()** inside computed property + using it with **Head** was causing problems, and after moving to useHead/useSeoMeta graph look like this _the spike at the end is server thing, need to fix it. Have nothing to do with the module_ ![image](https://user-images.githubusercontent.com/21735205/237782927-98dcb784-9179-482b-8267-569b6e1fdb39.png)

have you found any workaround?

**Comment by user6785** [comment]
> have you found any workaround?
wdym, i pointed out that i switched from head tag in template to useHead in script

**Comment by cyperdark** [comment]
> have you found any workaround?

i point out that i switched from head tag in template to useHead in script

**Comment by danielroe** [comment]
I can confirm this is still present, when using `i18n` in a computed property after an awaited promise. Here is a minimal reproduction: https://github.com/danielroe/i18n-memory-leak.

**Comment by kazupon** [comment]
I used `node -inspect` and chrome devtools profile to investigate memory leaks.
![image.png](https://volta.s3.fr-par.scw.cloud/image_5b7855dbfa.png)

It seems that memory leaks occur in  top level await on script setup, when computed is reactive to wrap t.

Incidentally, memory leak does not seem to occur when there is no top level await.
The `await` is transformed to `withAsyncContext` by vite, which seems to affect the memory leak. but, I'm not sure if that is the cause.

It could be a problem with the reactivity implementation of `t`.

**Comment by kazupon** [comment]
add information.

like the below code, I've found that if `await` is used after `computed` , no memory leak.

```vue
<script setup lang="ts">
const { $i18n } = useNuxtApp()

const timeLabel = computed(() => $i18n.t('general'))

await new Promise(resolve => setTimeout(resolve, 10))
</script>
```

**Comment by cyperdark** [comment]
> I used `node -inspect` and chrome devtools profile to investigate memory leaks. ![image.png](https://camo.githubusercontent.com/169288fdfbf3ee6ae9ec26f908a6a4fde4a8d89ec7e4728e67cb78cfc9c1794c/68747470733a2f2f766f6c74612e73332e66722d7061722e7363772e636c6f75642f696d6167655f356237383535646266612e706e67)

I dont know how to use this/read -inspect, so can i ask you to test this use case?:

and if it's still have memory leak int it, and if it's not possible to prevent this, then it worth to mention this somewhere, so people will be aware of it
```vue
<script setup lang="ts">
const { t } = useI18n();

const title = computed(() => {
    return `${t('title')}`;
});
</script>
```

```html
<Head>
    <Title>{{ title }}</Title>
</Head>
```

**Comment by kazupon** [comment]
>I dont know how to use this/read -inspect, so can i ask you to test this use case?:

You can try to reproduce the below:

```sh
# build nuxt app
npm run build

# start nuxt app with `node --inspect`
HOST=localhost node --trace-gc --inspect --max-old-space-size=600 ./node_modules/nuxt/bin/nuxt.mjs preview
```

To stress test it:
```sh
npx autocannon --duration 50 http://localhost:3000
````

**Comment by cyperdark** [comment]
> ```
> <script setup lang="ts">
> const { t } = useI18n();
> 
> const title = computed(() => {
>     return `${t('title')}`;
> });
> </script>
> ```

tested, no memory leak for this case, or i tested in wrong way, idk

**Comment by hakan-akgul** [comment]
Hi  

The problem still continues on`@nuxtjs/i18n v8.0.0-rc.5`  
As I remember, I saw `deep copy` function when I dive in heap snapshot on `node.js v16.13.0`  
Sadly, I uninstalled the plugin. Waiting for the fix.

It was our memory graph: 
![image](https://github.com/nuxt-modules/i18n/assets/64319895/1b164485-54f2-481d-9328-bee5513c4f3b)

Hope it helps

**Comment by kazupon** [comment]
@hakan-akgul 
Thank you for your reporting!
We need your minimal reproduction.
Could you give us about it, please? 🙏

**Comment by hakan-akgul** [comment]
Sorry for the late return. 
My colleague found the saved snapshots. 

I need some time; I want to return with some useful information if possible. 

We get the snapshots from test environment but the huge problem on the production. 
The leaks occurred so fast in production.
So, it is hard to understand the root cause from those snapshots.

I don't know if it is useful or not. Maybe you can find a pattern:

- We don't use computed like the examples above.
- We don't use routes like `foo.com/tr/bar`. 
- We use the components that import i18n, directly in layouts.
- We use json files in folders like:
```
languages/en/en.json
languages/tr/tr.json
```

**Comment by sync42johnny** [comment]
> * We don't use routes like `foo.com/tr/bar`.

I've encountered a similar issue in our application. Interestingly, the app would spontaneously switch to Turkish (tr) by itself. Although we do have a route setup for tr, as you've mentioned, the switch occurs without any explicit trigger. It's quite perplexing, and it seems this is related to the issue raised by @hakan-akgul.

**Comment by memic84** [comment]
> > * We don't use routes like `foo.com/tr/bar`.
> 
> I've encountered a similar issue in our application. Interestingly, the app would spontaneously switch to Turkish (tr) by itself. Although we do have a route setup for tr, as you've mentioned, the switch occurs without any explicit trigger. It's quite perplexing, and it seems this is related to the issue raised by @hakan-akgul.

Do you encounter also memory leaks in the application?

**Comment by agracia-foticos** [comment]
Same issue https://github.com/nuxt-modules/i18n/issues/2612

**Comment by BobbieGoede** [comment]
The latest edge release contains a fix for the (what was likely the larger) memory leak, please let me know if you can confirm this in your project! Installing it as alias: `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`, you may need to delete `node_modules` and any lockfiles.

From my testing it seems like there is still a smaller memory leak present, I'm still working on finding the cause and fixing that.

**Comment by s00d** [comment]
In general, I found where you have a leak. The problem is here: https://github.com/nuxt-modules/i18n/blob/64fa2f6f54bdaf9ea031e28a7fd96c7df0dd82a1/src/module.ts#L229 You can't do it this way; the documentation clearly states how variables should be imported using getContents: [[link to the documentation].](https://nuxt.com/docs/api/kit/templates#examples)

Currently, you are passing an object, and as a result, the node cannot clean up the memory because it is passed by reference.

Tomorrow, I will try to refactor it, but I don't understand how to fix this part:

${options.importStrings.length > 0 ? options.importStrings.join("\n") + "\n" : “”}
…
await setupNitro(nuxt, options, template);

**Comment by dargmuesli** [comment]
Also, if you're seeing some `updated` and `head` related debugging information, @BobbieGoede, see my potential finding in https://github.com/unjs/unhead/issues/281#issuecomment-1854059741

**Comment by s00d** [comment]
> The latest edge release contains a fix for the (what was likely the larger) memory leak, please let me know if you can confirm this in your project! Installing it as alias: `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`, you may need to delete `node_modules` and any lockfiles.
> 
> From my testing it seems like there is still a smaller memory leak present, I'm still working on finding the cause and fixing that.
Thank you, this helped.

Before the optimization, it consumed 1GB per 1000 requests. Now, after checking, it consistently stays at the level of 100-300MB. I tested it with 10,000 requests

After 5000 requests, the following error appeared:
```
[nuxt] [request error] [unhandled] [500] Maximum call stack size exceeded
  at useNuxtApp (./.output/server/chunks/app/server.mjs:497:20)  
  at ./.output/server/chunks/app/server.mjs:10255:33  
  at ./.output/server/chunks/app/server.mjs:10255:33  
  at ./.output/server/chunks/app/server.mjs:10258:29  
  at ./.output/server/chunks/app/server.mjs:10258:29  
  at ./.output/server/chunks/app/server.mjs:10258:29  
  at ./.output/server/chunks/app/server.mjs:10258:29  
  at ./.output/server/chunks/app/server.mjs:10258:29  
  at ./.output/server/chunks/app/server.mjs:10258:29  
  at ./.output/server/chunks/app/server.mjs:10258:29  

```

./.output/server/chunks/app/server.mjs:497:20
```
function useNuxtApp() {
```

./.output/server/chunks/app/server.mjs:10255:33
```
function extendBaseUrl(baseUrl, options) {
  return () => {
    var _a;
    const ctx = /* @__PURE__ */ useNuxtApp();
```

It seems that there is an issue with a memory leak, and the extendBaseUrl function is only using i18n. There might be another problem elsewhere.

**Comment by BobbieGoede** [comment]
>After 5000 requests, the following error appeared:

@s00d 
Could you share a reproduction and describe your testing method? And do you use a function to set `baseUrl`? Hitting the maximum call stack should be caused by excessive function calls, maybe there is a loop or recursion happening in your code.

**Comment by s00d** [comment]
> > After 5000 requests, the following error appeared:
> 
> @s00d Could you share a reproduction and describe your testing method? And do you use a function to set `baseUrl`? Hitting the maximum call stack should be caused by excessive function calls, maybe there is a loop or recursion happening in your code.

Sure, of course.
Here's the repo
https://github.com/s00d/max-call-err
It's very simple to check
```bash
npm i
npm run build 
node .output/server/index.mjs 
ab -n 10000 -c 100 http://localhost:3000/
```

ab is a utility for macOS, it allows you to send a bunch of requests in parallel
I'm not sure there are analogues on other OSs, but you can try like this
```bash
// macOS
brew install httpd

// debian
sudo apt-get install apache2-utils

// CentOS
sudo yum install httpd-tools
```
on windows, it should work through bash in theory

The project is completely clean, only i18n is installed, it is reproduced on previous versions.


I've added
Error.stackTraceLimit = Infinity;
to .output/server/index.mjs
Here's the full error stack:

```bash
[nuxt] [request error] [unhandled] [500] Maximum call stack size exceeded
at ./.output/server/index.mjs:12899:10
  at ./.output/server/index.mjs:12904:29
  at ./.output/server/index.mjs:12904:29
  at ./.output/server/index.mjs:12904:29
// ....
  at ./.output/server/index.mjs:12904:29  
  at ./.output/server/index.mjs:12904:29  
  at ./.output/server/index.mjs:12904:29  
  at resolveBaseUrl (./.output/server/index.mjs:11475:12)  
  at extendComposer (./.output/server/index.mjs:11627:22)  
  at ./.output/server/index.mjs:11585:7  
  at EffectScope.run (./.output/server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:42:16)  
  at i18n.install (./.output/server/index.mjs:11584:11)  
  at Object.use (./.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3778:18)  
  at setup (./.output/server/index.mjs:13211:9)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.callAsync (./.output/server/index.mjs:5133:16)  
  at async applyPlugin (./.output/server/index.mjs:6747:35)  
  at async applyPlugins (./.output/server/index.mjs:6767:7)  
  at async createNuxtAppServer (./.output/server/index.mjs:13627:7)  
  at async Object.renderToString (./.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)  
  at async ./.output/server/index.mjs:6118:21  
  at async ./.output/server/index.mjs:5172:22  
  at async Object.handler (./.output/server/index.mjs:2293:19)  
  at async Server.toNodeHandle (./.output/server/index.mjs:2482:7)

```

The memory leak is completely gone. After finishing the requests, the memory consumption resets to normal. However, the problem with "Maximum call stack size exceeded" error is definitely related to i18n. If I disable the module, the issue disappears.

The problem lies in the extendBaseUrl method of the baseUrl function. The baseUrl function is referencing itself, and with each subsequent request, the nesting of calls increases. After around 6500 requests, everything crashes.

I suspect that it all starts here:
```
nuxtI18nOptions.baseUrl = extendBaseUrl(nuxtI18nOptions.baseUrl, {
```
The method is referencing itself, leading to an infinite loop.

Maybe this fix could help:

https://github.com/nuxt-modules/i18n/pull/2620

But it's still better to double-check everything

**Comment by BobbieGoede** [comment]
Thanks for providing the reproduction and testing method, I have been able to replicate this locally and I think you're right about it being caused by `extendBaseUrl`. I guess it is wrapping itself in a new function on every request 🤯..

Based on the issue @s00d found I'll keep this issue open until that has been fixed. While the memory usage is more stable in `rc.10`, I can't recommend using it with this issue present! 

Will be checking out the provided fix, expect another release soon.

**Comment by dargmuesli** [comment]
Server be chillin' again. Great! :sunglasses: 

![image](https://github.com/nuxt-modules/i18n/assets/4778485/a478f510-2ad5-4494-a60f-28a1724049be)

("Festplatte" being hard drive)

**Comment by BobbieGoede** [comment]
Closing as the memory leak in the provided reproductions have been fixed, we will track the other potential leak in #2612. If anyone is still experiencing memory leaks, please let us know there (and provide a reproduction if possible 🙏)

**Comment by matheusgasparx** [comment]
i would like to know if this problem is really caused by i18n, or if any call to pinia can cause this problem, i have the same problem but i dont have i18n in the project yet, and im also unable to locale it in the project

**Comment by BobbieGoede** [comment]
@matheusgasparx 
The memory leak discussed in this issue was related to both nuxt-i18n and vue-i18n but has since been resolved.

Memory leaks can be tricky to debug, it could be caused by dependencies or your own code. I suggest using chrome devtools to debug heap snapshots, and removing dependencies and sections of code from your project to see if this prevents the memory leak. This way you'll be able to locate the source of the leak to report it or work on resolving it.

This issue is resolved and quite old, to prevent pinging participants unnecessarily I'm locking this issue.
