### ISSUE TITLE
431 Request Header Fields Too Large

### ISSUE THREAD

**Issue by 1129zaj** [nuxt-modules/i18n#2038]
### Environment

"@nuxtjs/i18n": "8.0.0-beta.11"

### Reproduction

"@nuxtjs/i18n": "8.0.0-beta.11"

### Describe the bug

"@nuxtjs/i18n": "8.0.0-beta.11",

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is deplicated with #2008.
This issue will be resolved by #2025 

Thanks!

**Comment by kogratte** [comment]
Did you found a workaround during your analyse?
