### ISSUE TITLE
nuxt i18n not working in IE throwing SCRIPT1006: Expected ')'

### ISSUE THREAD

**Issue by patelatit53** [nuxt-modules/i18n#2041]
I am trying to make the nuxt-i18n work for IE document mode 11.

SCRIPT1006: Expected ')'

Is anyone faced the same issue before and knows how to resolve it?

**Comment by kazupon** [comment]
Unfortunately, IE 11 had already retired.
So we would not maintain for it.
https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/

Thanks!
