### ISSUE TITLE
Locale is lost on navigation

### ISSUE THREAD

**Issue by some-user123** [nuxt-modules/i18n#2042]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zwtg8a?file=pages/index.vue

### Describe the bug

Locale is not preserved when navigating between pages.

Reproduction:
1. Switch locale to "fr" by clicking button "fr". 
2. Text changes from "Welcome" to "Bienvenue".
3. Click on link "Page2".

Expected: Text remains "Bienvenue" and locale remains "fr".
Actual: Text reverts to "Welcome" and locale switches back to "en".

**Comment by default64bit** [comment]
You need to use localePath() inside the nuxt-link:
`<NuxtLink :to="localePath('/second')">Page2</NuxtLink>`

You can read about this in the documentation [here](https://v8.i18n.nuxtjs.org/getting-started/basic-usage#url-path)

**Comment by some-user123** [comment]
I don't want to localize my URLs.

The documentation says "You can localize URL path with using useLocalePath."
Are you saying, localizing URLs is a must if I want to use this module? (Then I would suggest this as a potential improvement...)

**Comment by default64bit** [comment]
localePath() only adds prefixes to your links URL (based on what strategy you've chosen)

so `<NuxtLink :to="localePath('/second')">Page2</NuxtLink>`
will be rendered to
`<a href="/en/second">Page2</a>`
or
`<a href="/fr/second">Page2</a>`

It does not translate your URLs

**Comment by some-user123** [comment]
That's understood :)

Still, I don't want to localize the URLs, even with a prefix.

**Comment by default64bit** [comment]
If you don't want prefixes in your links then set the strategy to [no_prefix](https://v8.i18n.nuxtjs.org/guide/routing-strategies#no_prefix) in your `i18n` config

But you need cookies to keep track of current local by setting up `i18n.detectBrowserLanguage`  in the nuxt.config.ts file
For a more detailed explanation check the [browser-language-detection](https://v8.i18n.nuxtjs.org/guide/browser-language-detection#browser-language-detection) docs

**Comment by some-user123** [comment]
Hooray 🎆🎉 Thanks :+1:

(Maybe that would be a sensible default to allow progressive use of i18n.)
