### ISSUE TITLE
fix: `i18n-t` does not work in slot of component with own translations

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#2045]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-akfq2d-wlyakj?file=components/Test.vue

### Describe the bug

Using `i18n-t` as slot content for a component with own translations, the translation does not work. However, using `t` does work!

I expect `i18n-t` to work as well.

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is vue-i18n.
I've opened this issue on vue-i18n-next repo
https://github.com/intlify/vue-i18n-next/issues/1392

Thanks!
