### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by JustinJsn** [nuxt-modules/i18n#2047]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11-28058519.a069f38
- Build Modules:    -
------------------------------

### Reproduction

repo: https://stackblitz.com/edit/nuxt-starter-dylnd8

### Describe the bug

When use `defineI18nLocale` dynamically load locale messages, it would happen `403 Forbidden` error.

![image](https://user-images.githubusercontent.com/51405100/236745311-d7e69c66-cfab-4a4e-a427-b687e513c72f.png)

> Looks like a path splicing error.

**Comment by JustinJsn** [comment]
Look like is this function error `loadPrecompiledMessages`.

![image](https://user-images.githubusercontent.com/51405100/236749936-55af10f5-72db-4fa0-a5f5-c4f5c7948aef.png)

**Comment by kazupon** [comment]
I'm fixing now at #2048

**Comment by kazupon** [comment]
I've fixed this issue.
Please check edge channel `8.0.0-beta.11-28059008.d1499b6` version.

Thanks!

**Comment by JustinJsn** [comment]
So nice!It work fine.
