### ISSUE TITLE
Inconsistent TM return type in dev and build environment 

### ISSUE THREAD

**Issue by VeselyJan92** [nuxt-modules/i18n#2050]
### Environment

- Operating System: Linux
- Node Version:     v19.8.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      components, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11-28059008.d1499b6
- Build Modules:    -

### Reproduction

https://github.com/VeselyJan92/i18n-nuxt-bug/blob/master/pages/index.vue

### Describe the bug

Message compilation / rendering works differently on dev and release version. 

`tm` returns `object` instead of `array`. 
```
<template>

  <h1>{{ t("simple_key") }}</h1>

  <h2>v-for</h2>
  <div v-for="item in tm('items')">
    <p>{{ rt(item.name)}}</p>
  </div>

  <h2>map</h2>
  <p>
    Works only for: yarn run dev
    <br>
    Does not work for: yarn run build && yarn run start
  </p>

  <div v-for="name in mappedItems">
    <p>{{ name}}</p>
  </div>
  
</template>

<script setup>

const {t, tm, rt} = useI18n();

const mappedItems = tm('items').map(item => rt(item.name))

</script>
```

```
export default defineI18nConfig(async () => {
    return {
      legacy: false,
 
      messages: {
        cs: await getLocale('cs'),
        de: await getLocale('en'),
      }
    }
  })
  
  async function getLocale(locale: string) {
    return {
        simple_key: "header",
        items:[
            { name: "item 1"},
            { name: "item 2"},
            { name: "item 3"}
        ]
    };
  }
```

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is vue-i18n.
we hope you will open this issue on vue-i18n-next repo.
https://github.com/intlify/vue-i18n-next

Thanks!

**Comment by VeselyJan92** [comment]
Issue: https://github.com/intlify/vue-i18n-next/issues/1397

**Comment by kazupon** [comment]
I found out nuxt i18n module has bug for array resources
I've opened this issue.

**Comment by kazupon** [comment]
@VeselyJan92 
Hi!
I've just fixed this issue.
You can try to use with edge channel version.

And, I appreciate your Github Sponsors ❤️ 
Thank you very much!
