### ISSUE TITLE
ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'

### ISSUE THREAD

**Issue by gyhyfj** [nuxt-modules/i18n#2055]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      modules, vite, css, imports, pinia, sitemap, app, ignore, telemetry, appConfig, devServer, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.8, @pinia-plugin-persistedstate/nuxt@1.1.1, @element-plus/nuxt@1.0.4, @nuxtjs/robots@3.0.0, nuxt-simple-sitemap@2.4.11, @nuxtjs/i18n@8.0.0-beta.10
- Build Modules:    -

### Reproduction

It's monorepo on pnpm with .npmrc at root path, if without this file, nuxt3 cannot work:
```
shamefully-hoist=true
strict-peer-dependencies=false
```

### Describe the bug

In my monorepo project,
when I add  `"@nuxtjs/i18n": "8.0.0-beta.10"` to `package.json` for my nuxt3 project, I can neither install deps nor run dev.
It told me :
```
 ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'
│   at tryResolve (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.10_vue@3.2.47/node_modules/@nuxtjs/i18n/dist/module.mjs:116:9)
│   at async setupAlias (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.10_vue@3.2.47/node_modules/@nuxtjs/i18n/dist/module.mjs:215:38)
│   at async setup (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.10_vue@3.2.47/node_modules/@nuxtjs/i18n/dist/module.mjs:964:5)
│   at async normalizedModule (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxt+kit@3.4.3/node_modules/@nuxt/kit/dist/index.mjs:170:17)
│   at async installModule (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxt+kit@3.4.2/node_modules/@nuxt/kit/dist/index.mjs:450:95)
│   at async initNuxt (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/nuxt@3.4.2_@types+node@18.16.5_sass@1.62.0_typescript@5.0.4/node_modules/nuxt/dist/index.mjs:2619:7)   
│   at async loadNuxt (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/nuxt@3.4.2_@types+node@18.16.5_sass@1.62.0_typescript@5.0.4/node_modules/nuxt/dist/index.mjs:2680:5)   
│   at async loadNuxt (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxt+kit@3.4.3/node_modules/@nuxt/kit/dist/index.mjs:545:19)
│   at async Object.invoke (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/nuxi@3.4.2/node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
│   at async _main (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/nuxi@3.4.2/node_modules/nuxi/dist/cli.mjs:48:20)
```

**Comment by kazupon** [comment]
Thank you for your reporting!

We need to reproduce your minimal repo to resolve this issue.
Could you give us it please? 🙏

**Comment by gyhyfj** [comment]
[Here](https://github.com/gyhyfj/nuxt-module-i18n-reproduct) is the minimal repo @kazupon

**Comment by OmarMcAdam** [comment]
Ran into same issue in Monorepo with pnpm
`ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'`
When manually adding dependency of vue-i18n, it fails with
`ERROR  Cannot resolve @intlify/vue-router-bridge on pnpm! please install it on 'node_modules'`

Tried to reproduce in fresh project - works without any errors

Unlike @gyhyfj I only import it once in one webapp within the monorepo

**Comment by dargmuesli** [comment]
What about putting `.npmrc`s inside the subproject directories? For the Nuxt directory it could contain `shamefully-hoist=true`.

**Comment by gyhyfj** [comment]
> What about putting `.npmrc`s inside the subproject directories? For the Nuxt directory it could contain `shamefully-hoist=true`.

I did that, nuxt3 told me that it cannot resolve vue then🤣

`shamefully-hoist` of nuxt3 is really shamefully, I encounter [another problem](https://github.com/element-plus/element-plus/issues/10979) today when I use `@element-plus/nuxt` , if I refresh some pages of my nuxt3 project, it will return 500, but if I navigate to these pages from already hydrated success pages, everything is ok. Luckly I found this bug in time and fixed it by mv deps manually:
```ts
await $`mkdir ./.output/server/functions/node_modules/@popperjs`
await $`mv ./.output/server/functions/node_modules/@sxzz/popperjs-es ./.output/server/functions/node_modules/@popperjs/core`
```

It made many of pnpm users in nuxt ecosystem working painfully.

**Comment by dargmuesli** [comment]
> but if I navigate to these pages from already hydrated success pages, everything is ok

Check the browser console, most likely there is the equivalent of the 500 server error.

I think you should track https://github.com/nuxt/nuxt/issues/14146 and this issue can be closed as the source of the issue does not really seem to be this repository.

**Comment by trandaison** [comment]
In my case, I have both `@nuxtjs/i18n` and `vue-i18n` in package.json. Removing `vue-i18n` and it works again.
```
    "@nuxtjs/i18n": "8.0.0-beta.12",
    "vue-i18n": "^9.2.2",
```

**Comment by marco-land** [comment]
I had to add these packages to my dependencies:
```json
"@intlify/vue-i18n-bridge": "^0.8.0",
"@intlify/vue-router-bridge": "^0.8.0",
"vue-i18n": "9.3.0-beta.19",
"vue-i18n-routing": "^0.13.0"
```

**Comment by dargmuesli** [comment]
@marco-land do you have pnpm configured to shamefully-hoist?

**Comment by marco-land** [comment]
> @marco-land do you have pnpm configured to shamefully-hoist?

Yes, I use the `.npmrc` created from nuxt:

```
shamefully-hoist=true
strict-peer-dependencies=false
```

**Comment by dargmuesli** [comment]
Ok. Please show the directory structure of your project, especially the location of `package.json`s, `pnpm-lock.yaml`s , `pnpm-workspace.yaml` and `.npmrc`s (+ content), or give a link to your project (or even better a minimal reproduction) :pray:

**Comment by marco-land** [comment]
Of course, here is a [very basic setup](https://github.com/marco-land/nuxt-3-i18n-reproduction-2055) of what I was using.

**Comment by dargmuesli** [comment]
Thanks! You should be able to observe that running a `pnpm install` inside the `web` project of yours makes it work (because its `.npmrc` is respected then. It does not seem to be respected when running `pnpm install` in the root directory. So this is a pnpm / nuxt / workspace configuration issue, not nuxt-i18n's fault, so I'm going to close this issue for now.

Make sure to remove all `node_modules` directories when changing your pnpm configuration to make sure you get a clean result.

**Comment by dargmuesli** [comment]
Also, you can see if placing `shared-workspace-lockfile=false` into a root `.pnpmrc` makes `.pnpmrc`s in subdirectories be respected or if any other [option](https://pnpm.io/npmrc) fits your needs. Be sure to post here if you find what's working for you so others can find a solution as well! :)

**Comment by marco-land** [comment]
Adding a `.npmrc` with `shared-workspace-lockfile=false` to my root folder works!

**Comment by antal-k** [comment]
I still have this problem

**Comment by dargmuesli** [comment]
If you expect help, I'd recommend to not only post "me too" comments, but explain your problem and possible solutions tried in detail :pray:

**Comment by antal-k** [comment]
@dargmuesli well, the thing is it worked last week, my mac died, got a new one and now it's not working, so I have no clue what's wrong with it because I didn't really touch the code. using the same lock file, etc.

stack:
```
Nuxi 3.5.0
│ [@nuxtjs/i18n]  WARN  Vue I18n configuration file does not exist at i18n.config. Skipping...
│ [@nuxtjs/i18n]  WARN  Ignore Vue I18n configuration file does not exist at i18n.config on layer /Users/antal/melo/core/modules/nuxt-frontend/layers/tairo. Skipping...
│ [@nuxtjs/i18n]  WARN  Ignore Vue I18n configuration file does not exist at i18n.config on layer /Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/@shuriken-ui+nuxt@0.2.9_nuxt@3.5.0/node_modules/@shuriken-ui/nuxt.
│ [@nuxtjs/i18n]  WARN  Ignore Vue I18n configuration file does not exist at i18n.config on layer /Users/antal/melo/core/modules/nuxt-frontend/layers/tairo-layout-collapse. Skipping...
│ [@nuxtjs/i18n]  WARN  Ignore Vue I18n configuration file does not exist at i18n.config on layer /Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/nuxt-seo-kit@1.3.8/node_modules/nuxt-seo-kit. Skipping...
│  ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'
│   at tryResolve (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.12-28113576.7bc33c3/node_modules/@nuxtjs/i18n-edge/dist/module.mjs:208:9)
│   at async setupAlias (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.12-28113576.7bc33c3/node_modules/@nuxtjs/i18n-edge/dist/module.mjs:462:38)
│   at async setup (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.12-28113576.7bc33c3/node_modules/@nuxtjs/i18n-edge/dist/module.mjs:1713:5)
│   at async normalizedModule (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/@nuxt+kit@3.5.2/node_modules/@nuxt/kit/dist/index.mjs:170:17)
│   at async installModule (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:440:95)
│   at async initNuxt (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/nuxt@3.5.0_@parcel+watcher@2.1.0_@types+node@20.2.5_eslint@8.41.0_typescript@5.0.4_vue-tsc@1.6.5/node_modules/nuxt/dist/index.mjs:2887:7)
│   at async loadNuxt (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/nuxt@3.5.0_@parcel+watcher@2.1.0_@types+node@20.2.5_eslint@8.41.0_typescript@5.0.4_vue-tsc@1.6.5/node_modules/nuxt/dist/index.mjs:2950:5)
│   at async loadNuxt (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/@nuxt+kit@3.5.2/node_modules/@nuxt/kit/dist/index.mjs:534:19)
│   at async Object.invoke (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/nuxi@3.5.0/node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
│   at async _main (/Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/nuxi@3.5.0/node_modules/nuxi/dist/cli.mjs:48:20)
└─ Failed in 1.2s at /Users/antal/melo/core/modules/nuxt-frontend/.app
```

```
npm ls vue-i18n
tairo@1.1.2 /Users/antal/melo/core/modules/nuxt-frontend
├─┬ @intlify/unplugin-vue-i18n@0.10.1 extraneous -> ./node_modules/.pnpm/@intlify+unplugin-vue-i18n@0.10.1_vue-i18n@9.3.0-beta.19/node_modules/@intlify/unplugin-vue-i18n
│ └── vue-i18n@9.3.0-beta.19 -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
├─┬ @intlify/vue-i18n-bridge@0.8.0 extraneous -> ./node_modules/.pnpm/@intlify+vue-i18n-bridge@0.8.0_vue-i18n@9.3.0-beta.19/node_modules/@intlify/vue-i18n-bridge
│ └── vue-i18n@9.3.0-beta.19 -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
├─┬ @nuxtjs/i18n@npm:@nuxtjs/i18n-edge@8.0.0-beta.12-28113576.7bc33c3 invalid: "npm:@nuxtjs/i18n-edge" from the root project -> ./node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.12-28113576.7bc33c3/node_modules/@nuxtjs/i18n-edge
│ ├─┬ @intlify/unplugin-vue-i18n@0.10.1 -> ./node_modules/.pnpm/@intlify+unplugin-vue-i18n@0.10.1_vue-i18n@9.3.0-beta.19/node_modules/@intlify/unplugin-vue-i18n
│ │ └── vue-i18n@9.3.0-beta.19 deduped -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
│ ├─┬ vue-i18n-routing@0.13.0 -> ./node_modules/.pnpm/vue-i18n-routing@0.13.0_vue-i18n@9.3.0-beta.19/node_modules/vue-i18n-routing
│ │ └── vue-i18n@9.3.0-beta.19 deduped invalid: "npm:vue-i18n@next" from node_modules/.pnpm/vue-i18n-routing@0.13.0_vue-i18n@9.3.0-beta.19/node_modules/vue-i18n-routing, "npm:vue-i18n@next" from node_modules/.pnpm/vue-i18n-routing@0.13.0_vue-i18n@9.3.0-beta.19/node_modules/vue-i18n-routing -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
│ └── vue-i18n@9.3.0-beta.19 -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
├─┬ vue-i18n-routing@0.13.0 extraneous -> ./node_modules/.pnpm/vue-i18n-routing@0.13.0_vue-i18n@9.3.0-beta.19/node_modules/vue-i18n-routing
│ ├─┬ @intlify/vue-i18n-bridge@0.8.0 -> ./node_modules/.pnpm/@intlify+vue-i18n-bridge@0.8.0_vue-i18n@9.3.0-beta.19/node_modules/@intlify/vue-i18n-bridge
│ │ └── vue-i18n@9.3.0-beta.19 deduped -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
│ └── vue-i18n@9.3.0-beta.19 invalid: "npm:vue-i18n@next" from node_modules/.pnpm/vue-i18n-routing@0.13.0_vue-i18n@9.3.0-beta.19/node_modules/vue-i18n-routing, "npm:vue-i18n@next" from node_modules/.pnpm/vue-i18n-routing@0.13.0_vue-i18n@9.3.0-beta.19/node_modules/vue-i18n-routing -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
└── vue-i18n@9.3.0-beta.19 extraneous -> ./node_modules/.pnpm/vue-i18n@9.3.0-beta.19/node_modules/vue-i18n

npm ERR! code ELSPROBLEMS
npm ERR! extraneous: vue-i18n@9.3.0-beta.19 /Users/antal/melo/core/modules/nuxt-frontend/node_modules/vue-i18n
npm ERR! invalid: vue-i18n@9.3.0-beta.19 /Users/antal/melo/core/modules/nuxt-frontend/node_modules/.pnpm/vue-i18n-routing@0.13.0_vue-i18n@9.3.0-beta.19/node_modules/vue-i18n
```

**Comment by dargmuesli** [comment]
> and possible solutions tried

What about those? I'd recommend to open a new issue to not spam everyone subscribed to this one.
To me it sounds most likely that on your old computer there was a version of i18n still lingering around, which would have been removed with the result you showed now if you had removed your `node_modules` even on your old machine.

**Comment by raishid** [comment]
What was the solution to this? I have a workspace and I have the same problem.

**Comment by dargmuesli** [comment]
If you read the above comments and still have the problem, please submit a minimal reproduction instead of adding "me too" comments, thanks!

**Comment by antal-k** [comment]
I just cloned my repo to a new folder (earlier it was in a repo with submodules), and suddenly it started to work.
So I don't know the main problem; I tried every solution but nothing helped.

**Comment by Ballpin** [comment]
Can't we just have vue-i18n as peerDependency and vue-i18n as an external?

**Comment by Psycarlo** [comment]
Still no fix?

**Comment by LeCoupa** [comment]
For people using pnpm and getting issues when `shared-workspace-lockfile=false` is added to the root `.npmrc` file.

The best solution we came up with was to to add these packages to the `package.json` file of our nuxt app.

```
"@intlify/message-compiler": "9.4.1",
"@intlify/shared": "9.4.1",
"@intlify/vue-i18n-bridge": "1.0.1",
"@intlify/vue-router-bridge": "1.0.1",
"vue-i18n": "9.4.1",
"vue-i18n-routing": "1.1.1",
```

**Comment by bikedawuwang** [comment]
`
"@nuxtjs/i18n": "8.0.0-rc.4"
`

This problem still exists, has it not been fixed yet?

**Comment by Ballpin** [comment]
> `"@nuxtjs/i18n": "8.0.0-rc.4"`
> 
> This problem still exists, has it not been fixed yet?

seems to be fixed for me, get latest nuxt 3.7.4 and rc5 instead.

**Comment by Ballpin** [comment]
> `"@nuxtjs/i18n": "8.0.0-rc.4"`
> 
> This problem still exists, has it not been fixed yet?

seems to be fixed for me, get latest nuxt and rc5 instead.

**Comment by Psycarlo** [comment]
I am using:
Node 18.13.0
Turborepo (monorepo) (my nuxt web project in under `apps/web` folder)
Nuxt 3.7.4
@nuxtjs/i18n 8.0.0-rc.5

After `pnpm i`, I get the following error:

`ERROR  Cannot resolve vue-i18n on pnpm!`

@Ballpin still not fixed for me.

**Comment by Ballpin** [comment]
Forgot mention that i had latest pnpm(8.8.0). And in my .npmrc i had shamefully hoisted always on. 

Another way to fix it is to add install package on the root level package.json.

The last workaround is a long way and i recommend add it to script if you decide to go this path.

1. If you have `@nuxtjs/i18n` installed. Remove it

2. Install the nuxt packages as usual.

3. Install `@nutxjs/i18n` with shameful option as it says im github repo.

_Note run this from the folder were nuxt is_. If you fail do this just start from step 1 again.

Also if postinstall from the package fails ignore it. Important is that last step works.

4. Navigate to the project folder were you have nuxt config file. 

From there run `pnpm nuxi prepare`.

Note when you remove .nuxt or add new package you will need to redo this. It is a pain and far from a good solution. But its the best i got, others have tried it and confirmed that it works for them to.

Thats why i recommend write a script for it.

But as i said earlier after latest nuxt version (7.4.0 i think) and rc5 it just went away. The folks that tried my earlier workaround confirmed it went away from them to.


Last but not least if you use private registry make sure it is also working properly. Some registry does not work in the best way with pnpm or other pkg managers.

**Comment by Psycarlo** [comment]
`shamefully-hoist=true` did the trick for me

**Comment by dargmuesli** [comment]
@kazupon @BobbieGoede please consider locking this issue :raised_hands: 
All information that helped commenters resolve this issue has been provided already, some more than once. Since this issue has been closed many comments did not add much more than a "me too" message (except for @Ballpin's great summary).
Having this issue closed should motivate others to open new issues including a minimal reproduction instead of adding length to an issue that is related to pnpm usage, not to this repository specifically.
Of course, "me too" comments could be hidden as well to let the helpful comments pop out a bit more, but that'd be optional.
