### ISSUE TITLE
Module is conflicting with nuxt/devtools

### ISSUE THREAD

**Issue by jpsc** [nuxt-modules/i18n#2059]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.4.0`
- Package Manager:  `npm@9.6.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jpsc/beta.11.bug 

https://stackblitz.com/github/jpsc/beta.11.bug 

### Describe the bug

I'm adding `@nuxt/devtools` inside of a module with kit's `installModule` and it doesn't seem to work properly.
If I add the via the `nuxt.config` on the playground it works, but inside of the module not really.

I'm adding this here because if I remove `nuxt/i18n` module it works.

### Additional context

One of the errors is:

> Cannot read properties of undefined (reading 'Symbol(vue-i18n-routing-gor)')

**Comment by dine** [comment]
Some more additional context:

When adding `@nuxt/devtools` via `installModule`

`addImports` is called here:
https://github.com/nuxt-modules/i18n/blob/next/src/module.ts#L354

But the hook `imports:extend` is not called:
https://github.com/nuxt/nuxt/blob/main/packages/kit/src/imports.ts#L9

**Comment by kazupon** [comment]
I believe the problem is with nuxt devtools or nuxt kit (installModule).

The nuxt i18n module does not implement in a way that interferes with nuxt devtools or violates nuxt kit API usage.

Please open an issue on nuxt or nuxt devtools 🙏 

Thanks!

**Comment by rmdecourt** [comment]
If you are still having this problem as of 2025...
Please refer to the last comment here ⇒ https://github.com/nuxt/devtools/issues/827

Add this to your nuxt.config.ts:
```ts
i18n: {
  bundle: {
    optimizeTranslationDirective: false,
  },
}
```
