### ISSUE TITLE
Cannot read properties of undefined (reading 'options') when running on Gitlab runner

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt-modules/i18n#2060]
### Environment

- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@8.11.0
- Builder:          vite
- User Config:      telemetry, runtimeConfig, css, modules
- Runtime Modules:  nuxt-purgecss@2.0.0, @nuxtjs/i18n@8.0.0-beta.11-28059008.d1499b6
- Build Modules:    -

### Reproduction

Unfortunately I don't have a reproduction for this bug as my project builds perfectly fine on my local machine however fails when being run via the gitlab runner. If there's any way I can provide additional information as to the cause of this error I'd be happy to assist.

### Describe the bug

[log] Nuxi 3.4.3
[log] Nuxt 3.4.3 with Nitro 2.4.0
[error] Cannot read properties of undefined (reading 'options')
  at _default (node_modules/@nuxtjs/i18n/src/index.js:15:92)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:450:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2680:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:2743:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:545:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:37:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)

**Comment by kazupon** [comment]
Thank you for your reporting!

I noticed that your stacktrace is weird.

>at _default (node_modules/@nuxtjs/i18n/src/index.js:15:92)

when nuxt i18n module build,  dist fileds is built the following structured:

```
$ tree dist
dist
├── module.cjs
├── module.d.ts
├── module.json
├── module.mjs
├── runtime
│   ├── composables.d.ts
│   ├── composables.mjs
│   ├── internal.d.ts
│   ├── internal.mjs
│   ├── plugins
│   │   ├── composition.d.ts
│   │   ├── composition.mjs
│   │   ├── i18n.d.ts
│   │   ├── i18n.mjs
│   │   ├── legacy.d.ts
│   │   ├── legacy.mjs
│   │   ├── meta.d.ts
│   │   └── meta.mjs
│   ├── server
│   │   ├── dynamic.d.ts
│   │   ├── dynamic.mjs
│   │   ├── precompile.d.ts
│   │   └── precompile.mjs
│   ├── types.d.ts
│   ├── utils.d.ts
│   └── utils.mjs
└── types.d.ts
```

**Comment by bitbytebit1** [comment]
I resolved this by using yarn to install my packages instead of npm on the gitlab runner.

Edit: happy to see this issue closed
