### ISSUE TITLE
Nuxt generate doesn't include linked transations (@:)

### ISSUE THREAD

**Issue by Degete** [nuxt-modules/i18n#2061]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.10
- Build Modules:    -

### Reproduction

Linked to a [repository](https://github.com/Degete/nuxt-i18n-linked-locale-bug) which reproduces the bug.

### Describe the bug

When running the server with `yarn dev` it works as expected.
<img width="400" alt="image" src="https://github.com/nuxt-modules/i18n/assets/5583828/8a0a3f07-4db6-4994-8a60-6911c9e48c39">

However when generating a static website with `yarn generate`, this does not include the proper linked translation but instead the static value aka `@:value`, can be check opening the `index.html` or with `yarn preview`.
<img width="394" alt="image" src="https://github.com/nuxt-modules/i18n/assets/5583828/7d105816-1f44-4629-80f7-5f4df420894a">

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is resolved with edge channel version.
You can install it.
```
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
```

Thanks!
