### ISSUE TITLE
fix(composables): `useRoute` inside middleware

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#2064]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ccvbch?file=pages/index.vue

### Describe the bug

Using composables inside middleware yields e.g. `[nuxt] Calling useRoute within middleware may lead to misleading results. Instead, use the (to, from) arguments passed to the middleware to access the new and old routes."`

### Additional context

I'm going to submit a PR with a proposed fix.

**Comment by sync42johnny** [comment]
@ineshbose Any updates?

**Comment by dargmuesli** [comment]
This is already released since [v8.0.0-beta.13](https://github.com/nuxt-modules/i18n/releases/tag/v8.0.0-beta.13)

**Comment by hmingv** [comment]
In version [v8.0.0](https://github.com/nuxt-modules/i18n/tree/v8.0.0), this problem still exists.

https://stackblitz.com/edit/github-ccvbch-win87v

**Comment by onurusluca** [comment]
Still having this problem

**Comment by PeterPlevko** [comment]
Still having this problem

**Comment by BobbieGoede** [comment]
@onurusluca @PeterPlevko 
If you're still experiencing this issue using the latest release, please open a new issue with a minimal reproduction.

Locking this issue as it's unlikely (but not impossible) that the root cause for new issues is the same.
