### ISSUE TITLE
fix: optional chain undefined in middleware since beta 11

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#2067]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ccvbch-qurh4a?file=pages/index.vue

### Describe the bug

Using an optional chain (`x.test?.test`) inside a middleware leads to a 500 internal server error since `8.0.0-beta.11`. One does not need to use any nuxt-i18n related code in the middleware, it's enough to have the module enabled.

### Additional context

The issue does also occur in beta 12, but not in beta 10.

**Comment by dargmuesli** [comment]
Here is a comparison of the code being generated in beta 10:
```js
(a = {}.test) != null && a.test && console.log("test"),
```

to beta 11 / 12:

```js
const n = {};
if (_optionalChain([n, "access", a=>a.test, "optionalAccess", a=>a.test]) && console.log("test"),
```

I wonder why there appears an `_optionalChain` when using i18n?

**Comment by dargmuesli** [comment]
Found the culprit: the [addition](https://github.com/nuxt-modules/i18n/commit/c0b701c7ec36d2b1988defbf4e4079da7e011ba3) of `@mizchi/sucrase`. Having added that dependency all files generated by `nuxt build` contain the `_optionalChain` transformation:
![image](https://github.com/nuxt-modules/i18n/assets/4778485/f03d63a1-a70c-4538-9828-b3ffaaea32f8)

Notice that only `entry.js` and `server.js` are missing the function definition, the individual files like `AccoutProfilePicture.js` include the function definition.

Main question being: why are **all files transformed** by that dependency? I'm sure transforms should only be made for locale source files? :flushed: 
Isn't that a large performance drawback?

---

potentially related: https://github.com/alangpierce/sucrase/issues/602

**Comment by kazupon** [comment]
Thank you for your reporting!

This is an implementation miss in transformInclude in `src/transform/proxy.ts` or `src/transform/dynamic.ts`.
This hook needs to be corrected so that only locale resources are filtered.

**Comment by dargmuesli** [comment]
Great pointer! I'm not able to contribute a fix right now due to time constraints.

**Comment by simkuns** [comment]
> Found the culprit: the [addition](https://github.com/nuxt-modules/i18n/commit/c0b701c7ec36d2b1988defbf4e4079da7e011ba3) of `@mizchi/sucrase`. Having added that dependency all files generated by `nuxt build` contain the `_optionalChain` transformation: ![image](https://user-images.githubusercontent.com/4778485/237825667-f03d63a1-a70c-4538-9828-b3ffaaea32f8.png)
> 
> Notice that only `entry.js` and `server.js` are missing the function definition, the individual files like `AccoutProfilePicture.js` include the function definition.
> 
> Main question being: why are **all files transformed** by that dependency? I'm sure transforms should only be made for locale source files? 😳 Isn't that a large performance drawback?
> 
> potentially related: [alangpierce/sucrase#602](https://github.com/alangpierce/sucrase/issues/602)

Thank you for mentioning this! Replacing `@mizchi/sucrase` with `alangpierce/sucrase` and adding `disableESTransforms: true` to transform() helped me to temporarily work around this issue.

**Comment by hymair** [comment]
I am running in to this issue as well with the latest releases.

**Comment by BobbieGoede** [comment]
It looks like this issue has been fixed, no error is thrown after updating the dependencies in [the reproduction](https://stackblitz.com/edit/github-ccvbch-hjrucy?file=pages%2Findex.vue,app.vue).

Closing this for now, let me know if you're still running into this issue with the latest version!
