### ISSUE TITLE
i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release

### ISSUE THREAD

**Issue by voyageh** [nuxt-modules/i18n#2069]
### Environment

    "@element-plus/nuxt": "^1.0.4",
    "@nuxtjs/device": "^3.1.0",
    "@nuxtjs/i18n": "8.0.0-beta.12",
    "@types/node": "^18",
    "element-plus": "^2.3.4",
    "nuxt": "^3.4.3",
    "prettier": "^2.8.8",
    "sass": "^1.62.1"

### Reproduction

```javascript
  i18n: {
    lazy: true,
    langDir: "locales",
    defaultLocale: "zh-CN",
    locales: [
      {
        code: "zh-CN",
        iso: "zh-CN",
        name: "简体中文",
        file: "zh-CN.json",
      },
      {
        code: "en-US",
        iso: "en-US",
        name: "English",
        file: "en-US.json",
      },
    ],
  },
```

### Describe the bug

1. Vue I18n configuration file does not exist at i18n.config. Skipping...  
2. i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release.                       
If you're using it, please use i18n:registerModule instead.

**Comment by ineshbose** [comment]
https://v8.i18n.nuxtjs.org/guide/extend-messages

**Comment by ahoiroman** [comment]
The docs however state, that this is only for module authors...?
