### ISSUE TITLE
Error when using i18n on Layer: [vite-node] [ERR_INVALID_ARG_VALUE]

### ISSUE THREAD

**Issue by wypratama** [nuxt-modules/i18n#2073]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.4.0`
- Package Manager:  `pnpm@8.1.1`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `app`, `quasar`, `i18n`
- Runtime Modules:  `pinceau/nuxt`, `nuxt-quasar-ui@1.7.3`, `@nuxtjs/i18n@8.0.0-beta.12`, `nuxt-vitest`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/node-2avl69?file=README.md

### Describe the bug

Using Nuxt i18n in a layer project keep showing error below if I put i18n.config under root project. I can get it working only if I put i18n.config under .playground folder. 
```
[vite-node] [ERR_INVALID_ARG_VALUE] @nuxtjs/packages/layer/i18n.config.ts&hash=069c89e7&from=./.nuxt/i18n.options.mjs
```
When layer is extended however, and I try to run the app that extend the layer,  the error keeps showing no matter where I put the i18n.config file

### Additional context

On reproduction if running pnpm run dev:layer, the project can run. But when we run pnpm run deb:web then I can't figure out how to make it running.

**Comment by 9M6** [comment]
Any update on this @kazupon ?

**Comment by dargmuesli** [comment]
I've increased the priority as the issue violates documented behavior and is not only an edge case, I think.

**Comment by atayg** [comment]
Hello, is there any update?
I guess I am getting same error related this issue. I try to implement i18n into the Nuxt Layer Template project.
Here are my details:

nuxt.config.ts:
`export default defineNuxtConfig({
  modules: ['@nuxtjs/i18n'],
  i18n: {
    vueI18n: './i18n.config.ts',
  },`

i18n.config.ts:
`export default defineI18nConfig(() => ({
  lazy: true,
  langDir: 'locales',
  locales: [
    { code: 'tr', iso: 'tr', name: 'Turkish(TR)', file: 'tr/tr.ts' },
    { code: 'en', iso: 'en', name: 'English(EN)', file: 'en/en.ts' },
  ],
  defaultLocale: 'tr',
  strategy: 'no_prefix',
  detectBrowserLanguage: false,
  legacy: false,
  fallbackLocale: 'tr',
}));
`
**Error:** 
[vite-node] [ERR_LOAD_URL] .\.playground\i18n.config.ts?config=true

Thanks in advance.

**Comment by BobbieGoede** [comment]
This issue should be fixed by #2265, you can check it out by installing the edge channel `@nuxtjs/i18n@npm:@nuxtjs/i18n-edge`.

I have changed your reproduction to demonstrate this here: https://stackblitz.com/edit/node-yhgxzu?file=package.json
However in your reproduction, the layer config points to a `i18n.config.ts` which does not exist so I have commented that out. Can you confirm the edge channel resolves your issue locally?

**Comment by atayg** [comment]
Hello Bobbie, 

Thank you for your effort but still I could not use i18n for layer language support. Let me try to explain what I did.
1. I try to add settings inside of nuxt.config and i18n file just in the layer (without playground). It does not work.
2. I try to add settings inside of nuxt.config and i18n file for layer and playground project. It does not work.

In summary, I have app shell in the layer and I am giving some message to the layer but I could not control language support.

**Comment by BobbieGoede** [comment]
Hi @atayg,

It sounds like you may be experiencing a similar, but unrelated issue, can you open a separate issue and provide a reproduction of your setup?

**Comment by BobbieGoede** [comment]
I'm quite sure this issue is resolved in the edge channel so I will be closing this. @wypratama if you're still experiencing this issue with the edge channel installed, let me know and I'll reopen the issue again!

**Comment by dargmuesli** [comment]
I can confirm that this issue is resolved :)
