### ISSUE TITLE
[bug] Lazy-load translations ignore the second language content when switch

### ISSUE THREAD

**Issue by moHaHa** [nuxt-modules/i18n#2074]
### Environment

npx nuxi info
```bash
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.0
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      modules, experimental, css, colorMode, nitro, app, pwa, devtools, i18n
- Runtime Modules:  @vueuse/nuxt@9.13.0, @unocss/nuxt@0.51.4, @pinia/nuxt@0.4.8, @nuxtjs/color-mode@3.2.0, @vite-pwa/nuxt@0.0.7, @nuite-pwa/nuxt@0.0.7, @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-fxq7lw

### Describe the bug
Lazy-load translations ignore the second language content when switch

this what happens 
when I set     `defaultLocale: 'ar'` , the only content loaded is arabic.ts  and when I toggle the other language content not showing and the same when I set  `defaultLocale: 'en'`

`ar`
![image](https://github.com/nuxt-modules/i18n/assets/72744132/5d04471c-ecde-4985-8843-884eea8206f6)
![image](https://github.com/nuxt-modules/i18n/assets/72744132/8b8ba559-a004-427f-9953-823bdb784c9a)

`en`
![image](https://github.com/nuxt-modules/i18n/assets/72744132/71bd6d66-53ec-4fbe-b90e-a7648f00186b)
![image](https://github.com/nuxt-modules/i18n/assets/72744132/8d041b09-63f9-4531-8214-ec753d7b3b52)

`next.config.ts` 
```ts
export default defineNuxtConfig({

  // ...

  i18n: {
    locales: [
      {
        code: 'en',
        file: 'english.ts',
      },
      {
        code: 'ar',
        file: 'arabic.ts',
      },
    ],
    lazy: true,
    langDir: 'lang',
    defaultLocale: 'ar',
    experimental: {
      jsTsFormatResource: true,
    },
  },

// ...

})

```
`lang/araic.ts`
```ts

export default defineI18nLocale(async (context, locale) => {
  return {
    welcome: 'مرحبا بك،  بالعربية',
  }
})

```

`lang/english.ts`
```ts
export default defineI18nLocale(async (context, locale) => {
  return {
    welcome: 'welcome in english lang',
  }
})

```

`LangToggle.vue`
```vue
<script setup lang="ts">
const { locale } = useI18n()

function toggleLang() {
  locale.value = locale.value === 'ar' ? 'en' : 'ar'
}
</script>

<template>
  <button class="!outline-none" @click="toggleLang">
    <div class="i-carbon-language" /> {{ locale }}
  </button>
   <p>{{ $t('welcome') }}</p>
</template>

```

**Comment by moHaHa** [comment]
hmmm, how can be fixed? , should I do any thing?  I can contribute to fix it but how ?

**Comment by wypratama** [comment]
Hi @moHaHa, I apologize for jumping in. I tried to fork your reproduction link, but it seems to be working without any errors already. Here's the link: [https://stackblitz.com/edit/github-fxq7lw-gblyth?file=app.vue.](https://stackblitz.com/edit/github-fxq7lw-gblyth?file=app.vue.)

**Comment by moHaHa** [comment]
### replay on wypratama
>Hi @moHaHa, I apologize for jumping in. I tried to fork your reproduction link, but it seems to be working without any errors already. Here's the link: https://stackblitz.com/edit/github-fxq7lw-gblyth?file=app.vue.

@wypratama  I added the reproduction without seeing the result, and I still have the issue. I want to try something now because when I installed i18n in the reproduction, I saw that it was using `@nuxtjs/i18n 8.0.0-beta.12`, whereas my project is using `@nuxtjs/i18n 8.0.0-beta.11`. I edited it manually in reproduction and then left it without checking the result.

Currently, it's using `@nuxtjs/i18n 8.0.0-beta.11` in the reproduction, but I'm unsure about what happened. So, as a first step, I want to try updating it in my project to `@nuxtjs/i18n 8.0.0-beta.12`.



### What I will do

now I'll uninstall @nuxtjs/i18n ` "@nuxtjs/i18n": "8.0.0-beta.11",`
then install it again  ` "@nuxtjs/i18n": "8.0.0-beta.12",`

**Comment by moHaHa** [comment]
### replay 
> ### What I will do
> now I'll uninstall @nuxtjs/i18n  "@nuxtjs/i18n": "8.0.0-beta.11",
then install it again  "@nuxtjs/i18n": "8.0.0-beta.12",

problem solved : no  ❌


### update 
I still have the issue in my local project, so I upload it all in Reproduction 
[ stackblitz - vitesse-nuxt3-i18n](https://stackblitz.com/github/mohaha/vitesse-nuxt3-i18n) of [github - vitesse-nuxt3-i18n repo](https://github.com/mohaha/vitesse-nuxt3-i18n)
my project on Reproduction : ✔️ 
my project on local :  ❌ 

I did : 
- update to ` "@nuxtjs/i18n": "8.0.0-beta.12"`
- delete `/node_module`, `/.nuxt` , `pnpm-lock.yaml`
- install again one with `pnpm` and one with `npm`
 
problem solved in my local project : no  ❌

### why I still have the issue 
IDK , I even upload all my projects on Reproduction 



<div>
<img src="https://github.com/nuxt-modules/i18n/assets/72744132/81647c17-2cc4-4a8f-ad9b-51f45c089a0c" >
<img src="https://github.com/nuxt-modules/i18n/assets/72744132/d350577b-6a07-433e-b705-980dd1c8b65e" >
</div>

### What I will do 

in my machine I have node `v18.16.0` in the Reproduction  node is `v16.14.2` 
so I will test the project in both node versions

**Comment by moHaHa** [comment]
###  replay
> ### What I will do
> in my machine I have node v18.16.0 in the Reproduction node is v16.14.2
so I will test the project in both node versions 

problem solved in my local project: no ❌

**Comment by moHaHa** [comment]
### try to build to see what will happen 
now I have more issues , in `https://vitesse-nuxt3-i18n.netlify.app`   [vitesse-nuxt3-i18n.netlify.app](https://vitesse-nuxt3-i18n.netlify.app)
lang en : not working ❌ 
lang ar : not working  ❌ 

in local I try `nuxi build` then `node .output/server/index.mjs` ,  
lang en : not working ❌  same as `https://vitesse-nuxt3-i18n.netlify.app`  
lang ar : not working  ❌  same as `https://vitesse-nuxt3-i18n.netlify.app`

**Comment by kazupon** [comment]
close in-activity.
if you have still issue, please you will open as new issue.

thanks!
