### ISSUE TITLE
Lazy-Load Dynamic message files.

### ISSUE THREAD

**Issue by Timeraa** [nuxt-modules/i18n#2075]
### Describe the feature

Currently if you use lazy-loading for the translations of a website, they get pre-rendered / pre-compiled at build time which is not really feasible if you have a large/community driven translation project and want to have the translations dynamically update over let's say an API endpoint which provides the string data when you visit the page. Same goes for dynamically being able to add/remove locales (from the locales array) by fetching an API endpoint to find out what languages the website supports. I am not 100% sure if this isn't already possible because when I tried to do this by using a `ts` file to fetch the language it got pre-compiled once I built the project for SSR which I don't want.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by moHaHa** [comment]
@Timeraa 
can you take a look on my issue here  #2074 
my issue show  tow problems : 
1. my project local project not the same as reproduction stackblitz 
2. when I build the project all languages not working 


now I'm testing the minimum app in i18n v8, and again it's not working for both lang when I deploy  like this one 
[moHaHa/try-nuxt-v3](https://github.com/moHaHa/try-nuxt-v3) on [https://kaleidoscopic-torrone-d5d1a5.netlify.app](https://kaleidoscopic-torrone-d5d1a5.netlify.app)

**Comment by kazupon** [comment]
Thank you for your feedback!

This issue depends on the architecture of vue-i18n.
vue-i18n v9 compiles locale messages for production for performance optimization. It has a message compiler to compile them, which is not bundled for production.

To support true dynamic resources, the message compiler must be bundled.
Adding a new option to the experimental option may solve this problem by loading the message compiler into dynamic.
https://v8.i18n.nuxtjs.org/options/misc#experimental

**Comment by Timeraa** [comment]
Okay thanks for the quick response! Will you tackle this? I could try to do it but I haven't worked much with creating nuxt/vue plugins/modules, I looked into the module's code a bit but would really need to dig into it to understand its core structure.

**Comment by Vanger888** [comment]
@kazupon Hi, I faced the same limitation and opened a merge request with new experimental options. I am not sure that it will completely solve lazy loading feature. But with it we can make some workaround to support real dynamic resources. Could you please have a look if you have time?

**Comment by Vanger888** [comment]
This might be useful for someone who needs to use dynamic runtime translations. 
We can create a composable that loads messages and compiles them into functions. I also use store to avoid unnecessary requests on the client, check store and if there are no translations then make a request to cdn (normally this will only be done on the server side). Then I use the `compileToFunction` helper from `@intlify/core-base`. This will compile all messages into functions.

```typescript
import { compileToFunction } from '@intlify/core-base';
import type { MessageFunction } from '@intlify/core-base';

export const useLang = async (locale = 'en', localeIso = 'en') => {
  const translationsStore = useTranslationsStore();
  let messages = translationsStore.getLocaleMessages(locale);

  if (!messages) {
    messages = await useLangLoader(formatIsoToUnderscore(localeIso));
    translationsStore.setLocaleMessages(locale, messages);
  }

  const compiledMessages: Record<string, MessageFunction<string> | string> = {};

  Object.entries(messages).forEach(([key, value]) => {
    try {
      compiledMessages[key] = compileToFunction(value);
    }
    catch {
      compiledMessages[key] = value;
    }
  });

  return compiledMessages;
};
``` 
Then you need to add compiled translations to `$i18n`. For this purpose I created plugin
```typescript
export default defineNuxtPlugin(async (app) => {
  const { $i18n } = useNuxtApp();
  const { locale, localeProperties } = $i18n;
  const messages = await useLang(locale.value, localeProperties.value.iso);

  $i18n.mergeLocaleMessage(locale.value, messages);
});
```

**Comment by kazupon** [comment]
@Vanger888 
Thank you for your workaround!

Using `compileToFunction`, we can dynamically load resources and compile them to work in a production environment.
However, as [I commented in your PR](https://github.com/nuxt-modules/i18n/pull/2108#issuecomment-1563707633), `compileToFunction` will not work in a user environment with CSP limitations because it `new Function`.

```ts
    const msg = new Function(`return ${code}`)() as MessageFunction<T>
```
https://github.com/intlify/vue-i18n-next/blob/67b8402c818fe46ef12f8e6f233b1c59cff48d0c/packages/core-base/src/compile.ts#LL67C5-L67C71

when you will load dynamically as the string resource from a back-end DB via an API, we need to understand that this method cannot be fully guaranteed to work.
