### ISSUE TITLE
[nuxtjs:i18n-resource-dynamic] Plugin error - Unable to get file name for unknown file "xxxxxxx"

### ISSUE THREAD

**Issue by valicsek** [nuxt-modules/i18n#2077]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.0
- Builder:          vite
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12

### Reproduction

https://stackblitz.com/edit/github-nbjqyt

### Describe the bug

After set ssr:false in nuxt.config.ts and run nuxt build, i get the following error:
Plugin error - Unable to get file name for unknown file "a4bd1ac8".

### Logs

```shell
ERROR  Plugin error - Unable to get file name for unknown file "a4bd1ac8".                                                                                                     
  at error (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at FileEmitter.getFileName (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24103:24)
  at /node_modules/@nuxtjs/i18n/dist/module.mjs:1216:50
  at Array.reduce (<anonymous>)
  at Object.generateBundle (node_modules/@nuxtjs/i18n/dist/module.mjs:1215:44)
  at /node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24526:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by gbyesiltas** [comment]
I have the same error ✋ 
operating system: macos
ssr: false
@nuxtjs/i18n: 8.0.0-beta.12-28065601.76e2626
nuxt: 3.4.2
node: 18.14.0
npm: 8.19.3

**Comment by kazupon** [comment]
Thank you for your reporting!
duplicate issue as #2029, so close
