### ISSUE TITLE
usecookie can not use in defineI18nConfig

### ISSUE THREAD

**Issue by mokurofuzo** [nuxt-modules/i18n#2084]
### Environment

Nuxi 3.5.0                                                                                                        
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.2
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      imports, modules, i18n, app, css, vite, typescript
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

export default defineI18nConfig(() => ({
  legacy: false,
  globalInjection: true,
  locale: useCookie('lang').value || 'en',
  warnHtmlMessage: false,
  messages: message
}))

### Describe the bug

useCookie call can not read ('indexOf')

**Comment by kazupon** [comment]
Thank you for your reproting!

We need  minimal reproduction repo or stackbliz.
Could you give us your it please?

**Comment by kazupon** [comment]
close in-activity.
If you have still issue, please you will open as new issue.

thsnks!
