### ISSUE TITLE
 I can't find NuxtI18nInstance in v8.

### ISSUE THREAD

**Issue by atlansien** [nuxt-modules/i18n#2085]
### Describe the feature

The `NuxtI18nInstance` released in [v6.25.0](https://github.com/nuxt-modules/i18n/releases/tag/v6.25.0) is missing in v8. What should I use instead?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
This issue is question, So we will transfer to github discussion.
