### ISSUE TITLE
i18n crashes app with custom nitro pre-render config

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt-modules/i18n#2086]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      modules, nitro, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------
```

### Reproduction

Stackblitz: https://stackblitz.com/github/lukaszflorczak/nuxt-i18n-playground/tree/issue/nitro-prerender
Repository: https://github.com/lukaszflorczak/nuxt-i18n-playground/tree/issue/nitro-prerender

1. `pnpm install`
2. `pnpm build`
3. `node .output/server/index.mjs`

### Describe the bug

If the project has custom Nitro prerender rules (as shown in the example below), the app builds successfully but crashes after starting in production mode. In my opinion, I should be able to modify the settings in the project without affecting the external module.

<img width="1031" alt="Zrzut ekranu 2023-05-18 o 14 11 53" src="https://github.com/nuxt-modules/i18n/assets/1818979/c3e0692c-0e2d-4bb5-95ce-b1e4c73e85f3">

```ts
// In nuxt.config.ts
nitro: {
  prerender: {
    ignore: ['/'],
  },
},
```

Related issue: https://github.com/nuxt-modules/i18n/issues/2080

**Comment by monkemedia** [comment]
I get this issue when I visit my error page (ie 404)

@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-dfcfda38.mjs
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Page not found: /fjf","reason":{"message":"Page not found: /fjf","statusCode":404,"statusMessage":"Page not found: /fjf"},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Page not found: /fjf","    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)","    at process.emit (node:events:525:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown

**Comment by kazupon** [comment]
This reproduction repo specifies ignore `/`, so I understand that it's an example of this issue. 3rd party modules that use prerender, such as nuxt i18n, need to dynamically change the prerender route based on what the ignore setting is from.

I don't know how to do this.  😅  /cc @danielroe

**Comment by grexen** [comment]
I got the exact same issue but I'm not using any Nitro prerender rules.

**Comment by Aareksio** [comment]
Disabling prerender is required for https://github.com/harlan-zw/nuxt-seo-kit to work properly, as per https://github.com/harlan-zw/nuxt-seo-kit/issues/45, therefore this reproduction is not just made-up demonstration of the issue, rather something one may face in actual project.

Both i18n and sitemap module use prerender functionality which I think should be reserved for actually prerendering the app. Maybe there is a solution nuxt could provide for modules to achieve the goal without interfering with this app behavior defining setting?

**Comment by RodrigoProjects** [comment]
I have a mutation of this error: 
`@nuxtjs/i18n Cannot find module '/Users/something/Desktop/something/repos/something/apps/site/.output/server/public/__i18n__/prerender/2ddeb7bb.js' imported from /Users/something/Desktop/something/repos/something/apps/site/.output/server/chunks/app/assets/v4/i18n.options-728d52a7.mjs`

When my project is built. I don't use prerender routes in my project.

This file exists in the `/public` dir and not in the `/server/public` it seems
Any idea on this @kazupon ?

**Comment by RodrigoProjects** [comment]
```js
let url = `${NUXT_I18N_PRERENDERED_PATH}/2ddeb7bb.js`;
      if (true) {
        url = `../../../../public${url}`;
      }
```

This should take considerantion this: 
![image](https://github.com/nuxt-modules/i18n/assets/47485736/79bc4c1c-7f0b-4819-8aa6-99b251dd7ecb)
