### ISSUE TITLE
8.0.0-beta12 breaks type inference for plugins with nuxt 3.5.0

### ISSUE THREAD

**Issue by DirectorRen-TV** [nuxt-modules/i18n#2090]
### Environment

- Operating System: Linux
- Node Version:     v16.17.1
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  npm@8.15.0
- Builder:          vite
- User Config:      vite, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

if you install nuxt 3.5.0 and nuxt-i18n 8.0.0-beta12 simultaneously, then enable the module in nuxt.config, volar 1.6.4 in vscode will give an error that no such field was found in the context
 https://stackblitz.com/edit/nuxt-starter-m7yaxu

### Describe the bug

![изображение](https://github.com/nuxt-modules/i18n/assets/39501885/83c0643a-2210-4a96-acd8-45c801a315f7)
![изображение](https://github.com/nuxt-modules/i18n/assets/39501885/9db33861-780c-4885-a3e6-578c6f662fa8)

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I could not reproduce this issue 😞 
Maybe, I think there is something that causes this issue.

**Comment by DirectorRen-TV** [comment]
After taking back that repository, now I don't get that error either, it works as it should. Very strange, especially when you consider that the copy of the project I repeated in StackBlitz continued to give the error, but after several deletions of node_modules and package.lock and subsequent `npm i`, as well as reopening the project in VSCode, the error stopped appearing. This is even though package.lock did not change - git did not see any changes.

In general, something very strange happened only for me. I think we can close the issue

**Comment by ineshbose** [comment]
Many times refreshing `node_modules` and `.nuxt` often helps - glad the issue is resolved.
