### ISSUE TITLE
Cannot init i18n with layers

### ISSUE THREAD

**Issue by kleinpetr** [nuxt-modules/i18n#2092]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/kleinpetr/nuxt-i18n-layers

### Describe the bug

I've tried lot of variants of use, but cannot implement i18n with Nuxt layers. in the reproduction there is just `/app` and `/layer` and I would like to use trnaslations in the `/layer` basically. I am trying to use `resolve` for relative paths but it is not working neither with resolve nor with relative path.

I've also tried to use the same config for the `/app` which extends from `/layer`. but get another kind of error. So I am not able to reproduce usage as it is described in the docs. 

Could you explain how it can be used in this case? Thanks :pray:

**Comment by kleinpetr** [comment]
Is there currently any way how to use i18n with layers?

**Comment by acibilous** [comment]
any updates?

**Comment by xibman** [comment]
@acibilous it work well with latest edge version 

[8.0.0-beta.12-28110710.9b54123](https://www.npmjs.com/package/@nuxtjs/i18n-edge/v/8.0.0-beta.12-28110710.9b54123)

**Comment by kazupon** [comment]
I believe this issue is fixed by v8.0.0-beta.13.
I'll close this issue.
if you have still the issue, please you will open as new issue.
Thanks!

**Comment by souserge** [comment]
I still experience the same issue on v8.3.1

**Comment by kleinpetr** [comment]
let's try https://github.com/s00d/nuxt-i18n-micro ;)
