### ISSUE TITLE
support variable identifier default export for `defineI18nConfig`

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#2094]
Currently,  not support define style the below,
```ts
const i18nConfg = (() => ){ ... });
…
export default i18nConfig;
```

so ,you need to define it directly as export default, that is,

```ts
export default defineI18nConfig(() => ({ ... }))
```

_Originally posted by @kazupon in https://github.com/nuxt-modules/i18n/issues/2017#issuecomment-1556682090_

**Comment by rashidmya** [comment]
can I try doing this?

**Comment by kazupon** [comment]
Yeah! nuxt i18n module is community.
You can contribute it! :)

**Comment by rashidmya** [comment]
@kazupon can I get a hint on what I need to do?

**Comment by jilani97** [comment]
@kazupon what is the status here?
