### ISSUE TITLE
v8.0.0-beta11 Cloudflare Worker deployment fails

### ISSUE THREAD

**Issue by srtonz** [nuxt-modules/i18n#2095]
### Environment

```
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@3.2.4
- Builder:          vite
- User Config:      sourcemap, modules, css, image, i18n, runtimeConfig, telemetry, ssr, routeRules
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.10, @nuxt/image-edge@1.0.0-28020728.5df24eb, @nuxtjs/strapi@1.9.1, @nuxtjs/tailwindcss@6.7.0
- Build Modules:    -
```

### Reproduction

See https://github.com/srtonz/i18n-nuxt-app for a basic nuxt app bootstrapped with `npx nuxi init` and nuxtjs/i18n. Repo contains two commits for i18n v8beta10 and v8beta11 and associated build output.

CI output is available for:
* build with v8.0.0-beta10: https://github.com/srtonz/i18n-nuxt-app/actions/runs/5051124814/jobs/9062624194 
* build with v8.0.0-beta11: https://github.com/srtonz/i18n-nuxt-app/actions/runs/5051132083/jobs/9062640022 

### Describe the bug

When upgrading dependencies in our staging environment, we noticed deployments to Cloudflare Workers failing:

> Error: Script startup exceeded CPU time limit.
>   [code: 10021]

It appears that changes introduced with the v8-beta11 release have led to a significant increase in size of our server bundle and thus resource exhaustion on CF workers.

With v8.0.0-beta.10 installed:
```
√ Nitro server built
  └─ .output/server/index.mjs (1.87 MB) (511 kB gzip)
```

With v8.0.0-beta.11 (or newer) installed, no other changes:
```
√ Nitro server built
  └─ .output/server/index.mjs (2.63 MB) (729 kB gzip)
```

Downgrading i18n to v8-beta10 allows deployments again, although we're at a loss as to what would have prompted the bundle size increase. Apologies for the missing repro, hoping to provide this later.

**Comment by ineshbose** [comment]
Thanks for opening an issue. This could be tricky to investigate without a reproduction so having that would be incredible.
The main idea would be to isolate the issue as I also see that there are a few modules installed (but if you were able to diagnose changing versions of this module, maybe it may be in the changeset), again, a minimum reproduction would be very helpful.

**Comment by srtonz** [comment]
Reproduction has been added above. The server bundle for v8.0.0-beta.11 is significantly larger than the output for beta.10:

beta 10:
> Σ Total size: 3.31 MB (763 kB gzip)

beta 11:
> Σ Total size: 6.27 MB (1.42 MB gzip)

I'll keep the reproduction repository around for a bit.

**Comment by kazupon** [comment]
I've noticed that vue-i18n package is included to `.output/server/node_modules`.
We will try to exclude it for server (nitro) build.

**Comment by kazupon** [comment]
And, from v8.0.0-beta.11, We had supported js / ts format resource and `i18n.configt.ts`. 

These require pre-compile, which requires a compiler to support it.
Accordingly, dependencies to run them are included in `.output/server/node_modules`.

**Comment by kazupon** [comment]
When they are pre-compiled, dependent modules such as compiler are no longer needed.

I don't know how to make nuxt.config (nitro) not include those modules in `.output/server/node_modules`.
I need advices from @danielroe @pi0  😅

**Comment by rankjie** [comment]
I upgraded from beta.10 to beta.12 and also found this issue.
The error appears to be in the prerender process. I hope the log below is useful.

`
19:07:28.972 | [success] Server built in 62552ms
-- | --
19:07:29.516 | [success] [nitro] Generated public dist
19:07:29.517 | [info] [nitro] Initializing prerenderer
19:08:05.784 | [info] [nitro] Prerendering 1 routes
19:08:05.798 | [error] (node:1341) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
19:08:05.799 | (Use `node --trace-warnings ...` to show where the warning was created)
19:08:05.799 | [error] [nuxt] [request error] [unhandled] [500] Cannot use import statement outside a module
19:08:05.800 | at internalCompileFunction (node:internal/vm:73:18)
19:08:05.800 | at wrapSafe (node:internal/modules/cjs/loader:1176:20)
19:08:05.800 | at Module._compile (node:internal/modules/cjs/loader:1218:27)
19:08:05.800 | at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
19:08:05.800 | at Module.load (node:internal/modules/cjs/loader:1117:32)
19:08:05.800 | at Module._load (node:internal/modules/cjs/loader:958:12)
19:08:05.800 | at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
19:08:05.801 | at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
19:08:05.931 | [error] (node:1341) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
`

**Comment by signor-pedro** [comment]
Hi, is there any progress on this please?

We are currently releasing our application with a fork (custom patched beta10) as we cannot deploy to Cloudflare.

Is there any way to push this forward? I am unfortunately not a skilled JS developer so I probably couldn't fix it in code.

Maybe there could be a way to opt-out of the precompilation mechanism? Meaning if I don't want to use TS for the configuration, no compilation would occur?

Thanks.
