### ISSUE TITLE
All canonical by i18n goes with trailing slash - how to fix/control that?

### ISSUE THREAD

**Issue by financemarker** [nuxt-modules/i18n#2096]
### Environment

    "@nuxtjs/i18n": "^7.2.0",
    "nuxt": "^2.15.8",

### Reproduction

Just open Source code of page and check the canonical url

### Describe the bug

For all pages in source code, canonical link has trailing slash at the end. 
How to fix/control that behaviour?

**Comment by kazupon** [comment]
This is question, so we will convert to github discussions
