### ISSUE TITLE
The requested module '/_nuxt/@fs/=/node_modules/.cache/vite/client/deps/@intlify_shared.js' does not provide an export named 'assign'

### ISSUE THREAD

**Issue by mateusk** [nuxt-modules/i18n#2098]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v16.19.1
- Nuxt Version:     3.4.2
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      srcDir, css, runtimeConfig, typescript, modules, imports, i18n, vite, app
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12, @vueuse/nuxt@10.1.2, nuxt-swiper@1.1.0, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------
```

### Reproduction

Cannot reproduce this in a new Nuxt project, sorry.

### Describe the bug

`Uncaught SyntaxError: The requested module '/_nuxt/@fs/app/node_modules/.cache/vite/client/deps/@intlify_shared.js?v=85d61870' does not provide an export named 'assign' (at message-compiler.mjs?v=27c99670:6:18)`

My Nuxt app was running fine until this strange error came up all of a sudden. Could not replicate this issue in a new Nuxt 3 project, so I cannot provide a reproduction repo, sorry. Tried downgrading @nuxtjs/i18n, same. Tried removing /node_modules, reinstalling dependencies, same.

Thanks in advance for any clues.

**Comment by mateusk** [comment]
Turns out I had `@intlify/eslint-plugin-vue-i18n` which also depends on `@intlify/message-compiler` but installs a different version, and that was generating a conflict. Uninstalled `@intlify/eslint-plugin-vue-i18n` and all works again.

**Comment by dargmuesli** [comment]
Let's keep this open to further track the issue if that's fine for you, @mateusk. It might not be the perfect solution for everyone to just uninstall their linter plugin. A beta release for `@intlify/eslint-plugin-vue-i18n` seems to be needed.

**Comment by dargmuesli** [comment]
See https://github.com/intlify/eslint-plugin-vue-i18n/pull/373 as my WIP which could be released in a beta version as suggested.

**Comment by mathieuCatapulpe** [comment]
In case this might help someone, I faced a simular issue as explained in [#2110](https://github.com/nuxt-modules/i18n/issues/2110) and managed to fix it by using yarn instead of npm

**Comment by Roman-00** [comment]
The error still remains :(

nuxt v - 3.5.2

repos - https://github.com/Roman-00/iteca.events/tree/PR-3

**Comment by valernyx** [comment]
We are having this same issue as well (same error message), but our repo is not using the `eslint-plugin-vue-i18n`.  We have other eslint plugins however, so I'm trying to determine if it's related to one of them.  No luck getting it running so far :(

**Comment by dargmuesli** [comment]
Check why `@intlify/shared` is used, e.g. by `pnpm why @intlify/shared`, and why there are most likely different versions in use compared to your other intlify dependencies.

**Comment by valernyx** [comment]
> Check why `@intlify/shared` is used, e.g. by `pnpm why @intlify/shared`, and why there are most likely different versions in use compared to your other intlify dependencies.

@dargmuesli Thank you!  We have `@intlify/shared` used as a dep for a few other packages and it was using version `9.2.2` for them.  I was able to resolve the issue by adding the following to our `package.json`:

```
"overrides": {
    "@intlify/shared": "9.3.0-beta.17"
},
 ```
 
 Appreciate the quick assistance! 🎉

**Comment by ghost** [comment]
> Check why `@intlify/shared` is used, e.g. by `pnpm why @intlify/shared`, and why there are most likely different versions in use compared to your other intlify dependencies.

I use @nuxtjs/i18n in the project and I get an error with @intlify_shared, I tried the above actions, nothing helped, how else can I solve this problem?

**Comment by dargmuesli** [comment]
You could wait for the merge and release of https://github.com/intlify/eslint-plugin-vue-i18n/pull/382 if you use `@intlify/eslint-plugin-vue-i18n`.

**Comment by ghost** [comment]
> You could wait for the merge and release of [intlify/eslint-plugin-vue-i18n#382](https://github.com/intlify/eslint-plugin-vue-i18n/pull/382) if you use `@intlify/eslint-plugin-vue-i18n`.

So I don't use @intlify/eslint-plugin-vue-i18n, but the error is still present
