### ISSUE TITLE
How do I change i18n build dir?

### ISSUE THREAD

**Issue by zhengyimeng** [nuxt-modules/i18n#2101]
### Environment

npx build

### Reproduction

无

### Describe the bug

i18n 构建之后的默认目录是 .output/public/__i18n__
我如何修改 __i18n__ 为其他的名称？
能否增加一个选项叫，buildAssetsDir 改变 i18n 的默认路径？

**Comment by kazupon** [comment]
This is not issue, question, so we will convert to github discussions
