### ISSUE TITLE
Typecheck issue with extended layer in subfolder

### ISSUE THREAD

**Issue by Vanger888** [nuxt-modules/i18n#2106]
### Environment

 Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      extends, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

Reproduction project
https://stackblitz.com/edit/nuxt-starter-ctsn1s

Please follow these steps:
Run `cd platform/base-nuxt/`
Run `yarn install`
Run `cd ../..`
Run `yarn nuxi typecheck`

### Describe the bug

We got a type checking error when extending another nuxt project in a subfolder and it has its own node_modules.
![image](https://github.com/nuxt-modules/i18n/assets/47368844/b799fb76-2979-4923-8658-857012ec98d1)

This is not a big problem as everything works as expected, just a weird typescript error. But it is a bit confusing.
I also tried the edge version and got the same result

### Additional context

As you can see in the reproduction repo, we do not have any component in the parent project. Even app.vue placed in child project which is extended. I believe it is not common use case, but we want to try to use such approach. If we add any component, page or app.vue to parent project, the problem is gone. I really don't understand why this is happening. 
If we remove node_modules from the child project, the problem also disappears.
I am not sure if this is a bug or a misconfiguration. But we also have Pinia and Vueuse modules that are used in the same way, and there is no such problem with Typescript.

### Logs

```shell
error TS2339: Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 8 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (arg...'.
```

**Comment by BobbieGoede** [comment]
Closing this as I'm unable to replicate this issue in the reproduction using updated dependencies, let me know if you're still experiencing this issue (with an updated minimal reproduction)!
