### ISSUE TITLE
Support experimental.typedPages

### ISSUE THREAD

**Issue by szulcus** [nuxt-modules/i18n#2109]
### Describe the feature

https://github.com/nuxt/nuxt/issues/21048#issuecomment-1563022269

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by VladBrok37** [comment]
looking forward to see this feature! thanks

**Comment by VladislavYakonyuk** [comment]
any update?

**Comment by szulcus** [comment]
@VladislavYakonyuk yes but no: https://github.com/nuxt-modules/i18n/pull/2522 😆
