### ISSUE TITLE
v8.0.0-beta12 SyntaxError the requested module does not provide an export named 'assign'

### ISSUE THREAD

**Issue by mathieuCatapulpe** [nuxt-modules/i18n#2110]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      app, css, build, components, imports, modules, ssr, preset, apollo, vite, i18n, sitemap, optimization
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @nuxtjs/apollo@5.0.0-alpha.4, @vueuse/nuxt@9.5.0, @nuxtjs/i18n@8.0.0-beta.12, @pinia/nuxt@0.4.4, nuxt-swiper@0.1.9, nuxt-lodash@2.4.1, nuxt-simple-sitemap@2.1.7
- Build Modules:    -

### Reproduction

I tried making a reproduction on stackblitz and got no error at all, here it is just in case
https://stackblitz.com/edit/nuxt-starter-9nuros?file=package.json

### Describe the bug

Whenever I run `nuxt dev` on both my home computer or work office computer my browser console shows the error :
`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.cache/vite/client/deps/@intlify_shared.js?v=7a5be846' does not provide an export named 'assign'`

The error causes my page to not load at all (blank page)
Whenever I remove @nuxtjs/i18n module from my nuxt.config.ts file I can access my pages

### Additional context

I used Nuxt3.2.3 alongside @nuxtjs/i18n v8.0.0-beta10 a few days ago and everything worked fine, updated to Nuxt3.5.1 and @nuxtjs/i18n v8.0.0-beta12 and got the bug.

I tried downgrading back to the previous versions I had but the bug persists

**Comment by ineshbose** [comment]
Please check - https://github.com/nuxt-modules/i18n/issues/2098 and let me know if it's not a duplicate, I'll reopen. 🙂

**Comment by mathieuCatapulpe** [comment]
I tried to uninstall `@intlify/eslint-plugin-vue-i18n` like suggested in [#2098](https://github.com/nuxt-modules/i18n/issues/2098) but it didn't solve the problem :/
