### ISSUE TITLE
Bizarre bug with global sfc i18n blocks

### ISSUE THREAD

**Issue by unshame** [nuxt-modules/i18n#2112]
### Environment

- Operating System: Windows_NT                                                                                                                                                                               
- Node Version:     v18.15.0                                                                                                                                                                                 
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      ssr, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-bw8qaw?file=app.vue

### Describe the bug

Trying to use [sfc i18n blocks with global attribute](https://vue-i18n.intlify.dev/guide/advanced/sfc.html#define-locale-messages-for-global-scope) I get the following error when the i18n block is being loaded from a component:

```
Cannot read properties of undefined (reading 'value')

at adjustI18nResources (http://localhost:3001/_nuxt/node_modules/vue-i18n/dist/vue-i18n.mjs?v=ea82506c:232:56)
at useI18n (http://localhost:3001/_nuxt/node_modules/vue-i18n/dist/vue-i18n.mjs?v=ea82506c:2264:9)
at setup (http://localhost:3001/_nuxt/pages/index.js:13:19)
```

Taking a look at the offending code, I see this:

```javascript
function adjustI18nResources(global, options, componentOptions // eslint-disable-line @typescript-eslint/no-explicit-any
) {
    let messages = isObject(options.messages) ? options.messages : {};
    if ('__i18nGlobal' in componentOptions) {
        // The error originates here
        messages = getLocaleMessages(globalThis.locale.value, {
            messages,
            __i18n: componentOptions.__i18nGlobal
        });
    }
```

It appears the vue-i18n package is trying to access the `locale` object on `globalThis`. However, this code does not actually look like this in the vue-i18n package. There, it looks like this instead:

```typescript
export function adjustI18nResources(
  global: Composer,
  options: ComposerOptions,
  componentOptions: any // eslint-disable-line @typescript-eslint/no-explicit-any
): void {
  let messages = isObject(options.messages) ? options.messages : {}
  if ('__i18nGlobal' in componentOptions) {
    // DIfference is here
    messages = getLocaleMessages(global.locale.value as Locale, {
      messages,
      __i18n: componentOptions.__i18nGlobal
    })
  }
```
https://github.com/intlify/vue-i18n-next/blob/67b8402c818fe46ef12f8e6f233b1c59cff48d0c/packages/vue-i18n-core/src/utils.ts#L171

The script is supposed to access the `locale` object on the argument named `global` passed to the `adjustI18nResources`. I checked, and in my node_modules the script looks about the same.

It seems like for some bizarre reason either nuxt or @nuxtjs/i18n (or vite/esbuild) incorrectly replaces the reference to the `global` argument with a reference to `globalThis` when bundling this package.

I confirmed this by going to the offending `node_modules\vue-i18n\dist\vue-i18n.mjs` file, searching for the `adjustI18nResources` function and renaming its first argument and its usages from `global` to `variableFormerlyKnownAsGlobal`. This prevents the replacement of it with `globalThis` and fixes the crash.

**Comment by unshame** [comment]
This does not happen when using the vue-i18n package directly: https://stackblitz.com/edit/github-bw8qaw-3takq8?file=app.vue

**Comment by kazupon** [comment]
Thank you for your reporting!

>It seems like for some bizarre reason either nuxt or @nuxtjs/i18n (or vite/esbuild) incorrectly replaces the reference to the global argument with a reference to globalThis when bundling this package.
I confirmed this by going to the offending node_modules\vue-i18n\dist\vue-i18n.mjs file, searching for the adjustI18nResources function and renaming its first argument and its usages from global to variableFormerlyKnownAsGlobal. This prevents the replacement of it with globalThis and fixes the crash.

I've just confirmed this issue.
I could reproduce this issue.
maybe, I think that nuxt or vite has issue.
You can give the feedback for nuxt or vite.

**Comment by kazupon** [comment]
Close with #2120 
You can try to install with edge channel version!
Thanks!
