### ISSUE TITLE
Invalid linked format|Unexpected lexical analysis in token: '#$^*?_(). `V8-Nuxt3`

### ISSUE THREAD

**Issue by waleedtariq109** [nuxt-modules/i18n#2116]
### Environment

Operating System: `Ubuntu`
Node Version: `18.16.0`
Npm Version: `9.5.1`
Nuxt Version: `3.5.1`

### Reproduction

[Link to reproduction](https://stackblitz.com/edit/nuxt-starter-cgdrfq?file=app.vue)

### Describe the bug

When I run the npm run dev command, it throws an error message like `Invalid linked format|Unexpected lexical analysis in token`. After that, I navigate to my ar-SA.json locale file and remove all the JSON code, leaving only one key-value pair like this:
```json
{
   "hello": "World"
}
```
and I save the locale file, then I paste the previous JSON code, save it, and reload the project. After that, everything is working fine.

### Additional context

I have to remove all the JSON code from the locale file, then add only one property with a random name and value, and save the file. After that, I paste the previous code and save the file again. Everything works fine at that point. However, if I close the server and restart it, I encounter the same issue again. I have to follow the same steps in order to resolve this error.

### Logs

```shell
(400 Invalid linked format|Unexpected lexical analysis in token: '#$^*?_().'|Unexpected empty linked key|Invalid linked format|Unexpected lexical analysis in token: '#?.,:;_-'|Unexpected empty linked key (/__i18n__/precompile))

at async __vite_ssr_exports__.default (./@nuxtjs/i18n/__config__:16:23)
at async vueI18nConfigLoader (./.nuxt/i18n.options.mjs:20:19)
at async Module.resolveNuxtI18nOptions (./.nuxt/i18n.options.mjs:23:19)
at async Object.setup (./node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.mjs:22:154)
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
at async applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:111:23)
at async Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.js:127:7)
at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.js:29:7)
at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:18)
```

**Comment by kazupon** [comment]
Thank you for your feedback.

I noticed that your code has some special characters on your resources.
```json
"passwordDoesNotContainSpecialCharacters": "يجب أن تحتوي كلمة المرور على رمز مثل: (!,%&@#$^*?_().:;-).",
```

You need to use literal interpolation for special characters.
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

**Comment by waleedtariq109** [comment]
@kazupon Thanks now it works

**Comment by Soviut** [comment]
For posterity, I wanted to display a placeholder in an email field:

```yaml
emailPlaceholder: 'eg: test@example.com'
```

However, it complained about the `@` symbol.

I needed to put the entire string inside literal:

```yaml
emailPlaceholder: "{'eg: test@example.com'}"
```

**Comment by carbdias** [comment]
Are the quotes in the above example correct ?
I still get the warning in the same translation .. 

I'm trying this approach instead

https://vue-i18n.intlify.dev/guide/essentials/syntax#named-interpolation

**Comment by davefrassoni** [comment]
for html, just use this method: `"some-key": "{' your html translated text <a href=\"mailto:hello@mail.com\"> more text '}"`

**Comment by thiagonunesbatista** [comment]
> Are the quotes in the above example correct ? I still get the warning in the same translation ..
> 
> I'm trying this approach instead
> 
> https://vue-i18n.intlify.dev/guide/essentials/syntax#named-interpolation


The answer of @carbdias worked for me, thank you 🙋🏻‍♂️

It was difficult to find a solution to this problem, so I wrote a blog post to help other developers with the same problem.

[Read the Article here](https://codigoaoponto.com/en/blog/how-to-add-special-characters-on-i18n) ✍🏻

**Comment by thiagonunesbatista** [comment]
> Thank you for your feedback.
> 
> I noticed that your code has some special characters on your resources.
> 
> "passwordDoesNotContainSpecialCharacters": "يجب أن تحتوي كلمة المرور على رمز مثل: (!,%&@#$^*?_().:;-).",
> You need to use literal interpolation for special characters. https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters


The answer of @kazupon  worked for me, thank you 🙋🏻‍♂️

It was difficult to find a solution to this problem, so I wrote a blog post to help other developers with the same problem.

[Read the Article here](https://codigoaoponto.com/en/blog/how-to-add-special-characters-on-i18n) ✍🏻

**Comment by karladler** [comment]
Thanks @thiagonunesbatista for your Blog-Post. 
For people that just need a solution: Put special chars in curly braces as constant: 

Example:
`"key": "test@test.com"` --> `"key": "test{'@'}test.com"`
