### ISSUE TITLE
Cannot use HTML in i18n translations -  (Error: [400] Detected HTML in ... )

### ISSUE THREAD

**Issue by Qionar** [nuxt-modules/i18n#2118]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.17.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@8.18.0
- Builder:          vite
- User Config:      runtimeConfig, app, css, modules, vue, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11, nuxt-simple-sitemap@2.5.0
- Build Modules:    -

### Reproduction

Install Nuxt 3 + i18n
Add i18n.config.ts
Set up settings
Add messages with HTML
Use it in vue template as <div v-html="$t('hello')"></div>
Run npm run generate

### Describe the bug

Hi, I saw few similar problems in issues and these problems were resolved by adding next code to nuxt.config.ts, but this doesn't fix my problem, and I still receive (Error: [400] Detected HTML in '<span class=...) when I try to generate project using npm run generate

```
i18n: {
        precompile: {
            escapeHtml: false,
            strictMessage: false
        },
    }
```
All my translations I currently store in i18n.config.ts - fields messages. 

![image](https://github.com/nuxt-modules/i18n/assets/82905709/e5c0cad8-2e1a-4ca6-ba1c-a991074e5474)
![image](https://github.com/nuxt-modules/i18n/assets/82905709/a19d1d20-34c9-4f47-87d6-17530793fde4)

**Comment by kazupon** [comment]
This issue has already fixed in v8.0.0-beta.12
Please try to use that version.
related issue.
https://github.com/nuxt-modules/i18n/issues/1991

Thanks!

**Comment by vushe** [comment]
@kazupon this happens again in beta.13
![image](https://github.com/nuxt-modules/i18n/assets/15868217/fe75337b-f3ef-4a67-a863-4c8f090e3bcd)

**Comment by kazupon** [comment]
v8.0.0-beta.13 has breaking changes for compitation opions.
Maybe, you need to change `precompile` to `compilation`
https://v8.i18n.nuxtjs.org/options/misc#compilation

**Comment by vushe** [comment]
Thanks for prompt response! Yes, everything works fine with `compilation`. 

P.S: Just in case, config is
```
compilation: {
   strictMessage: false,
},
```
