### ISSUE TITLE
Text flashes the translation key in SSR mode in production build only.

### ISSUE THREAD

**Issue by jawngee** [nuxt-modules/i18n#2119]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      ssr, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-vbabpr

It only happens in the production build so you'll have to run the `./run-build.sh` or `npm run build --production --trace-warnings && node .output/server/index.mjs`

You will have to reload the preview a few times to see it.

### Describe the bug

In a production build with SSR enabled, the page flashes the i18n text key before replacing it with the appropriate text.  For example, if I have:

```html
<div>{{$t('button.sign-up')}}</div>
```

You'll see **button.sign-up** in the output before its eventually replaced with the correct text.  Here's a video:

https://github.com/nuxt-modules/i18n/assets/44449/9b9ed305-aaff-42ab-aaa2-d224ba101494

I'm not sure if I have something configured incorrectly or not.

**Comment by kazupon** [comment]
Thank you for your reproduction.
Unfortunately, I could not reproduce this issue.
I think this issue may have some conditions to be reproduced.

**Comment by jawngee** [comment]
Thanks for getting back to me.  I can actually reproduce it with the reproduction (its where I recorded the video).  It doesn't happen on every load, you have to reload constantly.  One note maybe I didn't make clear is this ONLY happens in the production build.  So on stackblitz you have to stop the dev server and run the ./run-build.sh script that is in the reproduction stackblitz.

Here's another video I just recorded using the reproduction link I supplied:

https://github.com/nuxt-modules/i18n/assets/44449/6f9f8c91-76b8-4521-9946-0c85fdbee1b6

You'll see it occasionally flash this:

![image](https://github.com/nuxt-modules/i18n/assets/44449/95414403-8864-4472-9ef5-52149cce8849)

The `button.sign-up` is the identifier for the localized text (in this case "Sign Up").

It is hard to see it in the reproduction but on on our production site that has a lot more going on it was super apparent and happened consistently.  We had to remove the i18n module because of it.

I imagine its a hydration issue and us possibly not setting up something correctly.  But the fact that it happens in a simple new nuxt project makes me think its the former.

**Comment by rudolfbyker** [comment]
I have the same (or very similar) issue. Repro here: https://stackblitz.com/edit/github-svtdnq?file=app.vue

**Comment by AhmadAbuyahya** [comment]
I'm having the same issue, although weirdly this happens on all pages except the homepage. did you find a solution?

**Comment by jawngee** [comment]
We were under some time constraints so we just yanked the entire module out and wrote the bits we needed ourselves.

**Comment by thisisandreww** [comment]
Having the same issue here, viewing the source of the page in production shows the translation key for me. But development & preview mode in my local works fine. 

Has anyone found a solution to this yet? or what are the alternatives here?

**Comment by kazupon** [comment]
>Reproduction
>https://stackblitz.com/edit/github-vbabpr

I've just tried to reproduce the blow with latest nuxt i18n v8.0.0-rc.3
I’ll close the issue, because I didn’t see this issue.
If you have still issue that is facing text flashes, please open a new issue **with your reproduction**.

Thanks!
