### ISSUE TITLE
When using nuxt 3 & i18n outputs ошибку @intlify_shared.js

### ISSUE THREAD

**Issue by ghost** [nuxt-modules/i18n#2134]
### Discussed in https://github.com/nuxt-modules/i18n/discussions/2133

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** June  3, 2023</sup>
When using next 3 & i18n, it throws an error related to the cache and the @intlify package

nuxt version - 3.5.2

 nuxt/i18n version - "@nuxtjs/i18n": "8.0.0-beta.12",

Screenshot of the error

<img width="1512" alt="Снимок экрана 2023-06-03 в 17 06 31" src="https://github.com/nuxt-modules/i18n/assets/58338625/243c8352-2aec-414d-871b-4d6248002f31">

Minimal build to view the error: https://github.com/Roman-00/iteca.events/tree/PR-3

</div>

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, We could not reproduce your repo.
We need more detail reproduction step.
Could you give us it please? 🙏

**Comment by ghost** [comment]
Hello! 

repos - https://github.com/Roman-00/test-nuxt-i18n
Minimal repository with an error

Installed i18n in the project, then specified in the modules in nuxt.config

When starting the dev environment, this error falls into the developer console

package manager - using pnpm

**Comment by HuanVo** [comment]
I have same this issue. I add @intlify/nuxt3 to modules in nuxt.config.ts to resolved this issue.

**Comment by kazupon** [comment]
@Roman-00 
Thank you for your reproduction!
However, I could not reproduce this issue 😞 
We need more infomation.
Could you try to run `npx nuxi info` please?

**Comment by ghost** [comment]
> @Roman-00 Thank you for your reproduction! However, I could not reproduce this issue 😞 We need more infomation. Could you try to run `npx nuxi info` please?

what exactly didn't work out? When installing dependencies via pnpm i, then launch the pnp dev project, go to the browser, open the developer console and see the error in the console tab

**Comment by ghost** [comment]
> @Roman-00 Thank you for your reproduction! However, I could not reproduce this issue 😞 We need more infomation. Could you try to run `npx nuxi info` please?

After executing npx nuxi info

Nuxi 3.5.2                                                                                                                                                               4:38:35 PM
                                                                                                                                                                         4:38:35 PM
RootDir: /Users/vassin/PhpstormProjects/test-nuxt-i18n                                                                                                                   4:38:35 PM
Nuxt project info: (copied to clipboard)                                                                                                                                 4:38:36 PM

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                              4:38:36 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

**Comment by ghost** [comment]
> @intlify/nuxt3

?????

**Comment by kazupon** [comment]
Could you try to add `strict-peer-dependencies=false` to `.npmrc` and re-install with pnpm ?

**Comment by ghost** [comment]
Does not work

**Comment by mrFANRA** [comment]
Some error ... 

Server console doesnt have errors.

Chrome console:
caught SyntaxError: The requested module '/_nuxt/node_modules/.cache/vite/client/deps/@intlify_shared.js?v=8d5a169e' does not provide an export named 'assign' (at message-compiler.mjs?v=5cc3b937:6:18)


FireFox console:
Uncaught SyntaxError: ambiguous indirect export: format


![Screenshot_17](https://github.com/nuxt-modules/i18n/assets/20259213/271539e8-74d5-48af-a442-284a835a2a37)

Strangely, everything worked fine and at one moment project fail. Cache clearing, deleting node_modules doesnt help.

**Comment by ghost** [comment]
> Could you try to add `strict-peer-dependencies=false` to `.npmrc` and re-install with pnpm ?

The error exists now, and has not been resolved

**Comment by ghost** [comment]
> Some error ...
> 
> Server console doesnt have errors.
> 
> Chrome console: caught SyntaxError: The requested module '/_nuxt/node_modules/.cache/vite/client/deps/@intlify_shared.js?v=8d5a169e' does not provide an export named 'assign' (at message-compiler.mjs?v=5cc3b937:6:18)
> 
> FireFox console: Uncaught SyntaxError: ambiguous indirect export: format
> 
> ![Screenshot_17](https://user-images.githubusercontent.com/20259213/244761207-271539e8-74d5-48af-a442-284a835a2a37.png)
> 
> Strangely, everything worked fine and at one moment project fail. Cache clearing, deleting node_modules doesnt help.

Please tell me if the problem was solved?

**Comment by ghost** [comment]
> Could you try to add `strict-peer-dependencies=false` to `.npmrc` and re-install with pnpm ?

Here is a reproduction of the error on the sandbox - https://stackblitz.com/edit/nuxt-starter-cdfvem?file=README.md

**Comment by kazupon** [comment]
Thanks.
I've noticed that there isn't `.npmrc` in your reproduction.
I've forked your reproduction, and add `.npmrc` on it.
so, it' works.
https://stackblitz.com/edit/nuxt-starter-8eqht8?file=.npmrc

**Comment by mrFANRA** [comment]
> Thanks. I've noticed that there isn't `.npmrc` in your reproduction. I've forked your reproduction, and add `.npmrc` on it. so, it' works. https://stackblitz.com/edit/nuxt-starter-8eqht8?file=.npmrc

I have this file, with shamefully-hoist=true strict-peer-dependencies=false but error exist =(

**Comment by ghost** [comment]
> mrFANRA

I have this file, with shamefully-hoist=true strict-peer-dependencies=false but error exist =(

**Comment by ghost** [comment]
> Here is a reproduction of the error on the

Here is a reproduction of the error on the repos - https://github.com/Roman-00/iteca

Error playback video

https://github.com/nuxt-modules/i18n/assets/58338625/fd5e6702-38ba-4403-ba62-271731c17e2a

Also, due to the module, there is a bug with auto-updating of the page !!!!!

**Comment by ghost** [comment]
> Thanks. I've noticed that there isn't `.npmrc` in your reproduction. I've forked your reproduction, and add `.npmrc` on it. so, it' works. https://stackblitz.com/edit/nuxt-starter-8eqht8?file=.npmrc

The error remained, the above provided a video + repository in which this error is reproduced. In stackblitz.com there is no way to open the developer console to identify this problem

**Comment by ghost** [comment]
> Thanks. I've noticed that there isn't `.npmrc` in your reproduction. I've forked your reproduction, and add `.npmrc` on it. so, it' works. https://stackblitz.com/edit/nuxt-starter-8eqht8?file=.npmrc

How will the problem be solved? Since now the problem has not disappeared

**Comment by kazupon** [comment]
Ah, That issue had already opened
https://github.com/nuxt-modules/i18n/issues/2098

I thiink that issue is helpful.

**Comment by ghost** [comment]
> Ah, That issue had already opened #2098
> 
> I thiink that issue is helpful.

Nothing from this branch helps

**Comment by Banayaki** [comment]
> > Ah, That issue had already opened #2098
> > I thiink that issue is helpful.
> 
> Nothing from this branch helps

I faced the same issue. Before installing `@nuxtjs/i18n@next`, I accidentally installed `@nuxtjs/i18n`. I believe this was the root of the problem in my case. So, I did a clean `npm install`, and it started working just fine.
