### ISSUE TITLE
silentTranslationWarn true not working 

### ISSUE THREAD

**Issue by jd1378** [nuxt-modules/i18n#2136]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.2
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@3.5.0
- Builder:          vite
- User Config:      typescript, modules, extends, runtimeConfig, app, routeRules, eslint, i18n, svgo, piniaPersistedstate, delayHydration   
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/tailwindcss@6.7.0, nuxt-svgo@3.1.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-swiper@1.1.0, nuxt-delay-hydration@1.2.1
- Build Modules:    -
------------------------------

### Reproduction

-

### Describe the bug

I'm not sure if this should work in dev or not, but it's not working and fallback warns are still printed to console like this:
```
[intlify] Not found 'yes' key in 'tr' locale messages.
[intlify] Fall back to translate 'yes' with root locale.
```

this is my i18n.config.ts:
```ts
export default defineI18nConfig(() => ({
  legacy: false,
  silentFallbackWarn: true,
}));
```

### Additional context

I'm using 8.0.0-beta.12

**Comment by kazupon** [comment]
Thank you for your reporting!

We need minimal reproduction.
Issue bug report said:

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
>👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Could you give us your minimal reproduction please?

**Comment by jd1378** [comment]
sure ! sorry I couldn't add a reproduction at the time of posting this
here you go:
https://stackblitz.com/edit/github-ku29me?file=i18n.config.ts,app.vue,nuxt.config.ts,lang%2Fen-US.js

**Comment by jd1378** [comment]
@kazupon please let me know if there's anything else missing

**Comment by kazupon** [comment]
Hi! 
Thank you for you reproduction!

I noticed that your i18n configuration has mis-taken.
To stop warnings in case of Translation Missing and Fallbacking, from Nuxt I18n v8 (vue-i18n v9), use the following options:

```ts
export default defineI18nConfig(() => ({
  legacy: false,
  fallbackWarn: false,
  missingWarn: false,
}));
```

I will close this issue, but please comment if you still have issue.
Happy coding! :)
