### ISSUE TITLE
middlewares can crash precompile step

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/i18n#2139]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hmeytw?file=server%2Fmiddleware%2Fcsrf.ts,package.json,nuxt.config.ts,i18n.config.ts,app.vue

### Describe the bug

Hi :wave: 

I think this is mostly an upstream issue maybe ? 
But all middleware are applied to `/__i18n__/precompile` so it can easily crash. 

The current workaround is to add an `if` staatement with `!getRequestPath(event).startsWith('/__')` for the users middlewares.
However I didn't tried yet what would happen (as we won't have any control on it) if modules such as[ nuxt-security](https://github.com/baroshem/nuxt-security) adds middlewares that can prevent `/__i18n__/precompile` from returning a response

**Comment by kazupon** [comment]
Thank you for your feedback!

Your feedback is a good point!

As you probably know, vue-i18n translates using i18n resources specified in the `langDir` options or set in `i18n.config.ts`.
Using endpoints, those resources are then precompiled at `/__i18n__/precompile`.
This endpoint is precompiled in `nuxi build` or `nuxi generate` through a prerender step.

I had this issue in my brain but it needs to be addressed.
I would like some advice from the nuxt team. /cc @danielroe 🙏 

And about this issue #2086  related to prerender
