### ISSUE TITLE
App `baseUrl` containing only path is not respected, what breaks translation in production mode

### ISSUE THREAD

**Issue by romikzo** [nuxt-modules/i18n#2150]
### Environment

Reproducible anywhere. Demo on stackblitz is provided. 

### Reproduction

https://stackblitz.com/edit/nuxt-starter-5bpssd

Execute
```bash
npm run build && npm run preview
```
and check the page. It should show "Hello" (which is value of locale message) instead of "example" (which is key)

### Describe the bug

Option `lazy` is enabled and dynamic messages generation is used. If the`baseUrl` setting in `nuxt.config.ts` contains only the path (for example `/api/`), in production mode after successful build translation breaks and shows only keys instead of values.  In the console you can see, that request for precompiled messages returns 404.

### Additional context

It works in dev mode though) I suppose it because dev and prod compilation flows differs.

**Comment by BobbieGoede** [comment]
It looks like this is working on the latest release candidate, I changed your reproduction to demonstrate [here](https://stackblitz.com/edit/nuxt-starter-ht6yw8?file=package.json). Please let me know if you're still running into this issue after installing the latest version!
