### ISSUE TITLE
got unplugin-vue-i18n error when using SFC in Nuxt 3 Project

### ISSUE THREAD

**Issue by ngonam22** [nuxt-modules/i18n#2154]
### Environment

Default Stackblitz environment:

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, vite, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

Fresh project on Stackblitz with Minimal config
https://stackblitz.com/edit/nuxt-starter-dgek8w

### Describe the bug

After append the SFC i18n tag

```
<i18n lang="yaml">
en:
  user: 'User'
vi:
  user: 'Người dùng'
</i18n>
```

I got an error `[plugin:unplugin-vue-i18n] All collection items must start at the same column`, changing the yaml or json format doesn't help

**Comment by kazupon** [comment]
Thank you for your reproting!

I noticed that your unplugin-vue-i18n is configured at `nuxt.config.ts`
unplugin-vue-i18n is included in nuxt i18n module
you don't need to configure it!

Happy coding! :)

**Comment by ngonam22** [comment]
> Thank you for your reproting!
> 
> I noticed that your unplugin-vue-i18n is configured at `nuxt.config.ts` unplugin-vue-i18n is included in nuxt i18n module you don't need to configure it!
> 
> Happy coding! :)

> 

I removed the config of unplugin-vuei18n in `nuxt.config.ts`, and not be able to use the translation specified in SFC `app.vue`.
Can you please take a look at the Stackblitz again? @kazupon

**Comment by ngonam22** [comment]
Never mind, I read the document again and found a typo in my script, silly me. Thank you!
