### ISSUE TITLE
@nuxtjs/i18n Failed to fetch dynamically imported module on Vercel

### ISSUE THREAD

**Issue by LePulsar** [nuxt-modules/i18n#2155]
Hi,

I have an issue while publishing on Vercel with the vueI18n parameter. It is intending to be a String with a relative path, but while it is building on Vercel (SSR) the things look different, paths are changing... 

The error looks like this:
`@nuxtjs/i18n Failed to fetch dynamically imported module: https://myurl.vercel.app/__i18n__/prerender/cfcb45fa.js`

Here is my NuxtConfig file:

```
export default defineNuxtConfig({	
	i18n: {
		baseUrl: process.env.NUXT_BASE_URL,
        strategy: 'prefix_except_default',
		vueI18n: './i18n.config.ts',
        locales: [{
			code: 'en',
			iso: 'en-US'
		  },
		  {
			code: 'es',
			iso: 'es-ES'
		  },
		  {
			code: 'fr',
			iso: 'fr-FR'
		  }],
        defaultLocale: 'fr'
    }	
})
```

Is the a way to just add an object for the vueI18n parameter? Or how to manage that? 

Thank you.

**Comment by kazupon** [comment]
Thank you for your reporting!

But, We need minimal reproduction with stackbliz or GitHub repo, to resolve your issue.
Could you give us it please? 🙏

**Comment by thezumrad** [comment]
@LePulsar Hey! Had the same issue but on Netlify. Seems like solved it by adding "type": "module" to package.json.
Hope it helps you too

**Comment by beejaz** [comment]
I have similar issue on Vercel with Nuxt 3.5.2, Nitro 2.4.1 and @nuxtjs/i18n 8.0.0-beta.12 every GET request in log is filled with this error (everything seems to work but its flooding my logs)

Demo: https://nuxt-i18n-issue-wheat.vercel.app/
Source: https://github.com/beejaz/nuxt-i18n-issue

```
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
```

```
JUN 21 17:33:30.24
200
nuxt-i18n-issue-wheat.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
JUN 21 17:29:46.31
200
nuxt-i18n-issue-wheat.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
JUN 21 17:29:34.28
200
nuxt-i18n-issue-azhe4talw-beejaz.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
JUN 21 17:29:34.16
206
nuxt-i18n-issue-azhe4talw-beejaz.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
JUN 21 17:29:33.67
200
nuxt-i18n-issue-azhe4talw-beejaz.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
JUN 21 17:29:31.02
200
nuxt-i18n-issue-azhe4talw-beejaz.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
JUN 21 17:29:29.64
206
nuxt-i18n-issue-azhe4talw-beejaz.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-b25fc943.mjs
JUN 21 17:29:29.58
206
nuxt-i18n-issue-azhe4talw-beejaz.vercel.app
[GET] /
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/t
```

Edit: I just saw this issue #2170

**Comment by LePulsar** [comment]
> @LePulsar Hey! Had the same issue but on Netlify. Seems like solved it by adding "type": "module" to package.json. Hope it helps you too

Hi @thezumrad Thank you for your feedback. Yeah, it works on Vercel too! You rock!

**Comment by thezumrad** [comment]
> > @LePulsar Hey! Had the same issue but on Netlify. Seems like solved it by adding "type": "module" to package.json. Hope it helps you too
> 
> Hi @thezumrad Thank you for your feedback. Yeah, it works on Vercel too! You rock!

Cool! Glad that it helped.
