### ISSUE TITLE
Question: Prefix prioritization

### ISSUE THREAD

**Issue by OndrejIT** [nuxt-modules/i18n#2158]
Hello how do I set the following behaviour:
if there is a prefix in the url, the one for language detection is used, if there is no prefix, cookies are used, if there are no cookies, the browser language is used.
I can't seem to set this, it always fails on the fact that the browser language has a higher priority than the prefix.

My config is:

> 		strategy: 'prefix_except_default',
		detectBrowserLanguage: {
			alwaysRedirect: true,
			fallbackLocale: 'en',
			redirectOn: 'all',
			useCookie: true,
			cookieCrossOrigin: false,
			cookieDomain: null,
			cookieKey: 'lang',
			cookieSecure: false
		}

Thank you very much, unfortunately I did not read this from the documentation.

**Comment by kazupon** [comment]
Thank you for your feedback.

nuxt i18n v8 has still `detectBrowserLanguage` option issues, first issue #1632 
So, I'm working on that issue.

**Comment by OndrejIT** [comment]
@kazupon ok I'm using version 7.3.1 and nuxt v2 ..
