### ISSUE TITLE
Cannot iterate over json arrays

### ISSUE THREAD

**Issue by atlansien** [nuxt-modules/i18n#2160]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.12.1
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, telemetry, runtimeConfig, devServer, app, css, plugins, serverHandlers, hooks, modules, proxy, i18n, vite, typescript
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/tailwindcss@6.7.0, @pinia/nuxt@0.4.11, @nuxtjs/eslint-module@4.1.0, nuxt-lodash@2.4.1, @nuxtjs/stylelint-module@5.1.0, @nuxt-alt/proxy@2.2.3
- Build Modules:    -
------------------------------

"@nuxtjs/i18n": "^8.0.0-beta.10",

### Reproduction

https://stackblitz.com/edit/github-zr79bh?file=app.vue

### Describe the bug

Nuxt2 could iterate over arrays in the above environment

ja.json
```
{
  "section": {
    "title": "array bug",
    "array": ["text1", "text2"]
  }
}

```

```
    <ul>
      <li v-for="text in $t('section.array')">
        {{ text }}
      </li>
    </ul>
```
but since I upgraded to Nuxt v3 and @nuxtjs/i18n the array $t('section.array') outputs the key

```
s
e
c
t
i
o
n
.
a
r
r
a
y
```

What should be done in v3?
It wasn't even mentioned in the [Migration Guide](https://i18n.nuxtjs.org/migrating/).

**Comment by kazupon** [comment]
Thank you for your reporting!

I think your issue is same as https://github.com/nuxt-modules/i18n/issues/2050
So, you can try to use edge channel version `"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"`. 

BTW, edge channel latest version is  `8.0.0-beta.12-28110710.9b54123`.
https://www.npmjs.com/package/@nuxtjs/i18n-edge?activeTab=versions

**Comment by kazupon** [comment]
And, from nuxt i18n v8 (vue-i18n v9), The translation API like `$t` and `t` function that return string only.
You need to use `$tm` (maybe more use `rt`) functions.
See details here:
https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-api-return-value

**Comment by muhammedjenos** [comment]
@atlansien ,
How did you get this working? i have been trying to retrieve an array from the language file but using $tm('section.array') returns the value in abstract sytax tree format and not an array.

<img width="364" alt="image" src="https://github.com/user-attachments/assets/f63110e6-06fc-4053-a85f-022df2369883">

Currently on nuxt/i18n 8.3.3.

Here is a reproduction in codesandbox
[https://codesandbox.io/p/devbox/bitter-feather-lp5ynm](codesandbox)

Any help much appreciated

**Comment by BobbieGoede** [comment]
@muhammedjenos 
Since you're not using an array of strings but an array of objects, you need to pass the property of said object (from the returned array of `tm()`) into `rt()`, like so:

```javascript
<p v-for="item in tm('summary')">
  {{ rt(item.title) }}
  {{ rt(item.description) }}
  {{ rt(item.price) }}
</p>
```

**Comment by muhammedjenos** [comment]
@BobbieGoede Thank you for the clarification. that work for strings.
But it fail when i have an array  inside an array to loop through, for eg rendering a dropdown with items.

The below doesnt seem to work
Error: Invalid Arguments

`
<UDropdown  :items="rt(item.subNavs)">
`

and this one doesnt seem to work either
Error: ch.charCodeAt is not a function

`<UDropdown  :items="tm(item.subNavs)">`

**Comment by BobbieGoede** [comment]
@muhammedjenos 
I haven't tried this myself but I can try and see what works in a minimal reproduction, either way you'll probably get more answers on https://github.com/intlify/vue-i18n as these functions are provided by Vue I18n.
