### ISSUE TITLE
Error when having HTML in translation files

### ISSUE THREAD

**Issue by dschreij** [nuxt-modules/i18n#2165]
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      ssr, alias, typescript, build, modules, auth, i18n
- Runtime Modules:  (), @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.12, @sidebase/nuxt-auth@0.6.0-beta.2, nuxt-vitest@0.8.5
- Build Modules:    -

### Reproduction

- Create a translation file with HTML in one of the translations
- Launch the nuxt3 app

### Describe the bug

Cannot disable warning/error that occurs when translations contain HTM:

![image](https://github.com/nuxt-modules/i18n/assets/689044/fab34ff5-0578-405e-bf18-9b0f126209c1)

Vue-I18n offers a way to disable/surpress this warning message, but this doesn't seem accessible through nuxt-i18n

https://vue-i18n.intlify.dev/guide/migration/breaking.html#change-warnhtmlinmessage-option-default-value

### Additional context

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/i18n',
  ],
  i18n: {
    lazy: true,
    langDir: './lang',
    locales: [
      {
        code: 'en',
        iso: 'en',
        name: 'English',
        file: 'en.json',
      },
      {
        code: 'nl',
        iso: 'nl',
        name: 'Nederlands',
        file: 'nl.json',
      },
    ],
    defaultLocale: 'en',
    vueI18n: './config/i18n.config.ts',
  },
})
```
The settings below should disable the error message, but don't
```ts
// ./config/i18n.config.ts
export default defineI18nConfig(() => ({
  warnHtmlInMessage: 'off',   // legacy
  warnHtmlMessage: 'off',     // composition
}))
```

**Comment by kazupon** [comment]
Thank you for your reporting!

From v8.0.0-beta.11, vue-i18n now outputs a warning if the message contains html. This is for security reasons to avoid XSS.

If you would like to use messages containing html, you can use them by setting the precompile option.
you need to configure `strictMessage: false` on nuxt i18n module option.

see more about precompile option details:
https://v8.i18n.nuxtjs.org/options/misc#precompile

Thanks!
