### ISSUE TITLE
_ctx.$localePath is not a function

### ISSUE THREAD

**Issue by simkuns** [nuxt-modules/i18n#2168]
### Environment

----------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-6vqdsb?file=app.vue,package.json,nuxt.config.ts

### Describe the bug

According to documentation available at https://v8.i18n.nuxtjs.org/guide/migrating#change-some-export-apis-name-on-nuxt-context it seems that API methods have to be prefixed with $, however it results in 500 error (`_ctx.$localePath is not a function`).

This works, but shows type error in VSCode
<img width="206" alt="Screenshot 2023-06-17 at 02 12 33" src="https://github.com/nuxt-modules/i18n/assets/6117989/66d17284-b927-46dd-8d54-6a144799ff0b">

This does not work and results in 500 error
<img width="213" alt="Screenshot 2023-06-17 at 02 12 47" src="https://github.com/nuxt-modules/i18n/assets/6117989/b0883539-854d-4d93-8cb5-ba68c49a042f">

This does work
<img width="246" alt="Screenshot 2023-06-17 at 02 13 02" src="https://github.com/nuxt-modules/i18n/assets/6117989/10373f6c-8963-4972-b1dc-ccdadca33547">

**Comment by fabkho** [comment]
any updates on this? Having the same problem...

As a workaround i use `<nuxt-link-locale>`, which just works.
[Components · @nuxtjs/i18n](https://v8.i18n.nuxtjs.org/api/components)

**Comment by antlionguard** [comment]
still same problem exist if `$localePath` used outside of setup.

**Comment by Foddie2** [comment]
Getting the error related to this 

> Cannot access 'localePath' before initialization

**Comment by BobbieGoede** [comment]
@Foddie2 please open a new issue with a minimal reproduction 🙏
