### ISSUE TITLE
choose the preferred behavior of prefix_and_default strategy

### ISSUE THREAD

**Issue by abdurrahmanseyidoglu** [nuxt-modules/i18n#2169]
I'm using ```@nuxtjs/i18n": "^7.3.1"```
When ```prefix_and_default ``` strategy is used and I visit http://localhost:3000/en 
the ```'/en'``` gets removed because it's the default language, 
but what if I want to keep the prefix if the user visited http://localhost:3000/en
as mentioned in the docs 

> This strategy combines both previous strategies behaviours, meaning that you will get URLs with prefixes for every language, but URLs for the default language will also have a non-prefixed version (though **_the prefixed version will be preferred_** when detectBrowserLanguage is enabled).

how would I prefer the ```prefixed``` version? 
even more: can I choose which pages the prefixed version would be preferred and which ones to remove the prefix from?
there is a similar issue here: https://github.com/nuxt-modules/i18n/issues/1401
but I'm guessing the feature never got implemented?

**Comment by tux2nicolae** [comment]
Did you find a solution for that?

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
