### ISSUE TITLE
lazy load not runs

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/i18n#2171]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Our nuxt.config.ts config:
`i18n : {
        defaultLocale : process.env.NUXT_PUBLIC_LANG,
        locales: [  {code : 'cs', file: 'cs.json'}, 
                    {code : 'da', file: 'da.json'}, 
                    {code : 'de', file: 'de.json'}, 
                    {code : 'en', file: 'en.json'}, 
                    {code : 'es', file: 'es.json'}, 
                    {code : 'fr', file: 'fr.json'}, 
                    {code : 'it', file: 'it.json'}, 
                    {code : 'nl', file: 'nl.json'}, 
                    {code : 'pl', file: 'pl.json'}, 
                    {code : 'pt', file: 'pt.json'}
                ],
        langDir : 'locales/',
        lazy : true
    },`

our lang filesystem

![image](https://github.com/nuxt-modules/i18n/assets/77386602/ca55da8f-4bac-40d2-94d2-f480cc23658d)

All lang files are loaded :(
![image](https://github.com/nuxt-modules/i18n/assets/77386602/697cfd3f-d127-4aee-a382-15fb310b84ff)

### Describe the bug

Our nuxt.config.ts config:
`i18n : {
        defaultLocale : process.env.NUXT_PUBLIC_LANG,
        locales: [  {code : 'cs', file: 'cs.json'}, 
                    {code : 'da', file: 'da.json'}, 
                    {code : 'de', file: 'de.json'}, 
                    {code : 'en', file: 'en.json'}, 
                    {code : 'es', file: 'es.json'}, 
                    {code : 'fr', file: 'fr.json'}, 
                    {code : 'it', file: 'it.json'}, 
                    {code : 'nl', file: 'nl.json'}, 
                    {code : 'pl', file: 'pl.json'}, 
                    {code : 'pt', file: 'pt.json'}
                ],
        langDir : 'locales/',
        lazy : true
    },`

our lang filesystem

![image](https://github.com/nuxt-modules/i18n/assets/77386602/ca55da8f-4bac-40d2-94d2-f480cc23658d)

All lang files are loaded :(
![image](https://github.com/nuxt-modules/i18n/assets/77386602/697cfd3f-d127-4aee-a382-15fb310b84ff)

**Comment by agracia-foticos** [comment]
for more information We are using srcDir : 'src/',

**Comment by agracia-foticos** [comment]
still waiting

**Comment by kazupon** [comment]
Thank you for your reporting!

However, We could not reproduce this issue...
We need an environment that anyone else can reproduce.

nuxt i18n issue guideline says:

>The reporting guideline of nuxt-modules/i18n is compliant with Nuxt too.
>Please carefully read the contribution docs before creating a bug report.
>👉 https://nuxt.com/docs/community/reporting-bugs
>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
>👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

https://github.com/nuxt-modules/i18n/issues/new?assignees=&labels=pending+triage&projects=&template=bug-report.yml

Could you give us your minimal reproduction env please?

**Comment by agracia-foticos** [comment]
https://stackblitz.com/edit/nuxt-starter-xqe68x

When i run this code with npm run dev, dont appear en.json in network tab in dev tools.

But if i compile with npm run build and node start, en.json appear in network tab in dev tools (lazy load not runs)

**Comment by kazupon** [comment]
related issue #2192

**Comment by agracia-foticos** [comment]
any solution?

**Comment by agracia-foticos** [comment]
with beta 13 dont runts :(

**Comment by kazupon** [comment]
I noticed that lazy loading is not working caused by #2192.
I will revert that PR as it is causing regression. /cc @userquin

**Comment by kazupon** [comment]
Sorry for the late reply.
I have already fixed this issue.
You can try with the edge channel version (`i18n-edge@8.0.0-beta.13-28155649.2e108fa`) 

BTW, your reproduction has the `detectBrowserLanguage` option enabled, so it tries to get the language from the browser or a cookie.
So depending on your environment, the nuxt i18n module to get that locale will also try that locale along with the default locale during initial loading.

Thanks!
