### ISSUE TITLE
Lazy loading function is not working when package.json has "type": "module"

### ISSUE THREAD

**Issue by devhus** [nuxt-modules/i18n#2172]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.14.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      runtimeConfig, devtools, modules, css, typescript, imports, alias, vuetify, i18n
- Runtime Modules:  @nuxt/image@1.0.0-rc.1, nuxt-icon@0.4.1, @sidebase/nuxt-session@0.2.7, dayjs-nuxt@1.1.2, @invictus.codes/nuxt-vuetify@0.2.20, @nuxtjs/i18n@8.0.0-beta.12, nuxt-lodash@2.4.1
- Build Modules:    -

### Reproduction

1- Enable lazy-loading translations mode
2- use defineI18nLocale
```ts
export default defineI18nLocale((locale) => {
  // for example, fetch locale messages from nuxt server
  return $fetch(`/api/${locale}`)
})
```
3- add ``"type": "module"`` to ``package.json``

### Describe the bug

Enabling lazy-loading translations mode while having the "type" of package.json file equal to "module" will cause a bug that prevents lazy-loading the translations from external URLs.

**Comment by kazupon** [comment]
Thank you for your reporting!

However, We could not reproduce this issue...
We need an environment that anyone else can reproduce.

nuxt i18n issue guideline says:

>The reporting guideline of nuxt-modules/i18n is compliant with Nuxt too.
>Please carefully read the contribution docs before creating a bug report.
>👉 https://nuxt.com/docs/community/reporting-bugs
>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
>👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

https://github.com/nuxt-modules/i18n/issues/new?assignees=&labels=pending+triage&projects=&template=bug-report.yml

Could you give us your minimal reproduction env please? 🙏

**Comment by kazupon** [comment]
close in-activity
