### ISSUE TITLE
defaultLocale not wokring when getting translations dynamically (weird flicker)

### ISSUE THREAD

**Issue by xjimdim** [nuxt-modules/i18n#2173]
### Environment

Nuxi 3.4.3
                        
RootDir: /app            
Nuxt project info:      
------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.1                                                                                                                                                                                      1:05:29 PM
- Builder:          vite
- User Config:      app, components, css, postcss, modules, i18n, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.9, @nuxtjs/i18n@8.0.0-beta.11, @nuxtjs/google-fonts@3.0.0, @nuxtjs/device@3.1.0, @nuxtjs/tailwindcss@6.6.6
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/loving-david-ytv9tc?file=%2Fnuxt.config.js%3A26%2C20

### Describe the bug

As you can see in the config, I have set the defaultLocale to "el" (Greek) but for some reason "en" (English) gets loaded at first load of the page (no cookies set).

Also (in my project locally) if I explicitly change it to el using the language switcher then when i refresh the page there's a weird flickering happening where firs the translation keys are shown (for like 1 sec) and then the el translations are shown. This doesnt seem to happen in the reproduction link though, on refresh it just goes back to English.

Any help on this would be greatly appreciated

EDIT: Found out that if I change detectBrowserLanguage to false then the defaultlLocale is respected. But still there's a weird flicker when the page loads:

[Screencast from 21-06-2023 12:32:06 ΜΜ.webm](https://github.com/nuxt-modules/i18n/assets/8918181/18b7e535-18a3-4227-8fd2-01c00b94228b)

**Comment by xjimdim** [comment]
I fixed the flickering issue by deleting the node_modules folder and reinstalling them (got the asnwer from https://github.com/nuxt-modules/i18n/issues/1812). 
This is kinda weird but ok.

Got a question though (related to the defaultLocale and detectBrowserLanguage):
What if i want to use cookies for my language switching but not detect the browser's language? is that a possibility?

For example I want to have "el" as my default language and when switching to "en" (through a dropdown or something) I want it to be kept in a cookie so as to be persistent when the page refreshes. Kinda like the way it works in detectBrowserLanguage but without the whole browser language detection thing.

**Comment by kazupon** [comment]
You can use `useCookieLocale` composable.
https://v8.i18n.nuxtjs.org/api/composables#usecookielocale

As notice, set `detectBrowserLanguage: false` on nuxt config.

This issue has been changed to a question, so we will close.
Thansk!

**Comment by MetalSamurai666** [comment]
So how should it be used? I've turned off `detectBrowserLanguage` and `useCookieLocale` is returning empty value. (I'm trying to use cookie without `detectBrowserLanguage`)

Edit: Docs say that if `detectBrowserLanguage` is turned off it will return empty value and it doesn't make sense. Because it won't let me to set my own default language, not browser's.
