### ISSUE TITLE
route doesn't update with prefix_except_default strategy

### ISSUE THREAD

**Issue by samk-dev** [nuxt-modules/i18n#2175]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.7.1`
- Builder:          `vite`
- User Config:      `devtools`, `modules`, `runtimeConfig`, `colorMode`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.12`, `@nuxtjs/color-mode@3.3.0`, `@vueuse/nuxt@10.2.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-7wffzy?file=app.vue

### Describe the bug

when using prefix_except_default strategy everything works fine but the route doesn't change. going to the route manually works fine `localhost:3000/ca/page`

The expected behaviour is when the routes strategy to prefix_except_default it should update the url to `localhost:3000/locale/page`

Thank you in advanced.

### Additional context

Console is clean from errors

**Comment by kazupon** [comment]
Thank you for your reporting!

I've just checked your reproduction codes.
I found out `pages` directory is not exist in your app.
You need `pages` directory.
nuxt i18n routing strategies works with Nuxt routing.

If you can resolve this issue, please comment on this issue.
we'll re-open this issue.

Thanks!

**Comment by samk-dev** [comment]
Hi @kazupon  thank your help. I have updated the stackblitz reproduction with layouts and pages directories as I have it in my local and it doesn't work as well.  I attached a screeshot of the directories of the app I am working on.

https://stackblitz.com/edit/nuxt-starter-7wffzy?file=app.vue

<img width="253" alt="Screenshot 2023-06-24 at 10 05 57" src="https://github.com/nuxt-modules/i18n/assets/33263129/bb33aa2c-6cf3-4a52-9dba-f8075663c959">

Thanks a lot.

**Comment by gbyesiltas** [comment]
I have the same problem

**Comment by sa8ab** [comment]
I have the same issue.
Although `switchLocalePath` is supposed to be used as `href` of an anchor tag but even if that is not there `setLocale` should work fine and it does not.
I have the same issue even when I am not specifying any strategies.

version: v8.beta-12
nuxt version: 3.6.1
