### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split') at functionsWorker-0.7282352485608163.js:5429:32

### ISSUE THREAD

**Issue by aguirremac** [nuxt-modules/i18n#2176]
### Environment

Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.1
- Package Manager:  pnpm@8.6.3
- Builder:          vite
- User Config:      app, modules, i18n, ssr, runtimeConfig, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @nuxt/devtools@0.5.5, @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/google-fonts@3.0.1
- Build Modules:    -

### Reproduction

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/tailwindcss',
    '@pinia/nuxt',
    '@nuxt/devtools',
    '@nuxtjs/i18n',
    [
      '@nuxtjs/google-fonts',
      {
        families: {
          ABeeZee: true,
          download: true,
          inject: true,
        },
      },
    ],
  ],

  i18n: {
    strategy: 'prefix_except_default',

    locales: [
      {
        code: 'en-GMG',
        iso: 'en-GMG',
        name: 'English(UK)',
        file: 'en-GMG.json',
      },
      {
        code: 'fil-PH',
        iso: 'fil-PH',
        name: 'Filipino',
        file: 'fil-PH.json',
      },
    ],
    lazy: true,
    langDir: 'lang',
    defaultLocale: 'en-GMG',
  },

  ssr: false,

  runtimeConfig: {
    public: {
      commit: process.env.CF_PAGES_COMMIT_SHA || 'UNKNOWN',
      built_at: new Date(),
    },
  },

  devtools: {
    enabled: true,
  },
})

### Describe the bug

0

Does anyone know how to fix this error?

Cannot read properties of undefined (reading 'split') at functionsWorker-0.7282352485608163.js:5429:32

I keep encountering it upon deploying to cloudflare but seems to be working fine on development.

I did look for answers around but no luck!

**Comment by brucethwaits** [comment]
I've been dealing with the exact same issue today. Reverting to beta 10 `@nuxtjs/i18n@8.0.0-beta.10` put a stop to this for me, although I'm having to find other workarounds now...

Comments here helped : https://github.com/nuxt-modules/i18n/issues/1993

**Comment by aguirremac** [comment]
Thank you @brucethwaits, reverting back to  "@nuxtjs/i18n": "8.0.0-beta.10", worked!

**Comment by n-kort** [comment]
Also ran into this, breaks the nitro `netlify-edge` build.

nuxt/nuxt#21719

**Comment by kazupon** [comment]
duplicate issues

#2095
#2031
#1993

**Comment by kazupon** [comment]
This issue was fixed since `@intlify/bundle-utils` is no longer bundled on the server side as of v8.0.0-beta.13.
If you have still issue, please reply.
