### ISSUE TITLE
How can I adjust the generated route order

### ISSUE THREAD

**Issue by robert-luoqing** [nuxt-modules/i18n#2178]
### Describe the feature

I have folder like
```
pages
  └─index
      └─ index.vue
      └─ _authorizing.vue
  └─ influ
       └─ index.vue
```
When I access like http://192.169.1.1:8080/ja/influ. It alway route to  _authorizing.vue. How can I put index-authorizing___ja to last one?

Thanks.

The generated route.json file here
```

[
  {
    "path": "/ja",
    "component": "C:\\\\web\\\\pages\\\\index.vue",
    "chunkName": "pages/index",
    "children": [
      {
        "name": "index___ja",
        "path": "",
        "component": "C:\\\\web\\\\pages\\\\index\\\\index.vue",
        "chunkName": "pages/index/index",
        "_name": "_22719572"
      },
      {
        "name": "index-authorizing___ja",
        "path": ":authorizing",
        "component": "C:\\\\web\\\\pages\\\\index\\\\_authorizing.vue",
        "chunkName": "pages/index/_authorizing",
        "_name": "_41447092"
      }
    ],
    "_name": "_3a8225e0"
  },
  {
    "name": "influ___ja",
    "path": "/ja/influ",
    "component": "C:\\\\web\\\\pages\\\\influ\\\\index.vue",
    "chunkName": "pages/influ/index",
    "_name": "_43a90453"
  },
  {
    "path": "/",
    "component": "C:\\\\web\\\\pages\\\\index.vue",
    "chunkName": "pages/index",
    "children": [
      {
        "name": "index___en",
        "path": "",
        "component": "C:\\\\web\\\\pages\\\\index\\\\index.vue",
        "chunkName": "pages/index/index",
        "_name": "_22719572"
      },
      {
        "name": "index-authorizing___en",
        "path": ":authorizing",
        "component": "C:\\\\web\\\\pages\\\\index\\\\_authorizing.vue",
        "chunkName": "pages/index/_authorizing",
        "_name": "_41447092"
      }
    ],
    "_name": "_3a8225e0"
  }
]


```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
Thank you for your reporting!

We need your minimal reproduction with github repo or stackbliz.
Could you give us it please? 🙏

**Comment by kazupon** [comment]
close in-activity.
if you have still issue, please you would open as new issue with minimal reproduction.
Thanks!
