### ISSUE TITLE
Access current iso code via useI18n

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt-modules/i18n#2181]
### Describe the feature

Would be pretty neat if we could access the current iso so that we can use it with useHead or similar.
Would be ever more neaterer if the nuxt module automatically set this however the complexity might not be worth it.

```js
const { iso } = useI18n()
useServerSeoMeta({
  meta: [{
    ogLocale: iso.value,
  }] 
})
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by sa8ab** [comment]
This should be working for you
```js
const { localeProperties } = useI18n()
const iso = localeProperties.iso
```

Haven't tested the code!

**Comment by kazupon** [comment]
Yes.
You can use `localeProperties`.

Thanks!
