### ISSUE TITLE
Simple project doesn't work

### ISSUE THREAD

**Issue by wanxe** [nuxt-modules/i18n#2183]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

There's the "working" environment
https://stackblitz.com/edit/nuxt-starter-b1mcwg?file=app.vue

### Describe the bug

I tried to run a super simple project but there seems to be no way to import the translation files (locales/....json). But i'm receiving the following error: `[intlify] Not found 'home_title' key in 'en' locale messages.`

Also note that the LangSwitcher can't get the current locales.

What i'm doing wrong?

**Comment by chiuwah** [comment]
Hi, you put config options in the wrong file. It should be in nuxt.config.ts. 

```javascript
// nuxt.config.ts
export default defineNuxtConfig({
  modules: ['@nuxtjs/i18n'],
  i18n: {
    vueI18n: './i18n.config.ts',
    locales: [
      {
        code: 'en-GB',
        iso: 'en-GB',
        name: 'English(UK)',
        file: 'en-GB.json',
      },
      {
        code: 'es-ES',
        iso: 'es-ES',
        name: 'Spanish(ES)',
        file: 'es-ES.json',
      },
    ],
    defaultLocale: 'en-GB',
    lazy: true,
    langDir: 'locales',
    strategy: 'prefix_except_default',
  },
});
```
https://stackblitz.com/edit/nuxt-starter-zqwxra

**Comment by wanxe** [comment]
Oops! Now it works like a charm. Thank you!
