### ISSUE TITLE
Failed to alter I18n configuration via module when layers used

### ISSUE THREAD

**Issue by MagicalSergio** [nuxt-modules/i18n#2186]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.1
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.5
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction
[Repro](https://codesandbox.io/p/github/megFree/i18n-layers-issue-min-repro/main?file=%2Fbase%2Fnuxt.config.ts%3A6%2C4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljfnttbu051t356m16qulmvl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljfnttbu051v356mpioyps33%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljfnttbu051t356m16qulmvl%2522%253A%257B%2522id%2522%253A%2522cljfnttbu051t356m16qulmvl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fbase%252Fnuxt.config.ts%2522%252C%2522id%2522%253A%2522cljfm89ls00g2356m28m9np2w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cljfm89ls00g2356m28m9np2w%2522%257D%252C%2522cljfnttbu051v356mpioyps33%2522%253A%257B%2522id%2522%253A%2522cljfnttbu051v356mpioyps33%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljfocjj803tz356mqh8l41di%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%257D%252C%257B%2522id%2522%253A%2522cljfocz1w042l356m4nz0vv8r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cljfocz1w042l356m4nz0vv8r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. pnpm i -r -f
2. cd ./extends
3. pnpm run dev

### Describe the bug

I have layered project with 2 layers. In my project, I fetch list of locales from external resource. So I need to alter i18n configuration via custom module, which loads locales before @nuxtjs/i18n executes and then change configuration. It was working fine, until I added layers to my project. So now I have empty locales list. If I remove "extends" field from "extends" layer - all works good. What am I doing wrong or this is a bug? Appreciated for any help.

**Comment by kazupon** [comment]
Thank you for your reprorting!
related issue #2206 

You need to configure `i18n` options on the nuxt app side that `extends` the nuxt layer. You configure nuxt i18n options in options in the custom nuxt module in `init-i18n` and set them in `nuxt.options.i18n`, but those options are not available in the nuxt layer extends side because those information is never used by the side that extends the nuxt layer. 

so as the documentation says, only `lazy`, `langDir` and `locales` are used.
https://v8.i18n.nuxtjs.org/guide/layers

**Comment by MagicalSergio** [comment]
@kazupon thank you for your answer!
So, if I got you right, are you suggesting to configure both configs by hand before build? I'm looking for a way to determine and set locales at compile time.
I'm thinking about generating all config files before build using some library for code generation, but it seems like a bit unnatural. And I was hoping you could have a better advice.

**Comment by BobbieGoede** [comment]
@megFree 
Are you still experiencing this issue with the latest edge channel installed? I am unable to check out your reproduction, would be happy to give it a look!

**Comment by kazupon** [comment]
close due to in-activity.
I you have still issue, please you will open the issue as new.

thanks!
