### ISSUE TITLE
[QUESTION] v8.0.0-beta.13 estimated release date

### ISSUE THREAD

**Issue by LeonardoRick** [nuxt-modules/i18n#2190]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.7.1`
- Builder:          `vite`
- User Config:      `devtools`, `css`, `routeRules`, `runtimeConfig`, `modules`, `pinia`, `app`, `nitro`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `@pinia/nuxt@0.4.11`, `@vue-macros/nuxt@1.3.12`, `@nuxtjs/fontaine@0.4.0`
- Build Modules:    `-`

### Reproduction

https://github.com/LeonardoRick/temp-nuxti18n-bug

### Describe the bug

Is there some reason why this major bugs are taking some time do be addressed? I'm new with `nuxt` and It seems like the dream framework but I'm struggling with basic things like:
1. [Just run the quickstart application](https://github.com/nuxt/nuxt/issues/20895#issuecomment-1612851422) with both packages latest version (`nuxt` and `@nuxtjs/i18n`)
2. [deployment on cloudflare](https://github.com/nuxt-modules/i18n/issues/2176)

I wish I had more knowledge so I could also help on this changes. I'm still figuring out how to be helpful because, in my use case, would be awesome to have this things fixed as soon as possible.

That said, Is there some new version already planned to be published? I've seen there's no update on the package for more than a month and, since those bugs are quite impactful, would be nice to have estimation about it.

Thanks for the great lib and to make coding something nice and easier!

### Additional context

The repo provided is a basic example of me just creating a `quick-start` project that triggers the `type: module` bug referred on the description.

**Comment by kazupon** [comment]
Thank you for your feedback!

I've worked on this vue-i18n PR.
https://github.com/intlify/vue-i18n-next/pull/1434

This PR fundamentally solves many of the issues that are causing the nuxt i18n module.

I'm just done and will be integrating this from now on. I estimate that I can have the next release by mid July at the earliest, or by the end of July at the latest.

This issue is closed because it's duplicate issue.

**Comment by LeonardoRick** [comment]
@kazupon thanks for the answer. It seems that the beta13 don't fix the `"type": "module"` bug ([ref](https://github.com/nuxt/nuxt/issues/20895)). Since you marked this as a duplicate, can you please provide me a link of the issue that is supposed to fix that so I can track it's fixing as well? Thanks!
