### ISSUE TITLE
Deprecation warning: i18n:extend-messages is deprecated.

### ISSUE THREAD

**Issue by ahoiroman** [nuxt-modules/i18n#2191]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v20.3.0`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.6.7`
- Builder:          `vite`
- User Config:      `devtools`, `modules`, `routeRules`, `googleFonts`
- Runtime Modules:  `@nuxthq/ui@2.5.0`, `@nuxtjs/i18n@8.0.0-beta.12`, `@nuxtjs/google-fonts@3.0.1`
- Build Modules:    `-`
```

### Reproduction

Add 

```
export default defineI18nConfig(() => ({
    legacy: false,
    lazy: true,
    langDir: 'locales',
    locales: [
        {
            code: 'en',
            file: 'en-GB.json'
        },
        {
            code: 'de',
            file: 'de-DE.json'
        }
    ],
}))
```

to `i18n.config.ts` and run `npm run dev`

### Describe the bug

Notice:

> [@nuxtjs/i18n 2:49:15 PM]  WARN  i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release.

appears. If I check https://v8.i18n.nuxtjs.org/guide/extend-messages, it states, that this hook is correct for module authors, which I am not. I am just trying to translate a plain-ol'-nuxt3-app.

**Comment by kazupon** [comment]
Thank you for your reporting!

That warning will be removed on official release.
Thanks!
