### ISSUE TITLE
[QUESTION] How to use import.meta.glob to dynamically import translations

### ISSUE THREAD

**Issue by Red-Asuka** [nuxt-modules/i18n#2194]
### Environment

Operating System: MacOS
Node Version: v20.3.1
Nuxt Version: 3.6.1
Nitro Version: 2.5.2
Package Manager: pnpm@8.6.5
Builder: vite

### Reproduction

https://stackblitz.com/edit/github-vjsmyp?file=lang%2Fen-US.ts

### Describe the bug

In Nuxt2, I use `require.context` to dynamically import translations, and it works well. Now I'm trying to upgrade the project to Nuxt3 and use `import.meta.glob`. When modifying the code under dev mode, it shows that it works fine after hot update. However, when running dev or build again, it displays an ERROR `'unknown' type in '/Users/xxx/lang/en-US.ts'`.

Is there any way to dynamically import translations?

<img width="651" alt="image" src="https://github.com/nuxt-modules/i18n/assets/38158783/a557c7e2-a81f-4d3f-aca5-1ebc675d95db">

**Comment by kazupon** [comment]
This is a question, so we will move to github disucuttions.
