### ISSUE TITLE
Error on "yarn build", Cannot find module i18n.config-XXXXXX.js

### ISSUE THREAD

**Issue by Faniahy** [nuxt-modules/i18n#2201]
### Environment

![image](https://github.com/nuxt-modules/i18n/assets/31946391/b919b3c6-7d9d-43d6-8320-2bc249ea83e2)

### Reproduction

![image](https://github.com/nuxt-modules/i18n/assets/31946391/89c26c51-8291-4fca-a5b4-2fe910bfeccf)

### Describe the bug

When i run "yarn build", I have this error message that "Cannot find module 'C:\Projects\domaine-du-castex\dist\server\_nuxt\i18n.config-0a1190b0.js'".

### Additional context

This is my project's structure

![image](https://github.com/nuxt-modules/i18n/assets/31946391/bd0a17eb-0e5b-4467-9299-529306684395)

**Comment by Faniahy** [comment]
@kazupon Do you have any Dates to solve the issues #2199 ?

**Comment by kazupon** [comment]
You can install v8.0.0-beta.13
Please try to it!

**Comment by Faniahy** [comment]
@kazupon Sure !
