### ISSUE TITLE
nuxt 3 module i18n dont working on nuxt layers

### ISSUE THREAD

**Issue by productdevbook** [nuxt-modules/i18n#2206]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/productdevbook/i18n-bugs-layer

### Describe the bug

pnpm install
pnpm dev admin

✔ Nitro built in 364 ms                                                                                                                        nitro 11:55:20 AM
[intlify] Not found 'hello' key in 'en-US' locale messages.                                                                                           11:55:21 AM
[intlify] Fall back to translate 'hello' key with 'en' locale.                                                                                        11:55:21 AM
[intlify] Not found 'hello' key in 'en' locale messages.                                                                                              11:55:21 AM
[intlify] Not found 'hello' key in 'en-US' locale messages.                                                                                           11:55:21 AM
[intlify] Fall back to translate 'hello' key with 'en' locale.                                                                                        11:55:21 AM
[intlify] Not found 'hello' key in 'en' locale messages.                                                                                              11:55:21 AM

### Additional context

pnpm install
pnpm dev admin

**Comment by thaikolja** [comment]
Same here. All packages default (using Nuxt Content).

**Comment by Tigriz** [comment]
I got the same problem and tried `nuxi upgrade --force` once again (even though I updated the day 3.6.1 released) and it worked, dunno what happened tbh.

**Comment by productdevbook** [comment]
> I got the same problem and tried `nuxi upgrade --force` once again (even though I updated the day 3.6.1 released) and it worked, dunno what happened tbh.

I updated the repo as you said, still the same problem persists.

**Comment by kazupon** [comment]
Hi!

I’ve checked your minimal reproduction repo.
I’ve noticed that you need to set up two things to make nuxt i18n work with nuxt layer.


### 1. set your custom nuxt module at `modules` options

You need to set your nuxt module defined in the nuxt layer (`layer` dir) of the `layer` dir to `nuxt.config.ts` as follows

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
import MyModule from './module'
export default defineNuxtConfig({
  modules: [
    // https://i18n.nuxtjs.org/
    MyModule,
    '@nuxtjs/i18n',
  ],
  devtools: { enabled: true }
})
```

It seems that the nuxt layer does not automatically install a custom nuxt module if you just define one.

2. configure `i18n` options

For nuxt application (`admin` dir) that extend the nuxt layer, the `i18n` options must be set as follows. The following is a case where lazy loading is used.

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  extends: [
    '../layer'
  ],
  // see the docs: https://v8.i18n.nuxtjs.org/guide/layers
  i18n: {
    lazy: true,
    langDir: 'lang',  // need `lang` dir on `admin`
    locales: [
      {
          code: 'en',
          file: 'en.json',
      },
      {
          code: 'fr',
          file: 'fr.json',
      },
    ]
  }
})
```

If lazy loading is not used, at least the `locales` option must be defined; if locales does not have resource definitions in files, an empty array must be defined in `files`.

@BobbieGoede 
If you have anything to add about the layer of nuxt i18n module, please comment. 🙏

**Comment by BobbieGoede** [comment]
Now that #2290 has been merged the configuration @kazupon described in step 2 are not necessary anymore. All you have to change in your reproduction is registering your module as mentioned. 

I have changed your reproduction to demonstrate it works with the edge channel installed (I registered the module by putting it in a `modules` folder) check it out [here](https://stackblitz.com/edit/github-ufrztv?file=layer%2Fnuxt.config.ts,admin%2Fnuxt.config.ts).

Please let me know if you're still experiencing any issues even with the latest edge version installed!

**Comment by productdevbook** [comment]
@BobbieGoede 

![image](https://github.com/nuxt-modules/i18n/assets/38668796/aa8df261-9390-4809-b68e-f0856226c892)


same repo nuxt 3.7.1 dont working 

```
    "@nuxtjs/i18n": "8.0.0-rc.4",

```

**Comment by skoenfaelt** [comment]
It is not working, if the Layer is installed as node dependency. 
https://github.com/nuxt-modules/i18n/discussions/2388

Should we start a new Issue or reopen?
