### ISSUE TITLE
Question related to loading translations

### ISSUE THREAD

**Issue by AndreiMaelstrom** [nuxt-modules/i18n#2209]
Hello,

I've been browsing through documentation and online resources but didn't manage to figure out a way of loading the translations on the server-side (so that they get rendered through SSR). My use case is that my translations are coming from an API that is only meant to be accessible from local network, and these translations need to be dynamic (i.e i cannot generate them statically as json files). At the moment all the solutions that i tried do call the API on the client side, or generate hydration issues (different translation on client vs server). What I would like to achieve essentially is to load all the translations per language/locale from my API when the Nuxt application is started. Any help would be highly appreciated.

Thanks,
Andrei

**Comment by kazupon** [comment]
This is a question, not issue, so We will move to Github Discussions.
