### ISSUE TITLE
Provide a nuxt-link-locale component who combine nuxt-link + localePath

### ISSUE THREAD

**Issue by albertlast** [nuxt-modules/i18n#2222]
### Describe the feature

I see many code where code like this is used:
```html
<nuxt-link :to="localePath('/')">{{ $t('home') }}</nuxt-link>
```
so i could imagine it would lead to a better dev experience when a own component would exists,
which improve the read ability (may also easier to convert existing code)

So idea would be something like that:
```html
<nuxt-link-locale to="/">{{ $t('home') }}</nuxt-link-local>
```

It would be also allow easier to tracking code places where locale is not done (for good/bad reasons).

to think this further:
```html
 <!-- with lang para -->
<nuxt-link :to="localePath('index', 'en')">Homepage in English</nuxt-link>
<nuxt-link-locale to="index" lang="en">Homepage in English</nuxt-link-local>

<!-- change language -->
<nuxt-link :to="switchLocalePath('en')">English</nuxt-link>
<nuxt-link-locale switch="en">English</nuxt-link-local>
```

About "Could this feature be implemented as a module?" i don't know enough internal stuff about vue/nuxtjs/i18n to awnser this.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
Thank you for your feedback!

Your idea looks useful!
Certainly writing a localePath in addition to the nuxt-link component every time would be tedious.

@ineshbose @dargmuesli @BobbieGoede 
We would like to discuss if there are any other concerns.

**Comment by dargmuesli** [comment]
Sounds good to me!

**Comment by BobbieGoede** [comment]
Looks like a useful component!

@kazupon
Is this something that would be implemented in `@nuxtjs/i18n` or in `@intlify/routing`?
And would this be useful for i18n Vue projects without Nuxt (I haven't used i18n outside of Nuxt myself)? If that is the case the component name would need to change, maybe `<locale-link>` or `<i18n-link>`?

**Comment by dargmuesli** [comment]
If it was based on `NuxtLink` it should be implemented in `@nuxtjs/i18n`, I'd say. If it's for made for Vue it can be pulled up a level of course.

**Comment by ineshbose** [comment]
Love this. Have had this on my mind for long now, I'm thinking more of overriding `NuxtLink` to possibly have an `locale` property of type `[Boolean, String]`? Another Nuxt function in this area is `navigateTo()`.
