### ISSUE TITLE
nuxt-link doesn't navigate probably when using `prefix_and_default` strategy

### ISSUE THREAD

**Issue by saifobeidat** [nuxt-modules/i18n#2227]
### Environment

OS: Windows 10
Node: 16.16.0
nuxt: "^3.6.2"
"@nuxtjs/i18n": "^8.0.0-beta.13"

### Reproduction

![i18n](https://github.com/nuxt-modules/i18n/assets/24841143/19910786-cd95-41da-8bda-29e759e9abd4)

Here you can try by yourself 
https://githubd2hhcf-55yd--3000--e809191e.local-credentialless.webcontainer.io/

and here's the reproduction:
https://stackblitz.com/edit/github-d2hhcf?file=app.vue
 

### Describe the bug

Hello...

First thanks for your effort for making this work no nuxt3..

We are currenlty migrating our app from nuxt2 and nuxt3.. and we are facing a major issue.

I am not able to navigate to another page route (default local) using nuxt-link.. I can navigate to page using other locale, but I can't get back to home ( it keeps me redirecting me to another page) as shown in the attached GIF image:

**Comment by ahmedragab20** [comment]
same here too

**Comment by kazupon** [comment]
Thank you for you reporting!

This is deplication issue #2226 

so, close
