### ISSUE TITLE
500 error on production environment

### ISSUE THREAD

**Issue by waleedtariq109** [nuxt-modules/i18n#2228]
### Environment

OS: Linus
Node: v18.16.0
Nuxt: v3.5.1
Environment: Production

### Reproduction

N/A

### Describe the bug

Hello everyone, I am facing a strange issue. When I deploy my application to the production environment and then visit the deployed application, it doesn't work. Upon checking the server logs, I discovered the following error. I also want to mention that my application runs perfectly fine in the local environment; the issue only occurs in production. Specifically, the problem seems to be related to nuxt/i18n on the production server.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Error
1|Sukuk-In |   at createCompileError (./.output/server/node_modules/.nitro/@intlify/message-compiler@9.3.0-beta.19/dist/message-compiler.mjs:54:19)
1|Sukuk-In |   at createI18nError (./.nuxt/dist/server/server.mjs:2799:10)
1|Sukuk-In |   at useI18n (./.nuxt/dist/server/server.mjs:4053:11)
1|Sukuk-In |   at ./.nuxt/dist/server/server.mjs:7180:22
1|Sukuk-In |   at processTicksAndRejections (node:internal/process/task_queues:95:5)
1|Sukuk-In |   at Proxy.nuxtInit (./.nuxt/dist/server/server.mjs:4659:11)
1|Sukuk-In |   at ./.nuxt/dist/server/server.mjs:7212:67
1|Sukuk-In |   at Object.callAsync (./.output/server/node_modules/unctx/dist/index.mjs:72:16)
1|Sukuk-In |   at applyPlugin (./.nuxt/dist/server/server.mjs:128:35)
1|Sukuk-In |   at applyPlugins (./.nuxt/dist/server/server.mjs:144:7)
```

**Comment by kazupon** [comment]
Thank you for you reporting!

We need the your minimal reproduction 
Issue guideline said:

> Please use a template below to create a minimal reproduction, and provide to us your issue cases
> 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

https://github.com/nuxt-modules/i18n/issues/new?assignees=&labels=pending+triage&projects=&template=bug-report.yml

Could you give it to us, please?

**Comment by kazupon** [comment]
close inactivty.
if you have still issue, please you would open as new issue with minimal reproduction.

Thanks!

**Comment by waleedtariq109** [comment]
@kazupon The issue is fixed actually the other lib causing isssue not i18n
