### ISSUE TITLE
`Compilation is not supported in this build` error

### ISSUE THREAD

**Issue by Dananz** [nuxt-modules/i18n#2231]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-3kuem5?file=nuxt.config.ts

### Describe the bug

After updating to the latest edge channel version, I get the following error:

```[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'common.close'.```

**Comment by ThomasBerne** [comment]
I got the same problem

**Comment by kazupon** [comment]
Thank you for your reporting!

I've noticed that `vue-i18n@9.2.2` is installed in your reproduction.
I don`t know how you installed it, but once clean with `rm -rf node_modules package-lock.json` and try `npm install`. 

I think you can see to work correctly.

**Comment by TomerDanan** [comment]
@kazupon Fixed after removing `node_modules` & `package-lock.json` and re-installing. Thanks!
