### ISSUE TITLE
cannot translate language in dynamic translation when my setup i18n for new version config but working in en.json/th.json file

### ISSUE THREAD

**Issue by dexon-panupong** [nuxt-modules/i18n#2233]
**Environment**

- Operating System: Windows 10
- Node Version: v16.15.0
- Nuxt Version: 3.5.3
- Package Manager: pnpm@8.6.3
- User Config: runtimeConfig, modules, app, css, i18n, imports
- Runtime Modules:@unocss/nuxt, @nuxtjs/i18n@8.0.0-beta.10

($t, t, rt, tm) not working in all dynamic translation

old nuxt.config.ts working all dynamic translation
`import i18nOptions from './lang/i18n'
export default defineNuxtConfig({
modules: [
    '@nuxtjs/i18n'
  ],
i18n: i18nOptions,
})
`

nuxt.config.ts:
`export default defineNuxtConfig({
modules: [
    '@nuxtjs/i18n'
  ],
i18n: {
    locales: ['en', 'th'],
    defaultLocale: 'en',
    switchLocalePath: '/:lang/:route',
    setLocaleCookie: true,
    getLocaleCookie: 'i18n_loc',
    vueI18nLoader: true,
    globalInjection: true,
    vueI18n: './lang/i18n.config.js',
  }
})
`

`<i18n locale="en" src="@/lang/en/terms-and-conditions.json"></i18n><i18n locale="th" src="@/lang/th/terms-and-conditions.json"></i18n><script setup>
const { rt, tm, t } = useI18n()
</script>
<template><h1 class="text-7xl font-bold">{{ t('meta.title') }}</h1></template>
`

**Comment by kazupon** [comment]
Thank you for your reporting!

Nuxt i18n module of your environment is `@8.0.0-beta.10`

Since then, v8.0.0-beta.11 and later have undergone significant internal structural changes, so your environment may be out of date.
Please try v8.0.0-beta.13 or edge channel version.

And, as the nuxt i18n module issue guideline also 
says, please give a minimal reproduction with stackbliz or gihtub repo, so we need it to find out your issue. 🙏

**Comment by dexon-panupong** [comment]
Thanks you, @kazupon  i already solved!

old environment
"vue-i18n": "^9.3.0-beta.16",
"@nuxtjs/i18n": "^8.0.0-beta.10",
"nuxt": "^3.2.2",
"pnpm@7.9.0",

new environment
"vue-i18n": "^9.2.2",
"@nuxtjs/i18n": "^8.0.0-beta.13",
"nuxt": "^3.6.2",
"npm@8.5.5"

key of solved
"vue-i18n": "^9.3.0-beta.16" >> "vue-i18n": "^9.2.2"
"pnpm@7.9.0" >> "npm@8.5.5"

my stackblitz
https://stackblitz.com/edit/nuxt-starter-i18n

**Comment by dexon-panupong** [comment]
but $t is not working you can help me? @kazupon

**Comment by kazupon** [comment]
Why do you install vue-i18n together nuxt i18n module?
nuxt i18n module has already included vue-i18n
you don't need it.

**Comment by webmaster-dexontechnology** [comment]
Solved after uninstall vue-i18n

**Comment by dexon-panupong** [comment]
Solved after uninstall vue-i18n
