### ISSUE TITLE
Hydration mismatch warning + delay before translations gets shown on page load after adding Vuetify

### ISSUE THREAD

**Issue by kevpug** [nuxt-modules/i18n#2237]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      vite, telemetry, imports, modules, css, build, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13-28155649.2e108fa
- Build Modules:    -

### Reproduction

I stole a working example from #1812
https://stackblitz.com/edit/github-us1wuk-jm1nqh?file=nuxt.config.ts

Steps to reproduce:
1. Launch working example
2. See that it works perfectly. No hydration mismatch / delay
3. Stop app and install Vuetify: npm i vuetify
4. Launch app back again and observe
5. See delay on page reload / See hydration mismatch warnings on page reload
6. Cry and consider a career change

### Describe the bug

There's a delay to the translation; I can see all the translation keys instead of their corresponding text at first. After a slight delay the text gets filled up with the right content and my console gets blowed up REAL GOOD by hydration mismatch warnings.

**I still get the hydration mismatch warnings even after using the edge version and removing node_modules/.nuxt/package-lock.json**

Removing Vuetify will make the slight delay / hydration mismatch go away.
Having a plugin file for vuetify or not does not change the outcome.

Example of said warning: 
chunk-BVQHDTV7.js:1449 [Vue warn]: Hydration text mismatch:
- Client: "SERVICES.TITLE "
- Server: "Services TI " 
  at <VOverlay ref=Ref< undefined > class="v-menu menuService" style= {}  ... > 
 ...
 
 It does that for every i18n key used on the page.

**Comment by kazupon** [comment]
Thank you for your reporting!

I have figured out that the nuxt i18n module is loading vue-i18n v9.2.2 on the server-side.

The nuxt i18n module installs the latest version of vue-i18n v9.3.0 beta. However, installing vuetify installs vue-i18n v9.2.2 with node_modules. Perhaps the vue-i18n version information specified in vuetify's peerDependencies is causing npm to install the latest stable version of vue-i18n.

By the way, if you run the installation with the yarn clasic stable version, it works fine.

**Comment by kevpug** [comment]
Thanks a lot ! 

I used yarn instead like you mentioned and it works perfectly now :)
