### ISSUE TITLE
Error when using dev-mode in layer

### ISSUE THREAD

**Issue by niklaswolf** [nuxt-modules/i18n#2238]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `extends`, `hooks`, `runtimeConfig`, `modules`, `i18n`
- Runtime Modules:  `modules/domainRuntimeInfo`, `nuxt-schema-org@2.2.0`
- Build Modules:    `-`

### Reproduction

I'll try to provide a repro later

### Describe the bug

I use nuxt-i18n edge version (latest version) in a project with a nuxt-layer.
The dev-mode is working in the layer, but not in the project using the layer
When I start the site in dev mode, the following error message shows in the browser
```
[vite-node] [ERR_INVALID_ARG_VALUE] @nuxtjs/i18n/main/i18n.config.ts&hash=57b8ea29&from=./.nuxt/i18n.options.mjs
```

When I build both sites (layer and project) and start them in prod mode, both work. So there seems to be something strange in dev-mode when using a nuxt-layer.

### Additional context

I18N configuration in both projects (layer and main-project)

```
i18n: {
    skipSettingLocaleOnNavigate: true,
    differentDomains: true,
    types: 'composition',
    locales: [
      {
        code: 'en-GB',
        file: 'en.json',
        domain: 'www.example.com'
      },
      {
        code: 'de-DE',
        file: 'de.json',
        domain: 'www.example.de
      },
    ],
    compilation: {
      strictMessage: false,
    },
    lazy: false,
    langDir: 'PATH_TO_DIR',
    defaultLocale: 'en-GB',
  },
```

**Comment by kazupon** [comment]
Thank you for your reporting!

We need the minimal reproduction to find out the cause.
Could you give us it with stackbliz or github repo, please ? 🙏

**Comment by niklaswolf** [comment]
@kazupon  finally found the time to make a reproduction.
Here you go: https://github.com/niklaswolf/nuxt-i18n-reproduction

**Comment by niklaswolf** [comment]
I think I found the place where the NULL byte is added: https://github.com/nuxt-modules/i18n/blob/next/src/gen.ts#L182 
its the `genDynamicInput` function. I modified the code a bit into seperate variables and found this when logging it:
```
@nuxtjs/i18n:gen importSpecifier  @nuxtjs/i18n/__config__?target=../i18n.config.ts&hash=da2031ea 

@nuxtjs/i18n:gen dynamicImportSpecifier  () => import("\u0000@nuxtjs/i18n/__config__?target=../i18n.config.ts&hash=da2031ea" /* webpackChunkName: "i18n_config_da2031ea" */) 
```

**Comment by niklaswolf** [comment]
Okay I think I tracked this down 🥳 
I'll try to explain using code references:

`asVirtualId` is called here
https://github.com/nuxt-modules/i18n/blob/next/src/gen.ts#L307C35-L307C46

It adds `\0` as a prefix: https://github.com/nuxt-modules/i18n/blob/next/src/transform/utils.ts#L16 

`genDynamicImport` from `knitwork` uses `JSON.stringify` internally, see https://github.com/unjs/knitwork/blob/main/src/string.ts#L3

If you run `JSON.stringify("\0asdf")` in node, you get `'"\\u0000asdf"'`

**Comment by kazupon** [comment]
@niklaswolf 
Thank you for your reproduction!
And your track code explanation is so helpful for us.
So, I'll try to fix this issue.

Maybe, this issue is also related to #2242

**Comment by kazupon** [comment]
This issue is same #2242.
It cause that the import IDs dynamically generated by nuxt i18n by vite are not being resolved correctly.
The error is different from #2242, but the root cause is the same.
