### ISSUE TITLE
Opting out of JIT mode

### ISSUE THREAD

**Issue by Ingramz** [nuxt-modules/i18n#2241]
### Describe the feature

Would it be possible to make JIT mode configurable such that use cases where messages are already precompiled to functions do not require message compiler in client bundle?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
Thank you for your feedback!

We can support about it!
We need to support it vue-i18n side.

BTW, for opt-out supporting, note that it means that we must precompile the locale resources ourself, and that we cannot dynamically retrieve locale resources from the API.

**Comment by Ingramz** [comment]
What do you think of just making this setting configurable for time being? https://github.com/nuxt-modules/i18n/blob/53161c6edfef24b09dcbee5d69ffb7686655582c/src/bundler.ts#L73-L75

**Comment by Ingramz** [comment]
Thank you!
