### ISSUE TITLE
ERROR  [nuxt] [request error] [unhandled] [500] The requested module 'file:///app/node_modules/@intlify/core-base/index.mjs' does not provide an export named 'compile'

### ISSUE THREAD

**Issue by mbWebExperience** [nuxt-modules/i18n#2243]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.17.1
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.7.2
- Builder:          vite
- User Config:      devtools, modules, i18n, vuetify, hooks, alias, components, runtimeConfig, imports, pinia, devServer, build
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13, @invictus.codes/nuxt-vuetify@0.3.0, @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-naand4?file=nuxt.config.ts,package-lock.json,pages%2Findex.vue,pages%2Fcontact.vue

In this stackblitz everything works wel. But on my Windows machine and in the Github build package process it fails.

### Describe the bug

I have this error (zie logs) only in production (npm run build, node .output/server/index.mjs). 
In development (npm run dev) everything works wel.

This project uses Vuetify (@invictus.codes/nuxt-vuetify) and I18n, when I disable one of the two everything works fine

{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@invictus.codes/nuxt-vuetify": "^0.3.0",
    "@nuxt/devtools": "latest",
    "@nuxtjs/i18n": "^8.0.0-beta.13",
    "@types/node": "^18.16.19",
    "nuxt": "^3.6.3",
    "sass": "^1.63.6",
    "sass-loader": "^13.3.2",
    "vite-svg-loader": "^4.0.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.4"
  }
}

I don't know for sure if this is an I18n problem, but hopefully someone can help us.

### Logs

```shell
Windows machine

Listening http://[::]:3000
[nuxt] [request error] [unhandled] [500] The requested module '@intlify/core-base' does not provide an export named 'compile'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
  at async /E:/sites/testnode3_2/testv2/.output/server/chunks/handlers/renderer.mjs:90:24
  at async /E:/sites/testnode3_2/testv2/.output/server/chunks/handlers/renderer.mjs:171:64
  at async /E:/sites/testnode3_2/testv2/.output/server/chunks/handlers/renderer.mjs:36:22
  at async Object.handler (/E:/sites/testnode3_2/testv2/.output/server/node_modules/h3/dist/index.mjs:1284:19)
  at async Server.toNodeHandle (/E:/sites/testnode3_2/testv2/.output/server/node_modules/h3/dist/index.mjs:1359:7)

Github:
#12 41.28  ERROR  [nuxt] [request error] [unhandled] [500] The requested module 'file:///app/node_modules/@intlify/core-base/index.mjs' does not provide an export named 'compile'
#12 41.28   at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)  
#12 41.28   at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)  
#12 41.28   at async Promise.all (index 0)  
#12 41.28   at async ESMLoader.import (node:internal/modules/esm/loader:530:24)  
#12 41.28   at async ./.nuxt/prerender/chunks/renderer.mjs:88:24
```

**Comment by kazupon** [comment]
Thank you for your reporting!

I noticed that I have figured out that the nuxt i18n module is loading vue-i18n v9.2.2 at `@invictus.codes/nuxt-vuetify`
package-lock.json:
```
...
    "node_modules/@invictus.codes/nuxt-vuetify/node_modules/vue-i18n": {
      "version": "9.2.2",
      "resolved": "https://registry.npmjs.org/vue-i18n/-/vue-i18n-9.2.2.tgz",
      "integrity": "sha512-yswpwtj89rTBhegUAv9Mu37LNznyu3NpyLQmozF3i1hYOhwpG8RjcjIFIIfnu+2MDZJGSZPXaKWvnQA71Yv9TQ==",
      "dev": true,
      "optional": true,
      "peer": true,
      "dependencies": {
        "@intlify/core-base": "9.2.2",
        "@intlify/shared": "9.2.2",
        "@intlify/vue-devtools": "9.2.2",
        "@vue/devtools-api": "^6.2.1"
      },
      "engines": {
        "node": ">= 14"
      },
      "peerDependencies": {
        "vue": "^3.0.0"
      }
    },
...
```

I seem that this issue is occured cause same as #2237.

The nuxt i18n module installs the latest version of vue-i18n v9.3.0 beta. However, installing `@invictus.codes/nuxt-vuetify` installs vue-i18n v9.2.2 with node_modules.

**Comment by rchl** [comment]
Issues like that were being fixed within the modules in Nuxt 2 by creating an alias for a given package and referencing the package using an alias instead of the original name.

For example here is how Sentry module does that in Nuxt 2: https://github.com/nuxt-community/sentry-module/blob/782b9d186bcc6fc144c229876a8321a48789a3f2/src/module.ts#L91-L100

I don't know what's the recommended way of handling that in Nuxt 3 but I would guess it might require similar approach.

The issue stems from the fact that during module initialization the package resolution would work as expected but bundled code would no longer have the same structure so it would not necessarily lookup the correct version.

**Comment by Insayt** [comment]
Hello my friend. I got with the same problem. Helped directly install the dependencies of the required versions in the project.
```
yarn add @intlify/core-base@9.3.0-beta.22
yarn add @intlify/shared@9.3.0-beta.24
```

**Comment by mbWebExperience** [comment]
Thanks guys, for the quick responses! We have"victory one this one"! 
Insayt solution was the key. 
First I removed node_modules, and .nuxt and then install and build everything with yarn

**Comment by rchl** [comment]
Switching to yarn is not a solution but either a workaround or just a coincidence due to packages getting hoisted differently.

This should work with any package manager.

**Comment by v-js-d** [comment]
> Hello my friend. I got with the same problem. Helped directly install the dependencies of the required versions in the project.
> 
> ```
> yarn add @intlify/core-base@9.3.0-beta.22
> yarn add @intlify/shared@9.3.0-beta.24
> ```

thx, it helped me! but I think it's still a temporary solution.

**Comment by fengxiaooctober** [comment]
> yarn add @intlify/core-base@9.3.0-beta.22
> yarn add @intlify/shared@9.3.0-beta.24

That actually helped, thx a lot.
But why the h*** this version is released?. It must took a lot of time to find the right matching version

**Comment by mrnasil** [comment]
> Hello my friend. I got with the same problem. Helped directly install the dependencies of the required versions in the project.
> 
> ```
> yarn add @intlify/core-base@9.3.0-beta.22
> yarn add @intlify/shared@9.3.0-beta.24
> ```

Thanks. Worked for me.

**Comment by jrutila** [comment]
I added the following to the `package.json` to fix this issue.
```
  "overrides": {
    "@intlify/core-base": "9.3.0-beta.25",
    "@intlify/shared": "9.3.0-beta.25"
  }
```

**Comment by lobermann** [comment]
Running into the same issue after updating to the latest version of a nuxt3 project. Adding the overrides did not help. Reverted back to @nuxtjs/i18n 8.0.0-beta.12 for now. Will wait for the next updates to try again.

**Comment by jrutila** [comment]
@lobermann I have the overrides working with 8.0.0-rc.2 (the latest is rc.3 which has problems in static generate).

**Comment by BobbieGoede** [comment]
Closing this as I believe this issue has been resolved for a while, if anyone is still experiencing this specific issue let me know and I will reopen. If you're experiencing something similar but not exactly the same please open a new issue with reproduction, thanks!

**Comment by vladovsiienko** [comment]
Still the same issue when upgrading @nuxtjs/i18n to v8.0.1 and above

**Comment by VladAnn9** [comment]
Still the same issue when upgrading @nuxtjs/i18n to v8.0.1 and above

**Comment by BobbieGoede** [comment]
> Still the same issue when upgrading @nuxtjs/i18n to v8.0.1 and above

@VladAnn9 
Have you tried updating to the latest version and refreshing lockfiles? Otherwise, could you open a new issue and provide a minimal reproduction?

**Comment by Mastercuber** [comment]
@BobbieGoede 
Specifying the explicit versions with `resolutions` solved the problem for `pnpm` and  for `yarn`. With `npm` the solution from @jrutila should work, since npm doesn't use the `resoultions` key but `overrides` instead. 

```json
"resolutions": {
  "vue-i18n": "^11.0.1",
  "@intlify/core": "^11.0.1",
  "@intlify/shared": "^11.0.1"
}
```
without this, for some reason an older version of the package `vue-i18n` as declared in the `package.json` of `@nuxtjs/i18n`, and as manually declared in the projects `package.json` ,  was used. In my case (version 9.12.x; though 10.0.5 was declared). This was visible through the provided `source-view` link of the package in the browser dev tools console, since the version of vue-i18n, vue, and also typescript are visible through this link.
