### ISSUE TITLE
8.0.0-beta.13 strategy: 'prefix_and_default' break NuxtLink click behavior

### ISSUE THREAD

**Issue by ausir0726** [nuxt-modules/i18n#2244]
### Environment

Nuxi 3.6.3

RootDir: /home/projects/nuxt-starter-yqdegx
Nuxt project info: 
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-yqdegx?file=pages%2Findex.vue

when use 8.0.0-beta.13
NuxtLink with localePath generated correct A href , but miss click behavior ( change page )

stop the termanal , and type yarn add @nuxt/i18n@8.0.0-beta.12 and yarn run dev
and everthing work fine

### Describe the bug

8.0.0-beta.13 upgraded break NuxtLink click behavior

**Comment by ausir0726** [comment]
in my research,
it's only happen with config `strategy: 'prefix_and_default'`

**Comment by 0856344** [comment]
I got the same issue with "prefix_and_default".

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue has fixed already by #2240
So you can try to install edge channel version.

Thanks!

**Comment by ausir0726** [comment]
@kazupon 

As the documentation suggests installing using yarn add @nuxt/i18n@next, it will default to installing beta.13. Therefore, to avoid any ambiguity in development and potential challenges during updates, it would be beneficial to release a hotfix for beta.14 as soon as possible.

Once again, I want to express my gratitude to you and all the contributors for your dedication and assistance.
