### ISSUE TITLE
hook i18n:beforeLocaleSwitch does not use the locale that is return in the function

### ISSUE THREAD

**Issue by joeykamsteeg** [nuxt-modules/i18n#2248]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `build`, `css`, `devtools`, `modules`, `nitro`, `postcss`, `routeRules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.11`, `@nuxt/image@1.0.0-rc.1`, `nuxt-api-party@0.13.0`, `@nuxtjs/i18n@8.0.0-beta.13`
- Build Modules:    `-`

### Reproduction

i18n.server.ts

```typescript
export default defineNuxtPlugin( nuxtApp => {
  nuxtApp.hook( 'i18n:beforeLocaleSwitch', ( { oldLocale, newLocale, initialSetup, context } ) => {
    if ( initialSetup ) {
        return 'nl-nl';
    }
  } );
} )

```

### Describe the bug

According to the docs:

```
Called before the app's locale is switched. Can be used to override the new locale by returning a new locale code.
```

This is not happing and it is still using the locale that is defined on variable `newLocale`

Edit: typo's

**Comment by kazupon** [comment]
Thank you for your reporting!

We need minimal reproduction.
Could you give us about it with stackbliz or github repo please? 🙏

**Comment by joeykamsteeg** [comment]
@kazupon I have made a reproduction repository, it can be found here: https://github.com/joeykamsteeg/nuxt3-i18n-beforelocaleswitch-hook-not-working

**Comment by kazupon** [comment]
Thank you for your minimal reproduction!

`i18n:beforeLocaleSwitch` is hooked when `NuxtLink` or `setLocale` involves a change of locale. since your code does not switch the locale in those ways. the hook you defined will not be called. you need to switch the locale.

**Comment by joeykamsteeg** [comment]
This hook is also triggered on app load (according to the documentation) and with initialSetup property I could hook my own logic how to handle URLs without locale in the URL. This is now not possible
