### ISSUE TITLE
Tag `i18n` not supported as described in vue-i18n guide for interpollation

### ISSUE THREAD

**Issue by SimonSimCity** [nuxt-modules/i18n#2253]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, devtools
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-kh9jk9?file=i18n.config.ts,app.vue

Create a new repo, set it up for translation. Try to use the `i18n` tag as defined in the `vue-i18n` guide for interpollation.

### Describe the bug

I tried to use the component interpollation, which uses the tag `i18n`, as described in the vue-i18n documentation (https://kazupon.github.io/vue-i18n/guide/interpolation.html#basic-usage).

The tag seems to be ignored, and I couldn't find anything in the documentation which stated this as a current limitation.

**Comment by kazupon** [comment]
nuxt i18n module use Vue I18n v9.
`i18n` tag (Translation Component) is ranamed to `i18n-t` tag in Vue I18n v9
please read docs breaking change section.
https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-component

FYI: I've just added Vue I18n version in nuxt i18n module docs
https://github.com/nuxt-modules/i18n/pull/2257

Thanks!
