### ISSUE TITLE
[edge] navigating from a default local route to non-default route (and vice versa) doesn't work 

### ISSUE THREAD

**Issue by saifobeidat** [nuxt-modules/i18n#2254]
### Environment

OS: Windows 10
Node: 16.16.0
nuxt: "^3.6.2"
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"

### Reproduction

https://stackblitz.com/edit/github-d2hhcf-sztftm?file=app.vue

https://githubd2hhcfsztftm-b3pn--3000--bec01ace.local-credentialless.webcontainer.io/about

### Describe the bug

Hello again.. thanks for your quick fix for the [previous issue](https://github.com/nuxt-modules/i18n/issues/2247) . I found another case on the edge related to the same area, hope its a minor one:

check the following cases, knowing the my default locale is `ar` and I am using `prefix_except_default`

❌  going from `/ar/about`  to `/ar/example`  this will go to: `/about`
❌  going from `/en/example`  to `/ar/about` this will go to: `/example`
❌  going from `/en/example`  to `/` this will go to: `/example`
❌  going from `/ar/example`  to `/about` this will go to: `/example`

✔️   going from `/en/example`  to `/en/about`  this will  go to: `/en/about`  
✔️   going from `/en/example`  to `/en/`  this will  go to: `/en/`  
✔️   going from `/about`  to `/ar/example`  this will  go to: `/ar/example`  
✔️   going from `/about`  to `/example`  this will  go to: `/example`

**Comment by kazupon** [comment]
Thank you for your reporting!

I've just checked your code.
The latest version of the nuxt i18n  edge version isn't installed in your reproduction.

Coud you try specifying this version?

```
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@8.0.0-beta.13-28164155.a503e8b",
```

**Comment by saifobeidat** [comment]
@kazupon works as expected with `npm:@nuxtjs/i18n-edge@8.0.0-beta.13-28164155.a503e8b` version..

thank you 🔥
