### ISSUE TITLE
not able to detect the browser language

### ISSUE THREAD

**Issue by pmnzt** [nuxt-modules/i18n#2255]
### Environment

nuxt 3.6.5
i18n beta.13 

### Reproduction

https://github.com/pmnzt/nuxt-i18n-repo

### Describe the bug

1 - when I change my browser's preferred language, the locale in my app doesn't switch.
2 - 
```js
detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root',  // recommended
    }
   ```
   

it does write the correct cookie based on the language, but it does  not redirect when the site is reload again

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I coud not access your reproduction github repo, so I've faced 404 ...
Could you give us your github repo please?

**Comment by pmnzt** [comment]
@kazupon 
> Thank you for your reporting!
> 
> Unfortunately, I coud not access your reproduction github repo, so I've faced 404 ... Could you give us your github repo please?

sorry for that. Now the repo is public: https://github.com/pmnzt/nuxt-i18n-repo
