### ISSUE TITLE
i18n Configuration in External File Removes All Locales in Nuxt.js

### ISSUE THREAD

**Issue by DidoMarchet** [nuxt-modules/i18n#2258]
### Environment

"@nuxtjs/i18n": "^8.0.0-beta.13",
"nuxt": "^3.6.5",

### Reproduction

Hello,

If I use the following configuration, everything works as expected:

```js
export default defineNuxtConfig({
  i18n: {
    vueI18n: './i18n.config',
    baseUrl: process.env.BASE_URL || '',
    defaultLocale: 'it',
    locales: [
      { code: 'it', site: 'it', iso: 'it-IT', name: 'Global Italiano' },
      { code: 'en', site: 'en', iso: 'en-UK', name: 'Global English' },
      { code: 'en-us', site: 'en', iso: 'en-US', name: 'North America English' },
    ],
    customRoutes: 'config',
    pages: {
      collezioni: {
        it: '/collezioni',
        en: '/collections',
        'en-us': '/collections',
      },
      sistemi: {
        it: '/sistemi',
        en: '/systems',
        'en-us': '/systems',
      },
    },
  },
});
```

However, when I attempt to move the i18n configuration to an external file (named `i18n.ts`) and import it, all locales disappear. The external file looks like this:

```js
export default {
  i18n: {
    vueI18n: './i18n.config',
    baseUrl: process.env.BASE_URL || '',
    defaultLocale: 'it',
    locales: [
      { code: 'it', site: 'it', iso: 'it-IT', name: 'Global Italiano' },
      { code: 'en', site: 'en', iso: 'en-UK', name: 'Global English' },
      { code: 'en-us', site: 'en', iso: 'en-US', name: 'North America English' },
    ],
    customRoutes: 'config',
    pages: {
      collezioni: {
        it: '/collezioni',
        en: '/collections',
        'en-us': '/collections',
      },
      sistemi: {
        it: '/sistemi',
        en: '/systems',
        'en-us': '/systems',
      },
    },
  },
};
```

The new `nuxt.config` file is:

```js
import i18n from './i18n';
export default defineNuxtConfig({
  ...i18n,
});
```

### Describe the bug

After moving the i18n configuration to an external file, all locales from the main configuration file disappear, and I only keep the configuration inside the `i18n.config`.

Does anyone have any suggestions on how to solve this?

Thank you.

**Comment by kazupon** [comment]
Thank you for your reporting!

But, We need your minimul reproduction, because we can reproduce your issue.
nuxt i18n has issue guideline.

> Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

Could you give us it with stackbliz or github repo please? 🙏

**Comment by BobbieGoede** [comment]
@DidoMarchet 
Have you tried one of the following approaches?
```ts
import i18n from './i18n';
export default defineNuxtConfig({
  i18n,
});
```

```ts
import i18n from './i18n';
export default defineNuxtConfig({
  i18n: { ...i18n },
});
```

It looks like you're spreading the `i18n` object, so the following is probably happening:

```ts
import i18n from './i18n';
export default defineNuxtConfig({
  ...i18n,
});

// results in the i18n config not being set to i18n key

export default defineNuxtConfig({
  vueI18n: './i18n.config',
  baseUrl: process.env.BASE_URL || '',
  defaultLocale: 'it',
  locales: [
    { code: 'it', site: 'it', iso: 'it-IT', name: 'Global Italiano' },
    { code: 'en', site: 'en', iso: 'en-UK', name: 'Global English' },
    { code: 'en-us', site: 'en', iso: 'en-US', name: 'North America English' },
  ],
  customRoutes: 'config',
  pages: {
    collezioni: {
      it: '/collezioni',
      en: '/collections',
      'en-us': '/collections',
    },
    sistemi: {
      it: '/sistemi',
      en: '/systems',
      'en-us': '/systems',
    },
  },
});
```

Edit:
Actually it should work according to your provided example, are you sure it matches your local setup?

**Comment by DidoMarchet** [comment]
Hi @BobbieGoede, thank you for your reply!

I have made a simple example here: https://stackblitz.com/edit/nuxt-starter-ikwgbh?file=configuration%2Fi18n.ts
You can see how I import i18n options into nuxt3 config.

With "my way", i18n configuration does not work well. 
I think it's something related to thehow I import './i18n.config'. But I can't figure out. 

I usually like to import all nuxt3 configurations from separate files. It is easier for me to read.

thanks and kind regards,

Davide

**Comment by BobbieGoede** [comment]
@DidoMarchet 
Thanks for adding the reproduction! I changed the way the `i18n` config is spread in your example here: https://stackblitz.com/edit/nuxt-starter-jwi2d8?file=nuxt.config.ts and it seems to work, I think the config import can be moved as well.

**Comment by DidoMarchet** [comment]
Hi! Thanks!
It works! 
I didn't realize I had to destructure the i18n object.

In my configuration there's a typescript error but it's minor.
```
Type '{ baseUrl: string; defaultLocale: string; locales: { code: string; iso: string; name: string; }[]; customRoutes: string; pages: { about: { it: string; en: string; }; 'blog/[slug]': { it: string; en: string; }; }; vueI18n: string; }' is not assignable to type 'NuxtI18nOptions<unknown>'.
  Type '{ baseUrl: string; defaultLocale: string; locales: { code: string; iso: string; name: string; }[]; customRoutes: string; pages: { about: { it: string; en: string; }; 'blog/[slug]': { it: string; en: string; }; }; vueI18n: string; }' is not assignable to type '{ vueI18n?: string | undefined; experimental?: ExperimentalFeatures | undefined; compilation?: LocaleMessageCompilationOptions | undefined; ... 14 more ...; dynamicRouteParams?: boolean | undefined; }'.
    Types of property 'customRoutes' are incompatible.
      Type 'string' is not assignable to type '"config" | "page" | undefined'.ts(2322)
module.d.ts(102, 9): The expected type comes from property 'i18n' which is declared here on type 'InputConfig<NuxtConfig, ConfigLayerMeta>
```

Thanks and kind regards!
Davide
