### ISSUE TITLE
i18n.setLocale() in plugins has error

### ISSUE THREAD

**Issue by vietanhbui** [nuxt-modules/i18n#2261]
This is my code in plugins/lang.js:
`export default defineNuxtPlugin(nuxtApp => {
    // language
    const i18n = nuxtApp.$i18n
    const { availableLocales } = i18n
    const lang = localStorage.getItem('lang') || i18n.defaultLocale
    if (lang && availableLocales.includes(lang)) {
        i18n.setLocale(lang)
    }
    else {
        i18n.setLocale(i18n.defaultLocale)
    }
    localStorage.setItem('lang', i18n.locale.value)
});`
 And this is error
![image](https://github.com/nuxt-modules/i18n/assets/43196820/80c6fe21-0197-4851-bb6f-081428f02989)

**Comment by kazupon** [comment]
Thank you for your reporting!

But, We need your minimul reproduction, because we can reproduce your issue.
Could you give us it with stackbliz or github repo please? 🙏

**Comment by kazupon** [comment]
close in-activity
if you have still issue, please you would open new issue with minimal reproduction !
Thanks!

**Comment by YarikSWT** [comment]
I think nuxtApp doesn't have $i18n, it is a bug. I will include reproduction
