### ISSUE TITLE
Error loading module when Nuxt app is part of a pnpm monorepo

### ISSUE THREAD

**Issue by marr** [nuxt-modules/i18n#2270]
### Environment

* in repo root*
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     0.0.0
- Nitro Version:    -
- Package Manager:  pnpm@8.6.10
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

* in app directory *
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    -
- Package Manager:  pnpm@8.6.10
- Builder:          vite
- User Config:      modules, devtools
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13-28175294.3a94c60
- Build Modules:    -

### Reproduction

Clone https://github.com/marr/pnpm-monorepo and `pnpm install` -- you will see the error:

> ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'

I have created a clean pnpm monorepo, and a fresh install of nuxt 3.6.5. The above error happens during the nuxt prepare phase. The previous issues mention this is a nuxt issue, but I'm not sure how to fix it. I'm new to pnpm, so maybe someone can point me in the right direction. I do have `shamefully-hoist=true` in my _.npmrc_, but it doesn't appear to do anything.

If I run `pnpm install --shamefully-hoist` there is no error, and the vue-i18n package shows up under the root node_modules. However, when I run `pnpm ls -r vue-i18n`, the results are empty.

Also, in my existing project (not this barebones repo), I can't get the `prepare` script to run. I've tried shamefully-hoist on the cli, and still receive the error above.

### Describe the bug

The vue-i18n module appears to be missing to the nuxt i18n module, when part of a pnpm monorepo.

### Additional context

If I enable DEBUG=* output when building, I see some extra info below.

### Logs

```shell
@nuxtjs/i18n:alias vue-i18n resolving from ... [                                                                                               11:48:57 AM
  '/Users/david.marr/code/cxl-ui-monorepo/node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.13-28175294.3a94c60_vue-router@4.2.4_vue@3.3.4/node_modules/@nuxtjs/i18n-edge/node_modules/vue-i18n/dist/vue-i18n.mjs',
  '/Users/david.marr/code/cxl-ui-monorepo/apps/daas/node_modules/vue-i18n/dist/vue-i18n.mjs',
  '/Users/david.marr/code/cxl-ui-monorepo/node_modules/vue-i18n/dist/vue-i18n.mjs'
] +0ms

 ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'                                                                   11:48:57 AM

  at tryResolve (/Users/david.marr/code/cxl-ui-monorepo/node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.13-28175294.3a94c60_vue-router@4.2.4_vue@3.3.4/node_modules/@nuxtjs/i18n-edge/dist/module.mjs:213:9)
  at async setupAlias (/Users/david.marr/code/cxl-ui-monorepo/node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.13-28175294.3a94c60_vue-router@4.2.4_vue@3.3.4/node_modules/@nuxtjs/i18n-edge/dist/module.mjs:432:38)
  at async setup (/Users/david.marr/code/cxl-ui-monorepo/node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.13-28175294.3a94c60_vue-router@4.2.4_vue@3.3.4/node_modules/@nuxtjs/i18n-edge/dist/module.mjs:1444:5)
```

**Comment by marr** [comment]
I'm still digging into this, and it looks like the `setupAlias` function is where things fail. One of my dependencies pulls in vue-i18n@9.2.2 which is possibly conflicting with the version that the i18n module expects.

None of the paths in the `targets` array exist here:
<img width="1008" alt="Screenshot 2023-07-29 at 8 41 50 AM" src="https://github.com/nuxt-modules/i18n/assets/44376/23c0e6ac-07a0-431a-acf3-8d56da7fbec7">

The values:
<img width="1166" alt="Screenshot 2023-07-29 at 8 42 42 AM" src="https://github.com/nuxt-modules/i18n/assets/44376/223b0ff3-4061-41fc-b9f2-995cbdea215d">

The closest thing to existing is the:
```
// workspace directories
resolve(workspaceDir, "node_modules", modulePath)
```
However, when I look at the _node_modules/vue-i18n/_ relative to the root repo, the version is 9.2.2. So the files in dist don't match what the module is looking for.

**Comment by marr** [comment]
for now I just installed `vue-i18n@next` at the top level of my monorepo. Not ideal, but works around the issue.

**Comment by kazupon** [comment]
Thank you for your reporting!

I've checked your reproduction.
In the monorepo case, you need to put the .npmrc with `shamefully-hoist=true` configured in root, not in the target package. I have confirmed that it works on your repro.

Thanks!

**Comment by marr** [comment]
@kazupon you can see the issue if you pull down the latest code. I simply added another vue app (via vite) into the _apps/others_ directory, and I tried to install `vue-i18n`. 

`shamefully-hoist` is still set at the top level, but you can see the error in the _apps/nuxt3-app_ directory, due to the root node_modules storing the 9.2.2 version of vue-i18n. The `prepare` fails, becuase of the reasons I mentioned above.

So, I believe there is still an issue with the nuxt module not supporting the common case of a monorepo.

To reproduce, pull down the repo again. Then:

```
cd apps/other-app
pnpm i vue-i18n -w
```

The error appears from the sibling nuxt project:
> ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'

This is because after the pnpm install, version 9.2.2 is put into the <root>/node_modules directory. The _postinstall_ hook runs in the nuxt app, and the module fails to find version 9.3.0-beta, which it is hardcoded to use.
