### ISSUE TITLE
[8.0.0-rc.2]: `setLocale()` changes the locale but without navigating to the new locale

### ISSUE THREAD

**Issue by saifobeidat** [nuxt-modules/i18n#2288]
### Environment

OS: Windows 10
Node: 16.16.0
nuxt: "^3.6.2"
"@nuxtjs/i18n": "^8.0.0-rc.2"

### Reproduction

https://stackblitz.com/edit/github-d2hhcf-uxzyel?file=app.vue,package-lock.json
https://githubd2hhcfuxzyel-5l5e--3000--a9bdb71e.local-credentialless.webcontainer.io/ar/about

as you see here, the route path doesn't change when i change the local.. whereas the locale gets changed
![route_doesnt_change](https://github.com/nuxt-modules/i18n/assets/24841143/a6de58c1-6571-4d7b-83ab-a47880cbcc85)

### Describe the bug

Hello..

Unlike version 7.. the `setLocale` was automatically navigating the current route's local to the new one when you using `setLocale()` 

in v8-rc2... seems this isn't working..

also i made sure from the docs that this is the expected behavior:
https://v8.i18n.nuxtjs.org/api/vue-i18n#setlocale
> If prefixes are enabled (strategy other than no_prefix), will navigate to new locale's route.

**Comment by Friis1978** [comment]
Same here

**Comment by kazupon** [comment]
Thank you for your reporting!
I backed from short vacation.

I'll try to fix this issue.

**Comment by saifobeidat** [comment]
@kazupon thank you, take your time 🙌
