### ISSUE TITLE
[SSG] When switching languages, the URL does not change correspondingly to the prefix.

### ISSUE THREAD

**Issue by yunyuyuan** [nuxt-modules/i18n#2291]
### Environment

```
Nuxt project info:                                                                                                18:03:03

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `telemetry`, `ssr`, `app`, `css`, `runtimeConfig`, `nitro`, `modules`, `i18n`, `experimental`, `vite`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       18:03:03

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com
```

### Reproduction

no need, see below

### Describe the bug

I have found this: https://github.com/nuxt-modules/i18n/blob/7c8dc6ec3e2a0d4af1834f80ebe49f0df5eed7eb/src/runtime/utils.ts#L355-L365

In SSG mode, the URL does not change when switching languages. However, if a user simply reloads the webpage, the language will revert to the previous one.

So, I'm thinking that by using [replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) instead of `location.assign`, we might be able to solve it elegantly(without breaking history).

**Comment by kazupon** [comment]
Thank you for your reporting!
I backed from short vacation!

I think we might be able to fix the issue by fixing the areas you pointed out. 
But, we should confirm at the facts with minimal reproduction, and then we will bug fix it.
Can you gjve us with your minimal reproduction?

I believe your reproduction will also be useful as a nuxt i18n regression :)

**Comment by kazupon** [comment]
I've faced in this PR.
https://github.com/nuxt-modules/i18n/pull/2307
So, I'll fix this issue.
