### ISSUE TITLE
Option to clear or disable cache when using lazy:true

### ISSUE THREAD

**Issue by martinsjek** [nuxt-modules/i18n#2293]
### Describe the feature

It would be great if there could be an option to disable cache when using lazy:true.

I have a problem where i use mergeLocaleMessage() in my code on some route changes.
Why because, I like to fetch translations based on route.
In my scenario, i have A LOT of pages with A LOT of translations for each page and it would be expensive to load them all on initial page load.
So now I am fetching translations on route change and then using mergeLocaleMessage() to add them.
But the cache breaks everything if the initial route is different. It loads only translations on client-side.

Little basic reproduction: https://stackblitz.com/edit/nuxt-starter-nus1pf?file=app.vue

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by RobertsG** [comment]
I could use this feature as well.

**Comment by martinsjek** [comment]
Any updates on this?

**Comment by tomsdob** [comment]
This would be useful for me too.
