### ISSUE TITLE
differentDomains (true) conflict with Nuxt routeRules (ssr: false)

### ISSUE THREAD

**Issue by tungquach** [nuxt-modules/i18n#2295]
### Environment

Nuxi 3.1.2                                                                                                 

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.3.3`
- Package Manager:  `pnpm@8.1.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `routeRules`, `app`, `css`, `plugins`, `build`, `modules`, `components`, `postcss`, `content`
- Runtime Modules:  `@nuxtjs/supabase@0.3.1`, `@nuxt/content@2.6.0`, `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.6.0`, `@nuxtjs/i18n@8.0.0-rc.1`
- Build Modules:    `-`
------------------------------

### Reproduction

Add config `routeRules` to `nuxt.config.ts`:

```
routeRules: {
    '/auth/**': { ssr: false },
},
```

Config i18n module to have differentDomains = true in `nuxt.config.ts`:

```
modules: [
    [
      '@nuxtjs/i18n',
      {
        strategy: 'no_prefix',
        defaultLocale: 'en',
        fallbackLocale: 'en',
        langDir: './locales',
        differentDomains: true,
        locales: [
          { code: 'en', iso: 'en-US', file: 'en.yml', domain: 'http://localhost:8800' },
          { code: 'vi', iso: 'vi-VN', file: 'vi.yml', domain: 'http://localhost:8801' },
        ],
      }
    ]
],
```

Then go to any page that match `routeRules` like `/auth/login` to see it keep infinite refresh loop

### Describe the bug

Browser refresh loop when going to route match `routeRules` (no SSR) with config differentDomains = true

**Comment by kazupon** [comment]
Thank you for your reporting!
I've backed from shot vacation.

Unfortunately, We could not your issue.
Could you give your minimal reproduction us with stackbliz (nuxt starter) or github repo please? 🙏

**Comment by tungquach** [comment]
> Thank you for your reporting! I've backed from shot vacation.
> 
> Unfortunately, We could not your issue. Could you give your minimal reproduction us with stackbliz (nuxt starter) or github repo please? 🙏

Here is it: https://stackblitz.com/edit/github-fjfcqz
Go to "infinite loop refresh page" in the demo to see the problem

**Comment by kazupon** [comment]
Thank you for your reproduction!

I've faced the warning output in my env
```
 WARN  [@nuxtjs/i18n]: The differentDomains option and no_prefix strategy are not compatible. Change strategy or disable differentDomains option.
```

`no_prefix` strategy isn't supported with `differentDomains: treu`
you need to change other strategy.

**Comment by tungquach** [comment]
> Thank you for your reproduction!
> 
> I've faced the warning output in my env
> 
> ```
>  WARN  [@nuxtjs/i18n]: The differentDomains option and no_prefix strategy are not compatible. Change strategy or disable differentDomains option.
> ```
> 
> `no_prefix` strategy isn't supported with `differentDomains: treu` you need to change other strategy.

Thank you for clear that to me

**Comment by karam12** [comment]
Hello @kazupon,
We have the same issue, event if we use another strategy than 'no_prefix'.
Here is a link to the stackblitz to reproduce : 
https://stackblitz.com/edit/nuxt-starter-iceuqr?file=nuxt.config.ts
