### ISSUE TITLE
Routes not auto generated

### ISSUE THREAD

**Issue by bekdauletarynbek** [nuxt-modules/i18n#2298]
### Environment

Nuxt 3.6.5
Nuxt-i18n 8.0.0.rc-2 or 8.0.0.beta-13

### Reproduction

Created routes and migrated to 3.6.5 from 3.0.0

### Describe the bug

So we are migrated from 3.0.0.rc-10 and i started works with adding nuxt-i18n. Nuxt-i18n auto installed nuxt 3.6.2 and everything is worked. But when i pulled new branch with migrated Nuxt 3.6.5, all my configs stop working. I checked routes, checked how it is included, adding module before @nuxtjs/i18n and all of this is not working
For example: 
 Routes not auto generated, and when i use starategy: 'prefix', and go to localhost, prefix not added. I check in Vue Devtools route component and name of component is same of route, and prefix not added
@kazupon you can check of this bug, or this is only in my project ?)

**Comment by BobbieGoede** [comment]
Thank you for reporting your issue! 

Unfortunately your description is not sufficient for us to figure out what is causing your issue, could you please provide a minimal reproduction project for us to debug locally?

**Comment by bekdauletarynbek** [comment]
<img width="264" alt="image" src="https://github.com/nuxt-modules/i18n/assets/52837531/3e860836-3a49-4c52-ad6d-0e66f1b5b73f">

switchToLocaePath not working

<img width="304" alt="image" src="https://github.com/nuxt-modules/i18n/assets/52837531/f03d1168-822e-49a4-9566-bb918468aea6">

prefix not added

@BobbieGoede show my source code ?)

**Comment by bekdauletarynbek** [comment]
@BobbieGoede where i can see auto generated routes in .nuxt directory? And how auto generate is works, because routing is works, but nuxt-i18n can't resolve of the files for auto generate

**Comment by BobbieGoede** [comment]
>@BobbieGoede show my source code ?)

A minimal reproduction is a project that reproduces your issue, this could be your source code (which is understandably not ideal), or more preferably a new small project with a similar configuration that recreates the same issue you are experiencing. You could for example use the [nuxt starter](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz) for this.

>@BobbieGoede where i can see auto generated routes in .nuxt directory? And how auto generate is works, because routing is works, but nuxt-i18n can't resolve of the files for auto generate

As you mentioned, usually you can see which routes have been generated in Vue Devtools in the Routes tab, or enable [Nuxt DevTools](https://nuxt.com/docs/api/configuration/nuxt-config#devtools) and see all routes in the Pages window.

**Comment by bekdauletarynbek** [comment]
all functionality is works perfect but strategy not working, and i think i cannot do all things in new project 🥲

**Comment by bekdauletarynbek** [comment]
<img width="358" alt="image" src="https://github.com/nuxt-modules/i18n/assets/52837531/b128a019-f924-4c07-99fc-a62b7190fec7">

<img width="548" alt="image" src="https://github.com/nuxt-modules/i18n/assets/52837531/cc36220d-d2da-41e6-a748-68474e011a9f">

**Comment by kazupon** [comment]
I've backed from short vacation.

as mention @BobbieGoede, We need minimal reproduction because we cannot reproduce your issue in out enviroment.

nuxt i18n module issue guidline says:

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

https://github.com/nuxt-modules/i18n/issues/new?assignees=&labels=pending+triage&projects=&template=bug-report.yml

Could you give your minimal reproduction to us please?

**Comment by bekdauletarynbek** [comment]
sorry, next week i will be continue investigate, why is autogenerate is not working
i think it is my local problem with packages, because my old realization is working, before we are ending migration to nuxt 3.6.5

**Comment by bekdauletarynbek** [comment]
i think it is because of layouts, when i integrated layouts works in extended pages level, now it is works by layouts direcory, and routes works in extended pages

**Comment by bekdauletarynbek** [comment]
all problem it is redirect in main path, we deleted redirect in main, and all routing is worked
