### ISSUE TITLE
Add option for fallback translation

### ISSUE THREAD

**Issue by martinsjek** [nuxt-modules/i18n#2309]
### Describe the feature

It would be great to declare fallback translation in $t() function - $t(key: string, fallbackText: string).

Let's say i want $t('home.title'), but I have this translation from API with lazy:true.
Then if we have $t('home.title', 'Homepage title'), the user sees "Homepage title" in case translation isn't loaded or is empty.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by martinsjek** [comment]
Any updates on this?

**Comment by RobertsG** [comment]
Also waiting on this, a fallback string would be greatly appreciated on my end.

**Comment by tomsdob** [comment]
This feature would also be useful for me.

**Comment by BobbieGoede** [comment]
This feature would probably need to be implemented in `vue-i18n` so I have opened a feature proposal there.

**Comment by martinsjek** [comment]
I see that the fallback/default message already exists in vue-i18n: https://vue-i18n.intlify.dev/api/injection.html#t-key-defaultmsg
I am closing this issue.
