### ISSUE TITLE
prefix_except_default doesn't work for `yarn generate`

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/i18n#2316]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.19.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      srcDir, devtools, ssr, modules, i18n, piniaPersistedstate, googleFonts, colorMode, postcss, build, vite
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.2, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/google-fonts@3.0.2, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @vueuse/nuxt@10.3.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/mrleblanc101/neobigben

### Describe the bug

I recentry upgraded from 8.0.0-beta.9 to 8.0.0-rc.2.
Since then, the language prefix doesn't appear in the URL in production build using Static Generation (`yarn generate && yarn preview`).

Here is `yarn dev`:
![2023-08-14 12 16 23](https://github.com/nuxt-modules/i18n/assets/17392251/8c7c3a44-19db-416d-8086-6706d4f3dbd6)

Here is `yarn generate && yarn preview`:
![2023-08-14 12 24 12](https://github.com/nuxt-modules/i18n/assets/17392251/9944ab02-8951-4254-b7af-75472700e229)

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

Your issue was already fixed by nuxt i18n edge channel version

```json
        "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@8.0.0-rc.2-28198958.0f3f8e4",
```

Please check it!
Thanks!

**Comment by mrleblanc101** [comment]
@kazupon oh nice, thanks.
I guess I should try the edge version before raising an issue next time.
