### ISSUE TITLE
Nuxt i18n + differentDomains + Apache Proxy with https

### ISSUE THREAD

**Issue by bcadu** [nuxt-modules/i18n#2329]
### Environment

- Operating System: Linux
- Node Version:     v16.18.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      devtools, modules, i18n, vite
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3
- Build Modules:    -

### Reproduction

Here the code: https://stackblitz.com/edit/github-kudpru
To reproduce you have to :
- copy the code on your local installation
- add this Apache config:
```
<VirtualHost *:443>
    ServerName fr.localhost
    ServerAlias en.localhost

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/localhost.crt
    SSLCertificateKeyFile /etc/ssl/certs/localhost.key

    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```
- generate the certs with this command
```
openssl req -new -newkey rsa:2048 -nodes -keyout localhost.key -out localhost.csr
```

### Describe the bug

When I go on https://fr.localhost/  or https://en.localhost/, in the console of my browser I have issue with https / wss protocol.
See the log below

I've tried with or without this config:
```
  vite: {
    server: {
      hmr: {
        protocol: "wss",
      },
    },
  },

```

I can't see to solve this ?

### Logs
[vite] connecting...
client.ts:77 WebSocket connection to 'wss://fr.localhost:24678/_nuxt/' failed: 
setupWebSocket @ client.ts:77
(anonyme) @ client.ts:67
client.ts:102 [vite] server connection lost. polling for restart...
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_SSL_PROTOCOL_ERROR
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:335
(anonyme) @ client.ts:103
chunk-BVQHDTV7.js:2710 <Suspense> is an experimental feature and its API will likely change.
DevTools failed to load source map: Could not load content for chrome-client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_SSL_PROTOCOL_ERROR
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_SSL_PROTOCOL_ERROR
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_SSL_PROTOCOL_ERROR
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_SSL_PROTOCOL_ERROR
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_SSL_PROTOCOL_ERROR
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
VM403 vitals.js:234 [Web Vitals Extension] CLS 0.00 (good)
VM403 vitals.js:234 [Web Vitals Extension] CLS 0.00 (good)
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103
client.ts:322     GET https://fr.localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED
ping @ client.ts:322
waitForSuccessfulPing @ client.ts:343
await in waitForSuccessfulPing (asynchrone)
(anonyme) @ client.ts:103

**Comment by kazupon** [comment]
Thank you for your reporting!

I think this issue isn’t nuxt i18n issue, but a configuration issue with Apatch and vite.
Please ask Apache and vite.

Thank you.

**Comment by bcadu** [comment]
Hi @kazupon 
Ok thanks for your answer. We'll have a look to vite. This issue only occurs in dev mode. It's not the case when it's built.
We have a lot difficulties with this i18n module and differentDomains. ( It's ok with Nuxt2)
We've another issue with differentDomains=true, I'm going to open a new ticket.
