### ISSUE TITLE
[RC3] Cannot resolve @intlify/message-compiler on pnpm

### ISSUE THREAD

**Issue by darthf1** [nuxt-modules/i18n#2331]
### Environment

Nuxt project info:                                                                              9:22:24 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.5.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      app, css, plugins, components, modules, googleFonts, i18n, ignore, imports, router, ssr, sourcemap, telemetry, nitro, runtimeConfig, vite
- Runtime Modules:  @formkit/nuxt@0.18.1, @nuxt/devtools@0.8.0, @nuxt/image@1.0.0-rc.1, @nuxtjs/google-fonts@3.0.2, @nuxtjs/i18n@8.0.0-rc.2, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @bootstrap-vue-next/nuxt@0.1.3, nuxt-tsconfig-relative-paths@1.0.6
- Build Modules:    -
------------------------------

### Describe the bug

When I upgrade from RC2 to RC3, I get the error: 
```
 ERROR  Cannot resolve @intlify/message-compiler on pnpm! please install it on 'node_modules'
```

### Additional context

```npmrc
audit=false
engine-strict=false
loglevel=error
fund=false
node-linker=hoisted
progress=false
shamefully-hoist=true
strict-peer-dependencies=true
update-notifier=false
```

### Logs

```
Nuxi 3.6.5
 ERROR  Cannot resolve @intlify/message-compiler on pnpm! please install it on 'node_modules'
  at tryResolve (node_modules/@nuxtjs/i18n/dist/module.mjs:217:9)
  at async setupAlias (node_modules/@nuxtjs/i18n/dist/module.mjs:453:53)
  at async setup (node_modules/@nuxtjs/i18n/dist/module.mjs:1439:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2409:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3238:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3314:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately we could not reproduce your issue
we need a minimum reproduction to ensure that we reproduce your issue.

Issue guideline saying:

> Please use a template below to create a minimal reproduction, and provide to us your issue cases
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

Could you give us it please? 🙏

**Comment by joan-domingo** [comment]
Hi, we have the same issue. I have here a minimal reproduction https://stackblitz.com/edit/github-7endol?file=package.json
It started with the beta-13.

Let me know if you need more help

**Comment by DamianGlowala** [comment]
Adding other library as well with the same error message:

![image](https://github.com/nuxt-modules/i18n/assets/48835293/71de86c1-5592-44fb-80ed-51c340d14897)

Deleted node_modules and lockfile, now getting:

![image](https://github.com/nuxt-modules/i18n/assets/48835293/bda7e9fb-a473-42a7-a85d-f00e2736db2c)

**Comment by kazupon** [comment]
@joan-domingo 
>Hi, we have the same issue. I have here a minimal reproduction https://stackblitz.com/edit/github-7endol?file=package.json
It started with the beta-13.
Let me know if you need more help

I think your issue is related to #2098

**Comment by joan-domingo** [comment]
> @joan-domingo
> 
> > Hi, we have the same issue. I have here a minimal reproduction https://stackblitz.com/edit/github-7endol?file=package.json
> > It started with the beta-13.
> > Let me know if you need more help
> 
> I think your issue is related to #2098

Might be but I can't seem to find a way to make it work by overriding the other intlify libraries version. If anyone has some hints let me know. Thanks!

**Comment by darthf1** [comment]
> Thank you for your reporting!
> 
> Unfortunately we could not reproduce your issue we need a minimum reproduction to ensure that we reproduce your issue.
> 
> Issue guideline saying:
> 
> > Please use a template below to create a minimal reproduction, and provide to us your issue cases
> > 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
> 
> Could you give us it please? 🙏

Hi @kazupon, I'm trying to create a reproduction like you asked.

So far, I've found that when I remove `"@intlify/eslint-plugin-vue-i18n": "2.0.0",` from my `package.json`, the error is gone.

Edit:

When I use `"@intlify/eslint-plugin-vue-i18n": "3.0.0-next.3",` the error is gone.

**Comment by BobbieGoede** [comment]
> When I use "@intlify/eslint-plugin-vue-i18n": "3.0.0-next.3", the error is gone.

> Hi, we have the same issue. I have here a minimal reproduction https://stackblitz.com/edit/github-7endol?file=package.json

Looks like installing the latest versions [resolves this issue](https://stackblitz.com/edit/github-7endol-4ynzyx?file=package.json).
