### ISSUE TITLE
rootRedirect not working > blank page and no redirect from / to /en

### ISSUE THREAD

**Issue by yoshschoemaker** [nuxt-modules/i18n#2333]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    -
- Package Manager:  npm
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

"@nuxtjs/i18n": "^8.0.0-rc.3"

nuxt.config.ts  
`  i18n: {
    // Module options
    locales: [
      {
        code: "en",
        iso: "en",
        name: "English",
        file: "en.json",
      },
      {
        code: "nl",
        iso: "nl",
        name: "Dutch",
        file: "nl.json",
      },
    ],
    baseUrl: process.env.BASE_URL || "http://localhost:3000",
    defaultLocale: "nl",
    rootRedirect: "/nl",
    lazy: true,
    strategy: "prefix",
    langDir: "locales",
  },`

### Reproduction

1. Use rootRedirect in nuxt.config.ts i18n options (for exampele rootRedirect: "/en".
2. Navigate to your nuxt application in the browser without /en behind the URL (localhost:3000 for example).
3. Watch and see that you're NOT redirected to /en.

### Describe the bug

I got a problem with Nuxt3 + i18n (@nuxt/i18n).

Everything works fine when navigating to the homepage like this: http://localhost:3000/en or http://localhost:3000/nl

But when navigating to http://localhost:3000/ the application does absolutely nothing.

When inspecting via the browser, the <div id="app"></div> is empty.

I expect when I add `rootRedirect: "/en" that the app will redirect from / to /en. But it doesn't do that.

I've searched around all possible fixes on Stackoverflow and this issues section, but nothing seems to work for me.

Anybody got some clues?

**Comment by kazupon** [comment]
Thank you for your reporting!

We appreciate your reproduction procedure. However, we need a minimum reproduction to ensure that we reproduce your issue.

Issue guideline saying:

> Please use a template below to create a minimal reproduction, and provide to us your issue cases
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

Could you give us it please? 🙏

**Comment by kazupon** [comment]
close in-activty.

If you have still issue, please you would open as new issue.
Thanks!
