### ISSUE TITLE
CallStackSizeExceeded when accessing `$i18n.localeProperties.value` within a component with a local scope applied

### ISSUE THREAD

**Issue by FreekVR** [nuxt-modules/i18n#2338]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      telemetry, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/github/nuxt/starter/csb-ctzmpk/draft/cranky-brown?file=/pages/index.vue:12,1

### Describe the bug

This combination in a page component results in a "Maximum call stack size exceeded"

```
<script setup>
import { useI18n } from "#i18n";

// Remove this block to remove the error...
const { t } = useI18n({
  useScope: "local",
});

// Or don't do this...
console.log(useI18n().localeProperties.value);
</script>
```

**Comment by kazupon** [comment]
Thank you for you reporting!

The root cause of this issue is the same as #2335
