### ISSUE TITLE
[PNPM] WARN  Ignore Vue I18n configuration file does not exist at i18n.config on layer

### ISSUE THREAD

**Issue by LeCoupa** [nuxt-modules/i18n#2343]
### Environment

Nuxi 3.6.5                                                           8:46:32 PM
                                                                     8:46:33 PM
[8:46:33 PM] RootDir: /Users/lecoupa/Documents/TheCompaniesAPI/thecompaniesapi-app
Nuxt project info: (copied to clipboard)                             8:46:33 PM

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.2
- Builder:          vite
- User Config:      build, devServer, experimental, nitro, extends, imports, runtimeConfig, vite, components, css, modules, app, typescript, devtools, i18n, pinia, plausible, pwa
- Runtime Modules:  @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.3, @pinia/nuxt@0.4.11, @unocss/nuxt@0.53.6, @vite-pwa/nuxt@0.1.0, @vueuse/nuxt@10.2.1, @nuxtjs/plausible@0.2.1, floating-vue/nuxt, vue-recaptcha/nuxt
- Build Modules:    -
------------------------------

### Reproduction

Here is my the i18n config object if it can help

```typescript
i18n: {
    defaultLocale: 'en',
    langDir: './locales/',
    lazy: true,
    strategy: 'prefix_except_default',
    vueI18n: './config/i18n.config.ts',

    detectBrowserLanguage: {
      useCookie: true,
      fallbackLocale: 'en',
    },

    locales: [
      {
        code: 'en',
        iso: 'en',
        file: 'en.ts',
      },
      {
        code: 'fr',
        iso: 'fr',
        file: 'fr.ts',
      },
    ],
  },
```

### Describe the bug

I don't know what happens but wherever I put it the `i18n.config.ts` file is never found. I have this strange error (notice the nuxt-seo-kit inside the url).

```
7|tca-app  | [@nuxtjs/i18n]  WARN  Ignore Vue I18n configuration file does not exist at i18n.config on layer /Users/lecoupa/Documents/TheCompaniesAPI/thecompaniesapi-app/node_modules/.pnpm/nuxt-seo-kit@1.3.9_@unhead+vue@1.3.7_rollup@2.79.1_vue@3.3.4/node_modules/nuxt-seo-kit. Skipping...
```

I have no idea where the issue is coming from. Here is my .npmrc as it seems to be related to pnpm?

```yaml
shamefully-hoist=true
strict-peer-dependencies=false
shell-emulator=true
registry=https://registry.npmjs.org
git-checks=false
```

**Comment by kazupon** [comment]
Thank you for your reporting!

Hmm 🤔, It seems that nuxt layers path resolution is not working properly with nuxt i18n. /cc @BobbieGoede 

We need minimal reproduction to debug.
Could you give us it please? 🙏

**Comment by BobbieGoede** [comment]
@LeCoupa 
The warning being logged is a bit eager, any layer that does not provide a Vue I18n configuration file will trigger this warning, I am guessing you are extending your project with `nuxt-seo-kit`. 

Note that this is a warning, if you are not seeing the same warning for your project (as opposed to this warning describing a layer), that probably means your VueI18n configuration file is being loaded as expected. 

You can confirm which configurations are being loaded by running your project with `DEBUG=@nuxtjs/i18n:module` set (eg. `DEBUG=@nuxtjs/i18n:module npm run dev`) and look for the logs starting with `@nuxtjs/i18n:module vueI18nConfigPathInfo` and `@nuxtjs/i18n:module layerVueI18nConfigPaths`.

I'm closing this issue as this does not sound like a bug or unexpected behaviour, I will be looking into making the warning less eager, perhaps checking if a layer provides i18n configuration in the first place before logging this. Please let me know if you have more questions or if you run into any issues!

**Comment by richard-edwards** [comment]
I have multiple layers in my nuxt app and only 2 of the 5 have the config file present so I get this warning a lot. Is there any way to turn off this particular warning?

**Comment by richard-edwards** [comment]
@BobbieGoede Sorry I'm an idiot .. just reread your previous comment which mentioned making it less eager. Early morning :(

**Comment by lautr** [comment]
Is there any Issue tracking this? I'd argue its a bug as its giving a warning about something thats it shouldnt.

Its definetly an Issue from a DX pespective as it makes the build process more noisy and can potentially lead to a developer missing actually warnings / errors.
