### ISSUE TITLE
Auto generate routes is not working if in parent has redirect

### ISSUE THREAD

**Issue by bekdauletarynbek** [nuxt-modules/i18n#2345]
### Environment

nuxt-3.6.5
@nuxtjs/i18n rc-2.0

### Reproduction

create routes by extended routes, and create redirect in parent level, after all the routes in this parent level will not be generated routes by localization

### Describe the bug

this is bug, and i cannot not use redirects in extended-routes, some routes and paths should be has redirect

**Comment by bekdauletarynbek** [comment]
@kazupon

**Comment by kazupon** [comment]
Thank you for your reporting!

We appreciate your reproduction procedure. However, we need a minimum reproduction to ensure that we reproduce your issue.

Issue guideline saying:

> Please use a template below to create a minimal reproduction, and provide to us your issue cases
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

Could you give us it please? 🙏

**Comment by kazupon** [comment]
close in-activity.
if you have still issue, you can open as the new issue with minimal reproduction.

Thanks!
