### ISSUE TITLE
Prerendering fails when defineI18nRoute is set for nested pages

### ISSUE THREAD

**Issue by davidsandoz** [nuxt-modules/i18n#2351]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.7.0`
- CLI Version:      `3.7.2`
- Nitro Version:    `2.6.2`
- Package Manager:  `npm@9.4.2`
- Builder:          `-`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-rc.3`
- Build Modules:    `-`

[Edit: edited to match the Stackblitz environment instead of my project]

### Reproduction

https://stackblitz.com/edit/github-at1ynv?file=pages%2Fmother%2Fdaughter.vue

### Describe the bug

In nested pages with locale-specific paths defined in `defineI18nRoute`, like this:
```typescript
defineI18nRoute({
  paths: {
    fr: '/mere/fille',
  },
});
```

the prerendering fails when doing `npm run generate`

```
ℹ Prerendering 10 initial routes with crawler                                                                          nitro 08:47:08
  ├─ /200.html (97ms)                                                                                                  nitro 08:47:08
  ├─ /404.html (97ms)                                                                                                  nitro 08:47:08
  ├─ /fr/mere (155ms)                                                                                                  nitro 08:47:08
  ├─ /mother (154ms)                                                                                                   nitro 08:47:08
  ├─ /fr (155ms)                                                                                                       nitro 08:47:08
  ├─ / (155ms)                                                                                                         nitro 08:47:08
  ├─ /mother/daughter (154ms)                                                                                          nitro 08:47:08
  ├─ /mother/son (154ms)                                                                                               nitro 08:47:08
  ├─ /fr/_payload.json (8ms)                                                                                           nitro 08:47:08
  ├─ /_payload.json (8ms)                                                                                              nitro 08:47:08
  ├─ /mother/daughter/_payload.json (7ms)                                                                              nitro 08:47:08
  ├─ /mother/son/_payload.json (7ms)                                                                                   nitro 08:47:08
  ├─ /fr/mere/fille (7ms)                                                                                              nitro 08:47:08
  ├─ /fr/mere/fils (7ms)                                                                                               nitro 08:47:08
  ├─ /fr/mere/fr/mere/fille (183ms)                                                                                    nitro 08:47:08
  │ └── Error: [404] Page not found: /fr/mere/fr/mere/fille
  ├─ /fr/mere/fr/mere/fils (183ms)                                                                                     nitro 08:47:08
  │ └── Error: [404] Page not found: /fr/mere/fr/mere/fils
  ├─ /fr/mere/fille/_payload.json (1ms)                                                                                nitro 08:47:08
  ├─ /fr/mere/fils/_payload.json (1ms)                                                                                 nitro 08:47:08
                                                                                                                       nitro 08:47:08
Errors prerendering:
  ├─ /fr/mere/fr/mere/fille (183ms)                                                                                    nitro 08:47:08
  │ └── Error: [404] Page not found: /fr/mere/fr/mere/fille
  ├─ /fr/mere/fr/mere/fils (183ms)                                                                                     nitro 08:47:08
  │ └── Error: [404] Page not found: /fr/mere/fr/mere/fils
                                                                                                                       nitro 08:47:08

 ERROR  Exiting due to prerender errors.   
```

We clearly see the bug, where `/fr/mere` is duplicated while it shouldn't. The children routes `/fr/mere/fille` and `/fr/mere/fils` are properly generated, so the failing route prerenders are additional and should rather not happen at all.

**Comment by visko83** [comment]
What causes the issue, is there any workaround? Two months ago with 8.0.0-beta.13 I did not have the issue, now I face it with beta.13 and 8.0.0-rc.4, too. Same with nuxt versions 3.6.2 and 3.7.1. 
I tried to define the phantom paths in nuxt.config.ts defineNuxtConfig.i18n.paths (map them to '/') but the same errors come.

**Comment by visko83** [comment]
I have just noticed that the error I have is slightly different, I defined all the paths in defineNuxtConfig.i18n.pages (so not in page's defineI18nRoute). What do you think shall I make another bug about it or are these really the same?

**Comment by visko83** [comment]
Workaround, in nuxt.config.ts:
```
export default defineNuxtConfig({
...
    nitro: {
        prerender: {
            ignore: ['/fr/mere/fr/']
        }
    },
})
```

**Comment by carbdias** [comment]
I have a simliar error here but with prettier: 
[vue/compiler-sfc] Unexpected token (13:10)
talking about the single-quote, but I have this option defined as ok in prettier, so I don't know what may be wrong
{
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true
}

**Comment by davidsandoz** [comment]
I noticed the merged PR that mentions this issue (thank you @BobbieGoede!), so I tried again with v8.0.0 and Nuxt 3.9.0.

https://stackblitz.com/edit/github-at1ynv-quqdsy?file=package.json,pages%2Fmother%2Fdaughter.vue

Unfortunately, the issue is still occurring.

**Comment by BobbieGoede** [comment]
@davidsandoz 
Sorry for the confusion 😅, #2625 was only preparation to fix this issue. I did try fixing this last month and made progress but it broke other project configurations, hopefully I have some time this month to pick it up again.
