### ISSUE TITLE
Lazy loading messages broken in production build

### ISSUE THREAD

**Issue by erikuit** [nuxt-modules/i18n#2353]
### Environment

Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      app, sourcemap, vite, components, modules, i18n, runtimeConfig, googleFonts, build, bundle, css
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3, @nuxtjs/google-fonts@3.0.2
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/github-ihvwd9?file=nuxt.config.ts

### Describe the bug

Translation messages are no longer loading in the production build when using `lazy: true` and `langDir` in the configuration. The development build works as expected.

### Additional context

Problem started occuring a few hours ago, could it somehow be related to https://github.com/nuxt-modules/i18n/commit/417af8382551f46537c697ac18c9ac7fe372ed7a ?
Downgrading to @nuxtjs/i18n@8.0.0-rc2 didn't resolve the issue.

**Comment by codeflorist** [comment]
same problem here. i still have a `yarn.lock`, where it is working, but couldn't pinpoint the package at fault. it's definitely not `@nuxtjs/i18n@8.0.0-rc.3`, since i have that in the working lockfile.

**Comment by AwesomeAnders** [comment]
Same problem here. Translations broken only in production build.

**Comment by BobbieGoede** [comment]
@erikuit
I believe I have found part of a workaround to this issue by overriding some dependencies, I changed your reproduction [here](https://stackblitz.com/edit/github-ihvwd9-tcaxzf?file=package.json) to demonstrate.

Try adding the following to your `package.json`:
```json
  "overrides": {
    "@intlify/bundle-utils": "7.0.2",
    "@intlify/message-compiler": "9.3.0-beta.24",
    "@intlify/shared": "9.3.0-beta.24"
  }
```

It looks like this only fixes the translation on the client-side though, so it throws a hydration mismatch error and untranslated text is visible on load for a short moment.

@kazupon 
I'm not sure but maybe this is related to changes in or after https://github.com/intlify/bundle-tools/pull/287? The project does make requests for the locale files and noticed they looked slightly different. Not sure why the overrides make it work on the client-side but not on the server-side.

**Comment by erikuit** [comment]
@BobbieGoede Thanks for the workaround! Can confirm that this also works for my original project.

**Comment by BobbieGoede** [comment]
@erikuit Happy to hear it works!

Something different may be going on altogether, the issue in the reproduction can be solved by simply adding `defaultLocale: 'en'` to the i18n configuration 😅 [reproduction to demonstrate here](https://stackblitz.com/edit/github-ihvwd9-rbujwn?file=package.json,nuxt.config.ts).

**Comment by erikuit** [comment]
@BobbieGoede Interesting! I have `defaultLocale` set in my original project, but there it doesn't work.  Still working out the difference.

**Comment by ChrisGV04** [comment]
Same issue with me. And it only happens on the production build. Here are my settings:

```ts
// nuxt.config.ts
i18n: {
  lazy: true,
  langDir: 'lang',
  defaultLocale: 'en',
  locales: [
    { code: 'en', file: 'en.json' },
    { code: 'es', file: 'es.json' },
  ],
  detectBrowserLanguage: {
    useCookie: true,
    redirectOn: 'root',
    cookieKey: 'i18n_redirected',
  },
},

// i18n.config.ts
export default defineI18nConfig(() => ({ legacy: false, locale: 'en' }));
```

I have my project using the `srcDir: "src"` and the language files are inside `src/lang`. For some reason everything was working just before I ran `pnpx nuxi upgrade --force` as suggested when updating Nuxt.

I tried using the workaround @BobbieGoede suggested but it's still not working.

EDIT: I'm getting this inside the logs but for every single key:
```
[intlify] Not found 'navigation.home' key in 'en' locale messages.
```

**Comment by ChrisGV04** [comment]
For anyone using `pnpm` that need to use the workaround, it must be set inside `pnpm.overrides` as such:

```json
{
  "pnpm": {
    "overrides": {
      "@intlify/bundle-utils": "7.0.2",
      "@intlify/message-compiler": "9.3.0-beta.24",
      "@intlify/shared": "9.3.0-beta.24"
    }
  }
}
```

**Comment by kazupon** [comment]
@BobbieGoede 
>I'm not sure but maybe this is related to changes in or after intlify/bundle-tools#287 feat(bundle-utils): support AST minify option? 

Yeah, 😅 
I have recently changed the nuxt i18n deps `@intlify/bundle-utils`, `@intlify/unplugin-vue-i18n`, and  vue-i18n related packages.
The handling around bundles has changed a little in those.

I have confirmed that the edge channel version works correctly on the reproduction repo.

The workaround is to override it with the override function of the package manager or use the edge channel version.

I will release v8.0.0-rc.4 soon. That should solve this issue.

**Comment by kazupon** [comment]
I've just released nuxt i18n v8.0.0-rc.4
please check it!

**Comment by erikuit** [comment]
Solved the issue on my end. Thank you!

**Comment by nazar1ua** [comment]
For me too! Thanks!
