### ISSUE TITLE
switchLocalePath does not keep query params in URL

### ISSUE THREAD

**Issue by martinsjek** [nuxt-modules/i18n#2354]
### Environment

- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      modules, css, vite, nitro, runtimeConfig, router, app, image, i18n, security, robots, gtag, htmlValidator, telemetry, $test
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3, @nuxt/image@1.0.0-rc.1, @pinia/nuxt@0.4.11, @vueuse/nuxt@10.4.1, @nuxtjs/tailwindcss@6.8.0, nuxt-security@0.14.4, nuxt-vitest@0.10.2, @artmizu/nuxt-prometheus@2.1.5, nuxt-gtag@0.6.2, @nuxtjs/robots@3.0.0, @nuxtjs/html-validator@1.5.2
- Build Modules:    -

### Reproduction

.

### Describe the bug

When using `const switchLocalePath = useSwitchLocalePath();`
As `switchLocalePath('en')`

URL changes, but it does not keep query parameters, example:
URL is `/cart?test=123`
After switchLocalePath it is `/en/cart`
But I need `/en/cart?test=12`

I am using `strategy: 'prefix_except_default',`

**Comment by q1103192605** [comment]
I have the same problem and can't find a solution

**Comment by RobertsG** [comment]
Was using this for my product page with filters, where I need them to stay persistent.
So I'm also interested in this.

**Comment by BobbieGoede** [comment]
Could you provide a minimal reproduction of this issue? I am unable to replicate it, [here is a starter project](https://stackblitz.com/fork/github/BobbieGoede/nuxt-i18n-starter/tree/v8) you can use.

**Comment by tomsdob** [comment]
@BobbieGoede the issue can be replicated with the starter project you provided. Open the app in a new tab and add any query parameter to the URL, for example `?test=123`, open the page with the query params. After that click on any of the links that use `switchLocalePath`, the query parameter is gone.

Example:
Edit `...webcontainer.io/en` to `....webcontainer.io/en?test=123`
When you are in `...webcontainer.io/en?test=123`, click on `Nederlands` `NuxtLink`.
Now the URL is `...webcontainer.io/nl` and the query params are gone. Should be `...webcontainer.io/nl?test=123`.

**Comment by BobbieGoede** [comment]
@tomsdob you're right! I'm not sure what I was looking at that I couldn't replicate it. I think I have found the source of the issue and opened a [PR](https://github.com/intlify/routing/pull/46) to potentially resolve it. It's quite a weird issue..
