### ISSUE TITLE
Missing keys in locale messages after updating to edge channel `RC.4`

### ISSUE THREAD

**Issue by Dananz** [nuxt-modules/i18n#2359]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.7.0`
- CLI Version:      `3.7.3`
- Nitro Version:    `2.6.2`
- Package Manager:  `npm@8.11.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/missing-keys-in-locale-messages?file=nuxt.config.ts

### Describe the bug

After updating from rc.2 to rc.4 it seems like i18n cannot locate the messages anymore.

Attaching a reproduction repo 

### Logs

```shell
@nuxtjs/i18n Could not find messages for locale codehe
[Vue Router warn]: No match found for location with path "/he"
[Vue Router warn]: No match found for location with path "/he/test"
[Vue Router warn]: No match found for location with path "/he"
[Vue Router warn]: No match found for location with path "/he/shlomi/one"
[Vue Router warn]: No match found for location with path "/he/shlomi/two"
[intlify] Not found 'common.close' key in 'he' locale messages.
@nuxtjs/i18n Could not find messages for locale codehe
[Vue Router warn]: No match found for location with path "/he"
[Vue Router warn]: No match found for location with path "/he/test"
[Vue Router warn]: No match found for location with path "/he"
[Vue Router warn]: No match found for location with path "/he/shlomi/one"
[Vue Router warn]: No match found for location with path "/he/shlomi/two"
[intlify] Not found 'common.close' key in 'he' locale messages.
```

**Comment by BobbieGoede** [comment]
A recent change broke inline options for `@nuxtjs/i18n-edge`, https://github.com/nuxt-modules/i18n/pull/2361 will resolve this issue. 

In the meantime you can use the `i18n` key for configuration or by installing the edge channel using an alias like so `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge` and changing `'@nuxtjs/i18n-edge'` to `@nuxtjs/i18n` in `nuxt.config.ts`.

**Comment by Dananz** [comment]
> A recent change broke inline options for `@nuxtjs/i18n-edge`, #2361 will resolve this issue.
> 
> In the meantime you can use the `i18n` key for configuration or by installing the edge channel using an alias like so `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge` and changing `'@nuxtjs/i18n-edge'` to `@nuxtjs/i18n` in `nuxt.config.ts`.

Unfortunately, I cant use the non-edge version.. It break `$tm` support. 

I've opened an bug issue on it https://github.com/nuxt-modules/i18n/issues/2360

**Comment by BobbieGoede** [comment]
When installing the edge version using an alias you will still be using the edge version, it's just the name of the non-edge version is used. I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/missing-keys-in-locale-messages-e4qm3j?file=package.json)

**Comment by BobbieGoede** [comment]
@Dananz now that #2361 has been merged this issue should be fixed after updating to the latest edge version! I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/missing-keys-in-locale-messages-4z398b?file=package.json)

**Comment by TomerActionItem** [comment]
> When installing the edge version using an alias you will still be using the edge version, it's just the name of the non-edge version is used. I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/missing-keys-in-locale-messages-e4qm3j?file=package.json)

Unfortunately, it does not behave like you describe it. 
It looks like its not using the edge version and I have the same bug with `$rt` or `$tm` I mentioned in #2360 
![image](https://github.com/nuxt-modules/i18n/assets/66682924/f357b6c2-df76-4a86-a236-91de2173acaa)

**Comment by Dananz** [comment]
> When installing the edge version using an alias you will still be using the edge version, it's just the name of the non-edge version is used. I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/missing-keys-in-locale-messages-e4qm3j?file=package.json)

Unfortunately, it does not behave like you describe it. 
It looks like its not using the edge version and I have the same bug with `$rt` or `$tm` I mentioned in #2360 
![image](https://github.com/nuxt-modules/i18n/assets/66682924/f357b6c2-df76-4a86-a236-91de2173acaa)


@BobbieGoede 
I have updated your demonstration [here](https://stackblitz.com/edit/not-working-tm?file=src%2Fpages%2Findex.vue)

**Comment by BobbieGoede** [comment]
> Unfortunately, it does not behave like you describe it.

@Dananz 
My suggestions are not related to #2360. The edge version is being installed and being used as can be seen in the lockfile and it solves the issue if the module not being able to locate the locale messages.

**Comment by TomerDanan** [comment]
> > Unfortunately, it does not behave like you describe it.
> 
> @Dananz My suggestions are not related to #2360. The edge version is being installed and being used as can be seen in the lockfile and it solves the issue if the module not being able to locate the locale messages.

You're right, when upgrading to the version you provided, I do not have to deal with these errors again.

But Im struggling with bigger problems now
https://stackblitz.com/edit/missing-keys-in-locale-messages-dm6cvk?file=src%2Fpages%2Findex.vue
