### ISSUE TITLE
`$tm` is not working in non edge channel version

### ISSUE THREAD

**Issue by Dananz** [nuxt-modules/i18n#2360]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.7.0`
- CLI Version:      `3.7.3`
- Nitro Version:    `2.6.2`
- Package Manager:  `npm@8.11.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

**none**

### Reproduction

https://stackblitz.com/edit/tm-not-working-in-non-edge-channel-version?file=nuxt.config.ts

### Describe the bug

Forced to use `$rt` when using `$tm` or `const { tm } = useI18n()` to get full objects translations.

![image](https://github.com/nuxt-modules/i18n/assets/40542472/a086900e-acc8-429c-b884-aab6049dc358)

**Comment by BobbieGoede** [comment]
Could you proved a reproduction in which this is working while using the edge channel? 

>Forced to use $rt when using $tm or const { tm } = useI18n() to get full objects translations.

I haven't used these functions myself, but as far as I can tell the Vue I18n docs seem to describe this as intentional behavior.
* [tm-key](https://vue-i18n.intlify.dev/api/composition.html#tm-key:~:text=You%20need%20to%20use%20rt%20for%20the%20locale%20message%20returned%20by%20tm.%20see%20the%20rt%20details.)
* [ComposerResolveLocaleMessageTranslation](https://vue-i18n.intlify.dev/api/composition.html#composerresolvelocalemessagetranslation), note the tip and warning below details.

**Comment by Dananz** [comment]
> Could you proved a reproduction in which this is working while using the edge channel?
> 
> > Forced to use $rt when using $tm or const { tm } = useI18n() to get full objects translations.
> 
> I haven't used these functions myself, but as far as I can tell the Vue I18n docs seem to describe this as intentional behavior.
> 
> * [tm-key](https://vue-i18n.intlify.dev/api/composition.html#tm-key:~:text=You%20need%20to%20use%20rt%20for%20the%20locale%20message%20returned%20by%20tm.%20see%20the%20rt%20details.)
> * [ComposerResolveLocaleMessageTranslation](https://vue-i18n.intlify.dev/api/composition.html#composerresolvelocalemessagetranslation), note the tip and warning below details.

I cant reproduce it now because its also broken in the edge-channel version.

But Im pretty sure that is not an intentional behavior of **@nuxt/i18n**, based on previous conversations I had with kazupon.
![image](https://github.com/nuxt-modules/i18n/assets/66682924/0ec2c6d5-0336-4a29-97cc-39b3bb894239)

**Comment by BobbieGoede** [comment]
>But Im pretty sure that is not an intentional behavior of @nuxt/i18n, based on previous conversations I had with kazupon.

In that case, /cc @kazupon! 😄

**Comment by kazupon** [comment]
@Dananz 
Thank you for your reporting!

You need to resolve locale messages with `$tm` (a.k.a translation message) with `$rt` (a.k.a resolve translation).
We can translate using vue-i18n `$t` or `t`, and specify the locale message key.

Sometimes, we may want to programmatically handle translation. For example, you may want to iterate using `v-for`.
`$tm` (or `tm`) get the locale message as low level. the retrieved message is optimized by bundle.
So, in vue-i18n, `$t` cannot handle it, so you need to use `$rt`.

about see details here:
https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-api-return-value

**Comment by TomerActionItem** [comment]
> @Dananz Thank you for your reporting!
> 
> You need to resolve locale messages with `$tm` (a.k.a translation message) with `$rt` (a.k.a resolve translation). We can translate using vue-i18n `$t` or `t`, and specify the locale message key.
> 
> Sometimes, we may want to programmatically handle translation. For example, you may want to iterate using `v-for`. `$tm` (or `tm`) get the locale message as low level. the retrieved message is optimized by bundle. So, in vue-i18n, `$t` cannot handle it, so you need to use `$rt`.
> 
> about see details here: https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-api-return-value

@kazupon 
So is that an intentional behavior?
As far as I know, in the current version im using (`"@nuxtjs/i18n-edge": "^8.0.0-rc.2-28194444.5abd10b"`)
there is no need to use `$rt` in combination of `$tm`. 

And I think that changing this behavior between versions its misleading and should be avoided.
It means that I have to stay with `8.0.0-rc.2` for ever because other versions force me to refactor more than 200 pages in my app

**Comment by Dananz** [comment]
> @Dananz Thank you for your reporting!
> 
> You need to resolve locale messages with `$tm` (a.k.a translation message) with `$rt` (a.k.a resolve translation). We can translate using vue-i18n `$t` or `t`, and specify the locale message key.
> 
> Sometimes, we may want to programmatically handle translation. For example, you may want to iterate using `v-for`. `$tm` (or `tm`) get the locale message as low level. the retrieved message is optimized by bundle. So, in vue-i18n, `$t` cannot handle it, so you need to use `$rt`.
> 
> about see details here: https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-api-return-value

@kazupon 
So is that an intentional behavior?
As far as I know, in the current version im using (`"@nuxtjs/i18n-edge": "^8.0.0-rc.2-28194444.5abd10b"`)
**there is no need** to use `$rt` in combination of `$tm`. 

And I think that changing this behavior between versions its misleading and should be avoided.
It means that I have to stay with `8.0.0-rc.2-28194444.5abd10b` for ever because other versions force me to refactor more than 200 pages in my app

**Comment by kazupon** [comment]
>WARNING
> You need to use rt for the locale message returned by tm. see the rt details

https://vue-i18n.intlify.dev/api/composition.html#tm-key

Although not mentioned in the vue-i18n `$tm` documentation, the same is for `$tm` as described in the `tm` API docs.

**Comment by Dananz** [comment]
> > WARNING
> > You need to use rt for the locale message returned by tm. see the rt details
> 
> https://vue-i18n.intlify.dev/api/composition.html#tm-key
> 
> Although not mentioned in the vue-i18n `$tm` documentation, the same is for `$tm` as described in the `tm` API docs.

By far, Im using `@nuxtjs/i18n` for 3 months already, and never had to wrap stuff with `$rt`. 

Upgrading from `rc.2` to `rc.4` forces me to wrap everything with `$rt` 
OR I just need to stay with `@nuxtjs/i18n-edge": "^8.0.0-rc.2-28194444.5abd10b"`

And this is just sad that I cant upgrade `@nuxtjs/i18n` anymore because some core i18n behavior has changed...

Maybe this could be an option I could opt out from the configuartion?
`autoResolveTransition: true` maybe?

**Comment by BobbieGoede** [comment]
> Upgrading from rc.2 to rc.4 forces me to wrap everything with $rt

In my testing it seems like `8.0.0-beta.12` was the last version that still supported the behavior you expect. 

> And this is just sad that I cant upgrade @nuxtjs/i18n anymore because some core i18n behavior has changed...

Pre-release versions (`alpha`, `beta` and `rc`) are not stable, and while we try to avoid introducing breaking changes, they are unfortunately an essential and expected part of the development process toward a stable release.

> Maybe this could be an option I could opt out from the configuartion?
`autoResolveTransition: true` maybe?

Feedback and suggestions are always appreciated. The breaking change was introduced upstream by the [`vue-i18n` (beta version)](https://github.com/intlify/vue-i18n-next) dependency, you could open an issue there to request this opt-out feature.

**Comment by kazupon** [comment]
> By far, Im using @nuxtjs/i18n for 3 months already, and never had to wrap stuff with $rt.
> Upgrading from rc.2 to rc.4 forces me to wrap everything with $rt
OR I just need to stay with @nuxtjs/i18n-edge": "^8.0.0-rc.2-28194444.5abd10b"

In your app, it was just a bug in vue-i18n (or unplugin-vue-i18n) that happened to work.
vue-i18n is wrong, but vue-i18n expects `$tm` and `$rt` to be used as a set, as we have just be using.

>Maybe this could be an option I could opt out from the configuartion?
autoResolveTransition: true maybe?

As BobbieGoede said, we are open to suggestions on this in vue-i18n.
vue-i18n is OSS.
If you have a great idea, we are always waiting for it!

**Comment by Dananz** [comment]
@kazupon @BobbieGoede 

Thanks for your response,
I've followed you suggestions and opened a [feature request here](https://github.com/intlify/vue-i18n-next/issues/1522)
