### ISSUE TITLE
Missing locale prefix for every route

### ISSUE THREAD

**Issue by alexanderfelipeoines** [nuxt-modules/i18n#2362]
### Environment

Nuxt project info:                                                    21:16:17

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      ssr, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

[Stackblitz minimal reproduction](https://stackblitz.com/edit/github-p52p5c?file=app.vue)

### Describe the bug

I get Vue Router warnings for every route using the `prefix` strategy, every route is missing locale prefix (e.g. "en/about") and when manually typing the locale prefixed route into the URL i get 404. 

### Additional context

- I have tried using the edge channel as well as `8.0.0-rc.4` for my `@nuxtjs/i18n` module.
- Same result with `ssr: false`and `ssr: true`

### Logs

```shell
Browser console warning:
[intlify] Not found 'pages.index' key in 'en' locale messages. [chunk-O3UPVJRG.js:110:13](https://githubp52p5c-4uve--3000--33975f1d.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/chunk-O3UPVJRG.js?v=9525272d)
[intlify] Not found 'pages.about' key in 'en' locale messages. [chunk-O3UPVJRG.js:110:13](https://githubp52p5c-4uve--3000--33975f1d.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/chunk-O3UPVJRG.js?v=9525272d)
```

**Comment by kazupon** [comment]
Thank you for your reporting!

Your `i18n.config.ts` contains not only vue i18n `createI18n` but also nuxt i18n config.
The only config that `i18n.config.ts` accepts is vue-i18n's `createI18n` option.
You need to configure `nuxt.config` for nuxt i18n specific settings such as `langDir`, `locales`, and etc.

Thanks!
