### ISSUE TITLE
`useSwitchLocalePath` producing wrong url on the client side when `differentDomains: true`

### ISSUE THREAD

**Issue by zipme** [nuxt-modules/i18n#2364]
### Environment

When setting `differentDomains` to `true` and a `domain` property set to `fr.vercel.app`,   `switchLocalePath(locale)` would yield a wrong URL string on client side (server side works fine)

### Reproduction

https://stackblitz.com/edit/github-kudpru-gvkszv?file=nuxt.config.ts

### Describe the bug

On homepage we have
```ts
<script setup>
const switchLocalePath = useSwitchLocalePath();
console.log(process.client ? 'client' : 'server', switchLocalePath('fr'));
</script>
```

Open the console, you can see the output look like:

```
client https:://example-fr.vercel.app
server http://example-fr.vercel.app
```

(Note the extra ':' in the URL)

Also because of this, visiting the domain would cause an infinite loop

### Additional context

Using rc4

**Comment by kazupon** [comment]
Thank you for your reporting!
This issue will be resolved in PR #2363.
