### ISSUE TITLE
Default JIT compilation breaks my production build

### ISSUE THREAD

**Issue by ghost** [nuxt-modules/i18n#2378]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.17
- Builder:          vite
- User Config:      app, hooks, pages, modules, i18n, css, build, typescript, vite, components, runtimeConfig
- Runtime Modules:  (), @pinia/nuxt@0.4.11, vite-plugin-vue-type-imports/nuxt, @nuxt/image-edge@1.0.0-rc.1-28180077.d51e794, @nuxtjs/i18n@8.0.0-rc.2
- Build Modules:    -
------------------------------

### Reproduction

The default value is toggled to JIT compilation, and I explicitly need to set it to false in order to avoid breaking my build

### Describe the bug

JIT compilation toggled to true. 

Vue-i18n state that it is default to false to avoid breaking change.

### Additional context

https://vue-i18n.intlify.dev/guide/advanced/optimization.html#jit-compilation

**Comment by ritter1** [comment]
>  I explicitly need to set it to false in order to avoid breaking my build

@GaetanWi, how / where would you do that? My production build is also affected..

**Comment by kazupon** [comment]
Thank you for your reporting!

I seem this issue is same #2379 

Could you give us your minimal reproduction please? 🙏

**Comment by GaetanWi** [comment]
> #2379

In your nuxt.config file, you need to specify this :
```
i18n: {
    compilation: {
      jit: false,
    },
    vueI18n: "./i18n.config.ts",
  },
```

**Comment by ghost** [comment]
> > I explicitly need to set it to false in order to avoid breaking my build
> 
> @GaetanWi, how / where would you do that? My production build is also affected..

@ritter1 In your nuxt.config file, you need to specify this :
```
i18n: {
    compilation: {
      jit: false,
    },
    vueI18n: "./i18n.config.ts",
  }
```
