### ISSUE TITLE
Missing docs: JIT and recompilation

### ISSUE THREAD

**Issue by ahoiroman** [nuxt-modules/i18n#2379]
### Describe the feature

At the moment, I am getting hundreds of warnings like this:

```
[intlify] the message that is resolve with key 'navigation.app.sidebar.vault') is not supported for jit compilation
```

In the docs I can find this: https://v8.i18n.nuxtjs.org/options/compilation#jit

> Mean that necessary to pre-compile locale messages that are not managed by the nuxt i18n module (e.g. in the case of importing from a specific URL, you will need to precompile them yourself.)And also, you need to understand that you cannot support use cases where you dynamically compose locale messages from the back-end via an API.

So I need to precompile them by myself? But why?  This is my config:

```
i18n: {
        experimental: {
            jsTsFormatResource: true
        },
        strategy: 'prefix_except_default',
        lazy: true,
        defaultLocale: 'en-US',
        langDir: 'locales',
        locales: [
            {
                code: 'en-US',
                iso: 'en-US',
                name: 'English',
                file: 'en-US.ts'
            },
            {
                code: 'de-DE',
                iso: 'de-DE',
                name: 'German',
                file: 'de-DE.ts'
            },
        ],
    },
```

And, if I need to precompile it, what does that even mean? How can I do that? It would be great to have an addition to the docs.

I would be willing to help implement this feature, but somebody needs to explain that to me first so I can contribute something to the docs ;-) 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by tomsdob** [comment]
This would be very useful for me too, as rc.4 caused the exact same thing.

**Comment by BobbieGoede** [comment]
It seems that these errors are triggered by messages from dynamic resources (js/ts files) as well as messages defined in `messages` key configured in a VueI18n configuration file. 

[Reproduction here](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-hpcvwp?file=i18n.config.ts), refresh on each page to see the different warnings, note how each page has a warning for the `thanks` key which is defined in the VueI18n config file, and for the `hello` key on the Dutch (Nederlands) page as well which is defined in a dynamic resource file. 

@kazupon 
It makes sense for dynamic/remote messages to still need additional precompilation, is there a way for users to do this manually? Surely there is a way for us to precompile messages defined in VueI18n files as well?

**Comment by ghost** [comment]
@BobbieGoede do you mind if I'm using your reproduction link for https://github.com/nuxt-modules/i18n/issues/2378 ? 
As the production build of your example is broken as well

**Comment by BobbieGoede** [comment]
@GaetanWi 
Actually I tried to recreate your issue as well but if you build the project in my reproduction the build seems to work still. Of course you can use my link, but it would be better if you tweak it to recreate the issue described in #2378! 😄

**Comment by ghost** [comment]
Actually, cancelling the terminal going for a yarn build/yarn preview result in error for me @BobbieGoede without changing anything

**Comment by BobbieGoede** [comment]
@GaetanWi 
Hmm, that's odd, it looks like running `preview` results in errors (regardless of `npm` or `yarn`). But running `build` and `node .output/server/index.mjs` seems to work fine. Should be helpful information for #2378!

**Comment by kazupon** [comment]
@BobbieGoede 
Thanks your reproduction! 

This is due to nuxt i18n not correctly setting module `options.alias` & `options.build.transpile`.
`@intlify/core-base` is not bundled in the server side build.

The jit compilation uses feature flags to optimize for development / production.
https://github.com/intlify/vue-i18n-next/blob/bf370816db2b45e0d4b6d25f6399dda2c3cdce42/packages/core-base/src/compilation.ts#L109-L112

On the server side, `@intlify/core-base` is module resolved by `import`, and the feature flags are not properly replaced by nitro.
Now that I know the cause, I will fix it ASAP.
