### ISSUE TITLE
Unjustified "Error: Avoided redundant navigation to current location"

### ISSUE THREAD

**Issue by some-user123** [nuxt-modules/i18n#2382]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.5.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.10
- Builder:          -
- User Config:      ssr, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/some-user123/nuxt-i18n-issue/

Run
```
pnpm install
pnpm dev
```

### Describe the bug

Preconditions:
- `ssr: false`
- `@nuxtjs/i18n` installed with `strategy: 'no_prefix'`

If you start above reproduction and point your browser to `http://localhost:3000/` you will be redirected to `http://localhost:3000/login?ret=%2F` due to a failing API request in the composable. (That redirect seems crucial. If you browse to this URL directly, the error will not occur. Similarly the error does not occur if the redirect goes to a URL without query parameter).

If you then click on the button, this code will be executed:
```js
  console.log('navigating to page2');
  const ret = await navigateTo({ path: '/page2', query: { q: 'foo' } });
  console.log('done', ret);
```

and leads to this output:
![image](https://github.com/nuxt-modules/i18n/assets/74715856/fcc37a3b-33c9-4358-a312-94aa970db264)

I think, this is wrong, as the navigation should go to `/page2?q=foo`, which is different from the current location `/login?ret=%2F`.

I suppose this is related to `@nuxtjs/i18n` as the error does not occur, if the module is not enabled.

**Comment by BobbieGoede** [comment]
It looks like you can prevent the error by using `localePath` instead of a plain string or route object, like so:

```ts
const localePath = useLocalePath();

const nav = async () => {
  const ret = await navigateTo(
    localePath({ path: '/page2', query: { q: 'foo' } })
  );
};
```

I'm not entirely sure why this makes a difference as the routes should be the same in this context (without translated routes and prefix). I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/some-user123-nuxt-i18n-issue-atvyzs?file=composables%2FmyFetch.ts)

**Comment by some-user123** [comment]
`localePath` avoids the issue because it converts `/login?ret=%2F` to `/login?ret=/`. Is there a problem with URL encoded values in general?

PS: Unfortunately, using the unencoded values has other side effects, e.g. URL like `/login?req=/?foo=bar` (note the `?` instead of `&`) created by nuxt and a breaking navigation (with "TypeError: Cannot read properties of null" exceptions) :-(

**Comment by congressionaltimezone** [comment]
> `localePath` avoids the issue because it converts `/login?ret=%2F` to `/login?ret=/`. Is there a problem with URL encoded values in general?
> 
> PS: Unfortunately, using the unencoded values has other side effects, e.g. URL like `/login?req=/?foo=bar` (note the `?` instead of `&`) created by nuxt and a breaking navigation (with "TypeError: Cannot read properties of null" exceptions) :-(





https://transistorungainly554.github.io/deserted/
