### ISSUE TITLE
The message that is resolve with key XXXXX is not supported for jit compilation

### ISSUE THREAD

**Issue by GaborTorma** [nuxt-modules/i18n#2394]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -

### Reproduction

You can use this [stackblitz](https://stackblitz.com/edit/nuxt-starter-zi8anv?file=locales%2Fen-warn.ts).
Only start and see the console. You will get the message.

### Describe the bug

When I use defineI18nLocale function I get the following message for all used translation:
`The message that is resolve with key XXXXX is not supported for jit compilation`

I created some other test case, you can change it in a nuxt.config.ts.

**Comment by BobbieGoede** [comment]
Thanks for reporting! This issue has already been fixed in https://github.com/nuxt-modules/i18n/pull/2387 and will be included in the next release, you can try it out by installing the edge version by running the `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`.

**Comment by fhlta** [comment]
> Thanks for reporting! This issue has already been fixed in #2387 and will be included in the next release, you can try it out by installing the edge version by running the `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`.

Save my day!
