### ISSUE TITLE
What is the reason why I get a prerender error with the generate command when using the i18n package in Nuxt3?

### ISSUE THREAD

**Issue by Fiyuva** [nuxt-modules/i18n#2396]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.3.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      typescript, app, css, router, routeRules, modules, plugins, build, nitro, pinia, security, pwa, image, purgecss, i18n
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/image@1.0.0-rc.1, @vite-pwa/nuxt@0.1.1, nuxt-purgecss@2.0.0, @nuxtjs/color-mode@3.3.0, nuxt-security@0.14.4, @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -

### Reproduction

When I use the Nuxt3 npm run generate command with the i18n package, I receive the following errors, but when I do not use the package, I do not receive the errors. How can I solve this error?

package.json: "@nuxtjs/i18n": "^8.0.0-rc.4",

`modules: [ "@nuxtjs/i18n", ],

`i18n: { lazy: true, langDir: "locales", strategy: "prefix_and_default", locales: [ { code: "en", iso: "en-US", name: "English", file: "en.json" }, { code: "tr", iso: "tr-TR", name: "Türkçe", file: "tr.json" }, ], defaultLocale: "tr", }`

You can see the errors in the link below

[https://stackoverflow.com/questions/77076951/what-is-the-reason-why-i-get-a-prerender-error-with-the-generate-command-when-us](url)

### Describe the bug

When I use the Nuxt3 npm run generate command with the i18n package, I receive the following errors, but when I do not use the package, I do not receive the errors. How can I solve this error?

package.json: "@nuxtjs/i18n": "^8.0.0-rc.4",

`modules: [ "@nuxtjs/i18n", ],

`i18n: { lazy: true, langDir: "locales", strategy: "prefix_and_default", locales: [ { code: "en", iso: "en-US", name: "English", file: "en.json" }, { code: "tr", iso: "tr-TR", name: "Türkçe", file: "tr.json" }, ], defaultLocale: "tr", }`

You can see the errors in the link below

[https://stackoverflow.com/questions/77076951/what-is-the-reason-why-i-get-a-prerender-error-with-the-generate-command-when-us](url)

**Comment by kazupon** [comment]
Thank you for your reporting!

We need your minimal reproduction.
Issue guideline is saying:

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 Reproduction starter (v8 and higher)
>👉 Reproduction starter (edge)

https://github.com/nuxt-modules/i18n/issues/new?assignees=&labels=pending+triage&projects=&template=bug-report.yml

Could you give us your minimal reproduction please?

**Comment by Fiyuva** [comment]
How can i give you minimal reproduction?

**Comment by Triloworld** [comment]
> How can i give you minimal reproduction?

Fork this: https://stackblitz.com/github/nuxt/starter/tree/v3
And and add only what cause problem

**Comment by Triloworld** [comment]
@Fiyuva share there when you have it. Nobody see link from there. This will help diagnose or implement fix if needed

**Comment by kazupon** [comment]
close in-activity
if you have still issue, please you would like to give your minimal reproduction.

thanks!

**Comment by Fiyuva** [comment]
There was a problem with my computer. I will share it in 3 days.
