### ISSUE TITLE
lazy: true not working

### ISSUE THREAD

**Issue by tung1998** [nuxt-modules/i18n#2400]
### Environment

"nuxt": "3.6.5",    
"@nuxtjs/i18n": "8.0.0-rc.3",

### Reproduction

no

### Describe the bug

![image](https://github.com/nuxt-modules/i18n/assets/25732360/582888d7-c898-4531-937e-a853b87cdc02)
![image](https://github.com/nuxt-modules/i18n/assets/25732360/50beaa35-15d9-4d6a-ae87-ab63d5be7eb6)
![image](https://github.com/nuxt-modules/i18n/assets/25732360/56a07070-e6df-416c-a812-1fc1532e277f)

i have option lazy = true, but build version still load all file language

**Comment by BobbieGoede** [comment]
Lazy loading has been fixed in RC 4 which requires Nuxt 3.7.0 or higher, updating both should fix your issue!

**Comment by freezyh** [comment]
> Lazy loading has been fixed in RC 4 which requires Nuxt 3.7.0 or higher, updating both should fix your issue!
I use Nuxt 3.8.2 and "@nuxtjs/i18n": "^8.0.0-rc.7", It not working by set  lazy = true , and have error
https://stackoverflow.com/questions/76594684/nuxt3js-error-i18n-find-files-lang-json

**Comment by BobbieGoede** [comment]
@freezyh 
Could you open a new issue and provide a minimal reproduction? Based on the information in your stackoverflow link, it looks like you should move some of the configuration out of `i18n.config.ts` and into the `nuxt.config.ts`.

Locking this issue as it's likely unrelated and already resolved.
