### ISSUE TITLE
Nested Routes are not created with pages options for layers

### ISSUE THREAD

**Issue by wu3rstle** [nuxt-modules/i18n#2412]
### Environment

Nuxt Version:     3.6.5
@nuxtjs/i18n: 8.0.0-rc.4

### Reproduction

Define nested pages within a nuxt layer following the documentations for nuxt (https://nuxt.com/docs/guide/directory-structure/pages#nested-routes) and i18n (https://v8.i18n.nuxtjs.org/guide/custom-paths#example-2-localize-the-part-of-url) insinde the layer

Try to access to the translated route for child page, it is not working and return a 404 error.

### Describe the bug

Nested routes are not created or linked I guess. Maybe I miss something.

### Additional context

pageDirOverride is not set for child processing and will always use `undefined` https://github.com/nuxt-modules/i18n/blob/bb2a970edb9111558107ec562efe04318b6d929c/src/pages.ts#L112

### Logs

```shell
[@nuxtjs/i18n]: Couldn't find AnalyzedNuxtPageMeta by NuxtPage (child), so no custom route for it
```

**Comment by kazupon** [comment]
Thank you for your reproting!

We need your minimum reproduction to solve your problem.
Could you please give it to us? 🙏

**Comment by wu3rstle** [comment]
Reproduction Repo can be found at https://stackblitz.com/edit/wu3rstle-nuxt-i18n-starter-9whaxh?file=layer%2Fpages%2Fparent%2Findex.vue

`/de/test` and `/en/demo` are working as expected because they are defined at project level.
`/en/parent/` is defined in the layer and working as expected.
`/de/eltern/` should use the same page but can't be found.

**Comment by memic84** [comment]
Same error here, this worked on Nuxt 3.5.x and nuxt i18n => 8.0.0-beta.12, after updating the nested pages are broken.

**Comment by memic84** [comment]
@wu3rstle Have you found a solution, or a workaround?
