### ISSUE TITLE
URL query is missing when started with no_prefix & ssr:false

### ISSUE THREAD

**Issue by dadajam4** [nuxt-modules/i18n#2414]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.5.0
- Builder:          -
- User Config:      ssr, modules, i18n, devtools
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-tc3aqw?file=nuxt.config.ts

1. Wait for the start command to complete.
2. Open preview in a new tab
3. Refresh the screen with an appropriate query to the URL e.g.  https://bobbiegoedenuxti18nstartertc3a-ds0n-bmnkfze2--3000--5291dfc1.local-credentialless.webcontainer.io/?test=1
4. The query granted in (3) is deleted and redirected

### Describe the bug

When nuxt-i18n is configured with certain conditions and nuxt is built (generate) in production mode, when accessing a URL with a query, the query is redirected to the missing URL.
This problem appears to be caused by the following preconditions

- Set to `no_prefix` mode.
-`ssr` is set to`false`.

### Additional context

Some redirects with URL queries are assumed during page initialization, such as modules for authentication, and this issue affects them.

**Comment by BobbieGoede** [comment]
This issue has been fixed by https://github.com/nuxt-modules/i18n/pull/2397 but has not yet been released in an RC version. You can try it out by installing the edge channel like so: `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`

**Comment by dadajam4** [comment]
@BobbieGoede 
I see that it was a known issue! Thanks a lot.
