### ISSUE TITLE
update to latest vue i18n

### ISSUE THREAD

**Issue by hi-reeve** [nuxt-modules/i18n#2415]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.8.3`
- Nitro Version:    `2.6.3`
- Package Manager:  `pnpm@7.14.0`
- Builder:          `-`
- User Config:      `typescript`, `runtimeConfig`, `modules`, `extends`, `nuxtTypedRouter`, `tailwindcss`, `lodash`, `devtools`, `image`, `i18n`, `naiveUI`, `macros`, `css`, `vite`, `imports`, `routeRules`, `components`, `app`, `proxy`, `sourcemap`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `nuxt-icon@0.5.0`, `@nuxtjs/tailwindcss@6.8.0`, `@vueuse/nuxt@10.4.1`, `@nuxt/image-edge@1.0.0-rc.2-28244125.e6e72be`, `nuxt-typed-router@3.3.1`, `@nuxtjs/robots@3.0.0`, `@huntersofbook/naive-ui-nuxt@1.2.0`, `@vue-macros/nuxt@1.8.1`, `@pinia/nuxt@0.4.11`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `@vueuse/motion/nuxt@2.0.0`, `@vee-validate/nuxt@4.11.6`, `~/modules/yup`, `~/modules/vue-query/module.ts`, `~/modules/vue-virtual.ts`, `@nuxtjs/eslint-module@4.1.0`, `@nuxt-alt/proxy@2.3.2`, `nuxt-lodash@2.5.0`, `vite-plugin-vue-type-imports/nuxt`
- Build Modules:    `-`

### Reproduction

please update to latest vue-i18n to fix related issue https://github.com/intlify/vue-i18n-next/pull/1550

### Describe the bug

https://github.com/intlify/vue-i18n-next/issues/1538

**Comment by kazupon** [comment]
Thank you for your feedback!

vue-i18n latest version was included with this [PR](https://github.com/nuxt-modules/i18n/pull/2413)
It will apply with the next RC release.

If you would like to use right now, you can use edge channel version.

Thanks!
