### ISSUE TITLE
localePath doesn't use baseUrl

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt-modules/i18n#2416]
### Environment

Any

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-h9x6wh?file=app.vue

### Describe the bug

When using localePath with baseUrl set, the baseUrl is not prefix to the url.

### Additional context

I've tried setting using both the module option and runtime option (if I understand the docs correctly we can't set the path using runtime options?)

**Comment by bitbytebit1** [comment]
Interestingly using NuxtLink works, but not anchor links

**Comment by rchl** [comment]
That's expected. NuxtLink automatically adds `baseUrl` so if `localePath` would add it, it would be duplicated.

For internal links (which is what `localePath` creates) you should use `NuxtLink`. If you for some reason must use normal anchor for internal links then you have to make sure to prepend the `baseUrl` yourself.

**Comment by bitbytebit1** [comment]
Can you explain what baseUrl does in the i18n config?
https://v8.i18n.nuxtjs.org/options/runtime-config
