### ISSUE TITLE
Router error when using nuxt-i18n

### ISSUE THREAD

**Issue by Teages** [nuxt-modules/i18n#2420]
### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------
```

also on vercel

### Reproduction

repo: https://github.com/Teages/nuxt-i18n-bug-report
stackblitz: https://stackblitz.com/edit/nuxt-starter-sdfbsn

### Describe the bug

There are two bugs:

I definded a dynamic route `/post/:id`, and I have a old post which id have a space, such `hello world`, then the url is `http://localhost:3000/posts/hello%20world`, in this page, the router (both `nuxt-link` and `useRouter`) would throw a error when routing to a new page
```ts
  console.error(await router.push({
    name: 'index'
  }))
```
```
Error: Avoided redundant navigation to current location: "/posts/hello%20world".
    at createRouterError (chunk-KKYRMFY7.js:711:19)
    at pushWithRedirect (chunk-KKYRMFY7.js:2419:17)
    at chunk-KKYRMFY7.js:2459:18
    at async test ([id].vue:6:17)
```

and the second bug, I have a records page, and this page requires login to access. so I definded a middleware.
```ts
export default defineNuxtRouteMiddleware((to) => {
  // ignore verify
  return navigateTo({
    path: '/login',
    query: {
      origin: encodeURIComponent(to.path),
    },
  })
})
```
now visit `http://localhost:3000/records` it works well. but if I visit `http://localhost:3000/records/` the whole nuxt app would be block. and all after requests will time out, it means the services would be stopped in not serverless use case, like being attacked

### Additional context

the nuxt config
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: {
    enabled: true,

    timeline: {
      enabled: true,
    },
  },

  modules: [
    '@nuxtjs/i18n',
  ],

  i18n: {
    locales: [
      { name: 'English', code: 'en', file: 'en/index.ts' },
      { name: '中文（简体）', code: 'zh-CN', file: 'zh-CN/index.ts' },
    ],
    lazy: true,
    langDir: 'locale',
    defaultLocale: 'en',
    strategy: 'no_prefix',
    dynamicRouteParams: false,
    experimental: {
      jsTsFormatResource: true,
    },
    vueI18n: './i18n.config.ts',
  },
})
```

**Comment by BobbieGoede** [comment]
These bugs sound similar to #2382, perhaps using `localePath` as I described there https://github.com/nuxt-modules/i18n/issues/2382#issuecomment-1709886575 will resolve both of your issues. 

Will be closing this so we keep tracking this in a single issue. Still working on resolving #2382 😄
