### ISSUE TITLE
 ERROR  [nuxt] Could not compile template i18n.options.mjs.

### ISSUE THREAD

**Issue by meerzulee** [nuxt-modules/i18n#2428]
### Environment

Working directory: /home/meerzulee/Workspace/Jumbo/aptocms-web-nuxt                                                    10:37:28 AM
Nuxt project info: (copied to clipboard)                                                                               10:37:28 AM

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, css, components, modules, googleFonts, i18n, directus, imports, pinia
- Runtime Modules:  @pinia/nuxt@0.4.11, @unocss/nuxt@0.56.0, @nuxtjs/google-fonts@3.0.2, nuxt-directus@5.5.0, @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

Here is my package.json:
 "devDependencies": {
    "@iconify-json/mdi": "^1.1.54",
    "@nuxt/devtools": "0.8.3",
    "@nuxtjs/i18n": "^8.0.0-rc.4",
    "@nuxtjs/google-fonts": "^3.0.2",
    "@types/node": "^20.6.3",
    "@unocss/nuxt": "^0.56.0",
    "@unocss/preset-icons": "^0.56.0",
    "@unocss/preset-wind": "^0.56.0",
    "@unocss/transformer-directives": "^0.56.0",
    "nuxt": "^3.7.3",
    "nuxt-directus": "^5.5.0",
    "vue-tsc": "^1.8.11"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "@unocss/reset": "^0.56.0"
  }
  
  And nuxt.config  i18n section: 
   i18n: {
    vueI18n: "./i18n.config.ts",
    compilation: {
      strictMessage: false,
    },
    trailingSlash: true,
    strategy: "prefix",
    defaultLocale: "ru",
    lazy: true,
    langDir: "locales",
    locales: [
      { code: "ru", file: "ru.js" },
      { code: "en", file: "en.js" },
      { code: "kg", file: "kg.js" },
    ],
  },
  
  run "yarn" or "yarn dev"

### Describe the bug

After installing     "@nuxtjs/i18n": "^8.0.0-rc.4", "yarn" and "yarn dev" throws and error: 
` ERROR  [nuxt] Could not compile template i18n.options.mjs.  `

Inside `.nuxt` folder I noticed there is no `i18n.options.mjs.` file has been generated.

**Comment by BobbieGoede** [comment]
It's difficult to determine the cause of the error without a minimal reproduction, could you provide one? You can use [this starter](https://stackblitz.com/fork/github/BobbieGoede/nuxt-i18n-starter/tree/v8) to set it up.

I'm not sure what locale files look like, but have you tried adding `experimental: { jsTsFormatResource: true }` to the `i18n` configuration?

**Comment by meerzulee** [comment]
I guess this error occurs only on specific conditions which I am not sure how to reproduce. 
I have created a new project and then added the i18n module, everything works well!
