### ISSUE TITLE
Parameter Not Rendered On The Server

### ISSUE THREAD

**Issue by DefinitlyEvil** [nuxt-modules/i18n#2430]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.15.1
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.5
- Builder:          -
- User Config:      devtools, css, modules, hooks, runtimeConfig, postcss, vite
- Runtime Modules:  @nuxtjs/google-fonts@3.0.2, @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

```typescript
<script setup lang="ts">
  const {$dynFetch} = useNuxtApp()
  const params = useRoute().params
  const run_id = parseInt(<string>params.id)
  const run = await $dynFetch('/run/get?id=' + run_id) // => which calls useFetch() internally
</script>

<template>
  <Head>
    <Title>{{$t('run_details.title', {name: run.item.title})}}</Title>
  </Head>
  ... other lines
</template>
```

### Describe the bug

The server spits the text in translated language, but without replacing any parameters. 
`Run Info - {name}` is in the rendered HTML instread of `Run Info - Some Name`. 

### Logs
```
[Vue warn]: Hydration text content mismatch in <div>:
- Client: Run Details - {name}
- Server: Run Details - Some Name
  at <[id][title] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
```

**Comment by DefinitlyEvil** [comment]
Not sure if this relates to #1812 .

**Comment by DefinitlyEvil** [comment]
By switching to the edge version `npm:@nuxtjs/i18n-edge` this issue is gone.

**Comment by BobbieGoede** [comment]
> By switching to the edge version npm:@nuxtjs/i18n-edge this issue is gone.

Happy to hear it's working on the edge channel, will be closing this issue. Fixes will be included in the next release of course 😄.

**Comment by DefinitlyEvil** [comment]
Thanks for your rapid response! :3 Keep up the good work! <3

**Comment by dongnaebi** [comment]
Can't wait to ask, when will the new version be released?
