### ISSUE TITLE
Broken URI fragment in docs

### ISSUE THREAD

**Issue by xfq** [nuxt-modules/i18n#2433]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `-`
- CLI Version:      `3.9.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/nuxt-modules/i18n/blob/a13dec929213f9ce242aa9cd2c8c1009e0bdfcdb/docs/content/3.options/2.routing.md?plain=1#L40

### Describe the bug

In https://v8.i18n.nuxtjs.org/options/routing#locales , the link to [detectBrowserLanguage](https://v8.i18n.nuxtjs.org/options/routing#detectbrowserlanguage) does not seem to exist.

**Comment by BobbieGoede** [comment]
Thanks for reporting! You're right, the settings were moved to a separate page, same for the `differentDomains` link. Will be fixing shortly.
