### ISSUE TITLE
Composer doesn't support formatting in static mode

### ISSUE THREAD

**Issue by fos7er** [nuxt-modules/i18n#2437]
### Environment

Linux, windows or freebsd

### Reproduction

https://stackblitz.com/edit/github-at1ynv-hufjge?file=pages%2Findex.vue

### Describe the bug

If you use composer like this:
\<div v-for="item in tm('array')"\>
   \<span\>{{ rt(item, ['Alex']) }}\</span\>
\</div\>
It works good on dev, but after generate it ignores additional locale parameters. It won't print 'Alex' on production in static mode.
BTW it works fine if you use Named formatting https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting

**Comment by Luffyyy** [comment]
Having the same issue, did you find a solution?

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is upstream issue.
so, I'll try to fix this issue.

**Comment by kazupon** [comment]
This issue was fixed by https://github.com/intlify/vue-i18n-next/pull/1571
Thanks!
