### ISSUE TITLE
 ERROR(vue-tsc)  Property 'code' does not exist on type 'string | LocaleObject'.   Property 'code' does not exist on type 'string'.

### ISSUE THREAD

**Issue by imcm7** [nuxt-modules/i18n#2440]
### Environment

 Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.2

### Reproduction

I do something like that https://v8.i18n.nuxtjs.org/guide/lang-switcher#lang-switcher

```
<script setup>
const { locale, locales, setLocale } = useI18n()

const availableLocales = computed(() => {
  return (locales.value).filter(i => i.code !== locale.value)
})
</script>

<template>
  ...
  <a
    href="#"
    v-for="locale in availableLocales"
    :key="locale.code"
    @click.prevent.stop="setLocale(locale.code)"
    >{{ locale.name }}</a
  >
  ...
</template>
Copy to clipboard

```

### Describe the bug

 ERROR(vue-tsc)  Property 'code' does not exist on type 'string | LocaleObject'.
  Property 'code' does not exist on type 'string'.

**Comment by BobbieGoede** [comment]
This happens because it is possible to configure locales with type `string` or `LocaleObject`, so the `locales` array is of type `string[] | LocaleObject[]`. 

In order to be typesafe you have to check which type it is before trying to access the `code` property, as these only exist on `LocaleObject`. The following would be one way to do this, excluding any locales of type `string`:

```ts
const availableLocales = computed(() => {
  return (locales.value).filter(i => typeof i !== 'string' && i.code !== locale.value)
})
```

Hope that clears things up, let me know if you have any questions!

**Comment by imcm7** [comment]
@BobbieGoede Thanks, I understand, but will be nice if it will simply work, without supplementary things to do.

**Comment by imcm7** [comment]
```
  const availableLocales = computed(() => {
    return $i18n.localeCodes.value; 
  });
 ```
 
 ```
 <div
      v-for="language in availableLocales"
      :key="language"
>
        {{ language }}
</div>
```

**Comment by Sazzels** [comment]
remove the current locale from `availableLocales`

```ts
const { locale, localeCodes } = useI18n();

const availableLocales = computed(() => {
  return localeCodes.value.filter((i) => i !== locale.value);
});
```
