### ISSUE TITLE
Is there any way to disable or turn off i18n base on a request ?!

### ISSUE THREAD

**Issue by yazdanqm** [nuxt-modules/i18n#2456]
### Environment

export default

### Reproduction

```

``` 

### Describe the bug

I don't know this is a bug or not , but is there any way or feature to disable whole I18n based on an API request ?! i i used I18n as an Addon and my users can disable or enable it. i want to disable it and its routes and all configs dynamically, how can i do this in Nuxt config or out of it ?

**Comment by kazupon** [comment]
This is not issue, so question.
I'll move to github discussions.
