### ISSUE TITLE
Alternative i18n config path not working

### ISSUE THREAD

**Issue by GaborTorma** [nuxt-modules/i18n#2459]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4-28265986.9dae464
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-5ve3dz?file=config%2Fi18n.ts,nuxt.config.ts

### Describe the bug

vueI18n config not found when I put it into a folder like this: vueI18n: './config/i18n.ts'
You can check it on Stackblitz. I used the latest edge release.

**Comment by GaborTorma** [comment]
@nuxtjs/i18n-edge@^8.0.0-rc.4-28244271.fbea0d9 release works well.

**Comment by BobbieGoede** [comment]
Oops! This bug was introduced by my refactor of the options generation, hopefully will have a fix for this soon.
