### ISSUE TITLE
Error log showing in production

### ISSUE THREAD

**Issue by rafaelragib** [nuxt-modules/i18n#2461]
### Describe the feature

Hello
While using i8n in Nuxt 3, I am facing an issue regarding the error log. The error log is shown in the production in runtime. It would be better if the error log could be omitted in the production or can be captured. It is important as the error cannot be captured in the plugin or middleware in runtime. 
![image](https://github.com/nuxt-modules/i18n/assets/23039771/f7b9aa4a-0a28-465b-a257-9717aa088301)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
It's not error, so warning message.
If you are getting that message, then you either do not have translation resources set, or you specified the wrong key.

If you do not want the warning output, you can suppress it by specifying the following optoins to i18n.config
- missingWarn
- fallbackWarn
