### ISSUE TITLE
i18n breaks Nuxt Auto-Import functionality!

### ISSUE THREAD

**Issue by Bombastickj** [nuxt-modules/i18n#2483]
### Environment

Nuxt project info:

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.6.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@8.17.0
- Builder:          -
- User Config:      devtools, typescript, imports, modules, pinia, i18n
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cmht5h?file=stores%2Fpage.ts

### Describe the bug

The error occurs when using the pinia & i18n packages for nuxt 3. All auto-imports for components are lost, when importing a component inside a pinia store, to define a InstanceType. I've tested to remove the i18n package and all auto-imports were back to normal.

### Additional context

Also checked that Volar (takeover) is active. Bug can be viewed easily when following small instructions inside /stores/page.ts

**Comment by kazupon** [comment]
Thank you for you reporting!

Hmm, 🤔 
nuxt i18n is just implemented using `addImports`.
We’re implementing it using the API provided by nuxt/kit.
https://github.com/nuxt-modules/i18n/blob/8a33fecd9b9c4668145e41d3fb35640d308711a5/src/module.ts#L297-L315

I don't see why combining it with `@pinia/nuxt` would cause issues. /cc @posva

@danielroe 
Is there anything in nuxt i18n's auto-import implementation that is not within the guidelines?

**Comment by posva** [comment]
I have no idea why combining both modules would break auto imports 😅

**Comment by BobbieGoede** [comment]
After trying the reproduction in stackblitz and locally, I can't reproduce the issue described. 

Uninstalling and removing `@nuxtjs/i18n` and its configuration seems to have no effect, `SomePopup` gets inferred correctly in `app.vue` but cannot be found inside the `page.ts` store with the `popupDefined` line uncommented. Edited [reproduction here](https://stackblitz.com/edit/nuxt-starter-k4xitt?file=components%2FSomePopup.vue)

Maybe I'm doing something wrong, can someone else confirm this issue is happening as described?

**Comment by Bombastickj** [comment]
> After trying the reproduction in stackblitz and locally, I can't reproduce the issue described.
> 
> Uninstalling and removing `@nuxtjs/i18n` and its configuration seems to have no effect, `SomePopup` gets inferred correctly in `app.vue` but cannot be found inside the `page.ts` store with the `popupDefined` line uncommented. Edited [reproduction here](https://stackblitz.com/edit/nuxt-starter-k4xitt?file=components%2FSomePopup.vue)
> 
> Maybe I'm doing something wrong, can someone else confirm this issue is happening as described?

Yeah to use the InstanceType, you have to uncomment the import in line 9 inside 'page.ts'. Then it will break locally. Mabe the Component needs to be imported another way? My problem is, that it fully works when i18n is not installed..

**Comment by BobbieGoede** [comment]
Ah I misread the instructions and didn't see the import on line 9 had to be uncommented as well!

Hmmm, after playing around some more, I noticed that removing `imports` from `nuxt.config.ts` seems to make it work as expected.

But after trying more things I noticed that it also works while keeping the `imports` config, and restarting Volar. Not sure why that is..


https://github.com/nuxt-modules/i18n/assets/6649305/a04486e7-3a57-4202-8f60-2c207124248a

**Comment by danielroe** [comment]
I can't reproduce when downloading that stackblitz and refreshing lockfile.

![CleanShot 2023-10-11 at 11 06 01](https://github.com/nuxt-modules/i18n/assets/28706372/58cd574c-5ba9-4501-ba6b-a9ac622134a5)

**Comment by Bombastickj** [comment]
> I can't reproduce when downloading that stackblitz and refreshing lockfile.
> 
> ![CleanShot 2023-10-11 at 11 06 01](https://user-images.githubusercontent.com/28706372/274227268-58cd574c-5ba9-4501-ba6b-a9ac622134a5.png)

Its all fine inside the store. What's not working is the auto-import inside all other files like `app.vue` when `popupDefined` is uncommented all components become the type `'unknown'`

**Comment by Bombastickj** [comment]
Hi guys, I have some videos to visualize the bug that is happening.

After looking more into it, I've found out that the bug does not only happen inside a pinia store:

https://github.com/nuxt-modules/i18n/assets/14128197/ab7fd5c7-aae9-4ae8-818c-1922983c7753

When `@nuxt/i18n` is removed no bug appears:

https://github.com/nuxt-modules/i18n/assets/14128197/f9423cb9-0d9e-412f-b9e0-f3c0546b2014

Updated reproduction:
https://stackblitz.com/edit/nuxt-starter-cmht5h?file=stores%2Fpage.ts

Hope this helps with clarification @kazupon

**Comment by Applelo** [comment]
Hi all, I can confirm @Bombastickj reproduction, I have the same issue with my current project using nuxt i18n last version. All Vue components (from /components folder or coming from other plugins/modules) inside my template are reported as `unknow`. 
[EDIT] What is weird, the components are imported correctly when call inside another components (inside the components folder) but not inside the /pages folder.

**Comment by jensk** [comment]
I also can confirm this issue

**Comment by metkm** [comment]
> [EDIT] What is weird, the components are imported correctly when call inside another components (inside the components folder) but not inside the /pages folde

This doesn't work for me at all. All the autocompletion just dies even inside the components folder.

**Comment by Bombastickj** [comment]
Hello,
do you guys have any updates on why this is happening? @kazupon @BobbieGoede

**Comment by BobbieGoede** [comment]
I'm still looking into what the exact source of this issue is, it's not that easy to debug unfortunately. 

I have been trying to find what is breaking the type inference by removing type imports inside `.nuxt` and restarting the vue language server, which is tedious. 

By doing so I have been able to narrow it down to types provided by `@intlify/vue-i18n-bridge` (in `vue-i18n-routing`) and `vue-i18n` (in `@nuxtjs/i18n`), if I remove type imports from those dependencies the type inference seems to work again. Next I will have to figure out what is different about those types, that will take some more time 😭

**Comment by kazupon** [comment]
@BobbieGoede 
I reproduced it in my environment. I really appreciate your efforts.

**Comment by BobbieGoede** [comment]
It seems like these lines are breaking the type inference https://github.com/intlify/vue-i18n-next/blob/master/packages/vue-i18n/src/vue.d.ts#L1232-L1239

**Comment by Bombastickj** [comment]
Thank you so much @BobbieGoede!

**Comment by rchl** [comment]
> It seems like these lines are breaking the type inference [intlify/vue-i18n-next@`master`/packages/vue-i18n/src/vue.d.ts#L1232-L1239](https://github.com/intlify/vue-i18n-next/blob/master/packages/vue-i18n/src/vue.d.ts?rgh-link-date=2023-11-02T22%3A51%3A14Z#L1232-L1239)

I haven't looked myself but in that case the issue is likely that it extends `GlobalComponents` in `@vue/runtime-core` but should be extending it in `vue` module instead.

And also it should likely first `import 'vue'` as the original module needs to be referenced first, otherwise (depending on loading order) the i18n module can overwrite the module instead of extending it.

**Comment by kazupon** [comment]
> And also it should likely first import 'vue' as the original module needs to be referenced first, otherwise (depending on loading order) the i18n module can overwrite the module instead of extending it.

The types provided by vue-i18n in npm will be combined with typescript-generated types and vue-extended types defined in `src/vue.d.ts` when building.
The combined types have `import vue`, so your point should not be a problem.

**Comment by metkm** [comment]
https://github.com/nuxt-modules/i18n/issues/2490#issuecomment-1793330070 This is related. Probably can be closed now if the issue is fixed

**Comment by Bombastickj** [comment]
Hi guys!
After having some small issues with opting into the edge release channel, I finally got it working! If anyone runs into some trouble installing, I used `node 18.18.2`. Don't forget to remove lock file and node_modules before installing.

Thank you guys so much!! @BobbieGoede @kazupon 

[Fixed reproduction](https://stackblitz.com/edit/nuxt-starter-cmht5h?file=package.json)
