### ISSUE TITLE
This module breaks ":to" links in nuxt v3

### ISSUE THREAD

**Issue by florealcab** [nuxt-modules/i18n#2493]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/florealcab/NuxtI18nBug

### Describe the bug

If you are in a page, and the URL ends with a slash (example: /sub/toto/), then any link on the page with the "to" parameter has no more effect (example : <NuxtLink to="/">Index</NuxtLink>) : click action is ignored, nothing in logs client side or server side.

If you just remove the trailing slash, all works well.

To reproduce it with the repo I give:
Go to http://localhost:3000/sub/test/ and try to click on the link "Go to index". Nothing happen. No logs.
Now, just remove the trailing slash (url become http://localhost:3000/sub/test). Click to the link "Go to index" again: it works!

### Additional context

This bug appears with the 8.0.0-rc3 version and does not exists before (tested with 8.0.0-beta10, rc1 and rc2), and always after (tested until rc5 which is the latest version for now.

This bug seems to be related to this module. I install all and then just downgrade or upgrade this module. I try to use the rc5 version and manually downgrade vue-i18n and vue-i18n-routing to the same version they had with the 8.0.0-beta10 of this module: the bug is still here.

But I don't know what causes this on this module, by the way...

**Comment by Luffyyy** [comment]
I had the same issue, it was causing issues when navigating to pages via an alias (which is defined via definePageMeta)

**Comment by Frallen** [comment]
I'm getting the same problem. With each version, there are only more and more bugs.

**Comment by Frallen** [comment]
Downgrade to `^8.0.0-beta.11`

**Comment by BobbieGoede** [comment]
>I'm getting the same problem. With each version, there are only more and more bugs.

@Frallen 
We're working hard to make v8 stable. If you run into bugs, report them and provide a minimal reproduction. Or better yet, open a PR to fix the issue, all contributions are appreciated!

**Comment by MaxCpp** [comment]
Sorry, when this fix release?
