### ISSUE TITLE
`useLocaleHead` stop workding when upgrade to 8.0.0-rc.5

### ISSUE THREAD

**Issue by everyx** [nuxt-modules/i18n#2497]
### Environment

- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.5
- Builder:          -
- User Config:      typescript, $development, runtimeConfig, build, nitro, modules, unocss, i18n, image, vue, $production
- Runtime Modules:  @unocss/nuxt@0.56.5, @nuxtjs/i18n@8.0.0-rc.5, @nuxt/image@1.0.0-rc.3
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-s3mfea-rnbn7m?file=layouts%2Fdefault.vue

### Describe the bug

When I upgrade from 8.0.0-rc.3 to 8.0.0-rc.5, `useLocaleHead` stop working.

### Logs

```shell
[vue-i18n-routing] Locale ISO code is required to generate alternate link
```

**Comment by kazupon** [comment]
Hmm, It appears to have been degrade by rc.5 release. /cc @BobbieGoede 
https://github.com/nuxt-modules/i18n/compare/v8.0.0-rc.4...v8.0.0-rc.5

**Comment by BobbieGoede** [comment]
Ah, I believe this is a bug introduced by my refactor, sorry about that! 🙏

Fortunately there is a simple workaround for this, if you add another property to each locale, it should work as expected. I recommend adding a `name` to each locale, but any key will do. I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/github-s3mfea-xszhrb?file=nuxt.config.ts).

As for the reason this happens, the shape of the configured locales `{ code: string; iso: string; }` is identical to the shape of `string` locales after being normalized. My bug incorrectly tries to restore the original configuration and writes that to `.nuxt/i18n.options.mjs`, I will look into a fix shortly!
