### ISSUE TITLE
Warning will be displayed if custom attribute is specified

### ISSUE THREAD

**Issue by dadajam4** [nuxt-modules/i18n#2498]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.5.0
- Builder:          -
- User Config:      ssr, devtools, srcDir, css, modules, auth, api, logs, catcher, runtimeConfig, imports, i18n, vite
- Runtime Modules:  @hoshinoresort/nuxt-openapi-client@0.0.4, @hoshinoresort/nuxt-hr-auth@1.0.14, @hoshinoresort/nuxt-catcher@0.0.14, @hoshinoresort/nuxt-logs@0.1.6, @hoshinoresort/nuxt-vue-ui@0.1.53, @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-e6xbjp?file=components%2FCustomLink.vue

### Describe the bug

A warning will be displayed if you specify a `custom` attribute that can be set for NuxtLink.

```
[Vue warn]: Extraneous non-props attributes (locale) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <RouterLink ref=fn to=Ref< "/en" > activeClass=undefined  ... > 
  at <NuxtLinkLocale to=Ref< "/en" > href=undefined target=undefined  ... > 
  at <NuxtLinkLocale to="/" custom="" > 
  at <CustomLink> 
```

### Additional context

This seems to be caused by passing a locale attribute to NuxtLink that NuxtLink does not allow in the following code section.

https://github.com/nuxt-modules/i18n/blob/1fc1f02a3d670c2b165d78b22de678b84ac7606a/src/runtime/components/NuxtLinkLocale.ts#L52

```
h(NuxtLinkLocale, { ...props, to: resolvedPath }, slots.default)
```

The above props object contains a `locale` key, and in my incidence the value was `undefined`.

I think the `locale` attribute is only needed for processing on the i18n side and not for injection into NuxtLink.

**Comment by BobbieGoede** [comment]
Resolved by #2499!
