### ISSUE TITLE
pnpm support without `--shamefully-hoist`

### ISSUE THREAD

**Issue by cexbrayat** [nuxt-modules/i18n#2506]
### Describe the feature

Nuxt itself now supports pnpm without forcing the usage of `--shamefully-hoist`, see https://github.com/nuxt/nuxt/issues/14146

But when adding `@nuxtjs/i18n@next` with:

```
pnpm add @nuxtjs/i18n@next --save-dev
```

then a minimal application does not build because of missing dependencies.

We currently have to at least add:

```
    "@intlify/core-base": "^9.5.0",
    "@intlify/message-compiler": "^9.5.0",
    "@intlify/shared": "^9.5.0",
    "@intlify/vue-i18n-bridge": "^1.0.1",
    "@intlify/vue-router-bridge": "^1.0.1",
    "@nuxtjs/i18n": "8.0.0-rc.5",
    "is-https": "^4.0.0",
    "js-cookie": "^3.0.5",
    "vue-i18n": "^9.5.0",
    "vue-i18n-routing": "^1.1.1"
```
to make a minimal application build.

See this minimal repro on stackblitz https://stackblitz.com/edit/nuxt-starter-m6l8tv?file=nuxt.config.ts,package.json

It would be great if this module supporte pnpm out the box, without needing to add all these dependencies explicitely.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
Thank you for your reporting!
This issue and related issues are working on right now.
#2503 
#2504 
I believe those are fixed, when that will be finished.

**Comment by BobbieGoede** [comment]
It seems to mostly work without installing all the deps, for some reason `is-https` still needs to be installed explicitely. 🤔

Changed your reproduction to demontrate [here](https://stackblitz.com/edit/nuxt-starter-mq1oh4?file=README.md)

**Comment by BobbieGoede** [comment]
This should work now on the latest edge channel!
