### ISSUE TITLE
Per-component translations not working with Options API

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt-modules/i18n#2514]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.7.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      app, modules, i18n, devtools, build, experimental
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -
------------------------------

### Reproduction

No need, there's no way to use per-component translations with the Options API currently.

### Describe the bug

Vue3 (and by extension Nuxt3) officially supports both the Options API and Composition API.
This module should provide per-component translations with the Options API, like we had for Nuxt2.

**Comment by TheDutchCoder** [comment]
I did find an undocumented component `<i18n-t></i18n-t>` that actually seems to work, but it's not a good alternative, as it would mean having to change the source code of hundreds of components in a big project.

What I don't fully understand is why the local version of `$t` is not provided by default? Couldn't we get something like `$tl` for the locally scoped version of `$t`?

**Comment by kazupon** [comment]
I seem this is upstream (vue-i18n-next).
Could you try to reproduce the below stackblize template, please? 🙏 
https://stackblitz.com/edit/vitejs-vite-gfrx6w

if you will get the issue, please open a new issue at vue-i18n-next repo

**Comment by TheDutchCoder** [comment]
Okay I'll create an issue there: https://github.com/intlify/vue-i18n-next/issues/1603

**Comment by kazupon** [comment]
close, so upstream issue.
