### ISSUE TITLE
fix: layer types for hooks

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#2515]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    -
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-cuatfe?file=package.json

Use `pnpm nuxt typecheck`.

### Describe the bug

Extending a project using `@nuxtjs/i18n` v8.0.0-rc.5-28296269.d5d5540 (including the removal of shameful hoisting) leads to type errors on `nuxt typecheck` if e.g. a plugin uses a hook by `@nuxtjs/i18n`:

The types are available when linting the layer, but not anymore when linting the project which uses the layer. A workaround is to install `@nuxtjs/i18n` on the project as well, but I think the types could be put in a place where they are accessible as before dropping shameful hoisting as explained below under "additional context".

### Additional context

@harlan-zw puts generated types into `.nuxt/module/*.d.ts`. Maybe that would fix the issue?

https://github.com/harlan-zw/nuxt-og-image/blob/c89fd4e29f56eeb00b12bc0d7e4bcb82ab459cae/src/kit.ts#L8

e.g.

```
// Generated by nuxt-seo-experiments.assets

declare module '#app/nuxt' {
  import { HeadEntry, HeadTag } from '@unhead/schema'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
...
export {}
```

### Logs

```shell
layer/plugins/i18n.ts:2:16 - error TS2345: Argument of type '"i18n:localeSwitched"' is not assignable to parameter of type 'HookKeys<RuntimeNuxtHooks>'.
2   nuxtApp.hook('i18n:localeSwitched', ({ newLocale }) => {
                 ~~~~~~~~~~~~~~~~~~~~~
layer/plugins/i18n.ts:2:42 - error TS7031: Binding element 'newLocale' implicitly has an 'any' type.
2   nuxtApp.hook('i18n:localeSwitched', ({ newLocale }) => {
                                           ~~~~~~~~~

Found 2 errors in the same file, starting at: layer/plugins/i18n.ts:2

 ERROR  Command failed with exit code 2: vue-tsc --noEmit
```

**Comment by BobbieGoede** [comment]
Looks like this has been resolved (likely has been for a while 😅), I've updated your reproduction to demonstrate [here](https://stackblitz.com/edit/github-cuatfe-5uebn8?file=package.json).

**Comment by dargmuesli** [comment]
It appears I can confirm this being fixed. Thank you! :partying_face:
