### ISSUE TITLE
Nuxt Typed Router support for the new NuxtLinkLocale component

### ISSUE THREAD

**Issue by UfukUstali** [nuxt-modules/i18n#2516]
### Describe the feature

Currently the props for the component are not typed like they are in the NuxtLink component
```vue
<template>
  <div>
    <NuxtLinkLocale to=""></NuxtLinkLocale>
                       ^ not typed
    <NuxtLink to=""></NuxtLink>
                 ^ typed ["/", "/about" ...]
  </div>
</template>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by BobbieGoede** [comment]
Is this similar to, or the same as #2109?

**Comment by UfukUstali** [comment]
Similar in the sense that it tries to achieve the same result but this is something [nuxt-typed-router](https://github.com/victorgarciaesgi/nuxt-typed-router) has already done the types are already there they are just not being utilized like they are in [useLocalePath](https://i18n.nuxtjs.org/api/composables#uselocalepath) composable.
```typescript
const localePath = useLocalePath()
localePath("")
            ^ typed
```
