### ISSUE TITLE
[intlify] the message that is resolve with key 'xxx') is not supported for jit compilation

### ISSUE THREAD

**Issue by everyx** [nuxt-modules/i18n#2520]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-aln3bd?file=pages%2Findex.vue

### Describe the bug

I use `mergeLocaleMessage` to  dynamic set messages, and use `tm` to get the message which include a named interpolation, then use `rt` to render it, and I will get `[intlify] the message that is resolve with key 'xxx') is not supported for jit compilation`, and this will cause Vue hydration content mismatch.

**Comment by kazupon** [comment]
Thank you for tour reporting!

I've just checked your `package-lock.json`
I noticed that an older version of the Nuxt-i18n deps is installed.
For example, vue-i18n was 9.3.0-beta.27.
nuxt-i18n rc5 directly worked correctly.

**Comment by ibrahemelahmedy** [comment]
thanks alot mr kazupon 
the same problem solved with me with your solve
