### ISSUE TITLE
LocalePath double encoding URLs, causing 404s

### ISSUE THREAD

**Issue by georgesaliba** [nuxt-modules/i18n#2523]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      experimental, routeRules, devtools, modules, runtimeConfig, security, app, i18n, nitro
- Runtime Modules:  nuxt-security@0.14.4, @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.5.1, nuxt-headlessui@1.1.4, @vueuse/nuxt@10.5.0, nuxt-lazy-hydrate@1.0.0
- Build Modules:    -

### Reproduction

Use localePath with any URL path that includes spaces.

### Describe the bug

Using useLocalPath on any URL that includes spaces is double encoding the path, causing the route to fail to resolve (404).

For example, the following:

`const { localePath } = useLocalePath();

const url = localePath('path/as a test')`

...will result in a url like "/path/as%2520a%2520test". It should instead be "/path/as%20a%20test", but the function appears to be double encoding, causing the %20 to change to %2520 (which fails to resolve as a route, and causes a 404).

**Comment by georgesaliba** [comment]
This appears to be caused by 8.0.0-rc.5; rolling back to 8.0.0-rc.4 works as a workaround.

**Comment by kazupon** [comment]
reopen, so We have not still integrate vue-i18n-routing  latest version
