### ISSUE TITLE
Hash in NuxtLink don't work with LocalePath

### ISSUE THREAD

**Issue by NtchPlayer** [nuxt-modules/i18n#2525]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, build, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ynzoxn

### Describe the bug

When you add a hash to a link with `localePath` like this:
```HTML
<NuxtLink :to="localePath({ name: 'about', hash: '#myHash' })">
  My link with a hash
</NuxtLink>
```

The Hash of link is not add to the generated tag
```HTML
<a href="/en/about">My link with a hash</a> // #myHash is missing
```

**Comment by BobbieGoede** [comment]
This issue should be fixed upstream when https://github.com/intlify/routing/pull/78 is merged and the dependency is updated. 

The issue only happens for links without query parameters so it's possible to add query parameters to the link for the hash to work. In the meantime a better workaround would be to pin `vue-i18n-routing` to its previous version `1.1.1`, which doesn't have this issue.

**Comment by NtchPlayer** [comment]
Thx for your precision !

**Comment by kazupon** [comment]
reopen, so We have not still integrate vue-i18n-routing  latest version
