### ISSUE TITLE
prefix_except_default doesn't generate new routes

### ISSUE THREAD

**Issue by wrkmartech** [nuxt-modules/i18n#2527]
### Environment

- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      devtools, modules, i18n, css, app
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -

### Reproduction

[https://stackblitz.com/edit/nuxt-starter-7insz7](https://stackblitz.com/edit/nuxt-starter-7insz7)

### Describe the bug

I have 2 initial routes:
`pages/index.vue`
`pages/about.vue`

and 3 locales: en, fr, es

Using the option "prefix_except_default" I expect to get a new array of routes, as described in [doc](https://i18n.nuxtjs.org/guide/routing-strategies#routing):
```
[
  {
    path: '/',
    name: 'index___en'
  },
  {
    path: '/fr',
    name: 'index___fr'
  },
  {
    path: '/es',
    name: 'index___es'
  },
  {
    path: '/about',
    name: 'about___en'
  },
  {
    path: '/fr/about',
    name: 'about___fr'
  },
  {
    path: '/es/about',
    name: 'about___es'
  },
]
```
But new routes are not created

### Logs

```shell
[Vue Router warn]: No match found for location with path "/fr"
[Vue Router warn]: No match found for location with path "/es"
[Vue Router warn]: No match found for location with path "/fr/about"
[Vue Router warn]: No match found for location with path "/es/about"
[Vue Router warn]: No match found for location with path "/fr"
[Vue Router warn]: No match found for location with path "/es"
[Vue Router warn]: No match found for location with path "/fr/about"
[Vue Router warn]: No match found for location with path "/es/about"
```

**Comment by BobbieGoede** [comment]
You need to set the locales option in the `i18n` config for this to work, I changed your reproduction to demonstrate [here].(https://stackblitz.com/edit/nuxt-starter-72yjba?file=i18n.config.ts,nuxt.config.ts)

I understand this is confusing as `vueI18n` detects the locales based on configured messages in `i18n.config.ts` separate from this module.
