### ISSUE TITLE
Some page recalls navigateTo again with 302 redirectCode.

### ISSUE THREAD

**Issue by Ciscodefran** [nuxt-modules/i18n#2528]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `bun@1.0.7`
- Builder:          `-`
- User Config:      `ssr`, `target`, `spaLoadingTemplate`, `routeRules`, `devtools`, `app`, `css`, `vite`, `nitro`, `experimental`, `components`, `imports`, `modules`, `buildModules`, `plugins`, `stylelint`, `i18n`, `pinia`, `piniaPersistedstate`, `vueuse`, `elementPlus`, `typescript`, `pwa`, `facebook`, `firebase`, `sitemap`, `runtimeConfig`
- Runtime Modules:  `@nuxt/devtools@1.0.0`, `@pinia/nuxt@0.4.11`, `@pinia-plugin-persistedstate/nuxt@1.2.0`, `@vite-pwa/nuxt@0.1.1`, `@nuxt/image@1.0.0`, `@element-plus/nuxt@1.0.6`, `@nuxtjs/i18n@8.0.0-rc.4`, `@vueuse/nuxt@10.5.0`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/device@3.1.1`, `nuxt-jsonld@2.0.8`, `@nuxtjs/stylelint-module@5.1.0`, `nuxt-simple-sitemap@3.4.1`, `nuxt-icon@0.5.0`
- Build Modules:    `nuxt-facebook-pixel-module@1.6.0`, `unplugin-icons/nuxt`

### Reproduction

I found the issue spot. I think I do not need it. sry.

### Describe the bug

I develop a project with nuxt3 on falsy SSR. when I use navigateTo function, the route navigate to same page again with redirect code 302.

**Comment by kazupon** [comment]
close due to in-activity.
if you are having still issue, please you would open as new issue.
thank you!
