### ISSUE TITLE
Use different languages as the default language according to different domain names, and the prefix_except_default policy takes effect

### ISSUE THREAD

**Issue by WooHoo-Wu** [nuxt-modules/i18n#2550]
### Describe the feature

Use different languages as the default language according to different domain names, and the prefix_except_default policy takes effect

for example：
I have 3 languages: en, zh, ru
domain: domain1.com
defaultLocale = 'en'
strategy = 'prefix_except_default'
router：
domain1.com/         is en locale
domain1.com/ru

When I switch to zh
domain: domain2.com
defaultLocale = 'zh'
strategy = 'prefix_except_default'
router：
domain2.com/          is zh locale
domain2.com/ru

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
Thank you for your reporting!

You have a routing strategy of `prefix_except_default` with different values for the `defaultLocale` option for each domain, so I seem that it’s works correctly

The locale value also behaves differently depending on the `detectBrowserLanguage` option.
You can see it in the docs.
https://i18n.nuxtjs.org/guide/browser-language-detection

Thank you!

**Comment by sxhweb** [comment]
I'm having the same problem and I don't think it can be solved by detecting the browser language. How to specify the value of defaultLocale based on the domain name?

**Comment by sxhweb** [comment]
> Thank you for your reporting!
> 
> You have a routing strategy of `prefix_except_default` with different values for the `defaultLocale` option for each domain, so I seem that it’s works correctly
> 
> The locale value also behaves differently depending on the `detectBrowserLanguage` option. You can see it in the docs. https://i18n.nuxtjs.org/guide/browser-language-detection
> 
> Thank you!
I'm having the same problem and I don't think it can be solved by detecting the browser language. How to specify the value of defaultLocale based on the domain name?
