### ISSUE TITLE
Default locales, manual URL redirection and Japanese/Chinese characters encode

### ISSUE THREAD

**Issue by orsileonel** [nuxt-modules/i18n#2551]
Hello, I have some questions which I couldn't find at the moment to fix them.

This is my configuration:

**package.json**
```
"nuxt": "^3.7.4",
"@nuxtjs/i18n": "^8.0.0-rc.5",
```

**nuxt.config.js**
```i18n: {
    langDir: './locales',
    locales: [
      {
        code: 'en',
        iso: 'en-US',
        name: 'English',
        file: 'en-US.js',
      },
      {
        code: 'es',
        iso: 'es-AR',
        name: 'Español',
        file: 'es-AR.js',
      },
      {
        code: 'zh',
        iso: 'zh-CN',
        name: 'Chinese',
        file: 'zh-CN.js',
      },
    ],
    lazy: true,
    defaultLocale: 'en',
    strategy: 'prefix_except_default',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_locale',
      alwaysRedirect: true,
      fallbackLocale: 'en',
    },
  },
```

**Questions**

1. Although I have defined three locales which are **en**, **es**, and **zh**, it is also generating locales for **fr**, **it**, and **de** which I had never specified

<img width="1521" alt="image" src="https://github.com/nuxt-modules/i18n/assets/7152955/4f143620-3e4b-43ef-8b9b-ab234024ff90">

2. When I access **localhost:3000** the first time it shows in English by default, if I manually add in the URL **localhost:3000/es** it changes to Spanish locale but if I close the page and reopen it goes back to the default which is English

How can I do that when someone manually changes the URL or access from a URL which already contains a different locale from the one you have in the cookie it saves this new locale, should I use a middleware? And if so, how?

3. When defining custom routes using for example Japanese or Chinese characters the build breaks since it says the URL is not encoded, is there any way to use them without breaking the encode?

```
defineI18nRoute({
  paths: {
    en: '/about-us',
    es: '/acerca',
    jp: '/について',
  },
})
```

Thank you for the help!

**Comment by kazupon** [comment]
close due to in-activity.
if you are having still issue, please you would open as new issue.
thank you!
