### ISSUE TITLE
Could not resolve module "@intlify/vue-router-bridge/lib/index.mjs" when using `npm`

### ISSUE THREAD

**Issue by BobbieGoede** [nuxt-modules/i18n#2556]
### Environment

with deps 

```json
"@nuxt/devtools": "latest",
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@^8.0.0-rc.5-28322235.b889e39",
"nuxt": "^3.8.1",
"vue": "^3.3.8",
"vue-router": "^4.2.5"
```

### Reproduction

https://github.com/metkm/test

### Describe the bug

Installing the module using `npm` and running will result in the following error
```bash
Could not resolve module "@intlify/vue-router-bridge/lib/index.mjs"
```

Users need to install `@intlify/vue-router-bridge`, `@intlify/vue-i18n-bridge` and `vue-i18n-routing` as dev dependencies to get around this issue. So workaround is to run: `npm i -D @intlify/vue-router-bridge @intlify/vue-i18n-bridge vue-i18n-routing`.

### Additional context

* This issue was mentioned in #2490
* Related https://github.com/nuxt/nuxt/issues/15721

**Comment by Domenys** [comment]
In fact, if I understand correctly, it is the Edge Release Channel that is the problem.
If npm install runs a clean install, without existing `node_modules` and `package-lock.json,` then the `"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"` dependency does not install the entire module and does not download all files.
For example, the core-base folder.
If you install it first:
`npm install @nuxtjs/i18n@next --save-dev`
And then replace in nuxt.config.js according to the instructions:
`{
  "devDependencies": {
-- "@nuxtjs/i18n":"^8.0.0.0-rc.1"
++ "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
  }
}`
Next, delete `package-lock.json` ( `node_modules` should remain) and run npm install.
Everything should work now.

**Comment by BobbieGoede** [comment]
~~Can you check if you're experiencing this issue if you have `vue` and `vue-router` installed as dev dependencies?~~

Nevermind, so far only `npm i -D @intlify/vue-router-bridge @intlify/vue-i18n-bridge vue-i18n-routing` seems to work when using `npm`

**Comment by padinko** [comment]
i see the problem:
`vue-i18n-routing` requires `"vue-demi": "^0.14.5"` and `"@intlify/vue-router-bridge": "^1.0.1"`
but `@intlify/vue-router-bridge` requires `"vue-demi": "^0.13.5"`

in npm `^` means: update until first non zero version number will change; so with package with zero major (first) version only patch (third) version can update
it means this 2 packages wants incompatible versions, NPM's best tree will then install `@intlify/vue-router-bridge` as submodule of `vue-i18n-routing` so there will be no conflict.. but then start the problem, because npm can not find `@intlify/vue-router-bridge` in root modules

some solutions for me:
 - if `vue-demi` will be stable in zero major version, both package should use `~` instead of `^`.. this will tale npm, that only major (first) version can not change in update, and then `~0.14.5` and `~0.13.5` will be compatible
_or_
 - if it's possible `@intlify/vue-router-bridge` should update to 0.14 and `vue-i18n-routing` will always use the same version
_or_
 - `vue-i18n-routing` should downgrade to 0.13 to be compatible with `@intlify/vue-router-bridge`, because it is using it

for now, we can add this packages to root dependencie, to fix this (npm will show error in dependencies because 2 root packages wants 2 different version of same package) but it works
`npm i -D @intlify/vue-router-bridge vue-i18n-routing`

**Comment by BobbieGoede** [comment]
You may be right, will check if we can sync `vue-demi` across these dependencies to a similar version and see if we can keep them compatible in the long term. While trying to figure out the version syntax this I found this [semver calculator](https://semver.npmjs.com/) quite useful. 

I'll check if both dependencies are compatible with the latest `vue-demi` version `0.14.6`, judging by its release and commit history it seems breaking changes basically never happen (only 1 breaking commit in 2021), so perhaps both dependencies can be set to use `>=0.14.6`? Or maybe `>=0.13.5` would be more lenient..

**Comment by padinko** [comment]
> both dependencies can be set to use `>=0.14.6`? Or maybe `>=0.13.5` would be more lenient..

i do not recommend use `>=`
it will allow to update major version, which is most of time breaking

maybe better use will be `>=0.13.5 < 1.0.0`

**Comment by BobbieGoede** [comment]
Agree, that would be a bit safer, I've changed the PRs to set it to `>=0.13.5 < 1.0.0`

**Comment by LisukiBoehm** [comment]
works with nuxtjs/i18n versions 8.0.0-rc.1, 8.0.0-rc.2, 8.0.0-rc.3, 8.0.0-rc.4, and 8.0.0-rc.5

**Comment by BobbieGoede** [comment]
Just merged #2583, can you check if you're still experiencing this issue using the latest edge release? `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`

**Comment by erikuit** [comment]
Solved it for me!

**Comment by AloisSeckar** [comment]
It looks good using edge for me as well - https://github.com/AloisSeckar/WBSC-Scoring

Thanks for fixing

**Comment by AloisSeckar** [comment]
> Just merged #2583, can you check if you're still experiencing this issue using the latest edge release? `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`

After applying the command from your post I now see version `8.0.0-rc.6-28361712.0bc7eea` in my `package-lock,json` 

It works, but I had to delete `node_modules` and `package-lock.json` and do a fresh `npm install` first. Updating to edge version alone didn't help.

**Comment by BobbieGoede** [comment]
Happy to hear it's working! I just merged #2593 as well which should prevent these dependencies from being installed further nested, will probably publish `rc.7` soon which includes these fixes.

>It works, but I had to delete node_modules and package-lock.json and do a fresh npm install first. Updating to edge version alone didn't help.

I forgot to mention this, this may be necessary for `rc.7` as well for those still getting this error.

**Comment by BobbieGoede** [comment]
Closing as the fixes are now released in https://github.com/nuxt-modules/i18n/releases/tag/v8.0.0-rc.7!

If you're running into this with `rc.7`, try deleting node_modules and lockfiles and installing again. If you're still running into this issue after that, let me know and I will reopen this issue.

**Comment by Tofandel** [comment]
I still have the same issue with `"@nuxtjs/i18n": "8.0.0-rc.7"` :(

Tried deleting the `package-lock.json` and `node_modules`  but still I have to install `npm i -D @intlify/vue-router-bridge @intlify/vue-i18n-bridge vue-i18n-routing` otherwise the issue happens

**Comment by BobbieGoede** [comment]
@Tofandel 
Sorry to hear that, could you provide a minimal reproduction?

**Comment by LisukiBoehm** [comment]
> I still have the same issue with `"@nuxtjs/i18n": "8.0.0-rc.7"` :(
> 
> Tried deleting the `package-lock.json` and `node_modules` but still I have to install `npm i -D @intlify/vue-router-bridge @intlify/vue-i18n-bridge vue-i18n-routing` otherwise the issue happens

@Tofandel 
For me, it worked like this: having the following in package.json:
```
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
    "@nuxtjs/i18n-edge": "npm:@nuxtjs/i18n-edge@^8.0.0-rc.7",
```
with a new npm it started working again :)

**Comment by gbyesiltas** [comment]
I'm having this issue on the non-edge `8.0.0` version :/

**Comment by BobbieGoede** [comment]
@gbyesiltas 
Can you provide a reproduction? Also have your tried deleting node_modules and lockfiles and installing again?

**Comment by gbyesiltas** [comment]
> @gbyesiltas Can you provide a reproduction? Also have your tried deleting node_modules and lockfiles and installing again?

Yes, I have tried deleting the node_modules and the lock files. I will add a reproduction when I have the chance, thanks for the quick reply :)

**Comment by gbyesiltas** [comment]
Update: I had `vue-i18n-routing` as a dependency myself at my `devDependencies` and was using to import the `STRATEGIES` enum. Removing that fixed the issue for me :) Just using the strings for the strategies from [here](https://i18n.nuxtjs.org/guide/routing-strategies#prefix_except_default) now :)
