### ISSUE TITLE
Unresolved function or method $t() 

### ISSUE THREAD

**Issue by filippodicostanzo** [nuxt-modules/i18n#2560]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      devtools, css, modules, i18n, swiper, postcss, build
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5, nuxt-swiper@1.2.2
- Build Modules:    -

### Reproduction

After initiating a new Nuxt.js project and installing the @nuxtjs/i18n module, an issue arises. When attempting to use the $t() function for string translation, PhpStorm displays a warning:

<img width="518" alt="image" src="https://github.com/nuxt-modules/i18n/assets/19286012/901cc1ab-9895-41ca-a01d-036877f4a0d9">

Steps to Reproduce

1. Start a new Nuxt.js project.
2. Install the @nuxtjs/i18n module.
3. Implement the $t() function in the code for string translation.
4. Observe the warning in PhpStorm.

### Expected Behavior
The $t() function, provided by the @nuxtjs/i18n module for internationalization, should be recognized by PhpStorm without any warnings.

### Describe the bug

In phpstorm 2023.1.3, after started a new project and after installed @nuxtjs/i18n, when i write the function $t() to translate the string, the ide return this warning: Unresolved function or method $t()

How can this issue be resolved? Any guidance or suggestions to address this warning in PhpStorm would be greatly appreciated.

**Comment by kazupon** [comment]
close due to in-activity.
if you are having still issue, please you would open as new issue.
thanks!
