### ISSUE TITLE
`t` function from `useI18n` doesn't reactively change whithin `app.vue`

### ISSUE THREAD

**Issue by muhammadmahmoud98** [nuxt-modules/i18n#2561]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-zgsnon?file=app.vue

### Describe the bug

In `app.vue`, when you define a localized variable in `<script>` with `t` from `useI18n`. That variable doesn't get translated when locale change. However, if it's used in a page that get's called in app.vue it works as expected.

In the reproduction above, open App.vue and you'll find I'm using the `t` from `useI18n()` following snippet 4 times in a page, component, in the template directly, and in the template with a variable defined in script setup.

Change the locale using the lang switcher at the top. You'll notice the following lines works (content gets translated when you change the locale)
```vue
<script>
const { t } = useI18n(); 
</script>

<template>
	<!-- Page. Works -->
	<NuxtPage />

	<!-- Using t (not $t) in template works -->
	<h1>{{ t('hello') }}</h1>
</template>
```

But the following two lines doesn't get translated and need to hard refresh the page.
```vue
<script>
const { t } = useI18n(); 
const hello = t('hello')
</script>

<template>
  <!-- Same index page content but wrapped in a component. Doesn't work -->
  <IndexButComponent />

  <!-- Same index page content but Inline. Doesn't work  -->
  <h1>{{ hello }}</h1>
</template>
```

### Additional context

The error also reproduces when using the same setup inside a layout then calling that layout inside app.vue eg.

```vue
// App.vue
<template>
  <NuxtLayout>
	<NuxtPage />
  </NuxtLayout>
</template>
```

**Comment by schneider-carlo** [comment]
Hi @muhammadmahmoud98, it is working like it should. With the code `const hello = t('hello')` you created a not reactive variable. If you want to create a variable which reacts to changes from the `t` composable, you can for example wrap it in a computed like this: `const hello = computed(() => t('hello'))`. 
I hope this helps you.

**Comment by muhammadmahmoud98** [comment]
@schneider-carlo Thanks for replying, I'm using the same method without a computed inside the page and it does work. Why does it stays reactive in the page and it does not in app.vue? That's what confuses me

**Comment by schneider-carlo** [comment]
@muhammadmahmoud98 Because the script tag in app.vue gets executed once and the script tags of the files in the pages directory get executed every time when the page changes, for example through clicking on a NuxtLink component.

**Comment by muhammadmahmoud98** [comment]
@schneider-carlo This is nice to learn. Thanks a lot I really appreciate your help 🙏

**Comment by schneider-carlo** [comment]
@muhammadmahmoud98 I'm glad I could help you. :)

**Comment by BobbieGoede** [comment]
Looks like this has been resolved already, thanks @schneider-carlo for helping out! 😄

**Comment by sneakylenny** [comment]
Wouldn't this be easier when allowing an export that wraps it in a computed for you?

For example: 

```ts
const { ct } = useI18n() // "ct" is an example name that could stand for "Computed Translation"

const hello = ct('hello') // Returns computed: `computed(() => t(key))`

console.log(hello.value) // Hello | Hola | Bonjour
```

React "👍" if interested

⬇️
