### ISSUE TITLE
Issue after upgrading

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt-modules/i18n#2567]
### Environment

Broken
------------------------------
- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@8.11.0
- Builder:          -
- User Config:      telemetry, sourcemap, vue, app, runtimeConfig, nitro, css, modules, ssh, env, cors, pinia, i18n, build, legacy, devtools, imports, typescript
- Runtime Modules:  @vueuse/nuxt@10.5.0, @nuxtjs/i18n@8.0.0-rc.5, @pinia/nuxt@0.4.11, nuxt-icon@0.5.0, @unocss/nuxt@0.56.5, nuxt-vite-legacy@1.0.1
- Build Modules:    -
------------------------------

Working

------------------------------
- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@8.11.0
- Builder:          -
- User Config:      telemetry, sourcemap, vue, app, runtimeConfig, nitro, css, modules, ssh, env, cors, pinia, i18n, build, legacy, devtools, imports, typescript
- Runtime Modules:  @vueuse/nuxt@10.5.0, @nuxtjs/i18n@8.0.0-rc.5-28283121.8a33fec, @pinia/nuxt@0.4.11, nuxt-icon@0.5.0, @unocss/nuxt@0.56.5, nuxt-vite-legacy@1.0.1
- Build Modules:    -
------------------------------

### Reproduction

Unfortunately I can't offer a reproduction here as my project is too large

### Describe the bug

After upgrading to Nuxt 3.8.2 I'm getting the following error when trying to render a page.
```
@nuxtjs/i18n Failed locale loading: [GET] "/n/api/translate/en": <no response> Response is not defined
```

I can confirm that this only happens after upgrading Nuxt and no other changes
What's bizarre is it seems to be server side only that is failing to get the translations, when the client hydrates it calls the translate endpoint listed above and gets the translations successfully.
Manually visiting the endpoint also returns a full list of translations so I'm not sure why the $fetch call is failing on the server

I suspect this is something to do with the data fetching changes that was introduced in Nuxt 3.8.2 and Nitro 2.7.0 and node 16.16.0 but I'm not sure

If there's anyway I can help you guys get more information please let me know as this is stopping me from upgrading Nuxt. 

### Additional context

Simplified example of one of my locale files

```
export default defineI18nLocale(async (locale) => {
    // Get translations from the API
  const translations = await $fetch(`/api/translate/${locale}`)

  return translations
})
```

**Comment by BobbieGoede** [comment]
I'm not able to reproduce this issue but I have a hunch this may be caused by you using node 16, which has reached end-of-life since September this year. Could you check if updating to node 18 or higher resolves this issue?

**Comment by kazupon** [comment]
close in-activity.
If you have still issue, you can open as new issue.
Thanks!
