### ISSUE TITLE
disable localized routes

### ISSUE THREAD

**Issue by djixadin** [nuxt-modules/i18n#2571]
### Environment

Working directory: /home/projects/nuxt-starter-ywb6cr                                                           2:15:02 PM
Nuxt project info:                                                                                              2:15:02 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ywb6cr?file=nuxt.config.ts

### Describe the bug

im expecting that links with false set in pages object couldn't be navigated to.

### Additional context

Not sure if im doing something wrong in my implementation but changing the locale variable im able to click on the link or visit it via url bar but i shouldn't be able to do that if the locale is pt right?

**Comment by kazupon** [comment]
Thank you for your reporting!

Sorry, I could not understand this issue.
Cloud you give us more your explanation of your issue, please? 🙏

**Comment by djixadin** [comment]
Im able to navigate to the login page even if the login page is set to false in the pages object. shouldnt setting that to false disable that route for that locale ?

**Comment by djixadin** [comment]
anyway it seems that this is fixed in latest v8.0.0 release.. you can close this if you want.
