### ISSUE TITLE
Error while installing 8.0.0-rc.6

### ISSUE THREAD

**Issue by FlorianWerndl** [nuxt-modules/i18n#2585]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `-`
- User Config:      `srcDir`, `runtimeConfig`, `devtools`, `typescript`, `modules`, `i18n`, `tailwindcss`, `postcss`, `css`, `vite`, `app`, `build`
- Runtime Modules:  `@pinia/nuxt@0.5.1`, `@nuxtjs/i18n@8.0.0-rc.5`, `@vueuse/nuxt@10.6.1`, `@nuxtjs/tailwindcss@6.10.1`, `@nuxtjs/fontaine@0.4.1`, `@samk-dev/nuxt-vcalendar@1.0.2`, `nuxt-lazy-hydrate@1.0.0`, `nuxt-viewport@2.0.6`
- Build Modules:    `-`

### Reproduction

Does not happen here: 
https://stackblitz.com/edit/github-nmzxu4?file=package.json

### Describe the bug

While upgrading from `8.0.0-rc.5` to `8.0.0-rc.6` I experienced the following error

<img width="603" alt="Bildschirmfoto 2023-12-01 um 15 17 03" src="https://github.com/nuxt-modules/i18n/assets/2530954/27ad595b-3f22-4a76-bbc1-d5dbd69b5db0">

If I use `npm install @nuxtjs/i18n@next --save-dev` the same error happens after starting the server

<img width="721" alt="Bildschirmfoto 2023-12-01 um 15 25 13" src="https://github.com/nuxt-modules/i18n/assets/2530954/70449485-4130-4bc4-9143-4ae2985879a2">

**Comment by BobbieGoede** [comment]
We're tracking this issue here https://github.com/nuxt-modules/i18n/issues/2556
