### ISSUE TITLE
Enable type checking from vue-i18n

### ISSUE THREAD

**Issue by dreitzner** [nuxt-modules/i18n#2591]
### Describe the feature

vue-i18n supports type safe resource Schemas. ([docs](https://vue-i18n.intlify.dev/guide/advanced/typescript.html))

It would be nice to have a way to do the same in nuxt-i18n as well.

From what I can gleen from the source code it might only be needed to add a possible type type to `defineNuxtPlugin` that is passed to `createI18n`.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danwithabox** [comment]
For people who want type-safety out-of-the-box without waiting for this, I have successfully used [global resource schema type definitions](https://vue-i18n.intlify.dev/guide/advanced/typescript#global-resource-schema-type-definition) as a workaround.

**Comment by adamdehaven** [comment]
I'm willing to contribute, but might need an assist: https://github.com/nuxt-modules/i18n/issues/1753#issuecomment-2146330404

**Comment by thomaslecoeur** [comment]
> For people who want type-safety out-of-the-box without waiting for this, I have successfully used [global resource schema type definitions](https://vue-i18n.intlify.dev/guide/advanced/typescript#global-resource-schema-type-definition) as a workaround.

Any details on the implementation? Can we reproduce on a vanilla nuxt project?

**Comment by BobbieGoede** [comment]
The latest v9 release candidate (https://github.com/nuxt-modules/i18n/releases/tag/v9.0.0-rc.2) includes experimental `vue-i18n` options and messages generation, this provides autocompletion for configuring options and translation functions, please try it out and let me know if this works as expected 🙏

More on the option that enables this functionality: https://i18n.nuxtjs.org/docs/v9/options/misc#experimentaltypedoptionsandmessages, the 
PR implementing this has a demo video of it in action https://github.com/nuxt-modules/i18n/pull/3151

**Comment by BobbieGoede** [comment]
Closing this as we have experimental support for this in the stable release of v9, please try it out and let me know your thoughts!
