### ISSUE TITLE
Nuxt3 - v8 RC - fallbackLocale option in the `nuxt.config.ts` doesn't accept `object`

### ISSUE THREAD

**Issue by FabianoLothor** [nuxt-modules/i18n#2594]
### Describe the feature

I'd like to get backwards compatibility for the `fallbackLocale` property.

The decision to require to create a new file with the `vueI18n` options is sad.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by kazupon** [comment]
Thank you for your feedback!

Here is why we changed the `vueI18n` option to its own config.
https://v8.i18n.nuxtjs.org/guide/migrating#deprecated-vuei18n-option-to-not-accept-createi18n-options

We do our best effort to make major upgrades without breakinig changes. However, major upgrades of nuxt and vue-i18n are sometimes affected by the architecture and require changes.
We appreciate your understanding.

Thank you!
