### ISSUE TITLE
lazy: true not working 

### ISSUE THREAD

**Issue by freezyh** [nuxt-modules/i18n#2601]
### Environment

Node: 20.5.0
Nuxt: 3.8.2
@nuxtjs/i18n: ^8.0.0-rc.7

### Reproduction

 https://stackblitz.com/edit/nuxt-starter-s3cdz5?file=nuxt.config.ts

### Describe the bug

I use @nuxtjs/i18n, set the option lazy: true  not working and option detectBrowserLanguage is not work, and show error tips, if I set lazy: false, I switch language it works
![97DBB052-4E71-4687-85E6-AAF423F7FCC1](https://github.com/nuxt-modules/i18n/assets/26577708/edffc439-b30a-4cda-8e35-8dcee1440c6f)

**Comment by BobbieGoede** [comment]
Hmm I suppose it's possible to change `locale` in this way when you're using `vue-i18n`, but for `@nuxtjs/i18n` to be able to detect a locale change I recommend using `setLocale` instead (or `switchLocalePath` but that wouldn't work in combination with `'no_prefix'` strategy). 

I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/nuxt-starter-byzynb?file=pages%2Findex.vue), when switching using  `setLocale` everything should work as you expect.

**Comment by freezyh** [comment]
> Hmm I suppose it's possible to change `locale` in this way when you're using `vue-i18n`, but for `@nuxtjs/i18n` to be able to detect a locale change I recommend using `setLocale` instead (or `switchLocalePath` but that wouldn't work in combination with `'no_prefix'` strategy).
> 
> I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/nuxt-starter-byzynb?file=pages%2Findex.vue), when switching using `setLocale` everything should work as you expect.

Thank you very much! It works，and I want to know more about nuxt/i18n options diffrent vue/i18n options, the nuxt/i18n document should provide more information  ?

**Comment by BobbieGoede** [comment]
Closing this as the issue has been resolved 😅..

>Thank you very much! It works，and I want to know more about nuxt/i18n options diffrent vue/i18n options, the nuxt/i18n document should provide more information ?

We're going to work on improving docs on this in the coming months, hopefully it will clear up some things!
