### ISSUE TITLE
eslint flat configurations

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#2607]
### background
It will come flat config at eslint v9
- https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/
- https://eslint.org/blog/2023/10/flat-config-rollout-plans/

### Migration references
- ESLint's new config system, Part 2: Introduction to flat config:
  - https://eslint.org/blog/2022/08/new-config-system-part-2/

### Real world references
- https://github.com/kazupon/unplugin-time-stat/blob/main/eslint.config.js

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [ ] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by MuhammadM1998** [comment]
You want to migrate this file ? https://github.com/nuxt-modules/i18n/blob/main/.eslintrc.cjs
This seems straight forward to do, I think using https://github.com/antfu/eslint-config with ~5 lines would do it.

I can take a try in it but how to benchmark the new PR against the current behavior? and is it ok to use antfu's package or do you want to use eslint directly

**Comment by kazupon** [comment]
Thank you for your interest!

> I can take a try in it but how to benchmark the new PR against the current behavior? 

You can migrate to flat configuration of nuxt i18n
Just migrate!

We are always waiting for your PR. :)

**Comment by MuhammadM1998** [comment]
Thanks! I'll take a try on it at the weekend

**Comment by kazupon** [comment]
already fixed with #2622
so close.

Thank @MuhammadM1998 for your contribution!
