### ISSUE TITLE
Nuxt i18n config type issue

### ISSUE THREAD

**Issue by VladimirFrunza** [nuxt-modules/i18n#2628]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@9.6.1`
- Builder:          `-`
- User Config:      `devtools`, `typescript`, `ssr`, `devServer`, `runtimeConfig`, `css`, `modules`, `i18n`
- Runtime Modules:  `@pinia/nuxt@0.5.1`, `@vueuse/nuxt@10.7.0`, `@nuxtjs/i18n@8.0.0-rc.11`
- Build Modules:    `-`

### Reproduction

Always

### Describe the bug

<img width="900" alt="Screenshot 2023-12-19 at 19 05 01" src="https://github.com/nuxt-modules/i18n/assets/28590473/095b9b6e-5971-4c8f-bfe4-490e05427fd0">
Type of file should be string or array with specific keys. code, file, cache... etc

**Comment by BobbieGoede** [comment]
Thanks for reporting! I'm working on fixing this but it will take a while, in the meantime I believe using a `files`  array instead of `file` should resolve this type issue as a workaround.
