### ISSUE TITLE
defineI18nLocaleDetector not  being exported by the module?

### ISSUE THREAD

**Issue by KarelVendla** [nuxt-modules/i18n#2633]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, app, css, i18n, modules, runtimeConfig
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.11, nuxt-icon@0.6.7, @nuxt/test-utils/module@3.9.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-szws5d?file=localeDetector.ts

### Describe the bug

The defineI18nLocaleDetector is not importable:
import { defineI18nLocaleDetector } from '#i18n'
but other composables are.
To me it seems that the server.mjs is not is not exported from index.mjs that's why it's not accessible? Otherwise it seems that the i18n module does not export the server.mjs contents at all.

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

server-side translations is experimental feature currently.
so, you need to configure `experimental.localeDetector` on nuxt config.
you can read docs
https://i18n.nuxtjs.org/guide/server-side-translations

**Comment by kazupon** [comment]
if you will configure it, you need to run the `npx nuxi prepare`.
The `defineI18nLocaleDetector` will be automatically imported.

**Comment by KarelVendla** [comment]
So if I follow the guide:
Create the localeDector.ts,
Link it to nuxt config ts
run npx nuxi prepare

then can i expect the locale to be what i set in the url (for example: locale=de) and my  translations to be applied based on the locale that is set?
