### ISSUE TITLE
nuxt2 add @nuxtjs/i18n@7x and run, throw error

### ISSUE THREAD

**Issue by alaxcc** [nuxt-modules/i18n#2638]
### Environment

 "dependencies": {
    "@ispa.io/vrcode": "^1.5.0",
    "@nuxtjs/axios": "^5.8.0",
    "@nuxtjs/proxy": "^1.3.3",
    "@nuxtjs/style-resources": "^1.0.0",
    "better-scroll": "^1.15.2",
    "echarts": "^5.3.3",
    "element-ui": "^2.15.8",
    "js-base64": "^2.5.1",
    "js-cookie": "^2.2.1",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "lockr": "^0.8.5",
    "nuxt": "^2.14.6",
    "remixicon": "^2.3.0",
    "vue-currency-input": "^1.8.4",
    "vue-echarts": "^6.2.1",
    "vue-quill-editor": "^3.0.6",
    "vue2-editor": "^2.10.3"
  },
  "devDependencies": {
    "@nuxtjs/composition-api": "^0.32.0",
    "@nuxtjs/date-fns": "^1.5.0",
    "@nuxtjs/device": "^2.1.0",
    "@nuxtjs/eslint-config": "^2.0.2",
    "@nuxtjs/eslint-module": "^1.0.0",
    "@nuxtjs/i18n": "7.3.1",
    "babel-eslint": "^10.1.0",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.1",
    "eslint-config-standard": "^14.1.1",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": "^23.8.2",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-nuxt": "^0.5.2",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "nodemon": "^2.0.2",
    "prettier": "^2.0.2",
    "sass": "1.56.1",
    "sass-loader": "^10.0.1"
  }

### Reproduction

pnpm add  @nuxtjs/i18n@7x

pnpm run prod

### Describe the bug

 FATAL                                                                                                        17:29:23

Vue packages version mismatch:

- vue@2.6.14
- vue-server-renderer@2.7.16

This may cause things to work incorrectly. Make sure to use the same version for both.

  Vue packages version mismatch:

  - vue@2.6.14
  - vue-server-renderer@2.7.16

  This may cause things to work incorrectly. Make sure to use the same version for both.

  at Object.<anonymous> (node_modules\.pnpm\vue-server-renderer@2.7.16\node_modules\vue-server-renderer\index.js:8:9)
  at Module._compile (node:internal/modules/cjs/loader:1256:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
  at Module.load (node:internal/modules/cjs/loader:1119:32)
  at Module._load (node:internal/modules/cjs/loader:960:12)
  at Module.require (node:internal/modules/cjs/loader:1143:19)
  at require (node:internal/modules/cjs/helpers:119:18)
  at Object.<anonymous> (node_modules\.pnpm\@nuxt+vue-renderer@2.17.2\node_modules\@nuxt\vue-renderer\dist\vue-renderer.js:17:27)
  at Module._compile (node:internal/modules/cjs/loader:1256:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

   ╭────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                            │
   │   ✖ Nuxt Fatal Error                                                                       │
   │                                                                                            │
   │   Error:                                                                                   │
   │                                                                                            │
   │   Vue packages version mismatch:                                                           │
   │                                                                                            │
   │   - vue@2.6.14                                                                             │
   │   - vue-server-renderer@2.7.16                                                             │
   │                                                                                            │
   │   This may cause things to work incorrectly. Make sure to use the same version for both.   │
   │                                                                                            │
   │                                                                                            │
   ╰────────────────────────────────────────────────────────────────────────────────────────────╯

 ELIFECYCLE  Command failed with exit code 1.

**Comment by kazupon** [comment]
Thank you for your reporting.

> Vue packages version mismatch:
> 
> * vue@2.6.14
> * vue-server-renderer@2.7.16
> 
> This may cause things to work incorrectly. Make sure to use the same version for both.
> 
> Vue packages version mismatch:
> 
> * vue@2.6.14
> * vue-server-renderer@2.7.16
> 
> This may cause things to work incorrectly. Make sure to use the same version for both.

The error said, you need to match the Vue version.
That is not issue of nuxt i18n

close.
