### ISSUE TITLE
Server-side Translations

### ISSUE THREAD

**Issue by kantum** [nuxt-modules/i18n#2643]
### Describe the feature

I'll like to translate the mail I send depending on user's browser setup, I followed the [documentation here](https://i18n.nuxtjs.org/guide/server-side-translations), but I get the following:

```
[nuxt] [request error] [unhandled] [500] useTranslation is not defined
  at <anonymous> (./server/api/mail.post.ts:36:1)
  at ./node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1610:47
  at async Object.handler (./node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1675:19)
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1885:7)
  ```

I defined the localDetector as prescribed in the documentation (copy paste) and added the path of my localDetector in my nuxt.config.ts:

```
    [
      '@nuxtjs/i18n',
      {
        locales: [
          { code: 'en', iso: 'en-US', file: 'en.json' },
          { code: 'fr', iso: 'fr-FR', file: 'fr.json' },
        ],
        langDir: 'i18n/',
        defaultLocale: 'en',
        detectBrowserLanguage: {
          useCookie: true,
          cookieKey: 'i18n_redirected',
          redirectOn: 'root', // recommended
          alwaysRedirect: true,
        },
        experimental: {
          localeDetector: './utils/localeDetector.ts',
        },
      },
    ],
```

Then I simply do:
```
export default defineEventHandler(async (event) => {
  const t = await useTranslation(event);
  console.log(t('hello'));
  ...
```

The module is in my dev dependencies, maybe it has to be in the normal dependencies? But then all its dependencies also...
```
  "devDependencies": {
    ...
    "@nuxtjs/i18n": "^8.0.0",
    ...
  }
```

I tried with`v8.0.0-rc.8` with no chance, useTranslation is still not defined.

I also tried to import it explicitly, but without anything being imported in the documentation, I don't know if I'm doing it right.

```
import { useTranslation } from '#imports';
--> ERROR  Error: [unimport] failed to find "useTranslation" imported from "#imports"
```
```
import { useTranslation } from '@nuxtjs/i18n';
--> ERROR  RollupError: "useTranslation" is not exported by "node_modules/.pnpm/@nuxtjs+i18n@8.0.0-rc.8_vue@3.4.3/node_modules/@nuxtjs/i18n/dist/module.mjs", imported by "server/api/mail.post.ts".    
```

It looks to me that the documentation either omits something or is outdated, or maybe I'm missing something so obvious it's not in the doc...

Does anyone have succeeded to use server-side translation yet?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by KarelVendla** [comment]
Can I ask. Is the LocaleDetector actually working for you? Does it change the locale? It does not  seem to update the locale for me if I just follow the docs.

**Comment by kantum** [comment]
I made a [reproduction](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-joukd6?file=pages%2Findex.vue), and it worked directly 😅 I think I made a typo in the `experimental.localeDetector` in `nuxt.config.ts`.

The localeDetector is actually getting the locale with the header, so it will use the browser's locale.
