### ISSUE TITLE
Falllback locale not working when the key path is not incomplete exist in current locale data

### ISSUE THREAD

**Issue by everyx** [nuxt-modules/i18n#2644]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-dwhr3q?file=pages%2Findex.vue

### Describe the bug

When I set default `en` locale message as below:

```json
{
	"deep": {
		"hello": {
			"world": "Test"
		}
	}
}
```

and another `es` locale message as below:

```json
{
	"deep": {
		"hello":  null
	}
}
```

I use `tm` and `rt` to get and display this message

```typescript
<script lang="ts" setup>
const { tm, rt } = useI18n({ useScope: 'global' });
const test = tm('deep.hello.world');
</script>
<template>
  <div>
    <h1>Nuxt I18n Starter - {{ $t('hello') }}!</h1>
    <p>{{ rt(test) }}</p>
  </div>
</template>
```

Then if I switch locale from `en` to `es`, I get error `last is null` and can not fallback to 'en' message.

I also tried vue-i18n and there was no such problem. For an example, see https://stackblitz.com/edit/vitejs-vite-asteuw?file=src%2FApp.vue

**Comment by BobbieGoede** [comment]
This doesn't work in vue-i18n either, it seems like your vue-i18n reproduction silently fails. If you set the locale to `'ja'` and the fallbackLocale to `'en'` it will error on load. I have edited your reproduction to demonstrate [here](https://stackblitz.com/edit/vitejs-vite-zkwein?file=src%2Fmain.ts), if you expect this behavior to work I suggest opening an issue on repo of vue-i18n.

**Comment by everyx** [comment]
@BobbieGoede  just created a issue in upstream, thanks https://github.com/intlify/vue-i18n-next/issues/1702
