### ISSUE TITLE
Using the t method in computed will trigger a [Vue warn]: getCurrentInstance() called inside a computed getter.

### ISSUE THREAD

**Issue by Red-Asuka** [nuxt-modules/i18n#2675]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.3.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.0
- Builder:          -
- User Config:      devtools, app, runtimeConfig, modules, i18n, site, plugins, css, postcss, vite, typescript, nitro, build, hooks
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.4, @vueuse/nuxt@10.7.1, @nuxtjs/i18n@8.0.0, @pinia/nuxt@0.5.1, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxt/image@1.0.0-rc.1, @nuxtjs/sitemap@5.0.1, @nuxt/content@2.10.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-y149ef?file=app.vue

### Describe the bug

As long as the t method is used in computed, this warning will appear.

### Logs

```shell
[Vue warn]: getCurrentInstance() called inside a computed getter. This is incorrect usage as computed getters are not guaranteed to be executed with an active component instance. If you are using a composable inside a computed getter, move it ouside to the setup scope.
```

**Comment by DouglasAR01** [comment]
I'm having the same issue

**Comment by WooHoo-Wu** [comment]
me too...

**Comment by BobbieGoede** [comment]
Looks like this warning was added yesterday to Vue https://github.com/vuejs/core/commit/324e817ef8d00c091e5d1537789542241c876d66. Related discussion here https://github.com/vuejs/core/discussions/9974 (`useI18n` gets mentioned 😄) and related issue https://github.com/vuejs/core/issues/10001 and follow up issue https://github.com/vuejs/core/pull/10038.

I haven't looked into it yet, but I'm guessing the warning is triggered by something upstream in `vue-i18n`. /cc @kazupon

**Comment by BobbieGoede** [comment]
Seems like this line triggers the warning https://github.com/intlify/vue-i18n-next/blob/master/packages/vue-i18n-core/src/composer.ts#L1784

**Comment by skirtles-code** [comment]
The warning has been reverted in Vue core, https://github.com/vuejs/core/commit/2fd39057386644c8bfee426c60a51f2b07a79b09. I imagine there'll be a 3.4.7 soon to release that.

**Comment by BobbieGoede** [comment]
Looks like the usage of `getCurrentInstance()` in `vue-i18n` is fine based on this comment https://github.com/vuejs/core/discussions/9974#discussioncomment-8062127.

As the warning has been removed and the usage shouldn't trigger the warning (usage is for debugging and done safely), I'll close this issue. And as mentioned this warning should be gone after the next Vue release!

**Comment by DouglasAR01** [comment]
> Seems like this line triggers the warning https://github.com/intlify/vue-i18n-next/blob/master/packages/vue-i18n-core/src/composer.ts#L1784

I supposed so. I'm using computed properties to easily react to lang switches in some components (i.e. the Navbar), I used this approach some time ago (about beta 10 iirc). I removed the computed properties to avoid the issue and it worked well, I guess that approach isn't needed anymore.
