### ISSUE TITLE
Inconsistent path encoding

### ISSUE THREAD

**Issue by BobbieGoede** [nuxt-modules/i18n#2698]
### Environment

```
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-28410629.a2a883f
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-vuphy7?file=pages%2Findex.vue

Scripts to compare behavior:
* `npm run dev`
  * strategy = no_prefix
* `npm run dev:alternate-1` 
  * strategy = prefix_and_default
* `npm run dev:alternate-2`
  * strategy = prefix_and_default
  * defaultLocale = en

### Describe the bug

The paths returned by `localePath` are escaped inconsistently as shown in the scenarios below. It seems to be related to when locale prefixes are used, hence it changes when `defaultLocale` is set or not when used with strategy `prefix_and_default`. Found during https://github.com/nuxt-modules/i18n/pull/2686.

This issue is likely related or the same as previously reported issues related to path encoding .

```ts
strategy: "no_prefix"
defaultLocale: "undefined"
localePath: "/path/hello%20world?foo=hello+world"
```

```ts
strategy: "prefix_and_default"
defaultLocale: "undefined"
localePath: "/en/path/hello world?foo=hello+world"
```

```ts
strategy: "prefix_and_default"
defaultLocale: "en"
localePath: "/path/hello%20world?foo=hello+world"
```

**Comment by mcombes-ew** [comment]
I am having a similar issue with Nuxt 3.

As an example: if I navigate to a page like the link below everything works as intended. 

             mysite.net/somePath/some%20%26%20path

But if there is any query string at the end it decodes the %26 to an & like example below.

             mysite.net/somePath/some%20%26%20path?queryString=true

gets decoded to 
             mysite.net/somePath/some%20&%20path?queryString=true
             
Can not figure out why this is happening.

**Comment by Red-Asuka** [comment]
I have the same issue, if the URL contains a query, and the value of the query is encoded, after using localePath, the value of the query will be encoded multiple times.

```js
localePath({ path: '/signin', query: { continue: `https://www.example.com/` } }) 
// /signin?continue=https://www.example.com/

localePath({ path: '/signin', query: { continue: encodeURIComponent(`https://www.example.com/`) } })
// /signin?continue=https%253A%252F%252Fwww.example.com%252F
```

**Comment by BobbieGoede** [comment]
@Red-Asuka 
I believe that's consistent with Vue Router's `router.resolve` is it not?
