### ISSUE TITLE
Minor docs issue for server-side usage

### ISSUE THREAD

**Issue by hansemannn** [nuxt-modules/i18n#2715]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      app, build, colorMode, ui, runtimeConfig, devtools, i18n, googleSignIn, modules, css
- Runtime Modules:  @nuxtjs/i18n@8.0.0, @nuxt/ui@2.12.0
- Build Modules:    -
------------------------------

### Reproduction

Visit [this link](https://i18n.nuxtjs.org/guide/server-side-translations).

### Describe the bug

There are some minor translation issues.

**Comment by BobbieGoede** [comment]
Resolved by #2716
