### ISSUE TITLE
Build error when value of key is only http url

### ISSUE THREAD

**Issue by nguyenvokim** [nuxt-modules/i18n#2727]
### Environment

- Operating System: Darwin
- Node Version:     v16.12.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  npm@8.19.4
- Builder:          -
- User Config:      head, css, components, router, buildModules, modules, site, device, env, i18n, sitemap, robots, io, axios, proxy, server, serverMiddleware, googleFonts, htmlValidator, intercom, rootDir, buildDir, build, telemetry, imports
- Runtime Modules:  @nuxt/image@1.3.0, @nuxtjs/i18n@8.0.0, @nuxtjs/robots@3.0.0, @nuxtjs/google-fonts@3.1.3, @nuxtjs/device@3.1.1, nuxt3-vuex-module@1.0.14
- Build Modules:    @nuxt/typescript-build, @nuxtjs/stylelint-module

### Reproduction

If the value of a key is fully a link, it will throw the error

```
[plugin:unplugin-vue-i18n] Invalid linked format (error code: 10) in **path-to-project**/assets/lang/en.js
  target message: https://www.google.com/maps/contrib/103353472332847156387/place/ChIJsaMZ6QG5uIkR-BJEAg3EifU/@44.6194791,-45.0197211,4z/data=!4m6!1m5!8m4!1e1!2s103353472332847156387!3m1!1e1?hl=en-US&entry=ttu
  target message path: buy_cs2_skins.most_trusted_trading.review_1.link

```

### Describe the bug

Put full link on a value of a key

**Comment by kazupon** [comment]
close in-activity.
If you have still an issue, please open as new issue.

thanks!
