### ISSUE TITLE
Custom route paths doesnt work with strategy `no_prefix`

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/i18n#2729]
### Environment

```
- Operating System: Darwin
- Node Version:     v21.2.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.21
- Builder:          -
- User Config:      devtools, css, modules, i18n, image, ignore, build
- Runtime Modules:  @nuxtjs/i18n@8.0.0, @nuxt/image@1.3.0, nuxt-icon@0.6.8
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-bvgtxu?file=nuxt.config.ts

### Describe the bug

Config:
```
  i18n: {
    vueI18n: './i18n.config.ts',
    strategy: 'no_prefix',
    locales: [
      {
        code: 'de',
        iso: 'de-DE',
      },
      {
        code: 'es',
        iso: 'es-ES',
      },
    ],
    customRoutes: 'config',
    pages: {
      'my-page': {
        de: '/my-page-de',
        es: '/my-page-es',
      },
    },
  },
```

With strategy `no_prefix` we have the following bugs:

* Route `/my-page` is still available
* Route `/my-page-de` is not available
* Using `localePath({ name: 'my-page' })` returns the `/my-page` instead of `/my-page-de`

### Additional context

It works when using strategy `prefix_except_default`

**Comment by BobbieGoede** [comment]
As [documented](https://i18n.nuxtjs.org/guide/routing-strategies), the `no_prefix` strategy does not support custom paths.

**Comment by MickL** [comment]
Too bad! The use case is the following:

I have a website which currently only has one language but it already uses nuxt-i18n and is prepared to be translated in the future. Right now the correct strategy to use (if I am not wrong) would be `no_prefix` but it does not support custom paths.

When using `differentDomains: true`, shouldnt also the strategy be `no_prefix`? This would mean that different domains and custom paths dont work together, or am I wrong?

**Comment by MickL** [comment]
@BobbieGoede Do you mind answering my last question? :)

> When using `differentDomains: true`, shouldnt also the strategy be `no_prefix`? This would mean that different domains and custom paths dont work together, or am I wrong?

**Comment by BobbieGoede** [comment]
I didn't build the `differentDomains` support and I haven't used it myself, based on the docs (https://i18n.nuxtjs.org/options/domain) it looks like no prefixes will be added when using `differentDomains`, and in the code I can see a warning will be logged if `no_prefix` strategy is used at the same time (https://github.com/nuxt-modules/i18n/blob/main/src/module.ts#L117-L122).

From what I can gather from this is that `differentDomains` is a unique case in which custom paths will probably work, and that you can't use `no_prefix` strategy, though prefixes will not be added, I can only guess this is to ensure localized routes are generated (which would be skipped when using `no_prefix`).

**Comment by bezoerb** [comment]
@MickL: it is working up to version v8.2.0 when omitting the `strategy` option.

See: https://github.com/nuxt-modules/i18n/pull/2705#issuecomment-2151036409
