### ISSUE TITLE
[nuxt] A composable that requires access to the Nuxt instance...

### ISSUE THREAD

**Issue by szwenni** [nuxt-modules/i18n#2736]
### Environment

node v18.18
Nuxt 3.9.0 with Nitro 2.8.1
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@latest"

### Reproduction

https://stackblitz.com/edit/github-kvhg77-uni1e8?file=package.json

### Describe the bug

When using the latest edge release, happens since version 8.0.0-28420652.7a0a9bd, and using localRoute in a computed property which is executed very early on setup function like useHead it throws the error
`[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.`

This can easily be reproduced like seen in the code sandbox

**Comment by szwenni** [comment]
One potential fix would be
being able to pass a nuxtApp instance here
https://github.com/nuxt-modules/i18n/blob/c9bdcd7773772bff4356111ca50d4c45730bac2e/src/runtime/routing/compatibles/routing.ts#L123

and then instead of using useRouter use nuxtApp.$router
And then when calling e.g. useLocaleRoute, save the nuxtApp Instance and pass it around. It would at least prevent this in the scenario where you have useLocaleRoute() in the setup function and then use the returned function in a composable.

So this
https://github.com/nuxt-modules/i18n/blob/c9bdcd7773772bff4356111ca50d4c45730bac2e/src/runtime/composables/index.ts#L250

would be something like - quick fix pseudocode

const nuxtApp = useNuxtApp();

const router = useRouter();

return (route, locale) => {

  return localeRoute(route, locale, {router, nuxtApp})

}

This should cover 99% of the scenarios as also the docs use useLocaleRoute directly in the setup and then the returned function in the subsequent calls. I know this can be written prettier but it should give at least an idea of how it could be fixed.

**Comment by BobbieGoede** [comment]
Thanks for reporting this issue! You're right, the composables/instances used inside the composables should be called/kept during initial setup. 

I remember something didn't seem quite right while making that change but somehow the tests are not running into this issue 😅.. I'll work on a fix and add regression tests to prevent this from happening in the future 🙏
