### ISSUE TITLE
Add option to edit canonical when using setI18nParams()

### ISSUE THREAD

**Issue by martinsjek** [nuxt-modules/i18n#2745]
### Describe the feature

I would like to edit canonical tag for specific routes, like if the route is "https://test.com/test1/test2/test3?query-param=1", i would like that canonical tag is "https://test.com/test1/test2". I would be removing unnecessary query parameters and route parameters.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by BobbieGoede** [comment]
Can you give an example of when and why it would be desirable to be able to remove route parameters from the canonical tag? As far as I know canonicals should point to duplicate/identical resources.

**Comment by martinsjek** [comment]
@BobbieGoede Well It seems that this package already does what i desire. and you can close this issue.
But I will describe this with an example for next person to stumble upon this.
So you have an e-commerce site with products and variations.
So product url: /product/test-product
Product variation url: /product/test-product/variation-one

I would like to say "hey google, this variation url is the same as product url, because barely anything changes (tabs opened or anything like that)". And that's why I would like to remove "/variation-one" from canonical.

But it seems that if your component under pages is named as optional page: [[variation]].vue, then canonical automatically removes it.

**Comment by martinsjek** [comment]
@BobbieGoede It seems that actually if the page is [[variation]].vue, it does not automatically remove it. What would be the workaround to what I have described in previous comment?

**Comment by BobbieGoede** [comment]
I wasn't sure what you meant previously as parameters (optional or not) are not removed in the canonical links as you found out. 

At the moment there's no workaround for this, Google suggests using query parameters for product variants (see their recommendations [here](https://developers.google.com/search/docs/specialty/ecommerce/designing-a-url-structure-for-ecommerce-sites#how-google-understands-urls-for-product-variants)), but if using url parameters is a common pattern we could think of a way to omit parameters somehow.

**Comment by martinsjek** [comment]
@BobbieGoede Yes, it would be great if we could do that. I will wait for any updates regarding this :)

**Comment by martinsjek** [comment]
Found a workaround with @BobbieGoede help.
You can modify canonical link in a page when using `setI18nParams`.
You just need to define `useHead` AFTER `setI18nParams`.
Example:
```
setI18nParams({
  en: {
    slug: 'tests1',
  },
  lv: {
    slug: 'tests',
  },
});

useHead({
  link: [
    {
      rel: 'canonical',
      href: 'https://example.com/anything-i-want',
    },
  ],
});
```

StackBlitz with example: https://stackblitz.com/edit/github-orzjqc-bntta4?file=pages%2Findex.vue,pages%2F[productCategory]%2F[id].vue
