### ISSUE TITLE
canonicalQueries does not work

### ISSUE THREAD

**Issue by martinsjek** [nuxt-modules/i18n#2746]
### Environment

StackBlitz

### Reproduction

https://stackblitz.com/edit/github-orzjqc-6knjap?file=app.vue,pages%2F[productCategory]%2F[id].vue

### Describe the bug

If you go to route /tests/1?customer=any, the canonical tag will be:
`<link id="i18n-can" rel="canonical" href="https://example.com/tests/1">`
it should be
`<link id="i18n-can" rel="canonical" href="https://example.com/tests/1?customer=any">`

**Comment by BobbieGoede** [comment]
Thanks for reporting! 

Looks like I already fixed this issue but it wasn't released yet, I just published [`8.0.1`](https://github.com/nuxt-modules/i18n/releases/tag/v8.0.1), it should be working as expected after updating 😄. I have updated your reproduction to demonstrate [here](https://stackblitz.com/edit/github-orzjqc-1q4vxj?file=package.json).
