### ISSUE TITLE
After update to Nuxt 3.10 a new warning shows in the console: `[Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement`

### ISSUE THREAD

**Issue by samk-dev** [nuxt-modules/i18n#2752]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xnbrlm?file=app.vue

### Describe the bug

After updating to Nuxt 3.10 `[Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement` appears in the console.

<img width="1210" alt="Screenshot 2024-02-02 at 21 22 26" src="https://github.com/nuxt-modules/i18n/assets/33263129/a6c234ec-8e83-4ce5-88aa-4889ffac9eea">

### Logs

```shell
vue.js?v=56ecbe30:1502 [Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

warn$1	@	vue.js?v=56ecbe30:1502
injectHook	@	vue.js?v=56ecbe30:4311
(anonymous)	@	vue.js?v=56ecbe30:4318
useLocaleHead	@	index.mjs?v=56ecbe30:113
injectNuxtHelpers	@	utils.mjs?v=56ecbe30:256
setup	@	i18n.mjs?v=56ecbe30:316
await in setup (async)		
(anonymous)	@	nuxt.js?v=56ecbe30:111
fn	@	nuxt.js?v=56ecbe30:182
runWithContext	@	vue.js?v=56ecbe30:5407
callWithNuxt	@	nuxt.js?v=56ecbe30:187
(anonymous)	@	nuxt.js?v=56ecbe30:32
run	@	vue.js?v=56ecbe30:312
runWithContext	@	nuxt.js?v=56ecbe30:32
applyPlugin	@	nuxt.js?v=56ecbe30:111
executePlugin	@	nuxt.js?v=56ecbe30:130
applyPlugins	@	nuxt.js?v=56ecbe30:155
await in applyPlugins (async)		
initApp	@	entry.js:48
(anonymous)	@	entry.js:65
```

**Comment by warflash** [comment]
See -> https://github.com/nuxt-modules/i18n/issues/2748

**Comment by BobbieGoede** [comment]
As referenced, this (duplicate) issue has already been resolved, just not been released yet.
