### ISSUE TITLE
Canonical and Hreflang Links output encoded 

### ISSUE THREAD

**Issue by readio** [nuxt-modules/i18n#2764]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     2.17.1
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

 Version: "@nuxtjs/i18n": "^7.3.1"

### Describe the bug

Canonical and Hreflang Links output encoded in the head.

Example:
`<link data-n-head="ssr" data-hid="i18n-can" rel="canonical" href="/en/pages%2Ffaq">`

According to our SEO team:

This issue affects the proper indexing of the pages, leading to SEO indexing problems and content duplication concerns. 

The canonical link still serves the same content. The issue is that it's telling search engines to ignore the live link and focus on indexing the incorrect coded link that is orphaned.

I've a had look in `node_modules/@nuxtjs/i18n/src/templates/head-meta.js`.

Below is the output of  `this.$route':

```
fullPath: "/en/pages/faq"
path: "/en/pages/faq"
...
```

However, the links are generated with `currentRoute` which outputs below:

```
fullPath: "/en/pages%2Ffaq"
path: "/en/pages%2Ffaq"
...
```

Is there a reason that '/' characters are encoded, and is there a way it can be changed?

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
