### ISSUE TITLE
$i18n.locales only returns code and not other properties

### ISSUE THREAD

**Issue by bsiguret** [nuxt-modules/i18n#2766]
### Environment

- Operating System: Darwin
- Node Version:     v21.6.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.1
- Nitro Version:    2.8.1
- Package Manager:  yarn@4.0.2
- Builder:          -
- User Config:      modules, app, vite, pwa, security, devtools, hooks, build, ssr, components, routeRules, postcss, runtimeConfig, sourcemap, experimental
- Runtime Modules:  @nuxt/devtools@1.0.6, @vite-pwa/nuxt@0.3.6, nuxt-security@0.14.4, @nuxtjs/tailwindcss@6.10.3, @nuxtjs/i18n@8.0.0-rc.6, @vueuse/nuxt@10.6.1, @artmizu/nuxt-prometheus@2.2.1
- Build Modules:    -

### Reproduction

_See additional context for actual results_

You can reproduce with the latest version and before 8.0.0-rc.6 to highlight the differences.

### Describe the bug

Hello, it's basically what's said in this discussion: https://github.com/nuxt-modules/i18n/discussions/2619#discussion-5958789

I'm in the same position, more or less. I put custom keys in my i18n `locales` config to access it in my switch languages component. The problem is since 8.0.00-rc.6, `$i18n.locales` isn't returning the whole locales config but only the locales code (like `availableLocales`).

I'm not finding new composable or property to have the same old comportment. I only found `localeProperties` but only for the current locale, which is not what I need. Is this change intended, since I'm not finding anything in the changelog? If yes, I'll just put this config in runtimeConfig to be able to access it and refactor my component.

I'm just highlighting this comportment change just in case, sorry if you find it unnecessary 😄 

Thank you for your time.

### Additional context

Before:
`console.log($i18n.locales)`
```
[
    {
        "code": "fr",
        "iso": "fr-FR",
        "dateFormat": "dd/MM/yyyy",
        "iconComponent": "IFrenchFlag",
        "emoji": "🇫🇷",
        "switchText": "Français",
        "files": [
            "lang/fr-FR.json",
            "lang/fr-FR/flash.json",
            "lang/fr-FR/errors.json"
        ]
    },
    {
        "code": "en",
        "iso": "en-GB",
        "iconComponent": "IEnglishFlag",
        "dateFormat": "MM/dd/yyyy",
        "emoji": "🇬🇧",
        "switchText": "English",
        "files": [
            "lang/en-GB.json",
            "lang/en-GB/flash.json",
            "lang/en-GB/errors.json"
        ]
    },
    {
        "code": "pt-BR",
        "iso": "pt-BR",
        "iconComponent": "IBrazilFlag",
        "dateFormat": "dd/MM/yyyy",
        "emoji": "🇧🇷",
        "switchText": "Português",
        "files": [
            "lang/pt-BR.json",
            "lang/pt-BR/flash.json",
            "lang/pt-BR/errors.json"
        ]
    }
]
```

After:
`console.log($i18n.locales)`
```
[
    "fr",
    "en",
    "pt-BR"
]
```

**Comment by BobbieGoede** [comment]
I'm unable to replicate this using the latest release, are you sure you experience this after installing the latest version? If so, could you add a minimal reproduction?

**Comment by bsiguret** [comment]
Yes, I tried to update from rc5 to the latest version. Then I had several bugs and tried to do it step by step with newer rc versions.

 But strangely, I can't reproduce it with the stackblitz you provide. I'll dig further into my app and come back to you. It's a real prod app with a lot of things going on, so it may be tricky to catch. Sadly I can't share the repo for obvious reasons.
 
 I'll close this if I can't give you further indications. I should have tested with the stackblitz before opening the issue, sorry for that.
