### ISSUE TITLE
useLocaleHead doesn't change or its not reactive.

### ISSUE THREAD

**Issue by pmnzt** [nuxt-modules/i18n#2775]
### Discussed in https://github.com/nuxt-modules/i18n/discussions/2765

<div type='discussions-op-text'>

<sup>Originally posted by **jesspinklet** February  8, 2024</sup>
![image](https://github.com/nuxt-modules/i18n/assets/77070946/cb04397f-cc81-492a-b834-e0bbd8f9e4fa)
I have this in my app.vue file

after upgrading to 8.0.1 or anything else above from 8.0.0 version, the lang and dir attribute is not getting updated when i set locale from useI18n() unless I change page. 

I read the docs and change logs but not sure if am I missing something or not</div>

**Comment by jesspinklet** [comment]
Based on this: https://github.com/nuxt-modules/i18n/issues/2771
In order to set locale, we have to import and use `setLocale()` instead of `locale`
