### ISSUE TITLE
Object literal may only specify known properties, and 'i18n' does not exist in type 'NuxtConfig'

### ISSUE THREAD

**Issue by martio** [nuxt-modules/i18n#2791]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.6.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.2
- Builder:          -
- User Config:      devtools, modules, app, css, postcss, pinia, routeRules, i18n
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxtjs/i18n@8.1.1, @nuxt/content@2.12.0, @nuxtjs/tailwindcss@6.11.4, nuxt-gtag@1.2.0, @nuxt/test-utils/module@3.11.0, @nuxtjs/eslint-module@4.1.0
- Build Modules:    -
------------------------------

### Reproduction

Create new an app and installing the latest packages.

<img width="751" alt="Zrzut ekranu 2024-02-15 o 09 53 46" src="https://github.com/nuxt-modules/i18n/assets/133636/2feac598-4bed-4390-80f6-02f165534cff">

### Describe the bug

After creating a new Nuxt application and installing the latest packages, I'm having trouble with TypeScript in "nuxt.config.ts" for "i18n". The command "pnpm dlx nuxi prepare" doesn't help. Deleting the ".nuxt" directory doesn't help either. For object literals, you can only specify known properties, and the "i18n" property does not exist in type "InputConfig<NuxtConfig, ConfigLayerMeta>".

### Additional context

nuxt: 3.10.2,
nuxtjs/i18n: 8.1.1

Updating to edge did not solve the problem.

**Comment by martio** [comment]
It started working and I don't know how I did it. It seems to be OK. Sorry for the confusion :confounded:

**Comment by webcodepl** [comment]
### Environment
* Operating System: ChromeOS / Windows 10 pro
* Node Version:     v20.11.1
* Nuxt Version:     3.10.3
* Runtime Modules:  @nuxtjs/i18n@8.1.1

### Reproduction
npx nuxi@latest init nuxt3-test

![image](https://github.com/nuxt-modules/i18n/assets/11521576/663443e4-cfd2-48b0-b9cf-d86a9aec6ea7)

### Describe the bug
After creating a new empty Nuxt application, I'm having trouble with TypeScript in "nuxt.config.ts" for "i18n". For object literals, you can only specify known properties, and the "i18n" property does not exist in type "InputConfig<NuxtConfig, ConfigLayerMeta>".

### Additional context
nuxt: 3.10.3, nuxtjs/i18n: 8.1.1

**Comment by martio** [comment]
@webcodepl Run the command `nuxt prepare`, which will solve the above problem...

**Comment by webcodepl** [comment]
Thanks. It works.
