### ISSUE TITLE
Memory Leak - crashes out

### ISSUE THREAD

**Issue by andylord56** [nuxt-modules/i18n#2793]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.0
- Builder:          -
- User Config:      devtools, css, modules, googleFonts, imports, postcss, turnstile, runtimeConfig, i18n
- Runtime Modules:  @nuxt/ui@2.13.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/google-fonts@3.1.3, @nuxtjs/turnstile@0.6.3, @vueuse/nuxt@10.7.2     
- Build Modules:    -

### Reproduction

Component:
```
<script lang="ts" setup>
  const languageStore = useLanguageStore();
  const userStore  = useUserStore();
  const { locale } = useI18n();
  const locales = ['en', 'fr'];

  function updateLocale(lang: string) {
    languageStore.setLocale(lang);
    locale.value = lang;
    if (userStore.isLoggedIn) {
        languageStore.storeResidentLocale(locale.value)
    }
  }

  onMounted(() => {
    const savedLocale = window.localStorage.getItem('locale')

    if (savedLocale) {
      languageStore.setLocale(savedLocale)
      locale.value = savedLocale
    } else {
      locale.value = languageStore.locale
    }
  })
</script>

<template>
  <UFormGroup name="locale">
    <USelect
      v-model="locale"
      @change="updateLocale($event.target.value)"
      :options="locales" 
    />
  </UFormGroup>
</template>
```
Config:
```
import en from './locales/en.json'
import fr from './locales/fr.json'

export default defineI18nConfig(() => ({
    legacy: false,
    locale: 'en',
    messages: {
      en,
      fr
    }
  }))
```
SetLocale 
```
    setLocale(newLocale: string) {
      this.locale = newLocale;
      if (process.client) {
        window.localStorage.setItem('locale', newLocale);
      }
    },
```

### Describe the bug

When running the app all fine however pressing F5 to refresh will then suddenly start using all the memory and cpu to crash

Have used versions:
8.11
8.0.1 - saw in another issue that possible fix

**Comment by Jorgee97** [comment]
Hi @andylord56, Did you find the solution for this? I'm having the same problem my RAM usage skyrockets when reloading for the first time.

**Comment by lshegay** [comment]
Nuxt definitely has a memory leak. Almost every second in any medium size project Node process RAM consumption increases by 10mb.

It can be easily reproduced:
1. Create a new Nuxt project 
2. Use [shadcn-vue](https://www.shadcn-vue.com/) to generate .vue SFC files, [blocks can be easily used](https://www.shadcn-vue.com/blocks.html)
3. Use them to render a page in development mode
4. Just look at any RAM meter, Node.js process consumption will be increasing without any action by developer.

i gave it 2-3 minutes without doing anything on my pc:

before:
![Image](https://github.com/user-attachments/assets/dafba25f-cece-4476-8995-5169c926f1d8)

after:
![Image](https://github.com/user-attachments/assets/afb575ce-3a8f-4021-8020-ea65b52d698e)
