### ISSUE TITLE
Lazy loading localeMessages fetches several times when the page changes

### ISSUE THREAD

**Issue by barakayevsanjar** [nuxt-modules/i18n#2810]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      ssr, css, app, modules, i18n, sitemap, image, device, site, nitro, build, security, devServerHandlers, runtimeConfig, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @nuxtjs/i18n@8.1.1, @vueuse/nuxt@10.7.2, @nuxtjs/device@3.1.1, @pinia/nuxt@0.4.11, nuxt-simple-robots@4.0.0-rc.13, nuxt-simple-sitemap@4.4.1, nuxt-security@0.14.4, @nuxt/image@1.3.0
- Build Modules:    -

### Reproduction

This is the code that I wrote 
[Link to StackBlitz](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-3mbkif?file=locales%2Fuz.ts)

### Describe the bug

When the app mounts, the localeMessages with the default locale fetches normally. However, when I navigate to certain pages, such as localhost:3000/u/some-user-name or /some-company-name (I have dynamic routes in the pages folder), it fetches again. Sometimes, lazy loading fetches an entirely different locale.

**Comment by sanjarbarakayev** [comment]
I had a component that I intended to use across multiple sites. Consequently, I created a page and utilized it as a widget component in my current project with iframe. However, the locale messages were fetched twice when the app was mounted within an iframe and I entered pages that used this widget.

Problem solved)

**Comment by BobbieGoede** [comment]
>Problem solved)

Seems like this issue has been resolved? I'll close this issue, let me know if you're still experiencing this issue and I'll reopen!
