### ISSUE TITLE
detectBrowserLanguage doesn't work

### ISSUE THREAD

**Issue by jmuidesign** [nuxt-modules/i18n#2829]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.1.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xkxgkk?file=nuxt.config.ts,pages%2Findex.vue

### Describe the bug

The cookie is never set when hit root, whether it's default `i18n_redirected` or custom `test_cookie` in my example

**Comment by BobbieGoede** [comment]
Somehow I remember this working before, but this seems to have been broken when reverting to earlier versions too.. From what I can tell it looks like the tests have never properly tested the cookie being set on page load, only after locale switching 🤔 so this may have never worked as expected (in v8). 

Current test
https://github.com/nuxt-modules/i18n/blob/eafe06bb561154b67ebbdb75acf8bcb00c8b1df2/specs/browser_language_detection/no_prefix.spec.ts#L39-L45

First version of test
https://github.com/nuxt-modules/i18n/blob/b660dc22daf740bee093527f7b49585c4011988d/specs/browser_language_detection/cookie.spec.ts#L25-L34)

Thanks for reporting, I'll work on a fix soon!

**Comment by jmuidesign** [comment]
Thank you @BobbieGoede 💪
