### ISSUE TITLE
Locale ISO code is required to generate alternate link

### ISSUE THREAD

**Issue by kaboume** [nuxt-modules/i18n#2836]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.5
- Builder:          -
- User Config:      runtimeConfig, css, typescript, build, modules, prismic, i18n, gtag, site, routeRules
- Runtime Modules:  (), @pinia/nuxt@0.4.11, @nuxtjs/prismic@3.1.0, nuxt-swiper@1.2.2, @nuxtjs/i18n@8.1.1, nuxt-gtag@1.2.0, @nuxtjs/seo@2.0.0-rc.8
- Build Modules:    -
------------------------------

### Reproduction

nuxt.config.js : 

```
i18n: {
    vueI18n: "./i18n.config.ts",
    locales: ["en", "fr"], 
    defaultLocale: "fr", 
    customRoutes: "config", // disable custom route with page components
    pages: {
      index: {
        fr: "/",
        en: "/",
      },
      contact: {
        fr: "/contact",
        en: "/contact",
      },
      "formations/[uid]": {
        fr: "/formation/[uid]",
        en: "/training/[uid]",
      },
```

### Describe the bug

I use useSetI18nParams because I have Dynamic route parameters.
Here is my page tree:
/pages/training/[uid].view

In my page /pages/formations/[uid].vue, I have:

```
<script setup>
const setI18nParams = useSetI18nParams();

const { data, pending, error } = await useLazyAsyncData(async () => {
      ....
       setI18nParams({
         en: { uid: tabUrlsLanguage.get("en") },
         fr: { uid: tabUrlsLanguage.get("fr") },
       });
     }
   }
```

When the switchLocalePath() is executed, the page laughs refreshing with this message in the log:
 
  **Locale ISO code is required to generate alternate link**

**Comment by BobbieGoede** [comment]
You should configure your locales as objects with an `iso` property, see https://i18n.nuxtjs.org/docs/guide/seo#requirements for an example. Let me know if that resolves the issue for you.

**Comment by kaboume** [comment]
Thanks, it works !
