### ISSUE TITLE
No match found for location with path "/"

### ISSUE THREAD

**Issue by hadimajidi** [nuxt-modules/i18n#2855]
### Environment

"nuxt": "^3.11.0",
"@nuxtjs/i18n": "^8.2.0",

### Reproduction

this is the export default defineNuxtConfig({

```
    ['@nuxtjs/i18n',
      {
        strategy: "prefix",
        lazy: false,
        langDir: "lang/",
        fallbackLocale: ['en', 'nl','fr','fa'],
        detectBrowserLanguage: {
          fallbackLocale: ['en', 'nl','fr','fa'],
          useCookie: true,
          cookieKey: lang_cookie_name,
          cookieSecure: true,
          redirectOn: 'root',
          alwaysRedirect: true
        },

```

### Describe the bug

the bug is in npm run dev get the error [Vue Router warn]: No match found for location with path "/".

this is very annoying when nuxt goes to npm run generate.

### Additional context

this is very annoying when nuxt goes to npm run generate.

### Logs

```shell
[Vue Router warn]: No match found for location with path "/"
```

**Comment by jesspinklet** [comment]
Here is the [reproduction](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-hexbdg?file=nuxt.config.ts).
Strategy prefix won't generate / path and it will only generate locales path. this will cause warnings inside terminal/console.

**Comment by nash403** [comment]
Same issue here 🙋🏾

**Comment by omerkoseoglu** [comment]
Same issue
