### ISSUE TITLE
$getRouteBaseName CommonComposableOptions error WTF

### ISSUE THREAD

**Issue by provokcx** [nuxt-modules/i18n#2864]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.6.2
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      devtools, typescript, modules, svgLoader, site, i18n, image, ogImage, sitemap, schemaOrg, runtimeConfig, vue, vite, nitro, routeRules, css, app
- Runtime Modules:  ~~/modules/download-global/index.ts, ~~/modules/download-routes-params/index.ts, ~~/modules/counter-robots/index.ts, ~~/modules/cms-redirections/index.ts, ~~/modules/svg-loader/index.ts, ~~/modules/lite-youtube-embed/index.ts, @nuxtjs/i18n@8.2.0, @nuxt/image@1.4.0, @nuxtjs/seo@2.0.0-rc.9
- Build Modules:    -
------------------------------

### Reproduction

...

### Describe the bug

You forgot to wrap `getRouteBaseName` with `wrapComposable` [here in your code](https://github.com/nuxt-modules/i18n/blob/7104e129b6ff00c33e5f8cccbeed65a4f423e236/src/runtime/routing/extends/i18n.ts#L147).

This results in `$getRouteBaseName` failing because the `common` argument is missing.

```ts
// This throws an error.
const routeBaseNameTest1 = $getRouteBaseName(specificRoute);

// This throws an error too.
const routeBaseNameTest2 = $getRouteBaseName();
```

### Additional context

Add tests to the code base to avoid pushing error-prone code.
(It's been a problem multiple times from the start with v8)

**Comment by BobbieGoede** [comment]
At first glance it looks like you're right, will look into it but a repro is always helpful.

**Comment by provokcx** [comment]
@BobbieGoede 

I updated to v8.3.0.

Now it's the Typescript definition of `getRouteBaseName` that's wrong (and thus the definition of `$getRouteBaseName` is wrong too.)

You'll find the wrong definition in the following generated file:
`dist/runtime/routing/compatibles/routing.d.ts`

The problem comes from the changes made to `getRouteBaseName` in the following commit (see line 50 of `src/runtime/routing/compatibles/routing.ts`):
https://github.com/nuxt-modules/i18n/commit/b0016471c617ece151ac1d2f3195f3bd4b0b3bc7

Do you have a strategy to avoid rollbacks for future module versions?

**Comment by BobbieGoede** [comment]
Feel free to open a PR!
