### ISSUE TITLE
bfcache Issue after adding i18n module

### ISSUE THREAD

**Issue by BrocksiNet** [nuxt-modules/i18n#2876]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.11.1`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `pnpm@8.15.5`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-jjkr5f

### Describe the bug

![image](https://github.com/nuxt-modules/i18n/assets/3763023/d3ad92ed-35d6-4ac5-b1dc-b45fb2eead39)

I was researching a lot today about that issue. :mag: 

I assume that the issue comes from [nuxt i18n module](https://v8.i18n.nuxtjs.org/getting-started/setup).

So I created a empty nuxt/vite project with that command:
`pnpm dlx nuxi@latest init <project-name>`

Testing this in **preview mode** is important because Vite is opening a WebSocket in dev mode, which can also cause an issue with bfcache.

So the steps for **testing** are:
1. pnpm build
2. pnpm preview
3. Open the Page in a Chrome Browser
4. Open Dev Tools -> Application -> Back/Forward Cache -> Click on Test Button

**Result:**
- Blank Nuxt/Vite Project -> No bfcache Issue :heavy_check_mark: 
- Blank Nuxt/Vite Project + i18n module -> bfcache Issue :x: 

Somehow I assume it has something to do with `detectBrowserLanguage` function. But not sure about that. :confused: 

Can someone reproduce or confirm? I hope I am wrong.

**Comment by BobbieGoede** [comment]
This seems to be caused by `useCookie` provided by Nuxt (which is used by `@nuxtjs/i18n`), I modified your reproduction to demonstrate [here](https://stackblitz.com/edit/github-jjkr5f-op1phh?file=nuxt.config.ts,pages%2Findex.vue).

I recommend opening an issue on the Nuxt repo as there isn't much we can do about this here.

**Comment by BrocksiNet** [comment]
But what about this [PR](https://github.com/nuxt/nuxt/pull/23667) in nuxt repo. 
It should fix that problem?

**Comment by FlorianWerndl** [comment]
I tried disabeling `detectBrowserLanguage` but problem seems to persist.

**Comment by FlorianWerndl** [comment]
@BrocksiNet have you found any workaround?

**Comment by bbauti** [comment]
Hello! Any workaround for this?

**Comment by BobbieGoede** [comment]
@bbauti 
Can you provide an up to date reproduction? I'll take a look

**Comment by BobbieGoede** [comment]
Closing this as I'm no longer able to reproduce this issue, perhaps it has been resolved upstream 🤔 Please let me know if you're still experiencing this issue with updated dependency, if you can provide an updated reproduction I'll reopen this issue 🙏

**Comment by BrocksiNet** [comment]
I can confirm that with `@nuxtjs/i18n` version `^8.5.5`, I no longer have this `bfcache` Issue. Thx :raised_hands:
