### ISSUE TITLE
getRouteBaseName error in Nuxt 3.11

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt-modules/i18n#2891]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      app, auth, components, css, devServer, devtools, modules, nitro, runtimeConfig, sourcemap, srcDir, vite
- Runtime Modules:  @nuxtjs/i18n@8.2.0, nuxt-jsonld@2.0.8, @nuxtjs/device@3.1.1, @nuxtjs/robots@3.0.0, nuxt-lazy-hydrate@1.0.0, @vueuse/nuxt@10.9.0, @sidebase/nuxt-auth@0.6.7
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-gs2dao?file=app.vue

### Describe the bug

When using `getRouteBaseName` with Nuxt 3.11, i18n fails to find `runtimeConfig`.
<img width="680" alt="image" src="https://github.com/nuxt-modules/i18n/assets/1668207/c14f0649-2eac-4d8b-afa9-c91f13688c29">

**Comment by BobbieGoede** [comment]
This should was resolved by #2865, I just published v8.3.0 which includes this fix!

**Comment by TheDutchCoder** [comment]
Thanks I can confirm this now works again!
