### ISSUE TITLE
<i18n-n scope="global"> throws warning [intlify] Not found parent scope. use the global scope

### ISSUE THREAD

**Issue by VictorKrasnov** [nuxt-modules/i18n#2895]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@4.1.1
- Builder:          -
- User Config:      app, ui, nuxtIcon, css, devtools, i18n, modules, nitro, runtimeConfig, tailwindcss, typescript, extends, colorMode
- Runtime Modules:  @nuxtjs/i18n@8.2.0, @nuxt/image@1.4.0, @davestewart/nuxt-scrollbar@1.0.0, nuxt-swiper@1.2.2, @nuxt/ui@2.14.2, @nuxtjs/color-mode@3.3.2, @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

Add tag <i18n-n :value="12345" scope="global" /> to any page / component. 

### Describe the bug

<i18n-n scope="global"> throws warning [intlify] Not found parent scope. use the global scope.
It's very difficult to test my project because I have a lot of these warnings in the browser console.

**Comment by VictorKrasnov** [comment]
I'm sorry, this html-code example disappeared in issue bug description section: `<i18n-n :value="12345" scope="global" />`

**Comment by VictorKrasnov** [comment]
Reproduction: https://stackblitz.com/edit/i18n-n-warning?file=pages%2Findex.vue

**Comment by BobbieGoede** [comment]
Thanks for reporting and providing a reproduction!

The fix for this has been merged upstream in vue-i18n (#1786) and has been released as well, removing lockfiles before installing will install this latest version, I've updated your reproduction to demonstrate [here](https://stackblitz.com/edit/i18n-n-warning-aq1fpb?file=pages%2Findex.vue).

**Comment by VictorKrasnov** [comment]
> Thanks for reporting and providing a reproduction!
> 
> The fix for this has been merged upstream in vue-i18n (#1786) and has been released as well, removing lockfiles before installing will install this latest version, I've updated your reproduction to demonstrate [here](https://stackblitz.com/edit/i18n-n-warning-aq1fpb?file=pages%2Findex.vue).

Sorry but I updated i18n to 8.0.3 in my project but nothing changed, I still see these warnings. What else should I check?

**Comment by BobbieGoede** [comment]
If removing lockfiles and reinstalling dependencies doesn't work you may have to also delete `node_modules` before running npm install. If you haven't pinned `vue-i18n` in your package.json, `@nuxtjs/i18n` should install the latest compatible `vue-i18n@^9.9.0` version which is `vue-i18n@9.11.0` which includes the fix.

If you're still getting the warning with the same usage as the reproduction then you likely have an older version installed.

**Comment by VictorKrasnov** [comment]
Thank you very much, everything works now.

**Comment by blowsie** [comment]
Related 
https://github.com/intlify/vue-i18n/discussions/851
