### ISSUE TITLE
Content and i18n - Document not found for non-default locales

### ISSUE THREAD

**Issue by vlamic** [nuxt-modules/i18n#2901]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, typescript, app, modules, site, nitro, content, i18n
- Runtime Modules:  @nuxt/content@2.12.1, @nuxtjs/i18n@8.3.0
- Build Modules:    -

### Reproduction

Hi, 

I'm trying to setup a project which is driven by content and supports multiple languages, so I have created two dirs in my `content` folder: `en` and `es`.  When I try to access the default routes (e.g.  http://localhost:3000/ or http://localhost:3000/about), it loads  the pages correctly. However, when I try to access non-default pages, it's not able to locate the content (e.g. http://localhost:3000/en/about or http://localhost:3000/en). Am I missing something?

I have uploaded a sample project here: https://github.com/vlamic/content-app-test

Content structure:

![iScreen Shoter - Code - 240325120127](https://github.com/nuxt/content/assets/1814198/a2a11368-c02f-4afd-a4a5-b959e96f7941)

Pages structure:

![iScreen Shoter - Code - 240325120213](https://github.com/nuxt/content/assets/1814198/ac906c90-4185-4d0e-b364-59b9c3b190ea)

Nuxt config:

![iScreen Shoter - Code - 240325120230](https://github.com/nuxt/content/assets/1814198/9fa87ba1-fdd5-4944-9644-fe2a52cf9774)

Thank you!

### Describe the bug

It's not able to find the localized pages in the content folder.

**Comment by kazupon** [comment]
Thank you for your reporting!

I tried to disable nuxt-i18n module and reproduced this issue.
So I faced same issue.
I think this issue is nuxt content.

Please, check nuxt content docs agian.
https://content.nuxt.com/

Thanks!

**Comment by owocc** [comment]
I also encountered the same problem as you, and then I cloned your project, and then I deleted the i18n configuration of the content, and then I visited the page, and the page can be accessed normally.

<img width="618" alt="Screenshot 2024-04-14 at 16 02 25" src="https://github.com/nuxt-modules/i18n/assets/59416906/1ead15db-b1e6-42ec-824b-842ec6917b72">

<img width="471" alt="Screenshot 2024-04-14 at 16 03 26" src="https://github.com/nuxt-modules/i18n/assets/59416906/5f500bfc-b6cb-4116-b111-db2f84d55094">

<img width="417" alt="Screenshot 2024-04-14 at 16 03 33" src="https://github.com/nuxt-modules/i18n/assets/59416906/c1e06c95-0023-4c38-86fd-de023cdb725f">
