### ISSUE TITLE
i18n-t Bug

### ISSUE THREAD

**Issue by rczdgbg** [nuxt-modules/i18n#2916]
### Environment

https://stackblitz.com/edit/github-a5wazj-ryaexl?file=package.json

### Reproduction

https://stackblitz.com/edit/github-a5wazj-ryaexl?file=package.json

### Describe the bug

https://stackblitz.com/edit/github-a5wazj-ryaexl?file=package.json

### Logs

```shell
An error occurs when running
```

**Comment by BobbieGoede** [comment]
It looks like you have to update your dependencies (and the configuration accordingly), I have updated your reproduction to demonstrate [here](https://stackblitz.com/edit/github-a5wazj-i94z8s?file=package.json).

If you're running into any issues please provide a description..

**Comment by rczdgbg** [comment]
@BobbieGoede  https://stackblitz.com/edit/github-a5wazj-tp1y9r?file=pages%2Findex.vue 
Can you help me look at the issue of switchLocalePath? Didn’t get the language address。
