### ISSUE TITLE
nuxt/i18n custom route paths doesn't work

### ISSUE THREAD

**Issue by Gizem346** [nuxt-modules/i18n#2923]
### Environment

My nuxt and i18n version are:
"@nuxtjs/i18n": "^8.3.0",
 "nuxt": "^3.10.1"

### Reproduction

It's my github repo: https://github.com/Gizem346/i18n-testing
and stackblitz reproduction link is here : https://stackblitz.com/~/github.com/Gizem346/i18n-testing

### Describe the bug

Current locale is: en
When i change language as deutch, also i want to change url path as **de/uber-uns** and **de/kontaktiere-uns** but it doesn't.
When I manually type the address **de/uber-uns** into the search bar, I can access the page, but not when I change it via links.
Here is nuxt/i18n custom route paths documantation: https://i18n.nuxtjs.org/docs/guide/custom-paths 

What is Expected?
* de/uber-uns
* de/kontaktiere-uns

What is actually happening?
* de/about-us
* de/contact-us

**Comment by BobbieGoede** [comment]
Your stackblitz reproduction doesn't seem to work for me (I haven't checked your repo repro locally yet either) but I think the issue here is that you're configuring custom routes for `about` and not for `about-us`.

My guess is that changing the configuration to the following should make things work as expected:

```ts
    pages: {
      'about-us': {
        en: '/about-us',
        de: '/uber-uns'
      }
    },
```

**Comment by Gizem346** [comment]
First of all, thank you for your contribution.  @BobbieGoede 
Yes, when I updated it as you said, I saw that the url changed depending on the link I clicked. Thanks a lot.
Expected: de/uber-uns
Happened: de/uber-uns

But before, when I manually typed de/uber-uns in the search bar, I could see the "Uber Uns" page in RouterView. Now I can't see the relevant pages even though the router has changed. 

<img width="958" alt="ss-of-vue-dev-tool" src="https://github.com/nuxt-modules/i18n/assets/67700158/1afff7f9-3f0a-4ebc-8e5c-f16d32b60305">

**Comment by Gizem346** [comment]
First of all, thank you for your contribution.
Yes, when I updated it as you said, I saw that the url changed depending on the link I clicked. Thanks a lot
Expected: de/uber-uns
Obtained: de/uber-uns

But before, when I manually typed de/uber-uns in the search bar, I could see the "Uber Uns" page in RouterView. Now I can't see the relevant pages even though the router has changed. 

<img width="958" alt="ss-of-vue-dev-tool" src="https://github.com/nuxt-modules/i18n/assets/67700158/143dec8b-c99c-4c73-ba8e-0b0147881345">

**Comment by BobbieGoede** [comment]
Sorry for the very late response, I just took another look at your reproduction, hopefully you already managed to figure it out on your own. 

In your reproduction project you're not exactly making full use of the i18n module features. Each page will be used by the module to generate a localized version and by using the translation functions provided by `vue-i18n` these pages will render the correct translations.

I have modified your reproduction project to demonstrate [here](https://stackblitz.com/edit/gizem346-i18n-testing-bh9fcv?file=pages%2Fabout-us.vue), please note the files in `pages` and the usage of translation functions. I think this should resolve your issue so I'll close this for now, but please let me know if you have any questions and I'll make sure to have a quicker response 🙏

**Comment by Gizem346** [comment]
thanks a lot @BobbieGoede , actually what i want to do is exactly this; i don't want to translate pages, i want to have two different .vue files named about-us and uber-uns and i want the user to change between them (change the route).
I don't want to translate pages.

For example, let's say 'en' is selected, the user is on the about-us page and wants to switch to uber-uns which is in German ('de'), when he clicks on uber-uns the page should switch to uber-uns.vue instead of being translated. 
I'm not sure if it is possible to do this in nuxt-i18n, what do you think?

**Comment by BobbieGoede** [comment]
You can achieve something similar by using the modified reproduction's setup, except having a component per language. It needs to be a single Vue page file if you want to make use of the custom routes feature.

```html
<!-- about-us.vue -->
<script setup>
const { locale } = useI18n();
</script>

<template>
  <AboutUsEnglishComponent v-if="locale === 'en'" /> 
  <AboutUsGermanComponent v-if="locale === 'de'" /> 
</template>
```

Is there any particular reason why you don't want to use the translate functions?

**Comment by Gizem346** [comment]
thanks again @BobbieGoede , i will try . 
And yes, the reason is that we may need to customize the design a bit more for German and other additional languages on our website. When English and German and other languages are translated, it can cause distortions in the design due to word lengths or similar reasons.
