### ISSUE TITLE
Repro projects no longer work

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt-modules/i18n#2924]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

The Stackblitz repro starters no longer work

### Additional context

Link: https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-58r3zi?file=README.md

**Comment by BobbieGoede** [comment]
There was a breaking change in the previous `vue-router` release (see https://github.com/nuxt-modules/i18n/issues/2920), now that this has been reverted the repro starter should work again after removing previously generated lockfiles and reinstalling deps.
