### ISSUE TITLE
Failed to switch page url with language switcher

### ISSUE THREAD

**Issue by tarikkavaz** [nuxt-modules/i18n#2926]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.1
- Builder:          -
- User Config:      devtools, css, postcss, modules, experimental, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-qi7g6c 

### Describe the bug

here is a demo on vercel https://multilang-nuxt3.vercel.app/en/about 
when I click on `switch path to Français (fr)` the patch should be https://multilang-nuxt3.vercel.app/fr/a-propos 
but it doesn't 
the same code works on stackblitz

**Comment by BobbieGoede** [comment]
You can fix this by removing lockfiles and reinstalling dependencies, this is caused by having `vue-router@4.3.1` installed which contains a breaking change and has been reverted in `vue-router@4.3.2`.

Related #2920, #2924
