### ISSUE TITLE
Cannot use dynamic locale file

### ISSUE THREAD

**Issue by intellild** [nuxt-modules/i18n#2929]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.12.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      hooks, typescript, imports, build, modules, css, alias, devtools, devServer, nitro, vite, runtimeConfig, app, piniaPersistedstate, sourcemap
- Runtime Modules:  @pinia/nuxt, @pinia-plugin-persistedstate/nuxt, @nuxtjs/tailwindcss, vite-plugin-version-mark/nuxt, nuxt-svgo, @vueuse/nuxt@10.7.2, @vueuse/motion/nuxt, @nuxtjs/i18n@8.2.0, unplugin-icons/nuxt
- Build Modules:    -
------------------------------

### Reproduction

Follow unplugin-vue-i18n's document
https://github.com/intlify/bundle-tools/blob/main/packages/unplugin-vue-i18n/README.md#allowdynamic

### Describe the bug

'unknown' type in 'mypath/en-US.ts'

### Additional context

I read through the code `src/utils#scanProgram` and managed to get it work through a hack
```
const defineFoo = (fn: () => Promise<any>) => {
  return fn();
};

export default defineFoo(async () => {
  return {};
});
```
But this diverges from unplugin-vue-i18n. Is it intended or a bug?

**Comment by rishta** [comment]
I'm having a similar problem. I think it is required to export the TS data through a wrapping adapter object like `export default createI18nLangueage({your: "language_object"})`, but I fail to find how to define it.

EDIT: RTFM:

https://i18n.nuxtjs.org/docs/guide/lazy-load-translations


`export default defineI18nLocale(async locale => {
  return {
    welcome: 'Bienvenue'
  }
})
`

**Comment by BobbieGoede** [comment]
@intellild 
I'm not sure what the issue is, the documentation you're referring to is not for Nuxt I18n

**Comment by intellild** [comment]
Thanks @rishta 
I was trying to use the feature from unplugin-vue-i18n which powers nuxt i18n and failed to find the correct documentation
