### ISSUE TITLE
how can i add prefix before i18n language prefix?

### ISSUE THREAD

**Issue by cyh2020** [nuxt-modules/i18n#2948]
### Describe the feature

# Environment
My nuxt and i18n version are:
"@nuxtjs/i18n": "^8.3.1",
"nuxt": "^3.11.2"

# Describe the feature
##### folderStructure
├── pages
│           └── wap
 |                            └──page.ts

##### nuxt config
``
i18n: {
    baseUrl: 'https://my-nuxt-app.com',
    vueI18n: "./i18n.config.ts",
    locales: [
      {
        code: "english",
        name: "english",
      },
      {
        code: "japanese",
        name: "japanese",
     ]
}
``

##### what's i want?
by default ,the route to this page is —— {lang}/wap/page, but i want it be —— wap/{lang}/page

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by cyh2020** [comment]
thank you very much!!!

**Comment by cyh2020** [comment]
add a module and resolved
import {
  defineNuxtModule,
  extendPages,
} from "nuxt/kit";

export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: "add-wap",
    configKey: "addWap",
  },
  defaults: {},
  async setup(_options, _nuxt) {
    _nuxt.hook("modules:done", () => {
      extendPages((pages) => {
        pages.forEach((page) => {
          const { path } = page;
          // Add wap path to page
          page.path = `/wap${path}`;
        });
      });
    });
  },
});

**Comment by BobbieGoede** [comment]
Glad to hear you found a solution to your issue!

I wonder if setting the `baseURL` for the whole project would have worked as well https://nuxt.com/docs/api/nuxt-config#baseurl? 🤔

**Comment by cyh2020** [comment]
yeah，thx，i didn't find baseurl can solve
&nbsp;it&nbsp;



---Original---
From: "Bobbie ***@***.***&gt;
Date: Tue, May 28, 2024 18:57 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [nuxt-modules/i18n] how can i add prefix before i18n languageprefix? (Issue #2948)




 
Glad to hear you found a solution to your issue!
 
I wonder if setting the baseURL for the whole project would have worked as well https://nuxt.com/docs/api/nuxt-config#baseurl? 🤔
