### ISSUE TITLE
Changing locale causes all components to be in Unmounted state

### ISSUE THREAD

**Issue by martinszeltins** [nuxt-modules/i18n#2951]
### Environment

````
------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.1
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/github/martinszeltins/nuxt-i18n-unmounted

### Describe the bug

When using `setLocale()` to change locale, it causes all of the components to be left in an `Unmounted` state.

Please see the reproduction. When you click the `Change Locale` button, which uses `setLocale` to change the locale, we see this output in console:

````
onMounted
onMounted
onUnmounted
onUnmounted
````

The last lifecycle hook that triggered was the `onUnmounted` hook. Now all components think that they are unmounted when actually they are not unmounted.

This causes all kinds of issues because usually in `onUnmounted` hook we perform cleanup, remove event listeners etc. and it causes the app to break.

**Screenshot:**
![image](https://github.com/nuxt-modules/i18n/assets/34019878/982a38cc-c50c-48e4-8400-e7e8739184b0)

**Comment by kazupon** [comment]
Thank you for your reporting!

`unmount` is called because nuxt-i18n registers the URLs for nuxt routing by locale. nuxt routing (vue-router) allows the Vue component lifecycle is invoked such as `mount` and `umount`
So, this is the expected behaviour.

Thanks!

**Comment by martinszeltins** [comment]
I don't think this is the expected behavior because the end state of all components is `unmounted` which triggers all `onUnmount` hooks to run and all event listeners are removed. But actually the component is still mounted.

**Comment by BobbieGoede** [comment]
I have changed the logs in your [reproduction](https://stackblitz.com/edit/github-usol9e?file=pages%2Findex.vue,components%2FHelloWorld.vue) to better illustrate what is happening:

![image](https://github.com/nuxt-modules/i18n/assets/6649305/19df61d4-e530-4d05-9a36-d5cc4ca55ba0)

**Comment by martinszeltins** [comment]
> I have changed the logs in your [reproduction](https://stackblitz.com/edit/github-usol9e?file=pages%2Findex.vue,components%2FHelloWorld.vue) to better illustrate what is happening

Oh, I see now. Each locale has its own instance. I also tested with lifecycle hooks and they do indeed seem to be working. Thank you for taking your time to look into this!
