### ISSUE TITLE
pages:extend pages i18n remove layout from extend pages

### ISSUE THREAD

**Issue by anas-js** [nuxt-modules/i18n#2956]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.8.0
- Builder:          -
- User Config:      experimental, hooks, ssr, devtools, nitro, vite, css, pwa, spaLoadingTemplate, app, modules, eslint, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.1, @pinia/nuxt@0.5.1, @nuxt/eslint@0.3.10, @hypernym/nuxt-anime@2.1.1, @vite-pwa/nuxt@0.7.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-jskhtw?file=pages%2Ftest.vue

### Describe the bug

When I add a page using hooks pages:extend:
```js
  hooks: {
    'pages:extend'(pages) {
      pages.push({
        name: `testExtend`,
        path: `/testExtend`,
        file: '~/pages/test.vue',
      });
    },
  },
```
i18n changes the layout to the default, even though on the same page it was not the default..

try open `/test` and `/testExtend` They are the same file
https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-jskhtw?file=pages%2Ftest.vue

/test : 
![image](https://github.com/nuxt-modules/i18n/assets/95453408/705694fb-3b37-443e-a10b-3fffe101074d)

/testExtend
![image](https://github.com/nuxt-modules/i18n/assets/95453408/a451dbe4-2193-4bee-87e3-7b0df3e80844)

**Comment by BobbieGoede** [comment]
This happens without i18n as well, you'll have to pass meta like so:

```ts
    'pages:extend'(pages) {
      pages.push({
        name: `testExtend`,
        path: `/testExtend`,
        meta: { layout: 'trans' },
        file: '~/pages/test.vue',
      });
    },
```

Not sure if `definePageMeta` should work on pages added this way, I suggest opening an issue on the Nuxt repo if that is the expected behavior.

**Comment by anas-js** [comment]
> This happens without i18n as well, you'll have to pass meta like so:
> 
> ```ts
>     'pages:extend'(pages) {
>       pages.push({
>         name: `testExtend`,
>         path: `/testExtend`,
>         meta: { layout: 'trans' },
>         file: '~/pages/test.vue',
>       });
>     },
> ```
> 
> Not sure if `definePageMeta` should work on pages added this way, I suggest opening an issue on the Nuxt repo if that is the expected behavior.

sorry, thanks
