### ISSUE TITLE
Can not use custom path with i18n in nuxt.config.ts

### ISSUE THREAD

**Issue by gaomingzhao666** [nuxt-modules/i18n#2959]
### Environment

- VScode1.85.2
- Windows 10 21H2
- NodeJS 20LTS

### main dependencies is following
```json
{
  "@nuxt/ui": "^2.16.0",
  "nuxt": "^3.11.2",
  "@nuxtjs/i18n": "^8.3.1",
}
```

### Reproduction

[Reproduction is here](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-ksfcam?file=internationalization%2Fi18n.config.ts)

### Describe the bug

I can not use custom path with a specific folder path, it is work properly when using a default path, but when I set custom path as /internationalization/i18n.config.ts as my config file path, that config file is not import properly.

### Logs

```shell
[intlify] not found 'name' key in 'en' locale messages nuxt-i18n
```

**Comment by BobbieGoede** [comment]
You haven't configured a `langDir` so the module is unable to find the file configured for each entry in `locales`, adding `langDir: './internationalization/lang'` to the i18n config in `nuxt.config.ts` should resolve your issue.

We should probably check if `file` or `files` is configured without a `langDir` so we can provide a better error message. 

Let me know if you have any questions, if the suggested changes solve your problem we can close this issue!

**Comment by gaomingzhao666** [comment]
@BobbieGoede Thank you so much for your help, the problem is well-solved!!
