### ISSUE TITLE
Mobile adaptation problem of nuxt/i18n in nuxt3

### ISSUE THREAD

**Issue by Xiangzi529** [nuxt-modules/i18n#2964]
### Environment

How to configure my nuxt/i18n to achieve m/zh CN/xxx when using nuxt3 in conjunction with nuxt/i18n and configuring m/address in nuxt to adapt to mobile devices? However, I am currently in zh CN/m/xxx

### Reproduction

How to configure my nuxt/i18n to achieve m/zh CN/xxx when using nuxt3 in conjunction with nuxt/i18n and configuring m/address in nuxt to adapt to mobile devices? However, I am currently in zh CN/m/xxx

### Describe the bug

How to configure my nuxt/i18n to achieve m/zh CN/xxx when using nuxt3 in conjunction with nuxt/i18n and configuring m/address in nuxt to adapt to mobile devices? However, I am currently in zh CN/m/xxx

### Additional context

How to configure my nuxt/i18n to achieve m/zh CN/xxx when using nuxt3 in conjunction with nuxt/i18n and configuring m/address in nuxt to adapt to mobile devices? However, I am currently in zh CN/m/xxx

### Logs

```shell
How to configure my nuxt/i18n to achieve m/zh CN/xxx when using nuxt3 in conjunction with nuxt/i18n and configuring m/address in nuxt to adapt to mobile devices? However, I am currently in zh CN/m/xxx
```

**Comment by kazupon** [comment]
Thank you for your reporting!

nuxt-i18n gitHub issues is the place to deal with reproducible bugs.
You can ask for help in the [Github Discussions](https://github.com/nuxt-modules/i18n/discussions) and [nuxt discord #i18n channel](https://discord.nuxtjs.org/).

If you would like to help, please share your context.
Then the community may be able to help you.
