### ISSUE TITLE
Regression: Retrieve object nodes

### ISSUE THREAD

**Issue by Leander250** [nuxt-modules/i18n#2966]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.7.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.1.0`
- Builder:          `-`
- User Config:      `modules`, `devtools`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.3.1`
- Build Modules:    `-`

### Reproduction

https://github.com/Leander250/nuxt-i18n-regression

### Describe the bug

In v7 it was possible to retrieve a node which was not a leaf. For example I could get the "options" node and i18n would return an object with 4 properties:

```js
bescheidform: {
        options: {
          bezAsc: 'Bezeichnung (Aufsteigend)',
          bezDesc: 'Bezeichnung (Absteigend)',
          matchcodeAsc: 'Matchcode (Aufsteigend)',
          matchcodeDesc: 'Matchcode (Absteigend)'
        }
 }
```
 
 This causes 
 "[intlify] Not found 'bescheidform.options' key in 'en' locale messages."

in v8 instead.

### Additional context

Would be nice if we could restore this functionality :)

**Comment by kazupon** [comment]
you need to use $tm / tm and $rt / rt.
About how to usage, you can read the docs
https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-api-return-value

thanks!
