### ISSUE TITLE
how can I support returning objects or arrays from the language file?

### ISSUE THREAD

**Issue by simpv** [nuxt-modules/i18n#2967]
### Environment

- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      devtools, app, devServer, css, postcss, modules, sitemap, site, i18n
- Runtime Modules:  @nuxt/content@2.12.1, @nuxtjs/i18n@8.3.1, @pinia/nuxt@0.5.1, @nuxtjs/sitemap@5.2.0, @nuxt/image@1.7.0
- Build Modules:    -

### Reproduction

--

### Describe the bug

I use a .js file to define multilingual content. When using the $t method, how can I support returning objects or arrays from the language file?

**Comment by kazupon** [comment]
you need to use `$tm` /  `tm` and `$rt` / `rt`.
About how to usage,  you can read the docs
https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-api-return-value

thanks!
