### ISSUE TITLE
useRoute('login') does not work, it expects useRoute('login__LOCALE')

### ISSUE THREAD

**Issue by martinszeltins** [nuxt-modules/i18n#2976]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

Nuxt i18n module has support for Nuxt typedPages but I can't understand how to use it.

Nuxt docs says:

> You can get typed params within a page by using `const route = useRoute('route-name')`

But I don't have one `route-name` when using i18n. I don't have a `login` route. Instead I have `login__en`, `login__de`, `login__fr` etc.

Passing in simply _"login"_ does not work `useRoute('login')`, it expects a locale which is very strange. How do I use this? I couldn't find anything in the docs.

**Comment by martijndewit** [comment]
```
definePageMeta({
      name: 'login'
    })
```
on the login page

So you can use 'name' as `localeRoute({ name: 'login' }, locale.value)` for example.

**Comment by martinszeltins** [comment]
@martijndewit That didn't work. I still see `index__en` and `user__de` in route names.

![image](https://github.com/nuxt-modules/i18n/assets/34019878/490d56d7-acdc-4b92-a297-28b8aa36f765)

![image](https://github.com/nuxt-modules/i18n/assets/34019878/35d3d3f7-cf58-470d-8c11-7bfb78a332f5)

**Comment by martijndewit** [comment]
How did you set your [Routing Strategy](https://i18n.nuxtjs.org/docs/guide) ?

**Comment by martinszeltins** [comment]
Sorry, that still doesn't work. `useRoute()` expects a union type to be passed in. I don't think the routing strategy has anything to do with it.

Error:
````
Argument of type '(RouteLocation & { href: string; }) | undefined' is not assignable to parameter of type 'keyof RouteNamedMap | undefined'.
````

![image](https://github.com/nuxt-modules/i18n/assets/34019878/cf607c9c-2057-4dad-a382-ae5188544d88)

**Comment by MinecraftStorage1** [comment]
Same issue, why route names are localized by default? It makes code extremely unreadable and quite doesn't make sense. Every time I need to resolve a route path, I need to figure out the current locale and then suffix it with that locale. I think you should be able to just reference the route name without a locale, and it resolves into a path with the current locale.

**Comment by letoast** [comment]
How do you reproduce this with stackblitz? As far as I've tried there are no type hints on stackblitz with nuxt(vue). 
Not only that, I can't even get i18n to redirect to /en on stackblitz

https://stackblitz.com/edit/github-zep9gz-2odmdq?file=pages%2Ftest.vue

**Comment by BobbieGoede** [comment]
This is related to route `strategy`, you will not have this behavior when using `no_prefix`. Basically when using any other strategy the i18n module will generate localized routes and 'remove' original (unprefixed) routes when they should not exist.

We try to make this behavior easier to deal with by providing composables such as `useLocalePath`, `useLocaleRoute` etc. Unfortunately we have little control over the route type generation, it simply generates types based on the resulting routes, which are accurate for the usual `useRoute` composable but not useful for the composables we provide.

**Comment by letoast** [comment]
@BobbieGoede 
So how do you get type support with useLocaleRoute if for example you have a page in `/pages/foo/[slug].vue`?
<img width="917" alt="image" src="https://github.com/user-attachments/assets/99cc7c65-9fd3-4075-979a-c5ce706eb274">
...
<img width="521" alt="image" src="https://github.com/user-attachments/assets/30e636dc-46d4-4aa8-a9ca-c84be9a55822">

Only this works, but nowhere did I get any hints that slug is even a possible key of params...
<img width="614" alt="image" src="https://github.com/user-attachments/assets/5b32d1f6-f220-4d3f-9273-92310da69530">


There are also no type hints that `/:slug(.*)*` is a possible route, even though I have `[...slug].vue` in my `pages` dir. 
<img width="702" alt="image" src="https://github.com/user-attachments/assets/bcfffa8c-e629-474f-8c74-7d82ed0cad1e">

I'm guessing that this example is not even possible if you have `strategy: 'prefix'` set, because there's no way `'blog'` would be a possible type hint https://i18n.nuxtjs.org/docs/api#uselocaleroute
```vue
<script setup>
const localeRoute = useLocaleRoute()
const { locale } = useI18n()
const linkPath = computed(() => {
  const route = localeRoute('blog', locale.value)
  return route != null ? route.path : '/'
})
</script>
```

**Comment by BobbieGoede** [comment]
I spent some time in the past week to see what it would take to have most of the type inference for these route composables/functions. 

Here's what I have so far https://github.com/BobbieGoede/i18n/pull/49, this branch contains lots of duplicated code from both Vue Router and Nuxt, and relies on their internals so it's not anywhere close to being stable.. 

I will check with their maintainers at some point and see if I could make something happen for v9 but I'm not very optimistic that this is something they want to support/expose downstream.

**Comment by martinszeltins** [comment]
The only way that I've found to be able to get IDE autocomplete for route params is to use one of the locale like this

```ts
const route = useRoute('login___en')

route.params.id // autocomplete works now
```

**Comment by Shhu** [comment]
I am using this as a workaround, but it would be great not to have to.

```ts
const localeRoute = useLocaleRoute()
localeRoute({ name: 'users.edit' as 'users.edit___en', params: { id: row.id } })
```

**Comment by BobbieGoede** [comment]
I have just published the first release candidate for v9 which includes the experimental typed routes [`experimental.typedPages`](https://i18n.nuxtjs.org/docs/v9/options/misc#experimental).

Try it out and please open new issues if you experience any with this feature 🙏
