### ISSUE TITLE
Unexpected token 'pages'

### ISSUE THREAD

**Issue by vis97c** [nuxt-modules/i18n#2986]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.20.3
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@4.2.2
- Builder:          -
- User Config:      extends, app, routeRules, vite, css, i18n
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-3aas7r?file=pages%2Findex.vue

### Describe the bug

Vite HMR fails with the following:

![imagen](https://github.com/nuxt-modules/i18n/assets/45251845/99f176ef-f48f-44bc-9e03-39225b4baed7)

This is a project wide issue, not sure where the issue is coming from. But in a route if I remove the i18n block from the most inner route the error goes away. I tried to replicate that with no avail.

Doing some debugging I found this:

![imagen](https://github.com/nuxt-modules/i18n/assets/45251845/17755474-3cf4-4496-b89e-b81bd29ca7c4)

### Additional context

For context I recently moved my locale from their own *.json file for each page to then import it via custom block src tag. To just include a single i18n block with the translations.

This was the before:

![imagen](https://github.com/nuxt-modules/i18n/assets/45251845/359c6308-67c7-4986-ad07-1da47d0188e8)

and imported them like this

![imagen](https://github.com/nuxt-modules/i18n/assets/45251845/cbd9f481-c982-4d35-bff5-6080a572d402)

### Logs

```shell
ERROR  Pre-transform error: Unexpected token 'pages'.            5:57:35 p.m.

ℹ Vite client warmed up in 20187ms                               5:57:47 p.m.
ℹ Vite server warmed up in 23511ms                               5:57:51 p.m.
✔ Nuxt Nitro server built in 15611 ms                      nitro 5:57:52 p.m.

 ERROR  Internal server error: Unexpected token 'pages'.          5:58:11 p.m.
  Plugin: unplugin-vue-i18n
  File: C:/projects/xamu/store/pages/app/[businessSlug]/settings/index.vue?vue&type=i18n&index=0&lang.json
      at ExtendParser.raise (C:\projects\xamu\store\node_modules\jsonc-eslint-parser\lib\parser\extend-parser.js:74:25)
      at ExtendParser.unexpected (C:\projects\xamu\store\node_modules\jsonc-eslint-parser\lib\parser\extend-parser.js:90:22)
      at pp$9.expect (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:766:28)
      at pp$5.parseObj (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:3182:14)
      at pp$5.parseExprAtom (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:2907:19)
      at pp$5.parseExprSubscripts (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:2715:21)
      at pp$5.parseMaybeUnary (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:2681:19)
      at pp$5.parseExprOps (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:2608:21)
      at pp$5.parseMaybeConditional (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:2591:21)
      at pp$5.parseMaybeAssign (C:\projects\xamu\store\node_modules\acorn\dist\acorn.js:2558:21)


 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/pages/app/[businessSlug]/settings/index.vue?vue&type=i18n&index=0&lang.json"


 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/pages/app/[businessSlug]/settings/index.vue"


 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/pages/app/[businessSlug]/settings/index.vue"


 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/pages/app/[businessSlug]/settings/index.vue"


 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/pages/app/[businessSlug]/settings/index.vue?vue&type=i18n&index=0&lang.json"
```

**Comment by vis97c** [comment]
Spotted the source of the issue. Using html as string within the json on the i18n block seems to be breaking the parsing of the block. Removing it solved the issue. Now I'm using a variable to define the html and using the locale where is needed only:

![imagen](https://github.com/nuxt-modules/i18n/assets/45251845/1f5c1c2f-1e5e-4fdb-a9ee-f76d70bc9289)

**Comment by jesspinklet** [comment]
This issue isn't fixed, We might need to use HTML inside a local scope. How can we make that happen?
