### ISSUE TITLE
Any ways to specify server-side-only translations that are not included in the frontend bundle?

### ISSUE THREAD

**Issue by raf202** [nuxt-modules/i18n#2998]
Using Nuxt 3, we're specifying some translation files that are only used in our backend API (server folder) and returned via API.
The problem is that they're also getting included and loaded in the frontend code, even though nothing on our frontend calls these directly. These files can have a LOT of translation strings and become huge with size, so we're trying to make it load only on the server side to prevent our frontend application becoming too resource consuming.

Any ideas how to achieve this?

**Comment by kazupon** [comment]
Thank you for your reporting.
This is not github issue, is question or consultation.
I'll move to github dicussions
