### ISSUE TITLE
Not able to add i18n config in nuxt.config.ts

### ISSUE THREAD

**Issue by mir1198yusuf** [nuxt-modules/i18n#3011]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@4.2.2
- Builder:          -
- User Config:      devtools, hooks, debug, modules, i18n, plugins, nitro, runtimeConfig, dayjs, postcss, app, tailwindcss, css, apollo, image, carousel, tour, vue, routeRules, serverHandlers, robots, device, security
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0, @nuxtjs/device@3.1.1, @nuxt/image@1.7.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/robots@3.0.0, dayjs-nuxt@2.1.9, vue3-carousel-nuxt@1.1.1, @nuxtjs/apollo@5.0.0-alpha.14, nuxt-tour@0.0.13, @nuxtjs/partytown@1.5.0, @nuxtjs/i18n@8.3.1
- Build Modules:    -
------------------------------

### Reproduction

This error does not come on StackBlitz or CodeSandbox

### Describe the bug

When I add i18n config to defineNuxtConfig, I get this error while adding below i18n object

nuxt.config.ts
```
defineNuxtConfig({
...
modules: [..."@nuxtjs/i18n"],
i18n: {
     vueI18n: {
            strategy: 'prefix_except_default',
            defaultLocale: 'en-IN',
            locales: [
                {
                    code: 'us',
                    name: 'English',
                    iso: 'en-US',
                },
                {
                    code: 'en-IN',
                    name: 'English',
                    iso: 'en-IN',
                },
            ],
        }
}
...
})
```

Error on hovering `vueI18n`: 
```
Object literal may only specify known properties, and 'vueI18n' does not exist in type 'Partial<ModuleOptions>'.ts(2353)
module.d.ts(470, 9): The expected type comes from property 'i18n' which is declared here on type 'InputConfig<NuxtConfig, ConfigLayerMeta>'
```

**Comment by steffenstolze** [comment]
This is a path to a file.

<img width="587" alt="image" src="https://github.com/nuxt-modules/i18n/assets/8490779/27b15c4d-fef8-4ae8-9d70-c740d6894de8">

--- 
add a `i18n.config.ts` file next to your nuxt config with your content:

```
export default {
	... your config
};
```

and adjust your nuxt config like this if you want to use a custom name for the config file:


```
i18n: {
     vueI18n: './my-crazy-i18n-config.ts'
....
}
```

**Comment by BobbieGoede** [comment]
@steffenstolze is right, configuring vue-i18n specific options was changed in v8, please refer to https://i18n.nuxtjs.org/docs/guide/migrating#deprecated-vuei18n-option-to-not-accept-createi18n-options for more details.
