### ISSUE TITLE
Change BaseURL when using different domains

### ISSUE THREAD

**Issue by RobArkesteijn** [nuxt-modules/i18n#3026]
### Describe the feature

I am not sure if this is already possible, but I can not seem to figure it out.
For my site I am using `differentDomains: true`
For SEO purposes, I would like the baseURL to change whenever I switch local (or domain) which it does not seem to be doing right now.
I am using the SEO module and for that to work properly I need to set up [the site config](https://nuxtseo.com/site-config/integrations/i18n). 

The site link will be automatically set to the baseURL of the i18n module. 

I am also not sure if this is i18n module or seo module issue.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by RobArkesteijn** [comment]
Nevermind, I have found a solution for this with the seo module

**Comment by WooHoo-Wu** [comment]
How to solve it, please
