### ISSUE TITLE
Custom Route Paths in nuxt.config dont work together with compiler macro defineI18nRoute

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/i18n#3029]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v21.6.1
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.18
- Builder:          -
- User Config:      extends, modules, future, experimental, runtimeConfig, i18n, routeRules, ignore, site, app, ogImage, sitemap, build
- Runtime Modules:  @nuxtjs/tailwindcss@^6.12.0, nuxt-icon@^0.6.10, @vee-validate/nuxt@^4.12.8, @nuxtjs/seo@^2.0.0-rc.11, nuxt-og-image
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-o4bb8f?file=nuxt.config.ts

* You can try comment/uncomment `customRoutes: 'config',`
* When uncommented `de/kontakt` works but not `de/ueber-uns`
* When commented `de/ueber-uns` works but not `de/kontakt`

### Describe the bug

* When setting `customRoutes: 'config'` in `nuxt.config.ts` Custom Route Paths can be set in `nuxt.config.ts` but using `defineI18nRoute()` is ignored
* When removing `customRoutes: 'config'` from `nuxt.config.ts` `defineI18nRoute()` is works but Custom Route Paths in `nuxt.config.ts` are ignored

### Additional context

Mixed custom route paths in `nuxt.config.ts` and `defineI18nRoute()` is not possible. It must be either all in nuxt.config.ts or all with `defineI18nRoute`.

I dont know if this is supposed to work this way because the [docs](https://i18n.nuxtjs.org/docs/guide/custom-paths#page-component) say:
> You can use the defineI18nRoute compiler macro to set _some_ custom paths for each page component.

**Comment by BobbieGoede** [comment]
This is expected behavior, I suppose this should be documented more clearly.

The default value for `customRoutes` is `'pages'`, so by commenting `customRoutes: 'config'` it will switch back to its default value, [options docs](https://i18n.nuxtjs.org/docs/options/routing#customroutes) and [custom routes docs](https://i18n.nuxtjs.org/docs/guide/custom-paths#:~:text=There%20are%202%20ways%20of%20configuring%20custom%20paths%20for%20your%20Module%20configuration%20or%20your%20pages%20Page%20component.) for reference.

**Comment by MickL** [comment]
Thanks for the quick response! In this case I would suggest to remove the word 'some' and add the info that it is either one or the other :)

Btw. I added a question in the discussions if you might have time.

**Comment by BobbieGoede** [comment]
I agree the wording can be more definitive, the wording is a side effect of having contributors from across globe 💪 Feel free to open a PR if you find anything that needs fixing.
