### ISSUE TITLE
Custom Route Paths Bug with dynamic Sub-Paths

### ISSUE THREAD

**Issue by danbaechtold** [nuxt-modules/i18n#3035]
### Environment

Stackblitz (Reproduction starter (v8 and higher))
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, devtools, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-qr67sy

### Describe the bug

Having this config:
```
customRoutes: 'config',
pages: {
  tours: {
    en: '/trails-en',
    nl: '/trails-nl',
  },
  'tours/[provider]': {
    en: '/trails-en/[provider]',
    nl: '/trails-nl/[provider]',
  },
  'tours/[provider]/[slug]': {
    en: '/trails-en/[provider]/[slug]',
    nl: '/trails-nl/[provider]/[slug]',
  },
}
```

And these pages:
```
pages/
├─ tours/
├─── [provider]/
├───── [slug].vue
├───── index.vue
├─── index.vue
```

I get the following results:
- /trails-en/a/b ==> [slug].vue ==> OK
- /nl/trails-nl/a/b ==> [slug].vue ==> OK
- /trails-en/a ==> 404 ==> NOK, I'd expect it to be handled by /tours/[provider]/index.vue
- /nl/trails-nl/a ==> 404 ==> NOK (same as above)
- /trails-en ==> 404 ==> NOK, I'd expect it to be handled by /tours/index.vue
- /nl/trails-nl ==> 404 ==> NOK (same as above)

**Comment by danbaechtold** [comment]
My bad, I've made a mistake in the pages configuration:

The `../index` was missing in the pages key.

This is the correct configuration:
```
customRoutes: 'config',
pages: {
  'tours/index': {
    en: '/trails-en',
    nl: '/trails-nl',
  },
  'tours/[provider]/index': {
    en: '/trails-en/[provider]',
    nl: '/trails-nl/[provider]',
  },
  'tours/[provider]/[slug]': {
    en: '/trails-en/[provider]/[slug]',
    nl: '/trails-nl/[provider]/[slug]',
  },
}
```

**Comment by denFete** [comment]
@danbaechtold  You saved my day, thanks! Couldn't find any docs with that folder structure
