### ISSUE TITLE
localePath not generating route, it's empty

### ISSUE THREAD

**Issue by grzegorztomasiak** [nuxt-modules/i18n#3038]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.5.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.1
- Build Modules:    -

### Reproduction

no reproduction given.

### Describe the bug

I can't find anything on the web regarding the issue I have, I followed the docs many times and still no luck.

When I use ```<NuxtLink :to="localePath('index', 'fr')">Homepage in FR</NuxtLink>``` the localePath does not generate any url, in fact it's null in the console and null and ```<a>``` tag does not contain href property.

![image](https://github.com/user-attachments/assets/efea03d7-11c5-4acd-a45a-7fa09b508dec)

![image](https://github.com/user-attachments/assets/06040e3f-852d-4750-aefc-2519b25fb034)

and i18n configuration

```js
export default defineI18nConfig(() => ({
  legacy: false,
  locales: ['en', 'fr'],
  defaultLocale: 'en',
  messages: {
    en: {
      welcome: 'Welcome'
    },
    fr: {
      welcome: 'Bienvenue'
    }
  }
}))
```

Anyone has idea why?

**Comment by BobbieGoede** [comment]
The `defineI18nConfig` is meant for `vue-i18n` specific options, have you configured locales in the `i18n` option in `nuxt.config.ts`? These will be applied to `vue-i18n` options as well.

**Comment by grzegorztomasiak** [comment]
```js
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['@nuxtjs/i18n'],
  i18n: {
    locales: ['en', 'fr'],
    vueI18n: './i18n.config.ts'
  }
})
```

holy cow, now it works. I will leave the locales in nuxt.config.js only. Thank you!

**Comment by BobbieGoede** [comment]
Any shared options you only need to configure in `nuxt.config`, these will be applied to `vue-i18n` as well. The `vueI18n` config file simply accepts all `vue-i18n` configurations including those we handle as well.

We're considering merging these options in the next major version so this can configured in one place if possible 😄 (difficulties are serialization of certain properties)
