### ISSUE TITLE
Experimental switchLocalePathLinkSSR causing possible XSS vector

### ISSUE THREAD

**Issue by KilianSSL** [nuxt-modules/i18n#3042]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.10.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      site, debug, app, ssr, telemetry, devtools, sourcemap, modules, vite, nitro, runtimeConfig, i18n, hooks, graphqlMiddleware, multiCache, sitemap, robots, svgSprite, alias, purgecss, htmlValidator
- Runtime Modules:  @nuxtjs/html-validator@1.8.2, @nuxtjs/i18n@8.3.1, @nuxtjs/sitemap@5.2.0, @nuxtjs/robots@3.0.0, @nuxtjs/svg-sprite@1.0.2, @pinia/nuxt@0.5.1, nuxt-graphql-middleware@4.0.0, nuxt-multi-cache@3.1.1, nuxt-purgecss@2.0.0, @nuxt/test-utils/module@3.13.1
- Build Modules:    -

### Reproduction

Minimal Repro: https://github.com/KilianSSL/i18n-ssr-repro

Disable javascript, to best review the SSR response.

1. Set experimental switchLocalePathLinkSSR flag to true
2. Create a wildcard page like /pages/[...slug].vue
3. Make sure you have a language switcher utilizing `<SwitchLocalePathLink>`
4. Navigate to a page like: `http://localhost:3000/fr/%22%3Exss/`
5. If not manually overridden/sanitized via 

  ```
 setI18nParams({
    fr: { slug: '' },
    de: { slug: '' },
  })  
```

  the `">xss/` portion of the URL will cause `<SwitchLocalePathLink>` to output invalid HTML that will render whatever comes after `">xss/`.

### Describe the bug

The bug seems to be caused by `<SwitchLocalePathLink>` defaulting to the current URL parameters, if not set otherwise via `setI18nParams`. The parameters are not being sanitized before they're used in the generated HTML.

![grafik](https://github.com/user-attachments/assets/5e2046c7-202f-4467-8887-971c31b32023)

**Comment by BobbieGoede** [comment]
This is problematic, thanks for reporting! I'll see if I can get this fixed soon and publish a patch release with it.
