### ISSUE TITLE
switchLocalePath returning empty string

### ISSUE THREAD

**Issue by pmnzt** [nuxt-modules/i18n#3051]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.2
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.4
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.3
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/pmnzt/nuxt-i18n-issues

### Describe the bug

As the title, the function is returning an empty string instead of a path

**Comment by BobbieGoede** [comment]
Your project has no pages, so no routes for the module to localize, I have modified your reproduction [here](https://stackblitz.com/edit/pmnzt-nuxt-i18n-issues-rzezrb?file=pages%2Findex.vue,app.vue) and added an index page to demonstrate.

**Comment by pmnzt** [comment]
> Your project has no pages, so no routes for the module to localize, I have modified your reproduction [here](https://stackblitz.com/edit/pmnzt-nuxt-i18n-issues-rzezrb?file=pages%2Findex.vue,app.vue) and added an index page to demonstrate.

ok sorry, did not know that, what about ? https://github.com/nuxt-modules/i18n/issues/3052
