### ISSUE TITLE
Custom route paths are not working with Nuxt 4 directory structure/custom srcDir inside Layers

### ISSUE THREAD

**Issue by Spreizu** [nuxt-modules/i18n#3076]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.13.0`
- CLI Version:      `3.13.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.8.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Reproduction: https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-knvwuy?file=src%2Flayers%2Fcustom-layer%2Fnuxt.config.ts

### Describe the bug

When using the new Nuxt 4 directory structure in Layers with `customRoutes: "config"` the following warning is returned and no valid routes are generated for locales: `[@nuxtjs/i18n]: Couldn't find AnalyzedNuxtPageMeta by NuxtPage (/custom/:slug()), so no custom route for it `.

This occurs, because the pages directory is not resolved correctly in this function: https://github.com/nuxt-modules/i18n/blob/4df3491161138615b0dfb36e3b0d1f8b9987dc11/src/layers.ts#L77

### Additional context

When patching part of the function specified above from:
`const lPath = resolve(project.config.rootDir, l.config.rootDir, l.config.dir?.pages ?? 'pages')`
to:
`const lPath = resolve(project.config.rootDir, l.config.srcDir, l.config.dir?.pages ?? 'pages')`

then everything appears to work correctly.

**Comment by BobbieGoede** [comment]
Sorry for the late response I hope the patch is working fine still. I have just opened a PR with your suggested fix (#3133), which will probably be included it in the next patch release (likely within a week).
