### ISSUE TITLE
`restructureDir` default value unset for v9

### ISSUE THREAD

**Issue by eevinky** [nuxt-modules/i18n#3085]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    -
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      future, compatibilityDate, modules, devtools, i18n
- Runtime Modules:  @nuxtjs/i18n@9.0.0-alpha.1-28747213.ebbc7f4
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-frlapt?file=nuxt.config.ts,package.json,app%2Fapp.vue

### Describe the bug

nuxt.config.ts:
  future: {
    compatibilityVersion: 4,
  },
  compatibilityDate: '2024-08-08',
  
  When using the new directory structure under nuxt 4, when the root directory of i18n is rootDir/i18n, the parsing error
  
  [plugin:vite:import-analysis] Failed to resolve import "../app/locales/en.json" from ".nuxt/i18n.options.mjs". Does the file exist?

**Comment by eevinky** [comment]
According to v9 https://i18n.nuxtjs.org/docs/v9/getting-started There is no restructureDir attribute, 8.5.1 the latest stable version is there, I wonder if v9 is not merged completely

**Comment by BobbieGoede** [comment]
It seems like we haven't set the default value for `restructureDir` yet in v9, which is what it should be according to the docs https://i18n.nuxtjs.org/docs/v9/options/misc#restructuredir.

You can work around this temporarily by setting the options to its default: `restructureDir: 'i18n'` until we have fixed the default value 🙏 Let me know if this solves your issue! And let's keep this issue open while the default value has not been updated.

**Comment by eevinky** [comment]
I have no problem downgrading to 8.5.1,Set up by yourself， Because it has already added the type, because v9 does not currently set a default value, I have not tested whether it is possible to add it by myself, but nuxt.config.ts should also report a type error, and may indeed need to do it yourself

**Comment by BobbieGoede** [comment]
This should get resolved by #3088, you can try out the changes in the PR by installing its preview release with `pnpm add https://pkg.pr.new/@nuxtjs/i18n@3088`.
