### ISSUE TITLE
v9: langDir is prefixing i18n

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/i18n#3156]
### Describe the bug

I got my files within `app/i18n` which was working in v8:

```
i18n: {
    langDir: 'i18n',
}
```

Now in v9 I get an error:

> ERROR  Cannot start nuxt:  ENOENT: no such file or directory, open '/Users/mick/git/my-project/i18n/i18n/de.ts'

If I set langDir to `app/i18n` I get:
> ERROR  Cannot restart nuxt:  ENOENT: no such file or directory, open '/Users/mick/git/my-project/i18n/app/i18n/de.ts'

Therfore cant get v9 to work, app is not starting.

**Comment by BobbieGoede** [comment]
Please check the breaking changes documentation page, you're running into the new directory structure https://i18n.nuxtjs.org/docs/v9/guide/breaking-changes-in-v9#directory-restructure-and-langdir-default-value

If you're still experiencing issues, please provide a minimal reproduction 🙏

**Comment by MickL** [comment]
Thanks for the quick response!

**Comment by MickL** [comment]
@BobbieGoede Just one more note: According to migration guide the i18n.config.ts should now sit in i18n folder. When setting no value in nuxt.config.ts for `vueI18n` then this file will not be found, needs to be set manually to `vueI18n: './i18n/i18n.config.ts'`. Shouldnt it default to i18n folder?

**Comment by BobbieGoede** [comment]
That sounds like a bug, I think I know where the resolution may be going wrong but haven't managed to fix it just yet, may need to open an issue to track this lest I forget.
