### ISSUE TITLE
Property '$t' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps...;

### ISSUE THREAD

**Issue by FlorientPlouvin** [nuxt-modules/i18n#3167]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.14.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@4.3.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

My package json : 

```
  "dependencies": {
    "@heroicons/vue": "^2.1.3",
    "@histoire/plugin-nuxt": "^0.17.17",
    "@histoire/plugin-vue": "^0.17.17",
    "@nuxt/eslint-config": "^0.3.6",
    "@nuxt/test-utils": "^3.12.0",
    "@nuxtjs/i18n": "^8.5.5",
    "@nuxtjs/seo": "^2.0.0-rc.18",
    "@nuxtjs/tailwindcss": "^6.12.1",
    "@pinia/nuxt": "^0.5.1",
    "@tailwindcss/container-queries": "^0.1.1",
    "@vuelidate/core": "^2.0.3",
    "@vuelidate/validators": "^2.0.4",
    "@vueuse/components": "^11.1.0",
    "@vueuse/core": "^11.1.0",
    "@vueuse/nuxt": "^11.1.0",
    "dayjs": "^1.11.11",
    "dotenv": "^16.4.5",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-vitest": "^0.3.26",
    "histoire": "^0.17.17",
    "jwt-decode": "^4.0.0",
    "mitt": "^3.0.1",
    "nuxt": "^3.13.2",
    "nuxt-auth-utils": "^0.4.2",
    "nuxt-snackbar": "^1.0.4",
    "pinia": "^2.1.7",
    "prettier": "^3.2.5",
    "sass": "^1.74.1",
    "tailwind-merge": "^2.4.0",
    "unplugin-auto-import": "^0.17.5",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0",
    "vue-tailwind-datepicker": "^1.7.3",
    "vue-tsc": "^2.1.6",
    "vue3-carousel-nuxt": "^1.1.3",
    "webdriverio": "^8.36.1"
  },
  "devDependencies": {
    "@histoire/plugin-nuxt": "^0.17.17",
    "@histoire/plugin-vue": "^0.17.17",
    "@nuxt/eslint": "^0.3.0-beta.3",
    "@nuxtjs/device": "^3.1.1",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.1",
    "@typescript-eslint/eslint-plugin": "^7.3.1",
    "@typescript-eslint/parser": "^7.3.1",
    "@vitest/browser": "^1.5.2",
    "@vitest/coverage-v8": "^1.4.0",
    "@vitest/ui": "^1.5.2",
    "@vue/test-utils": "^2.4.5",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-vitest": "^0.3.26",
    "happy-dom": "^14.3.1",
    "husky": "^9.0.11",
    "jsdom": "^24.0.0",
    "playwright-core": "^1.42.1",
    "typescript": "^5.4.3",
    "vitest": "^1.5.2"
  },
  "resolutions": {
    "vite-plugin-checker": "0.8.0",
    "vue-tsc": "2.0.29"
  },
  "packageManager": "yarn@4.3.0"
```

### Describe the bug

Just update to nuxt 3.13.2 (started form 3.12.2) and vs-code give me this error  :
`Property '$t' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<{ slides: ISlider[]; class?: string | undefined; sizeClass?: string | undefined; hasGradient?: boolean | undefined; }, {}>, { ChevronLeftIcon: typeof ChevronLeftIcon; ChevronRightIcon: typeof ChevronRightIcon; userStore: typeof userStore; width: typeof width; p...'`

When I want to build my project (with nuxt build), it give me the same error, but no problem in dev mod. 
I also see my translation in dev mod. 

### Additional context

I tried  to create a `vue.d.ts` file and put this inside : 
```
declare module "vue" {
  interface ComponentCustomProperties {
    $t: (key: string, ...params: any[]) => string;
  }
}

```
Yes the `$t` error disapear, but now every emit or called function (in Pinia for exemple) is now an implicit any and building not working.

**Comment by FlorientPlouvin** [comment]
A small repository for reproduction https://github.com/FlorientPlouvin/Reproduction-i18n

**Comment by BobbieGoede** [comment]
I haven't checked it locally yet, but you should change any module augments from `@vue/runtime-core` to `vue`, such as the one here https://github.com/FlorientPlouvin/Reproduction-i18n/blob/main/plugins.d.ts should be like this instead:

```ts
declare module "vue" {
  interface ComponentCustomProperties {
    $device: Device;
    $breakpoints: {
      isMobile: boolean;
      isTablet: boolean;
      isDesktop: boolean;
      isPortable: boolean;
      current: string;
    };
  }
}
```

Augmenting `@vue/runtime-core` breaks other correct augmentations.

**Comment by FlorientPlouvin** [comment]
It's was this ! Thanks you !

**Comment by valterbarros** [comment]
For me it won't works, I follow this link https://github.com/vuejs/language-tools/issues/3372

and created that file .d.ts

```
import type { ComponentCustomProperties } from '@vue/runtime-core';
import type { Composer } from 'vue-i18n';

declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $t: Composer<A, B, C,D,E>['t'];
    $d: Composer<A, B, C,D,E>['d'];
    $tm: Composer<A, B, C,D,E>['tm'];
    $rt: Composer<A, B, C,D,E>['rt'];
  }
}
```

**Comment by BobbieGoede** [comment]
@valterbarros 
Augmenting `@vue/runtime-core` might seem like it works but it will cause issues for other type augmentations. You should make sure your project and its dependencies only augment `vue` for proper types.

**Comment by snowdream** [comment]
What about this?

# vue-i18n.d.ts

```
import Vue from "vue";

declare module "@vue/runtime-core" {
  export interface ComponentCustomProperties {
    $t: (key: string, ...args: any[]) => string;
    $d: (key: string, ...args: any[]) => string;
    $tm: (key: string, ...args: any[]) => string;
    $rt: (key: string, ...args: any[]) => string;
  }
}
```

**Comment by BobbieGoede** [comment]
@snowdream 
You should **not** augment `@vue/runtime-core`, this will cause issues, see the documentation on how to augment global properties https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties

Edit: missed an essential work
