### ISSUE TITLE
npm code of v8.5.5 not up to date

### ISSUE THREAD

**Issue by dm-heinze** [nuxt-modules/i18n#3181]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.1.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Go to https://www.npmjs.com/package/@nuxtjs/i18n/v/8.5.5?activeTab=code and compare the code with the commits of the the release v8.5.5 https://github.com/nuxt-modules/i18n/compare/v8.5.5...main 

### Describe the bug

Last commits on github are from Oct 10, 2024, but version 8.5.5 was published on npm on Sep 21, 2024. So the code on npm is not up to date.

**Comment by derHodrig** [comment]
In my case 8.5.5 is totally broken. If I use a config file, the plugin wont run anything. If I put the configs inside the nuxt.config > i18n it works.

**Comment by BobbieGoede** [comment]
You're comparing the main (v9) branch to the latest v8 release tag, but you're right there are some commits that haven't been released in v8 yet on the v8 branch. I'll release these soon.

**Comment by BobbieGoede** [comment]
Sorry for the delay, I was still on holiday! I've just published a patch release for v8, my priority is to get a stable v9 release out in the coming days/weeks so I hope you could give the release candidates a try as well, feedback would be invaluable for stability. 🙏
