### ISSUE TITLE
npm run generate produces absolute path to my language files

### ISSUE THREAD

**Issue by kokhoor** [nuxt-modules/i18n#3188]
### Environment

Nuxt:: ^3.12.2
@nuxtjs/i18n: ^8.5.5

### Reproduction

My nuxt.config.js:

```
modules: [
  ...
  "@nuxtjs/i18n",
  ...
],
i18n: {
    locales: [
      {
        code: "en",
        file: "en.json"
      },
      {
        code: "cn",
        file: "cn.json"
      }
    ],
    lazy: true,
    strategy: "no_prefix",
    langDir: "lang",
    defaultLocale: "en"
  },
```

Then I generate using npm run generate.

### Describe the bug

I have following nuxt.config.js (snippet)

```
modules: [
  ...
  "@nuxtjs/i18n",
  ...
],
i18n: {
    locales: [
      {
        code: "en",
        file: "en.json"
      },
      {
        code: "cn",
        file: "cn.json"
      }
    ],
    lazy: true,
    strategy: "no_prefix",
    langDir: "lang",
    defaultLocale: "en"
  },
```

When I do an npm run generate, my index.html content for the nuxt config portion has configLocales that contains absolute path:

```
configLocales:[{code:"en",files:["C:/mynuxt/en.json"]},{code:"cn",files:["C:/mynuxt/lang/cn.json"]}]
```

How do I fix this?

**Comment by adesombergh** [comment]
+1, I have my personal local file path hard-coded into all generated pages on a production site (yeety.be, just search "/Users" in the source-code of any page)

**Comment by adesombergh** [comment]
Realized this thanks to Google Search Console detecting a bunch of 404

**Comment by lceihen** [comment]
+1, and how can i resolve this problem
