### ISSUE TITLE
Disable locale for some pages with setI18nParams

### ISSUE THREAD

**Issue by Tofandel** [nuxt-modules/i18n#3191]
### Describe the feature

Usually to define parameters translation we use `setI18nParams({fr: {param: 'foo'})`, but what if we want to disable a locale for a specific page dynamically (for example because the backend said that the page is not yet translated)

It seems doing `setI18nParams({fr: false)` could be a solution but currently with this it just acts like if the function was not even called

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [x] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by BobbieGoede** [comment]
If I understand correctly this sounds like a feature that would resolve #2782, is that right?

**Comment by Tofandel** [comment]
Yeah that's actually a duplicate, the title of that issue is not very descriptive of the problem but I guess I'll close this one and continue the discussion there

**Comment by BobbieGoede** [comment]
Agreed the title is not very descriptive, I've updated it to something that more closely matches yours, hopefully it will help others find it too 🙏
