### ISSUE TITLE
LocaleObject type is no longer exported in v9

### ISSUE THREAD

**Issue by maxdzin** [nuxt-modules/i18n#3201]
### Environment

Nuxt project info:                                                                            11:04:15 PM

------------------------------
- Operating System: Linux
- Node Version:     v22.11.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.6.1, @nuxtjs/color-mode@3.5.2, @nuxtjs/google-fonts@3.2.0, @nuxtjs/i18n@9.0.0, @nuxtjs/robots@4.1.11, @nuxtjs/tailwindcss@6.12.2, @pinia/nuxt@0.7.0, @vueuse/nuxt@11.2.0, nuxt-security@2.0.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-z4bplq?file=types%2Flocale.ts
Go to `types/locale.ts` file and check the `LocaleObject` import...
or launch `pnpm typecheck` in terminal to see that error.

### Describe the bug

`LocaleObject` is no longer exported from the `@nuxtjs/i18n` module (v9).

### Logs

error TS2614: Module '"@nuxtjs/i18n"' has no exported member 'LocaleObject'. Did you mean to use 'import LocaleObject from "@nuxtjs/i18n"' instead?

2 import type { LocaleObject } from '@nuxtjs/i18n'

**Comment by Xenossolitarius** [comment]
Exported type for locales in general is {}[]. And in schema file it looks like the generation failed

**Comment by BobbieGoede** [comment]
Hmm I guess we should be exporting this if we originally did this, I can see the value of having it available for end users though I don't think this was documented. 

Not sure if it should be the generated narrowed type (locale code string literals) or a more permissive version, or both?

@Xenossolitarius 
I'm not sure what you mean, can you provide more information?

**Comment by Xenossolitarius** [comment]
@BobbieGoede Sorry don't have the exact snippets but the types remained actually the same. My bad. But the template looks like this:


.nuxt > types > schema.d.ts
```
   i18n: {
      baseUrl: string,

      defaultLocale: string,

      defaultDirection: string,

      strategy: string,

      lazy: boolean,

      rootRedirect: any,

      routesNameSeparator: string,

      defaultLocaleRouteNameSuffix: string,

      skipSettingLocaleOnNavigate: boolean,

      differentDomains: boolean,

      trailingSlash: boolean,
 
      configLocales: Array<{

      }>,

      locales: {
         ro: {
            domain: any,
         },

         en: {
            domain: any,
         },

         hr: {
            domain: any,
         },
      },

```

where configLocales seems like the generation of types missfired? Maybe it just looks like that bcs of templating
