### ISSUE TITLE
If there is `|` in the information, the subsequent information will not be displayed.

### ISSUE THREAD

**Issue by lxccc812** [nuxt-modules/i18n#3203]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.9.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.13.1
- Builder:          -
- User Config:      modules, ssr, runtimeConfig, app, css, devServer, devtools, device, experimental, gtm, i18n, nitro, pwa, site, sitemap
- Runtime Modules:  @nuxtjs/device@3.1.1, @nuxtjs/i18n@9.0.0, @nuxtjs/sitemap@5.0.4, @unocss/nuxt@0.57.7, @vite-pwa/nuxt@0.6.0, @vueuse/nuxt@10.7.2, @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt-lodash@2.5.3, nuxt-swiper@1.2.2
- Build Modules:    -
------------------------------

### Reproduction

None

### Describe the bug

When I internationalize the title information, my title information contains the `|` symbol, but the information after the `|` is not displayed.

![Image](https://github.com/user-attachments/assets/dd019235-a25f-4893-9802-e6e8edf60232)
![Image](https://github.com/user-attachments/assets/a3a7423f-927e-4925-a81e-6086d87d50b1)
![Image](https://github.com/user-attachments/assets/b22dfc4c-1b6c-404b-ade2-fc874644d532)

**Comment by BobbieGoede** [comment]
The `|` is used for pluralization, see https://vue-i18n.intlify.dev/guide/essentials/pluralization.html.

You may be able to wrap it in brackets like `{'|'}` as described in the literal interpolation section https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation, but I can't easily test this without a reproduction.

Hope this resolves your issue, if you're still experiencing issues, please open an issue on the repository of vue-i18n as this is not something this module has control over 🙏
