### ISSUE TITLE
Problems with tsx template after updating to v9

### ISSUE THREAD

**Issue by cernymatej** [nuxt-modules/i18n#3208]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.13.1`
- CLI Version:      `3.13.1`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.9.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxtjs/i18n@9.0.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ffpcjt?file=nuxt.config.ts,components%2FTestComponent.vue,app.vue

### Describe the bug

After upgrading from `8.5.3` to `v9`, I encountered several pre-transform errors. In my main project, it was the following error message: `Pre-transform error: '>' expected.` I tracked this down to an issue with parsing TSX templates.

While stripping down the project to identify the root cause, I also encountered the following errors:
```
ERROR  Internal server error: ',' expected.
   10:26:17 AM
  Plugin: unplugin-vue-i18n:directive
```
and
```
Pre-transform error: Type expected.
```
The last one is present in the minimal reproduction linked above.

This issue wasn’t present in `8.5.3`. I suspect it might be an upstream bug. However, I'm not sure where to report it.

### Additional context

This seems to work fine:
```ts
<script lang="ts">
export default defineComponent((props, ctx) => {
  return () => h('div', ['Test'])
})
</script>
```

**Comment by BobbieGoede** [comment]
This is likely an upstream bug as you suspect, probably `unplugin-vue-i18n`, could you open an issue on its repository? https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n 🙏

Let's leave this issue open while the upstream issue exists, there's probably more users running into this while updating.

**Comment by cernymatej** [comment]
For anyone interested in tracking this issue, here is the link: https://github.com/intlify/bundle-tools/issues/402

**Comment by cernymatej** [comment]
For anyone encountering this same issue, the recommended solution is to update `@nuxtjs/i18n` to `9.1.1` and disable the directive optimizations like this:
```ts
// nuxt.config.ts
i18n: {
  bundle: {
    optimizeTranslationDirective: false
  }
}
```

Related issues / PRs:
https://github.com/intlify/bundle-tools/issues/423
https://github.com/intlify/bundle-tools/issues/402
https://github.com/intlify/bundle-tools/pull/414
https://github.com/nuxt-modules/i18n/pull/3256

**Comment by bloor** [comment]
YES. This works for me as well. Thankyou.
Nuxt3 3.17.1
`@nuxtjs/i18n` to `9.5.3
