### ISSUE TITLE
Internal server error: Failed to resolve import "../i18n/locales/en-US.json" from ".nuxt/i18n.options.mjs" on following lazy-load translation guide

### ISSUE THREAD

**Issue by arun-mani-j** [nuxt-modules/i18n#3213]
### Environment

- Operating System: `Linux`
- Node Version:     `v22.11.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.9.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.12.2`, `@nuxtjs/i18n@9.0.0-rc.2`
- Build Modules:    `-`

### Reproduction

1. Follow https://i18n.nuxtjs.org/docs/guide/lazy-load-translations as it is.
2. On running with `npm run dev`, you will  get error: 
```
Internal server error: Failed to resolve import "../i18n/locales/en-US.json" from ".nuxt/i18n.options.mjs". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/path/to/project/.nuxt/i18n.options.mjs:11:66
```

### Describe the bug

From what I can see, `i18n` expects the translation files to be under `i18n/locales` directory, so moving the files from `i18n` to `i18n/locales` fixes the issue.

So just updating the example directory structure is enough. If confirmed, I'm happy to PR the fix in docs 😅 .

### Logs

```shell

```

**Comment by userquin** [comment]
PR welcome 🙏

**Comment by mghase** [comment]
stil get the same error in nuxt 4
