### ISSUE TITLE
Error pre-transform

### ISSUE THREAD

**Issue by initmn** [nuxt-modules/i18n#3228]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.15.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @unocss/nuxt@0.64.0, v-wave/nuxt, @vee-validate/nuxt@4.14.7, vue-recaptcha/nuxt, @vueuse/nuxt@11.2.0, @pinia/nuxt@0.7.0, @nuxt-alt/auth@3.1.7, nuxt-bezier@1.12.0, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxtjs/google-fonts@3.2.0, @nuxtjs/i18n@9.0.0
- Build Modules:    -
------------------------------

                                                                                                                                                     12:46:02 PM
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com

### Reproduction

-

### Describe the bug

error when upgrade to latest version

### Additional context

![Image](https://github.com/user-attachments/assets/943a0816-8dcd-4b7c-9ecb-39d7e48ef9e8)

config

```js
 i18n: {
    langDir: 'locales',
    lazy: true,
    locales: [
      {
        code: 'id',
        language: 'id-EN',
        file: 'id.json',
        name: 'Indonesian',
      },
      {
        code: 'en',
        language: 'en-US',
        file: 'en.json',
        name: 'English',
      },
    ],
    defaultLocale: 'id',
    detectBrowserLanguage: false,
  }


### Logs

```shell

```

**Comment by initmn** [comment]
Same error :/

https://stackblitz.com/edit/github-pq3cpy?file=nuxt.config.ts

**Comment by BobbieGoede** [comment]
The default folder structure has changed in v9, either temporarily disable it with `restructureDir: false` or move your i18n files/directories inside a `i18n` directory in the root directory. See the migration guide page for more details on how to migrate from v8 to v9 https://i18n.nuxtjs.org/docs/guide/migrating.

**Comment by kengres** [comment]
I basically created a new folder `i18n` in rootDir and moved my `locales` folder into it.
