### ISSUE TITLE
Argument of type '"share-p-slug"' is not assignable to parameter of type 'keyof RouteNamedMap | undefined'

### ISSUE THREAD

**Issue by lxccc812** [nuxt-modules/i18n#3230]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.17.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.11.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/device@3.2.4, @nuxtjs/i18n@9.0.0, @nuxtjs/sitemap@5.3.5, @unocss/nuxt@0.57.7, @vite-pwa/nuxt@0.6.0, @vueuse/nuxt@10.11.1, @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt-lodash@2.5.3, nuxt-swiper@1.2.2
- Build Modules:    -
------------------------------

### Reproduction

None

### Describe the bug

What happened is, after I used `nuxt/i18n`, my useRoute was not resolving my routes correctly.
![Image](https://github.com/user-attachments/assets/688873d2-58dd-4b39-9269-df091de244f5)

And prompted me to use `____en`.
![Image](https://github.com/user-attachments/assets/6be22378-3432-452b-a11a-c72530b3facc)

### Additional context

i18n config
```ts
i18n: {
        baseUrl: process.env.NUXT_PUBLIC_BASE_URL,
        locales: [
            {
                code: 'en',
                language: 'en-US',
                file: 'en-US.ts',
                domain: process.env.NUXT_PUBLIC_BASE_URL,
            },
            {
                code: 'ja',
                language: 'ja-JP',
                file: 'ja-JP.ts',
                domain: 'https://jp.example.com',
            },
        ],
        defaultLocale: 'en',
        lazy: true,
        differentDomains: true,
    },
```

### Logs

```shell

```

**Comment by BobbieGoede** [comment]
This is expected behavior, this module localizes the routes in your project so these can differ depending on your routing strategy. We have composables that accept non localized parameters to provide similar functionalities, in your example you may want to try out [`useLocaleRoute`](https://i18n.nuxtjs.org/docs/composables/use-locale-route).
