### ISSUE TITLE
Incorrect merging of locales when using Nuxt Layers

### ISSUE THREAD

**Issue by cernymatej** [nuxt-modules/i18n#3232]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `^3.14.159`
- CLI Version:      `3.15.0`
- Nitro Version:    `-`
- Package Manager:  `pnpm@9.9.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/cernymatej/i18n-locale-merging

### Describe the bug

I've noticed that the merging strategy of the i18n configuration when using Nuxt Layers is not ideal. 

Currently, if I define `locales` in a layer project (let's refer to it as `layer/`), these locales are merged into all projects extending this layer, regardless of whether the extending project specifies the `locales` option or not.

Consider the following setup:
- `project-a/` (should only have the "en" locale).
- `project-b/` (should have both "en" and "sk" locales).

We want to share some common translations between all projects, so we need to configure `locales` with file names in `layer/` like so:
To share some common translations between all projects, we need to configure `locales` with file names in `layer/` like this:

```ts
// layer/nuxt.config.ts
// ...
i18n: {
    locales: [
        {
            code: 'sk',
            language: 'sk-SK',
            name: 'Slovak',
            file: 'sk-SK.json5',
        },
        {
            code: 'en',
            language: 'en-US',
            name: 'English',
            file: 'en-US.json5',
        },
    ],
```

Without this configuration, the locale files will not be registered, and the projects extending `layer/` would not have access to the shared translations.

Now, in `project-a/`, we specify only one locale:
```ts
// project-a/nuxt.config.ts
// ...
extends: ['../layer'],
i18n: {
    locales: [
        {
            code: 'en',
            language: 'en-US',
            name: 'English',
            file: 'en-US.json5',
        },
    ],
},
```
However, even though we explicitly specified only one locale, all locales defined in `layer/` are still available in `project-a/`.

This behavior is undesirable because it forces all locales from the layer to be present, even when they are not needed or intended for a specific project.
The layer could be a component library, with translated `aria` attributes for a lot of languages. However, the projects extending this layer will usually only allow a few locales.

### Logs

```shell

```

**Comment by warflash** [comment]
Hey, this sounds a lot like https://github.com/nuxt-modules/i18n/issues/3047

**Comment by cernymatej** [comment]
Yeah, you're correct. Thanks for pointing it out!
