### ISSUE TITLE
Pre-transform error: Cannot read properties of null (reading 'parse')

### ISSUE THREAD

**Issue by kieranwv** [nuxt-modules/i18n#3241]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.2
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/i18n@9.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ktam3z?file=nuxt.config.ts

### Describe the bug

![Image](https://github.com/user-attachments/assets/8c0d189d-3812-4de8-8aab-9806be6d1844)

### Logs

```shell

```

**Comment by BobbieGoede** [comment]
We're still investigating this issue, so far it seems this issue is only present in a Stackblitz, are you able to reproduce this locally as well?

@userquin managed to narrow it down to `@vitejs/vite-plugin-vue` and we're tracking that here https://github.com/vitejs/vite-plugin-vue/issues/474

**Comment by kieranwv** [comment]
> We're still investigating this issue, so far it seems this issue is only present in a Stackblitz, are you able to reproduce this locally as well?
> 
> [@userquin](https://github.com/userquin) managed to narrow it down to `@vitejs/vite-plugin-vue` and we're tracking that here [vitejs/vite-plugin-vue#474](https://github.com/vitejs/vite-plugin-vue/issues/474)

Thank you. I also encountered this problem locally, the repo address is: [https://github.com/starter-collective/starter-nuxt3](https://github.com/starter-collective/starter-nuxt3).

**Comment by userquin** [comment]
@BobbieGoede in the meantime, maybe we should fix the error in the vite directive plugin, will not work if using `v-t` in the root nuxt component on vite warmup (check my closed PR): https://github.com/intlify/bundle-tools/pull/421

(I can restore the branch and submit a new PR)

**Comment by userquin** [comment]
@kieranwv you can patch i18n module if you're not using `v-t` directive: check https://github.com/nimbus-zone/nimbus/pull/3

**Comment by sent** [comment]
Hello,

I've been trying hard time with this issue. Can the proposed fix merged, please?

Thanks!

**Comment by BobbieGoede** [comment]
This should be resolved in `9.1.1` so I'm closing this, let me know if you're still experiencing this after updating and I'll reopen!
