### ISSUE TITLE
Some routes are missing for default language when using multiDomainLocales and prefix_except_default

### ISSUE THREAD

**Issue by e-kravtsov** [nuxt-modules/i18n#3248]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.4
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.14.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/i18n@9.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/e-kravtsov/-nuxtjs-i18n-missing-default-routes

1. run pnpm dev
2. try to open one of these routes: 
/my-pages/my-information
/my-pages/my-contacts
/my-pages/order-history
/my-pages/reminders
/order-confirmed/orderId?
/order-confirmed/orderNumber?
/order-tracking/id?
3. route slug will open up instead of them although /en/my-pages/my-information works fine. In vue devtools there are 218 routes, but 225 routes expected, other nested routes work fine, for example, /flower-delivery/florist-in.

### Describe the bug

Some routes are missing for the default lanugage without language prefix. But they work fine when using language prefix. These routes are missing in the vue devtools as well

### Logs

```shell

```

**Comment by persimmmon** [comment]
I've got the same. This is the only reason why we are not using this feature in our project

**Comment by Vincentdevreede** [comment]
[New release](https://github.com/nuxt-modules/i18n/releases/tag/v9.1.1) is available @e-kravtsov @persimmmon! 🚀 
Hope this will fix your problems! 👍
