### ISSUE TITLE
[ERROR] No matching export in "node_modules/.pnpm/@intlify+shared@10.0.4/node_modules/@intlify/shared/dist/shared.mjs" for import "create"

### ISSUE THREAD

**Issue by sumomo015** [nuxt-modules/i18n#3249]
### Environment

- Operating System: Darwin
- Node Version:     v22.11.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.14.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/i18n@9.1.0
- Build Modules:    -

### Reproduction

https://github.com/sumomo015/nuxt-i18n-reproduction

1. `pnpm install`
2. `pnpm run dev`

Please let me know if any additional information is needed.

### Describe the bug

When starting the Nuxt development server, I encounter the following error message:

```
 [ERROR] No matching export in "node_modules/.pnpm/@intlify+shared@10.0.4/node_modules/@intlify/shared/dist/shared.mjs" for import "create"

    node_modules/.pnpm/@intlify+core-base@10.0.5/node_modules/@intlify/core-base/dist/core-base.mjs:6:42:
      6 │ import { getGlobalThis, hasOwn, isNumber, create, isObject, isString, isBoolean, warn, format as format$1, isFunction, isPromise, isArray...
        ╵
```

This issue occurs while trying to use the i18n module in my Nuxt project.

### Logs

```shell

```

**Comment by sumomo015** [comment]
I was able to avoid the error by setting the following configuration in pnpm:

```json
{
  "pnpm": {
    "overrides": {
      "@intlify/shared": "10.0.5",
      "@intlify/core": "10.0.5"
    }
  }
}
```

**Comment by vinoddotcom** [comment]
Same issue here.

**Comment by davinma** [comment]
The same error occurred. I downgraded `@nuxtjs/i18n` to 8.5.1 as a temporary workaround.

It seems the issue is due to a mismatch in the `@intlify/shared` version?
https://github.com/intlify/vue-i18n/issues/1637

**Comment by BobbieGoede** [comment]
We found the source of the issue and hopefully it's resolved now, can you try refreshing your lockfiles?

The issue was that the `10.0.5` releases of vue-i18n and intlify dependencies were not tagged as `latest` but as `stable`, causing npm to not consider it compatible with the `^10.0.0` version range 🤔

Related https://github.com/intlify/vue-i18n/issues/2037#issuecomment-2507490733

**Comment by sumomo015** [comment]
@BobbieGoede 

I confirmed that the issue was resolved after updating the lockfiles. Thank you for your prompt response. ❤️
