### ISSUE TITLE
How to use `NuxtLinkComponent` with `<component :is="" />`

### ISSUE THREAD

**Issue by ThibaudDauce** [nuxt-modules/i18n#3257]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v23.1.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/content@2.13.4, @nuxt/eslint@0.5.7, @nuxt/icon@1.7.2, @nuxt/image@1.8.1, @nuxtjs/i18n@8.5.6, @nuxtjs/tailwindcss@6.12.2, @sentry/nuxt/module@8.38.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-2seyxf?file=pages%2Findex.vue

### Describe the bug

I want to be able to import `NuxtLinkLocale` but it doesn't seems to be exported by anything. `import { NuxtLinkLocale } from '@nuxtjs/i18n'` doesn't work.

My goal is to have a custom button for my application that can be either a `button`, a `a` or a `NuxtLinkLocale` based on some prop. 

### Logs

```shell

```

**Comment by userquin** [comment]
iirc you need to register the component globally in the vue app

cannot use `custom` attribute using binding props? iirc `NuxtLink` can be customized, I guess `NuxtI18nLink` should have also this feature

https://nuxt.com/docs/api/components/nuxt-link#routerlink

**Comment by BobbieGoede** [comment]
I'm not sure if we're exporting the component explicitly at the moment, that's something we will need to take a look at. Using `const NuxtLinkLocale = resolveComponent('NuxtLinkLocale')` should work for your use case as a workaround 🙏

**Comment by ThibaudDauce** [comment]
I found we can import it with `import { NuxtLinkLocale } from '#components'`
