### ISSUE TITLE
Error:  Nuxt Build Error: [unplugin-vue-i18n:directive] (0 , _typescriptEstree.parse) is not a function

### ISSUE THREAD

**Issue by elyesnext** [nuxt-modules/i18n#3260]
### Environment

------------------------------
- Operating System: Ubuntu-latest
- Node Version:     v22.7.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.12.1
- Builder:          -
- User Config:      app, runtimeConfig, devtools, css, components, plugins, imports, hooks, experimental, typescript, sourcemap, vue, vite, build, modules, hub, nitro, i18n, compatibilityDate
- Runtime Modules:  @vueuse/nuxt@10.11.0, @nuxtjs/device@3.1.1, @pinia/nuxt@0.5.2, nuxt-mongoose@1.0.6, @nuxtjs/i18n@9.0.0, @nuxthub/core@0.8.7
- Build Modules:    -
------------------------------

### Reproduction

name: Deploy with NuxtHub CLI
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '8.7.0'
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.7.0
          cache: 'pnpm'
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install

      - name:  Deploy with nuxthub
        run: npx nuxthub deploy
        env:
          NUXT_HUB_PROJECT_KEY: ${{ secrets.NUXT_HUB_PROJECT_KEY}}
          NUXT_HUB_USER_TOKEN: ${{ secrets.NUXT_HUB_USER_TOKEN }}

### Describe the bug

Build error traces back to @nuxtjs/i18n dependencies

### Logs

```shell

```

**Comment by BobbieGoede** [comment]
I have just published a new release, could you check if you're still experiencing this issue after updating? 🙏

**Comment by elyesnext** [comment]
updating pnpm version to latest seems to fix this somehow, marking the issue as closed!
