### ISSUE TITLE
Unsure how to access t outside of setup

### ISSUE THREAD

**Issue by JaeTLDR** [nuxt-modules/i18n#3265]
Hi all, i'm sure this is obvious but i haven't bean able to work it out. 

I am trying to use translations inside ts files in utils, these files are objects used later in components to render text in the various languages. 

I have trried using the #i18n  import ,  importing the i18n config, using useNuxtApp.$i18n and none of these have worked for obvious reasons. 

Thanks in advanced

**Comment by JonathanXDR** [comment]
Is this what you were looking for?

app.vue:
```vue
<template>
  <div>
    Translation from i18n:
    {{ t('hello') }}
    <br>
    Translation from util:
    {{ getTranslation() }}
  </div>
</template>

<script setup lang="ts">
const { t } = useI18n()
</script>
```

utils/index.ts:
```ts
export const getTranslation = () => {
  const { t } = useI18n()
  return {
    translation: t('hello'),
  }
};
```

i18n/locales/de.json:
```json
{
  "hello": "Deutsches hallo"
}
```

i18n/locales/en.json:
```json
{
  "hello": "English hello"
}
```

nuxt.config.ts:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  modules: ['@nuxtjs/i18n'],

  i18n: {
    defaultLocale: 'de',
    locales: [
      {
        code: 'de',
        file: 'de.json'
      },
      {
        code: 'en',
        file: 'en.json'
      },
      
    ],
  }
})
```

**Comment by JaeTLDR** [comment]
@JonathanXDR Yes thank you! i think my core issue was having my data at the top level of my utile file. i used useI18n() and made a simple function to return my  data as needed and it is working correctly.  I feel a bit silly for not putting this together myself.

**Comment by JonathanXDR** [comment]
@JaeTLDR I'm glad the issue was resolved! If everything is working as expected now, could you kindly close this issue? It helps keep the repository organized and makes it easier for others to find relevant topics. Thanks, and happy coding! :)
