### ISSUE TITLE
i am unable to set up multi domain locales

### ISSUE THREAD

**Issue by zecar** [nuxt-modules/i18n#3287]
```
i18n: {
      langDir: 'lang',
      multiDomainLocales: true,
      strategy: 'prefix_except_default',
      locales: [
      {
            code: 'en',
            iso: 'en-US',
            name: 'English',
            file: 'en-US.ts',
            domains: ['domain.com', 'domain.ro', 'domain.it'],
            defaultForDomains: ['domain.com']
      },
      {
            code: 'ro',
            iso: 'ro-RO',
            name: 'Română',
            file: 'ro-RO.ts',
            domains: ['domain.com', 'domain.ro', 'domain.it'],
            defaultForDomains: ['domain.ro']
      },
      {
            code: 'it',
            iso: 'it-IT',
            name: 'it',
            file: 'it-IT.ts',
            domains: ['domain.com', 'domain.ro', 'domain.it'],
            defaultForDomains: ['domain.it']
      },
      ],
      detectBrowserLanguage: {
            useCookie: true,
            cookieKey: 'user_language',
            redirectOn: 'root',
      },
},
```

I'm using this setup.. I need the language to be in cookie

With this config, if i go to domain.ro i get domain.ro/en and if i switch the lang i have domain.ro/ro instead of just domain.ro

unsure of what to do..

**Comment by karhow** [comment]
bro. i have same problem, how to fix it

**Comment by zecar** [comment]
> bro. i have same problem, how to fix it

I just dropped it and used a .env file variable because i have separate instances for each domain

then i'm using a plugin to read the cookie and set the appropriate language per domain.. something like this


```
export default defineNuxtPlugin(({ $pinia, $i18n }) => {
  const cookieStore = useCookieStore($pinia)
  cookieStore.init()

  const runtimeConfig = useRuntimeConfig()
  let currentLanguage = cookieStore.getCookieValue('user_language')
  if (!currentLanguage) {
    currentLanguage = runtimeConfig.public.instanceLanguage ?? 'en'
    cookieStore.setCookie('user_language', currentLanguage)
  }

  $i18n.setLocale(currentLanguage)
})
```

**Comment by karhow** [comment]
> > bro. i have same problem, how to fix it
> 
> I just dropped it and used a .env file variable because i have separate instances for each domain
> 
> then i'm using a plugin to read the cookie and set the appropriate language per domain.. something like this
> 
> ```
> export default defineNuxtPlugin(({ $pinia, $i18n }) => {
>   const cookieStore = useCookieStore($pinia)
>   cookieStore.init()
> 
>   const runtimeConfig = useRuntimeConfig()
>   let currentLanguage = cookieStore.getCookieValue('user_language')
>   if (!currentLanguage) {
>     currentLanguage = runtimeConfig.public.instanceLanguage ?? 'en'
>     cookieStore.setCookie('user_language', currentLanguage)
>   }
> 
>   $i18n.setLocale(currentLanguage)
> })
> ```

Thank you for your reply
