### ISSUE TITLE
Per-page translations

### ISSUE THREAD

**Issue by alexgrozav** [nuxt-modules/i18n#498]
### What problem does this feature solve?

I have lots of documentation pages with non-repeating text blocks.

I'd like to be able to load the translations for these respective pages only when accessing them. 

This would immediately improve a site's loading speed.

### What does the proposed changes look like?

The way I see this, a good solution would be to have the same file structure you have in pages, but inside of the `lang` folder.

If you'd have `pages/about.vue`, the corresponding translations would be `lang/en/about.js` or  `lang/fr/about.js`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c329">#c329</a>)</em></sub></div>

**Comment by rchl** [comment]
Per-page translations are supported. Not exactly the way you are asking for but have a look here: https://nuxt-community.github.io/nuxt-i18n/vue-i18n-loader.html#vue-i18n-loader

**Comment by remychvn** [comment]
> Per-page translations are supported. Not exactly the way you are asking for but have a look here: https://nuxt-community.github.io/nuxt-i18n/vue-i18n-loader.html#vue-i18n-loader

Does this feature allow several translation files per language? Are they loaded only when the translation strings are going to be displayed?

**Comment by alexgrozav** [comment]
> Per-page translations are supported. Not exactly the way you are asking for but have a look here: https://nuxt-community.github.io/nuxt-i18n/vue-i18n-loader.html#vue-i18n-loader

That might be a good solution to my problem, thank you! Do you know if vue-18n-loader translations are lazy-loaded?

**Comment by rchl** [comment]
As far as I know, they are bundled with that particular page so loaded as lazily as it gets.

**Comment by rchl** [comment]
Not per-locale lazily though. All locales are loaded at once.

**Comment by alexgrozav** [comment]
I thought so. It would be amazing if it would be lazy-loading per locale the way it does with nuxt-i18n (fallback+current). I suppose the feature request should remain open, then..

**Comment by alex-chuev** [comment]
I would like to help with the implementation, and I already have different ideas on how to implement this. What is the best way to start work? Do this by myself or discuss implementation with someone?

**Comment by rchl** [comment]
@alex-chuev Feel free to discuss it here or in Discord with me (rafal#0842)

**Comment by alex-chuev** [comment]
1. After some thinking process I have figured out that it is possible to load additional translations using asynchronous imports or regular fetch/ajax request within `asyncData` method and register them using `setLocaleMessage` method for a current locale.

2. Also it is possible using asynchronous imports load whole components for different locales:
   ```
   components: {
     AboutUsEn: () => import('...'),
     AboutUsRu: () => import('...'),
     AboutUsDe: () => import('...'),
   },
   ```
   And inside the template we can 
   ```
   <div class="about-us">
     <AboutUsRu v-if="ru" />
     <AboutUsDe v-else-if="de" />
     <AboutUsEn v-else />
   </div>
   ```
   It's quite handful when translated content contains different links, images and so on.

Both the approaches solve all my needs so I decided not to waste time on an additional solution.

**Comment by alexgrozav** [comment]
@alex-chuev In my opinion, this approach is hard to maintain. If it works for you, that's great, but: 
- If you ever add another language, you'll need to add a new component in each and every place you use translations. 
- You will need to maintain multiple component markups. Changing a design aspect in one component will require changes in all the other ones as well.

**Comment by alex-chuev** [comment]
@alexgrozav What do you think about the first point? When we load missing translations in `asyncData` method on demand, merge them with already loaded translations and save the result by `setLocaleMessage`.

**Comment by alexgrozav** [comment]
That's actually a good workaround for the issue. Do you have access to the active locale at that time?

**Comment by alex-eri** [comment]
@alex-chuev where are `mergeLocaleMessage` docs?

**Comment by alex-eri** [comment]
Can i combine per page `<i18n>` and langDir: 'lang/' ?

**Comment by tvld** [comment]
Why not set lazy loading language components same format as in nuxt.config ? :+1: 
```js
<script>
export default {
  i18n: {
    locales: [
      {
        name: 'English',
        code: 'en',
        iso: 'en-US',
        file: 'en.js'
      },
      {
        name: 'Nederlands',
        code: 'nl',
        iso: 'nl-NL',
        file: 'nl.js'
      }
    ],
    lazy: true,
    langDir: 'assets/lang/',
    defaultLocale: 'en'
  },
```
This would not only solve lazy loading but also different fallback per page, which I happen to have use case for ... ;)

**Comment by tvld** [comment]
Changed to .coffee files in my comment as that is what we use ))

**Comment by yakovyarmo** [comment]
I there any progress or way to do that?

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
