### ISSUE TITLE
Warnings in console after ignore route in-component

### ISSUE THREAD

**Issue by Jassmin586** [nuxt-modules/i18n#710]
My app have got two languages (en and ar). To set only one language in specific page I used 'in-component' option:

```
nuxtI18n: {
    locales: ['en']
},
```
After that I have a page with only en language, that's great but also a lot of warnings in console like

![image](https://user-images.githubusercontent.com/19594765/82032953-53032100-969c-11ea-88e9-09401371d2af.png)

How properly can I set one language for page without warnings?

**Comment by rchl** [comment]
This is probably triggered because you are language selector somewhere on the page that calls  `localePath` or `switchLocale` with those other locales.

You'd need to show the code that triggers those warnings, then I might be able to advise more.

**Comment by Jassmin586** [comment]
I commented all `localePath` and `switchLocale` in project and still the same.

Simple reproduce:
[https://codesandbox.io/s/710-nuxt-i18n-vqgsx?file=/pages/about.vue](https://codesandbox.io/s/710-nuxt-i18n-vqgsx?file=/pages/about.vue)

Turn to Console and click 'About' link on homepage.

![image](https://user-images.githubusercontent.com/19594765/82065628-a4c49f00-96ce-11ea-9623-6353664310e6.png)

**Comment by rchl** [comment]
Could be also coming from `seo` functionality if you have that enabled.
But I will look into it later (can't right now).

**Comment by rchl** [comment]
Yes, those are triggered from seo functionality (`seo: true`).
I'll check later if I can do something about it.

**Comment by matsrietdijk** [comment]
@rchl this warning it triggered even more when `seo: true`, thats true. But the real issue is `loadAndSetLocale` which doesn't consider either filtering locale on the component as @Jassmin586 did above or the possiblilty of setting `nuxtI18n: false` on the component.

So even when disabling seo all together this warning will still be thrown on initial load and any time you programatically switch the locale with `$i18n.setLocale(..)` on a page configured like this.

**Comment by ozgurdemir** [comment]
Any updates on this? I'm running into the same issue. Probably related to this but I'd also like to remove the language switcher on pages which don't have that language enabled. It seems i18n does not have any variable stating which languages are actually available for the actual page.

**Comment by Menark** [comment]
The same issue

**Comment by quangvision** [comment]
Looking for clear solution on this matter. I am getting similar warnings

**Comment by HADB** [comment]
Any updates?

**Comment by gouz7514** [comment]
Any updates?

**Comment by surge-squirrel** [comment]
The problem remains unresolved

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
