### ISSUE TITLE
How to translate routes without using locale prefix

### ISSUE THREAD

**Issue by jonalxh** [nuxt-modules/i18n#735]
hI, I'm trying to do an app which works in Spanish and English, I need it can be accesed with page name and translated name, i.e: I have `about.vue `in `pages` folder and I need to access it with **/about** and **/nosotros**. I've tried with your plugin but it causes an **/es/nosotros** route and I need it to work without locale prefix.

Adding `no_prefix` strategy to` nuxt-i18n` config in `nuxt.config.js` doesn't work too.

I've set the following code in `about.vue` without success:

```
 export default {
	nuxtI18n: {
		paths: {
			es: '/nosotros',
			en: '/about'
		}
	},
}

```

nuxt.config.js:
```
modules: [
    ['nuxt-i18n', {
      strategy: 'no_prefix',
      lazy: true,
      parsePages: false, //Tried with true and does not work
      locales: [
        {
          name: 'Español',
          code: 'es',
          file: 'es/locale.json'
        },
        {
          name: 'English',
          code: 'en',
          file: 'en/locale.json'
        }
      ],
      langDir: '/locales/',
      defaultLocale: 'en'
    }]
]
```

**Comment by rchl** [comment]
With `no_prefix` no prefixes are created.
The `about.vue` snippet also seems correct.

You must be doing some a simple mistake somewhere if that doesn't work.
Please create reproduction on github or https://codesandbox.io/ if you want me to look at it.

**Comment by jonalxh** [comment]
Do you have a working example for me to try before creating the code snippet?
Thanks.

**Comment by jonalxh** [comment]
I was reading [this article](https://github.com/nuxt-community/nuxt-i18n/blob/master/docs/es/routing.md)  and it says **no_prefix** does not work with **Custom Routers**. What should I do to correctly translate my routes?

**Comment by rchl** [comment]
Here is some example you can fork and modify: https://codesandbox.io/s/i18n-plugin-i18nlocales-ouwhn

> I was reading [this article](https://github.com/nuxt-community/nuxt-i18n/blob/master/docs/es/routing.md) and it says **no_prefix** does not work with **Custom Routers**.

Ah yes, that's true.
To be fair not sure why. I think it might still be possible to support custom routes with `no_prefix` strategy. I could have a look at that at some point.

**Comment by jonalxh** [comment]
Looking at the example you gave me, using `no_prefix` only keep the same initial route, so if I have **/about** it will be the same in Spanish and English, I'd like it to change the current path by the custom path specified in `about.vue`: 
```
nuxtI18n: {
		paths: {
			es: '/nosotros', //Set it on language change
			en: '/about'
		}
	},
```

Is it possible or nothing to do?

**Comment by rchl** [comment]
Yes, I've confirmed that in my previous comment and said that I'll look into it.

**Comment by jonalxh** [comment]
> Yes, I've confirmed that in my previous comment and said that I'll look into it.

Thanks, I'll be waiting for it.

**Comment by jonalxh** [comment]
Hi. Is there any progress with this? I'm actually working in a project and it is an important part.
Maybe could you give me some ideas to make it work?

Thanks a lot.

**Comment by rchl** [comment]
I've looked into it but unfortunately, it would require more work than I've anticipated.
It would require solution similar to what #710 and #641 require.
So I don't think I can do a quick fix here.

**Comment by thomas4Bitcraft** [comment]
Any updates on this? 🙂

**Comment by jonalxh** [comment]
Any updates?

**Comment by rchl** [comment]
Only can reply with this: https://blog.sindresorhus.com/issue-bumping-e3b9740e2a0

**Comment by existe-deja** [comment]
If this feature is mandatory to go online, a workaround is to start as many servers as you have different languages. This way you can take advantage of prefix_except_default strategy.

**Comment by whooof** [comment]
Any chance for improving and making it possible? (somewhat a key feature in a project I develop)

**Comment by rttmax** [comment]
+1

**Comment by Expanddigital** [comment]
Can't believe this still isn't fixed, kind of a key features for most software. Why would you use a prefix if you are going to translate the slugs.

**Comment by yunyuyuan** [comment]
A workaround🤔:
```ts
function useUnlocalePath() {
  const path = useRoute().path;
  for (const locale of useI18n().availableLocales) {
    const prefix = "/" + locale;
    if (path.startsWith(prefix)) {
      return path.slice(prefix.length);
    }
  }
  return path;
}
```

**Comment by yunyuyuan** [comment]
I remember trying nuxt-i18n a year ago and encountering a problem. I saw that no one had handled it, so I gave up using nuxt-i18n. However, now I need to implement i18n in my Nuxt project🥲

**Comment by margintopt** [comment]
i18n: {
    strategy: 'no_prefix'
}

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (hotfixes only), if this still applies to v8 and later please open a new issue!
