### ISSUE TITLE
How to use vue-i18n-loader in asyncData or validation?

### ISSUE THREAD

**Issue by VadimCeretean** [nuxt-modules/i18n#809]
I try to use vue-i18n-loader in asyncData, but when i call for app.$i18n.t('title'), it's return 'title", but if i call in fetch or another cycles it works fine. Is vue-i18n-loader do not support SSR?

**Comment by rchl** [comment]
It should be `app.i18n.t`, not `app.$i18n.t`. Otherwise, I'm not sure what is your problem. You need to provide reproduction steps (a repo ideally).

(vue-i18n-loader is something else, unrelated to your issue)
