### ISSUE TITLE
How to add routes params in nuxtjs.config.js?

### ISSUE THREAD

**Issue by phucvo0709** [nuxt-modules/i18n#81]
How to add routes params in nuxtjs.config.js i try but not working

code router:
 `  <nuxt-link :to="localePath({ name: 'thiet-ke-web', params: { slug: price.slug_prices } })"></nuxt-link>`

code in nuxtjs.config.js
![untitled](https://user-images.githubusercontent.com/35060381/39623239-2aedd898-4fbf-11e8-9a9e-422f9ff77c8f.png)

**Comment by acamenhas** [comment]
Did you solve this?
