### ISSUE TITLE
Location template for page

### ISSUE THREAD

**Issue by lwswnnscrm** [nuxt-modules/i18n#810]
Hi, i have 1 request, i need create locale template for difference location, as an example i have en, fe and cn locations user in my app and in home page i need have some difference block, but the whole page is the same, difference 2-3 block in every location. Are there any solutions for this now? v-if with locale($i18n) too hard to maintain we have 20 locale now. Custom routing create for me 1500-1600 routes. Maybe you can give advice something other?

**Comment by rchl** [comment]
Don't know of any better solution than some form of v-if/v-else. If it makes it any cleaner, you can encapsulate that logic in a separate component but it's probably not much of a difference.

**Comment by lwswnnscrm** [comment]
@rchl Thank you for response. One more thing, maybe i can have in nuxt req in import component i mean when i use ```import component from './component/component'```  maybe i can have req for get location from req i have url example.com/location(/de, /cn, etc..), and if i could get req with url i can import component by location from url. I understand that it is unlikely, and this is not an instance, but suddenly it could be done like that.

**Comment by rchl** [comment]
I don't understand what you are asking there. I'll try again if you rephrase it.

**Comment by lwswnnscrm** [comment]
@rchl I mean, maybe i can have context.req or only url params in <script> tag higher export default, as example use 
``` 
<script>
  import router from '...'
  or 
  import req from '...'
```
and then use 
```
<script>
  import component from createRoute(router, '/main-baner');
```
and in createRoute
```
createRoute(route. path) {
  if (route.indexOf(route.path)) { return route.path + '/' + path }
  else { return './default' + path }
}
 ```
then i can create components folder structure
``` 
home-page 
  default 
    main-baner
  de
    main-baner
  cn
    main-baner
```
can it work like that?

**Comment by rchl** [comment]
You can import components using a dynamic path. See for example https://forum.vuejs.org/t/import-component-dynamically/33400 for an idea how to do it. But the file structure would most likely need to be more like `main-banner-[locale]`.

(Not sure why would you need req or router as you have locale available from `$i18n.locale`.)

BTW. It's not the best place to discuss that. I suggest you go to [Nuxt discord](https://discord.nuxtjs.org/) and ask further questions there.
