### ISSUE TITLE
How to get the translated path with a nested dynamic page (without index.vue)

### ISSUE THREAD

**Issue by jeckojim** [nuxt-modules/i18n#816]
Hi, maybe I didn't search correctly but after 4 hours of searching, trying and reading the doc, I can't figure out how to do it.

I want to get a directory like this:
```
pages/
  beers/
    _id.vue
```
Note that there is no need of index page for beers in my case, as the listing is in the global index.vue page (home page).

So I created the folder beers and page _id.vue and entered this in nuxt.config.js:
```
/*
  ** Nuxt.js modules
  */
  modules: [
    [
      'nuxt-i18n',
      {
        seo: false,
        baseUrl: 'https://website.com',
        notSecureBaseUrl: 'http://website.com',
        locales: [
         ...
        ],
        lazy: true,
        langDir: 'locales/',
        defaultLocale: 'fr',
        parsePages: false,
        pages: {
          'beers/': {
            en: '/beers',
            fr: '/bieres'
          },
          //I tried also
         'beers/_id': {
            en: '/beers/:id',
            fr: '/bieres'/:id
          },
...
```
How can I get it for `<nuxt-link to="translated-path/id">` ?

I tried this:
` <nuxt-link :to="localePath(`/beers/${productId}`">`... that output `href="/"`
and this
` <nuxt-link :to="`${localePath('/beers')}/${productId}`">`... that output `href="//product-id"`

Sorry the backticks didn't get formated correctly above.

If someone can help me to understand I will really appreciate.

Thanks for the great work with this module by the way.

**Comment by rchl** [comment]
I believe this should work:

`<nuxt-link :to="localePath({ name: 'beers', params: { id: productId } })">...</nuxt-link>`

That is a bit weird but that's what VueRouter expects.

There are examples like that at https://i18n.nuxtjs.org/basic-usage.html#nuxt-link

**Comment by jeckojim** [comment]
Hello,
Thank you for your answer.
I'm sorry for late reply I didn't have access to internet for the last 3 days: your suggestion didn't worked for me. Below what I did to get it translated:

```
/*
  ** Nuxt.js modules
  */
  modules: [
    [
      'nuxt-i18n',
      {
        ...
        pages: {
          'beers/index': {
            en: '/beers',
            fr: '/bieres'
          },
          'beers/_id': {
            en: '/beers/:id',
            fr: '/bieres/:id'
          },
...

/*
  ** pages/index.js
  */
...
<nuxt-link
      :to="`${localePath('beers')}/${productId}`"
      :title="$t('pages.products.show_details.title')"
>
      {{ $t('pages.products.show_details.text') }}
      <span class="show-details-button-expand-icon"><img src="~assets/img/x.svg" alt=""></span>
</nuxt-link>
```

Thank you again for trying to help me.

**Comment by rchl** [comment]
`<nuxt-link :to="localePath({ name: 'beers-id', params: { id: 'budwiser' } })">Give me the beer</nuxt-link>`

The route name needs match route's generated name which you can lookup in the build dir (`.nuxt/router.js`).

**Comment by jeckojim** [comment]
Hi Rafał, thank you again,
that worked. Even if Budweiser is not really a beer... ;)
I was thinking that it would be the name  of the parent path that will go in the`name` property, without the nested part (e.g. 'beers' without the `-id`).
Cheers :)
