### ISSUE TITLE
Routing problem when switching between sites [NuxtJS-i18n]

### ISSUE THREAD

**Issue by ghost** [nuxt-modules/i18n#817]
I have a NuxtJs App with i18n (https://github.com/nuxt-community/i18n-module). I use the following to change my current language:
```
<n-link v-if="$i18n.locale !== 'en'" :to="switchLocalePath('en')">
  <img class="flag" src="/icons/flags/uk.png" alt="english">
</n-link>
<n-link v-if="$i18n.locale !== 'de'" :to="switchLocalePath('de')">
  <img class="flag" src="/icons/flags/germany.png" alt="german">
</n-link>
```

The language changes but if I change the side e.g. like this: 
```
<n-link class="nav-link font-3 hide-link-small" to="/about">{{ $t("about.title") }}</n-link>
```

The language resets to the default local.
NuxtJs-i18n automatically changes the url to `/en` but if I switch the site it does not get convertet to `/en/about` instead it jumps to `/about`.

```
// nuxt.config.js

import de from './lang/de'
import en from './lang/en'

...

[
  'nuxt-i18n',
  {
    locales: ['en', 'de'],
    defaultLocale: 'de',
    strategy: 'prefix_except_default',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: en,
        de: de
      }
    }
  }
]
```

**Comment by rchl** [comment]
For the first issue, you need to persist your choice with `setLocale`. See https://i18n.nuxtjs.org/lang-switcher.html (the docs are not super clear on that maybe).

For the second issue, you need to use `localePath` to generate a path for the current locale. https://i18n.nuxtjs.org/basic-usage.html#nuxt-link has a lot of examples and all are using `localePath` or `switchLocalePath`.
