### ISSUE TITLE
Default locale should be loaded from main bundle

### ISSUE THREAD

**Issue by rchl** [nuxt-modules/i18n#818]
If the user has specified `defaultLocale` and is using `lazy` option to load messages, the lang file for default locale should be loaded from the main bundle as it's always needed (either for the current locale or to be used as fallback).

This was brought up in both #486 and #815.

**Comment by koteezy** [comment]
What if the user's language doesn't match defaulLocale, in this case, in main.bundle will find the unnecessary language.

Maybe we should inject JSON with current user language to the page via nuxtState, this way you can avoid an unnecessary Ajax request.

**Comment by rchl** [comment]
Even if the user's locale is not the default locale, the default locale is needed as it's loaded as a fallback. So there are still benefits to having it in the main bundle.

> Maybe we should inject JSON with current user language to the page via nuxtState

This is a possible further, separate improvement.
