### ISSUE TITLE
dynamic routes don't get generated in unprefixed version

### ISSUE THREAD

**Issue by violoncelloCH** [nuxt-modules/i18n#822]
### Version
nuxt-i18n: 6.13.2
nuxt: 2.14.0

### Reproduction Link
https://git.violoncello.ch/websites/repro-nuxti18n-822
clone over https: https://git.violoncello.ch/websites/repro-nuxti18n-822.git

### Steps to reproduce
1. generate site with static and dynamic routes (with `strategy: prefix` and `defautlLocale` set
2. run `nuxt generate`
3. see that unprefixed routes are generated for static routes but not for dynamic (crawled) ones

### What is Expected?
uprefixed routes should be created for all routes

### What is actually happening?
as in steps to reproduce

**Comment by rchl** [comment]
I'll call it a feature request as the crawling part is a new feature in Nuxt and it's just not supported.

**Comment by violoncelloCH** [comment]
sorry - makes sense :see_no_evil: 
fine by me :)

it just felt unexpected to me, as those dynamic routes are generated for the prefixed routes...

**Comment by rchl** [comment]
@Atinux Would you be able to help here?

Basically what this module does is it uses the `this.extendRoutes` hook from the module's code to process all known routes and add some of its own based on those. But it seems like the routes discovered by the crawler are not in the list yet at that point (understandable) and there is no way for this module to process crawled routes. Do you see any possible solution for that?

**Comment by atinux** [comment]
Hi @violoncelloCH 

I tried to run `yarn generate` on your reproduction and got this:

![Screenshot 2020-09-30 at 11 50 56](https://user-images.githubusercontent.com/904724/94670765-444b9c80-0313-11eb-838e-dc56eeaa0398.png)

The crawler will actually read the `<a>` generated when the page is rendered, if you have no link pointing to `/dynamic/`, it is normal that it won't generate it.

**Comment by violoncelloCH** [comment]
Well I get your point, however as I have a nuxt-link pointing to `localePath('/dynamic/')` I'd expect it to generate `/dynamic/` in an unprefixed version as well.
Is there a better way to create those navigation links so an unprefixed version would actually be generated? (except for creating a complete separate navigation for the unprefixed version)

**Comment by violoncelloCH** [comment]
Thinking about it, it looks to me like the problem is actually that the default locale causes links on unprefixed routes to be generated in `/en/*` variant anyways. Would it make sense/be possible to have links on unprefixed urls to be created as unprefixed links?

**Comment by rchl** [comment]
When using the `prefix` strategy, all locales are supposed to be prefixed.

This module still adds unprefixed routes to act as a fallback for static serving but that is not an essential feature IMO as you can probably set up your hosting service to handle all non-existent routes through the `200.html` route that Nuxt generates. Those fallback routes are only meant for redirecting to prefixed routes anyway.

If you want to actually use unprefixed routes for your default locale then investigate using a different `strategy` option.

**Comment by violoncelloCH** [comment]
I agree on it not being essential because of the fallback, it's more something nice to have as pre-generated routes load quicker (and also work in a browser with no/disabled js).
So maybe it's more a question of consistency. It feels odd to me that for `strategy: prefix` some of the routes get pre-generated in the un-prefixed variant while others are not...
Thanks for the hint on using an other strategy, I'm aware of that and `prefix` is a deliberate choice there :)
So if you consider this small "inconsistency" as appropriate behaviour, feel free to close this issue...

**Comment by rchl** [comment]
I'd rather move away from generating extra fallback routes than adding more.

Nuxt already generates 200.html fallback route and it should be possible to configure any hosting service to use that as a fallback.
