### ISSUE TITLE
nuxt start wants locales from project, not from built source

### ISSUE THREAD

**Issue by zeidlos** [nuxt-modules/i18n#826]
### Version
nuxt-i18n: 6.13.4
nuxt: 2.14.0

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal

### Nuxt-i18n configuration
This is the generated configuration `dist/nuxt-i18n/options.js`
Be aware, we're only using one language, for sake of testing/reproducability we've added a 2nd language.

```
export const vueI18n = {}
export const vueI18nLoader = false
export const locales = [{"name":"German","code":"de","iso":"de-DE","file":"de-DE.json"},{"name":"Swiss-German","code":"ch","iso":"de-CH","file":"de-CH.json"}]
export const defaultLocale = 'de'
export const routesNameSeparator = '___'
export const defaultLocaleRouteNameSuffix = 'default'
export const strategy = 'prefix_except_default'
export const lazy = true
export const langDir = 'locales/'
export const rootRedirect = null
export const detectBrowserLanguage = {"useCookie":true,"cookieDomain":null,"cookieKey":"i18n_redirected","alwaysRedirect":false,"fallbackLocale":""}
export const differentDomains = false
export const seo = false
export const baseUrl = ''
export const vuex = {"moduleName":"i18n","syncLocale":false,"syncMessages":false,"syncRouteParams":true}
export const parsePages = true
export const pages = {}
export const beforeLanguageSwitch = () => null
export const onLanguageSwitched = () => null
export const IS_UNIVERSAL_MODE = true
export const MODULE_NAME = 'nuxt-i18n'
export const LOCALE_CODE_KEY = 'code'
export const LOCALE_ISO_KEY = 'iso'
export const LOCALE_DOMAIN_KEY = 'domain'
export const LOCALE_FILE_KEY = 'file'
export const STRATEGIES = {"PREFIX":"prefix","PREFIX_EXCEPT_DEFAULT":"prefix_except_default","PREFIX_AND_DEFAULT":"prefix_and_default","NO_PREFIX":"no_prefix"}
export const COMPONENT_OPTIONS_KEY = 'nuxtI18n'
export const defaultLangFile = 'de-DE.json'
export const hasNonDefaultLangFiles = true
export const localeCodes = ["de","ch"]
export const trailingSlash = undefined
```

### Steps to reproduce
Run `yarn build --production`
move/delete your locales folder (from your project)
Run `yarn start`

### What is Expected?
It is expected that nuxt-i18n uses the locales from generated (dist) folder.

### What is actually happening?
It tries to use locales file from our local project. The source files are not available in our docker image.

If you need help to reproduce, we can set up a Zoom call, or I can try to provide further information if needed.
This bug was introduced recently, most likley with the update to 6.13.3/4.

**Comment by rchl** [comment]
Let me do some substantial refactor to fix it and hopefully not break anything more in the process...

**Comment by zeidlos** [comment]
For now we mitigate this, copying our locales folder into the docker image. That should work and not block us. 

Thank you very much for your swift response and work on this project!

**Comment by rchl** [comment]
Resolved in [v6.13.5](https://github.com/nuxt-community/i18n-module/releases/tag/v6.13.5)

Thanks for good reports and sorry for the breakage. :)

**Comment by svewag** [comment]
Wow - that was faster than fast!

**Comment by zeidlos** [comment]
I can confirm that it works as intended again! Thanks! ;)

**Comment by rchl** [comment]
Did you bring friends with you or the issue is so common? ;)
I've never seen so many "reactions" in a random bug. :)

**Comment by svewag** [comment]
yep, here is one :-D

**Comment by divine** [comment]
> Did you bring friends with you or the issue is so common? ;)
> I've never seen so many "reactions" in a random bug. :)

We're all here! Waiting for your commits 😂

**Comment by aSchaffe** [comment]
yep, and here is an other one :-D

**Comment by zeidlos** [comment]
> Did you bring friends with you or the issue is so common? ;)
> I've never seen so many "reactions" in a random bug. :)

Of course! You always bring friends/coworkers to appreciate great work from an open source contributor. ;)
