### ISSUE TITLE
Locale detection don't work on client side, with differentDomains enabled and vuex sync disabled

### ISSUE THREAD

**Issue by coremyslo** [nuxt-modules/i18n#831]
### Version
nuxt-i18n: 6.13.6 (older too)
nuxt: 2.13.1 (older too)

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [] spa

### Nuxt-i18n configuration
```
["nuxt-i18n", {
    differentDomains: true,
    defaultLocale: config.LOCALE_DEFAULT,
    locales,
    parsePages: false,
    pages,
    vueI18n: {
        fallbackLocale: config.LOCALE_FALLBACK,
        silentFallbackWarn: true,
        messages,
    },
    vueI18nLoader: true,
    vuex: {
        syncMessages: false,
        syncLocale: false,
    },
}],
```

### Steps to reproduce
1. Create setup with 
```
{
    differentDomains: true,
    defaultLocale: "any-locale",
    vuex: {
        syncMessages: false,
        syncLocale: false,
    }
}
```
2. open in browser non-default locale, on server it will work as expected, but on client it will be default

**Comment by coremyslo** [comment]
It's not a problem to have
```
vuex: {
    syncMessages: false,
    syncLocale: true,
}
```
but in that case, when I try to overwrite messages in `nuxtServerInit` like this:
```
nuxtServerInit ({}, ctx) {
    ctx.app.i18n.setLocaleMessage("en-FR", { test: "yo" });
},
```
I have text replace effect back to origin on the client-side (on server "yo" rendered)
not sure why actually, because `syncMessages` is **false**

NOTE: in `nuxtServerInit` I want to merge existing messages with messages fetched from the cloud

**Comment by coremyslo** [comment]
as a workaround to my origin problem with overwriting messages I can use also `lazy:true` and fetch messages from the cloud there, but in that case, I will have 2 serial promises one in lazy js file, one in nuxtServerInit (there are some not related to locales), if I will do it in `nuxtServerInit`, they would be parallel.

**Comment by rchl** [comment]
I think I need more information or ideally a small repo that reproduces.

When testing locally I see some issue due to my local server running on non-default port but otherwise, I can't see the issue.

**Comment by coremyslo** [comment]
I'll create a repo

**Comment by coremyslo** [comment]
@rchl 
https://github.com/coremyslo/nuxt-i18n-issue
You would need to add this 2 hosts to /etc/hosts or replace them in config with any
```
{
    code: 'en',
    domain: 'localhost:3000',
},
{
    code: 'fr',
    domain: 'fr.localhost:3000',
},
```
after setup, issue would be on http://fr.localhost:3000/, where `yo` text got replaced on client by `Bonjour` back again
This is my real issue I want to resolve.

The other one is when you change to
```
{
    syncMessages: false,
    syncLocale: false,
}
```
you might see fallback to default locale on the client.
I guess, there are 2 different, not related issues actually.

**Comment by rchl** [comment]
While it's not the main issue, your configuration has `detectBrowserLanguage` enabled (because it's enabled by default). Do you agree that this option should be force-disabled when using `differentDomains`? I guess we don't want to detect user's locale and show page in English, for example, when user visits `fr.*` page.

**Comment by coremyslo** [comment]
I agree to force disable it.

**Comment by rchl** [comment]
I've created #832. I'd need to also add tests before integrating.

I've fixed domain detection on the client which was confused both by the port (:3000) and by the route's own locale.

I'm switching off `detectBrowserLanguage` when using `differentDomains` but it can break people's expectations I guess. I'm not sure if redirecting from one domain to another automatically is something that people expect.

BTW. The other part of your issue where you call:
```js
            context.app.i18n.setLocaleMessage("fr", {
                home: {
                    title: "yo"
                },
            });
```
from `nuxtServerInit` and expect those messages to be used on the client also, won't work. The client re-reads the messages and what you do here is lost.

It's possible to fix that too (use "nuxtState" to carry over messages to the client - something I've added just recently for `lazy` loading) but I would consider that a separate issue/feature.

**Comment by coremyslo** [comment]
> I'm switching off detectBrowserLanguage when using differentDomains but it can break people's expectations I guess. I'm not sure if redirecting from one domain to another automatically is something that people expect.

agree, another way would keep this option but with false as default, but it would be more breaking change

for the nuxtServerInit overwrite, should I report another issue/feature request?

**Comment by coremyslo** [comment]
thanks for this changes and your reactivity on replies.

**Comment by rchl** [comment]
> for the nuxtServerInit overwrite, should I report another issue/feature request?

Yes, please create a feature request for passing messages from the server to the client (when not using `lazy`).

**Comment by rchl** [comment]
> > I'm switching off detectBrowserLanguage when using differentDomains but it can break people's expectations I guess. I'm not sure if redirecting from one domain to another automatically is something that people expect.
> 
> agree, another way would keep this option but with false as default, but it would be more breaking change

I'll revert that change then and just add a note in the documentation about that.

**Comment by coremyslo** [comment]
yes, there are already notes for other cases about incompatibility, so another note would be safier than potential issue for someone.
