### ISSUE TITLE
Add support of runtime locales config

### ISSUE THREAD

**Issue by coremyslo** [nuxt-modules/i18n#834]
### Is your feature request related to a problem? Please describe.
I'm using `differentDomains: true` and originally my locales config was like this:
```
locales: [
    {
        code: 'en',
        domain: 'localhost:3000',
    },
    {
        code: 'fr',
        domain: 'fr.localhost:3000',
    },
],
```
With progress of my app, I have `development`, `staging` and `production` instances, so I need to extend my config to this:
```
locales: [
    {
        code: 'en-local',
        domain: 'localhost:3000',
    },
    {
        code: 'fr-local',
        domain: 'fr.localhost:3000',
    },
    {
        code: 'en-production',
        domain: 'my-site.com',
    },
    {
        code: 'fr-production',
        domain: 'fr.my-site.com',
    },
    {
        code: 'en-staging',
        domain: 'staging.my-site.com',
    },
    {
        code: 'fr-staging',
        domain: 'fr.staging.my-site.com',
    },
    {
        code: 'en-development',
        domain: 'development.my-site.com',
    },
    {
        code: 'fr-development',
        domain: 'fr.development.my-site.com',
    },
],
```

NOTE: prefixes `-local`, `-staging`, `-deveopment`, `-production` are added only to have unique codes, they are not containing any messages.

The problem is because I want to deploy the same build accross mupliple env's and I need to include config for all my env's in the same build, which create a bunch of routes never used on specific env

### Describe the solution you'd like
I'm not sure if it's possible at the moment, but Ideally would be good to have the ability to provide this config on runtime somehow using `process.env` or `publicRuntimeConfig`

**Comment by rchl** [comment]
Have you seen https://i18n.nuxtjs.org/different-domains.html#runtime-environment-variables ?

In general, this module (like most others) should support runtime config but that's a bigger task. Also not everything will be runtime configurable as some things can only be configured at build time.

**Comment by coremyslo** [comment]
you are right, missed that, no issue. sorry

**Comment by rchl** [comment]
Actually `locales` could not be a runtime configurable thing as those affect what routes (at least in strategies other than `no_prefix`) are created which can only be done at build-time. The `domain` itself could be configurable though (like it already is when using a store-based solution).

So it would be quite tricky to handle runtime configuration in a concise and easy to understand for the user way...

**Comment by coremyslo** [comment]
understood and make total sense.
