### ISSUE TITLE
nuxt-link component in $t().

### ISSUE THREAD

**Issue by lwswnnscrm** [nuxt-modules/i18n#857]
Hi, question. What i need to to make nuxt-link work in $t()?
Example i have json with my translations: 
```
{
  en: {
    about_us: '<span>text text text <nuxt-link :to="localePath('/')>home page</nuxt-link></span>
  }
}
```

and when i use in my component $t('about_us') i see in HTML 
`<span>text text text <nuxt-link :to="localePath('/')>home page</nuxt-link></span>'`
and routing don't work and nuxt-link don't change to <a>, is there a possibility use <nuxt-link> i my translation, or i need do <nuxt-link> only in component?

**Comment by rchl** [comment]
You can't have components in your translations.

You need to restructure that and use [Component interpolation](http://kazupon.github.io/vue-i18n/guide/interpolation.html#basic-usage) instead, for example.
