### ISSUE TITLE
error ie11

### ISSUE THREAD

**Issue by osnosov** [nuxt-modules/i18n#860]
### Version
"nuxt-i18n": "^6.13.11",
"nuxt": "^2.14.0"

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [] spa

### What is actually happening?
after the commit
[https://github.com/nuxt-community/i18n-module/commit/c2aafd63601675a2745e2fe2c052ccb1cc6e2802](https://github.com/nuxt-community/i18n-module/commit/c2aafd63601675a2745e2fe2c052ccb1cc6e2802)
nuxt-i18n does not workin in  ie11. Error in deepcopy.js

**Comment by rchl** [comment]
Thanks. Released fix in [v6.13.12](https://github.com/nuxt-community/i18n-module/releases/tag/v6.13.12)
