### ISSUE TITLE
[Feature Request]YAML Locales Support

### ISSUE THREAD

**Issue by willin** [nuxt-modules/i18n#863]
### Is your feature request related to a problem? Please describe.

https://github.com/nuxt-community/i18n-module/blob/master/src/templates/utils.js#L31

```js
            const langFileModule = await import(/* webpackChunkName: "lang-[request]" */ `~/<%= options.langDir %>${file}`)
            const getter = langFileModule.default || langFileModule
            messages = typeof getter === 'function' ? await Promise.resolve(getter(context, locale)) : getter
```

i found that locales are imported as js/json files. but `yaml` format files are more lighter.

### Describe the solution you'd like

add a check, when pass in yaml files use yaml-parser to load them.

**Comment by willin** [comment]
moreover, if support multiple files will be more better


like:

```
locales/
en/
  message.yml
  navigation.yml
zh/
  message.yml
  navigation.yml
```

**Comment by willin** [comment]
for the time being, i need a script to build and use generated files, demo codes at: https://github.com/shiwangme/yaml-i18n-demo

**Comment by rchl** [comment]
Wouldn't it **just work** if you would extend your webpack config with [yaml-loader](https://github.com/eemeli/yaml-loader)?

Also see https://nuxtjs.org/faq/extend-webpack/

**Comment by willin** [comment]
@FearwareX have a try

**Comment by 12ain** [comment]
I extend webpack config with [yaml-loader](https://github.com/eemeli/yaml-loader) , It works!

**Comment by rchl** [comment]
Do you expect something to be done within the module to support that out of the box?

To me, it seems like something that the user should set up itself. He might even be using the yaml-loader already. The least I could do is to maybe extend docs to mention how to set it up.

**Comment by Tenrys** [comment]
> 
> 
> I extend webpack config with [yaml-loader](https://github.com/eemeli/yaml-loader) , It works!

Doing this breaks i18n blocks with lang yaml for me.

**Comment by tillsanders** [comment]
I can confirm that using the "default" yaml rule breaks i18n blocks. I was able to resolve this by only applying the yaml-loader rule to my `locales/` directory, like so:

```javascript
  build: {
    extend(config) {
      config.module.rules.push({
        test: /locales\/.*\.ya?ml$/,
        type: 'json',
        use: 'yaml-loader'
      })
    }
  }
```

Now, I can import locales from yaml files in `locales/` and still use i18n blocks. I think this or a better solution should be mentioned in the docs. If you like my approach, I can file a PR to add a new guide to the docs. Let me know what you think!

Also, happy holidays!
