### ISSUE TITLE
Multilingual static site with NUXT

### ISSUE THREAD

**Issue by VeselyJan92** [nuxt-modules/i18n#866]
### Version
nuxt-i18n: 6.13.12
nuxt: 2.14.3

### PROBLEM

I am trying to generate full static generated site using Nuxt with target `static`. The problem i18n gnerates lots of JS that is shipped to the browser and never used: `dist/_nuxt/static/1598426386/state.js` contains transaltion JSON file `__i18n` which can be pretty big (contains all possible transaltions, only a fraction is actually used on the current site) and because the site was already generated they are not used. I do not need a hot language swap. Ideally I would love to see i18n only during the generate phase and do not include any of its features for production site. Maybe this could be an inspiration 
[https://www.npmjs.com/package/static-i18n](url)

Is there a way use I18N only during the generate phase and do not include it for production or alt least minimaze the `__i18n.langs` size 

`dist/_nuxt/static/1598426386/state.js`:

```
window.__NUXT__ = {
  staticAssetsBase: "\u002F_nuxt\u002Fstatic\u002F1598449871",
  layout: "default",
  error: null,
  serverRendered: true,
  routePath: "\u002F",
  config: {},
  __i18n: {
    langs: {
      cs: {
        brand: "U Veselých",
        penzion: "penzion",
.... More translations

```
Config
```
 {
        defaultLocale: 'cs',
        vueI18nLoader: false,

        vueI18n: {
          fallbackLocale: 'cs',
        },

        locales: [
          { code: 'en', file: 'en.json', iso: 'en-US'},
          { code: 'de', file: 'de.json', iso: 'en-US'},
          { code: 'pl', file: 'pl.json', iso: 'en-US'},
          { code: 'cs', file: 'cs.json', iso: 'en-US'}
        ],
        lazy: true,
        langDir: 'assets/localization/',
        seo: true,
      }
```

**Comment by rchl** [comment]
Even full-static site is initializing the Vue runtime after load so if you wouldn't have translations available somewhere, the strings would just go blank (or rather show just the keys). So it's not possible to get rid of them entirely.

The only thing that could be considered here is whether the locales should be included in the `nuxtState` (`state.js`) or only in a separate JS locale files (`lang-*.js`). Including them in `nuxtState` means that every generated page will carry that same payload while if we don't do that, the pages will have to do an extra request to get the locale file.

For full-static (or just generated) sites, I would lean towards not having locales in the nuxtState.

**Comment by VeselyJan92** [comment]
> Even full-static site is initializing the Vue runtime after load so if you wouldn't have translations available somewhere, the strings would just go blank (or rather show just the keys). So it's not possible to get rid of them entirely.

For example if you disable JS, pages are working fine with correct translations (no need to translate them on the client. All was handled by `nuxt generate`). I do not see a point of shipping translation files for already translated page to the client. The user already got a translated page based on the url the user requested. 

Should I make a demo project for you?

> For full-static (or just generated) sites, I would lean towards not having locales in the nuxtState.

That is probably what I am looking for. Would you elaborate more on how to set it up or share a link. I haven't done any other settings except the config I have shared.

**Comment by rchl** [comment]
> For example if you disable JS, pages are working fine with correct translations (no need to translate them on the client. All was handled by `nuxt generate`). I do not see a point of shipping translation files for already translated page to the client. The user already got a translated page based on the url the user requested.

Yes. If you disable JS then it will work. It's the JS that would actually "break" the page by "hydrating" the page on load. You *need* the translation. Generated nuxt page (even in static mode) is still a dynamic Vue page.

> Should I make a demo project for you?

I suggest you just remove that `__i18n` object (or just rename to something else for the sake of experiment). You should still get correct translations but then the `lang-*.js` file will be requested on page load. And if you delete that file then you'll notice that translations are broken. So yes, you still need translations accessible one way or another.

The point in them being in nuxt state already is to avoid extra network request to load the `lang-*.js` file.

> That is probably what I am looking for. Would you elaborate more on how to set it up or share a link. I haven't done any other settings except the config I have shared.

It's something that would have to be implemented. Either make it so that locales are not injected into nuxtState for generated pages or by providing an option to toggle the behavior.

**Comment by Surt** [comment]
Hi,

I'm wondering about this too. My language json files are big and I get frustrated every time i see the rendered source code. Wouldn't be better  to "import" the language file as a reference? So the browser have it cached.  Or maybe setting the json on the local storage after a first attempt? under a hash used to control modifications or something.


EDITED:

so... I found 
``` 
     lazy: {
            skipNuxtState: true
        },
```

and I'm happy now :)

**Comment by rchl** [comment]
As you've mentioned, there is `lazy.skipNuxtState` option (https://i18n.nuxtjs.org/options-reference#lazy) so closing this.
