### ISSUE TITLE
Use params on any route

### ISSUE THREAD

**Issue by VictorCamargo** [nuxt-modules/i18n#871]
Hello everyone, I'm using `<nuxt-link :to="localePath({ name: 'purchases' params: { slug: 123 } })">Link</nuxt-link>` but it only works when  I'm inside the route **/purchases/_id**. Outside this route on purchases list for example, I have to use `localePath('/purchases/' + purchase._id)` , because it don't add the params to the path.

There's any way to achieve `localePath({ name: 'purchases' params: { slug: 123 } })` with params?

**Comment by rchl** [comment]
Your dynamic route is called `_id.vue` so you have to pass param called `id`, not `slug`

**Comment by VictorCamargo** [comment]
Thank you for that, but I had updated to `localePath({ name: 'purchases', params: { _id: 123 } })` and still not work. Maybe my page folder is causing that?

I have:

```
/pages
  /purchases
    _id.vue
    index.vue

```

> Your dynamic route is called `_id.vue` so you have to pass param called `id`, not `slug`

**Comment by rchl** [comment]
I said id not _id.

**Comment by rchl** [comment]
But the route name is wrong too

**Comment by VictorCamargo** [comment]
> I said id not _id.

Sorry, I updated it to **id** but still not work.

**Comment by VictorCamargo** [comment]
> But the route name is wrong too

Humm, I'm missing that. What is wrong with the route name?

**Comment by VictorCamargo** [comment]
> But the route name is wrong too

Ahhh I got it! It's because the final name to this route will not be `purchases` but `purchases-id`.

@rchl Now that works. Thank you very much for the clue.

**Comment by VictorCamargo** [comment]
@rchl I'm just curious, how can I achieve the same result using **path**, is it possible?

**Comment by rchl** [comment]
Using paths is less reliable but I think `localePath('/purchases/123')` should work.
