### ISSUE TITLE
Custom paths in components not working

### ISSUE THREAD

**Issue by this-is-fine-dev** [nuxt-modules/i18n#878]
### Version
nuxt-i18n: 6.13.12
nuxt: v2.14.4 

### Nuxt configuration
 - [X] universal
 - [] spa

### Nuxt-i18n configuration
```
i18n: {
    locales: [
      {
        code: 'en',
        name: 'English',
        file: 'en-US.js',
      },
      {
        code: 'pl',
        name: 'Polski',
        file: 'pl-PL.js',
      },
    ],
    defaultLocale: 'pl',
    lazy: true,
    langDir: 'lang/',
  },
```

When I add this in my page, custom path not working
```
  nuxtI18n: {
    paths: {
      en: '/products',
      pl: '/produkty',
    },
  },
```

but, if I set in nuxt.config.js works great
```
parsePages: false,
    pages: {
      products: {
        en: '/products',
        pl: '/produkty',
      },
    },
```

**Comment by rchl** [comment]
Are there any errors/warnings in the console when building?

I think you might need to create a reproducible test case.

**Comment by abellion** [comment]
I had the same issue, and by setting to "true" the `parsePages` option it worked.

However, I noticed that the changes made to the `nuxtI18n` object aren't taken into account once the development server is launched. I have to restart it every time to actually get the updated routing. It looks like this is a live reloading issue.

**Comment by rchl** [comment]
Closing due to no response.
The feature works according to my testing.

> I had the same issue, and by setting to "true" the `parsePages` option it worked.

`parsePages` is `true` by default so you shouldn't need to set it to `true` yourself unless you've overridden it to `false`, of course.

Also see documentation for `parsePages` and `pages`: https://i18n.nuxtjs.org/options-reference#parsepages

**Comment by infostatus** [comment]
Has exactly the same problem. 
With parsePages = false the custom paths didn't work in components. But it was working on nuxt.config.js file.
Has to change to true or delete that configuration line for it to work in components.
