### ISSUE TITLE
How to Add translation to the default messages object?

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [nuxt-modules/i18n#879]
In `nuxt.config.js` , you can add `messages` option to overwrite the default values of nuxt.

```js
//nuxt.config.js
export default {
  messages: {
      loading: 'Loading...',
      error_404: 'This page could not be found',
      server_error: 'Server error',
      back_to_home: 'Back to the home page',
      server_error_details: 'An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.',
      client_error: 'Error',
      client_error_details: 'An error occurred while rendering the page. Check developer tools console for details.'
      //...
  }
}
```

I was trying to add translation to them (and be changed dynamically when changing the language), Is there a proper way of doing this?

And if there is not, would it be a good feature to implement?!

**Note: I'm using `no_prefix` Routes generation strategy and `Lazy load` translation files.**

**Comment by rchl** [comment]
Those messages look like largely unused in production.

Maybe only `error_404` and `server_error` might show up production but I suppose you can override those error pages with your local one to show your own strings.

But unless Nuxt changes the way those are shown, I don't think I can do anything in the module to support translating those. Those would have to be translated at runtime so Nuxt would have to provide some callback to translate them.

Another thing is that `server_error` might be (haven't checked for sure) a hard error and without Vue environment so it might be impossible to translate that at runtime at all.

**Comment by AbdallahAlhaddad** [comment]
@rchl Thank you for your fast response.
My problem is I have several `404 not found` custom errors:
- blog not found
- page not found
- ...etc.

For dynamic pages, I'm using `asyncData` for my api calls, and passing translated errors from it like below:
```js
   // ~/pages/blogs/_slug.vue
  async asyncData({ ..., error }) {
    try {
       // get blogs here
    } catch (err) {
      error({ statusCode: 404, message: app.i18n.t('notFound.blog') })
    }
```
- And Displaying `message` & `status code` in `Error.vue`.
-  This works fine unless the route is a static page, as I didn't find a way to change the default `404` message except in `nuxt.config.js` message object (will be one language and don't fit my needs), so as a workaround (for now) I handled it in `errorData` computed property below but its hacky and future bug prone:
```html
<template>
  <div>
    <span>{{ errorData.statusCode }}</span>
    <span>{{ errorData.message }}</span>
  </div>
</template>

<script>
export default {
  layout: 'empty',
  props: {
    error: {
      type: Object,
      default: null,
    },
  },
  computed: {
    errorData() {
      const message =
        this.error.message === 'This page could not be found' // hacky and bug prone if nuxt change the message in the future.
          ? this.$t('notFound.page')
          : this.error.message
      return { message, statusCode: this.error.statusCode }
    },
  },
}
</script>
```

**Comment by rchl** [comment]
This functionality seems to be quite hardcoded in Nuxt so best way forward is to create a feature request in Nuxt to make it more flexible. Maybe support those messages through runtime config which would then make it easy to override using plugin.

**Comment by AbdallahAlhaddad** [comment]
@rchl  Thank you for your suggestion.
I've  created feature request in Nuxt [#8375]( https://github.com/nuxt/nuxt.js/issues/8375)
