### ISSUE TITLE
v6.14.0 breaks yarn upgrade/install 

### ISSUE THREAD

**Issue by ludo237** [nuxt-modules/i18n#883]
### Version
nuxt-i18n: 6.14.0
nuxt: ^2.13

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt-i18n configuration
```
i18n: {
    locales: [
      {
        code: "it",
        file: "it.js",
      },
    ],
    lazy: true,
    langDir: "lang/",
    defaultLocale: "it",
    vueI18n: {
      fallbackLocale: "it",
    },
    vuex: {
      moduleName: "i18n",
      syncLocale: true,
      syncMessages: true,
      syncRouteParams: true,
    },
  },
```

### Reproduction Link
Not necessary

### Steps to reproduce
- Add nuxt-i18n v6.1.4.0 as dependency
- Run yarn or yarn upgrade

### What is Expected?
Yarn should complete the installation/upgrade process

### What is actually happening?
Yarn outputs this at the end of the build

```bash
[4/4] Building fresh packages...
error \path\to\my\app\node_modules\node_modules\nuxt-i18n: Command failed.
Exit code: 1
Command: cd docs && yarn && cd ..
Arguments:
Directory: \path\to\my\app\node_modules\nuxt-i18n
Output:
The system cannot find the path specified.
```

This does not happen if I downgrade to nuxt i18n v6.13.12

**Comment by rchl** [comment]
Thanks for the quick reaction. v16.14.1 should fix it.
It was a `postinstall` script that only worked during development.

**Comment by ludo237** [comment]
@rchl no problem I was messing around with the `edge` branch of the project where I try to install the latest and greatest and this popped out of nowhere
