### ISSUE TITLE
Avoid 404 when page is not translated

### ISSUE THREAD

**Issue by narduin** [nuxt-modules/i18n#892]
Hello!

I have a website in french that is also available in english.
The blog (nuxt content) contains articles in french and in english but some articles are not translated.
So when I switch to english from a french article not translated, I get a 404.

Is it possible to redirect to a custom error page (ex: 'translation in progress') to avoid 404?
I read in the docs that using `defaultLocale` may try to redirect from 404 but I can't make it work…

My nuxt-i18n config:
```js
'nuxt-i18n',
      {
        strategy: 'prefix_except_default',
        locales: [
          {
            code: 'en',
            name: 'English',
            iso: 'en-US',
            file: 'en.js',
          },
          {
            code: 'fr',
            name: 'Français',
            iso: 'fr-FR',
            file: 'fr.js',
          },
        ],
        lazy: true,
        langDir: 'i18n/',
        defaultLocale: 'fr',
        vueI18n: {
          fallbackLocale: 'fr',
        },
        vueI18nLoader: true,
      }
```

Thanks a lot!

**Comment by rchl** [comment]
Maybe you should file an issue for `content` since it's `content` that knows which languages are missing so it's in the best position to disable the language selector if necessary.

**Comment by mauricemojito** [comment]
I have the same problem now. when I disable the nuxt language selector it shows the hreflang link to the page and conflicts with seo
