### ISSUE TITLE
Load "jump" using detectBrowserLanguage

### ISSUE THREAD

**Issue by ghost** [nuxt-modules/i18n#894]
Is there any way to redirect language before the browser starts to load the default language?

For example, using this configuration:

```
i18n: {
    locales: ['fr', 'en'],
    defaultLocale: 'fr',
    detectBrowserLanguage: {
      useCookie: false,
      onlyOnRoot: true
    },
    vueI18n: {
      fallbackLocale: 'en',
    }
  }
```

When a user that is not set on default Locale 'fr' access domain.com, default locale loads for a second before the browser redirect to domain.com/en. This causes the content to jump from the french to the english version of the site, which is not super pretty. Can I avoid this using another technique?

Thanks a lot for your help.

**Comment by rchl** [comment]
Sounds like a bug. It would be better if you would file an issue rather than question and provide more information on how you are running / deploying nuxt because I'm pretty sure it shouldn't happen with default nuxt settings.

**Comment by ghost** [comment]
I did it. See [here](https://github.com/nuxt-community/i18n-module/issues/895).
