### ISSUE TITLE
request headers “Accept-Language” has a higher priority than domain path "/en"

### ISSUE THREAD

**Issue by baotlake** [nuxt-modules/i18n#897]
### Version
nuxt-i18n: 6.15.1 
nuxt: 2.13.0

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [√] universal
 - [] spa

### Nuxt-i18n configuration

```
i18n: {
    locales: ['zh', 'en'],
    differentDomains: false,
    defaultLocale: 'zh',
    vueI18n: {
      fallbackLocale: 'zh',
      messages: {
        en: require('../lang/en.json'),
        zh: require('../lang/zh.json'),
      },
    },
  }
```

### Steps to reproduce
I apologize for not being able to provide an example to reproduce this problem. But maybe you can reproduce the problem with a simple command.

This project has two languages, Chinese and English， Chinese is the default language. So, when I visit "http://localhost:3000/en", I expect that I will open the English version of the website, But in fact it is not the case. Sometimes it returns 302 and redirects to the Chinese version of the website. 

```
curl -I http://localhost:3000/en -H 'Accept-Language:zh-CN,zh'
```
The above command will return ***302 Found***
```
HTTP/1.1 302 Found
Location: /
Date: Sun, 20 Sep 2020 03:41:54 GMT
Connection: keep-alive
```

### What is actually happening?

I need to add a domain to my project. This domain only provides English version services. so I need to redirect the request to "/en" in nginx. 

And then I find that the browser sometimes fails to visit the website because of ***too many redirects***, that is to say sometimes I visit ***"/en"***, nuxt-i18n will redirect to ***"/"***, finally, I found that it was caused by the request header "Accept-Language", I had to reset the header: "Accept-Language" in nginx  to solve this problem.

**Comment by rchl** [comment]
Have you seen and tried the [detectBrowserLanguage.onlyOnRoot](https://i18n.nuxtjs.org/options-reference#detectbrowserlanguage) option?

**Comment by baotlake** [comment]
Yes, after I discovered this problem, I noticed this option in the document. This option is false by default. I did not declare this option before. After discovering this problem, I tried to proactively declare it as false, But I don’t know if the configuration is incorrect or other problems, the problem still exists, so I just reset the header "accept-language" in nginx

**Comment by rchl** [comment]
You should try setting it to true

**Comment by baotlake** [comment]
Sorry
```
{
    locales: ['zh', 'en'],
    differentDomains: false,
    detectBrowserLanguage: {
      onlyOnRoot: true,
    },
    defaultLocale: 'zh',
    vueI18n: {
      fallbackLocale: 'zh',
      messages: {
        en: require('../lang/en.json'),
        zh: require('../lang/zh.json'),
      },
    },
  }
```
 I configured it like this, but it still returns "302 Found" when I request "/en"

**Comment by rchl** [comment]
Without `onlyOnRoot` it's expected that you get redirected with that CURL command.
With `onlyOnRoot` it should not redirect and it doesn't here.

Make sure you are using the latest `nuxt-i18n` version and try to create a repro on codesanbox if you can still reproduce.

**Comment by baotlake** [comment]
I currently do not reproduce this problem in codesandbox. 
Is there an option to disable detectBrowserLanguage, if I do not want to redirect under the root path, what should I do?

**Comment by rchl** [comment]
detectBrowserLanguage: false

**Comment by baotlake** [comment]
Thank you for your patient help.
