### ISSUE TITLE
How to custom path prefix with router base

### ISSUE THREAD

**Issue by Ichalle** [nuxt-modules/i18n#898]
Hello!

I have website using default locale indonesia and that is also available in english.

**What is Expected?**
http://mywebsite.com/id/landing/about/

**What is actually happening?**
http://mywebsite.com/landing/id/about/

Version
nuxt-i18n: 6.15.1
nuxt: 2.14.0

Nuxt configuration
mode: universal

nuxt.config.js
```
router: {
    base: '/landing/'
},
////
modules: [
    'bootstrap-vue/nuxt',
    ['nuxt-i18n'],
],
i18n: {
    strategy: 'prefix',
    locales: ['id', 'en'],
    defaultLocale: 'id',
    paths: {
      en: '/landing/',
      id: '/landing/'
    },
  }
```

**Comment by rchl** [comment]
You can't as far as I can tell. The `router.base` is considered the root of the site and you can't control anything above that.

That makes sense since the typical use case for `router.base` is when you have server exposed at that base and anything above that would likely reach another server.
