### ISSUE TITLE
Hitting Not Found Before Applying I18N

### ISSUE THREAD

**Issue by x-N0** [nuxt-modules/i18n#899]
### Version, Nuxt configuration
[Webpage](https://i18n.nuxtjs.org/es/), so... latest deployment(?

### Reproduction Link
Go to google, search for Nuxt

### Steps to reproduce
![ReprGif](https://github.com/Collabos/BugRepr/blob/master/Not-Found-i18nNuxt-Issue.gif)

### What is Expected?
Switch and load as a found resource.

### What is actually happening?
Hitting a "Not Found" while the lookup of the resource.

**Comment by rchl** [comment]
https://i18n.nuxtjs.org/es/ is loading fine here. Not sure what is the issue you are seeing (the food was not attached properly).

**Comment by rchl** [comment]
Can you copy and paste here the URL of that Google result?

**Comment by rchl** [comment]
I've updated dependencies and I think the problem should be gone now.
