### ISSUE TITLE
i18n is undefined available under nuxt context in nuxt plugin

### ISSUE THREAD

**Issue by MartinMalinda** [nuxt-modules/i18n#902]
### Version
nuxt-i18n: 6.13.12
nuxt: 2.12.2

### Steps to reproduce

```ts
export default (ctx: NuxtContext, inject): void => {
  const { app } = ctx;
  const { $axios, $i18n } = app;
  // $i18n is undefined
};
```

### What is Expected?

$i18n is undefined under `ctx.app`

---

This issue is already discussed here: https://github.com/nuxt-community/i18n-module/issues/874#issuecomment-692366233

But I didn't want to comment on a closed issue.

I tried to implement a fix that is recommended there - registering the plugin via a module, but it didn't fix it for me. Maybe I missed something.

`modules/api-call-register.ts`
```ts
import path from 'path';

export default function apiCallRegister(this: any) {
  this.addPlugin(path.resolve(__dirname, '../client/plugins/apiCall.ts'));
}
```

`plugins/apiCall.ts`
```ts
export default (ctx: NuxtContext, inject): void => {
  const { app } = ctx;
  const { $axios, $i18n } = app;
  inject('apiCall', apiCallFactory({ $axios, $i18n: $i18n as any }));
};
```

`config:`
```
  modules: [
    'nuxt-i18n',
    '@nuxtjs/axios',
    '@nuxtjs/sentry',
    '@nuxtjs/auth',
    'nuxt-user-agent',
    '~~/modules/api-call-register.ts',
    '~~/modules/helmet.ts',
  ],
  plugins: [
    `~/plugins/apiCall.ts`,
  ],
```

Any tips appreciated 🙏 I guess I'm missing something trivial in the module

**Comment by rchl** [comment]
1. `nuxt-i18n` doesn't inject to `context.$i18n`, only to `context.app.i18n`
2. There is no need to create a wrapper module really. Plugins registered in `plugins` will run after plugins added by modules (as long as modules are adding them from the main execution context which `nuxt-i18n` does after the mentioned fixes).

**Comment by rchl** [comment]
3. This module ships with types so you can add `nuxt-i18n` to `types` array in `tsconfig.json` and it should be more clear what is available and where.

**Comment by MartinMalinda** [comment]
> nuxt-i18n doesn't inject to context.$i18n, only to context.app.i18n

That is where I am retreiving it from:

```ts
  const { app } = ctx;
  const { $axios, $i18n } = app;
```

> There is no need to create a wrapper module really. Plugins registered in plugins will run after plugins added by modules (as long as modules are adding them from the main execution context which nuxt-i18n does after the mentioned fixes).

In that case I don't understand why i18n is undefined

<img width="555" alt="Screenshot 2020-09-22 at 15 29 02" src="https://user-images.githubusercontent.com/9468793/93898021-0a670e80-fcf3-11ea-85f6-3b968a5da249.png">

> This module ships with types

I'll check it out, thanks!

**Comment by rchl** [comment]
`context.app.i18n` not `context.app.$i18n`. :)

**Comment by rchl** [comment]
Also, check documentation https://i18n.nuxtjs.org/api#extension-of-nuxt-context

**Comment by MartinMalinda** [comment]
That's it! Thanks 🤦 It used to work before though.
