### ISSUE TITLE
Locale switches back to default after `setLocale`

### ISSUE THREAD

**Issue by MartinMalinda** [nuxt-modules/i18n#903]
### Version
nuxt-i18n: 6.13.12
nuxt: 2.12.2

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [x] spa

### Nuxt-i18n configuration
```
  i18n: {
    lazy: true,
    langDir: '../locales/',
    locales: ..., // some dynamic code here
    strategy: 'prefix',
    defaultLocale: 'en',
    detectBrowserLanguage: {
      // If enabled, a cookie is set once a user has been redirected to his
      // preferred language to prevent subsequent redirections
      useCookie: true,
      // Cookie
      cookieKey: 'language',
      cookieSecure: true,
      // Set to always redirect to value stored in the cookie, not just once
      alwaysRedirect: true,
      // If no locale for the browsers locale is a match, use this one as a fallback
      fallbackLocale: 'en',
    },
  },
```

### Steps to reproduce
1. I am on locale `en`
2. I select `cs` via `$i18n.setLocale('cs');`
3. cookie is successfuly updated to `cs`
4. nuxt-auth is redirecting to `/cs`
5. after next boot something - and I can't find it in the code (I put debugger to all places in `plugin.main.js` where redirection happens) - is redirecting back to `/en`
6. on visit of `/en` cookie is set back to `en` which is expected

### What is Expected?

The redirect back to default locale does not happen

**Comment by rchl** [comment]
I can't really investigate without a reproduction repo.

**Comment by MartinMalinda** [comment]
@rchl 

I did some more debugging and docs reading and the issue is now clear to me.

It's the combination of `alwaysRedirect` and `detectBrowserLanguage` and `useCookie`.

When I `setLocale` that causes a redirect, after redirect the `detectBrowserLanguage` will prefer the browser language over the value from the cookie.

I'd expect the browser language would be used only if there's no cookie but the priority is different. I'm not sure if this is a bug or a feature though.

And then I found out that `onlyOnRoot` mostly fixes the issue for me.
But even still, even on `/` I'd expect that cookie has higher priority over browser language. Is that just me?

**Comment by MartinMalinda** [comment]
Is this clear? Should I still create the reproduction repo? Thanks!

**Comment by divine** [comment]
> And then I found out that `onlyOnRoot` mostly fixes the issue for me.
> But even still, even on `/` I'd expect that cookie has higher priority over browser language. Is that just me?

It's working fine. Redirecting based on cookie in the first place _only on root path_.

**Comment by rchl** [comment]
Yes, would need a repro to see what's wrong.

**Comment by MartinMalinda** [comment]
> It's working fine. Redirecting based on cookie in the first place only on root path.

In my experience the cookie is read only if `!finalLocale` which comes from `doDetectBrowserLanguage`. So if the browser language detection succeeds, the cookie is not read.

https://github.com/nuxt-community/i18n-module/blob/master/src/templates/plugin.main.js#L265

> Yes, would need a repro to see what's wrong.

On it!

**Comment by rchl** [comment]
> In my experience the cookie is read only if `!finalLocale` which comes from `doDetectBrowserLanguage`. So if the browser language detection succeeds, the cookie is not read.

But `doDetectBrowserLanguage` will consider cookie before anything else: https://github.com/nuxt-community/i18n-module/blob/2e2658b3a061cf2a22ad216c357b344722a891a7/src/templates/plugin.main.js#L194

But it's possible that there is some logic error there with some combination of options. There are too many options...

**Comment by MartinMalinda** [comment]
So I couldn't reproduce in a different repo and it made me double check my main app code.

It turned out I had two cookies with same key but with different domains (somehow). I guess it was a leftover from much earlier. `JsCookie.get(cookieKey)` preferred it over the new one and that's why the language was switching wrongly for me.

Sorry for the time waste! I think this can be closed.
