### ISSUE TITLE
"export 'default' (imported as 'deepcopy') was not found in 'deepcopy

### ISSUE THREAD

**Issue by ProduceSinapsi** [nuxt-modules/i18n#907]
### Version
nuxt-i18n: "^6.15.1"
nuxt:  "^2.14",

### Nuxt configuration
 - [x] universal
 - [] spa

### Nuxt-i18n configuration
```
i18n: {
    vueI18n: {},
    // If true, vue-i18n-loader is added to Nuxt's Webpack config
    vueI18nLoader: true,

    // List of locales supported by your app
    // This can either be an array of codes: ['en', 'fr', 'es']
    // Or an array of objects for more complex configurations:
    // [
    //   { code: 'en', iso: 'en-US', file: 'en.js' },
    //   { code: 'fr', iso: 'fr-FR', file: 'fr.js' },
    //   { code: 'es', iso: 'es-ES', file: 'es.js' }
    // ]
    //   `iso` value should have either:
    //   - code of ISO 639-1 (e.g. 'en')
    //   - code of ISO 639-1 and code of ISO 3166-1 alpha-2, with a hyphen (e.g. 'en-US')
    locales: [
      {
        name: 'English',
        code: 'en',
        iso: 'en-US',
        file: 'en.js',
      },
      {
        name: 'Italiano',
        code: 'it',
        iso: 'it-IT',
        file: 'it.js',
      },
    ],

    // The app's default locale, URLs for this locale won't have a prefix if
    // strategy is prefix_except_default
    defaultLocale: 'it',

    // Separator used to generated routes name for each locale, you shouldn't
    // need to change this
    routesNameSeparator: '___',

    // Suffix added to generated routes name for default locale if strategy is prefix_and_default,
    // you shouldn't need to change this
    defaultLocaleRouteNameSuffix: 'default',

    // Routes generation strategy, can be set to one of the following:
    // - 'no_prefix': routes won't be prefixed
    // - 'prefix_except_default': add locale prefix for every locale except default
    // - 'prefix': add locale prefix for every locale
    // - 'prefix_and_default': add locale prefix for every locale and default
    strategy: 'prefix_except_default',

    // Wether or not the translations should be lazy-loaded, if this is enabled,
    // you MUST configure langDir option, and locales must be an array of objects,
    // each containing a file key
    lazy: true,

    // Directory that contains translations files when lazy-loading messages,
    // this CAN NOT be empty if lazy-loading is enabled
    langDir: 'lang/',

    // Set this to a path to which you want to redirect users accessing root URL (/)
    rootRedirect: null,

    // Enable browser language detection to automatically redirect user
    // to their preferred language as they visit your app for the first time
    // Set to false to disable
    detectBrowserLanguage: {
      // If enabled, a cookie is set once a user has been redirected to his
      // preferred language to prevent subsequent redirections
      // Set to false to redirect every time
      useCookie: true,
      // Cookie name
      cookieKey: 'i18n_redirected',
      // Set to always redirect to value stored in the cookie, not just once
      alwaysRedirect: false,
      // If no locale for the browsers locale is a match, use this one as a fallback
      fallbackLocale: null,
    },

    // Set this to true if you're using different domains for each language
    // If enabled, no prefix is added to your routes and you MUST configure locales
    // as an array of objects, each containing a domain key
    differentDomains: false,

    // If true, SEO metadata is generated for routes that have i18n enabled.
    // Note that performance can suffer with this enabled and there might be compatibility
    // issues with some plugins. Recommended way is to set up SEO as described in:
    // https://nuxt-community.github.io/nuxt-i18n/seo.html#improving-performance
    seo: false,

    // Fallback base URL to use as prefix for alternate URLs in hreflang tags.
    // By default VueRouter's base URL will be used and only if that is not available,
    // fallback URL will be used.
    baseUrl: '',

    // By default a store module is registered and kept in sync with the
    // app's i18n current state
    // Set to false to disable
    vuex: {
      // Module namespace
      moduleName: 'i18n',

      // If enabled, current app's locale is synced with nuxt-i18n store module
      syncLocale: true,

      // If enabled, current translation messages are synced with nuxt-i18n store module
      syncMessages: false,

      // Mutation to commit to set route parameters translations
      syncRouteParams: true,
    },

    // By default, custom routes are extracted from page files using babel parser,
    // set this to false to disable this
    parsePages: true,

    // By default, custom paths will be encoded using encodeURI method.
    // This does not work with regexp: "/foo/:slug-:id(\\d+)". If you want to use
    // regexp in the path, then set this option to false, and make sure you process
    // path encoding yourself.
    encodePaths: true,

    // Called right before app's locale changes
    beforeLanguageSwitch: (oldLocale, newLocale) => null,

    // Called after app's locale has changed
    onLanguageSwitched: (oldLocale, newLocale) => null,
  },
```

### What is actually happening?
![image](https://user-images.githubusercontent.com/57394476/94535794-41cd4200-0242-11eb-86ae-61fd8311df1e.png)

const vueI18nOptions = typeof vueI18n === 'function' ? vueI18n(context) : deepcopy(vueI18n)

Warning error appears in console:
./.nuxt/nuxt-i18n/plugin.main.js 309:80-88"export 'default' (imported as 'deepcopy') was not found in 'deepcopy'

**Comment by rchl** [comment]
Remove your `node_modules` and re-install them.

If that doesn't help, please post your `package-lock.json` or `yarn.lock` contents somewhere (https://gist.github.com/ maybe).

**Comment by ghost** [comment]
Also seeing this after updating to `v6.15.1` with a clean `npm i`

**Comment by rchl** [comment]
Feel free to help me to solve this issue by providing some information (answer my question or provide a repo).
I've misplaced my crystal ball somewhere.

**Comment by karlpower6** [comment]
@rchl Looks like deepcopy is not exported as default since `v2.1.0`
https://github.com/sasaplus1/deepcopy.js/blob/bc496ea7acc4dc6abc1787dfce170070cd131efa/src/index.ts#L92

**Comment by karlpower6** [comment]
I created a PR https://github.com/nuxt-community/i18n-module/pull/908

**Comment by rchl** [comment]
Please provide Nuxt project repo that reproduces.

**Comment by filippolcr** [comment]
> Remove your `node_modules` and re-install them.
> 
> If that doesn't help, please post your `package-lock.json` or `yarn.lock` contents somewhere (https://gist.github.com/ maybe).

Sorry for the late response. Too busy. No luck with this. I will send you the package.json shortly

**Comment by filippolcr** [comment]
> Also seeing this after updating to `v6.15.1` with a clean `npm i`

I tried to downgrade to versions 6.14.2 and 6.13.12 but the error persist

**Comment by rchl** [comment]
As I've said before, verify if it still happens after deleting `node_modules` and re-installing dependencies. There was a caching bug in older Nuxt versions that would cause such issues. Removing `node_modules` would delete the cache.

If it still reproduces then I need to see the exact project with the lock file.

**Comment by filippolcr** [comment]
package.json
https://gist.github.com/filippolcr/a695eb042d092d887bc669ac3b821fc9

package.lock
https://gist.github.com/filippolcr/bc06cc9c650eab544cad1f9c04297457

Is it enough for you? 

I can tell you that until a few days it never happened.

Thanks 🤙🏻

**Comment by rchl** [comment]
No, sorry, this doesn't reproduce and I don't see anything wrong there.

Maybe it's related to node version? Which one are you running?

**Comment by filippolcr** [comment]
I'm using nvm.
So, the .nvmrc says: 12.16.3
but nvm current command print v10.19.0

🤔

**Comment by ghost** [comment]
@rchl 
This repo should reproduce: https://github.com/karlpower6/nuxti18n
Seems to be an issue below Nuxt v2.12

**Comment by rchl** [comment]
I can reproduce on that old version. I wonder why everyone before was saying that it happens in the latest version... :)

Seems like https://github.com/nuxt/nuxt.js/pull/7070 is what fixed it in 2.12.
Not sure if it's fixable on my side, short of switching to some other library similar to deepcopy.

**Comment by ProduceSinapsi** [comment]
> I can reproduce on that old version. I wonder why everyone before was saying that it happens in the latest version... :)
> 
> Seems like [nuxt/nuxt.js#7070](https://github.com/nuxt/nuxt.js/pull/7070) is what fixed it in 2.12.
> Not sure if it's fixable on my side, short of switching to some other library similar to deepcopy.

I've tried to come back to a previous branch and I notice that the error disappears when the nuxt-i18n version is set to "nuxt-i18n": "^ 6.13.1" and nuxt ":" ^ 2.14 "

**Comment by filippolcr** [comment]
> I can reproduce on that old version. I wonder why everyone before was saying that it happens in the latest version... :)
> 
> Seems like [nuxt/nuxt.js#7070](https://github.com/nuxt/nuxt.js/pull/7070) is what fixed it in 2.12.
> Not sure if it's fixable on my side, short of switching to some other library similar to deepcopy.

I've tried to come back to a previous branch and I notice that the error disappears when the nuxt-i18n version is set to "nuxt-i18n": "^ 6.13.1" and nuxt ":" ^ 2.14 "

**Comment by rchl** [comment]
@filippolcr The bug is fixed from Nuxt v2.12. You shouldn't see it regardless of which version of `nuxt-i18n` you are using. 

And an older version of `nuxt-i18n` didn't use `deepcopy` library which is a problematic one here so then you would also not see the issue.

And since you are saying that you are on `^2.14` range of Nuxt (as is the initial comment), I don't see how you can get this issue in the first place...

**Comment by filippolcr** [comment]
> @filippolcr The bug is fixed from Nuxt v2.12. You shouldn't see it regardless of which version of `nuxt-i18n` you are using.
>
> And an older version of `nuxt-i18n` didn't use `deepcopy` library which is a problematic one here so then you would also not see the issue.
> 
> And since you are saying that you are on `^2.14` range of Nuxt (as is the initial comment), I don't see how you can get this issue in the first place...

I'm worked on package.json configuration and I've tried some combinations./

For now the only trick is to revert to the "nuxt-i18n" version: "6.13.8", as explained previously.

Is it impossible that it is related to some module settings itself?

It seems strange to me, I'm using the latest version of Nuxt.

**Comment by rchl** [comment]
Then please provide a repo that reproduces.
If you have sensitive data in the repo then please remove all of that.

**Comment by ghost** [comment]
i have the same issue using nuxt 2.11, looks need updaing then

**Comment by rchl** [comment]
https://github.com/nuxt-community/i18n-module/releases/tag/v6.15.4 no longer uses `deepcopy`.

**Comment by filippolcr** [comment]
> https://github.com/nuxt-community/i18n-module/releases/tag/v6.15.4 no longer uses `deepcopy`.

The release 6.15.4 solve completely this issue. 
Now my package.json contains:
`  
   "nuxt-i18n": "^6.15.4",  
   "nuxt": "^2.14" 
`

> Then please provide a repo that reproduces. 

My apologies rchl to not submitting the repo, Do you still need it? Am I back fully operational? 🙏

**Comment by rchl** [comment]
> My apologies rchl to not submitting the repo, Do you still need it? Am I back fully operational?

The issue is fixed so I don't need the repro anymore, thanks.
