### ISSUE TITLE
Got VueI18n instance, expected NuxtI18n instance

### ISSUE THREAD

**Issue by gulien** [nuxt-modules/i18n#910]
### Version
nuxt-i18n: `6.15.1`
nuxt: `2.14.0`

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [ ] spa

### Steps to reproduce

I have a method `async onSubmit()` on my `pages/login.vue` component.

On login success, I want to redirect the user to the home page with: `this.$router.push(this.$i18n.localePath({ name: 'index' }))`.

### What is Expected?

Routing success.

### What is actually happening?

`TypeError: _this.$i18n.localePath is not a function`

<img width="691" alt="Capture d’écran 2020-10-02 à 11 35 41" src="https://user-images.githubusercontent.com/8983173/94909413-696f1500-04a3-11eb-9ae5-4b1f05c8cc6b.png">

AFAIK, it seems that I got an `VueI18n` instance instead of a `NuxtI18n` instance and this instance does not contain the method `localePath`.

**Comment by rchl** [comment]
Use `this.localePath`. it's not part of Vue I18n instance.

**Comment by gulien** [comment]
😄 works great now! Thank you for the quick reply 👍
