### ISSUE TITLE
Static target doesn't prerender root page (prefixed strategy)

### ISSUE THREAD

**Issue by divine** [nuxt-modules/i18n#911]
Houston, we have a problem <strike>SEO issues</strike>! 😅

### Version
nuxt-i18n: 6.15.1
nuxt: 2.14.6

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [x] target: 'static'
### Nuxt-i18n configuration

```
i18n: {
    strategy: 'prefix',
    detectBrowserLanguage: {
      onlyOnRoot: true
    },
    defaultLocale: "en"
}
```

### Reproduction Link
Surge: http://helpless-death.surge.sh/
Github: https://github.com/divine/i18n-static-redirect

### Steps to reproduce
`yarn generate` && `cd dist` && `cat index.html`

### What is Expected?

Root path generated `index.html` * should be generating page based on default locale.

\* which is used for redirection after page load

### What is actually happening?

Target static doesn't prerender page content at all**. However `target: 'server'` produces correct result.

\** You can check that there is no content at all as well as no title.

Thanks!

**Comment by rchl** [comment]
Let's discuss in #912 first as I think those are related.

**Comment by rchl** [comment]
The fallback page doesn't have content because it triggers a redirect (which results in content not being rendered).

I could suppress redirects when generating pages for static mode but I'm not sure about the consequences...
