### ISSUE TITLE
Infinite loop of redirects with onlyOnRoot option.

### ISSUE THREAD

**Issue by Perezmarc** [nuxt-modules/i18n#917]
Hi, 
I'm trying to implement the onlyOnRoot option, I've been looking forward to it :)
On the root path, I get the proper experience, but when I change to any other page, 
I get an infinite loop of redirects to the same page.

I think it only happens in production, I cannot reproduce it locally.

If I set the `onlyOnRoot` option to `false`, the loop does not happen.

### Version
"nuxt-i18n": "^6.15.1"
"nuxt": "^2.14.6",

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal
 - [] spa

### Steps to reproduce
- deploy a nuxt page as a static page
- add the `onlyOnRoot: true` configuration under nuxt-i18n module
- go to any non-root page of your site and the redirect loop occurs

### What is Expected?
No loop on reload or go to a page that is not the root with "onlyOnRoot: true"

### What is actually happening?

- On the root path, I get the proper experience
-  Going to any non-root page **I get an infinite loop of redirects to the same page.**
- I think it only happens in production, I cannot reproduce it locally.
- If I set the `onlyOnRoot` option to `false`, the loop does not happen.

Thanks! 

PS: I love the plugin :)

**Comment by rchl** [comment]
Are you deploying static page or to a node server?

If to a node server then please log the redirects with browser developer tools (in Network section).

If deploy static page then redirects are probably in JS and you can't see easily where it's redirecting.

If you can't figure it out yourself then you need to provide more information. Your full nuxt configuration, including the modules you are using and any custom redirects that you might be using in your pages.

**Comment by Perezmarc** [comment]
I'm deploying it as a static page through github pages.

The config file looks like this:
```
const routerBase =
  process.env.DEPLOY_ENV === "GH_PAGES"
    ? {
        router: {
          base: "/"
        }
      }
    : {};

export default {
  mode: "universal",
  /*
   ** Headers of the page
   */
  head: {
    title: process.env.npm_package_name || "",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        hid: "description",
        name: "description",
        content: process.env.npm_package_description || ""
      }
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }]
  },
  /*
   ** Customize the progress-bar color
   */

  loading: { color: "#fff" },
  /*
   ** Global CSS
   */
  css: ["@/assets/sass/main.sass"],
  /*
   ** Plugins to load before mounting the App
   */
  plugins: [
    { src: "~/plugins/gsap", ssr: false },
    { src: "~/plugins/consentCookies/index.js", ssr: false }
  ],
  /*
   ** Nuxt.js modules
   */
  buildModules: [
    [
      "nuxt-i18n",
      {
        strategy: "prefix_and_default",
        locales: [
          {
            name: "English",
            code: "en",
            iso: "en-US"
          },
          {
            name: "Español",
            code: "es",
            iso: "es-ES"
          }
        ],
        vueI18n: {
          fallbackLocale: "en",
          messages: {
            en: require("./locale/en.json"),
            es: require("./locale/es.json")
          },
          silentTranslationWarn: false
        },
        defaultLocale: "es",
        seo: false,
        baseUrl: "https://getsilt.com",
        detectBrowserLanguage: {
          useCookie: true,
          cookieKey: "i18n_redirected",
          onlyOnRoot: true
        }
      }
    ],
    "@nuxtjs/router-extras",
    "@nuxtjs/sitemap",
    "@nuxtjs/robots",
    [
      "@nuxtjs/google-analytics",
      {
        id: "UA-160379082-1"
      }
    ]
  ],
  sitemap: {
    i18n: true,
    i18n: {
      locales: ['en', 'es'],
      routesNameSeparator: '___'
    },
    hostname: "https://getsilt.com",
    path: "/sitemap.xml",
    cacheTime: 1000 * 60 * 60 * 2,
    trailingSlash: true,
    gzip: true,
    exclude: [
      "/en/cookies",
      "/en/legal-notice",
      "/en/privacy",
      "/cookies",
      "/legal-notice",
      "/privacy"
    ]
  },

  robots: {
    UserAgent: "*",
    Disallow: ["/cookies", "/legal-notice", "/privacy"]
  },

  ...routerBase,
  router: {
    middleware: "redirects",
    extendRoutes(routes, resolve) {
      routes.push({
        name: 'index',
        path: '/',
        component: resolve(__dirname, 'pages/business.vue')
      })
    }
  },
  generate: {
    fallback: "404.html"
  },
  /*
   ** Build configuration
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {},
    postcss: {
      // Add plugin names as key and arguments as value
      // Install them before as dependencies with npm or yarn
      plugins: {
        // Disable a plugin by passing false as value
        "postcss-url": false,
        "postcss-nested": {},
        "postcss-responsive-type": {},
        "postcss-hexrgba": {}
      },
      preset: {
        // Change the postcss-preset-env settings
        autoprefixer: {
          grid: true
        }
      }
    }
  }
};

```

this is the middleware that redirects only in these cases, but the loop happens for every page, even disabling this middleware.
```
export default function({ app, params, route, redirect }) {
  // hypothetical set of all supported locales
  if (route.path=== "/users") {
    if (app.i18n.locale === 'es')
        redirect('301', '/identidad-digital-para-usuarios');
    else if (app.i18n.locale === 'en')
        redirect('301', '/en/digital-identity-for-users');
    else
        redirect('301', '/en/digital-identity-for-users');

  } else if (route.path === "/business") {
    redirect("301", "/");
  }
}

```

Note again that if I disable "onlyOnRoot", the redirect does not take place.

Thanks! :)

**Comment by rchl** [comment]
What is the `redirects` middleware doing? Sounds like something that could fight with nuxt-i18n over redirections.

Try to minimize your project by removing all other parts and see if you can still reproduce. I can't help you if I don't have access to the parts that you haven't shared.

**Comment by Perezmarc** [comment]
The middleware does not affect the result, I tried deactivating it. You have it in the previous message.
I noticed that it happens when I reload or navigate through the address bar. 
It does not happen when navigating using a link inside a page.

**Comment by Perezmarc** [comment]
you can check the issue now here:
https://getsilt.com/developers/ 

I will deactivate the onlyonroot in an hour

**Comment by rchl** [comment]
The links point to `https://getsilt.com/en/developers` but your hosting is redirecting to `https://getsilt.com/en/developers/`. I think you should disable those redirects in your hosting settings.

**Comment by rchl** [comment]
And if there is no way to change the hosting settings related to trailing slashes (and [this comment](https://stackoverflow.com/a/54791518/986604) seems to suggest that there isn't), then you could experiment with those Nuxt settings:
 - https://nuxtjs.org/guides/configuration-glossary/configuration-router#trailingslash
 - https://nuxtjs.org/guides/configuration-glossary/configuration-generate#subfolders

**Comment by Perezmarc** [comment]
I tried everything before, but it was not until I tried your tip of `subfolders` that worked with the onlyOnRoot option set to true!
Thank you very much!

**Comment by rchl** [comment]
You are welcome.

Just a warning that using those non-default options can in theory have some unwanted consequences since those are not very well tested.

I've also noticed that the reason you get into that loop is that your routes have `pathToRegexpOptions: { strict: true }` set. I'm not sure what does set that, probably one of the other modules. Without it, the redirect would only happen at most once since the routes with and without trailing slash would be considered equivalent.
