### ISSUE TITLE
Matched error when navigate using dynamic pages at same folder level

### ISSUE THREAD

**Issue by ajmasia** [nuxt-modules/i18n#926]
### Version
nuxt-i18n: 6.15.1
nuxt: 2.14.0

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [] spa

### Nuxt-i18n configuration

```javascript
i18n: {
    strategy: 'no_prefix',
    locales: [
      {
        code: 'es',
        iso: 'es-ES',
        file: 'es-ES.js',
        name: 'Español',
        domain: 'https://mydomain.com',
      },
      // {
      //   code: 'en',
      //   iso: 'en-US',
      //   file: 'en-US.js',
      //   name: 'English',
      //   domain: 'https://en.mydomain.com',
      // },
    ],
    vueI18n: {
      fallbackLocale: 'es',
    },
    defaultLocale: 'es',
    noPrefixDefaultLocale: true,
    parsePages: false,
    detectBrowserLanguage: false,
    seo: true,
    lazy: true,
    langDir: 'i18n/',
  },
```

### Reproduction Link
https://codesandbox.io/s/suspicious-night-zbhxz?file=/pages/blog/index.vue

### Steps to reproduce
I have two dynamic routes nested in the blog route. One of them shows the posts detail `_slug.vue` and the other shows a list of posts related to a category` _category.vue`. When I access to the detail of a post from the path `_category.vue`. instead of using the path `blog-name` keep using` blog-category '.

Both routes use the same PostCard component, that redirects to the `_slug.vue` page:

```js
<NuxtLink
    :to="
      localePath({
        name: 'blog-slug',
        params: { slug: post.slug },
      })
    "
  >
```

But it doesn't redirect well. It does this using the path `_category.vue`:

![Screenshot 2020-10-12 at 13 29 04](https://user-images.githubusercontent.com/23419327/95741713-0c3b4680-0c8f-11eb-853d-32cf1f3f1b48.png)

That is my current pages:

![Screenshot 2020-10-12 at 13 31 03](https://user-images.githubusercontent.com/23419327/95741816-3b51b800-0c8f-11eb-92be-ec8206821188.png)

### What is Expected?
When navigating from `http://localhost:8000/blog/page/1` to detail post,  should navigate to `http://localhost:8000/blog/post-slug using `_slug.vue` instead of `_category.vue`

### What is actually happening?
Navigating always using `_category.vue`

Note: Using NuxtLink whiteout `localePath`, works fine!

**Comment by rchl** [comment]
I'd ask you to make a repro project (either a repo or on codesanbox).

**Comment by ajmasia** [comment]
Hi @rchl, here you have a [codesanbox](https://codesandbox.io/s/suspicious-night-zbhxz?file=/pages/blog/index.vue) example. 

Using the `localePath` method, if you try to navigate to post detail, always use the `category` dynamic route. 

If you do not use the `localePath` work fine in dev mode. In production, it doesn't work either.

what could be happening?

Thanks for your patient wait 😄

**Comment by rchl** [comment]
I'm seeing this in my forked codesanbox where I haven't made any changes:

![Screen Recording 2020-10-18 at 20 32 09](https://user-images.githubusercontent.com/153197/96376789-44f08980-1181-11eb-9db9-5a09a20a5c84.gif)

It looks to me like this is how it's supposed to work? Why I'm not seeing the issue?

**Comment by ajmasia** [comment]
If you navigate to a post from the blog or categories pages you should see the post detail through the `_slug/index.vue` component
![Screenshot 2020-10-18 at 21 15 23](https://user-images.githubusercontent.com/23419327/96377623-137abc80-1187-11eb-9218-3724a1c3edd2.png)

If you remove all `localePath` methods work fine!

I've updated the codesanbox repo: https://codesandbox.io/s/suspicious-night-zbhxz?file=/pages/blog/index.vue

**Comment by rchl** [comment]
I can see that result in both cases...

Reloading the post page fails to show the extra detail though so I think you have a more fundamental problem.
Reloading the page triggers server-side rendering so you might be hiting problems related to that when doing client-side navigation.

**Comment by rchl** [comment]
I mean, If you want to support server-side requests (which you should) then I think that this directory structure is not a proper solution since Vue Router won't know which route to pick based on the URL path itself. So you can make client-side navigations work but that is only half of the solution.

Anyways, `localePath` just generates an URL so it's functionally equivalent to specifying a route path to navigate to manually. You can just compare what you get by using `localePath` and if it's the same as the one you are saying is working, then it should work exactly the same. If it's different, then let me know what it is and I can then try to see what the issue issue is.

**Comment by ajmasia** [comment]
I updated the routes structure, and works fine!

![Screenshot 2020-10-19 at 07 09 03](https://user-images.githubusercontent.com/23419327/96403981-ffac7600-11d9-11eb-9737-de6d86956e6b.png)

Now I can navigate to the post details using these path `year/month/_slug`, categories `category` and tags `tag/_tag` and blog pages `page/_number` to show the post list

Thanks for your help!

**Comment by rchl** [comment]
It still looks to me like server side rendering won't be able to differentiate between category and year/month/slug routes but at least it's not a nuxt-i18n issue.
