### ISSUE TITLE
Webpack Module parse failed: Unexpected token... with nuxt-i18n 6.15.2

### ISSUE THREAD

**Issue by exophunk** [nuxt-modules/i18n#929]
### Version
nuxt-i18n: 6.15.2
nuxt: 2.14.6
node: v14.2.0

### Nuxt configuration
```
export default {
    modules: [
        ['nuxt-i18n', {}],
    ],
};

```

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal
 - [] spa

### package.json
```
{
  ...
  "dependencies": {
    "core-js": "^3.6.5",
    "nuxt": "^2.14.6",
    "nuxt-i18n": "^6.15.2"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@nuxtjs/stylelint-module": "^4.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.10.0",
    "eslint-plugin-nuxt": "^1.0.0",
    "stylelint": "^13.7.2",
    "stylelint-config-standard": "^20.0.0"
  }
}

```

### Nuxt-i18n configuration
```
{}
```

### Steps to reproduce

Install nuxt-i18n with Version `6.15.2` and use it as a module. When running the project with `npm run dev`, webpack fails with this:

```
Module parse failed: Unexpected token (75:55) File was processed with these loaders: * ./node_modules/babel-loader/lib/index.js You may need an additional loader to handle the result of these loaders. | name: this.getRouteBaseName() | }; > const canonicalPath = this.localeRoute(currentRoute)?.path; | | if (!canonicalPath) { 
```

With `6.15.1` it works, only happens with `6.15.2`

1. Create new project with `npx create-nuxt-app test`
(I only add eslint + stylelint) everything else was default
2. npm install nuxt-i18n
3. Adjust nuxt config to include nuxt-18n module (nothing else)
4. run `npm run dev`
5. Webpack fails in my case

### What is Expected?
Webpack should build normally

### What is actually happening?

Webpack fails?

**Comment by zrisher** [comment]
Experiencing the same issue. Changing to `6.15.1` resolved it.

**Comment by exophunk** [comment]
Seems to be related to [this line](https://github.com/nuxt-community/i18n-module/commit/d09ad9e6f521a1c193fdb05f1ed2f26289586847#diff-b29aab519f53063465d99c7141a67617eb2591ad174ec05b66047310fe956819R95) because of the `?.` operator?

My babel config (which is default of new nuxt project):
```
{
    "env": {
        "test": {
            "plugins": [
                [
                    "module-resolver",
                    {
                        "root": [
                            "."
                        ],
                        "alias": {
                            "@": ".",
                            "~": "."
                        }
                    }
                ]
            ]
        }
    }
}

```

**Comment by rchl** [comment]
Released https://github.com/nuxt-community/i18n-module/releases/tag/v6.15.3 with a fix although optional chaining is supposed to be transpiled by Nuxt so not sure what's the issue.

I can reproduce this issue when using Node 14 but not Node 12.

**Comment by rchl** [comment]
Found Nuxt bug here: https://github.com/nuxt/nuxt.js/issues/7722
