### ISSUE TITLE
Can i use some cdn json files instand of local files? Or a translate json request from axios.

### ISSUE THREAD

**Issue by Feenormen** [nuxt-modules/i18n#931]
My project wants to set translate by require some cdn json files, but i can fine example about not use local files.
So i wanna know can i set that translate from axios?

**Comment by rchl** [comment]
The `file` property of the locale object can point to a file with an exported function in which you can have all the custom code to load your locale data -- https://i18n.nuxtjs.org/lazy-load-translations.
