### ISSUE TITLE
not possible to override SEO: false on page level

### ISSUE THREAD

**Issue by Martin7mind** [nuxt-modules/i18n#932]
### Version
nuxt-i18n: 6.15.3
nuxt: 2.12.0

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [] spa

### Steps to reproduce
1. set seo: true in nuxt config
2. set seo: false in page level
3. tags are still added in the head
![image](https://user-images.githubusercontent.com/58424724/96240540-52e7b400-0fa1-11eb-83ca-fd12b3c1e6c7.png)

**Comment by Martin7mind** [comment]
actually - setting seo: false in the nuxt config does not remove the canonical link and the html-lang attribute... :S

**Comment by divine** [comment]
Hello,

What target are you using (static or server)?

> nuxt: 2.12.0

I can't reproduce this on **v2.12.2** https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-spz5q

However, yes, it's not working on **v2.12.0**. Solution is simple: please update to version **2.12.2**!

Thanks!

**Comment by Martin7mind** [comment]
awesome and quick help! thanks a lot <3

**Comment by Martin7mind** [comment]
oh wait. in nuxt 2.12.2 setting seo: false works in nuxt config, but not on page level :(

**Comment by Martin7mind** [comment]
https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-xw5s4

im using server, btw

**Comment by divine** [comment]
Does changing `nuxtI18n` to `i18n` in component resolves your issue?

Thanks!

**Comment by Martin7mind** [comment]
no difference :/

also when setting the page to be available in only one locale, i get about 800 warnings when loading the page
![image](https://user-images.githubusercontent.com/58424724/96260045-c0560d80-0fbe-11eb-9887-8d90dab9e697.png)

![image](https://user-images.githubusercontent.com/58424724/96260132-dfed3600-0fbe-11eb-99f9-1f13c4b1017a.png)

**Comment by Martin7mind** [comment]
Seems like the codesandbox is down atm - will provide an example when its up again

**Comment by finalgamer** [comment]
I do have the same problem. 

```javascript
nuxtI18n: {
  seo: false
},
```

Is not recognized and meta/link tags are still added. I have also tried using just `i18n` instead of `nuxtI18n` without success.


Also I am unable to overwrite any meta tags.

like
```javascript
head() {
  link: [
    {hid: 'i18n-can', rel: 'canonical', href: 'bla'},
  ],
}

**Comment by AgustinBanchio** [comment]
Having the same issue! Setting seo to false in the page still results in tags and links generated in head.

**Comment by rchl** [comment]
~~`seo` option is not supported on the page level. Only in global settings.~~

The problem with warnings when disabling locales is known (related to #984).

**Comment by finalgamer** [comment]
@rchl If the seo option is not supported on page level the documentation needs to be updated.

https://i18n.nuxtjs.org/seo#requirements

> If you'd like to disable SEO on specific pages, set i18n.seo to false right in the page:
> ```javascript
> // pages/about.vue
> export default {
>  nuxtI18n: {
>    seo: false
>  }
>}
> ```

**Comment by iifawzi** [comment]
@rchl i dug into the code a little bit and that's what i found: 

`seo` option is supported in the page's level, there's a check in the `nuxtI18nSeo` function which checks weather the seo is disabled or not on the page's level, and logically? it should work. 
```js
if (
    (this.$options[COMPONENT_OPTIONS_KEY] && this.$options[COMPONENT_OPTIONS_KEY].seo === false)
  ) {
    return { }
  }
```

what i found is, that the problem happens because in each page, the seo plugin is applied on other components, like the layout component, default components (Transition, loading, NuxtBuildIndicator, etc... ) which re-generate the meta tags - because the global seo is enabled -

**Comment by rchl** [comment]
Right, yes, that sounds like the actual problem that I've also noticed when I've checked this back in the day.

Even when using the more performant solution (https://i18n.nuxtjs.org/seo#improving-performance), we'll be in the layout component when SEO is applied so the check won't work.

I think it would still require some solution like mentioned in https://github.com/nuxt-community/i18n-module/issues/932#issuecomment-763903759 so that we store those overrides somewhere where we could map them to the current route.

**Comment by iifawzi** [comment]
> actually - setting seo: false in the nuxt config does not remove the canonical link and the html-lang attribute... :S

I'm able to re-produce it in Nuxt v2.14.12.

**Comment by Josepdal** [comment]
Any update?

**Comment by divine** [comment]
> Any update?

Hello,

This option has been removed.

What kind of update do you expect?

Thanks!

**Comment by rchl** [comment]
In case someone wants to enable SEO meta globally and then exclude for some pages, I guess the solution right now is to create a helper function somewhere that will check the route name and return empty object instead of `$nuxtI18nHead` based on that.

**Comment by ArtemGrachov** [comment]
For ones who will face with same problem, I have found another workaround.
You have to disable `seo` option in `nuxt.config.js` file, then manually call `this.$nuxtI18nHead` where do you need it (in layouts, pages, mixins etc.). This way you will be able to change the object that `$nuxtI18nHead` returns.
