### ISSUE TITLE
Error parsing "nuxtI18n" component option in file

### ISSUE THREAD

**Issue by Luferov** [nuxt-modules/i18n#933]
### Version

nuxt: 2.14.7
nuxt-i18n: 6.15.3

nuxt.config.js
```js
{
 buildModules: [
    '@nuxt/typescript-build',
    '@nuxtjs/vuetify',
    ['nuxt-i18n', {
      lazy: true,
      langDir: 'lang/',
      defaultLocale: 'ru',
      locales: [
        { code: 'ru', file: 'ru.ts' },
        { code: 'en', file: 'en.ts' }
      ]
    }]
  ]
}
```

At the beginning of the assembly, it issues such warnings, and not on all pages.

![image](https://user-images.githubusercontent.com/26242554/96338247-55c3d100-1095-11eb-93ea-92883daf5411.png)

Could this cause problems?

**Comment by rchl** [comment]
Can you post the source of one of those files?

If you actually don't use `nuxtI18n` option in your pages then you can disable `parsePages` and the warning should go away.

**Comment by Luferov** [comment]
I use TS  . My component. When I delete `get bc()`, warning disappears. Perhaps, component style is bad way...
```js
<template lang="pug">
  bread-crumbs(:items="bc")
    v-row Dashboard
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { MetaInfo } from 'vue-meta'
import BreadCrumbs from '~/components/BreadCrumbs.vue'
import { BreadCrumbsItem } from '~/types/devind'
import TwoColumns from '~/components/global/TwoColumns.vue'

@Component<DashboardPageIndex>({
  components: { TwoColumns, BreadCrumbs },
  middleware: ['auth'],
  head (): MetaInfo {
    return { title: 'Dashboard' } as MetaInfo
  }
})
export default class DashboardPageIndex extends Vue {
  get bc (): BreadCrumbsItem[] {
    return [{ text: 'Dashboard', to: this.localePath({ name: 'dashboard' }), exact: true }]
  }
}
</script>
```

**Comment by Luferov** [comment]
If use this style, its ok.
```js
<template lang="pug">
  bread-crumbs(:items="bc")
    v-row Dashboard
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { MetaInfo } from 'vue-meta'
import BreadCrumbs from '~/components/BreadCrumbs.vue'
import { BreadCrumbsItem } from '~/types/devind'
import TwoColumns from '~/components/global/TwoColumns.vue'

@Component<DashboardPageIndex>({
  components: { TwoColumns, BreadCrumbs },
  middleware: ['auth'],
  computed: {
    bc (): BreadCrumbsItem[] {
      return [{ text: 'Dashboard', to: this.localePath({ name: 'dashboard' }), exact: true }]
    }
  },
  head (): MetaInfo {
    return { title: 'Dashboard' } as MetaInfo
  }
})
export default class DashboardPageIndex extends Vue { }
</script>
```

**Comment by rchl** [comment]
Since the parsing of pages is a custom code, it only works with basic syntaxes. Even if it's not crashing in your second example, it might not be able to extract `nuxtI18n` options had you defined them. So in your case, I'd suggest disabling `parsePages` and if you need to specify per-page options, use `pages` option in module configuration.

**Comment by darthf1** [comment]
Hi @rchl, I have the same issue, but I think it is introduced by a version change because I have not changed anything to my `nuxtI18n` config for a long time. Also, I get this error 8 times, whilst I have 30+ pages which have the same setup.

I'll try to find out which version update this was.

```
yarn run v1.22.5
$ nuxt-ts build
ℹ Production build
ℹ Bundling for server and client side
ℹ Target: server
✔ Builder initialized
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/aPage.vue".
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/anotherPage.vue".
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/etc.vue".
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/etc.vue". 
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/etc.vue". 
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/etc.vue".
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/etc.vue".
 WARN  [nuxt-i18n] Error parsing "nuxtI18n" component option in file "/usr/src/client/pages/folder/etc.vue".
✔ Nuxt files generated
```

```js
import { Component, Vue } from 'nuxt-property-decorator'

@Component({
  name: 'MyComponent',
  middleware: ['auth', 'project'],
  nuxtI18n: {
    paths: {
      en: '/en/path',
      nl: '/nl/path',
    },
  },
})
export default class MyComponent extends Vue {}
```

`nuxt.config.ts`
```ts
import { NuxtConfig } from '@nuxt/types'

const config: NuxtConfig = {
  modules: [
    [
      'nuxt-i18n',
      {
        defaultLocale: 'nl',
        parsePages: true,
        locales: [
          { code: 'nl', file: 'nl-NL.json' },
          { code: 'en', file: 'en-US.json' },
        ],
        lazy: true,
        langDir: 'translations/',
        seo: false,
      },
    ],
  ],
}

export default config
```

**Comment by leeuwd** [comment]
Same here

![image](https://user-images.githubusercontent.com/1755190/96604705-b18c9500-12f5-11eb-942d-c9a0510a3109.png)

**Comment by rchl** [comment]
Maybe someone has time to figure out in which version exactly it has regressed. It would speed up progress in this issue.

**Comment by xfyre** [comment]
Same issue after upgrading to the latest version (currently it's 6.15.4)

@rchl If that helps, my upgrade was from 6.15.1 to 6.15.4.

P.S. The problem doesn't seem to really affect localization.

**Comment by darthf1** [comment]
Unfortunately downgrading from `6.15.4` to `6.15.1` has no impact. Could it be a dependency?

**Comment by ferleal** [comment]
Also having the same issue, but I detected that some files were not throwing the same warns, so checking them, the only difference was that the files that throws the warns have computed functions.

```ts
  get fullName (): string {
    return `${this.user.firstName} ${this.user.lastName}`
  }
```
hope it helps debug this.

**Comment by darthf1** [comment]
I think this is related to `babel`.

What I did was create a new `Nuxt` project and compared `package.json` and `nuxt.config.ts` of my project to the newly created `Nuxt` project. 

I noticed a lot of `babel/` and `@babel/` going on in my project, both included as packages in `package.json` and also some entries in a custom build config.

I synched the fuiles in my project with the newly created `Nuxt` project, which essentially was deleting all references to `(@)babel`, did a `yarn install`, `yarn upgrade` and a new build. The issues with `nuxt-i18n` disappeared.

**Comment by belvederef** [comment]
Still experiencing this issue. In my case, it happens if I use any external variable/import in the `nuxtI18n` component options. E.g. this works:
```ts
@Component({
  nuxtI18n: {
    locales: ['en'],
  },
})
```
while the code below triggers the error and does not let nuxtI18n apply the in-component options for the page. 
```ts
const myLocales = ['en'];

@Component({
  nuxtI18n: {
    locales: myLocales,
  },
})
```
I was not able to overcome this issue, it's a huge blocker

Edit:
This issue is nastier than I thought. I get the issue even if I try to specify some TS typings. E.g.:
```ts
@Component({
  nuxtI18n: {
    locales: ['en'] as Array<string>,
  },
})
```

**Comment by xinbenlv** [comment]
Having the same issue. Hope it can be prioritized.

**Comment by nachoadjust** [comment]
We get the same error in the same conditions as @belvederef reported. 
Is there any update on this?

**Comment by gaoxu529** [comment]
我也遇到同样的问题，经过排查，是部分组件使用了自定义 render 渲染时，所以出现的问题。

**Comment by HollyCreep** [comment]
I get same error as @belvederef  mentioned.  Any workaround to use variables within o nuxtI18n options ?

![image](https://user-images.githubusercontent.com/49692932/176262361-3cc2377e-cd39-4daf-b90a-a99caa29e3c1.png)
I would like to use this on nuxtI18n options, like i used on head or even an variable to be able to avoid replicated code.

![image](https://user-images.githubusercontent.com/49692932/176264281-d59b283a-61fe-450c-8baa-171d270a5079.png)

**Comment by Luferov** [comment]
I would advise you to use the composition API instead of the basic class style from your project. And this error will go away.

**Comment by HollyCreep** [comment]
Thank you @Luferov  for the reply. I'm running a Vue2 application, its possible to implement your suggestion with a plugin like this [Composition API plugin for Vue 2](https://github.com/vuejs/composition-api) ? 

If possible, would you mind providing us an example? Thank you again in advance!

**Comment by Luferov** [comment]
> Thank you @Luferov for the reply. I'm running a Vue2 application, its possible to implement your suggestion with a plugin like this [Composition API plugin for Vue 2](https://github.com/vuejs/composition-api) ?
> 
> If possible, would you mind providing us an example? Thank you again in advance!

Of course, no problem. We are writing an application and it is open source. We are currently transitioning to nuxt3 and therefore are now in the nuxt-bridge version.
For example, https://github.com/devind-team/dcis/tree/main/client.

**Comment by valh1996** [comment]
> I would advise you to use the composition API instead of the basic class style from your project. And this error will go away.

Hi, what do you mean by `use the composition API`? 
Do you recommend to go through your custom composable every time to make the error disappear? :
https://github.com/devind-team/dcis/blob/main/client/composables/i18n.ts

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
