### ISSUE TITLE
How to use full url instead of parameters

### ISSUE THREAD

**Issue by AugustBurnsRed** [nuxt-modules/i18n#939]
Hi, all my url are generated in my cms. Is there a way to translate the full url instead of using setRouteParams and each params?

My articles url are like: blog/category-name/article-name. It's more complicated to use setRouteParams and pass the category name + article name instead of just using the full url. However i don't see a easy way to do this.

For now i'm thinking about using just a _.vue file. Inside i load the correct page template as a component. In my nuxt config something like:

```
_: {
    "fr": "/:param_1/",
    "en-ca": "/:param_1/", 
 },
_: {
    "fr": "/:param_1/:param_2",
    "en-ca": "/:param_1/param_2", 
 },
_: {
    "fr": "/:param_1/:param_2/:param_3",
    "en-ca": "/:param_1/param_2/:param_3", 
 },

```

And a function to explode my url from the CMS to pass them in setRouteParams as slug_1, slug_2...

Is there an easier way to do this. It's seems pretty basic but i can't find how.

Thanks!

**Comment by rchl** [comment]
I'm not sure what problem are you trying to fix.

It seems pretty simple to just create a helper function that will split the URL on `/` and create an object with your chosen keys from it.

I probably wouldn't consider adding more complexity to the module if it's already possible to achieve the expected result with little effort.

**Comment by AugustBurnsRed** [comment]
Yes i could, i was probably just overthinking it. I wanted to find a way to use a complete slug instead of calling an helper function for the 10-20 differents type of routes that i will have.
