### ISSUE TITLE
$route.name with wrong prefix when option differentDomains is in true

### ISSUE THREAD

**Issue by joaquinvexels** [nuxt-modules/i18n#942]
I'm trying to make a site with translation on different subdomains and when I go to another subdomain, in the variable $route.name always get 'page___pt'.

I have been looking at the .nuxt folder and get always the 'PT' language because I put it 'PT' in the last place on the array of locales.

I try it with the option differentDomains on false and work perfectly.

How can I fix this?

Thanks!

**Comment by andorfermichael** [comment]
I can verify this issue, except that for me it always takes the first locale of my locales array.
