### ISSUE TITLE
Cannot get component interpolation to work

### ISSUE THREAD

**Issue by kissu** [nuxt-modules/i18n#945]
So, basically I want to implement component interpolation, but I cannot achieve it.
https://kazupon.github.io/vue-i18n/guide/interpolation.html#slots-syntax-usage

Here is my `nuxt-i18n` config
```js
[
  'nuxt-i18n',
  {
    defaultLocale: ENGLISH_LOCALE,
    detectBrowserLanguage: {
      cookieKey: 'detected_locale',
      fallbackLocale: ENGLISH_LOCALE,
    },
    langDir: 'locales/',
    lazy: true,
    locales: [
      {
        code: ENGLISH_LOCALE,
        file: 'en.json',
        iso: 'en',
      },
      {
        code: 'fr',
        file: 'fr.json',
        iso: 'fr',
      },
    ],
    strategy: 'no_prefix',
    vueI18n: {
      fallbackLocale: ENGLISH_LOCALE,
      silentFallbackWarn: true,
      silentTranslationWarn: true,
    },
    vueI18nLoader: true,
    vuex: {
      syncLocale: true,
      syncMessages: true,
    },
  },
]
```

`vueI18nLoader` is set to `true`.

Here is a screenshot of my whole current `.vue` file:
![image](https://user-images.githubusercontent.com/5133074/97857124-8cd4ec00-1cfd-11eb-9624-5b5469a518bf.png)

This is the final result on my view.
![image](https://user-images.githubusercontent.com/5133074/97856993-60b96b00-1cfd-11eb-8a35-98bf650f0b6b.png)

Some key points:
- the first `div` is not working totally because the json key is missing the param `email` (totally fine here !)
here is a truncated view of my `en.json`
```json
{
  "dashboard": {
    "sidebar": {
      "needHelp": {
        "contactUsMail": "Feel free to contact us : {email}"
      }
    }
  },
  "common": {
    "dummyEmail": "contact@dummy.io"
  }
}
```
- the second `div` is basically just showing that the path for the mail is good
- the third `div` is showing us that we can display all the content when passing the whole object as inline translation (it's too limited in my wished use-case)
- I do have a total access to the translations located thanks to `<i18n>` aka with `clown` key here, hence it's working
- I've tried installing `@intlify/vue-i18n-loader` also, but nothing works any better
- I'm using i18n Ally to help me, so I also know that everything is wired properly here, as shown in the result ^^

So, this is the only part that does not work although, it should when seeing the above. Did I miss something basic here ? 
```js
<i18n :path="$t('dashboard.sidebar.needHelp.contactUsMail')" tag="p">
  <template #email>{{ $t('common.dummyEmail') }}</template>
</i18n>
```

PS: The syntax highlight may look bad but it's basically just ESlint that does not like the formatting of lines 41-45. It can look better when not formatted but it's still working perfectly great, having that thing for a long time already.

I've stumbled upon this [issue's comment](https://github.com/nuxt-community/i18n-module/issues/58#issuecomment-378349781) but I'm not sure that it's related, it's pretty old and still it didn't work on my side.

So yeah, that's basically it tell me if you need more details on my issue. Thanks for reading. 😸

**Comment by rchl** [comment]
You are using `$t` "too much". You are not supposed to use it within `v-t` or `<i18n` component.

For example:

```vue
<i18n path="dashboard.sidebar.needHelp.contactUsMail" tag="p">
  <span slot="email">{{ $t('common.dummyEmail') }}</span>
</i18n>
```

And here are examples of how to use locales with placeholders in `v-t` directive: http://kazupon.github.io/vue-i18n/api/#v-t

**Comment by kissu** [comment]
Oops, just realized that one indeed. Thanks for the tip ! 👍🏻 

Oh and it's working perfectly now, thank you veeery much. ❤️
