### ISSUE TITLE
How can I remove the query parameters from the hreflang?

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-modules/i18n#953]
How can I remove the query parameters from the reflang URL?

**Comment by rchl** [comment]
Do you mean `hreflang` (https://i18n.nuxtjs.org/seo#automatic-hreflang-generation)?

It doesn't seem like you can currently. It generates those URLs the same way as when generating URLs for switching locales.

What's the reason you don't want to include them?

**Comment by simplenotezy** [comment]
Thanks for a promt reply @rchl  😊 

Because we currently use ?page=2 for an infinite product list, and we generate our site in static mode.

So I don't want the canonical/reflang URLs to point to ?page=2, since the HTML that the client would receive, would be the same as ?page=1

**Comment by rchl** [comment]
`canonical` already doesn't include query params.

To be able to exclude specific query params there would need to be a new feature implemented.

**Comment by manullah** [comment]
Sorry, i want to ask. 
Is possible i remove query params in hreflang that generates from i18n?

**Comment by rchl** [comment]
No, as stated above

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
