### ISSUE TITLE
Validate JSON before build.

### ISSUE THREAD

**Issue by snakemastr** [nuxt-modules/i18n#954]
Running a nuxt application with i18n, I have a .json file for my translations.
The file is being edited by non-tech colleagues directly through bitbucket (for speed and/or lazyness ofc).

When the JSON is invalid (due to trailing comma's or dot's, wrong formatting), the nuxt build issues a warning but keeps on building and is being deployed. The translation is obviously unresolved so it looks a mess. Is it possible to validate the JSON in the build process and abort when invalid? I'd like to prevent deployment of the mess :)

**Comment by rchl** [comment]
You can configure your commit hooks to validate your JSON files. It doesn't have to have anything to do with this module.

It could be just a simple script that just tries to `JSON.parse` your files or look for something else on npm.

**Comment by snakemastr** [comment]
Thank you, I will find a solution in that direction.
