### ISSUE TITLE
Constructor Vue-i18n postTranslation not working

### ISSUE THREAD

**Issue by snakemastr** [nuxt-modules/i18n#957]
Running nuxt-i18n @ 6.15.4 (vue-i18n v8.22.1 postTranslation supported)
I would like to use postTranslation handler in vue-i18n

When I define the handler in config as constructor option, it won't work.
Config snippet:
```['nuxt-i18n', {
      vueI18n: {
        postTranslation: str => str.toUpperCase()
      }
}],```

But defining it in a plugin it does work.
Plugin snippet:
```export default function ({app}) {
  app.i18n.postTranslation = function (str, key) {
    return str.toUpperCase()
  }
}```

I came across this problem because I initially used the plugin but I'm having issues with postTranslation being called too late so I thought the plugin was different from the constructor option.

**Comment by rchl** [comment]
See the documentation of the `vueI18n` option here: https://i18n.nuxtjs.org/options-reference#vuei18n

You can (and should in this case) set the value to a path to the script.
