### ISSUE TITLE
trailingSlash not working as expected

### ISSUE THREAD

**Issue by rrmesquita** [nuxt-modules/i18n#970]
AFAIK when you don't set the `trailingSlash` setting in Nuxt, both options work (`domain.com/foo` AND `domain.com/foo/`). And I might have misinterpreted the documentation, but I think the following assumption is wrong:

https://github.com/nuxt-community/i18n-module/blob/f3679268053c8ed83b10979440ff12d1e123bf2e/src/helpers/routes.js#L126

So, because of that, `domain.com/en` (with `prefix` strategy) will result in the browser redirect the user to `domain.com/en/en` while `domain.com/en/` will work nicely.

Does anyone know a workaround until this gets fixed?

**Comment by rchl** [comment]
Please provide a repro project demonstrating the issue. It looks to work in https://codesandbox.io/s/nuxt-nuxt-i18n-trailing-slash-issue-970-rfenk?file=/nuxt.config.js

**Comment by rrmesquita** [comment]
@rchl I'll take a deep look at it, thanks !

**Comment by rrmesquita** [comment]
@rchl on that very same example you provided, change the page `index.vue` to `_.vue` and you will know what I'm talking about.

**Comment by rrmesquita** [comment]
@rchl so far, changing my `_.vue` to `_route.vue` (it can be any name in my case), made some progress, now I'm not getting duplicated locale codes anymore when visiting `/` route.

**Comment by rrmesquita** [comment]
I'm closing this issue as its title has nothing to do with my actual problem.

**Comment by rchl** [comment]
It's an interesting case and it would be worth to have a bug report for it (even those I can't immediately see how to fix that).

These are the router paths that get generated for respective page names:

page name | generated path |
----------- | ----------------|
index.vue    | /en | /fr |
_.vue           | /en/* |
_route.vue  | /en/:route? |

For the `_.vue` case, vue-router can't resolve or navigate to the path `/en`. It works for other cases.
