### ISSUE TITLE
Good config for en-US and en-GB

### ISSUE THREAD

**Issue by jb-thery** [nuxt-modules/i18n#972]
Hello

If I whant to have **en-US** and **en-GB** can I use **enus** and **en** codes in my i18n config ?

example:
```
locales: [
      {
        code: 'enus',
        iso: 'en-US',
        file: 'en-US.js',
      },
      {
        code: 'en',
        iso: 'en-GB',
        file: 'en-GB.js',
      }
    ],
```

**Comment by rchl** [comment]
I don't recall if there are any assumptions about it being two-letter only. I guess you should just try and see if there any issues. ;)

"enus" sounds a bit bad to me as it is very close to another word like that that starts with "a". Can't you just use "us" code for the "en-US" locale?

**Comment by jb-thery** [comment]
great it's better with us, I just hope it doesn't break anything
