### ISSUE TITLE
Browser language detection problem if no exact match

### ISSUE THREAD

**Issue by AugustBurnsRed** [nuxt-modules/i18n#979]
### Version
nuxt-i18n: 6.15.4
nuxt: 2.14.6

### Nuxt configuration
 - [x] universal
 - [] spa

### Nuxt-i18n configuration
```
i18n: {
    detectBrowserLanguage: {
      useCookie: false,
      onlyOnRoot: true,
    },
    loadLanguagesAsync: true,
    locales: [
      {
        code: "fr-ca",
        file: "fr.js",
        iso: "fr-CA"
      },
      {
        code: "en-ca",
        file: "en-ca.js",
        iso: "en-CA"
      },
      {
        code: "en-us",
        file: "en-us.js",
        iso: "en-US"
      }
    ],
    lazy: true,
    langDir: "lang/",
    seo: false,
    strategy: 'prefix',
    parsePages: false,
}
```

### Steps to reproduce

- Use detectBrowserLanguage with a fr-ca locale.
- Set Chrome to fr-fr.
- Visit the root of your site.

### What is Expected?

- You should be redirected to fr-ca because in the doc: "If there is no exact match for the full locale, the language code (letters before -) are matched against configured locales (for backward-compatibility)."

### What is actually happening?

- There is no redirect. However if you change your Chrome locale to fr-ca it's now working because there is an exact match with the browser local.

Thanks!

**Comment by rchl** [comment]
Will be fixed by #965
