### ISSUE TITLE
Store a map for customized paths

### ISSUE THREAD

**Issue by rchl** [nuxt-modules/i18n#984]
### Is your feature request related to a problem? Please describe.

To solve issues like #641, #710, #735, #1254 and #1177, we would need to create and expose a list of customized paths. The knowledge of which paths are customized would allow short-cutting some cases or handle them in a special way.

### Describe the solution you'd like

Internally there should be a list of customized paths in a format that is quick to look up and be as compact as possible, size-wise.

### Describe alternatives you've considered

No alternative.

### Additional context

This concerns the `pages` option and custom component options specified through the `nuxtI18n` option.

**Comment by divine** [comment]
Hello,

@rchl is using something like [flexsearch](https://github.com/nextapps-de/flexsearch#store) would be the best solution to store/search paths?

Thanks!

**Comment by rchl** [comment]
At first sight it doesn't seem to be super fitting as I don't think we'll need full text capabilities like that here. We just need to be able to lookup route.name => route.path and route.path => route.name. At least as far as I remember this issue...

**Comment by divine** [comment]
> At first sight it doesn't seem to be super fitting as I don't think we'll need full text capabilities like that here. 

There is a light version as well which is stripped down version (flexsearch.light.js 2.9 kb)

> We just need to be able to lookup route.name => route.path and route.path => route.name. At least as far as I remember this issue...

And custom settings for that route as well (in component option).

Thanks!

**Comment by rchl** [comment]
#1254 concerns dynamic routes. Would need to investigate how would that have to be handled even when having a mapping of sorts.

**Comment by divine** [comment]
@rchl I'd gladly help but not sure where to start and what needs to be done. Can you give you some ideas?

I will try my best.

Thanks!

**Comment by rchl** [comment]
I've started working on it on the https://github.com/nuxt-community/i18n-module/commits/fix/no-prefix-rename branch but I remember leaving it in a pretty unfinished state.

I think there is quite a lot left to do but I won't give you any pointers as I don't remember much now. I'm not even sure if the approach I was experimenting with is even good and would solve all the issues...

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
