### ISSUE TITLE
Import the i18n plugin for composition api

### ISSUE THREAD

**Issue by bissolli** [nuxt-modules/i18n#986]
Is there a way to import the translator method to use with composition API? I actually don't want to get it from the root or from nuxt context, I would like to do something like:

```javascript
import { useI18n } form "@nuxtjs/i18n"

export default {
   setup() {
      const { t } = useI18n();

      return {
          t
      }
   }
}
```

The reason is that I would like to keep things the more clear and decoupled possible! And I am also mocking the nuxtContext for my tests are quite annoying! Would be much simpler mocking the plugin i18n itself.

**Comment by rchl** [comment]
The composition API in general has to be implemented.
I've created a general feature request now at https://github.com/nuxt-community/i18n-module/issues/987

**Comment by rchl** [comment]
Duplicate of #987

**Comment by giuliano-oliveira** [comment]
@rchl still a problem specific for i18n, sure a lot of composables are supported, but i18n is still not
