### ISSUE TITLE
Implement composition API

### ISSUE THREAD

**Issue by rchl** [nuxt-modules/i18n#987]
### Is your feature request related to a problem? Please describe.

Add a native composition API for use with Vue 3.

Some more info at https://dev.to/alvarosaburido/how-to-migrate-your-library-from-vue2-to-vue3-1h81

**Comment by philipdanielhayton** [comment]
Hola guys, any news on this? Or any work around for the short term?

What's the best way to access methods such as localePath inside the setup method currently?

**Comment by rchl** [comment]
See https://github.com/nuxt-community/composition-api/issues/425#issuecomment-813102698

**Comment by DamianGlowala** [comment]
@rchl any ideas on how to get a translated string inside `setup()` (when using an `<i18n>` custom block)? Everything comes back as a raw translation path... totally lost on this. Anything I am doing incorrectly in the below example? I am using Nuxt 2 with Composition API.

```
<i18n>
{
  "en": {
    "exampleString": "Test"
  }
}
</i18n>

...

setup() {
  const { i18n } = useContext();
  
  console.log(i18n.t("exampleString"));
}
```

Is this related to [https://github.com/nuxt-community/i18n-module/pull/1333](https://github.com/nuxt-community/i18n-module/pull/1333)? May I ask why this PR is still a draft?

**UPDATE**
I made a Nuxt composable by copying the `useI18n()` function from the [https://github.com/nuxt-community/i18n-module/pull/1333](https://github.com/nuxt-community/i18n-module/pull/1333). Works perfectly as a workaround ;)

**Comment by thisismydesign** [comment]
On nuxt 2 bridge:

```html
<script setup lang="ts">

const { $i18n } = useNuxtApp()
$i18n.t('key')

</script>
```

**Comment by MatthD** [comment]
@thisismydesign  is this suppose to work ?
