### ISSUE TITLE
BrowserDetection & respect locale in url on first visit

### ISSUE THREAD

**Issue by annablgkv** [nuxt-modules/i18n#990]
I am trying to achieve this behavior:
1. If there is locale in url, then use it (for example, localhost:3000/pt)
2. If there is no locale in url, then use one that is in cookie (just localhost:3000/)
3. If there is neither locale in url, nor in cookie then try to detect browser language and use it
4. If there is no such translation that matches the browser language, then use default one
For now I use config:
```
strategy: 'prefix',
defaultLocale: 'en',
detectBrowserLanguage: {
    fallbackLocale: 'en',
    onlyOnRoot: true,
 }
```
and this works as listed, but only on index.
When onlyOnRoot is disabled, there is no cookie and I want to open url with locale, for example, localhost:3000/de/feedback, browser detection triggers and redirects me to /fr/feedback (fr is browser language). 
(It also redirects to fr/feedback if there is no cookie and I typed just localhost:3000/feedback, which is ok.)
But how can I disable redirect to browser lang if there was suitable locale in url? Is it possible to do what I described?

**Comment by divine** [comment]
Hello,

This has been fixed in https://github.com/nuxt-community/i18n-module/pull/896 but still not released.

Could you please try master version and see if everything works as expected for you?

Thanks!

**Comment by rchl** [comment]
I'm not sure if this part would work, even on master.

> If there is no locale in url, then use one that is in cookie (just localhost:3000/)

**Comment by divine** [comment]
> I'm not sure if this part would work, even on master.
> 
> > If there is no locale in url, then use one that is in cookie (just localhost:3000/)

@annablgkv probably disabled `onlyOnRoot` option because it overrides and redirects locale that is already in URL path.

New option `onlyOnNoPrefix` should make it work as expected on root path as its similar to `onlyOnRoot`?

Thanks!

**Comment by divine** [comment]
@rchl I've just checked it up. It will detect cookie and is working as expected.

https://github.com/nuxt-community/i18n-module/blob/d5957d057c819049c9d73a526fb6752c428a67c6/src/templates/plugin.main.js#L199-L203
`route.path.match(getLocalesRegex(localeCodes))` returns null because:

`route.path` value is `/`
`getLocalesRegex(localeCodes)` value is `/^/(en|ru)(?:/|$)/i`

Thanks!
